### ISSUE TITLE
Pelican logo

### ISSUE THREAD

**Issue by russkel** [getpelican/pelican#1008]
If some talented individual could cook up a vector logo (SVG) for pelican users and their themes, we could proudly show a "Generated by Pelican" icon. :bird:

Just an idea, perhaps something like http://openclipart.org/detail/26579/pelican-with-fish-by-johnny_automatic

**Comment by hyperking** [comment]
I have developed a flat file cms called "pygmy". I will most likely use my third option if it's been decided that it will not be used as the pelican logo.

**Comment by ametaireau** [comment]
Option #2 from https://github.com/getpelican/pelican/issues/1008#issuecomment-54472158 is probably the best fit to me.

I think we should make a call and decide! @hyperking @justinmayer and others, would that be okay for you?

**Comment by hyperking** [comment]
@ametaireau and @justinmayer As long as I can make the final refinements to option #2 I am okay with that.

If color is to be added let me know. Cheers

**Comment by dbrgn** [comment]
+1 for deciding :)

**Comment by ametaireau** [comment]
I would like to have at least @avaris and @justinmayer votes on this one. Next step, once we agree, is to put the logo on the documentation I believe.

**Comment by avaris** [comment]
@ametaireau, I do like the #2 as well. Simple and elegant.

**Comment by justinmayer** [comment]
As I [mentioned before](https://github.com/getpelican/pelican/issues/1008#issuecomment-26335520) (WOW — two years ago!), I like the simple black silhouette the most. That said, if Derry is open to refining the shape on [option 2](https://github.com/getpelican/pelican/issues/1008#issuecomment-54472158) to more closely resemble the contours of a pelican's head and bill, then I'm sure that would be a fine choice as well. (^_^)

**Comment by hyperking** [comment]
@justinmayer I am open to all consideration moving forward.

Since the bird is in flight, I would rather use this head silhouette ( repo image )

https://github.com/getpelican/pelican/issues/1008#issuecomment-22556443

is that doable?

**Comment by justinmayer** [comment]
@hyperking. Yes, that seems okay to me.

**Comment by hyperking** [comment]
@justinmayer Cool. I have been away on other assignments. I will work on another draft.
Anyone else with color suggestions let me know. 

Cheers!

**Comment by justinmayer** [comment]
Sounds great. If it's ready by next weekend (10th), I'll show it off on my slides at my PyCon Japan talk.  (^_^)

**Comment by hyperking** [comment]
:+1: ( rolling up sleeves ) it's go time!

**Comment by hyperking** [comment]
@justinmayer here is a revised draft. any thoughts?
![pelicanupdated](https://cloud.githubusercontent.com/assets/1525894/10299652/8d0fab46-6bba-11e5-8bae-55cc157bb5d0.jpg)

**Comment by hyperking** [comment]
@justinmayer anyway to provide feedback on the revised logo?
[Revised Logo](https://github.com/getpelican/pelican/issues/1008#issuecomment-145734271)

I was affected by the recent flooding in the US. Im dedicated to getting this work to you before the Oct. 10th.

Per colors Im imagining something inline with the "sea and air"

[sea colors](https://color.adobe.com/sea-green-fade-color-theme-6793864/)

[python colors + sea](https://color.adobe.com/Under-the-Sea-color-theme-6983895/)

any thoughts on this as well??

**Comment by justinmayer** [comment]
Looks great to me. I like the sea color scheme as well. Nicely done. Looking forward to seeing the colorized version!

**Comment by hyperking** [comment]
@justinmayer  Thanks!.

Here are some color auditions. I also refined an icon version to be more rounded which increases line fidelity when scaling down.


![image](https://cloud.githubusercontent.com/assets/1525894/10340463/1dd286e8-6cde-11e5-8793-10b044303634.png)

**Comment by hyperking** [comment]
@justinmayer Hey feedback with the color drafts? I have other projects warranting my attention.
i may have delay in my responses. 

Thanks

**Comment by justinmayer** [comment]
Nice! They look great. I think I'd go with the first one with the circle around it.

**Comment by hyperking** [comment]
@justinmayer Cool! glad to see this issue finally resolved.

To everyone else here is a dropbox link to download png images of the logo.
[final Pelican Logo](https://www.dropbox.com/sh/3kroddwrbfq7z4j/AAA51lxDYD1769-fQ1SbAsXMa?dl=0)

Cheers to everyone contributing to such great software.

**Comment by gntech** [comment]
What is the licence for the logos? Can i for example download them for use in a blog post about pelican?

**Comment by hyperking** [comment]
@gntech I think that would be fine with me. 
sure to note my name as logo designer would be nice. :-) similar to [Alex Jf](http://www.alexjf.net/blog/site/website-ported-to-pelican/)

**Comment by gntech** [comment]
@hyperking Thank you for this great contribution to the pelican project! :)
Now the blog post is up at http://www.gntech.se/posts/pelican-driver-gntechse/ i made a mention of the designer in a footnote.

**Comment by peterrus** [comment]
Any chance we'll see these on the official site/docs. I really like what you people have come up with! Would be a shame not to use it.

**Comment by leotrs** [comment]
@justinmayer did the official logo ever get used.. officially?

**Comment by justinmayer** [comment]
@leotrs: Yes, as can be seen here: https://twitter.com/getpelican

As part of the next release (whenever that happens), I agree that incorporating the logo into the site and docs would be great.

**Comment by leotrs** [comment]
Looking great.

**Comment by Juanlu001** [comment]
Looking forward to the next release then :)

**Comment by silverhook** [comment]
Was this logo ever officially adopted? And if so, under which license is it?

**Comment by ivanhercaz** [comment]
So I understand for the last comments in this thread that the proposed logos made by @hyperking are the ones chosen to represent Pelican. I am working in a theme in which I am going to design a logo. I want to be sure of the license of the logos. I know Hyperking said:

> @gntech I think that would be fine with me. sure to note my name as logo designer would be nice. :-) similar to Alex Jf

But I like to specify the licenses of everything I used to make it easy to share in the same conditions (or clarify if it can be shared/reused in another way).

cc. @justinmayer, as the one assigned to this issue.

**Comment by justinmayer** [comment]
Logo license type: https://creativecommons.org/licenses/by/4.0/

**Comment by ivanhercaz** [comment]
> Logo license type: https://creativecommons.org/licenses/by/4.0/

Nice! Thank you @justinmayer :). I think the should be easier to find, it could be documented in the official blog of Pelican. If I can help with something, I can try to help with some task :).

**Comment by justinmayer** [comment]
It’s already listed on the getpelican.com site.

**Comment by ivanhercaz** [comment]
Oh! Excuse me, I didn't visit the [Colophon](https://blog.getpelican.com/pages/colophon.html) before to ask. Thank you very much again!

**Comment by justinmayer** [comment]
Once again, many sincere thanks to @hyperking for all his hard work on the Pelican logo. It's truly splendid artwork and a boon to the project.
