### ISSUE TITLE
SCSS/Compass files with Pelican

### ISSUE THREAD

**Issue by jminardi** [getpelican/pelican#1012]
I recently started using pelican to build my personal site. I am using the [mnmlist](https://github.com/getpelican/pelican-themes/tree/master/mnmlist) theme from the pelican-themes repo. I wanted to make some style changes and I noticed the theme uses [Compass](http://compass-style.org/) to compile it's css. Is there an easy/correct way to include the compass compilation in in the pelican build? Is there a plugin to do this? Is this a candidate for a plugin?

On a more general note, what is the difference between compass, sass, and scss?

**Comment by atoohill** [comment]
Hey @justinmayer , what specific pelican plugin are you referencing?

**Comment by justinmayer** [comment]
@atoohill: Comment above updated to specifically refer to the `assets` plugin.

**Comment by atoohill** [comment]
Thanks @justinmayer , appreciate the clarification.  We assumed it was that one but the webassets documentation seems a little unclear on how to include compass still in our pelican project.  Do you know of any documentation that would be helpful for us to review?  Appreciate your time to help point us in the right direction.  Currently, we're having to manually import all the compass .scss files into the project and it adds alot of extra time to the compilation and we're thinking there should be a faster way of doing this but we just haven't gotten it yet.  Thanks!

**Comment by justinmayer** [comment]
I haven't used it, so I don't have any suggestions other than [reading the docs](https://github.com/getpelican/pelican-plugins/tree/master/assets) and perhaps reaching out to folks via the `#pelican` IRC channel.

**Comment by atoohill** [comment]
Thanks Justin.  Where is the #pelican IRC channel located? Probably obvious but I just don't see it.  Thanks.

**Comment by justinmayer** [comment]
Pelican Docs: [How to Get Help](http://docs.getpelican.com/en/latest/contribute.html#how-to-get-help)
