### ISSUE TITLE
Add support for hierarchical (multi-level) menu items with user defined order

### ISSUE THREAD

**Issue by ssbarnea** [getpelican/pelican#1037]
While do find pelican extremly usefull, I was surprised to discover that there is no support for hierarchical menu items. So far the only current option is it create them as part of the theme which is not a good practice.

**Comment by dkalisch** [comment]
This is something that I am looking for. However, the suggested method doesn't work for me. Is there something one need to set up besides adding `Order: parent` and `Order: slug_name_of_parent` in the .md and . rst files?
