### ISSUE TITLE
Ability to symlink or hardlink copied output static files if possible

### ISSUE THREAD

**Issue by ssbarnea** [getpelican/pelican#1042]
Pelican should be able to create hard links for files that are just copied. This would improve the development environment experience and also to speed of site generation.

I could implement this but first I want to know others opinion and if this should be enabled by default or just by a config option.

**Comment by leotrs** [comment]
My site is being generated with a symlink being copied correctly. Was there work put into this, or am I seeing a bug? (Or maybe I'm just wrong.)

**Comment by Lucas-C** [comment]
I think this has been implemented in https://github.com/getpelican/pelican/pull/1982

**Comment by justinmayer** [comment]
Presumably implemented in above-referenced issue. Thanks, @Lucas-C. 👍
