### ISSUE TITLE
Copying HTML files to output without processing them

### ISSUE THREAD

**Issue by liyanage** [getpelican/pelican#1046]
The documentation for FILES_TO_COPY says directories are allowed:

> A list of files (or directories) to copy

But when I try it, it errors out at that point:

    CRITICAL: (21, 'Is a directory')
    CRITICAL: [Errno 21] Is a directory: u'/Users/liyanage/Documents/websites/foo.com-pelican/content/software/bar/'

**Comment by MartinThoma** [comment]
I think I might have the same problem: http://stackoverflow.com/q/37104625/562769 - can anybody solve it?

**Comment by Scheirle** [comment]
@MartinThoma move your `html5` folder in your `content` folder (symlink works too) and only use `STATIC_PATHS = [..., 'html5']`

**Comment by MartinThoma** [comment]
@Scheirle I tried it and I got

    ERROR: Skipping html5/regression/regression.htm: could not find information about 'NameError: date'
    ERROR: Skipping html5/regression/README.md: could not find information about 'NameError: title'

**Comment by Scheirle** [comment]
@MartinThoma use `ARTICLE_EXCLUDES` and maybe `PAGE_EXCLUDES` to exclude the `html5` folder. 

Alternatively move all your articles in a sub folder and use `ARTICLE_PATHS`, so pelican only looks in the given folder for articles.

**Comment by leotrs** [comment]
This is solved by setting both `STATIC_PATHS` and `PAGE/ARTICLE_EXCLUDES` at the same time.

I admit it's annoying, but at least this is no longer an issue.

**Comment by justinmayer** [comment]
I'm sure this use case could be handled better, but there are at least avenues to achieve the desired result. Follow-up enhancements are of course welcome.

**Comment by mattgilbertnet** [comment]
Just ran into this issue. The fix in this thread worked, but I would think any static paths would be excluded (from pages and articles processing) by default. Being static and all.

**Comment by avaris** [comment]
@matrixise [not necessarily](http://docs.getpelican.com/en/stable/content.html#mixed-content-in-the-same-directory)
