### ISSUE TITLE
Split SITEURL into its three separate components

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1054]
I have long believed that we should split the SITEURL setting into its three components:
- the protocol (e.g., http://, https:// or //)
- the domain (e.g., example.com)
- the prefix, if any (e.g., /blog/)

At present, all three are combined into a single SITEURL variable, and I think they should be decoupled. The same could possibly be said of the FEED_DOMAIN setting.

Splitting these into separate components would allow for more flexibility and fewer problems with feeds and protocol-independent URL schemes.

**Comment by patdavid** [comment]
I'm coming here from https://github.com/getpelican/pelican/pull/1052 where I believe I was looking for similar results to the OP there, that is:

1. Be able to use a protocol-less domain on the main site for SITEURL (//www.gimp.org).
2. Be able to re-direct the RSS writer to prepend all feed entry <link>'s to use a separate, protocol domain (https://www.gimp.org/...)

Right now, changing FEED_DOMAIN only changes the rel="self" <link>:

```
<feed xmlns="http://www.w3.org/2005/Atom">
<title>GIMP</title>
<link href="//www.gimp.org/" rel="alternate"/>
<link href="https://www.gimp.org/feeds/atom.xml" rel="self"/>
<id>//www.gimp.org/</id>
<updated>2016-05-23T00:00:00+02:00</updated>
<entry>
<title>Call for GIMP 2.10 Documentation Update</title>
<link href="//www.gimp.org/news/2016/05/23/gimp-2-10-docs-update-call/" rel="alternate"/>
```

All of the other <link>'s still use SITEURL.  I see from the previous issue that it was closed as this was not desired behavior.

So, is there a work-around or solution to the question?  Can I have the prepended domain for <link> elements to the entries in the XML file be different than the SITEURL?

**Comment by justinmayer** [comment]
After further reflection, I agree with @gpoo's [comment](https://github.com/getpelican/pelican/issues/1054#issuecomment-27530105) that this can be handled via `urlparse` and does not require separate settings.
