### ISSUE TITLE
How to use code-block directive in Markdown?

### ISSUE THREAD

**Issue by calfzhou** [getpelican/pelican#1098]
In Pelican document, the paragraph [Syntax highlighting](http://docs.getpelican.com/en/3.3.0/getting_started.html#syntax-highlighting) presents a lot of useful directives for reStructuredText, such as `linenos`, `hl_lines`. But I cannot find any words talking about how to use them in Markdown. Maybe you don't like Markdown as much as reStructuredText, but I really hope that all features supported by reStructuredText have corresponding alternatives in Markdown.

**Comment by matousu** [comment]
Regarding reST vs Markdown in Pelican ... is there a fully working alternative for .. directive in Markdown? Thanks a lot.
