### ISSUE TITLE
No way to specify multiple paths in EXTRA_PATH_METADATA

### ISSUE THREAD

**Issue by gpoo** [getpelican/pelican#1104]
In 3.2 I could set a common file to use in multiple directories, for example:

    FILES_TO_COPY = (
                   ('extra/htaccess-feed', 'feed/.htaccess'),
                   ('extra/htaccess-NoIndexes', 'theme/.htaccess'),
                   ('extra/htaccess-NoIndexes', 'drafts/.htaccess')
    )

However, 3.3 `FILES_TO_COPY` does not work and must be migrated to something like:

    STATIC_PATHS = [
          'extra/htaccess-feed',
          'extra/htaccess-NoIndexes'
    ]

    EXTRA_PATH_METADATA = {
          'extra/htaccess-feed': {'path': 'feed/.htaccess'},
          'extra/htaccess-NoIndexes': {'path': 'theme/.htaccess'},
          ???
    }

The last item in `FILES_TO_COPY` cannot be added because it will overwrite the path of the previous item.  Also, the key (`'path'`) does not seem to work with a dictionary like in:

    ...: {'path': {'theme/.htaccess', 'drafts/.htaccess'}

Neither regular expressions:

    ...: {'path': r'(theme|drafts)/.htaccess'}

The work-around is to copy the extra file as many times as needed (or use symlinks). But this seems suboptimal.

**Comment by leotrs** [comment]
Having a one-to-one relationship from `STATIC_PATHS` to `OUTPUT_PATH` is more obvious to me, and seems more in line with a static site generator. The way pelican knows where I want my output files is to mirror the contents of the content directory. Instructing it to copy one file in multiple locations goes against that principle.

**Comment by justinmayer** [comment]
If someone would like to implement this feature, please comment here and I will re-open this issue.
