### ISSUE TITLE
Author pages still generated when disabled

### ISSUE THREAD

**Issue by aqw** [getpelican/pelican#1106]
Following the documentation (http://docs.getpelican.com/en/latest/settings.html), I have the following set in pelicanconf.py:

AUTHORS_SAVE_AS = False

Yet, despite running `make clean`, <author_name>.html files are generated with content.

At least two other settings show similar behavior:

"TAGS_SAVE_AS = False" still generates tags files, but they're empty.
"CATEGORY_SAVE_AS = False" still generates categories.html, but it's empty.

I am running Pelican 3.2.2 on Debian jessie.

---Alex

**Comment by therealmaxmoon** [comment]
I still have problems with not generating author, tags and category pages. I have this in my config:

```
AUTHOR_SAVE_AS = None
TAG_SAVE_AS = None
CATEGORY_SAVE_AS = None
```

After I execute `pelican --autoreload --listen -D` I get the following:
```
WARNING: TAG_SAVE_AS is set to None
WARNING: Caught exception "TypeError: join() argument must be str or bytes, not 'NoneType'". Reloading.
CRITICAL: TypeError: join() argument must be str or bytes, not 'NoneType'
```

Using Pelican 4.2.0

**Comment by justinmayer** [comment]
That's because this issue is seven years old and no longer relevant. Instead of `None`, set to an empty string (`""`), as is already mentioned in a blue-colored note at the end of the [URL settings docs](https://docs.getpelican.com/en/stable/settings.html#url-settings).
