### ISSUE TITLE
No valid files in content after clean install

### ISSUE THREAD

**Issue by karlcow** [getpelican/pelican#1135]
1. Install Mac OS X 10.9 (get a wipe out of site-packages)
2. sudo pip install pelican (everything is fine)
3. make html
   
   → make html
   [ ! -d /Users/karl/pelican/output ] || find /Users/karl/pelican/output -mindepth 1 -delete pelican /Users/karl/pelican/content -o /Users/karl/pelican/output -s /Users/karl/pelican/pelicanconf.py 
   WARNING: No valid files found in content.
   Done: Processed 0 articles and 0 pages in 0.37 seconds.

The content has not changed. Everything is in place. Previously I was in 3.2 instead of 3.3. The configuration file is still the same. For what is worth, my content is in a dated space. For example.

```
content/2013/10/25/foo.md
```

Not sure what happened :)

**Comment by cknoll** [comment]
@justinmayer 

+1 for better warning. Suggestion: "Make sure you have installed all necessary packages, e.g., markdown. See FAQ for more info."

Such a message would have saved me about 10minutes.

**Comment by jpeacock29** [comment]
+1 for better warning.

For the record, the fix here is just to install the `markdown` python package (eg, `pip install markdown`)
