### ISSUE TITLE
Custom PAGINATION_PATTERNS not working correctly

### ISSUE THREAD

**Issue by calfzhou** [getpelican/pelican#1137]
Pelican v3.3.0 document provides an example setting of PAGINATION_PATTERNS (http://docs.getpelican.com/en/3.3.0/settings.html#using-pagination-patterns), which is:

``` python
PAGINATION_PATTERNS = (
    (1, '{base_name}/', '{base_name}/index.html'),
    (2, '{base_name}/page/{number}/', '{base_name}/page/{number}/index.html'),
)
```

But this configuration will cause a **CIRTICAL** error if there are more than one tags (or categories). The error is:

```
CRITICAL: File <blahblah>/output/tag/index.html is to be overwritten
make: *** [html] Error 1
```

The reason is that for example there are two tags, tagA and tagB. When processing tagA, it will generate `output/tag/index.html`. And for tagB, it will try to generate another `output/tag/index.html`, but this file already exists.

A solution is to add a `{name}` placeholder to the patterns, such as:

``` python
PAGINATION_PATTERNS = (
    (1, '{base_name}/', '{base_name}/{name}/index.html'),
    (2, '{base_name}/page/{number}/', '{base_name}/{name}/page/{number}/index.html'),
)
```

This will not cause any error, but the generate tags (or categories) files are: `output/tag/tag/tagA/index.html` and `output/tag/tag/tagB/index.html`. As you could see, there are two level of `tag` folder. And for posts, their index pages will be saved in `output/index/index.html` and `output/index/page/2/index.html`.

**Comment by veddermatic** [comment]
I agree, having to choose between not having pagination or having "bad" URLs doesn't seem like a good choice.
