### ISSUE TITLE
Is that ok when install pelican with a lot of warning ?

### ISSUE THREAD

**Issue by ioiioi** [getpelican/pelican#1155]
here is my installation log under linux's python virtualenv

```
(pelican)chenrui@E43:~/blog/pelican$ pip install pelican
Downloading/unpacking pelican
  Downloading pelican-3.3.tar.gz (195Kb): 195Kb downloaded
  Running setup.py egg_info for package pelican

Downloading/unpacking feedgenerator>=1.6 (from pelican)
  Downloading feedgenerator-1.7.tar.gz
  Running setup.py egg_info for package feedgenerator

    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking jinja2>=2.7 (from pelican)
  Downloading Jinja2-2.7.1.tar.gz (377Kb): 377Kb downloaded
  Running setup.py egg_info for package jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
Downloading/unpacking pygments (from pelican)
  Downloading Pygments-1.6.tar.gz (1.4Mb): 1.4Mb downloaded
  Running setup.py egg_info for package pygments

Downloading/unpacking docutils (from pelican)
  Downloading docutils-0.11.tar.gz (1.6Mb): 1.6Mb downloaded
  Running setup.py egg_info for package docutils

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
Downloading/unpacking pytz>=0a (from pelican)
  Downloading pytz-2013.8.tar.bz2 (177Kb): 177Kb downloaded
  Running setup.py egg_info for package pytz

    warning: no files found matching '*.pot' under directory 'pytz'
    warning: no previously-included files found matching 'test_zdump.py'
Downloading/unpacking blinker (from pelican)
  Downloading blinker-1.3.tar.gz (91Kb): 91Kb downloaded
  Running setup.py egg_info for package blinker

Downloading/unpacking unidecode (from pelican)
  Downloading Unidecode-0.04.14.tar.gz (200Kb): 200Kb downloaded
  Running setup.py egg_info for package unidecode

Downloading/unpacking six (from pelican)
  Downloading six-1.4.1.tar.gz
  Running setup.py egg_info for package six

Downloading/unpacking markupsafe (from jinja2>=2.7->pelican)
  Downloading MarkupSafe-0.18.tar.gz
  Running setup.py egg_info for package markupsafe

Installing collected packages: pelican, feedgenerator, jinja2, pygments, docutils, pytz, blinker, unidecode, six, markupsafe
  Running setup.py install for pelican

    Installing pelican script to /home/chenrui/blog/pelican/bin
    Installing pelican-import script to /home/chenrui/blog/pelican/bin
    Installing pelican-quickstart script to /home/chenrui/blog/pelican/bin
    Installing pelican-themes script to /home/chenrui/blog/pelican/bin
  Running setup.py install for feedgenerator

    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
  Running setup.py install for jinja2

    warning: no files found matching '*' under directory 'custom_fixers'
    warning: no previously-included files matching '*' found under directory 'docs/_build'
    warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyc' found under directory 'docs'
    warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
    warning: no previously-included files matching '*.pyo' found under directory 'docs'
  Running setup.py install for pygments

    Installing pygmentize script to /home/chenrui/blog/pelican/bin
  Running setup.py install for docutils
    changing mode of build/scripts-2.7/rst2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2s5.py from 644 to 755
    changing mode of build/scripts-2.7/rst2latex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xetex.py from 644 to 755
    changing mode of build/scripts-2.7/rst2man.py from 644 to 755
    changing mode of build/scripts-2.7/rst2xml.py from 644 to 755
    changing mode of build/scripts-2.7/rst2pseudoxml.py from 644 to 755
    changing mode of build/scripts-2.7/rstpep2html.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt.py from 644 to 755
    changing mode of build/scripts-2.7/rst2odt_prepstyles.py from 644 to 755

    warning: no files found matching 'MANIFEST'
    warning: no files found matching '*' under directory 'extras'
    warning: no previously-included files matching '.cvsignore' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*~' found under directory '*'
    warning: no previously-included files matching '.DS_Store' found under directory '*'
    changing mode of /home/chenrui/blog/pelican/bin/rst2odt.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2man.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2html.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2xml.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2odt_prepstyles.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rstpep2html.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2latex.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2pseudoxml.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2xetex.py to 755
    changing mode of /home/chenrui/blog/pelican/bin/rst2s5.py to 755
  Running setup.py install for pytz

    warning: no files found matching '*.pot' under directory 'pytz'
    warning: no previously-included files found matching 'test_zdump.py'
  Running setup.py install for blinker

  Running setup.py install for unidecode

  Running setup.py install for six

  Running setup.py install for markupsafe

    building 'markupsafe._speedups' extension
    gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c markupsafe/_speedups.c -o build/temp.linux-i686-2.7/markupsafe/_speedups.o
    gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro build/temp.linux-i686-2.7/markupsafe/_speedups.o -o build/lib.linux-i686-2.7/markupsafe/_speedups.so
Successfully installed pelican feedgenerator jinja2 pygments docutils pytz blinker unidecode six markupsafe
Cleaning up...
```

there are a lot of warning.

**Comment by dacbarbos** [comment]
Here is my attempt on OS X 10.10.3 - https://dpaste.de/EMyq

**Comment by avaris** [comment]
@dacbarbos Your issue isn't related to the topic but based on the error, looks like you have some bad configuration in your system locale. Check with `locale` command in your terminal. Something is set as `UTF-8` which isn't a valid locale.

**Comment by dacbarbos** [comment]
@avaris `UTF-8` isn't a [valid locale](https://www.gnu.org/savannah-checkouts/gnu/libc/manual/html_node/Locale-Categories.html)? I doubt that. My `LC_CTYPE` was set to [UTF-8](http://stackoverflow.com/questions/5231620/what-does-set-localelc-ctype-c-actually-do). Anyway, I followed [this article](http://www.cyberciti.biz/faq/os-x-terminal-bash-warning-setlocale-lc_ctype-cannot-change-locale/) and after having my `LC_TYPE` value set to `"C"`, I gave it another try. Check [the outcome](https://dpaste.de/R5hL) :(

**Comment by avaris** [comment]
Well, looks like `UTF-8` can be a valid locale on some systems. But this isn't a `pelican` issue. It's coming from `docutils` which actually hits a `python` ["bug"](https://bugs.python.org/issue18378). 

As for your new try, `C` itself usually isn't a utf-8 aware locale and your trademark symbol is causing problems. Use something else, like `en_US.UTF-8` or similar (depending on your system). You can check the available locales with `locale -a`.

**Comment by dacbarbos** [comment]
I agree. Using plain ASCII for my content works fine. I was just trying to highlight the point that for a lesser 'geek type' user it may not be so easy to get started. Anyway, so far I like it. Good work!

**Comment by justinmayer** [comment]
When I install Pelican 3.6.2 in a fresh virtual environment via `pip install --no-use-wheel --no-binary all --no-cache-dir pelican`, I don't see any of the warnings mentioned in the original issue description. I don't know whether that's because Pip 7.x is hiding such warnings now or not, but since I can't currently get any of those warnings to show up, I'm closing this issue.

**Comment by justinmayer** [comment]
Ran `python setup.py develop` on current 3.6.4.dev0 master, and it seems FeedGenerator, Docutils, and Jinja still have these manifest issues in need of correction upstream.

FeedGenerator:

```
warning: no files found matching '*' under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
```

Docutils:

```
warning: no files found matching 'MANIFEST'
warning: no files found matching '*' under directory 'extras'
warning: no previously-included files matching '.cvsignore' found under directory '*'
warning: no previously-included files matching '*.pyc' found under directory '*'
warning: no previously-included files matching '*~' found under directory '*'
warning: no previously-included files matching '.DS_Store' found under directory '*'
```

Jinja:

```
warning: no files found matching 'run-tests.py'
warning: no files found matching '*' under directory 'custom_fixers'
warning: no files found matching '*' under directory 'jinja2/testsuite/res'
warning: no previously-included files matching '*' found under directory 'docs/_build'
warning: no previously-included files matching '*.pyc' found under directory 'jinja2'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
warning: no previously-included files matching '*.pyo' found under directory 'jinja2'
warning: no previously-included files matching '*.pyo' found under directory 'docs'
```

**Comment by justinmayer** [comment]
Update on this issue...

### python-dateutil

Warnings are still present, presumably due to https://github.com/dateutil/dateutil/pull/201. cc: @koobs @pganssle

### docutils

Fixes needed here:
https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/MANIFEST.in

### jinja2

Fixes needed here:
https://github.com/pallets/jinja/blob/master/MANIFEST.in

Would anyone care to assist with submitting pull requests to these repositories so that these spurious warnings can be eliminated? cc: @getpelican/reviewers

**Comment by pganssle** [comment]
@justinmayer I'm not sure I understand the issue. `python-dateutil` does not appear in the pasted list above. What specifically needs to change in `python-dateutil`'s MANIFEST?

**Comment by justinmayer** [comment]
@pganssle: That list above pre-dates the `python-dateutil` change I referenced above. Inside the following snipped output you should see the two warnings:
<details>
    <summary>Selected output from `cd pelican && python setup.py develop`</summary>
<details>
    <summary>Selected output from `cd pelican && python setup.py develop`</summary>
    Processing dependencies for pelican==3.6.4.dev0
    Searching for python-dateutil
    Reading https://pypi.python.org/simple/python-dateutil/
    Downloading https://pypi.python.org/packages/b7/9f/ba2b6aaf27e74df59f31b77d1927d5b037cc79a89cda604071f93d289eaf/python-dateutil-2.5.3.zip#md5=52b3f339f41986c25c3a2247e722db17
    Best match: python-dateutil 2.5.3
    Processing python-dateutil-2.5.3.zip
    Writing /var/folders/r6/6892mkd91zv3szb6gmzfrx800000gn/T/easy_install-2cZRXO/python-dateutil-2.5.3/setup.cfg
    Running python-dateutil-2.5.3/setup.py -q bdist_egg --dist-dir /var/folders/r6/6892mkd91zv3szb6gmzfrx800000gn/T/easy_install-2cZRXO/python-dateutil-2.5.3/egg-dist-tmp-JsqPW8
    warning: no previously-included files matching '__pycache__' found anywhere in distribution
    warning: no previously-included files matching '*.py[co]' found anywhere in distribution
    Copying python_dateutil-2.5.3-py2.7.egg to /Users/jm/virtualenvs/tempenv-774328166501e/lib/python2.7/site-packages
    Adding python-dateutil 2.5.3 to easy-install.pth file
</details>
</details>

**Comment by pganssle** [comment]
@justinmayer The manifest is like that because for whatever reason the `sdist` argument to `setup.py` does not include the tests, but if you are building the source distribution *after* you've run the tests, it will end up including all the random `pyc` and `__pycache__` files that are generated during the test run. I'm not sure why this is generating a warning for you, but it doesn't seem like a problem to me.

**Comment by justinmayer** [comment]
As far as I can tell, there are thankfully no longer any manifest-related warnings when installing Pelican that can be attributed to 3rd-party dependencies. The only remaining warning was in Pelican itself, which I just rectified via d2eb32c9. Happy to close this issue! (again)
