### ISSUE TITLE
Use pelican-quickstart to upgrade an existing blog

### ISSUE THREAD

**Issue by voltagex** [getpelican/pelican#1160]
I have upgraded my system's pelican so that I have the code from https://github.com/getpelican/pelican/pull/958. I now need to upgrade my makefile and develop_server.sh

I realise this won't suit all cases, but would it be possible for pelican-quickstart to take an existing pelicanconf/publishconf into account? That way I don't have to reset my title, config and themes.

**Comment by matrixise** [comment]
@justinmayer I think you can close this bug.

1. ``pelican-quickstart`` is exactly for a ``quickstart`` and not an upgrade of a current website.

2. I don't know how to upgrade a pelican project, because it's mainly markdown and restructured text files.

**Comment by justinmayer** [comment]
As @matrixise has kindly pointed out, there doesn't seem to be much interest in this feature, so I'm closing this issue.

**Comment by moorepants** [comment]
Are there any recommendations for updating the Makefile that is generated from quickstart? I continually upgrade pelican but the Makefile in an existing site languishes. One thing I've noticed is that I now have Makefiles that seem to require CTRL-C to stop a devserver and some that require calling `make stopserver`. I can no longer tell what it is supposed to be, as `make stopserver` doesn't work in some of the website repos.
