### ISSUE TITLE
RSS Generator should use a template

### ISSUE THREAD

**Issue by jsonbecker** [getpelican/pelican#1162]
One of the great things about Pelican is how easy the template system is for creating new posts-types mimicking functionality like Tumblr.

However, many of these changes, either to the article template or creating a new template, are not reflected in the RSS feed. For example, a "link post" should always have the title link to the external source. This is easy enough to add to templates, but the RSS generator only grabs the article attributes and there are no user-accessible options to modify how the article content are displayed.

I think making the RSS generator use a template that's easily modified is a strong solution that could allow for other creative uses.

**Comment by mitchtbaum** [comment]
I believe we can do this simply and effectively with:
1) https://github.com/mitchtbaum/pelican/commit/fa89f262b7133ee359e96b46880997ef35d41d89
2) a simple script to update existing ```Content.template``` lines to append them with ```.html```, since it would no longer be assumed (thank you for explaining this @Avaris), and then all themes will continue working as is
3) https://github.com/getpelican/pelican/issues/1656 to address this change in plugins that use ```get_template```.   (thank you again @Avaris for noticing this one)

**Comment by justinmayer** [comment]
Related: https://github.com/getpelican/pelican-plugins/pull/426

**Comment by mitchtbaum** [comment]
* https://api.drupal.org/api/drupal/core%21modules%21views%21templates%21views-view-rss.html.twig/8
* https://craftcms.com/docs/templating/rss-feed
* https://gist.github.com/bzerangue/1b10c92ff8aef46af522

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.

**Comment by homlett** [comment]
I'm digging up the thread to raise a use case where the templating approach would be great to support RSS media tags as defined here: https://www.rssboard.org/media-rss  
Media tags are needed to turn a classic RSS feed into a feed compatible with podcast subscriptions.

**Comment by egberts** [comment]
> ly and get a post with a TOC, he only can see the TOC and any content at all, just because I can't filter that from the feed.
> And I don't feel confortable with the need to overloading pelican with plugi

sounds to me like one could refocus this Link plugin not to process "FeedGenerator" when in "PageGenerator" mode, no?
