### ISSUE TITLE
`Exception: File /tag/index.html is to be overwritten` just after installed

### ISSUE THREAD

**Issue by soulchainer** [getpelican/pelican#1164]
I use Archlinux.
And create a `virtualenv` for install and use pelican.

``` bash
(soulblog)[soulchainer@hinata] [soulbits] $ (~*3*)~ python --version
Python 3.3.2
```

And follow the docs to install it, with:

``` bash
pip install pelican
pip install markdown
```

Configured it following the docs and get this configuration: https://gist.github.com/3b34a1651b9901d4205d
Added four plugins from pelican-plugins (but this happens also deactivating the plugins) and installed a theme from pelican-themes (same thing).
The actual hierarchy of my test site is (I won't use the automation tools, just `pelican` command):

```
soulbits/
├── content
│   └── extra
│   └── images
│   └── pages
│   └── posts
│       └── 2013
│           └── 20
│               └── test.md 
├── output
└── pelicanconf.py 
```

And when I try to build the site with `pelican -D` I get an
`Exception: File /home/soulchainer/Dev/Proyectos/Web/soulbits/output/tag/index.html is to be overwritten` error. What I'm doing wrong.
I revised the files and the docs many times and I don't know what to do.
Is this a configuration error? Is a bug? Can someone help me, please?
I don't know if this is the appropiate place to ask this. If not, told me about the appropiate site, sorry.

(Debug output: https://gist.github.com/soulchainer/c7e50f148c5dc4fb74d1/raw/32f86b390833e351e0d88aa165dcd9fdc9b4b4c7/tag_overwritten)

**Comment by dimo414** [comment]
I ran into this same error and was able to reproduce it in a clean installation.  It appears to be a conflict with paginated URLs and tags.  In particular, the sample `PAGINATION_PATTERNS` in the [settings docs](http://docs.getpelican.com/en/latest/settings.html#using-pagination-patterns) appears to be broken.

Reproduction steps:

    $ pelican --version
    3.6.0

    $ pelican-quickstart
    ...
    Done. Your new project is available at /tmp/demo

    $ echo "
    PAGINATION_PATTERNS = (
        (1, '{base_name}/', '{base_name}/index.html'),
        (2, '{base_name}/page/{number}/', '{base_name}/page/{number}/index.html'),
    )" >>  pelicanconf.py

    $ cat > content/demo.md <<EOF
    Title: Demo
    Date: 2015-7-17
    Tags: one, two

    Text
    EOF

    $ pelican
    CRITICAL: RuntimeError: File /tmp/demo/output/tag/index.html is to be overwritten

**Comment by avaris** [comment]
@dimo414 #1615
