### ISSUE TITLE
Linking to other articles within metadata fields

### ISSUE THREAD

**Issue by mitchtbaum** [getpelican/pelican#1169]
[Linking to internal content](http://docs.getpelican.com/en/3.1.1/getting_started.html#linking-to-internal-content) currently only works within the body field.  Extending this functionality to metadata would be useful for defining relationships between content.

Take for example a blog with reviews of music albums and their tracks.  Each album article could have information specific to the album, such as release date and cover image.  Then, an article for each track (with fields such as producer, performer, length) would use an album field to link to the albums that contain it.

A related feature would be to add a listing to the album template with the tracks that reference it, so that there are links going in both directions.   This could be useful for the use case defined in https://github.com/getpelican/pelican/issues/1158

**Comment by justinmayer** [comment]
If someone would like to implement this feature, please comment here and I will re-open this issue.
