### ISSUE TITLE
OUTPUT_PATH seems to be ignored

### ISSUE THREAD

**Issue by dghubble** [getpelican/pelican#1171]
Setting

SITEURL = "http://mysite.com/blog"
OUTPUT_PATH = "output/blog/"

seems to result in generated static files always being placed directly within the output directory.

The behavior I would expect is for the static files generated to be located under output/blog/ so that the only contents directly inside the output folder is the nested folder blog containing the generated files.

Other OUTPUT_PATH choices such as OUTPUT_PATH="myoutput/" are similarly ignored.

Pelican 3.3 pip installed
Python 2.7.6
OS X 10.9

**Comment by reider-roque** [comment]
I've just stumbled on the same issue.

The whole Makefile build system that does not respect main settings and introduced duplicate settings feels so lame.
