### ISSUE TITLE
utils.slugify is very slow for non-English words

### ISSUE THREAD

**Issue by calfzhou** [getpelican/pelican#1172]
`utils.slugify` calls `unidecode.unidecode` to convert all words (especially non-English characters) to their ASCII representation. This is very slow. My site have less than 100 posts, and dozens of Chinese tags, it takes 30+ seconds to build the site. If I manually change all tags to English, it takes only 15 seconds.

It might be better to let user disable `unidecode.unidecode` and define custom slugify mapping (from Unicode character to ASCII representation).

**Comment by leotrs** [comment]
@justinmayer #1701 has been merged and states this issue can now be deferred to plugins.

**Comment by justinmayer** [comment]
Ostensibly addressed via 1701.
