### ISSUE TITLE
Support Summary max length for kanji language set

### ISSUE THREAD

**Issue by cwliu** [getpelican/pelican#1180]
In kanji like Chinese characters, any single character is a word, so the summary counting regular expression on Chinese not work well. It actually count sentences not words.     

I did a quick workaround for this issue. However I only cover english and janj. For other latin-1 lanuage. it seems still has problem.

https://github.com/cwliu/pelican/commit/ff11581107b1062883091f3e2a5ae59a1f14c704

**Comment by leotrs** [comment]
@justinmayer maybe have SUMMARY_MAX_LENGTH count number of unicode characters instead of words.

**Comment by justinmayer** [comment]
@leotrs: I think that might be sensible, and if someone would like to implement that, please comment here and I will re-open this issue.
