### ISSUE TITLE
Yet another static files problem

### ISSUE THREAD

**Issue by gamesbrainiac** [getpelican/pelican#1184]
Hi there!

It seems to me that pelican 3.3 had a certain number of issues with static files. The issue, I'm facing right now is with static files inside of .rst files. I initially tried to make my own static blog generator using pelican, but once I failed to do that I went back to the basics, and just cloned the pelican repo.

Now, I went into the pelican samples and built the blog from the same pelican blog, that was made by Alex. So I was inside `pelican/samples/output`, and I ran the following command:

```
pelican -o output -s pelican.conf.py  
```

This generated the output files I wanted, inside the `output` folder. And so, I went inside the output folder, and just ran the following command:

```
python -m SimpleHTTPServer 8000
```

After doing so, I stumbled onto this problem:

![selection_012](https://f.cloud.github.com/assets/3856600/1714070/0bde15a2-619a-11e3-9ad4-632631da101e.png)

As you can see the images are not working. This is the same problem that I faced when confronted with my own blog generation. Would anyone provide some guidance as to what I can do to resolve this problem?

**Comment by egberts** [comment]
So there is no way to keep the images with the article, such that we have the following directory tree:

```
+ content/articles/
    + article_number_one.md
    + article_number_two.rst
    + article_number_three/
        + article_number_three.md
        + article_number_three_image_one.png
        + article_number_three_image_two.png
```
And be able to move all non-generated files (such as PNG images) into their respective output directory (`output/images`)?

**Comment by avaris** [comment]
@egberts possibly with a plugin. In a plugin, going through the static files and setting `override_save_as` and `override_url` attributes as you like (based on file type?) would potentially handle that.

**Comment by egberts** [comment]
attributes?  Like in `example.md`:

```
Title: Example Markdown
status: published
date: 2020-03-11
override_save_as: images/
override_url: images/

An example markdown file
```
