### ISSUE TITLE
Empty files throw exceptions / warning

### ISSUE THREAD

**Issue by berlincount** [getpelican/pelican#1203]
I'm using 'touch slug' in my content directory to take notes on what I still want to write about - these show (unnecessary) warnings which clutter other output.

**Comment by leotrs** [comment]
Did that commit ever get merged?

**Comment by leotrs** [comment]
Rather than ignoring files silently, I recommend placing note-taking files in a different directory from content.

If pelican's principle is to mirror the content directory into the output directory, then empty content files should generate empty html pages, instead of ignoring them.

**Comment by justinmayer** [comment]
If someone would like to implement the approach [@kylef suggested](https://github.com/getpelican/pelican/pull/1204#issuecomment-56201933), please comment here and I will re-open this issue.
