### ISSUE TITLE
Why are CATEGORIES_URL and TAGS_URL gone?

### ISSUE THREAD

**Issue by DandyDev** [getpelican/pelican#1225]
According to the [3.3.0 docs](http://docs.getpelican.com/en/3.3.0/settings.html#url-settings), `TAGS_URL` and `CATEGORIES_URL` exist and have defaults. However, according to the [latest docs](http://docs.getpelican.com/en/latest/settings.html#url-settings) those settings don't exist anymore, and it's actually advised to put the urls hardcoded in the theme. That seems "dirty". Why has this changed?

**Comment by justinmayer** [comment]
If memory serves, these settings can be defined and then used in themes, but there's no need for them to be explicitly included in Pelican. If someone can make a contrary case, feel free to do so and I will re-open this issue.
