### ISSUE TITLE
Weird error for invalid rst

### ISSUE THREAD

**Issue by chrisglass** [getpelican/pelican#1231]
When pelican is passed a file with several top-level headers, it outputs an error like "ERROR: Skipping <article>: could not find information about 'date'"., which has nothing to do with the root cause of the problem (there are several top-level titles).

**Comment by fradeve** [comment]
Woow thanks, this definitely solves my issue, and this is still present in Pelican 3.5.0

**Comment by justinmayer** [comment]
Pull requests welcome.

**Comment by nunogrl** [comment]
> Hi Chris. Thanks for reporting this issue. Is this something you might be willing to work on and help us improve?

Would be good to have a section on troubleshooting :)

**Comment by justinmayer** [comment]
This particular issue should have been resolved by the [above-mentioned PR](https://github.com/getpelican/pelican/issues/1231#ref-pullrequest-308307322).
