### ISSUE TITLE
Documented code block syntax hilighting for Markdown does not work

### ISSUE THREAD

**Issue by jantman** [getpelican/pelican#1236]
The current documentation at http://docs.getpelican.com/en/latest/getting_started.html#syntax-highlighting says that MD code blocks, to be syntax hilighted, should be 8-space indented and the first line (also 8-space indented) should contain ":::identifier" (where identifier is a valid Pygments lexer). Using default settings from the sample/ directory, Markdown==2.3.1 and Pygments==1.6, this does not work - it includes a literal e.g. ":::python" as the first line of the code block, and no syntax hilighting.

Using either of the other two notations - either fenced code blocks with three-backticks and the identifier immediately following the backticks, or fenced code blocks with four tildes and a class-style identifier following the leading fence (i.e. "~~~~{.python}") - both work.

**Comment by nullne** [comment]
<img width="499" alt="screen shot 2015-08-28 at 21 17 39" src="https://cloud.githubusercontent.com/assets/6008447/9547067/41f6574e-4dca-11e5-9238-44b3053997a3.png">
how can i have code indented like this?

**Comment by viettd** [comment]
@nullne I solved by using the `8-space` intended like this:

```
1. Item 1:

        echo "Item 1"

1. Item 2:

        echo "Item 2"
```
