### ISSUE TITLE
Allow to use // instead of explicitly defining http

### ISSUE THREAD

**Issue by jvoisin** [getpelican/pelican#1251]
It would be nice to be able to use a "//" url scheme instead of "http" or "https" in *SITE_URL*. For now, *make publish* issues a warnings, and the generated HTML contains wrong links.
> make publish
> pelican /home/jvoisin/blog/content -o /home/jvoisin/blog/output -s /home/jvoisin/blog/publishconf.py 
> WARNING: Feeds generated without SITEURL set properly may not be valid
> Done: Processed 73 articles and 0 pages in 1.79 seconds.

Related to #1132 .

**Comment by justinmayer** [comment]
Not enough detail here to proceed. Closing.
