### ISSUE TITLE
The RSS feeds <guid> isn't passing W3C validator

### ISSUE THREAD

**Issue by treffynnon** [getpelican/pelican#1263]
The error reported is:

> guid must be a full URL, unless isPermaLink attribute is false

The snippet flagged looks like this:

```xml
<dc:creator xmlns:dc="http://purl.org/dc/elements/1.1/">Simon Holywell</dc:creator>
<pubDate>Thu, 13 Feb 2014 09:38:57 +0000</pubDate>
<guid>tag:simonholywell.com,2014-02-13:post/2014/02/functional-php-talks.html</guid>
<category>phpug</category>
<category>php</category>
```

URL to replicate test: http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fsimonholywell.com%2Ffeeds%2Ftags%2Fphp.rss.xml.gz

**Comment by curby** [comment]
I just came across this tonight while validating pages on my site.  I'd have to say that @Scheirle's number two option doesn't seem "right" to me, in the sense that Pelican's slugs are in fact meant to be permalinks AFAIK.  If an RSS feed is meant to offer permalinks by default, and we are generating them in Pelican already, then we should maintain that semantic link if at all possible.

Of course, I don't understand the difficulty that would be involved in another type of solution, or even what the RSS spec requires.  It seems that perhaps they're looking for a slash in front of the path, e.g. `/post/2014/02/functional-php-talks.html` from @treffynnon's sample.

When I brought this up in #pelican, mitchell suggested #1162 as one path to solving this particular issue.

**Comment by justinmayer** [comment]
I believe this is resolved in current master. If that's not the case, please post the details in a comment here and I will re-open.

**Comment by rhertzog** [comment]
If that's really fixed on master, can we get a new release out then?
