### ISSUE TITLE
<p> tag surrounding article.summary and page.summary

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican#1271]
<p class="first last"> surrounds article.summary and page.summary. Causes problems if looking to use the summary in a meta tag or you want to control what surrounds the data. Creates the requirement to modify your theme to use a filter to strip these tags out — i.e.: `{{ article.summary|striptags }}`

(*Edited by @justinmayer to clarify the provided interim workaround*)

**Comment by leotrs** [comment]
@justinmayer this should also be closed.

**Comment by justinmayer** [comment]
Ostensible dupe of closed issue #887.
