### ISSUE TITLE
Ambiguous feed titles on sites with multiple categories

### ISSUE THREAD

**Issue by radix** [getpelican/pelican#1291]
If you have multiple categories in your pelican site, the feeds for all of them will have the same title. On feed aggregation sites like feedly, this can be confusing when a user searches for your web site only to see a list of feeds with the same name (your site name) and different content.

I think the solution to this should be to include the category name in the feed title.

I couldn't figure out a way to customize the feed titles with configuration or templating.

**Comment by radix** [comment]
Thanks!

**Comment by davidlesieur** [comment]
Great! Thanks everyone, especially @chriskrycho for taking up the torch!
