### ISSUE TITLE
Live page reloading

### ISSUE THREAD

**Issue by kylef** [getpelican/pelican#1326]
Jekyll has a "live reload" feature, which extends on from `pelican --reload` and adds HTML and JavaScript magic so that it will automatically reload a HTML page in your browser when you make changes to the source. This is really nice for developing.

I'm have no idea how this would work, weather it would be better suited in a plugin etc. So chucking it up here to discuss.

**Comment by leotrs** [comment]
@justinmayer What's the state of `pelican --autoreload`?

**Comment by avaris** [comment]
I'd say pretty confused, since `--autoreload` doesn't have anything to do with serving pages.

**Comment by leotrs** [comment]
It says 
```
 -r, --autoreload      Relaunch pelican each time a modification occurs on
                               the content files. (default: False)
```

If the point is to get the content to the browser as soon as possible, I thought relaunching pelican would have to be part of that. Am I missing something?

**Comment by justinmayer** [comment]
@leotrs: `pelican -r` already re-generates output when source articles/pages change. As I understand it, @kylef is talking about subsequently triggering a *browser* refresh to see the changed output without having to manually reload the page.

As for the status, to my knowledge a pull request was never submitted, and I'm not sure that anyone has tested the commit that @notetau made in his fork. If someone were to prepare a proper pull request (with docs, tests, etc), it would be a nice feature addition.  (^_^)

**Comment by leotrs** [comment]
I see. Thanks. I agree this would be desirable.

**Comment by saschwarz** [comment]
FYI: this blog post gives a pretty easy way to do this: https://merlijn.vandeen.nl/2015/pelican-livereload.html I just tried it and it seems to work nicely when using port 5500 I didn't need to install any browser plugin(?). It could be a new script that is integrated in the Makefile/fabfile.

**Comment by dandavison** [comment]
I'm also looking forward to having this in pelican. In case it's helpful, the `grip` markdown renderer https://github.com/joeyespo/grip has an implementation that works well.

To add to @saschwarz's comment, another (even easier) workaround for those using chrome on OS X is to use `chrome-cli reload -t <tabid>` https://github.com/prasmussen/chrome-cli. E.g. by configuring your text editor to make the call to `chrome-cli` on file modification, or by having some shell code watching for file modification.

**Comment by josch** [comment]
This feature would go excellent together with the `pelican --listen` option that I implemented in pull request #2176. If anybody would accept my pull request then I volunteer to implement this feature as well.

It probably doesn't hurt to even have it enabled by default without needing an extra switch, right?

**Comment by Lucas-C** [comment]
:+1: 
One solution to implement this could be to use https://github.com/lepture/python-livereload

**Comment by bhrutledge** [comment]
One possible gotcha is that python-livereload [doesn't detect file deletion](https://github.com/lepture/python-livereload/issues/197) on macOS/Windows, which I discovered while implementing the [workaround](https://merlijn.vandeen.nl/2015/pelican-livereload.html) suggested by @saschwarz.

**Comment by justinmayer** [comment]
@bhrutledge: Thank you for [addressing the file deletion detection problem in python-livereload](https://github.com/lepture/python-livereload/pull/198). 🎊

**Comment by decentral1se** [comment]
OK, here's what worked for me on the latest pelican:

```python
from livereload import Server

CONFIG = {
    'content_path': 'content',
    'deploy_path': 'output',
    'port': 8000,
}

@task
def livereload(c):
    server = Server()
    server.watch(CONFIG['content_path'], lambda: build(c))
    server.serve(root=CONFIG['deploy_path'], port=CONFIG['port'])
```

Don't forget to `pip install livereload` and then `invoke livereload` and it's done.

**Comment by justinmayer** [comment]
Many thanks to @bhrutledge, @johnfraney, and everyone else who helped devise a solution for Pelican regeneration + automatic browser reloading. Perhaps someday this could be implemented in plugin form, but I think the Invoke-based implementation is good enough for now.

**Comment by justinmayer** [comment]
I made some enhancements to the Invoke-based regeneration + automatic browser reloading feature, as seen in the PR above.
