### ISSUE TITLE
Static content not copied without PATH='content'

### ISSUE THREAD

**Issue by georgevreilly** [getpelican/pelican#1333]
With the latest Pelican 3.3.1.dev, static content (`STATIC_PATHS = ['talks', 'images']`) is not copied to the output directory unless `PATH = 'content'` is also set in `pelicanconf.py`. `PATH` was not set in the `pelicanconf.py` that I created about 18 months ago.

**Comment by dns2utf8** [comment]
I am having this problem again with 4.0.0 sadly with `PATH = 'content'` already specified

**Comment by oulenz** [comment]
@dns2utf8 To be clear, do you mean what you described in https://github.com/getpelican/pelican/issues/2444, or are you experiencing a second problem?

**Comment by justinmayer** [comment]
I'm not sure this issue is associated with anything actionable. If someone has a specific problem, with detailed steps to reproduce, please feel free to submit a new issue.
