### ISSUE TITLE
pelican-quickstart and specifying a URL prefix

### ISSUE THREAD

**Issue by sursh** [getpelican/pelican#1337]
I'm on my first hour of Pelican here, and have found it all clearly thought through and well documented. Hooray! 

The one thing that's given me pause is the "Do you want to specify a URL prefix?" question. It's not obvious to me (the Pelican quickstarter) what the implications of this are—how should I decide? What will this be used for? Will it screw me over later? Can I decide later?

What do you think of two small changes to the `pelican-quickstart` script that would make this clearer: 
1. One sentence of explanation of what the URL prefix is for (from a quick look through the codebase, it looks like it's for absolute link generation in the templates, and not having it will mean that your links are relative and your rss feed will be borked)
2. One sentence at the end of the questions pointing you to the config files if you want to change things later.

**Comment by heyman** [comment]
Hi! Just wanted to chime in as my experience is very similar to that of @sursh's:

> The one thing that's given me pause is the "Do you want to specify a URL prefix?" question. It's not obvious to me (the Pelican quickstarter) what the implications of this are—how should I decide? What will this be used for? Will it screw me over later? Can I decide later?

Since the implication is just a matter of setting a config variable, I think simply mentioning that this can be easily changed later would solve much of the issue.

**Comment by justinmayer** [comment]
@heyman: I understand the desire for more elaboration regarding this question, but I don't think the quick-start script itself should be the mechanism for providing that information. If someone, on the other hand, would like to submit a pull request that adds such detail to the [relevant section of the docs](https://docs.getpelican.com/en/latest/quickstart.html#create-a-project), we would be happy to review it.
