### ISSUE TITLE
Use a temporary_locale context manager

### ISSUE THREAD

**Issue by smartass101** [getpelican/pelican#1347]
While working on my i18n_subsites plugin, I came up with an idea how to simplify some code that is often used in Pelican: doing stuff with a temporarily different locale.
This could be neatly solved by a context manager:

``` Python
from contextlib import contextmanager
import locale

@contextmanager
def temporary_locale(temp_locale=None):
    '''Enable code to run in a context with a temporary locale

    Resets the locale back when existing context.
    Can set a temporary locale if provided
    '''
    orig_locale = locale.setlocale(locale.LC_ALL)
    if temp_locale is not None:
        locale.setlocale(locale.LC_ALL, temp_locale)
    yield
    locale.setlocale(locale.LC_ALL, orig_locale)
```

This would enable stuff like

``` Python
with temporary_locale('C'):
     pass
```

**Comment by justinmayer** [comment]
@smartass101: Any update on your proposal here?

**Comment by usmanatron** [comment]
Im going to pick this up; looks like a good first issue  to start contributing!

**Comment by justinmayer** [comment]
@usmanatron: Any progress on your work on this issue?

Would anyone else like to implement the functionality described in this issue?

**Comment by justinmayer** [comment]
@avaris: Would you mind sharing your thoughts on this proposal? Would be nice to close it out, one way or another.

**Comment by holden-nelson** [comment]
Submitted a pull request for this feature. Kind of a contributing noob so let me know if I did anything incorrectly or need to make any changes. Thanks!

**Comment by holden-nelson** [comment]
Ahh, now I see pull request #2027 which fixes the issue and implements the new functionality right away. Oh well! Would you like me to just close this?
