### ISSUE TITLE
Draft posts should not depend on a date

### ISSUE THREAD

**Issue by kylef** [getpelican/pelican#1356]
Since it's a draft, you won't know the date yet. It makes very little sense to require the date for drafts.

**Comment by ehashman** [comment]
I was hoping to help close this bug but I'm not sure what the problem is. If you create an article with `status: draft`, no date is required for the draft to generate an article. @kylef, what is the desired fix?

**Comment by ingwinlu** [comment]
@ehashman see the above linked open issue I opened that explains the issue

**Comment by leotrs** [comment]
If drafts now don't really depend on a date, then we can probably continue discussion at #1748, reference this issue from there and close this.

**Comment by justinmayer** [comment]
@leotrs: Agreed. If someone determines that draft posts do indeed require a date, please comment here and I will re-open this issue.
