### ISSUE TITLE
Automatic post summary causes weird line numbers in code-block

### ISSUE THREAD

**Issue by edelooff** [getpelican/pelican#1369]
When leaving Pelican to create post summaries automatically based on the `SUMMARY_MAX_LENGTH` setting, there is a bad interaction with code-blocks with `:linenos: table` set:

![bad-cut](https://cloud.githubusercontent.com/assets/490090/3212431/bfd75082-ef5c-11e3-8520-c0b8f15dc2d8.png)

The amount of code shown depends entirely on the summary max length setting, but the line-numbers table will be as long as the actual code-block in source. This means that for the given article, the code-block ends after three lines, but the line-numbers count up to fitteen.

There are a couple of solutions to this, and perhaps multiple apply:
- For now, I've simply set the `linenos` to be `inline`, which removes the problem though copy/paste of code becomes tricky
- Having a per-article summary-max-length could provide for a quick and dirty solution (setting `:summary:` would cause a lot of duplication for my use-case where I want the first bit of the article in the index)
- Actually checking the number of lines left from the code-block and limiting the number of lines in the line-number cell to that value would clearly be ideal.

**Comment by leotrs** [comment]
Is this still present in 3.6?

**Comment by Scheirle** [comment]
> Is this still present in 3.6?

Yes, https://bernhard.scheirle.de/page/2/ ("Tipue Search - Tag support" article)

**Comment by justinmayer** [comment]
@Scheirle: I agree that tables are probably not appropriate for summary content. What do you propose we do about that?
