### ISSUE TITLE
Can not parse .rst with "ERROR: Skipping ./test.rst: could not find information about 'date'"

### ISSUE THREAD

**Issue by donly** [getpelican/pelican#1394]
The test.rst file's content is same as that in docs, which has 'date' and 'slug' metadata.
After adding "DEFAULT_DATE = 'fs'" to the pelicanconf.py, this error disappear but another warning occur, WARNING: empty slug for u'/Users/Sun/Documents/Python/site3.5.dev/content/test.rst'. You can fix this by adding a title or a slug to your content.
Pelican install from $ pip install -e "git+https://github.com/getpelican/pelican.git#egg=pelican".

**Comment by fradeve** [comment]
Hi all,
I have the same problem here, but the rst looks fine:

    :date: 2007-09-29 15:01:01

any hint?
