### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)

### ISSUE THREAD

**Issue by twmht** [getpelican/pelican#1403]
Dear all,

I am using python 2.7.7 and have installed pelican by pip.

However, I got the following error message when I want to regenerate all the html pages.

```
tumh@tumh-lubuntu:~/blog$ make devserver 
/home/tumh/blog/develop_server.sh restart
Killing pelican.server
Stale PID, deleting
Starting up Pelican and pelican.server
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Restoring system path
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---
False

-> Modified: settings, content, theme. re-generating...
DEBUG: template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.html', u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html', u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html', u'analytics.html', u'archives.html', u'article.html', u'article_infos.html', u'author.html', u'authors.html', u'base.html', u'categories.html', u'category.html', u'disqus_script.html', u'github.html', u'google_custom_search.html', u'gosquared.html', u'index.html', u'page.html', u'pagination.html', u'period_archives.html', u'piwik.html', u'tag.html', u'tags.html', u'translations.html', u'twitter.html']
CRITICAL: ('ascii', "[Errno 2] \xe6\xb2\x92\xe6\x9c\x89\xe6\xad\xa4\xe4\xb8\x80\xe6\xaa\x94\xe6\xa1\x88\xe6\x88\x96\xe7\x9b\xae\xe9\x8c\x84: u'/home/tumh/blog/cache/ArticlesGenerator-Readers'", 10, 11, 'ordinal not in range(128)')
CRITICAL: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)
Traceback (most recent call last):
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/__init__.py", line 394, in main
    pelican.run()
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/__init__.py", line 156, in run
    ) for cls in self.get_generator_classes()
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/generators.py", line 230, in __init__
    super(ArticlesGenerator, self).__init__(*args, **kwargs)
 File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/generators.py", line 171, in __init__
    **kwargs)
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/generators.py", line 46, in __init__
    self.readers = Readers(self.settings, readers_cache_name)
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/readers.py", line 403, in __init__
    caching_policy, load_policy,
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/utils.py", line 645, in __init__
    load_policy)
  File "/home/tumh/.pythonbrew/pythons/Python-2.7.7/lib/python2.7/site-packages/pelican/utils.py", line 601, in __init__
    self._cache_path, err))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 10: ordinal not in range(128)
```

My locale is as follows:

```
LANG=en_US.UTF-8
LANGUAGE=zh_TW:
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=en_US.UTF-8

```

However, I tried to switch python 3.4.1 and it works fine. In python 3.4.1, it generated both cache and __pycache__ directory. If both directories exist, then python 2.7.7 will work.

Any suggestions?

Many thanks!

**Comment by sdsawtelle** [comment]
I just ran into the same error so wanted to add it here even though the thread is old.

I was using python 2.7 virtualenv and the [ipynb plugin]( http://danielfrg.com/blog/2013/03/08/pelican-ipython-notebook-plugin/#disqus_thread) for converting jupyter notebooks to html with pelican. 

With some .ipynb notebooks in the pelican content folder I tried running `pelican content`. I was receiving the error "UnicodeDecodeError: 'ascii' codec can't decade byte 0xc2 in position 333: ordinal not in range(128)." The error only occurred for jupyter notebooks that had code cells in them, the pure markdown notebooks were fine.

I found [this](http://stackoverflow.com/questions/21393758/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe5-in-position-0-ordinal) SO question and added the following at the top of the pelicanconf.py file under `from __future__ import __unicode_literals` :

import sys
reload(sys)
sys.setdefaultencoding("utf-8")

This seems to have fixed the issue, but I don't really understand why.

**Comment by avaris** [comment]
@sdsawtelle Although the error looks same (`UnicodeDecodeError`), yours is a different issue and possibly coming from `ipynb` plugin. And I'd really suggest against using the "workaround" you found. Instead, please file an issue with the `--debug` log in the `plugins` repo for that plugin.

**Comment by sdsawtelle** [comment]
@avaris Ok thank you! Yes, agree that it is probably to do with the `ipynb` plugin.

**Comment by dm-wyncode** [comment]
I am having the same issue as @sdsawtelle using [this plugin](https://github.com/danielfrg/pelican-ipynb).

> ERROR: Could not process posts/object_classes/interfaces.ipynb
  | UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 87400: ordinal not in range(128)
