### ISSUE TITLE
Pandoc's line wrapping breaks pelican-import for WordPress

### ISSUE THREAD

**Issue by arafalov** [getpelican/pelican#1406]
I have tried importing WordPress blog using pelican-import. It generates a lot of errors like:

    Block quote ends without a blank line; unexpected unindent.
    Unexpected indentation.

Looking at generated rst files, it seems that the line wrap occurs after other formatting is applied and it breaks a lot of formatting across multiple lines.

Modifying *pelican_import.py* to add **--no-wrap** to pandoc invocation has reduced the number of errors significantly (though not completely).

Since the goal of the importer is to get - potentially large - number of articles from one system to another as fast as possible, perhaps the line-wrapping niceties are not as important here.

Pelican 3.4.0, Pandoc 1.12.4.2 on Mac

**Comment by leotrs** [comment]
@arafalov did you ever work around this?

**Comment by arafalov** [comment]
No. I ended up not using the project.
