### ISSUE TITLE
Adding a pelican-newpost script

### ISSUE THREAD

**Issue by TC01** [getpelican/pelican#1410]
So, this is something I'd be interested in working on, but I'm not sure exactly what the right way to do it would be:

I maintain two Pelican sites (currently). It didn't dawn on me until now how useful a script that automatically sets stuff like the date and prompts the user for title/category/slug/author/etc would be.

I was imagining something like pelican-quickstart, which prompts the user directly for most arguments. After having the idea, though, a quick search through the repository found a pull request #1085, which added a script called pelican-article that does something very similar, although it takes command line arguments.

The request was rejected for other reasons, and as far as I can tell hasn't been resubmitted by the original author since then? (If I am wrong, please correct me).

As I'm interested in this feature: would it be permissible for me to take @icyleaf's script as a starting point, modify it, and resubmit it under a different name? I mean, I might do things slightly differently, but his script is probably a decent starting point.

**Comment by btnpushnmunky** [comment]
Did this every happen @TC01 ?

**Comment by TC01** [comment]
It did not; I was waiting for the pelican-tools repository to get created.

**Comment by kylef** [comment]
I've created the repository as a first step: https://github.com/getpelican/pelican-tools would really appreciate if someone could contribute a pull request for #800 to get things started.

**Comment by leotrs** [comment]
@kylef what's the state of this? I *could* try my hand at a pelican-newpost script for pelican-tools if that was going to be supported, but right now pelican-tools looks abandoned.

**Comment by leotrs** [comment]
cc @justinmayer ^

I already have a new-post script for my workflow, based on a jinja tamplate [here](https://github.com/leotrs/erdos/tree/master/scripts/templates). Would gladly update and PR it. Is the deserted pelican-tools repo ever going to be used?

**Comment by justinmayer** [comment]
Who would like to volunteer to submit a pull request to the [Pelican Tools](https://github.com/getpelican/pelican-tools) repository to add this feature?

**Comment by luigibertaco** [comment]
Hi, @justinmayer I'd like to give it a go.

**Comment by justinmayer** [comment]
That would be great, Luigi. Let us know if you get stuck on anything! 💫

**Comment by georgexyz19** [comment]
Hi, @luigibertaco I recently wrote a [newpost.py script](https://github.com/georgexyz19/georgexyz.com/blob/master/newpost.py) for my own blog site.  I also wrote [a short blog post](https://georgexyz.com/create-new-pelican-post.html) about it.  The script only supports markdown and is tailored to my own need.  Maybe a start point for your effort.

**Comment by luigibertaco** [comment]
Hi, @georgexyz19 

Thanks for that, I am trying to open the PR today but I'll definitely have a look at your implementation to make it as production-ready as possible.

**Comment by justinmayer** [comment]
Closing in favor of https://github.com/getpelican/pelican-tools/issues/6
