### ISSUE TITLE
SITEURL & Feed Generation

### ISSUE THREAD

**Issue by miseqs** [getpelican/pelican#1419]
I'm just getting started with pelican and have a quick question about SITEURL and feed generation.

From what I can tell, pelicanconf.py is the default configuration and all configured values are applied when developing. Publishconf.py inherits the settings from pelicanconf.py and overrides specific settings for the published version of the site.

In my pelicanconf.py I have left SITEURL = "". If I specify a value for this setting (using the actual site URL) the dev content (obviously) breaks.

In my publishconf.py, I specify that actual server url and everything seems to work correctly.

In my pelicanconf.py, I have attempted to disable feed generation by setting:
FEED_ATOM = None
FEED_RSS = None
FEED_ALL_ATOM = None
FEED_ALL_RSS = None

And in my publishconf.,py, I set these correctly. The feeds seem to be working correctly.

However, when I build the site using "make html" I get the following warning:

```
WARNING: Feeds generated without SITEURL set properly may not be valid
```

Any suggestions how I can resolve this?
For reference, my site source is [here](https://github.com/nfarrar/crunk.io).

**Comment by LaurianoElmiroDuarte** [comment]
@nfarrar i am also trying to understand pelican  
good ask.
