### ISSUE TITLE
Markdown Tables & CSS

### ISSUE THREAD

**Issue by miseqs** [getpelican/pelican#1421]
I've got some tables written in markdown that I'm trying to add bootstrap rendering for.
An example is here: http://crunk.io/understanding-ejuice-and-branching-out.html#blends

I'm currently using a forked copy of the pelican-bootstrap3 theme.

I first asked about this feature on the original theme authors github repo here: https://github.com/DandyDev/pelican-bootstrap3/issues/116.

After a small discussion, I understand I have at least 3 options to make this work:
1. Write the tables in the markdown document as inline html.
2. Write a kramdown plugin for pelican.
3. Add a custom stylesheet to apply a set of styles to all tables.

When the markdown parser renders the table, the generated code is essentially:

```
<table>
    <thead>
        <tr>
            <th>Heading1</th>
            <th>Heading2</th>
            <th>Heading3</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Data1</td>
            <td>Data2</td>
            <td>Data3</td>
        </tr>
    </tbody>
</table>
```

To improve the rendering, I need to apply the bootstrap attributes to the table tag:

```
<table class="table">
    ...
</table>
```

... or: 

```
<table class="table table-condensed table-bordered table-hover">
    ...
</table>
```

With the proper bootstrap attributes applied, it looks like this instead:
![Rendered Properly](https://www.evernote.com/shard/s110/sh/b04caa1a-6447-4ab6-b311-616250684441/509f8121fb2049866ef358abda031d85/res/2d1c2954-fbf1-4b6a-a174-c13b937dea4d/skitch.png)

I'm curious if anyone has any insight with this issue and can suggest a good approach or identify a solution I may not be aware of.

Thanks!

**Comment by zhao-ji** [comment]
So, how can I  get the markdown table which have black line?

**Comment by ingwinlu** [comment]
https://github.com/ingwinlu/pelican-bootstrapify

**Comment by zhao-ji** [comment]
good! but the theme must contain bootstrap? @ingwinlu

**Comment by equiman** [comment]
@avaris Thanks! Works for me.

**Comment by dnmfarrell** [comment]
Another hack would be to add this to the bottom of the template:
```
<script>
var tables, i;
tables = document.getElementsByTagName('table');
for (i=0;i<tables.length;i++) {
  tables[i].className = 'table table-striped';
}
</script>
```

**Comment by gsauthof** [comment]
Another workaround - post-process the output via something like:

    grep '<table>' output  -r -l --include '*.html' \
     | xargs -r sed -i 's/<table>/<table class="table table-striped">/'

**Comment by Goddard** [comment]
markdown generated tables need to have a class applied and the problem would be solved.

Other plugins may also generate tables so applying a table css style defeats the purpose.

It is a simple fix.  If we had a markdown specific css class that always gets applied then we can target it. 

What is the issue?

**Comment by gsauthof** [comment]
Yet another workaround is to put this into your `pelicanconf.py`:

```
# for bootstrap:
# table_css_class = 'table table-striped'

# for m.css:
table_css_class = 'm-table'

import markdown.extensions.tables

class BetterMDTableProcessor(markdown.extensions.tables.TableProcessor):
    def run(self, parent, blocks):
        super().run(parent, blocks)
        for e in parent:
            if e.tag == 'table':
                e.attrib['class'] = table_css_class

class BetterMDTableExtension(markdown.extensions.tables.TableExtension):
    def extendMarkdown(self, md):
        if '|' not in md.ESCAPED_CHARS:
            md.ESCAPED_CHARS.append('|')
        md.parser.blockprocessors.register(BetterMDTableProcessor(md.parser), 'table', 75)

MARKDOWN = {
    'extensions': [ BetterMDTableExtension() ],
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'm-code'},
        'markdown.extensions.footnotes': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.toc': { 'permalink': True },
    },
    'output_format': 'html5',
}
```

@Goddard - I think the issue is that the maintainer of the Python markdown package doesn't want to add any features to the table extension. Don't even a trivial `css_class` configuration item that would work analogously to the `css_class` item of the codehilite extension.

**Comment by egberts** [comment]
I have found a table-ization plugin for Pelican called jtable. 

https://github.com/burakkose/just_table

I am using it intensively in all my blogs, one intensive table example is over at https://egbert.net/blog/articles/openssl-envvars.html

Templating for Markdown-only (not Rst) is easy as:

```
Nice table here:
[jtable]
Name, Description, Option
Sue, a web designer, yes
Tom, an IT guy, no
[/jtable]
```

It does work well.  

Unfortunately, I cannot change the separator (it is stuck at comma symbol).  

Given that limitation, this is good enough for me. 

The plug-in is old.  Very old, has not been upgraded to use the `pelican.plugins` namespace ... yet.  My entire blog and I am in danger of being obsoleted out of Any future Pelican upgrades. 

Secondly, the Pelican.generator doesn't seem to parse the various options attributes within the `[jtable opt=value]`.  This alone explains my inability to change separator char. 

Thirdly, the use of square brackets pair as a macro notation (within Markdown) seems to be treated very differently than Jinja2's double-curly-braces pair.  As if Pelican recognize Jinja2 exclusively and only.  

While a great utility, it is in danger of obsolescence.
