### ISSUE TITLE
categories.html in "notmyidea" theme incorrectly formatted

### ISSUE THREAD

**Issue by vpiotr** [getpelican/pelican#1450]
When using "notmyidea" theme "categories.html" look awful - list is displayed on the left border, not in the central (body) part.  

Small correction below fixes this - just add new file to theme: "categories.html" (based on author list)

#categories.html

    {% extends "base.html" %}
    {% block content %}

    <section id="content" class="body">
        <h1>Categories on {{ SITENAME }}</h1>

    <ul>
    {% for category, articles in categories %}
        <li><a href="{{ SITEURL }}/{{ category.url }}">{{ category }}</a></li>
    {% endfor %}
    </ul>

    </section>

    {% endblock %}

**Comment by stharrold** [comment]
@vpiotr Thanks for the fix!
@justinmayer Until a fix is applied to pelican, is there a way to tell pelican to use `categories.html` above without forking my own version of [`pelican/themes/notmyidea`](https://github.com/getpelican/pelican/tree/master/pelican/themes/notmyidea)? Thanks for your help!

**Comment by leotrs** [comment]
Is this still an issue?

**Comment by stharrold** [comment]
@leotrs I no longer use the `notmyidea` theme, so I'm not sure if there is still an issue. (I migrated to themes derived from Bootstrap.)

**Comment by leotrs** [comment]
This should be closed then.

**Comment by justinmayer** [comment]
Thanks for the nudge, Leo!

**Comment by vpiotr** [comment]
I'm not sure who is who in this project, but I'm quite sure @stharrold was not the person who created this issue...

**Comment by leotrs** [comment]
@vpiotr you did. Is this still an issue?

**Comment by vpiotr** [comment]
I'm still using my own copy of pelican + this theme and I see no change in category.html during these 2 years so I assume this page looks as it was. However, if this is not important, you can close the issue - I don't care.

**Comment by justinmayer** [comment]
@vpiotr: Do you know whether this change still exists in current master?

**Comment by vpiotr** [comment]
You mean if I know if the issue still exists? No, I don't know. Probably if you have a clean build, and some content with categories, it's just a matter of opening this page (categories.html).
