### ISSUE TITLE
develop_server.sh stops scanning files on rst error

### ISSUE THREAD

**Issue by countergram** [getpelican/pelican#1458]
When there is a syntax/parsing error in an RST file being watched by `develop_server.sh` it stops auto-reloading files at all. So after you fix the RST you have to restart the server, which is contrary to the point of having a server that auto-reloads files.

Pelican 3.4.0 / pip install pelican / default theme etc.

**Comment by leotrs** [comment]
@countergram Did this ever get done? Does the problem still exist on the newest version?
