### ISSUE TITLE
custom Writer plugins are passed to custom Generator.generate_output() calls

### ISSUE THREAD

**Issue by sawall** [getpelican/pelican#1459]
I am writing a custom Generator plugin. I've noticed that, when generate_output() in my Generator is called, it is sent an unpredictable Writer based on whether or not I'm loading a plugin that has a custom Writer (e.g., the feed_summary plugin).

If a different plugin has a Writer, get_writer() in **init**.py returns it because Pelican.writer isn't initialized until line 169 in run(), right before generate_output is called on all the Generators. If there's no plugins with Writers, self.get_writer() returns pelican.writers.Writer. But when you load feed_summary, Pelican.writer becomes feed_summary.feed_summary.FeedSummaryWriter.

The simple workaround is to ignore the writer passed in generate_output. Off the top of my head, I think one of the following is needed:
- Change generate_output() so that it is sent a list of all Writers instead of one. Changes to the core Pelican Generators would need to be made to support this to cherry pick the proper Writers for output. Handling arbitrary plugin Writers might be weird or confusing. Pelican.**init**() might need to put a pelican.writers.Writer at the head of the list.
- Drop the writer from generate_output() entirely and have Generator plugins instantiate Writers explicitly. This seems like a clean approach but there might be use cases where a Generator plugin wants to get a Writer from another plugin that I'm not thinking about. This requires rewrites in the core Pelican code and of Generator plugins.
- Leave it the way it is since the API is used internally, and don't expect custom plugins to be able to successfully use the Writer it's passed. Update the docs to say it shouldn't be used.

I'm happy to help out with any of the above!

**Comment by justinmayer** [comment]
@getpelican/reviewers: Any comments on the proposals listed in this issue?

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
