### ISSUE TITLE
Nested Blocks

### ISSUE THREAD

**Issue by RossMerriam** [getpelican/pelican#1475]
Hi I'm trying to make a nested block in my pelican theme that wraps a for loop:
```
{% block content %}
{% block test_block %}
{% for subcategory in article.subcategories %}
Stuff here
{% endfor %}
{% endblock test_block %}
{% endblock content %}
```
But my theme is not compiling. If I take the for loop out of the 'test_block' everything runs as expected. Where am I going wrong? Any help would be appreciated. Thanks,

**Comment by matrixise** [comment]
I think you can close this bug.

**Comment by justinmayer** [comment]
Thanks, @matrixise.
