### ISSUE TITLE
New articles won't compile because of language issues?

### ISSUE THREAD

**Issue by FuzzyWuzzie** [getpelican/pelican#1479]
Hello,

Whenever I attempt to compile new articles (written in Markdown), they fail to compile, citing the error `cannot import name 'guessLanguageTag'. A sample file that doesn't work:

```markdown
Title: A Basic Entity System Written in Haxe
Slug: basic-entity-system-in-haxe
Date: 2014-09-22 14:17:35
Tags: Haxe, Entity System
Category: Game Development
Author: Kenton Hamaluik
Lang: en
Status: draft
Summary: Derp

Why won't this compile?!
```

With output that looks like:

```bash
WARNING: Could not process 2014\2014-09-22-basic-entity-system-in-haxe.md
cannot import name 'guessLanguageTag'
Done: Processed 45 article(s), 0 draft(s) and 0 page(s) in 2.11 seconds.
```

(there are 46 articles including this one that won't process).

**Comment by justinmayer** [comment]
Caching is now disabled by default in 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html). Sounds like a mix of plugins — and not caching — were the cause here, but I thought I'd mention it anyway.
