### ISSUE TITLE
Support for Textbundles

### ISSUE THREAD

**Issue by DirkR** [getpelican/pelican#1482]
Hi all,

There is a relatively new specification for Markdown files bundled with media assets called TextBundle (http://textbundle.org/spec/). In anutshell a textbundle is a folder with ",textbundle" a name suffix and a predefined folder hierarchy. The Markdown text is always in a file "text.md", all referenced assets (images, videos, etc.) are located in a subfolder named "assets/" and a file "info.json" (obviously in JSON format) provides some meta data.

I'd like to restructure my content and use the Textbundle spec, because it bundles the text together with its media files.

I tinkered with Pelican's sources this evening and tried to add Textbundle Support:

* Implemented a new `TextbundleReader` as subclass of `MarkdownReader`
* Added `READERS = {'textbundle': TextbundleReader}` in `pelicanconf.py`
* moved all posts in `content/posts/post_name.md` to `content/posts/post_name.textbundle/text.md`.   
   So far I didn't move the images into the assets folders.

In my setup the posts are generated into HTML files `[slug]/index.html`and it should support relative image URLs àssets/image.jpg`. Later I will have to manage the media files and extend the Writer classes...

Before I continue my explorations, I want to get some Input of you, if I am on the right track. My questions:

* Is this the way to extend Pelican?
* Should I extend Pelican Core as described above or would it be better to create a plugin? I tend to prefer the plugin version...

Thanks in advance for your feedback!

Best regards
Dirk

**Comment by justinmayer** [comment]
Hi Dirk. I'm very sorry for the delay in responding to your most recent comment. I took the liberty of adding your plug-in to the Pelican Plug-ins repository. Many thanks for your contribution!
