### ISSUE TITLE
All content is held in memory at once.

### ISSUE THREAD

**Issue by foresto** [getpelican/pelican#1494]
Looking through generators.py, and especially the `generate_context()` methods, it looks like every `Content` object in an entire site is held in memory at the same time. That includes the full HTML output of all pages, plus a second copy of each one after `get_content()` does its URL replacement and memoization. It seems to me that becoming conservative with memory usage would make Pelican more appealing to people building larger sites or running on constrained hardware. (My server, for example, has only a fraction of a gigabyte of RAM, much of which is devoted to other software.)

**Comment by justinmayer** [comment]
@foresto: What do you think should be done here?
