### ISSUE TITLE
Add JINJA_TESTS in the settings

### ISSUE THREAD

**Issue by sylvinus** [getpelican/pelican#1498]
Should be straightforward to do, just like JINJA_FILTERS

**Comment by justinmayer** [comment]
@sylvinus: Is this something you would like to work on?

**Comment by leotrs** [comment]
Did [800c3c1](https://github.com/oseledets/pelican/commit/800c3c1013fbbc487e2a4adf5e6f360fb2be21a4) ever get merged into pelican? It looks like a good idea.

**Comment by leotrs** [comment]
@oseledets Are you interested in PRing [300c3c1](https://github.com/oseledets/pelican/commit/800c3c1013fbbc487e2a4adf5e6f360fb2be21a4)?

**Comment by justinmayer** [comment]
Pull request #1816 was submitted to address this, but we are still awaiting follow-up changes from @oseledets.

**Comment by justinmayer** [comment]
I implemented this via the above-linked PR, which has been merged to master. 💫
