### ISSUE TITLE
subscribe by email feature

### ISSUE THREAD

**Issue by horstjens** [getpelican/pelican#1504]
Sorry if this question is very stupid but i wonder if there is a simple solution to offer visitors of my pelican blog (who don't know about RSS / Atom feed) a possibility to subscribe to a feed by email (like in wordpress.com) ?

**Comment by matrixise** [comment]
I think you can close this bug. it's not related to Pelican but just to a mailing list system.

**Comment by justinmayer** [comment]
Agreed. Thanks, @matrixise.
