### ISSUE TITLE
Running pelican out of a pelican folder generates strange warnings

### ISSUE THREAD

**Issue by arqeco** [getpelican/pelican#1508]
When you run the "pelican" command out of a pelican configured folder, it would be expected (at least to a beginner like me) something like:

    CRITICAL: Unable to find 'content' folder

But, instead, you get on 3.4.0

    CRITICAL: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)

and on 3.5.0 dev

    ERROR: Skipping local/lib/python2.7/site-packages/pelican/themes/simple/templates/gosquared.html: could not find information about 'title'
    ERROR: Skipping local/lib/python2.7/site-packages/pelican/themes/simple/templates/article.html: could not find information about 'title'
    ERROR: Skipping local/lib/python2.7/site-packages/pelican/themes/simple/templates/categories.html: could not find information about 'title'
    ERROR: Skipping local/lib/python2.7/site-packages/pelican/themes/simple/templates/page.html: could not find information about 'title'
    ERROR: Skipping local/lib/python2.7/site-packages/pelican/themes/simple/templates/tags.html: could not find information about 'title'

**Comment by leotrs** [comment]
This is still an issue on 3.6.3. I agree this needs attention.

cc. @justinmayer What would be the desired default behavior?

**Comment by justinmayer** [comment]
The docs [explicitly mention](http://docs.getpelican.com/en/stable/faq.html#is-it-mandatory-to-have-a-configuration-file) that settings files are optional and not mandatory. I can't think of a sensible way to handle situations like this, but if someone else can and wants to actively work on a pull request that elegantly addresses this, please comment here and I will re-open this issue.
