### ISSUE TITLE
Add support for emphasize-lines option to code-block directive

### ISSUE THREAD

**Issue by stevepiercy** [getpelican/pelican#1510]
Please consider adding support for the emphasize-lines option to the code-block directive.

**Comment by leotrs** [comment]
@stevepiercy Did the docs ever get updated?

Either way, this can probably be closed. cc @justinmayer.

**Comment by stevepiercy** [comment]
@leotrs no. http://pelican.readthedocs.io/en/3.6.3/content.html#syntax-highlighting

I just created a PR to resolve this. Thanks for the reminder. @justinmayer

**Comment by justinmayer** [comment]
Addressed via #1993.
