### ISSUE TITLE
Migrate to bumpversion

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1520]
We currently have [bumpr.rc](https://github.com/getpelican/pelican/blob/master/bumpr.rc), but [bumpr](https://github.com/noirbizarre/bumpr) is unmaintained, so I propose that we use [bumpversion](https://github.com/peritus/bumpversion) instead. Other suggestions welcome, of course.  :^)

**Comment by iKevinY** [comment]
I think this can be closed in favour of #1652.

**Comment by justinmayer** [comment]
Yikes. Can't believe I submitted this twice. :dizzy_face:
