### ISSUE TITLE
Linking to direct templates

### ISSUE THREAD

**Issue by Undeterminant** [getpelican/pelican#1524]
It would be nice if I could link to a direct template from a page, although there doesn't seem to be any syntax for it. Maybe `{template}`?

**Comment by justinmayer** [comment]
@Undeterminant: Is this something you would like to work on?

**Comment by Undeterminant** [comment]
@justinmayer: I don't know if I'll get around to it, but maybe eventually if no one works on it and I have the time.

**Comment by justinmayer** [comment]
Hi Claire. When you find the time, please post a comment here and I'll re-open. Thanks!
