### ISSUE TITLE
Deploying on GitHub Pages requires RELATIVE_URLS to be True.

### ISSUE THREAD

**Issue by OrangeTux** [getpelican/pelican#1526]
When `RELATIVE_URLS = False` static files are not loaded. This should be mentioned in the docs.

**Comment by nacnudus** [comment]
I have the same problem [here](https://nacnudus.github.io/crosstab-kiwi/index.html), set up with the default theme and `SITEURL = 'https://nacnudus.github.io/crosstab-kiwi'.

**Comment by avaris** [comment]
@nacnudus, can you show your config file?

**Comment by nacnudus** [comment]
[config](https://github.com/nacnudus/crosstab-kiwi/blob/master/publishconf.py) and pasted below.  Thanks for checking this out.

    #!/usr/bin/env python
    # -*- coding: utf-8 -*- #
    from __future__ import unicode_literals
    
    # This file is only used if you use `make publish` or
    # explicitly specify it as your config file.
    
    import os
    import sys
    sys.path.append(os.curdir)
    from pelicanconf import *
    
    SITEURL = 'https://nacnudus.github.io/crosstab-kiwi'
    RELATIVE_URLS = False
    
    FEED_ALL_ATOM = 'feeds/all.atom.xml'
    CATEGORY_FEED_ATOM = 'feeds/%s.atom.xml'
    
    DELETE_OUTPUT_DIRECTORY = True
    
    # Following items are often useful when publishing
    
    #DISQUS_SITENAME = ""
    #GOOGLE_ANALYTICS = ""

**Comment by avaris** [comment]
@nacnudus that's `publishconf.py`. In your `pelicanconf.py`, you have `SITEURL = ''`. How do you generate your site?

**Comment by nacnudus** [comment]
First I create an empty repository, then I do this:

```
(pelican)nacnudus@nactop:~% git clone https://github.com/nacnudus/crosstab-kiwi.git
Cloning into 'crosstab-kiwi'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
(pelican)nacnudus@nactop:~% cd crosstab-kiwi
(pelican)nacnudus@nactop:~/crosstab-kiwi% pelican-quickstart                                                                ±[master]
Welcome to pelican-quickstart v3.3.0.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

    
> Where do you want to create your new web site? [.] 
> What will be the title of this web site? Crosstab Kiwi
> Who will be the author of this web site? Duncan Garmonsway
> What will be the default language of this web site? [en] 
> Do you want to specify a URL prefix? e.g., http://example.com   (Y/n) 
> What is your URL prefix? (see above example; no trailing slash) https://nacnudus.github.io/crosstab-kiwi
> Do you want to enable article pagination? (Y/n) 
> How many articles per page do you want? [10] 
> Do you want to generate a Fabfile/Makefile to automate generation and publishing? (Y/n) 
> Do you want an auto-reload & simpleHTTP script to assist with theme and site development? (Y/n) 
> Do you want to upload your website using FTP? (y/N) 
> Do you want to upload your website using SSH? (y/N) 
> Do you want to upload your website using Dropbox? (y/N) 
> Do you want to upload your website using S3? (y/N) 
> Do you want to upload your website using Rackspace Cloud Files? (y/N) 
Done. Your new project is available at /home/nacnudus/crosstab-kiwi
(pelican)nacnudus@nactop:~/crosstab-kiwi% pelican content -o output -s pelicanconf.py                                    ±[●][master]
WARNING: No valid files found in content.
Done: Processed 0 articles and 0 pages in 0.05 seconds.
(pelican)nacnudus@nactop:~/crosstab-kiwi% ghp-import output                                                              ±[●][master]
(pelican)nacnudus@nactop:~/crosstab-kiwi% git push origin gh-pages                                                       ±[●][master]
Username for 'https://github.com': nacnudus
Password for 'https://nacnudus@github.com': 
Counting objects: 36, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (22/22), done.
Writing objects: 100% (36/36), 25.07 KiB | 0 bytes/s, done.
Total 36 (delta 13), reused 36 (delta 13)
To https://github.com/nacnudus/crosstab-kiwi.git
 * [new branch]      gh-pages -> gh-pages
(pelican)nacnudus@nactop:~/crosstab-kiwi% 
```

**Comment by avaris** [comment]
Note that you're using `pelicanconf.py`:

    (pelican)nacnudus@nactop:~/crosstab-kiwi% pelican content -o output -s pelicanconf.py  

And you don't have `SITEURL` properly defined in that. Either fix `pelicanconf.py` or use `publishconf.py`.

**Comment by nacnudus** [comment]
Aha, that works.  In which case shouldn't http://docs.getpelican.com/en/latest/tips.html be fixed to use `publishconf.py`, since it currently uses `pelicanconf.py`?  I got the above script from the docs.
