### ISSUE TITLE
Content.url_format needs a new name and doc string

### ISSUE THREAD

**Issue by foresto** [getpelican/pelican#1535]
The `Content.url_format` property looks like it has changed so much over time that it no longer does anything resembling what its name and doc string describe. It probably ought to be a method instead of a property, private since it is apparently called only by `_expand_settings()`, and named something like `_get_url_substvars()`.

I nearly submitted a patch for this, but since I don't know whether there are plugins out there in the world depending on this property, I figured it would be best to get the opinion of the long-time Pelican maintainers.

**Comment by justinmayer** [comment]
@foresto: What do you think should be done here?
