### ISSUE TITLE
CRITICAL: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by webinista** [getpelican/pelican#1536]
I'm running Pelican 3.5 on Python 2.7.6 using `virtualenv` on Yosemite (10.10.1). When I run Pelican I get the following error: `CRITICAL: can't compare offset-naive and offset-aware datetimes`.

**Comment by zackw** [comment]
@robclancy I think "A date in the future should get `status=draft` regardless of what it says in the article metadata" should maybe be tracked as a separate issue from "`WITH_FUTURE_DATES=False` causes pelican to crash."

**Comment by schneiderfelipe** [comment]
I just had the same problem. As it turns out, I had `DEFAULT_METADATA = {"status": "draft"}` in `pelicanconf.py`. Commenting the line "fixed" the issue. Removing all plugins wasn't enough.

I'm using Pelican 4.2.0 on Python 3.6.9.

**Comment by avaris** [comment]
This should be fixed in the current master via cff6a829

**Comment by schneiderfelipe** [comment]
> This should be fixed in the current master via [cff6a82](https://github.com/getpelican/pelican/commit/cff6a829c2c3962f0c0d7a706d4bc6791966ce20)

Yes, solved! Thanks!
