### ISSUE TITLE
Early Typogrify-cation breaks jinja2content plugin and Markdown's attr_list

### ISSUE THREAD

**Issue by kernc** [getpelican/pelican#1543]
Typogrify running [before](https://github.com/getpelican/pelican/blob/b35759224825c72ea7789193ddb246881a537454/pelican/readers.py#L468) `content_object_init` signal breaks (at least) [jinja2content](https://github.com/joachimneu/pelican-jinja2content) plugin (featured in `pelican-plugins`).
Afaik there are no drawbacks in applying Typogrify after `content_object_init` handlers have run? If so, would be happy to submit a PR.

**Comment by justinmayer** [comment]
Hi @kernc. Is this something you would be willing to help us fix?

**Comment by leotrs** [comment]
@kernc, I wrote [this](https://github.com/leotrs/pelican-jinja2content) as a replacement for jinja2content. Please try it out and let me know if same problems persist.

**Comment by justinmayer** [comment]
[jinja2content](https://github.com/getpelican/pelican-plugins/tree/master/jinja2content) is now in the Pelican Plugins repo, so if it needs to be modified to address this topic, PRs there are welcome.
