### ISSUE TITLE
 develop_server.sh should clear cache folder

### ISSUE THREAD

**Issue by znotdead** [getpelican/pelican#1544]
develop_server.sh should clear before start as it is used only for development.

For example, changing css_class of codehilite plugin of MD_EXTENSIONS doesn't give any changes if articles already cached and restart of dev server doesn’t helped.

**Comment by justinmayer** [comment]
What do you think, @smartass101?

**Comment by smartass101** [comment]
That's again the question of whether to cache by default or not. @znotdead, you can simply put `LOAD_CONTENT_CACHE = False` into your `pelicanconf.py` (assuming that settings file is used by your develop env).

**Comment by justinmayer** [comment]
This should be addressed in 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html). Caching is now disabled by default.
