### ISSUE TITLE
`category.slug` is not honored when determining URLs for articles

### ISSUE THREAD

**Issue by zackw** [getpelican/pelican#1547]
I'm trying to write a plugin which allows me to manually adjust the slug for a category, i.e. the thing which goes into the URL when you put `{category}` in `ARTICLE_URL` and friends.  I have it working, except that `category.slug` is *ignored* by `Content.url_format` (in favor of `slugify(category)`, which uses the *name*, so the generated pathname for the category itself honors the slug setting, but the generated pathnames for articles in the category don't.

It appears to me that this is a straight-up bug in `Content.url_format`, possibly due to its having been written before `URLWrapper` objects were a thing?

**Comment by justinmayer** [comment]
Addressed via above-mentioned pull request.
