### ISSUE TITLE
pelican-quickstart: optionally create .gitignore

### ISSUE THREAD

**Issue by lathan** [getpelican/pelican#1548]
When starting a pelican blog, the thing I do after `pelican-quickstart` and before `git init`, is to fetch the `.gitignore` from [here](https://github.com/getpelican/pelican-blog/blob/master/.gitignore). Maybe it makes sense to provide this in `pelican-quickstart`.

**Comment by shrayasr** [comment]
+1

**Comment by justinmayer** [comment]
I totally understand the motivation, but the only line in that file that is relevant is:

    output

The rest are not Pelican-specific and therefore belong in users' own global `~/.gitignore` file. (In fact, I should remove the other lines in that file you referenced.)

Personally, I always re-locate the output directory so it's not mixed in with my source content, obviating the need to ignore `output`.

Last but not least, I'm concerned that posing too many questions to new users defeats the spirit of a "quick start" process. If someone knows how to use Git, would they not know how to `echo "/output/" > .gitignore`?

With all that said, do you still think it makes sense to do this?

**Comment by lathan** [comment]
> Last but not least, I'm concerned that posing too many questions to new users defeats the spirit of a "quick start" process.

I agree here.

And I just realized that git isn't handled at all by `pelican-quickstart` so maybe `.gitignore` shouldn't be either. If git was managed by quickstart, then it would make sense to just create a .gitignore with `output`, without asking. Thanks for the reply though.

**Comment by shrayasr** [comment]
@justinmayer some really great points there. 

> With all that said, do you still think it makes sense to do this?

No, not really. Thanks for explaining this though.

**Comment by kylef** [comment]
Also remember, Pelican is not limited to be used with git. There is nothing specific to git in Pelican. git is just a way to version your content, you could achieve the same with mercurial, svn, bazar, flat files in a folder. A user running `pelican-quickstart` might not be using version control, or might be using something else like mercurial.

**Comment by justinmayer** [comment]
Kyle is totally right, of course. We shouldn't assume everyone uses Git.

Thanks again for the suggestion, though!

**Comment by shrayasr** [comment]
> A user running pelican-quickstart might not be using version control, or might be using something else like mercurial.

Spot on. Its really a habit issue I guess :sweat_smile:

**Comment by snosratiershad** [comment]
> With all that said, do you still think it makes sense to do this?

@justinmayer, I think there is another cases other that `output` directory to be gitignored (`__pycache__`,  virtualenvs, etc.).

> Also remember, Pelican is not limited to be used with git.

@kylef Yes but when we support something like GitHub Pages, I don't think it's deal-breaker to add some git-specific configurations
