### ISSUE TITLE
PEP8 / flake8 compliance PR needed?

### ISSUE THREAD

**Issue by ajferrick** [getpelican/pelican#1552]
I read in the documentation that Pelican tries to adhere to PEP8 / flake8 as much as possible. I ran just `pep8` against the repository (`4add2d344bd7855575cf07e9610956bc7069b7f3`) and saw some violations.

I'm just starting to dig into the Pelican codebase, and thought fixing these violations would be a good way to get broad exposure. Would it be worthwhile for me to submit a PR fixing the violations?

**Comment by honzajavorek** [comment]
If there are meaningful divergences from PEP8, mark them with `# NOQA` comment (and possible explanation why the divergence makes sense) and the tools will ignore it.

**Comment by ingwinlu** [comment]
@justinmayer since we do have a pep8 checks in place now can we close this issue to avoid necroing it?

**Comment by leotrs** [comment]
This can be closed.
