### ISSUE TITLE
Override docutils configuration: doctitle_xform and docinfo_xform

### ISSUE THREAD

**Issue by saaj** [getpelican/pelican#1553]
This began like a pretty weird situation, very untypical to my Python experience. Pelican failed on simplest article presented in the docs, relevant tests failed, but at the same time I've seen it passes the tests in TravisCI just fine. Also there were enough people complaining about the same error (#1394, #1231, #1210).

I took `pelican/tests/content/article_with_metadata.rst`.
```

This is a super article !
#########################

:tags: foo, bar, foobar
:date: 2010-12-02 10:14
:modified: 2010-12-02 10:20
:category: yeah
:author: Alexis Métaireau
:summary:
    Multi-line metadata should be supported
    as well as **inline markup** and stuff to "typogrify"...
:custom_field: http://notmyidea.org
```
And it failed to build with: 
```
ERROR: Skipping ./qooxdoo.rst: could not find information about 'date'
```
The corresponding test, `pelican.tests.test_readers.RstReaderTest.test_article_with_metadata` failed as well. I started to debug the problem, which took several hours, and since [this commit](https://github.com/getpelican/pelican/commit/cacc6db9a4cbbce979e4ebf90c93c770f6359453) Pelican relies on `docutils` to parse metadata, I've ended up with it.

Problem in nutshell. The following code:
```
from io import StringIO
import docutils.core

source = StringIO(u'''
The title
=========

:date: 2010-12-02

Some text.
''')

pub = docutils.core.Publisher(destination_class=docutils.io.StringOutput)
pub.set_components('standalone', 'restructuredtext', 'pseudoxml')
pub.process_programmatic_settings(None, None, None)
pub.set_source(source)

ml = pub.publish()
print(pub.document.traverse(docutils.nodes.docinfo))
print(ml.decode())
```
Depending on configuration may result in Pelican-expected:
```
[<docinfo: <date...>>]
<document ids="the-title" names="the\ title" source="None" title="The title">
    <title>
        The title
    <docinfo>
        <date>
            2010-12-02
    <paragraph>
        Some text.
```
And may be this, which leads to blank metadata and title:
```
[]
<document source="None">
    <section ids="the-title" names="the\ title">
        <title>
            The title
        <field_list>
            <field>
                <field_name>
                    date
                <field_body>
                    <paragraph>
                        2010-12-02
        <paragraph>
            Some text.
```
The culprit is pair of `doctitle_xform` and `docinfo_xform` from [standalone reader configuration](http://docutils.sourceforge.net/0.6/docs/user/config.html#standalone-reader). If either is set to false, Pelican breaks. I don't know where exactly it has come from, but I had the following in `~/.docutils`.
```
[standalone reader]
doctitle_xform = false
```
Note about `docutils` publisher API and [configuration](http://docutils.sourceforge.net/0.6/docs/user/config.html#configuration-files) override rules. It is ugly, illogical and unpythonic (e.g. `Publisher.get_settings` is in fact a mutator). There are three default configuration files, lower overrides upper:

* /etc/docutils.conf
* ./docutils.conf
* ~/.docutils

Thus user home directory file take precedence, so placing `docutils.conf` is Pelican directory won't help. What's more ridiculous is that configuration from files takes precedence over `settings_overrides` argument to `Publisher.process_programmatic_settings`, and Pelican `DOCUTILS_SETTINGS` won't help as well. It's necessary to override settings attributes directly:
```
from io import StringIO
import docutils.core

source = StringIO(u'''
The title
=========

:date: 2010-12-02

Some text.
''')

pub = docutils.core.Publisher(destination_class=docutils.io.StringOutput)
pub.set_components('standalone', 'restructuredtext', 'pseudoxml')
pub.process_programmatic_settings(None, None, None)

pub.settings.doctitle_xform = True
pub.settings.docinfo_xform = True

pub.set_source(source)

ml = pub.publish()
print(pub.document.traverse(docutils.nodes.docinfo))
print(ml.decode())
```
And `pelican.readers.RstReader._get_publisher` should be changed accordingly.

**Comment by idahogray** [comment]
I attempted fix this in my own fork but I still have the same problem. I am willing to test any patches.

**Comment by justinmayer** [comment]
Pelican 3.6, [which was just released](http://blog.getpelican.com/pelican-3.6-released.html), now disables caching by default. If this issue persists, please comment here and I will re-open.

**Comment by saschwarz** [comment]
I just ran in to this same error and I'm reporting what my real problem was in hopes it helps someone else.  In my .rst file I had
```
Title
#####
:date: 2015-11-29 15:00
:author: me

some content

Subtitle
########

more content
```

It turns out I was getting the error  because the title of the post and the subtitle had the same type of underline. The error went away once I changed the title to:
```
#####
Title
#####
```
