### ISSUE TITLE
Architecture feature: allow other input than file on disk

### ISSUE THREAD

**Issue by adrianandreias** [getpelican/pelican#1554]
Would be nice for pelican to accept other sources of content, besides files on disk.
I had a look through the code and noticed it is pretty tide to files on disk right now:
https://github.com/getpelican/pelican/blob/b4ae60b3d021bc359b289de9bdea5bd6ca89aa2f/pelican/readers.py#L237
https://github.com/getpelican/pelican/blob/b4ae60b3d021bc359b289de9bdea5bd6ca89aa2f/pelican/utils.py#L233-L240

Readers could accept streams and strings of data.
This opens a lot of possibilities allowing pelican to be used as a library (that's a another topic, didn't check the code yet to see if pelican can be used as a library from other point of views, mainly separation of concerns in modules :) ).

You could for instance have CMS editor that runs on database* and provide content from database to pelican for rendering.

* Yeah, I know that's the opposite of the Pelican philosophy, having a non-monolithic architecture really  opens up possibilities to numerous use cases.

**Comment by justinmayer** [comment]
@adrianandreias: Feel free to elaborate and we can re-open this issue as necessary.
