### ISSUE TITLE
DEFAULT_ORPHANS inconsistent with documentation

### ISSUE THREAD

**Issue by kernc** [getpelican/pelican#1568]
The documentation for `DEFAULT_ORPHANS` setting says:
> The minimum number of articles allowed on the last page. Use this when you don’t want the last page to only contain a handful of articles.

However, with
```
DEFAULT_PAGINATION = 1
DEFAULT_ORPHANS = 1
```
and with **three articles** paginated, one appears on the first page and two on the second. The same setup with `DEFAULT_PAGINATION = 2` produces a single, unpaginated page.

So it seems that `(DEFAULT_ORPHANS + 1)` is the _minimum number of articles allowed on the last page_.

**Comment by leotrs** [comment]
@kernc can you still replicate this?

**Comment by kernc** [comment]
Seems so. With pelican git, given three articles in a paginated category,
```text
DEFAULT_PAGINATION = 1
DEFAULT_ORPHANS = 1
```
results in two pages (1+2). Expected are three pages (1+1+1).

Likewise,
```text
DEFAULT_PAGINATION = 2
DEFAULT_ORPHANS = 1
```
results in a single, unpaginated page. Expected are two pages (2+1).

Both of these behaviors are inconsistent with docs for `DEFAULT_ORPHANS`.

Setting in both above cases `DEFAULT_ORPHANS = 0` results in expected behavior (as noted above). This seems to indicate `DEFAULT_ORPHANS` is really interpreted as `DEFAULT_ORPHANS + 1`.

**Comment by leotrs** [comment]
Sounds like a change in documentation could solve this issue. PRs are welcome.

**Comment by kernc** [comment]
That would be the easy and probably invalid fix. Got something better in https://github.com/getpelican/pelican/pull/1992, I hope. :smiley:

**Comment by kernc** [comment]
Resolution: invalid https://github.com/getpelican/pelican/pull/1992#issuecomment-239975458.
Thanks.
