### ISSUE TITLE
Pagination breaks in default notmyidea template when last page contains a single item

### ISSUE THREAD

**Issue by ehashman** [getpelican/pelican#1572]
Encountered this bug when I enabled pagination and the last page contained a single item. When this occurs, the page structure breaks, displaying stray footer elements floating around the page. I am using Pelican v3.5.0; from my investigation below, I've confirmed the bug still exists in master.

**Steps to reproduce:** start a new Pelican website with 2 articles, set `DEFAULT_PAGINATION = 1`, and view the second page (likely index2.html).

**Fix:** In the default notmyidea template, we have three [`loop.length > 1` checks](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/index.html#L45-L51). If `loop.length == 1` and the item wasn't the first in the loop, these checks will fail; thus, closing tags never get inserted, breaking the page.

If loop.length is non-zero, `if loop.last` should always return true, so I believe we can simply remove the `> 1` checks. I can submit a PR [(see diff)](https://github.com/ehashman/pelican/compare/issue1572), but I'm wondering if I should confine it to this change or if you'd prefer that I first check that other instances of this bug don't exist.

**Comment by ehashman** [comment]
I'm not sure if the fix above actually works (iirc it broke the tests) but here's an example of this bug out in the wild, on Pelican 3.6.0: http://wics.uwaterloo.ca/tags/big-csters/2/

**Comment by justinmayer** [comment]
In my testing earlier this week, this fix did indeed address the problem.

**Comment by justinmayer** [comment]
This should be addressed in 3.6.1.
