### ISSUE TITLE
pelican-quickstart UI

### ISSUE THREAD

**Issue by webglider** [getpelican/pelican#1576]
Presently pelican-quickstart offers users a CLI enabling them to quickly setup a new pelican blog. The prompts which appear may confuse a beginner (due to lack of description or because the user does not have an exhaustive list of allowed options) Also as pelican advances, more prompts may need to be added and that will make it worse.
One solution to this would be to provide a GUI for the quickstart process. 
The idea which I have in mind is the following:
When the quick start script starts, we can run a simple web server which listens on a specific port.  The user is presented a simple form when the browser is pointed to this location which upon submission completes the required quickstart process.

**Comment by iKevinY** [comment]
This is closely related to #1601.

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this in favor of the aforementioned issue.
