### ISSUE TITLE
Cannot change articles directory properly

### ISSUE THREAD

**Issue by Nevralgeek** [getpelican/pelican#1580]
I have some troubles with Pelican when I try to generate the articles in some subdirectories (I use the subcategory plugin).
I create them in __content/category/subcategory/article.html__

Here is my conf : 
```python
    PATH = 'content'
    STATIC_PATHS = ['category', 'images', 'pages', 'pdf']
    ARTICLE_SAVE_AS = '{category}/{slug}.html'
    ARTICLE_URL = '{category}/{slug}.html'
```

Everything works great, but the tags links don't work.
Their URL is __website/category/tag/tag.html__ which leads to a 404 because tags are generated in __website/tag/tag.html__

I tried to change it with __TAG_URL__ and __TAG_SAVE_AS__ but it's pointless.

**Comment by alistairmagee** [comment]
I'll have a look over the next couple of days. My first thought is that it shouldn't be the subcategory plugin as it doesn't affect the generation of tags at all. Would you mind sharing the rest of your pelican conf and what other plugins you are using? 

What did you try with the TAG_URL and TAG_SAVE_AS?

**Comment by justinmayer** [comment]
Hi @Nevralgeek. Were you able to resolve your problem?

**Comment by justinmayer** [comment]
Please comment here if the issue persists. Thanks!
