### ISSUE TITLE
STATIC_PATHS file not being recognized as a article instead of page. 

### ISSUE THREAD

**Issue by rawrgulmuffins** [getpelican/pelican#1587]
I'm receiving this error when attempting to use a static page.

`ERROR: Skipping extra/google69b9c0096934230f.html: could not find information about 'title'`

```
STATIC_PATHS = ['extras']
EXTRA_PATH_METADATA = {
        'extra/google69b9c0096934230f.html': 
            {'path': 'google69b9c0096934230f.html',}}
```

From what I have read in the documentation this page should just be read without being run through the mark down processor. 

Pelican version and python version 
```
$ pelican --version
3.5.0
$ python --version
3.4.0
Ubuntu 14.04
```

**Comment by iKevinY** [comment]
From the information provided, it looks like you've configured the "extras" directory to be ignored but file is in `extra/` (not plural).

**Comment by avaris** [comment]
If that path is included in either `ARTICLE_PATHS` or `PAGE_PATHS`, then pelican will try to process it using the `HTMLReader`. And if you don't define them, then the default `ARTICLE_PATHS` (which is `['']`, i.e. root of your content folder) will include that.

You have a few options depending on your setup:
 * If possible, you can narrow down `ARTICLE_PATHS` and/or `PAGE_PATHS` so that the file/folder is not included
 * You can put `'extras'` in `ARTICLE_EXCLUDES` and/or `PAGE_EXCLUDES` to notify pelican that the folder is not for Article/Page sources
 * You can disable `HTMLReader` by `READERS = {'html': None}` if you're not using it

PS: Pelican will auto-include `PAGE_PATHS` into `ARTICLE_EXCLUDES` (and vice versa) but that's not the case for `STATIC_PATHS` because they are not necessarily mutually exclusive like `Page` and `Article`. A static file can be next to your content sources.

**Comment by justinmayer** [comment]
Hi Alex. Were you able to resolve your problem?

**Comment by stevengorrell** [comment]
I'm having similar trouble with STATIC_PATHS.

     PAGE_EXCLUDES = ['extra']
     ARTICLE_EXCLUDES = ['extra']
     STATIC_PATHS = ['extra']
     EXTRA_PATH_METADATA = {'extra/keybase.txt': {'path': 'keybase.txt'},}

The expected behavior is that keybase.txt is put in the root, however but it keeps being placed in the extra directory inside content:

     PS C:\Users\WebDev\Documents\GitHub\TestSite> pelican content -D
     DEBUG: Adding current directory to system path
     DEBUG: Temporarily adding PLUGIN_PATHS to system path
     DEBUG: Restoring system path
     DEBUG: Template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html',      u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.     html', u
     '!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html',      u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.     ht
     ml', u'analytics.html', u'archives.html', u'article.html', u'author.html', u'authors.html', u'base.     html', u'categories.html', u'category.html', u'gosquared.html', u'index.html', u'page.html',      u'pagina
     tion.html', u'period_archives.html', u'tag.html', u'tags.html', u'translations.html']
     DEBUG: Read file first-post.md -> Article
     DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
     DEBUG: Successfuly imported extension module "markdown.extensions.codehilite".
     DEBUG: Successfully loaded extension "markdown.extensions.codehilite.CodeHiliteExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.extra".
     DEBUG: Successfuly imported extension module "markdown.extensions.smart_strong".
     DEBUG: Successfully loaded extension "markdown.extensions.smart_strong.SmartEmphasisExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.fenced_code".
     DEBUG: Successfully loaded extension "markdown.extensions.fenced_code.FencedCodeExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.footnotes".
     DEBUG: Successfully loaded extension "markdown.extensions.footnotes.FootnoteExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.attr_list".
     DEBUG: Successfully loaded extension "markdown.extensions.attr_list.AttrListExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.def_list".
     DEBUG: Successfully loaded extension "markdown.extensions.def_list.DefListExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.tables".
     DEBUG: Successfully loaded extension "markdown.extensions.tables.TableExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.abbr".
     DEBUG: Successfully loaded extension "markdown.extensions.abbr.AbbrExtension".
     DEBUG: Successfully loaded extension "markdown.extensions.extra.ExtraExtension".
     DEBUG: Successfuly imported extension module "markdown.extensions.meta".
     DEBUG: Successfully loaded extension "markdown.extensions.meta.MetaExtension".
     DEBUG: Signal article_generator_context.send(ArticlesGenerator, <metadata>)
     DEBUG: Read file output\archives.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\archives.html      does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\archives.html: could not find information about 'date'
     DEBUG: Read file output\authors.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\authors.html      does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\authors.html: could not find information about 'date'
     DEBUG: Read file output\blank-slate.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\blank-slate.     html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\blank-slate.html: could not find information about 'date'
     DEBUG: Read file output\categories.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\categories.html      does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\categories.html: could not find information about 'date'
     DEBUG: Read file output\index.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\index.html does      not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\index.html: could not find information about 'date'
     DEBUG: Read file output\tags.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\tags.html does      not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\tags.html: could not find information about 'date'
     DEBUG: Read file output\author\WebDev.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\author\WebDev.     html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\author\WebDev.html: could not find information about 'date'
     DEBUG: Read file output\category\general.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\category\general     .html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\category\general.html: could not find information about 'date'
     DEBUG: Read file output\tag\writing.html -> Article
     WARNING: Meta tag in file C:\Users\WebDev\Documents\GitHub\TestSite\content\output\tag\writing.     html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
     ERROR: Skipping output\tag\writing.html: could not find information about 'date'
     DEBUG: Read file extra\keybase.txt -> Static
     DEBUG: Signal static_generator_preread.send(StaticGenerator)
     DEBUG: Signal static_generator_context.send(StaticGenerator, <metadata>)
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\2015/04/28/blank-slate/index.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\index.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\tags.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\categories.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\authors.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\archives/index.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\tag\writing.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\category\general.html
     -> Writing C:\Users\WebDev\Documents\GitHub\TestSite\output\author\WebDev.html
     -> Copying C:\Users\WebDev\Documents\GitHub\TestSite\content\extra\keybase.txt to extra/keybase.txt
     Done: Processed 1 article(s), 0 draft(s) and 0 page(s) in 0.69 seconds.

**Comment by avaris** [comment]
@stevengorrell windows paths were causing some issues (`\` vs `/`). Current master includes fixes for that. Did you try with 3.5 or the master?

**Comment by stevengorrell** [comment]
@avaris This was done with 3.5. I can upgrade to master and try again.

**Comment by stevengorrell** [comment]
@avaris That worked. Thank you very much!

**Comment by rawrgulmuffins** [comment]
This also fixed my issue.

**Comment by rawrgulmuffins** [comment]
Sorry I haven't been following the thread. I didn't receive notifications when other commented for some reason. I'll check to see if my issue is resolved today.
