### ISSUE TITLE
category_url and category_save_as doesn't seem to work

### ISSUE THREAD

**Issue by ludbek** [getpelican/pelican#1596]
I have following settings for category. But does not seem to work. The generated contents follow the default settings i.e. category/{slug}.html.
CATEGORY_URL = '{slug}/'
CATEGORY_SAVE_AS = '{slug}/index.html'

**Comment by avaris** [comment]
Did you try the note at the top of [settings docs](http://docs.getpelican.com/en/3.5.0/settings.html)?

> When experimenting with different settings (especially the metadata ones) caching may interfere and the changes may not be visible. In such cases disable caching with LOAD_CONTENT_CACHE = False or use the --ignore-cache command-line switch.

**Comment by ludbek** [comment]
thanx it worked
