### ISSUE TITLE
Verify external links on publish

### ISSUE THREAD

**Issue by jniggemann** [getpelican/pelican#1604]
Is there a plugin or piece of code to let me check all external links when building the site? This would, of course, take quite some additional time, but could report all 4xx and 5xx http errors...

I'm on pelican 3.5.0 / CentOS in case that matters.

**Comment by smartass101** [comment]
Not really, but you could use some BeautifulSoup code to parse the 
resulting HTML files and extract the links.
You'd have to hook into the the readers code to catch the links at 
generation time, but that would be a lot harder as many readers aren't 
ready for that.

**Comment by jniggemann** [comment]
OK so I'll probably just test-publish the site first, check it with `linkchecker` and if the latter returns 0 errors I'll publish for good...

**Comment by Lucas-C** [comment]
For reference, there is this plugin: https://github.com/silentlamb/pelican-deadlinks
