### ISSUE TITLE
Google Adsense or other ad services

### ISSUE THREAD

**Issue by KCastiglione** [getpelican/pelican#1606]
is it possible to integrate google adsense in the blog? How to do it?
How to add other scripts for showing ads from different providers?

**Comment by justinmayer** [comment]
Since ads are peripheral to the content, they don't really have much to do with Pelican's core functionality. You can add ads, if you wish, by customizing your theme.

**Comment by KCastiglione** [comment]
Thanks for following up, is there a guide or tutorial on how to do this?

**Comment by justinmayer** [comment]
I think our general docs on themes, as well as the plethora of existing themes to use as a reference, should be more than sufficient. I'm not aware of any guide specific to ads.
