### ISSUE TITLE
notmyidea theme: article pdf link is generated twice

### ISSUE THREAD

**Issue by foresto** [getpelican/pelican#1610]
While reading the notmyidea theme's templates, I noticed that the following code appears in both article_infos.html and taglist.html:

    {% if PDF_PROCESSOR %}<a href="{{ SITEURL }}/pdf/{{ article.slug }}.pdf">get the pdf</a>{% endif %}

Since article_infos.html includes taglist.html, I expect this generates a duplicate link for people who use the pdf plugin. The code should probably be removed from taglist.html.

**Comment by iKevinY** [comment]
Would it make sense to remove all `PDF_PROCESSOR`-related code from notmyidea since PDF generation was removed from Pelican's core in #1010?

**Comment by justinmayer** [comment]
Yea, I think it would.

**Comment by iKevinY** [comment]
@justinmayer Alright, I'll submit a PR addressing this shortly!
