### ISSUE TITLE
Please don’t delete old releases from PyPI

### ISSUE THREAD

**Issue by sscherfke** [getpelican/pelican#1611]
It would be *realy* nice if you could keep older releases of Pelican on PyPI.

We test our Pelican sites with a fixed configuration of dependencies (a `requirements.txt` with `package==x.y.z` entries) in order to make sure they build on the server. In the past we had some issues with “just install the latest version of everything” so we want to be in control of which versions we use when we setup venvs on a production server.

**Comment by avaris** [comment]
It's not intentional, see #1522.
