### ISSUE TITLE
Remove an article from the website

### ISSUE THREAD

**Issue by yw5aj** [getpelican/pelican#1613]
Dear all,

First of all, apologies if this is not the best place to post questions - I tried to find a mailing list or google groups page for pelican, but did not find any.

My question is - is there a way to remove an article from the blog site created by `pelican-quickstart`?

Thank you!

Shawn

**Comment by claman** [comment]
Yep! Just delete the appropriate file from the `content` folder

**Comment by yw5aj** [comment]
Ah sorry about missing this obvious action. Thanks! :)

Shawn

**Comment by luzfcb** [comment]
@yw5aj close this issue
