### ISSUE TITLE
Using Pelican's Configuration with Fabric

### ISSUE THREAD

**Issue by nfarrar** [getpelican/pelican#1619]
I'm using fabric, rather than Make to manage pelican. The default `fabfile.py` hardcodes the OUTPUT_PATH, which I didn't love. I came up with a (poor but working) solution to import the hardcoded configuration values from `pelicanconf.py` & `publishconf.py`, but pelican has some internal logic that generates default variables that I'm unsure how to access.

Here's what I've got right now:

    # Import pelicanconf.py as a module. If we're running the publish command, load
    # publishconf.py.
    if len(sys.argv) >= 2:
        if sys.argv[1] != 'publish':
            env.PELICANCONF='pelicanconf.py'
            import pelicanconf
        else:
            env.PELICANCONF='publishconf.py'
            import publishconf as pelicanconf

        # Inject all the uppercase globals from the pelicanconf into fabric's shared
        # state variable (env).
        for key in pelicanconf.__dict__.keys():
            if key.isupper():
                env.__setattr__(key, pelicanconf.__dict__[key])

        # Set a default path for the output directory, in case we haven't set it in
        # PELICAN_CONF.
        try:
            env.__getattr__('OUTPUT_PATH')
        except:
            env.__setattr__('OUTPUT_PATH', 'output')

        # Set ports for our live reload server.
        env.__setattr__('LIVE_RELOAD_PORT', 35279)
        env.__setattr__('DEV_SERVER_PORT', 80

The full configuration is [here](https://github.com/nfarrar/nfarrar.github.io/blob/source/fabfile.py). If possible, I'd like to hook pelican somehow to pull computed configuration out and into the fabfile. Any ideas?

**Comment by LudoVio** [comment]
hi
    from pelican.settings import read_settings
    settings = read_settings('pelicanconf.py')

**Comment by LudoVio** [comment]
for change settings and put it in pelicanconf.py I think you should use the module tokenize for something clean. If you want something fast and dirty you can something like this:

from os.path import relpath, isabs

# load default and user settings:
default = read_settings()
user = read_settings('pelicanconf.py')

result = ""
del user['FEED_DOMAIN']
for setting, value in user.items():
    if value and setting.find('PATHS') != -1:
        value = [isinstance(path, unicode) and isabs(path) and relpath(path) or path for path in value]
    elif value and setting.find('PATH') != -1:
        print setting, value
        value = isinstance(value, unicode) and isabs(value) and relpath(value) or value
    if setting not in default or value != default[setting]:
        result += setting + " = " + repr(value) + "\n"

with open('pelicanconf.py') as flux:
    flux.write(result)

it's probably not 100% and will need some cleaning to add, i just tried on a basic pelicanconf.py

**Comment by justinmayer** [comment]
Please comment here if you're still looking for input. Thanks!
