### ISSUE TITLE
Excluding Pages from DEFAULT_METADATA

### ISSUE THREAD

**Issue by nfarrar** [getpelican/pelican#1620]
When I set the following in pelicanconf.py:

    DEFAULT_METADATA = {
        'status': 'draft',
    }

My pages break:

    ERROR: Unknown status 'Published' for file pages/about.md, skipping it.

In `PATH` I have the directories 'pages' and 'posts'. I attempted to fix this by explicitly setting:

    ARTICLE_PATHS = ['posts']
    PAGE_PATHS = ['pages']

However this still generates the same errors for pages. Any suggestions?

**Comment by iKevinY** [comment]
I tested this locally, and it seems like you need to use `Status: published` (it's case-sensitive). That being said, perhaps the status check *should* be case-insensitive. Thoughts, @justinmayer?

**Comment by avaris** [comment]
It *should* be case-insensitive, `ArticlesGenerator` [does that](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L517). For some odd reason, it was [omitted](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L644) in `PagesGenerator`. So, this is a bug.

**Comment by iKevinY** [comment]
@avaris Ah, thanks for confirming. Do you mind if I submit a PR fixing this?

**Comment by avaris** [comment]
@iKevinY not at all :), I can't submit a PR tonight anyway, so go ahead.

**Comment by nfarrar** [comment]
So, I'm trying to understand what's going on here - I went back and checked the [docs](http://docs.getpelican.com/en/3.5.0/settings.html) and the first thing I noticed was that my syntax was not written the way the docs say it should be, so I adjusted this to:

    DEFAULT_METADATA = (
        ('Status', 'draft'),
    )

... and also using 'draft' (undercase) as you mentioned above. This still generates an error for markdown pages:

    ERROR: Unknown status 'draft' for file pages/about.md, skipping it.

- If I set `Status: draft` on the `about.md` page itself, the same error is generated.
- If I set `Status: published` on the page, no errors are generated.

So it looks like right now you can't set the status of a page to anything except `published`.

This is a separate issue, but also related to `DEFAULT_METADATA`: I set (I also tried using a list, and unicode strings, but nothing worked):

    DEFAULT_METADATA = (
        ('Authors', 'Nathan Farrar'),
    )

Then I get a different unicode error:

    CRITICAL: 'unicode' object has no attribute 'name'

It looks like the `AUTHORS` issue was already reported [here](https://github.com/getpelican/pelican/issues/1542).

**Comment by iKevinY** [comment]
@nfarrar If I remember correctly, for pages, the two types of statuses are `published` and `hidden` rather than `published` and `draft`. Also, I believe it doesn't matter if you use a dictionary or a list of tuples to define `DEFAULT_METADATA` because it gets converted to a dictionary using `dict()` either way. I submitted a PR that attempts to clarify this ambiguity (#1593).

**Comment by vojtechkral** [comment]
@iKevinY  Hi, sorry for necroposting, but I ran into this issue. I was wondering, have you considered making `hidden` and `draft` a synonym? Are they, in fact, any different? I may have missed something, but right now it seems needlesly complex and cumbersome to have articles and pages recognize a different "not-published" status.

**Comment by iKevinY** [comment]
@vojtechkral I agree that `hidden` and `draft` essentially serve the same purpose. I'm not sure if there's any history behind them _not_ being synonyms  — maybe @justinmayer has some insight here?

**Comment by justinmayer** [comment]
@iKevinY: From a practical perspective, I can't think of any relevant differences off the top of my head, possibility excepting the output path. (I think all drafts are output to a single location.)

**Comment by justinmayer** [comment]
Thanks to @oulenz, pages can now have `draft` status. 🎉
