### ISSUE TITLE
Use AWSCLI instead of s3cmd for publishing to AWS S3 bucket

### ISSUE THREAD

**Issue by vlcinsky** [getpelican/pelican#1626]
Current `make` command (see [tools/templates/Makefile.in](https://github.com/getpelican/pelican/blob/3b22dd4f2df285f7511ae2439808cd3964ec6ca7/pelican/tools/templates/Makefile.in#L109)) file is for publishing to AWS S3 bucket using command `s3cmd`

Nowadays, there is much more widely used tool called AWSCLI which is able doing the same job very well.

My current `Makefile` is modified as follows:

```
s3_upload: publish
    #s3cmd sync $(OUTPUTDIR)/ s3://$(S3_BUCKET) --acl-public --delete-removed --guess-    mime-type
    aws s3 --profile ttr sync $(OUTPUTDIR)/ s3://$(S3_BUCKET) --acl public-read --delete
```

**Comment by justinmayer** [comment]
Hi Jan. Would you like to submit a pull request implementing the change you are suggesting?

**Comment by syndbg** [comment]
I've got mixed feelings about this.

While `aws-cli` is modern and definitely the standard approach when using S3, it introduces a lot of new dependencies.


If there are ideas to add more s3 commands, I see a good reason to use `aws-cli`, otherwise is it really worth it for just 1 command?

**Comment by cossatot** [comment]
I am reviving a blog neglected for a few years.  In the interim, I've abandoned Python 2, and `s3cmd` doesn't support Python 3 (and seems to have no plan to). This seems like a reasonable reason to change the command used to upload to S3; it'd be unfortunate for some amount of Pelican to be tied to Python 2 because of one ancillary dependency.

**Comment by sevagh** [comment]
Similar experience to @cossatot - s3cmd requires Python 2 and in my case, it couldn't predict the correct MIME type (even with magic disabled). With the aws cli I use:

    aws s3 sync --delete output/ s3://{BUCKET_URL}

**Comment by justinmayer** [comment]
Pull requests are welcome. Anyone want to implement this change?

**Comment by sevagh** [comment]
Just thinking out loud here, but what if the Makefile was reduced to only the commands which generate and serve $(OUTPUTDIR) - i.e. remove the gh-pages, s3, dropbox, all those vendor-specific hosting rules.

Does it make Pelican too difficult to use if it went like "OK, static files generated, now you take $(OUTPUTDIR) and do what you need to do to host it wherever you want".

**Comment by vlcinsky** [comment]
Hi all
Still watching but too busy to find time for proper reaction (a pull request).

Meantime I have learned:

- boto (and s3cmd) are now really obsolete - see reactions to issue [`boto3` is not a replacement of `boto` (yet?)](https://github.com/boto/boto/issues/3306)
- awscli is actively mantained by Amazon and we shall expect it to continue it this way
- I use [doit](http://pydoit.org/) as great replacement of `make` to be less dependent on non-python tools.
-
