### ISSUE TITLE
Gracefully handle invalid cache files

### ISSUE THREAD

**Issue by robertlagrant** [getpelican/pelican#1630]
E.g. when moving to a new version of Python. Just if you can't read (unpickle, etc) the cache file, maybe have a setting that catches the error, logs it, and deletes and recreates the cache file, so it'll work next time.

**Comment by avaris** [comment]
It should already do that. Are you getting an unhandled exception? If so, showing the error would help.

**Comment by justinmayer** [comment]
@robertlagrant: Any additional detail you can provide on this?

**Comment by robertlagrant** [comment]
Sorry, possibly this is just a documentation issue. Docs say:

The cache files are Python pickles, so they may not be readable by different versions of Python as the pickle format often changes. If such an error is encountered, the cache files have to be rebuilt by removing them and re-running Pelican, or by using the Pelican command-line option --ignore-cache. 

I was suggesting an automatic handling of that case. Apologies if it's no longer an issue.

**Comment by smartass101** [comment]
If the Pickle protocol is different a `ValueError: unsupported pickle protocol` should be raised [which is caught](https://github.com/getpelican/pelican/blob/master/pelican/utils.py#L658) and the cache is rebuilt. I agree that the docs kinda don't make it clear that it works this way, so a PR with doc improvements is welcomed @robertlagrant
