### ISSUE TITLE
Picture Slide with restructured Text

### ISSUE THREAD

**Issue by mgiaco** [getpelican/pelican#1634]
Does anybody know how to achieve a picture Slide in a pelican? Like this one on this Page on the End?
http://www.homebaking.at/croissant/  I do not need the auto play feature but i would be great if it is possible to embed some picture with a left right button.

So Is it possible with pelican in any way? In Nikola it is possible but i would not switch from pelican. I found the Gallery plugin but the Link does not work. Maybe this plugin would help me but i do not know how to use it only with the read me.

thank´s for the help
regards
mathias

**Comment by DirkR** [comment]
The slideshow is done by the jquery.cycle.js. ou can embed this library into your website.

They have a "getting started" guide on their website: http://jquery.malsup.com/cycle/begin.html

If you are writing your content in Markdown, then you can embed the HTML code directly into your posts.
Add the CSS code to your theme's CSS and add the javascript code into your theme as well.

Best regards
Dirk

**Comment by mgiaco** [comment]
@DirkR thanks - sorry for the late response. I was so busy, that looks really nice I will give it a try.

But in the meantime I found a Pelican Blog http://www.pxquim.pt/  => on Fotografia is a nice picture handling - sliding. That´s what I am searching for.

I contacted @pxquim via Email how he arranged that with pelican and  md or rst. If I get an answer I will try to share it anywhere - because the picture handling is not really user friendly documented in pelican :-) i think.

Best regards,
Mathias

**Comment by pxquim** [comment]
I just shared some code with @mgiaco via email, but it is for Pelican 3.3.0 at this time. I will post a plugin as soon as I clean up and update the code.

In a related matter, I must also refactor code to a different "sub_article" plugin, which was my solution to associate multiple galleries with a single article.

**Comment by pxquim** [comment]
I just submitted a pull-request getpelican/pelican-plugins#454 for the new Photos plugin. Although a dirtier variant of the plugin has managed ~40k photos in http://pxquim.pt for over an year, I am still not quite convinced that I got the plugin right. Comments?
