### ISSUE TITLE
Use absolute url to static files on feed RSS and ATOM

### ISSUE THREAD

**Issue by luzfcb** [getpelican/pelican#1640]
Currently, the generated rss file, the static files are referenced relatively. This causes problems if some website shows (renders) the contents of the rss file.

I discovered this behavior after registering the rss of my blog in http://planetpython.org/  ( https://github.com/python/planet ) and see that the images are not displayed correctly

**Comment by justinmayer** [comment]
This occurs when `SITEURL` is not defined. I suggest you define it.

**Comment by luzfcb** [comment]
SITE_URL is defined correctly : https://github.com/pythonclub/pythonclub.github.io/blob/pelican/pelicanconf.py#L12



The error was the image declaration in the wrong way

To fix, I did as described in the comment https://github.com/getpelican/pelican/issues/1639#issuecomment-75707383:

Use:
```.. image:: {filename}images/ramalho/Tweedledum-Tweedledee_500x390.png```

instead of

```.. image:: images/ramalho/Tweedledum-Tweedledee_500x390.png```
