### ISSUE TITLE
make PATH_METADATA and FILE_METADATA lists

### ISSUE THREAD

**Issue by fragfutter** [getpelican/pelican#1644]
To extract multiple, possibly overlapping, items from a path, it would be nice to make the metadata configuration options a list of multiple regular expressions. 

for example one pattern to extract an id at the end of a filename, and a seconds pattern to get the filename without extensions would overlap.

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
