### ISSUE TITLE
Improperly formatted time in restructured text results in error

### ISSUE THREAD

**Issue by rajbala** [getpelican/pelican#1646]
This isn't so much a bug with Pelican (I don't think), but a note to someone who encounters this problem in the future.  Sorry if this isn't the correct place to put this.  

A time in an RST file formatted with a dash rather than a colon this generates error:

    CRITICAL: tzinfo.utcoffset() returned 1440; must be in -1439 .. 1439

This works fine:

```
My super title
################

:date: 2010-10-03 20:20
:authors: Alexis Metaireau, Conan Doyle
:summary: Short version for index and feeds
```

This does not:

```
My super title
################

:date: 2010-10-03 20-20
:authors: Alexis Metaireau, Conan Doyle
:summary: Short version for index and feeds
```

**Comment by justinmayer** [comment]
I've never seen time formatted as `20-20` before. Is that a standard convention in some parts of the world?

**Comment by rajbala** [comment]
Don't think so to be honest.  It was typo in my code that resulted in RST files being generated like this, but it was hard to track down because of a bunch of reasons that are particular to my code/deployment.

Google searches for that error basically lead to no where, so I thought I would save someone a little time in the future.

**Comment by justinmayer** [comment]
Gotcha. Thanks for clarifying.
