### ISSUE TITLE
[rst] figure - scale and align directives don't appear to work

### ISSUE THREAD

**Issue by sanjayankur31** [getpelican/pelican#1648]
python-pelican-3.3.0-5.fc21.noarch

This is what my rst file has

```
.. figure:: {filename}/images/2014-07-31-04.39.19.png
    :align: center
    :scale: 25 %
    :target: {filename}/images/2014-07-31-04.39.19.png
    :alt: Mirakel screenshot

```

but the images don't seem to scale when I check the blog with `make html; make serve`.  Nothing suspicious in the output or the makefile.

I'm using the voidy-bootstrap theme and the plugins enabled are: post_stats, render_math and sitemap.

**Comment by sanjayankur31** [comment]
Scale seems to work. Not sure what I changed :/

**Comment by justinmayer** [comment]
Glad that at least the problem resolved itself.  (^_^)
