### ISSUE TITLE
javascript and custom divs

### ISSUE THREAD

**Issue by lgwapnitsky** [getpelican/pelican#1649]
I'm new to this whole pelican game, and a relative n00b to jquery\javascript, so please bear with me.

I'm including a script that I see appearing in the source file for my published page. My div gets published as well, but my javascript entity never appears.

My includes file has the following:

    <script type="text/javascript">
        $(function () {
            var $section = $('section');
            $(window).on("resize", function () {
                var dif = Math.max($(window).height() - $section.height(), 0);
                var padding = Math.floor(dif / 2) + 'px';
                $section.css({ 'padding-top': padding, 'padding-bottom': padding });
            }).trigger("resize");
            $('#myCounter').mbComingsoon({ expiryDate: new Date(2015, 0, 1, 9, 30), speed:100 });
            setTimeout(function () {
                $(window).resize();
            }, 200);
        });
    </script>

and I'm putting the following in my page's .md file:

    <div id="myCounter"></div>

but nothing is showing. Am I doing something incorrectly?

Thank you

**Comment by ingwinlu** [comment]
is this still open? without your full setup it is hard to guess what you want to do / why it fails

**Comment by justinmayer** [comment]
Indeed. Please add more detail and we can re-open if necessary.
