### ISSUE TITLE
older versions deleted from PyPI

### ISSUE THREAD

**Issue by glyph** [getpelican/pelican#1650]
My blog is deployed on Pelican 3.4.0, but I can't download that from PyPI any longer; it seems the only version available to download is 3.5.0.  Was there a security reason that the old versions were removed?

**Comment by iKevinY** [comment]
This is a duplicate of #1522. I don't think it was a security reason — it somehow just happened.

**Comment by glyph** [comment]
Right you are, closing in favor of #1522
