### ISSUE TITLE
Sanitize HTML tags in article.title?

### ISSUE THREAD

**Issue by Armonth** [getpelican/pelican#1651]
One common use in blogs is use `<br>` for separate titles in two lines (or other tags for same/other aesthetic changes: `span`, `strong`, etc):

    Markdown sintaxis:
    Title: Why use two lines in a title? <br>Because we can!

    RST:
    Title: Why use two lines in a title? <br>Because we can!
    ########################################################

And get:

# Why use two lines in a title? <br>Because we can!

But instead, we get:

    <h1>
      <a href="somelink" rel="bookmark" 
        title="Why use two lines in a title? <br>Because we can!">
          Why use two lines in a title?&lt;br&gt;Because we can!
      </a>
    </h1>

"Wrong" title and "wrong" a[title] atribute. And same happens in head-title tag.

Output I expected:

* `<title>` and `a[title]`: Why use two lines in a title? Because we can!
    * (Without `<br>`)
* `<h1>`: Why use two lines in a title? `<br>`Because we can!
    * Without sanitized

What do you think?

**Comment by avaris** [comment]
Markdown version should work, because it allows you to put arbitrary HTML inside documents. reStructuredText does indeed sanitize. There is argument for both approaches. What if you don't want it to be processed as HTML? A title like: `How to use <br> properly`...

**Comment by Armonth** [comment]
Yes, there is argument for both approaches.

> `A title like: How to use <br> properly...`

Assuming is sanitized by default like I expected can be: 

1. Use identitys (`&lt;` and `&gt;`)
2. No sanitize if \` is used (same logic as when in the body of article we write `That is a piece of code with <strong>` and `<strong>` is not processed because is inside a  `<code>` tag.

In (2) I used the backslash \ for add \` without be processed but that can create potentially problems in the parsers.

Anyway, you are right: is a "issue" if you want to use RST (I have to admit i not know too much his sintaxs). For me, a Markdown lover, is just another argument for go full-MD in my site (the other guy wants to use RST every time he can).

**Comment by justinmayer** [comment]
Might be possible to use the merged functionality from https://github.com/getpelican/pelican/pull/1622 for this purpose, although I haven't tested it.
