### ISSUE TITLE
Rationalize release process

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1652]
A pull request was merged a while back that utilizes [Bumpr](https://github.com/noirbizarre/bumpr) to increment the version number, tag the new release, upload to PyPI, et cetera. The last few times I used it to issue new releases, I found it to be more cumbersome then I think it needs to be. Plus, Bumpr has not been updated in nearly 2 years, and I think there are probably other tools that might serve us better. (e.g., https://github.com/peritus/bumpversion)

This issue is therefore intended to track the migration to a better automated release process.

Reference:
https://github.com/getpelican/pelican/blob/master/bumpr.rc

**Comment by robclancy** [comment]
Just make a release?

**Comment by justinmayer** [comment]
Deferring this issue to a subsequent releare, in order to eliminate this as a blocker. Kyle has been working on a new tool that, when ready, we will evaluate as a potential long-term release automation solution.

**Comment by jonathan-s** [comment]
Couldn't [Travis](http://docs.travis-ci.com/user/deployment/pypi/) be used for release automation?

**Comment by justinmayer** [comment]
@jonathan-s: Not sure Travis would do everything that needs to be done. That said, I am open to proposals that cover all of the required steps.

After testing with [Bumpr](https://github.com/noirbizarre/bumpr) a bit more, I realize my assessment was hasty. While not documented very well, it actually does a very good job at automating the release process, and it handled the 3.6 release with aplomb. I plan to continue using it until a better solution surfaces.

That said, I look forward to evaluating @kylef's solution when it's ready!  (^_^)
