### ISSUE TITLE
What can we do with Peru?

### ISSUE THREAD

**Issue by naturallymitchell** [getpelican/pelican#1655]
https://github.com/buildinspace/peru#peru--

Peru is a generic package management tool for using code in external repositories as parts of a project.  Pelican sites often require additional code, like plugins and themes, available in repositories on github, bitbucket, self-hosted, etc.  Perhaps this tool would work well for Pelican users, so if you have some notes and experiences worth sharing, we can all use them to evaluate Peru's usefulness.

**Comment by leotrs** [comment]
This sounds interesting. No experience with Peru, but depending on how powerful it is, it might or might not be too close to a full-on package management system for pelican.

+1 for easier/better ways to get and integrate themes and plugins.
-1 for making use of a huge system for what can be done with a couple of `git clone`s.

**Comment by iranzo** [comment]
Something like this would be interesting, so that we can easily upgrade to latest copy of pelican and keep modules also updated.

Having to clone all folder for plugins, then removing the ones not at used is doable, but not the best user experience here...

**Comment by lioman** [comment]
For plugins it would be better to encourage developers to release plugins as pip packages.
It is easier to use them because there are already battle proved tools to get plugins as dependencies

**Comment by justinmayer** [comment]
I agree that normal Python packages are probably the best way forward, so I'm closing this in favor of #1564.
