### ISSUE TITLE
Import an old pelican-blog

### ISSUE THREAD

**Issue by ZjjConan** [getpelican/pelican#1665]
Hi Everyone !
How to import an old pelican-blog ? 

Thanks !

**Comment by justinmayer** [comment]
Other than ensuring your settings file doesn't have outdated values, I'm not sure there is anything special to do. Of course, your chosen theme and plugins should also be updated as necessary.

**Comment by ZjjConan** [comment]
Thanks @justinmayer , But I want to import existing pelican blog from github rep. I need to import html files into my new blog, how can I do it ? It seems that pandoc cannot exactly convert html into .md

**Comment by avaris** [comment]
Correct me if I'm not understanding right: You don't have the original `.md`/`.rst` files anymore and you want to 'import' your site from the output files.

The output files highly depend on the theme, and because of that, a generic 'import' method is next to impossible. You pretty much need to scrape your own site (using `lxml` or `BeautifulSoup`) for the content.

**Comment by ZjjConan** [comment]
Thanks @avaris, I will try.

**Comment by DirkR** [comment]
@ZjjConan I recently documented my workflow for scraping an HTML website and converting it to markdown files. Unfortunatly it is written in german: http://niebegeg.net/post/website-nach-markdown-kopieren/

But in essence first I scraped the website to locally stored HTML files using wget:

    wget -m -S -nH --adjust-extension -e robots=off -R 'js,css' \
      --exclude-directories='de/taxonomy,en/taxonomy,en/node,de/node,sites/all,misc,modules' \
      -Dexample.org --no-parent -p -P ~/Downloads/website_raw \
      http://example.org/de

Then I used `xidel` (http://videlibri.sourceforge.net/xidel.html) to extract parts of the html file to generate the markdown file. So I wrote a script as contained in the [blog post](http://niebegeg.net/post/website-nach-markdown-kopieren/). Maybe you need to adopt the `xidel --extract ...` statements, as it was tailor-made for the HTML structure of a drupal website.

HTH!

**Comment by pxquim** [comment]
panic can convert HTML into Markdown. However, you have to cleanup the resulting Markdown to remove headers and navigation.

**Comment by justinmayer** [comment]
Thanks to everyone for the helpful responses.

@ZjjConan: If you need further assistance, please free to comment here.

**Comment by ZjjConan** [comment]
I just do the similar way as @pxquim said, but still thanks for every people here.
