### ISSUE TITLE
org_reader does nothing?!

### ISSUE THREAD

**Issue by dsteuer** [getpelican/pelican#1668]
Hi! I´m completely new to pelican, so maybe my problem will have a trivial solution. 

My setting:
- I want to use org-mode as source format. There is a plugin org_reader in pelican-plugins. So
  it should be easy.
- I have successfully installed pelican 3.5.0 on OpenSuse 13.1
- My testproject was created by pelican quickstart. Posts in markdown are translated as expected.
- If I use org-syntax I get an error.
This  is my file ./content/first.org:
-----
#+TITLE: My Second Review
#+DATE: 2010-12-03 
#+CATEGORY: Review

* Following is a review of my favorite mechanical keyboard.
  very important message
-----
This is my pelicanconf.py:
-----
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = u'dsteuer'
SITENAME = u'Endloser Test'
SITEURL = ''

PATH = 'content'

TIMEZONE = 'Europe/Paris'

DEFAULT_LANG = u'de'

PLUGIN_PATHS = ["pelican-plugins"]
PLUGINS = ["org_reader"]

READERS = {'org': "org_reader"}

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (('You can add links in your config file', '#'),
          ('Another social link', '#'),)

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True

# Settings for org-reader
ORG_READER_EMACS_LOCATION = ["/usr/bin/emacs"]
ORG_READER_EMACS_SETTINGS = ["/home/steuer/.emacs.d/init.el"]

-----
 And this is my resulting debug output:

-----
pelican --debug content/
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `org_reader`
DEBUG: Registering plugin `org_reader`
DEBUG: Restoring system path
DEBUG: Template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.html', u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html', u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html', u'analytics.html', u'archives.html', u'article.html', u'article_infos.html', u'author.html', u'authors.html', u'base.html', u'categories.html', u'category.html', u'comments.html', u'disqus_script.html', u'github.html', u'gosquared.html', u'index.html', u'page.html', u'pagination.html', u'period_archives.html', u'tag.html', u'taglist.html', u'tags.html', u'translations.html', u'twitter.html']
DEBUG: Read file first.org -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
-> Reading Org file /home/steuer/Test/Pelican/content/first.org
DEBUG: OrgReader: running command `[[u'/usr/bin/emacs'], '--batch', '-l', [u'/home/steuer/.emacs.d/init.el'], '-l', '/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.el', '--eval', '(org->pelican "/home/steuer/Test/Pelican/content/first.org" \'html)']`
ERROR: Could not process ./first.org
  | 'list' object has no attribute 'rfind'
  |___
  | Traceback (most recent call last):
  |   File "/usr/lib/python2.7/site-packages/pelican/generators.py", line 502, in generate_context
  |     context_sender=self)
  |   File "/usr/lib/python2.7/site-packages/pelican/readers.py", line 459, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.py", line 71, in read
  |     json_result = subprocess.check_output(cmd)
  |   File "/usr/lib64/python2.7/subprocess.py", line 566, in check_output
  |     process = Popen(stdout=PIPE, *popenargs, **kwargs)
  |   File "/usr/lib64/python2.7/subprocess.py", line 709, in __init__
  |     errread, errwrite)
  |   File "/usr/lib64/python2.7/subprocess.py", line 1326, in _execute_child
  |     raise child_exception
  | AttributeError: 'list' object has no attribute 'rfind'
-> Writing /home/steuer/Test/Pelican/output/index.html
-> Writing /home/steuer/Test/Pelican/output/tags.html
-> Writing /home/steuer/Test/Pelican/output/categories.html
-> Writing /home/steuer/Test/Pelican/output/authors.html
-> Writing /home/steuer/Test/Pelican/output/archives.html
Done: Processed 0 article(s), 0 draft(s) and 0 page(s) in 0.10 seconds.

-----

Any help very appreciated.
Detlef

**Comment by dsteuer** [comment]
I forgot: I composed the call to emacs by hand and tried a manual export from emacs. That seemed to work, i.e. gave no error, but it also gave no output ... Therefore the title of my post.

**Comment by saimn** [comment]
Looking at the generated command, it seems that you should use (no list for values):
```
ORG_READER_EMACS_LOCATION = "/usr/bin/emacs"
ORG_READER_EMACS_SETTINGS = "/home/steuer/.emacs.d/init.el"
```

**Comment by dsteuer** [comment]
Hmm, ok, that was an improvement. Something learned already.

The error changes now to:

~/Test/Pelican> pelican --debug content/
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `org_reader`
DEBUG: Registering plugin `org_reader`
DEBUG: Restoring system path
DEBUG: Template list: [u'!simple/archives.html', u'!simple/article.html', u'!simple/author.html', u'!simple/authors.html', u'!simple/base.html', u'!simple/categories.html', u'!simple/category.html', u'!simple/gosquared.html', u'!simple/index.html', u'!simple/page.html', u'!simple/pagination.html', u'!simple/period_archives.html', u'!simple/tag.html', u'!simple/tags.html', u'!simple/translations.html', u'analytics.html', u'archives.html', u'article.html', u'article_infos.html', u'author.html', u'authors.html', u'base.html', u'categories.html', u'category.html', u'comments.html', u'disqus_script.html', u'github.html', u'gosquared.html', u'index.html', u'page.html', u'pagination.html', u'period_archives.html', u'tag.html', u'taglist.html', u'tags.html', u'translations.html', u'twitter.html']
DEBUG: Read file first.org -> Article
DEBUG: Signal article_generator_preread.send(ArticlesGenerator)
-> Reading Org file /home/steuer/Test/Pelican/content/first.org
DEBUG: OrgReader: running command `[u'/usr/bin/emacs', '--batch', '-l', u'/home/steuer/.emacs.d/init.el', '-l', '/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.el', '--eval', '(org->pelican "/home/steuer/Test/Pelican/content/first.org" \'html)']`
Loading ~/.emacs.d/custom.el...
Debug (ox-odt): Searching for OpenDocument styles files...
Debug (ox-odt): Trying /home/steuer/.emacs.d/org-mode/etc/styles/...
Debug (ox-odt): Using styles under /home/steuer/.emacs.d/org-mode/etc/styles/
Debug (ox-odt): Searching for OpenDocument schema files...
Debug (ox-odt): Trying /home/steuer/.emacs.d/org-mode/etc/schema/...
Debug (ox-odt): Using schema files under /home/steuer/.emacs.d/org-mode/etc/schema/
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-dark-emacs.el~...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-example.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-library.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-dark-emacs.el~...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-example.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-library.el (source)...
Loading /home/steuer/.emacs.d/my-color-themes/color-theme-dark-emacs.el (source)...
Loading /home/steuer/.emacs.d/my-color-themes/color-theme-zenburn.el (source)...
Restoring clock data
Loading /home/steuer/.emacs.d/org-clock-save.el (source)...
Symbol's function definition is void: json-encode
Saving file /home/steuer/.emacs.d/org-clock-save.el...
Wrote /home/steuer/.emacs.d/org-clock-save.el
Saving file /home/steuer/.ido.last...
Wrote /home/steuer/.ido.last
ERROR: Could not process ./first.org
  | Command '[u'/usr/bin/emacs', '--batch', '-l', u'/home/steuer/.emacs.d/init.el', '-l', '/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.el', '--eval', '(org->pelican "/home/steuer/Test/Pelican/content/first.org" \'html)']' returned non-zero exit status 255
  |___
  | Traceback (most recent call last):
  |   File "/usr/lib/python2.7/site-packages/pelican/generators.py", line 502, in generate_context
  |     context_sender=self)
  |   File "/usr/lib/python2.7/site-packages/pelican/readers.py", line 459, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.py", line 71, in read
  |     json_result = subprocess.check_output(cmd)
  |   File "/usr/lib64/python2.7/subprocess.py", line 573, in check_output
  |     raise CalledProcessError(retcode, cmd, output=output)
  | CalledProcessError: Command '[u'/usr/bin/emacs', '--batch', '-l', u'/home/steuer/.emacs.d/init.el', '-l', '/home/steuer/Test/Pelican/pelican-plugins/org_reader/org_reader.el', '--eval', '(org->pelican "/home/steuer/Test/Pelican/content/first.org" \'html)']' returned non-zero exit status 255
-> Writing /home/steuer/Test/Pelican/output/index.html
-> Writing /home/steuer/Test/Pelican/output/tags.html
-> Writing /home/steuer/Test/Pelican/output/categories.html
-> Writing /home/steuer/Test/Pelican/output/authors.html
-> Writing /home/steuer/Test/Pelican/output/archives.html
Done: Processed 0 article(s), 0 draft(s) and 0 page(s) in 1.78 seconds.

If I call emacs  directly:

emacs  --batch -l ~/.emacs.d/init.el -l pelican-plugins/org_reader/org_reader.el --eval "(org->pelican \"/home/steuer/Test/Pelican/content/first.org\" 'html)"  
Loading ~/.emacs.d/custom.el...
Debug (ox-odt): Searching for OpenDocument styles files...
Debug (ox-odt): Trying /home/steuer/.emacs.d/org-mode/etc/styles/...
Debug (ox-odt): Using styles under /home/steuer/.emacs.d/org-mode/etc/styles/
Debug (ox-odt): Searching for OpenDocument schema files...
Debug (ox-odt): Trying /home/steuer/.emacs.d/org-mode/etc/schema/...
Debug (ox-odt): Using schema files under /home/steuer/.emacs.d/org-mode/etc/schema/
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-dark-emacs.el~...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-example.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-library.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-dark-emacs.el~...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-example.el (source)...
Loading /home/steuer/.emacs.d/color-theme-6.6.0/themes/color-theme-library.el (source)...
Loading /home/steuer/.emacs.d/my-color-themes/color-theme-dark-emacs.el (source)...
Loading /home/steuer/.emacs.d/my-color-themes/color-theme-zenburn.el (source)...
Restoring clock data
Loading /home/steuer/.emacs.d/org-clock-save.el (source)...
Symbol's function definition is void: json-encode
Saving file /home/steuer/.emacs.d/org-clock-save.el...
Wrote /home/steuer/.emacs.d/org-clock-save.el
Saving file /home/steuer/.ido.last...
Wrote /home/steuer/.ido.last


It seems ok.

**Comment by saimn** [comment]
The command should send you a json result, which doesn't work: `Symbol's function definition is void: json-encode`

**Comment by dsteuer** [comment]
Duuh. I should have guessed that myself...
Thank you a lot. My first.org now gets processed just fine.
May be pelican-plugins/org_reader/org_reader.el should get a line (require 'json)? Or at least 
that should be mentioned in pelican-plugins/org_reader/README.md ?

Thx again! I close this thread.
