### ISSUE TITLE
Official user group for Pelican?

### ISSUE THREAD

**Issue by abrahamvarricatt** [getpelican/pelican#1671]
Do we have one? (eg: https://groups.google.com/forum/?hl=en#!forum/django-users ) Because I can't find any mention of it!

After reading (skimming?) the official documentation, googling, reading multiple blogs .. etc, I'm just lost. My head is full of questions to ask about Pelican but inappropriate to be mentioned on this issue tracker (eg: which is better - heroku/github? how expensive is AWS? .. etc).

It's tempting to just make a google group and 'solve' this issue myself, but that would come off as presumptuous (and possibly rude) to all the developers here. Soooo, can someone of appropriate authority make an official user group somewhere?

**Comment by fuzzmz** [comment]
I think it's best to just drop on in IRC on Freenode, `#pelican`, or skim through the [IRC logs](https://botbot.me/freenode/pelican/).

**Comment by ingwinlu** [comment]
your sample questions are not pelican related at all, maybe thats why you did not find anything in the docs.

hosting is not the scope of pelican.

**Comment by abrahamvarricatt** [comment]
Yes, I know that the questions I asked are not Pelican related - but they are the kind of things that someone new might want answers to. 

As for IRC ... it's difficult to setup at work - where I do most of my reading.

**Comment by avaris** [comment]
If you can not setup an IRC client, you can always use [webchat](http://webchat.freenode.net/).

**Comment by justinmayer** [comment]
While I agree that IRC is our current preferred mechanism, I'm not opposed to setting up an official forum (e.g., via Discourse) at some point in the future. But it probably isn't going go happen any time soon.

**Comment by iKevinY** [comment]
I think that having a Discourse instance for Pelican would complement IRC and GitHub well. By pointing people to Discourse, it would be easier to keep this issue tracker reserved for technical issues, and longer-term discussion that isn't well-suited for IRC could take place on Discourse instead.
