### ISSUE TITLE
no module named html_parser

### ISSUE THREAD

**Issue by johnwheeler** [getpelican/pelican#1674]
Trying to run pelican-quickstart on OS X Yosemite and get above error.

**Comment by ingwinlu** [comment]
#1558

**Comment by johannesl** [comment]
A fresh OS X Yosemite install with just "easy_install pelican" give the same error. Is there another way recommended for installing pelican?

**Comment by avaris** [comment]
From what I read, OS X Yosemite system python ships with `six` module. Quite outdated one in fact.`pip` can install a recent version but in a path different than the one that was already installed. Moreover the `pip`-installed path is lower in import chain so system `six` takes precedence. That's the issue in a nutshell.

The solution? Just don't mess with the system python and use virtualenv.

**PS**: This is from a brief search. I don't even own a Mac, so I don't have any way to verify. If you want, you can check it:

```
python -c "import six; print(six.__version__, six.__file__)"
```

This should give you the version and the location of the `six` module that's used.

**Comment by ingwinlu** [comment]
the solution with a virtualenv has been noted in the closed issue i linked in march; the pelican documentation also shows the 'recommended' way of installing pelican in a virtualenv.

**Comment by ingwinlu** [comment]
looking in the changelog of the six project, we might be able to circumvent this problem by requiring a newer version of six, thoughts? https://bitbucket.org/gutworth/six/src/8a545f4e906f6f479a6eb8837f31d03731597687/CHANGES?at=default

**Comment by avaris** [comment]
Again, from what I read, it doesn't matter what `pelican` requires. `pip` can install the newest, shiniest `six` but it goes to a different path. It doesn't upgrade the one that's preinstalled. System version shadows the `pip` version because it's the first one in `sys.path`. [All of this needs confirmation from an actual OS X Yosemite user, since I'm not even close to that]

**Comment by johannesl** [comment]
$ python -c "import six; print(six.__version__, six.__file__)"
('1.4.1', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc')

Actually, sys.path seems to be adjusted according by other packages like gevent to get around this. Here's an example sys.path from Yosemite:

['', '/Library/Python/2.7/site-packages/gevent-1.0-py2.7-macosx-10.9-intel.egg', '/Library/Python/2.7/site-packages/greenlet-0.4.2-py2.7-macosx-10.9-intel.egg', '/Library/Python/2.7/site-packages/ujson-1.33-py2.7-macosx-10.9-intel.egg', '/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/pelican-3.5.0-py2.7.egg', '/Library/Python/2.7/site-packages/Pygments-2.0.2-py2.7.egg', '/Library/Python/2.7/site-packages/Jinja2-2.7.3-py2.7.egg', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC', '/Library/Python/2.7/site-packages']

**Comment by justinmayer** [comment]
I run Yosemite but don't use the Python bundled with it. ([Here's how I do it.](http://hackercodex.com/guide/python-development-environment-on-mac-osx/))

Yosemite seems to come with `six` version 1.4.1:

    $ /usr/bin/python -c "import six; print(six.__version__, six.__file__)"
    
    ('1.4.1', '/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/six.pyc')

Perhaps we should require version 1.9.0 or higher. Thoughts?

**Comment by justinmayer** [comment]
@johannesl: What happens if you `pip install six==1.9.0` and then try `pip install pelican`?

**Comment by johannesl** [comment]
Installing 1.9.0 doesn't help unfortunately. And if you do the fix from http://wangbo.info/pelican-error-on-macbook-htmlparser.html you get more errors. First one about "logger" in six and then:

  File "/Library/Python/2.7/site-packages/pelican-3.6.1.dev-py2.7.egg/pelican/readers.py", line 300, in HTMLReader
    class _HTMLParser(HTMLParser):
TypeError: Error when calling the metaclass bases
    module.__init__() takes at most 2 arguments (3 given)

**Comment by avaris** [comment]
@johannesl After installing 1.9.0 what does this give?

```
python -c "import six; print(six.__version__, six.__file__)"
```

**Comment by johannesl** [comment]
It gives 1.9.0.
*JL

Skickat från min iPhone

**Comment by avaris** [comment]
@johannesl that's weird. Are you sure the six 1.9.0 and the pelican is installed to same python?

**Comment by justinmayer** [comment]
Solving the issue with the system Python provided by Yosemite is clearly proving to be a non-trivial task. That being the case, and given that installing into a virtual environment resolves the problem (and is currently the recommended installation method), I'm closing this issue until someone volunteers to address it.

The good news is that El Capitan reportedly includes updated versions of a variety of system components, so most likely this issue will resolve itself when it is released a few months from now.
