### ISSUE TITLE
Markdown reference links in summary not displaying correctly

### ISSUE THREAD

**Issue by fuzzmz** [getpelican/pelican#1675]
It looks like markdown reference links in the summary of an article are not converted to proper links.

![md_summary_bug](https://cloud.githubusercontent.com/assets/1335181/6857352/f30f91de-d40e-11e4-9048-406c9b5e6069.png)

You can see the bug reproduced [here](http://fuzz.me.uk/) with the raw markdown content of the post available [here](https://raw.githubusercontent.com/fuzzmz/fuzzmz.github.io/source/content/travis-article-publish.md).

**Comment by avaris** [comment]
This is expected behavior. When you provide summary in the metadata, it's processed through markdown independently from what you have in content. Either use inline links or provide those links for summary:

```markdown
...
Summary: Some summary with [a link][1].
    [1]: http://example.com "Example"

Content here...
```

**Comment by fuzzmz** [comment]
@avaris, good to know. Going to close this issue but I think it's best to have this behavior mentioned somewhere in the docs.
