### ISSUE TITLE
Issues with Image src when site hosted on a sub folder

### ISSUE THREAD

**Issue by shireenrao** [getpelican/pelican#1676]
I followed the pelican docs http://docs.getpelican.com/en/3.5.0/content.html#linking-to-internal-content on linking to other internal content (either articles or images).
So my images are as follows in my markdown files

    ```
    ![Alt Text](/images/han.jpg)
    ```

This works fine when I was testing locally. I am seeing the image at 
    
    ```
    http://localhost:8000/images/han.jpg
    ```

I am deploying my output to a subdirectory (i.e http://example.com/subdir). The image is available at

    ```
    http://example.com/subdir/images/han.jpg
    ```

but the generated html has the image at 

    ```
    http://example.com/images/han.jpg
    ``` 

How can I have the image src be 

    ```
    http://example.com/subdir/images/han.jpg 
    ```

in the generated html.

My SITEURL is set to 'http://example.com/subdir'

**Comment by avaris** [comment]
If you followed the docs you linked (like you said), then you'd have:

    ![Alt text]({filename}/images/han.jpg)

or 

    ![Alt text]({attach}/images/han.jpg)

**Comment by shireenrao** [comment]
Thank you for pointing out the missing {filename} in my syntax. I realized my mistake.. While testing, I was viewing the markdown files in a markdown editor (mou) and could not see the images displayed wit {filename}. I took out {filename} and saw the output working both in the editor and when I ran the devserver. Thanks for you help.
