### ISSUE TITLE
Ignore subdirectories by pattern

### ISSUE THREAD

**Issue by skettlitz** [getpelican/pelican#1678]
Currently ignoring subdirectories by pattern is not possible.

What works is:
1) ignoring files by pattern by setting 'IGNORE_FILES = ["pattern1_","pattern2_","._","__"]'
2) ignoring specific directories by setting 'PATH_EXCLUDE = ["maindir1","maindir2/subdir"]'

What I'd suggest is another way to ignore subdirectories by pattern. 

The following code adds a configuration variable 'IGNORE_SUBDIRS' analogous to 'IGNORE_FILES'.

```
diff --git a/pelican/generators.py b/pelican/generators.py
index 75bd6b2..20942ab 100644
--- a/pelican/generators.py
+++ b/pelican/generators.py
@@ -139,6 +139,11 @@ class Generator(object):
                     for e in exclusions_by_dirpath.get(dirpath, ()):
                         if e in dirs:
                             dirs.remove(e)
+                    for dir in dirs:
+                        #check IGNORE_SUBDIRS
+                        ignores = self.settings['IGNORE_SUBDIRS']
+                        if any(fnmatch.fnmatch(dir, ignore) for ignore in ignores):
+                            dirs.remove(dir)
                     reldir = os.path.relpath(dirpath, self.path)
                     for f in temp_files:
                         fp = os.path.join(reldir, f)
```

and

```
diff --git a/pelican/settings.py b/pelican/settings.py
index 0d69c08..c675f50 100644
--- a/pelican/settings.py
+++ b/pelican/settings.py
@@ -122,6 +122,7 @@ DEFAULT_CONFIG = {
     'PYGMENTS_RST_OPTIONS': {},
     'TEMPLATE_PAGES': {},
     'IGNORE_FILES': ['.#*'],
+    'IGNORE_SUBDIRS': [],
     'SLUG_SUBSTITUTIONS': (),
     'INTRASITE_LINK_REGEX': '[{|](?P<what>.*?)[|}]',
     'SLUGIFY_SOURCE': 'title',
```

**Comment by leotrs** [comment]
LGTM

**Comment by justinmayer** [comment]
@leotrs: Nothing to merge here, because it's not a pull request.  😉 

If this were to be submitted as a pull request, replete with docs *and* tests, then we could certainly consider merging it.

**Comment by Scheirle** [comment]
Somewhat related to https://github.com/getpelican/pelican/pull/1975

**Comment by joemull** [comment]
I am coming across this issue in a new project. Specifically I ran into it because the docs say `IGNORE_FILES` can be used with a glob pattern, but that is not accurate because Pelican just matches on the result of `os.path.basename`, which omits the directory. So glob patterns that include directories are not matched.

https://github.com/getpelican/pelican/blob/84db21c724143e21673e266d98857c4235d1499a/docs/settings.rst?plain=1#L153-L158

https://github.com/getpelican/pelican/blob/84db21c724143e21673e266d98857c4235d1499a/pelican/generators.py#L147-L152

If it continues to be a blocker for us I will may work on a PR, but thought I'd go ahead and document the discrepancy.

**Comment by justinmayer** [comment]
Hi @joemull. I think you will need to provide more proof to back this assertion. In my testing, setting `IGNORE_FILES = ["*foo*"]` successfully ignores any Markdown files inside `content/foo/` or `content/articles/foo/`.

If you do a code search for `IGNORE_FILES`, you will see that there are other places in which this setting is utilized — not just in the one place you referenced.

**Comment by justinmayer** [comment]
As noted above, my testing indicates that it is already possible to ignore directories and sub-directories via glob patterns. If anyone finds a specific, reproducible problem related to this feature, please file a new issue with the appropriate details.
