### ISSUE TITLE
How to configure pelican comment system

### ISSUE THREAD

**Issue by kusumasuresh** [getpelican/pelican#1682]
Hi,

Please guide me on how to setup pelican comment system
What i did is 
# yum install epel-release
# yum install python-pip
# pip install pelican markdown
# mkdir /projects
# cd /projects/
# mkdir mysite
# cd mysite/
# pelican-quickstart
Provided all required details for above command
then, 
# cd content/
# vim test.md
Title: Test
Date: 2015-04-07 10:20

    this is page
:wq
# cd /projects/mysite/
# pelican content
# cd /projects/mysite/output
# python -m SimpleHTTPServer
This shows my blog 
But now i want to configure comment system on pelican, Can u please guide on this.

I have downloaded pelican-themes and plugins well and configured only pelicanconf.py as mentioned in 
https://github.com/getpelican/pelican-plugins/blob/master/pelican_comment_system/doc/installation.md
and configured settings also same in pelican_comment_system/pelicanconf.py as mentioned above but replaced False with True.

but strucked at next level, din't  understanding, i'm new to pelican. What to do next..
Please guide me step by step like i mentioned above. 
 
Thanks
Suresh

**Comment by Scheirle** [comment]
You now have to modify your theme (I assume you already have selected one), so the comments can be displayed.

Therefore copy https://github.com/getpelican/pelican-plugins/blob/master/pelican_comment_system/doc/installation.md#example-articlehtml-theme in the '[YourTheme]/templates/article.html' (Where exactly depends on the theme and your taste.)

A minimalist example of a working site can be found at: https://github.com/Scheirle/pelican_comment_system_example

PS: When the basic setup works you probably want to edit the theme, so the comments look better with your current theme.

**Comment by kusumasuresh** [comment]
FYI

#  pelicanconf.py
PLUGIN_PATHS = ['/root/pelican-plugins']
PLUGINS = ['pelican_comment_system']
PELICAN_COMMENT_SYSTEM = True

# theme/templates/article.html
{% extends "base.html" %}
{% block title %}{{ article.title|striptags }}{% endblock %}
{% block content %}
<section id="content" class="body">
<article>
        <header> <h1 class="entry-title"><a href="{{ article.url }}"
        rel="bookmark" title="Permalink to {{ article.title|striptags }}">{{ article.title
        }}</a></h1> {% include 'twitter.html' %} </header>
        <div class="entry-content">
        {% include 'article_infos.html' %}
        {{ article.content }}
        </div>
        {% if DISQUS_SITENAME %}
        <div class="comments">
        <h2>Comments !</h2>
            <div id="disqus_thread"></div>
            <script type="text/javascript">
               var disqus_identifier = "{{ article.url }}";
               (function() {
               var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
               dsq.src = 'http://{{ DISQUS_SITENAME }}.disqus.com/embed.js';
               (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
              })();
            </script>
        </div>
        {% endif %}
</article>
</section>
{% if article.comments %}
    {% for comment in article.comments recursive %}
        {% if loop.depth0 == 0 %}
            {% set marginLeft = 0 %}
        {% else %}
            {% set marginLeft = 50 %}
        {% endif %}
            <article id="comment-{{comment.slug}}" style="border: 1px solid #DDDDDD; padding: 5px 0px 0px 5px; margin: 0px -1px 5px {{marginLeft}}px;">
                <a href="{{ SITEURL }}/{{ article.url }}#comment-{{comment.slug}}" rel="bookmark" title="Permalink to this comment">Permalink</a>
                <h4>{{ comment.author }}</h4>
                <p>Posted on <abbr class="published" title="{{ comment.date.isoformat() }}">{{ comment.locale_date }}</abbr></p>
                {{ comment.metadata['my_custom_metadata'] }}
                {{ comment.content }}
                {% if comment.replies %}
                    {{ loop(comment.replies) }}
                {% endif %}
            </article>
    {% endfor %}
{% else %}
    <p>There are no comments yet.<p>
{% endif %}
{% endblock %}

And My pelican_comment_system pelicanconf.py
       
        ('PELICAN_COMMENT_SYSTEM', True),
        ('PELICAN_COMMENT_SYSTEM_DIR', '/test/comments'),
        ('PELICAN_COMMENT_SYSTEM_IDENTICON_OUTPUT_PATH', 'images/identicon'),
        ('PELICAN_COMMENT_SYSTEM_IDENTICON_DATA', ()),
        ('PELICAN_COMMENT_SYSTEM_IDENTICON_SIZE', 72),
        ('PELICAN_COMMENT_SYSTEM_AUTHORS', {}),
        ('PELICAN_COMMENT_SYSTEM_FEED', os.path.join('feeds', 'comment.%s.atom.xml')),
        ('PELICAN_COMMENT_SYSTEM_FEED_ALL', os.path.join('feeds', 'comments.all.atom.xml')),
        ('COMMENT_URL', '#comment-{slug}')

And here the output what i'm getting, There is no coloum to post comment,
showing only "There are no comments yet" at top right side, Please suggest...

![screenshot from 2015-04-08 14 30 48](https://cloud.githubusercontent.com/assets/11228585/7042075/93481c42-ddfc-11e4-86ca-20e9608397f7.png)

**Comment by Scheirle** [comment]
> And My plugin pelican_comment_system pelicanconf.py file configuration

There shouldn't be such a file. All settings you change go in the main (website root) pelicanconf.py.

> There is no coloum to post comment

This you have to add yourself.
Some pointers can be found at: <https://github.com/getpelican/pelican-plugins/blob/master/pelican_comment_system/doc/form.md>

> [..] showing only "There are no comments yet" at top right side

Insert the comment theme between '< /article>" and '< /section>' (not below).
Then the comments should be under the article.

**Comment by kusumasuresh** [comment]
As suggested in https://github.com/getpelican/pelican-plugins/blob/master/pelican_comment_system/doc/installation.md#settings  settings for pelican _comment_system i mentioned above,
it is not pelicanconf.py its /root/pelican-plugins/pelican_comment_system/pelican_comment_system.py

**Comment by Scheirle** [comment]
>As suggested in https://github.com/getpelican/pelican-plugins/blob/master/pelican_comment_system/doc/installation.md#settings settings for pelican _comment_system mentioned above,
it is not pelicanconf.py its /root/pelican-plugins/pelican_comment_system/pelican_comment_system.py

In pelican_comment_system.py are just the default values.
If you want to change them, add them to your pelicanconf.py (which then overwrites the defaults).

> About form creation, i don't know about the javascript deveoper, i'm linux administrator, so can u please guide me step by step where need to add that code, if possible please edit my article.html file and post here..

I extended the minimalistic example (<https://github.com/Scheirle/pelican_comment_system_example> and <http://scheirle.github.io/pelican_comment_system_example/sample-article.html>) so it now contains the comment form.

The actual article.html: <https://github.com/Scheirle/pelican_comment_system_example/blob/master/no_avatars/theme/templates/article.html>

This should give you all information you need to setup your own article.html.

**Comment by kusumasuresh** [comment]
Getting following error after made chages according to your code in article.html file 

CRITICAL: 'jinja2.environment.TemplateModule object' has no attribute 'translations_for'

**Comment by Scheirle** [comment]
The plugin you selected (pelican_comment_system) uses a **static** approach.
It reads the comments from files but doesn't handle the comment/file creation.

For your requirements a different comment system (e.g. disqus) is probably a better choice.

**Comment by DirkR** [comment]
@kusumasuresh Look at https://github.com/posativ/isso - it's written in python and quite easy to install.
I deployed it for my pelican blog.

**Comment by kusumasuresh** [comment]
@Scheirle I'm Testing on my local test machine which does not have public domain, I as per my knowledge Disqus require public domain name.

@DirkR How to install isso for my pelican, please go through my pelican configurations above and please guide what to do next. step by step

**Comment by ingwinlu** [comment]
we are not your personal instruction bots, read the isso docs, read the pelican docs, do some work yourself.

**Comment by DirkR** [comment]
@kusumasuresh No, I cannot do that. There is extensive documentation at http://posativ.org/isso/docs/, and there is a blog post from the author (unfortunatly in German), where he describes the installation in a specific shared hosting environment: http://blog.posativ.org/2014/isso-und-uberspace-de/
