### ISSUE TITLE
Allow to force menu items order

### ISSUE THREAD

**Issue by nicoulaj** [getpelican/pelican#169]
Right now menu items ordering seems to be alphabetical, which means you can have categories and pages mixed up.

I have no clear idea on how this should be done, but here are some ideas:
- Put categories first, then pages (may be through an option, but I can't see any case where one would want it to be mixed)
- Order using their file names

**Comment by colmoneill** [comment]
Found this closed issue that relates to a question I have, hope this finds you, it's probably not worth opening a new issue for:

To be able to give an order to my menu items, I use the MENUITEMS setting in pelicanconf.py, would there be anyway of integrating a logic for a `{% if cat == category %} class="active"{% endif %}` logic with this setting do you think?

Thanks!

**Comment by justinmayer** [comment]
@colmoneill: I'm not sure. Perhaps have a look at Page Order or Page Hierarchy plugins in the [Pelican Plugins](https://github.com/getpelican/pelican-plugins) repo.
