### ISSUE TITLE
code_block: line-wise spans to enable CSS line numbering

### ISSUE THREAD

**Issue by chaoflow** [getpelican/pelican#1694]
It would be great if the code_block directive would wrap the content of the generated pre-tag line-wise in span tags and add classes, as such:

```
<pre class="code_block">
<span class="line">line1</span>
<span class="line">line2</span>
...
<pre>
```
This would allow to add line numbers via CSS.

**Comment by ingwinlu** [comment]
except that pelican does not do the syntax highlighting at all. have a look at `PYGMENTS_RST_OPTIONS` or `MD_EXTENSIONS` to archive what you want.

**Comment by TylerShaw** [comment]
It is possible with `PYGMENTS_RST_OPTIONS`, but you can't do it with `MD_EXTENSIONS`. I'd also like this feature and have spent most of my day trying to find a work around without editing Codehilites or Pygments

**Comment by Armonth** [comment]
And the most semantic way (recommended by the forks of HTML5) of put code is using `<pre><code class="language-css">` por CSS language, language-html for HTML, etc.

For most of us adding `span` and `div` and a bunch of classes inside of the block for highlight code only serves for bloat the code.

If you need a work around for this, try [prism.js](http://prismjs.com/): you don't need to add anything except the pre/code with class language-XXXX and JS do all the magic. You create a custom JS/CSS with only the languages you need and/or themes/plugins (line count, line highlight, etc) you want.

At least for me is a better solution compared with bloating the code block.

Note: use markdown extra is even more easier for block codes:

\`\`\`{.language-css}
.some-code-in-css {}
\`\`\`

**Comment by justinmayer** [comment]
If someone would like to work on this, please comment here and I will re-open.
