### ISSUE TITLE
Figurecaption and Markdown: asking for a plugin

### ISSUE THREAD

**Issue by Armonth** [getpelican/pelican#1697]
"xsteadfastx" asked in IRC this question: _what is the best way to write image captions in markdown... i found something for rst files... but i only have markdown files here_

And I replied: _with markdown standard i think can't be done... so HTML or JS for inject in the HTML using the alt text_. At least I don't found anyone, so i'm asking for add this feature in pelican (as core or plugin, what you think is better).

That is a one common issue/recurrent question.

Exist one plugin for RST+Markdown for [better figures](http://duncanlock.net/blog/2013/10/19/the-better-figures-images-pelican-plugin-now-supports-figure-numbering/) but the autor says don't tested in Markdown and he have two mayor problems:

* Is not working for me in a new pelican install with Markdown.
* Have a issue of "**div**initis" (don't make HTML5 semantic code).

So I'm asking about hack this plugin or creating a new one for support figurecaption in Markdown.

My idea need maybe further discussion about sintax but basically is use Markdown+Markdown extra and using definition lists as figurecaption and parse for a `#fig-1` where 1 is the number of fig. Insert image where we want to publish:

```
![alt text of image](image url of a tree){#fig-1 .fig .fig-left}
```

The `#fig-1` is the way for identifity that image as a image inside of a figure+figurecaption, another alternative is using `!fig` but that is add a new "thing" to Markdown. Then add a definition list at end of article for that figurecaption:

```
    #fig-1
:   Yeah, that is a tree, and that is a definition list using markdown-extra
```

And the output is:

```
<figure id="#fig-1" class="fig fig-left">
  <img alt="alt text of image" src="image url of a tree">
  <figcaption>
    <strong>Fig #number-of-the-fig</strong>
    <p>Yeah, that is a tree, and that is a definition list using markdown-extra</p>
  </figcaption>
</figure>
```

And maybe allow a option for set "Fig" inside of the `strong`  to another thing (in my language, spanish, maybe is more natural use "Imagen").

**Comment by avaris** [comment]
If you're asking for a plugin, isn't it more appropriate to ask in [pelican-plugins](https://github.com/getpelican/pelican-plugins)?

**Comment by justinmayer** [comment]
As suggested, this doesn't belong here and should be re-posted to the Pelican Plugins repo.
