### ISSUE TITLE
Add Site Search

### ISSUE THREAD

**Issue by stupergenius** [getpelican/pelican#170]
I'm thinking we could just generate a JSON file that contains the search index, and have some client side JS search through that index and display results.

I'm not sure the best way to roll this into Pelican, however, as it seems to me that a large portion of the functionality would need to be written into the theme? Unless we have Pelican generate the index and a generic implementation of the JS search code, and have the templates just call that generic search routine to get a list of objects to style how it sees fit.

I'm thinking we could model this after Sphinx quite nicely.

I'm willing to take on this piece once there's a good plan for implementation and for rolling into Pelican.

**Comment by kdeldycke** [comment]
Same thing as @talha131: just added fully-static search on a Pelican site thanks to the [Tipue Search](https://github.com/getpelican/pelican-plugins/tree/master/tipue_search) plugin.

It is now supported out of the box by my [Plumage theme](https://github.com/kdeldycke/plumage). See it in action on my blog at: http://kevin.deldycke.com/

**Comment by MTecknology** [comment]
My number one concern with Tipue is that it pulls a json export of the entire website content down to the browser. For small websites, that's not a big deal, but for anything of reasonable size, that's a pretty big concern. That's worse yet if the user is on a slow system or behind a slow network. This lets your site stay fully static, but it puts a whole lot of load on the user side.

Tapir seems like a better option. It still requires javascript client side, but that javascript just makes an API call to a separate search service and feeds the results into the page. This is definitely a better option, but... I'm not satisfied with it. It also doesn't seem to catch updated content, only new content, and it doesn't handle if you want to enforce SSL on your website.

What I did with my website (https://michael.lustfield.net/search?q=nginx), I'm considering building a web service for. I have a few ideas for building this and would to know if there's any interest.
What I would like to emphasize:

1. Can be indexed immediately
2. Always fully indexed, no partial updates that don't catch modified content
3. Can have search.<yourdomain>; myservice.com/search?d=<yourdomain>; <yourdomain>/search, etc.
4. Content returned in your theme
5. NO javascript
6. Your servers and the client don't do any work
7. I have a few thoughts for handling SSL as well
8. Anything else?

I don't want to put in the effort to build this if there's going to be no interest. If any developers are interested, I could definitely use help.

**Comment by jducastel** [comment]
Hello
Just an idea there, not sure i would have time to implement it. With [semantic-ui](http://semantic-ui.com/modules/search.html) (amongst other frontend frameworks of course), search results are expected as a json list of contents. Something like :
```json
{
  "results": [
    {
      "title": "Result Title",
      "url": "/optional/url/on/click",
      "image": "optional-image.jpg",
      "price": "Optional Price",
      "description": "Optional Description"
    },
    {
      "title": "Result Title",
      "description": "Result Description"
    }
  ]
}
```

which is returned by the server when the client script calls for search suggestion at an url like /search/typed-string/

It's usually a server-side generation, but maybe instead of generating one big json index file, pelican could generate a bunch of pre-generated search results, at least for a subset of content words ? Using a jinja template to accomodate other json results specifications ?

**Comment by leotrs** [comment]
@jducastel I don't thinkg pre-generated search results would really work for big sites with lots of content. And for small sites, there's Tipue search already.

**Comment by repus** [comment]
erightsoft.org

**Comment by repus** [comment]
erightsoft.org

**Comment by repus** [comment]
erightsoft.com

**Comment by ssteinerx** [comment]
"repus" link is video converter SPAM.

**Comment by justinmayer** [comment]
Indeed. The user has been reported to GitHub's abuse team.

**Comment by justinmayer** [comment]
I'm inclined to believe search to be outside the scope of Pelican core. Given that, and the existence of the [Tipue Search](https://github.com/getpelican/pelican-plugins/tree/master/tipue_search) plugin, I think it's time to put this issue to rest.
