### ISSUE TITLE
Linking to internal content by source filename is broken

### ISSUE THREAD

**Issue by brechtm** [getpelican/pelican#1702]
I'm trying to link to another article or static page using the instructions provided [here](http://pelican.readthedocs.org/en/3.5.0/content.html#linking-to-internal-content). I always get the following warning:

    WARNING: Unable to find `other_article.rst`, skipping url replacement.

Printing `self._content['filenames']` in the `replacer` function in `contents.py` shows that this is an empty list. Maybe someone who is familiar with the code has an idea why?

I'm using Pelican 3.5.0 on Python 2.7.9 (Homebrew) on OS X 10.10.2.

**Comment by avaris** [comment]
Can you show the pelican log output with `--debug`?

**Comment by ahmetalpbalkan** [comment]
I can repro this on 3.5.0 (on OS X as well). My entire blog is broken with this error because after 4 failures it just says

    WARNING: Other resources were not found and their urls not replaced

and doesn't replace any `|filename|` or `{filename}`s for the rest of the blog.

1. My images live in `content/images/`
2. pelicanconf.py has `STATIC_PATHS = ['images']`
3. I use `![]({filename}/images/2007/09/logo2.gif) ` and image is definitely at `content/images/2007/09/logo2.gif` on the filesystem (as well as `output/`)
4. `--debug`, `-D` or `-v` doesn't really print anything different than the default verbosity level for this step.

Seems critical to me.

**Comment by ahmetalpbalkan** [comment]
This is definitely a regression in 3.5.0.
If I go back to 3.4.0 manually, I no longer see this problem and `|filename|` or `{filename}`s are resolved just fine.

**Comment by avaris** [comment]
@ahmetalpbalkan I need a way to investigate it. Something more than "doesn't work". `--debug` output helps. A link to the source repo (if it's public) so that I can reproduce the issue is even better.

**Comment by ahmetalpbalkan** [comment]
@avaris I am sort of worried revealing all my blog's files :) But I can put up a redacted version if you don't mind: https://gist.github.com/ahmetalpbalkan/306f58d5325853d42c50

**Comment by avaris** [comment]
@ahmetalpbalkan that's helpful, sort of :). I noticed:
```
WARNING: Unable to find `/images/2007/09/avea.thumbnail.jpg`, skipping url replacement.
```

and 

```
-> Copying /Users/alp/workspace/blog/content/images/2007/09/avea.jpg to images/2007/09/avea.jpg
```

Note the difference. One has `.thumbnail` in filename. Do you also have that file? It would show in the log as:

```
DEBUG: Read file images/2007/09/avea.thumbnail.jpg -> Static
```

**Comment by avaris** [comment]
Wait... A bit more investigative work: You get that error right after the file is read. That means something is trying to access `.content` there. It's not pelican, so it must be a plugin. A quick check reveals that `read_more_link` does that.

The difference between 3.4 and 3.5 is the time static files are read. 3.4 did it before any other generator, 3.5 does it after. So, at that time articles are read, your static files are not known by pelican, therefore you get `skipping ...` warnings if something tries to do that. Moreover `Article.content` is `@memoized` so, it doesn't re-process during write.

Quick fix: remove `read_more_link` until it's compatible with 3.5

**Comment by ahmetalpbalkan** [comment]
@avaris yep looks like `read_more_link` was it. Thank you! Shall we file a separate issue for that?

**Comment by avaris** [comment]
Yes, an issue in pelican-plugins would be appropriate.

**Comment by brechtm** [comment]
Thanks for investigating! I'm not using the `read_more_link` plugin myself:

    PLUGINS = ['sitemap', 'extract_toc', 'tipue_search', 'share_post', 'neighbors']

I'll try to find out which could be causing the problem.

**Comment by brechtm** [comment]
Seems like `share_post` is to blame.

**Comment by avaris** [comment]
Ah, I remembered why this sounded familiar: getpelican/pelican-plugins#410

**Comment by justinmayer** [comment]
Not relevant to Pelican core.
