### ISSUE TITLE
Internal link does not work properly with files containing spaces

### ISSUE THREAD

**Issue by whypro** [getpelican/pelican#1706]
I try to define a internal link in a article:

    `Arch Linux <{filename}/树莓派/为树莓派制作 Arch Linux SD 卡.rst>`_

Then run:

    make html

but it outputs a warning:

    WARNING: Unable to find `/树莓派/为树莓派制作ArchLinuxSD卡.rst`, skipping url replacement.

It seems to ignore **all spaces** in filename. 

How can I solve this problem without renaming the rst file? 

My Pelican version is 3.5.0, installed by pip.

**Comment by avaris** [comment]
Looks like spaces are stripped by the rst parser in docutils. By the time pelican gets it, they are long gone. And, I couldn't see a way to suppress that behavior in docutils. If you want to preserve spaces in the filenames, you need to manually encode the spaces with `%20`s in links. Like:
```
`Arch Linux <{filename}/树莓派/为树莓派制作%20Arch%20Linux%20SD%20卡.rst>`_
```

**Comment by whypro** [comment]
It works. Thank you! @avaris
