### ISSUE TITLE
How to run Pelican from a Apache cgi-bin script???

### ISSUE THREAD

**Issue by arqeco** [getpelican/pelican#1707]
We have Pelican and Apache installed on our local Debian server. I would like to have a link on our intranet home page - where our webdesigner could click - to run pelican.

The idea is avoiding the use of the command line terminal by our non-technical content creators. 

That link could run a cgi-bin script to activate the virtualenv, possibly changing to the right user, and run pelican to regenerate the site. It could be this way or another one, as simple as possible.

Is it possible?

Thanks,
Marcio

**Comment by justinmayer** [comment]
I don't see why it *couldn't* be done, although I've never tried it.

**Comment by arqeco** [comment]
This is my /usr/lib/cgi-bin/run-pelican.py script:


    #!/home/samba//Site/pelican350-venv/bin/python
    # -*- coding: UTF-8 -*-
    
    import cgitb
    cgitb.enable(format="text")  # Enable debugging

    print "Content-Type: text/plain"
    print
    print "Importing Pelican"
    import pelican
    print "Imported:", pelican
    print "Running pelican"
    pelican.main()
    print "Done"

The output on the browser is this:

    Importing Pelican
    Imported: <module 'pelican' from '/home/samba/Site/pelican350-venv/local/lib/python2.7/site-packages/pelican/__init__.pyc'>
    Running pelican

Notice that Pelican output in not displayed, and even the "Done" word is not displayed.

But when the run-pelican.py is called from the command line (by root, owner of cgi-bin) the output of Pelican is displayed on the terminal and it works fine, creating cache and output folders.

**Comment by justinmayer** [comment]
@arqeco: Seems like you came up with a solution. Well done.  (^_^)
