### ISSUE TITLE
signals.content_object_init.connect not working as described in docs

### ISSUE THREAD

**Issue by bkfunk** [getpelican/pelican#1711]
The docs suggest adding a sender parameter when connecting the `content_object_init` signal. However, when I do that, just copying the example in the docs, nothing happens. When I just put the method name, with no additional argument, the signal appears to be sent correctly. Searching through the plugins repo, it appears that none of the plugins use the additional sender argument as suggested in the docs. Is this functionality no longer there? If so, the docs should be corrected.

The relevant section of the documentation:

> The signal content_object_init can send a different type of object as the argument. If you want to register only one type of object then you will need to specify the sender when you are connecting to the signal.

> ```python
from pelican import signals
from pelican import contents

> def test(sender, instance):
        print "%s : %s content initialized !!" % (sender, instance)

> def register():
        signals.content_object_init.connect(test, sender=contents.Article)
```

**Comment by ingwinlu** [comment]
@bbinet why did you break that functionality in https://github.com/getpelican/pelican/commit/ed907b4094c49d5014716bca82a77265bcc49091 ?

**Comment by ingwinlu** [comment]
we actually have a test in place for that signal, but it is fairly useless as it does not check if the signal actually gets called... https://github.com/getpelican/pelican/blob/master/pelican/tests/test_contents.py#L193
