### ISSUE TITLE
Sorting all articles on main page by date

### ISSUE THREAD

**Issue by lgwapnitsky** [getpelican/pelican#1713]
I currently have multiple categories for articles on my site. I've played with the options, but all articles appear to be sorted by category then date, e.g.

Category 1
  newest
  second
  third
Category 2
  newest
  second
  third

Essentially, I want them shown in the same order as in the archives. Am I missing something?

Thanks

**Comment by avaris** [comment]
Which theme are you using? Unless the theme does that, `articles` (or `all_articles`) should be sorted by date.

**Comment by lgwapnitsky** [comment]
nevermind.  got it fixed.
