### ISSUE TITLE
{tag} links to the wrong directory

### ISSUE THREAD

**Issue by vtbassmatt** [getpelican/pelican#1725]
From an article, I link to a tag page. The documentation makes me think `[go here]({tag}foobar)` will point at `output/tag/foobar.html`. Instead, it's pointing at `output/posts/tag/foobar.html`, which doesn't exist. This is Pelican 3.5.0 + Python 2.7.8 on Mac OS X 10.10.3.

**Comment by ingwinlu** [comment]
try with the latest master instead of 3.5, should be resolved

**Comment by vtbassmatt** [comment]
OK - I will try to check this tonight. Thanks!

**Comment by vtbassmatt** [comment]
Confirmed fixed in master. Thanks!
