### ISSUE TITLE
AUTHOR_URL not working

### ISSUE THREAD

**Issue by Anshik** [getpelican/pelican#1731]
I've not see AUTHOR_URL in pelican, only in settings.
How can I change url from http://127.0.0.1:8000/author/xxxx.html?

My packages:
Jinja2==2.7.3
Markdown==2.6.2
MarkupSafe==0.23
Pygments==2.0.2
Unidecode==0.04.17
argparse==1.2.1
blinker==1.3
docutils==0.12
feedgenerator==1.7
pelican==3.5.0
python-dateutil==2.4.2
pytz==2015.4
six==1.9.0
wsgiref==0.1.2

**Comment by Anshik** [comment]
fixed AUTHOR_URL in template
<h6>Written by <a href="{{ SITEURL }}/pages/about.html">{{ article.author }}</a> {% if article.category %}in <a href="{{ SITEURL }}/{{ article.category.url }}">{{ article.category}}</a> {% endif %}on {{ article.locale_date }}.{% if article.tags|count > 0 %} Tags: {% for tag in article.tags %}<a href="{{ SITEURL }}/{{ tag.url }}">{{ tag }}</a>, {% endfor %}{% endif %}</h6>
	{{ article.content if FOUNDATION_FRONT_PAGE_FULL_ARTICLES else article.summary }}

**Comment by justinmayer** [comment]
Glad you resolved your issue.
