### ISSUE TITLE
Issue with .rst images: "Error in image directive"

### ISSUE THREAD

**Issue by b1az** [getpelican/pelican#1732]
This is working Pelican 3.5.0:
```
.. |substitution_name| image:: images/image.jpg
		       :alt: image
		       :width: 30%
```
But it's not working when you also add `:align: left` to the above `image` directive. Running `pelican -r --ignore-cache content` errors out:
> (ERROR/3) Error in "image" directive: "left" is not a valid value for the "align" option within a substitution definition.  Valid values for "align" are: "top", "middle", "bottom".

And also:
> (ERROR/3) Undefined substitution referenced: "substitution_name".

The [`image` directive docs](http://docutils.sourceforge.net/docs/ref/rst/directives.html#images) say that `left`, `center` and `right` should also be valid. I've also read on [substitutions](http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#substitution-definitions). 

Now, as soon as I enter `\n` after the above working example (`:width: 30%`), it is immediately obvious that the indentation in Emacs' `ReST mode` is wrong, since the cursor won't align with `:width:`. Am I doing something very wrong or is this indeed a bug?

**Comment by avaris** [comment]
Wording in the docs is a bit ambiguous, but based on the [code](http://docutils.sourceforge.net/docutils/parsers/rst/directives/images.py), if you use substitution definition (which implies an inline image) you can only use vertical alignment (`top`, `middle`, or `bottom`). I'm not sure if this is intended behavior or a bug, but in any case it is a [`docutils`](http://sourceforge.net/projects/docutils/) issue, not `pelican`.

For your other error (`Undefined substitution referenced`), I can't say anything without seeing the actual `.rst` file.

**Comment by b1az** [comment]
You're right, H-alignment makes no sense for a (supposed) inline image. I just shouldn't have been using substitution definition for a standalone image in the first place. And the other error, `Undefined substitution referenced`, then stems from the first one, an invalid `.rst` file altogether.
