### ISSUE TITLE
Pelican on Visual Studio

### ISSUE THREAD

**Issue by arqeco** [getpelican/pelican#1734]
Hello,

Have anyone tried to create a Pelican site on Visual Studio? I have just discovered Visual Studio Community 2013 and really liked it. But I still could not found a way to run Pelican from inside Visual Studio.

This py script

    import pelican
    pelican.main()

generates this error:

...Pelican\env\lib\site-packages\pelican\log.py", line 178, in init
    if (os.isatty(sys.stdout.fileno())
AttributeError: '_DebuggerOutput' object has no attribute 'fileno'

Thanks,
Marcio

**Comment by arqeco** [comment]
Hello,

I just discovered how to do it.

1) Create a new project using the template "Python Application". Notice that I have Python Tools for Visual Studio (PTVS) installed.

2) Inside VS create a virtual environment and install pelican (check PTVS docs on how to do it).

3) The pelican-quickstart step I don´t know how to do in VS since I just copied (Ctrl-C) some files and folders from my previous pelican work folder and pasted in Solution Explorer: content and custom-theme folders, pelicanconf.py, etc.

4) Edit the .py file created with the project to this:

    import pelican
    pelican.main()

This file must be in bold in Solution Explorer. If not, right click it and select "Set as startup file".

5) Now it´s time to run, but DO NOT press F5 (Debug > Start debugging), but instead press Shift-Alt-F5 (Execute project in Python interactive), so you can see the output messages from pelican, and find if you made some mistake.

Greetings,
Marcio

**Comment by justinmayer** [comment]
Thanks for tip, which will be saved here in the issue archive for posterity.

**Comment by arqeco** [comment]
About step 5, it´s better yet use Ctrl-F5 (Run without debugging). I promised to write a better guide... sometime :-)
