### ISSUE TITLE
How does one create an author page?

### ISSUE THREAD

**Issue by EliRibble** [getpelican/pelican#1735]
First off, what do I mean by an author page? Let's say I create an article like so:

```
...
Authors: Eli Ribble
Summary: A test page

...
```

This will populate the `authors` dict with `Eli Ribble` as an author and add that page to the list of articles `Eli Ribble` is an author of. This in turn will usually create a page, `author/eli-ribble.html` that will, for many themes, produce a page that lists out all of the articles associated with that author. Some themes will actually just produce the index page with slightly different <meta> tags, some will produce a blank page, etc. What I'm looking for is if there is a way to make that page have actual content, like an author's bio or resume or CV or something. I attempted to create a page with `slug: author/eli-ribble` but that just gives me a critical error about overwriting an existing page.

Is there a reasonable way I could a) somehow add a arbitrary content into the template context for an author so I could modify the theme to display that content or b) create a page that will map to `author/eli-ribble` without the critical error?

**Comment by jdittrich** [comment]
As far as I am concerned you could create a template or include (`{% include "Author-JohnDoe" %}`) and create the name of that file-to-import from the [author-variable](http://docs.getpelican.com/en/3.5.0/themes.html#templates-and-variables) using the jinja [string-concatenate operator](http://jinja.pocoo.org/docs/dev/templates/#other-operators) (`~`)  like `"author"~{{ author }}~".html"`.

:warning: *have not tested it (yet); it is certainly not ideal to put actual content in templates.*

**Comment by charlesreid1** [comment]
Instead of `slug: author/eli-ribble`, try `save_as: author/eli-ribble.html`. I use the `save_as` metatag all the time, very handy...

**Comment by mitchtbaum** [comment]
https://github.com/getpelican/pelican/issues/884#issuecomment-53165209

**Comment by justinmayer** [comment]
Something like the [Category Metadata plugin](https://github.com/getpelican/pelican-plugins/tree/master/category_meta) — but for authors — might address this use case.

For now I'll close this issue. If someone wants to work on it, feel free to submit a pull request that references this issue number.

**Comment by manugarri** [comment]
@justinmayer reopening this issue. As of now, the Category Metadata plugin is [broken](https://github.com/getpelican/pelican-plugins/issues/855), and given how the plugin was last updated in 2015, probably discontinued. Is there any newer approach to add this functionality?
