### ISSUE TITLE
Load GitHub ribbon via https

### ISSUE THREAD

**Issue by vmarkovtsev** [getpelican/pelican#1736]
http://s3.amazonaws.com/github/ribbons/forkme_right_red_aa0000.png results in a "Mixed Content" warning in Chrome if the blog itself is loaded via https. You should change it to https

**Comment by justinmayer** [comment]
Can you provide more detail? It's hard to know exactly what you're talking about here.

**Comment by vmarkovtsev** [comment]
```
/usr/local/lib/python3.4/dist-packages/pelican/themes/notmyidea/templates/github.html
```
there are plain http links to Amazon S3, which result in mixed content if the generated blog is behind SSL. In other words, everything is loaded from https, but this GitHub image is loaded unencrypted. Google Chrome complains about that and (what's way more important!) changes the page green lock icon to yellow.

**Comment by justinmayer** [comment]
Thanks for the clarification, Vadim. I've fixed this locally and will push my changes tomorrow. (cc: @ingwinlu)

**Comment by vmarkovtsev** [comment]
Great, thanks!
