### ISSUE TITLE
How often are changes pushed out to pypi?

### ISSUE THREAD

**Issue by jonathan-s** [getpelican/pelican#1738]
When I played around with WITH_FUTURE_DATES in python 3 I discovered that it doesn't work with current version in pypi. However I saw that the code is working in the repo. So I'm curious how often you release the fixes to pypi?

I stumbled upon the same issue described in #1666

**Comment by justinmayer** [comment]
How often? It depends, but usually more often than we've seen between 3.5 and 3.6.

If all goes well, 3.6 will be released within a week's time.

**Comment by justinmayer** [comment]
[Pelican 3.6 was just released](http://blog.getpelican.com/pelican-3.6-released.html).
