### ISSUE TITLE
Hidden pages not counted when generating

### ISSUE THREAD

**Issue by jonathan-s** [getpelican/pelican#1739]
If you set status to hidden on a page it won't be counted when generating. These pages are nonetheless generated. So there should be a counter for hidden as well.

**Comment by ingwinlu** [comment]
The patch to that is trivial, but how should the new wording be?
`Done: Processed 42 article(s), 1 draft(s) and 1 (1 hidden) page(s) in 4.88 seconds.` does not have a nice ring to it, and somehow I am not able to come up with something better
