### ISSUE TITLE
Category object has no attribute _slug

### ISSUE THREAD

**Issue by jonathan-s** [getpelican/pelican#1742]
If I'm installing from source `pip3 install git+https://github.com/getpelican/pelican.git` and try to run the latest additions I get the following traceback

```
CRITICAL: Internal failure: "'Category' object has no attribute '_slug'"
  |___
  | Traceback (most recent call last):
  |   File "/Users/jonathan/.virtualenvs/pelican3/lib/python3.4/site-packages/pelican/__init__.py", line 437, in main
  |     pelican.run()
  |   File "/Users/jonathan/.virtualenvs/pelican3/lib/python3.4/site-packages/pelican/__init__.py", line 169, in run
  |     p.generate_context()
  |   File "/Users/jonathan/.virtualenvs/pelican3/lib/python3.4/site-packages/pelican/generators.py", line 546, in generate_context
  |     self.categories[article.category].append(article)
  |   File "/Users/jonathan/.virtualenvs/pelican3/lib/python3.4/site-packages/pelican/urlwrappers.py", line 53, in __hash__
  |     return hash(self.slug)
  |   File "/Users/jonathan/.virtualenvs/pelican3/lib/python3.4/site-packages/pelican/urlwrappers.py", line 35, in slug
  |     if self._slug is None:
  | AttributeError: 'Category' object has no attribute '_slug'
```

**Update**: problem resolved, though it would be nice to have more helpful error. I assume that this will happen to everyone that upgrades and has a cache and for first time users it's a bit confusing.

**Comment by avaris** [comment]
Clear the cache. Cached objects from the previous version cause this issue. Also, duplicate: #1722.

**Comment by jonathan-s** [comment]
Thank you! 

Out of curiosity is there a good way of clearing the cache? I could recreate the environment entirely. But other than that?

**Comment by jonathan-s** [comment]
Actually, the issue seems to be persist even after creating a new environment.

**Comment by avaris** [comment]
Remove the `cache` folder or use `--ignore-cache` option when running `pelican`.

**Comment by jonathan-s** [comment]
Ah, ok that cache. That did work. Though since this error seems to be fairly or at least it's highly likely that it will show everytime someone upgrades a version. It would be nice to have a more helpful error, like "try remove the cache".

**Comment by avaris** [comment]
There is a discussion for turning off `cache-by-default` (see #1689). With that, people had to actively turn on cache in their settings to be affected by it. Plus, we can put a note for it in the release logs.

Apart from those, working around this or trying to catch it would introduce quite a bit of awkward code.

A saner option could be versioning the caches and invalidating/regenerating them in case of a mismatch.

**Comment by justinmayer** [comment]
3.6 was just released and disables caching by default. Upgrade notes at the bottom of the [release announcement](http://blog.getpelican.com/pelican-3.6-released.html) mention the need to delete the `cache` folder.
