### ISSUE TITLE
Rework Content

### ISSUE THREAD

**Issue by ingwinlu** [getpelican/pelican#1748]
Current Content Structure and population has several problems
- ~~[`DEFAULT_STATUS` gets applied to both, pages and articles, making it effectively useless (every setting except published breaks either pages or articles if you don't want to set everything explicitly)~~
- ~~Drafts are 'Articles' that get discarded because of metadata, then get reread as drafts, resulting in unneeded procession and producing issues like #1356~~
resolved via #2128 

Proposal:
- ~~split up content specific `__init__` functions into the actual classes they belong to~~
- ~~remove DEFAULT_STATUS and replace with DEFAULT_PAGE_STATUS and DEFAULT_ARTICLE_STATUS or remove alltogether~~
started in #2128 , maybe able to refactor further

New structure should have the following steamlined flow:
1. generator throws path and class at readers.read_file
2. read_file calls appropriate reader on the path with reader.read
3. reader.read performs the content parse, then parses metadata according to the class (either page OR ArticleDraft) and returns None if one of the checks failed, or the appropiate content class
4. generator now only has to check if content is none and then file the content appropiatly without needing additional checks

Help with any of those points are welcome

**Comment by justinmayer** [comment]
@ingwinlu: Considering this issue to be addressed. If you feel that's not the case, please comment here and we can re-open to discuss further.
