### ISSUE TITLE
Consolidate setting deprecation

### ISSUE THREAD

**Issue by ingwinlu** [getpelican/pelican#1749]
A lot of settings deprecation handling is distributed all over the code; need to gather it all up and put it into a single function.

**Comment by leotrs** [comment]
I would like to take a stab at this. @ingwinlu do you have any examples of this deprecation handling laying around?

**Comment by justinmayer** [comment]
@ingwinlu / @leotrs: Any thoughts regarding how to proceed with this endeavor?

**Comment by justinmayer** [comment]
Re-opening since @oulenz was kind enough to submit a related pull request.

**Comment by justinmayer** [comment]
Thanks to @oulenz, the remaining settings deprecation logic has been consolidated and included in the just-released Pelican v4.1.3, courtesy of [AutoPub](https://justinmayer.com/projects/autopub/).
