### ISSUE TITLE
Change Makefile to copy also hidden files in root folder

### ISSUE THREAD

**Issue by gsportelli** [getpelican/pelican#1751]
scp won't copy hidden files in root folders, e.g., ".htaccess"
this is because in the Makefile the command line is

    scp -P $(SSH_PORT) -r $(OUTPUTDIR)/* $(SSH_USER)@$(SSH_HOST):$(SSH_TARGET_DIR)

it should be instead

    scp -P $(SSH_PORT) -r $(OUTPUTDIR)/. $(SSH_USER)@$(SSH_HOST):$(SSH_TARGET_DIR)

(note the dot replacing the asterisk)

**Comment by ingwinlu** [comment]
the quickstart generated files are by no means a solution for everything and are intended to be modified to suite the users needs.

though I can not come up with any reason someone would have hidden files in his output directory that he does not want uploaded (I also can not come up with any reason someone wants to use scp instead of rsync either so that might not say much).

**Comment by gsportelli** [comment]
The point is that there is a file that I do want to copy, with either ssh or rsync: it is .htaccess and it is quite common. If you use the "$(OUTPUTDIR)/*" syntax, hidden files will not be copied, resulting in an at least unexpected behaviour. If you use the "$(OUTPUTDIR)/." syntax they will be copied instead.

In the specific, it took me an hour to understand why my .htaccess was not being copied. I just wrote so as to save that time to anybody else.

**Comment by ybroze** [comment]
I encountered the same problem as well. It's easy enough to twiddle your own Makefile, but it feels like this should work out-of-the-box.

**Comment by ybroze** [comment]
UPDATE: This seems to do the trick without needing to do any Makefile changes:

```
EXTRA_PATH_METADATA = {
    'extra/.htaccess': {'path': '.htaccess'},
    'extra/robots.txt': {'path': 'robots.txt'},
    'extra/favicon.ico': {'path': 'favicon.ico'},
}
```

**Comment by justinmayer** [comment]
`EXTRA_PATH_METADATA` is probably the best approach at this time.
