### ISSUE TITLE
make source code pretty

### ISSUE THREAD

**Issue by ingwinlu** [getpelican/pelican#1752]
* docutils strings are `'''` and `"""` in some places.
* lots of pep8 violations
* add a tox environment that runs flake8 checks
```
[testenv:flake8]
basepython = python2.7
deps =
    flake8
commands =
    flake8 pelican
```

**Comment by ingwinlu** [comment]
@justinmayer i suggest delaying this till after the release

**Comment by justinmayer** [comment]
I was going to suggest the same thing.
