### ISSUE TITLE
when pelican build the static html file, it does not skip the not-modified content file bu default ?

### ISSUE THREAD

**Issue by xh84** [getpelican/pelican#1754]
it will waste much time!!!!

**Comment by justinmayer** [comment]
Um, what? [This is already covered in the docs.](http://docs.getpelican.com/en/latest/settings.html#reading-only-modified-content)

**Comment by xh84** [comment]
o ,  i just see that the modification times of the generated *.html files always change everytime i use "pelican content" command.

does it skip the not-modified content file bu default when i use "pelican content" command?

does i have to set the LOAD_CONTENT_CACHE, CACHE_PATH, CHECK_MODIFIED_METHOD in my pelicanconf.py manually

how can i find it works?

**Comment by justinmayer** [comment]
As noted in the Getting Help section of the docs, the best way is to ask folks on IRC.

**Comment by xh84** [comment]
i read "Reading only modified content" and "Why does Pelican always write all HTML files even with content caching enabled?" of the docs, and i think pellican can rebuild the site or a post up to users.

for example:
after using a new theme or plugin, the users can rebuild the whole site.
after that the users can just rebuild the modified post or page everytime but not need to rebuild the whole site.

i don't know am i right?
i am a new guy!!

**Comment by justinmayer** [comment]
As is explained in the docs, when caching is enabled, that is indeed how Pelican behaves.

**Comment by xh84** [comment]
i am confused.
when enable cache, pelican read modified posts, but still write all HTML files.
what does pelican write to html file when a post is not modified?

**Comment by justinmayer** [comment]
What is the actual problem? Generation is too slow? Something else?

In any case, what you probably want is the [`--write-selected`](https://encrypted.google.com/search?hl=en&q=pelican%20%22write-selected%22) option.

If you need further assistance, please ask on IRC, as I have already noted above.
