### ISSUE TITLE
Categories and tags of pages are ignored?

### ISSUE THREAD

**Issue by asmaier** [getpelican/pelican#1757]
For my pelican 3.5 website I created some pages (not articles!) at
    
    content/pages/about.md  
    content/pages/quotes.md

But when I generate the website no categories and tags are shown at

    output/categories.html
    output/tags.html

As soon as I convert the pages into articles by moving them into

    content/about.md
    content/quotes.md

categories and tags for these articles are generated in `categories.html` and `tags.html` . To make sure this is not a problem with my template I confirmed that this is also the case using just the default template. Is this a bug or do I have to add some configuration option to also generate categories and tags for pages?

**Comment by avaris** [comment]
I won't classify this as a bug, at most maybe a missing feature. `category` or `tags` are relevant only for articles. You can have them on pages if you want but `category.html` or `tags.html` templates are used for articles.

**Comment by asmaier** [comment]
Ok. It would also already help to simply mention this fact in the documentation at http://docs.getpelican.com/en/latest/content.html#pages .

**Comment by avaris** [comment]
Well, you're looking at the wrong place. Your question is about the output (i.e. HTML files) which is handled by the theme. And the documentation for [theme](http://docs.getpelican.com/en/latest/themes.html) states that the variables `category.html` or `tags.html` get are collections of articles (no pages).

**Comment by asmaier** [comment]
Thank you for pointing me to the right place. I did not find that information before.

**Comment by CNG** [comment]
This also confused me for a good long time before I finally found this definitive documentation (in this closed Github issue) the tags of pages are not intended to be tags like on articles. The place in the docs where _I_ was looking was [Creating themes — Pelican 4.2.0 documentation](http://docs.getpelican.com/en/latest/themes.html#page) where it lists the attributes of `Page` objects, including 
> tags:  List of [Tag](http://docs.getpelican.com/en/latest/themes.html#object-author-cat-tag) objects.

**Comment by martyheyman** [comment]
So, Pelican is a blogging engine. Trying to develop a Web site, blogging is almost an afterthought, and categories and tags aren't supported. I get it.

**Comment by virtadpt** [comment]
Categories and tags are supported.  It's the theme that makes them available more than Pelican itself.

**Comment by martyheyman** [comment]
Thanks. The previous replies in the thread led me astray. Apologies. Hints on a theme to look at to adapt ours?

—
Marty 
+1 650 963-7606

**Comment by virtadpt** [comment]
Take a look at the [Brutalist](https://github.com/mc-buckets/brutalist) Pelican theme.  Support for categories as well as tags is part of the basic template files.  If you look in there it's an excellent introduction to how they can be used in a site with a couple of Jinja tags.

**Comment by martyheyman** [comment]
Thanks. I really appreciate the pointer!

—
Marty 
+1 650 963-7606
