### ISSUE TITLE
Trailing dot in author name causes file/link mismatch

### ISSUE THREAD

**Issue by leaveye** [getpelican/pelican#1761]
when post author name ending with dot (`.`), the author file name generated drops it, and the links in all generated `.html` files keeps it.

eg.
```
# in any-post.md
Author: Foobar C.

# in output/author/
foobar-c.html

# in output/any-post.html
<a href="/author/foobar-c..html">...
```

**Comment by justinmayer** [comment]
Interesting conundrum. Is this something you would like to help us fix?
