### ISSUE TITLE
how can add custom metadata and show image on index.html or category.html?

### ISSUE THREAD

**Issue by xh84** [getpelican/pelican#1763]
when i creat my theme, i get some problems:
1. how can i add custom metadata for every article? i add a metadata in article file as ":mymeta: mywords", and use it as "{{article.mymeta}}" , but it seems does not work?
2. is there a variable looks like "article.images", which can get the all images in the article, or a variable looks like "article.image (article.first_image or article.last_image)" can get the first image or the last image?

**Comment by avaris** [comment]
1) What does "not work" mean? If you're getting errors, it's a good idea to show them.
2) Not by default but a plugin can extract them and create those variables.

**Comment by xh84** [comment]
when i use {{article.mymeta}}, i get no error, but it shows nothing at the front after publishing website for testing

**Comment by ingwinlu** [comment]
if article.mymeta outputs nothing, it is None or "";

as for 2) look at the gallery plugin available in pelican-plugins

**Comment by xh84** [comment]
but i have set ":mymeta: mywords" in my article file, how could it be none or ""

**Comment by ingwinlu** [comment]
since you don't provide any means for us to reproduce, how should we know?

**Comment by xh84** [comment]
i am sorry, when i now test it again, it works!!!!

**Comment by xh84** [comment]
maybe because of cache? i don't why?
