### ISSUE TITLE
WARNING: Unable to find `the path to my article`, skipping url replacement

### ISSUE THREAD

**Issue by xh84** [getpelican/pelican#1765]
under 'content' folder there are two articles, when i use 'pelican content', it tells me :
WARNING: Unable to find `/keyboard-review.md`, skipping url replacement
Done: Processed 1 article(s), 0 draft(s) and 0 page(s) in 0.61 seconds.

my os:win8 64bit
pelican:3.5

**Comment by ingwinlu** [comment]
and what is in your articles?

this is the second issue you open up without providing any means to debug your issue. Read https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst or solve your problems alone.

**Comment by xh84** [comment]
the article 'keyboard-review.md' is under  'content' folder just as default, and the content in it:

Title: My First Review
Date: 
Category: Review

Following is a review of my favorite mechanical keyboard.


<table>
    <tr>
        <td>Foo</td>
    </tr>
</table>

**Comment by xh84** [comment]
i have an another computer in my conpany with os win7 32bit and pelican 3.50, and it works well.
but i copy the same 'content' folder to the computer at home with win8 64bit and pelican 3.50, it gets the problem

**Comment by xh84** [comment]
how can i debug to find the problem?

**Comment by justinmayer** [comment]
Since the current version of Pelican is 3.6, I suggest you update to the latest version on all of your systems before reaching out for assistance.

**Comment by MinchinWeb** [comment]
@xh84 : Make sure your link to the file has the right capitalization. Windows doesn't care about capitalization, but Pelican does. I.e. `keyboard-review.md` and `keyboard-review.MD` are the same to Windows, but not Pelican.

**Comment by leotrs** [comment]
@xh84 please update. Did you resolve this issue?

**Comment by gouthambs** [comment]
I use 3.6, and I have a similar problem. My guess is that this arises from some plugin perhaps?

**Comment by gouthambs** [comment]
@leotrs Do you use the `share_post` plugin? I had a similar problem where the links were not resolving. It turns out that my share_post plugin was stale, and I just updated it. Now links resolve. Perhaps you are having a similar issue?

**Comment by leotrs** [comment]
@gouthambs I do not have this issue, I was trying to move the conversation along. Maybe @xh84 can update.

**Comment by justinmayer** [comment]
@xh84: Please feel free to comment here if you need additional guidance.

**Comment by rask004** [comment]
@xh84  Having similar problem.  Using Pelican 3.7.1.

Have checked Capitalisation, and path is correct. Also presence of whitespace in the path has no effect.

**Comment by rask004** [comment]
My articles are in a subfolder (in ARTICLE_PATHS list in settings). example ref I am using is

`href="{filename}\articles\Cloud Apps\article.html"`

Error response is:

WARNING: Unable to find `\articles\Cloud Apps\article.html`, skipping url replacement.

Happens for both development settings and production settings.

**Comment by avaris** [comment]
@rask004 Use `/` instead of `\`.

**Comment by xxks-kkk** [comment]
I had similar problem but resolve it via `pip install Markdown`
