### ISSUE TITLE
Pygments syntax highlighting options in Markdown

### ISSUE THREAD

**Issue by afedulov** [getpelican/pelican#1773]
How can options, like line numbers be activated in Markdown?

**Comment by ingwinlu** [comment]
go ahead and close it if it is resolved

**Comment by afedulov** [comment]
@ingwinlu, sorry it turns out I still do have a question. Edited the original question.

**Comment by justinmayer** [comment]
If you want to selectively enable line numbers on a per-block basis, use the [shebang identifier](http://pythonhosted.org/Markdown/extensions/code_hilite.html#shebang-no-path) instead of colons:

    #!python
    print("Hello world")

If you _always_ want line numbers, add this to your settings file:

    MD_EXTENSIONS = ['codehilite(css_class=highlight,linenums=True)','extra']

**Comment by justinmayer** [comment]
If you have any follow-up questions, please do so via our IRC channel ([as is explained in the docs](http://docs.getpelican.com/en/latest/contribute.html#how-to-get-help)).
