### ISSUE TITLE
Provide a way to generate nofollow links

### ISSUE THREAD

**Issue by dimo414** [getpelican/pelican#1782]
The markdown parser generates all links (both local and external) as "clear" links.  Some way to mark certain links (or even just all external links, if that's the best that can be done) as [nofollow](https://support.google.com/webmasters/answer/96569) links would be valuable.

**Comment by kylef** [comment]
What about just putting this in your markdown files?

```
<a rel="nofollow" href="my-link">text</a>
```

**Comment by dimo414** [comment]
Yeah, that would work.  It's a pretty standard use case though, it's too bad we have to resort to HTML to support web crawler best-practices.

Will using HTML still support things like `{filename}` links?

**Comment by avaris** [comment]
If markdown doesn't support a way to add `rel` attribute to its link syntax, pelican can't do much. As for `{filename}`, yes, it should work for HTML as well.

**Comment by dimo414** [comment]
Fair enough, I'll explore the issue with Markdown. [This](https://github.com/xyres/markdown-nofollow/) looks promising, but appears to simply blanket-nofollow all processed links, which probably isn't what most users will want.

**Comment by mitchtbaum** [comment]
With pristine content sources, you should be able to generate any desired output.  It would seem easiest to use a "formatter plugin", like [summary_footnotes](https://github.com/dperelman/summary_footnotes) which would rewrite your (selected) articles' outputs to this standard.

**Comment by johanson** [comment]
`[text](http://pelican.com/){:rel=nofollow}`

**Comment by houmie** [comment]
> [text](http://pelican.com/){:rel=nofollow}

Doesn't work.
