### ISSUE TITLE
Disqus comments not loading on all articles 

### ISSUE THREAD

**Issue by mclearc** [getpelican/pelican#1784]
I'm having this weird problem where Disqus loads on [some](http://colinmclear.net/2015/maintain-a-cv-in-html-and-pdf) article pages but [not others](http://colinmclear.net/2015/pandoc-letters). I can't see any relevant difference between them. Any ideas? Thanks!

**Comment by avaris** [comment]
I can see the comments section in both articles.

**Comment by justinmayer** [comment]
As can I.

**Comment by mclearc** [comment]
Sorry -- I came up with the (weird) following resolution.

I pasted the following into the two pages that were not loading comments

`````
<div id="disqus_thread"></div>  
 <script type="text/javascript">  
/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
var disqus_shortname = 'YOUR_DISQUS_SHORTNAME'; // required: replace example with your forum shortname

/* * * DON'T EDIT BELOW THIS LINE * * */
(function() {
var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
(document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')`[0]).appendChild(dsq);
`})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

`````
After which I ran a local server, and lo, the comment section showed up. I then *deleted* the above, saved the file, and pushed the changes to github and now comments show on the website. I don't know what that was all about, but things seem to be working. I'll close the issue, but if you think you have any idea what happened I'd be curious to hear.
