### ISSUE TITLE
Set followlinks=True in utils.py copy

### ISSUE THREAD

**Issue by nkabir** [getpelican/pelican#1785]
When using themes with symlinked assets, the default method of `utils.copy` does not copy all of the assets. This fixes the issue:

```
for src_dir, subdirs, others in os.walk(source_, followlinks=True):

```

Any objection to making that the default behavior?

**Comment by avaris** [comment]
Sounds good.

**Comment by justinmayer** [comment]
Hi Norman. Would you submit a pull request, including docs and tests, that implements this? Before doing so, please read the [Contributing Guidelines](http://docs.getpelican.com/en/latest/contribute.html) thoroughly. Thanks!

**Comment by networkpadawan** [comment]
when will this patch be implemented? i have this issue if DELETE_OUTPUT_DIRECTORY is true then css file wil not be generated...

**Comment by justinmayer** [comment]
A fix is currently pending better tests — see #1863.

**Comment by avaris** [comment]
Oh, i did this with #2306 and completely forgot there were previous issues/PRs regarding it. No tests though :(.

**Comment by justinmayer** [comment]
Thanks to @avaris, the relevant change is now in master. Anyone want to contribute tests for that change?
