### ISSUE TITLE
Internal linking {filename} syntax appears to be unaware of save_as attributes

### ISSUE THREAD

**Issue by Cheekysoft** [getpelican/pelican#1786]
Using the HTML syntax

**pages/contact.html**

    ...
    <head>
      <title>Contact Us</title>
      <meta name="save_as" content="contact.html" />
    </head>
    ...

**pages/home.html**

    ...
    <body>
      Please <a href="{filename}contact.html">Contact Us</a>
    </body>
    ...

The generated link in the rendered `home.html` is to the default filename `pages/contact-us.html` and not to the actual created file (as specified in the save_as attribute) `contact.html`.

**Comment by avaris** [comment]
`{filename}` uses the `url`, so you also need to define the `url` metadata:

```html
<head>
  <title>Contact Us</title>
  <meta name="save_as" content="contact.html" />
  <meta name="url" content="contact.html" />
</head>
```

**Comment by justinmayer** [comment]
Thanks for the tip, @avaris.

@Cheekysoft: Does that resolve your issue?

**Comment by Cheekysoft** [comment]
@justinmayer It does indeed. Thanks all.

But I wonder if in a future release, pelican should consider internally adjusting the default `url` based on the `save_as`. 

For now this is probably a documentation improvement; to make it clear that `url` must be also be set if `save_as` is used.

**Comment by Cheekysoft** [comment]
The relationship --and apparent redundance-- between the two always threw me a little sideways; I came to the (incorrect) conclusion that one would only set `url` when there was a "mismatch" e.g. for the likes of DirectoryIndex files:

    <meta name="save_as" content="index.html" />
    <meta name="url" content="/" />


or perhaps in the case when aliases may be set up on the web server and "friendly urls" were wanted instead of filepath-based URLs

**Comment by justinmayer** [comment]
It certainly is not redundant; while the example use case you provided is likely the most common, there are other instances in which the user wants to save a file with a different name and location than the corresponding URL link.

Feel free to submit a pull request if you think the documentation could be improved.
