### ISSUE TITLE
truncate_html_words() fails to truncate content when tags span multiple lines

### ISSUE THREAD

**Issue by andreacorbellini** [getpelican/pelican#1787]
I have an article with the following content:

    <strong>text text text <span                                              
    style="font-family:serif;white-space:nowrap;"> text text text</strong>

and I've set `SUMMARY_MAX_LENGTH` to a non-zero value.

When the article gets truncated by Pelican, here's the markup I get:

    <strong>text text text <span
    style="font-family:serif ...</strong></p>

As you can see, Pelican believes that `style="font-family:serif;white-space:nowrap;"` is text and truncates it without correctly closing the `<span>`, resulting in a broken web page.

The problem occurs because the regular expression `re_words` does not look for newline characters. This can be fixed by using the `DOTALL` option:

    re_words = re.compile(r'&.*?;|<.*?>|(\w[\w-]*)', re.U | re.DOTALL)

[This can also be fixed by using a HTML parser, but I guess you already know that :)]

**Comment by iKevinY** [comment]
Looks like this issue can be closed since #1788 has been merged in. /cc @justinmayer

**Comment by justinmayer** [comment]
This issue has been addressed by @andreacorbellini via the above-mentioned pull request. (Thanks for the nudge, Kevin!)
