### ISSUE TITLE
Locale setting isn't working

### ISSUE THREAD

**Issue by J-Moravec** [getpelican/pelican#1789]
Language is set to en (u'en')
Locale is set to anything english
still produce date in my locale.

**Comment by justinmayer** [comment]
Presumably this is `Colombo` from IRC. Either way, please keep this in IRC.

This is not a proper bug report. Quite honestly, it is not even remotely close to being a halfway-decent bug report. It doesn't follow any of the [guidelines stated in the docs](http://docs.getpelican.com/en/latest/contribute.html). 

We **want** to help you. We can't do that if you don't follow the guidelines.
