### ISSUE TITLE
Article template in the simple theme renders the description field incorrectly

### ISSUE THREAD

**Issue by boite** [getpelican/pelican#1792]
some-article.md

    title: My Title
    date: 2015-08-07T00:07:00+00:00
    description: My description
    
    Hello world.

results in:-

    <meta name="description" content="M" />
    <meta name="description" content="y" />
    <meta name="description" content=" " />
    <meta name="description" content="d" />
    <meta name="description" content="e" />
    <meta name="description" content="s" />
    <meta name="description" content="c" />
    <meta name="description" content="r" />
    <meta name="description" content="i" />
    <meta name="description" content="p" />
    <meta name="description" content="t" />
    <meta name="description" content="i" />
    <meta name="description" content="o" />
    <meta name="description" content="n" />

Surely then, the `article.html` template should not do:-

    {% for description in article.description %}
        <meta name="description" content="{{description}}" />
    {% endfor %}

It should be:-

    {% if article.description %}
        <meta name="description" content="{{article.description}}" />
    {% endif %}

Or have I missed something?

**Comment by ingwinlu** [comment]
yes, pr it
