### ISSUE TITLE
Anchor links in article summary are broken

### ISSUE THREAD

**Issue by marwinxxii** [getpelican/pelican#1796]
I have a table of contents with links to chapters in article, this table appears in the beginning of the article and is shown in summary on articles list page.

While links to chapters (e.g. #chapter1) work OK on article page, they are broken on article list, because their URL is incorrect, e.g. `index.html#chapter1` instead of `article1.html#chapter1`.

I have `RELATIVE_URLS = False` in config.
Shouldn't this option affect internal links too?

My workaround is custom Jinja filters, which strips such links from summary.
But is there a better way to do this or is it a bug?

**Comment by ingwinlu** [comment]
are you sure your toc links are `article1.html#chapter1`? I am fairly sure they are just `#chapter1` (at least with my toc plugin). which would explain the behaviour. not sure we can do a lot for you here, maybe provide full links to the article headers somehow.

**Comment by marwinxxii** [comment]
I forgot to say, that my toc is basically a list with links to headers.

@ingwinlu right, I meant `#chapter1`, which is fine when opened on `arcticle1.html` page, but not on index page.

**Comment by ingwinlu** [comment]
if you write your toc yourself, nothing is stopping you from using [linking to internal content](http://pelican.readthedocs.org/en/latest/content.html#linking-to-internal-content) to write your links, those are parsed in summary as well (`FORMATTED_FIELDS`)

```
  1 Title: linking
  2 Date: 2010-12-03 10:20
  3 Status: draft
  4 
  5 [a link to h1]({filename}003_linking.md#h1)
  6 [a link to h2]({filename}003_linking.md#h2)
  7 
  8 
  9 #h1
 10 ##h2
```

**Comment by marwinxxii** [comment]
Yeah, thanks, I didn't think of writing links myself, because I'm lazy :-) May be it's better than strip links programmatically.

But original problem with relative links remains, though we have a couple of workarounds.

**Comment by ingwinlu** [comment]
manually written links are not influenced by that setting, relative urls only influences urls generated by pelican.

if you want to postprocess such links, you might want to write a plugin.

**Comment by justinmayer** [comment]
@marwin: Please feel free to comment here if you need additional guidance.
