### ISSUE TITLE
Separate Pip requirements files for each use case

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1808]
**Problem:** The current `dev_requirements.txt` file was originally meant for use by Pelican developers but is now also used by Travis and `tox` for testing purposes. These are two different use cases that are not well served by a single Pip requirements file.

**Solution:** Create separate requirements files for each use case while minimizing redundancy and staying DRY.

I’d like to propose the following revised structure for Pip requirements:

    project_root/
    └── requirements/
        ├── developer.pip
        └── test.pip

Proposed contents for `requirements/test.pip`:

    # Tests
    mock

    # Optional packages
    Markdown
    BeautifulSoup4
    lxml
    typogrify

Proposed contents for `requirements/developer.pip`:

    -r test.pip

    # Development
    flake8
    -e git+https://github.com/public/flake8-import-order#egg=flake8-import-order
    sphinx
    tox

    # Release issuance
    bumpr==0.2.0
    wheel

As an additional bonus, using the `.pip` extension instead of the generic and information-free `.txt` suffix will allow for easy syntax highlighting (e.g., in Vim).

**Comment by justinmayer** [comment]
Any comments or feedback on this Pip requirements proposal? cc: @avaris @ingwinlu @kylef @iKevinY

**Comment by iKevinY** [comment]
Looks good to me. The fact that `-r test.pip` can be used to reduce redundancy is quite convenient.

**Comment by justinmayer** [comment]
Agreed. Thanks for the input, Kevin.  (^_^)

**Comment by ingwinlu** [comment]
the problem with the `developer.pip` is the following:

either I want to use tox I don't want to use tox.
*  If I don't want to use tox, then why would I install it?
*  If I want to use tox, I don't want anything installed except tox (as tox handles the install in virtual environments)

The current structure respects that, it does not force you to use any specific tooling, the requirements.txt only enables you to run 'most' (we can't pip install pandoc) test cases.

Additionally, a developer does not need wheel and bumpr, only maintainers need those.

**Comment by justinmayer** [comment]
Thanks for the input, Winlu. I have no problem removing `tox`, `bumpr`, and `wheel` from `developer.pip`. I'll work on implementing this later in the week.

**Comment by avaris** [comment]
I agree. `tox`, `bumpr` and `wheel` aren't needed for development, I'd prefer to not have them in there.
