### ISSUE TITLE
UnicodeEncodeError and BeautifulSoup parser error

### ISSUE THREAD

**Issue by jsmm** [getpelican/pelican#1809]
Congratulations for the development of Pelican!

I have installed Pelican with no problem but I also get two errors having to do with parsing and encoding. 

I use Apple's Yosemite in Spanish (es-ES). I had Pelican 3.6.4 installed via pip install pelican in its own virtualenv. Now I have 3.6.4.dev0 after pip install git+https://github.com/getpelican/pelican#egg=pelican Yet the same errors. I write in MultiMarkDown.

1) Always:
```
UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html5lib"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

To get rid of this warning, change this:
BeautifulSoup([your markup])
to this:
BeautifulSoup([your markup], "html5lib")
 markup_type=markup_type))
```
2) When setting TYPOGRIFY = True
```
ERROR: Could not process pages/Sample MultiMarkdown Document.md
 | UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 15: ordinal not in range(128)
 |___
 | Traceback (most recent call last):
 |   File "/Users/ant/Dev/dev_pelican_notes/venv/lib/python2.7/site-packages/pelican/generators.py", line 616, in generate_context
 |     context_sender=self)
 |   File "/Users/ant/Dev/dev_pelican_notes/venv/lib/python2.7/site-packages/pelican/readers.py", line 548, in read_file
 |     context=context)
 |   File "/Users/ant/Dev/dev_pelican_notes/venv/lib/python2.7/site-packages/pelican/contents.py", line 149, in __init__
 |     signals.content_object_init.send(self)
 |   File "/Users/ant/Dev/dev_pelican_notes/venv/lib/python2.7/site-packages/blinker/base.py", line 267, in send
 |     for receiver in self.receivers_for(sender)]
 |   File "/Users/ant/Dev/dev_pelican_notes/pelican-plugins/pelican-toc/toc.py", line 100, in generate_toc
 |     content.toc = BeautifulSoup(tree.toString()).decode(formatter="html")
 |   File "/Users/ant/Dev/dev_pelican_notes/pelican-plugins/pelican-toc/toc.py", line 80, in toString
 |     ret = ret + child.toString()
 |   File "/Users/ant/Dev/dev_pelican_notes/pelican-plugins/pelican-toc/toc.py", line 76, in toString
 |     ret = ret + "<li><a class='toc-href' href='#{0}' title='{1}'>{1}</a>".format(self.id, self.header)
 | UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 15: ordinal not in range(128)
```
My requirements.txt
> beautifulsoup4==4.4.0
> blinker==1.4
> cssmin==0.2.0
> docutils==0.12
> ecdsa==0.13
> Fabric==1.10.2
> feedgenerator==1.7
> gitdb==0.6.4
> GitPython==1.0.1
> html5lib==0.999999
> Jinja2==2.8
> Markdown==2.6.2
> MarkupSafe==0.23
> pandoc==1.0.0a8
> paramiko==1.15.2
> pelican==3.6.4.dev0
> pycrypto==2.6.1
> Pygments==2.0.2
> python-dateutil==2.4.2
> pytz==2015.4
> sh==1.11
> six==1.9.0
> smartypants==1.8.6
> smmap==0.9.0
> typogrify==2.0.7
> Unidecode==0.4.18
> webassets==0.11.1
> wheel==0.24.0

Thanks for your help.

**Comment by ingwinlu** [comment]
both errors occur in plugins, take it to the respective repositories

**Comment by jsmm** [comment]
I guess for the UnicodeEncodeError the problem is with pelican-toc. 
But I don't know for the BeautifulSoup error.

**Comment by ingwinlu** [comment]
I can't either since you did not provide all the information required as per the contribution guidelines (which you apparently ignored when opening this issue)

**Comment by ingwinlu** [comment]
both warnings could be from pelican-toc, maybe you have a very old version?

**Comment by ingwinlu** [comment]
@justinmayer can we close this? pelican-toc implemented unicode headers months ago and this really has no place here.
