### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by lemonsong** [getpelican/pelican#1810]
Hi guys, I met with an error as follows:

kis-MacBook-Air:blog xxx$ make html
pelican /Volumes/L/github/xxx.github.io/blog/content -o /Volumes/L/github/xxx.github.io/blog/output -s /Volumes/L/github/xxx.github.io/blog/pelicanconf.py 
ERROR: Could not process ./._test.md
  | UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 37: invalid start byte
ERROR: Could not process ./._test2.md
  | UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 37: invalid start byte
Done: Processed 2 articles, 0 drafts, 0 pages and 0 hidden pages in 0.78 seconds.

test and test2 are two articles under content folder.

I use OS Yosemite 10.10.2
The pip list is as follows:
abstract-rendering (0.5.1)
argcomplete (0.8.1)
astropy (0.4.2)
atom (0.3.9)
backports.ssl-match-hostname (3.4.0.2)
BeautifulSoup (3.2.1)
beautifulsoup4 (4.3.2)
binstar (0.7.1)
bitarray (0.8.1)
blaze (0.6.3)
blinker (1.4)
blz (0.6.2)
bokeh (0.6.1)
bosonnlp (0.5.0)
boto (2.32.1)
casuarius (1.1)
cdecimal (2.3)
cffi (0.8.6)
chaco (4.4.1)
colorama (0.3.1)
conda (3.9.1)
conda-build (1.8.2)
conda-env (2.1.3)
configobj (5.0.6)
cryptography (0.5.4)
Cython (0.21)
cytoolz (0.7.0)
DataShape (0.3.0)
decorator (3.4.0)
docutils (0.12)
ecdsa (0.13)
enable (4.3.0)
enaml (0.9.8)
Fabric (1.10.2)
feedgenerator (1.7)
Flask (0.10.1)
Flask-WTF (0.11)
future (0.13.1)
futures (2.1.6)
gevent (1.0.1)
gevent-websocket (0.9.3)
ghp-import (0.4.1)
greenlet (0.4.4)
grin (1.2.1)
h5py (2.3.1)
httplib2 (0.9)
ipython (3.0.0)
itsdangerous (0.24)
jdcal (1.0)
Jinja2 (2.7.3)
jsonschema (2.4.0)
kiwisolver (0.1.3)
llvmpy (0.12.7)
lxml (3.4.0)
Markdown (2.6.2)
MarkupSafe (0.23)
matplotlib (1.4.0)
mock (1.0.1)
multipledispatch (0.4.7)
networkx (1.9.1)
nltk (3.0.0)
nose (1.3.4)
numba (0.14.0)
numexpr (2.3.1)
numpy (1.9.2)
oauth2 (1.5.211)
oauthlib (0.7.2)
openpyxl (1.8.5)
pandas (0.14.1)
paramiko (1.15.2)
patsy (0.3.0)
pelican (3.6.3)
pep8 (1.5.7)
PIL (1.1.7)
pip (1.5.6)
ply (3.4)
psutil (2.1.1)
py (1.4.25)
PyAudio (0.2.7)
pycosat (0.6.1)
pycparser (2.10)
pycrypto (2.6.1)
pycurl (7.19.5)
pyenchant (1.6.6)
pyface (4.4.0)
pyflakes (0.8.1)
Pygments (2.0.2)
pyOpenSSL (0.14)
pyparsing (2.0.1)
pytest (2.6.3)
python-dateutil (1.5)
python-twitter (2.2)
pytz (2014.7)
PyYAML (3.11)
pyzmq (14.5.0)
redis (2.9.1)
requests (2.5.3)
requests-oauthlib (0.4.2)
rope (0.9.4)
runipy (0.1.1)
scikit-image (0.10.1)
scikit-learn (0.15.2)
scipy (0.14.0)
setuptools (14.0)
simplejson (3.6.5)
six (1.8.0)
smartypants (1.8.6)
sockjs-tornado (1.0.1)
Sphinx (1.2.3)
spyder (2.3.3)
SQLAlchemy (0.9.7)
statsmodels (0.5.0)
sympy (0.7.5)
tables (3.1.1)
toolz (0.7.0)
tornado (4.0.2)
traits (4.4.0)
traitsui (4.4.0)
tweepy (3.4.0)
twitter (1.16.0)
TwitterSearch (1.0.0)
typogrify (2.0.7)
ujson (1.33)
unicodecsv (0.9.4)
Unidecode (0.4.18)
virtualenv (12.0.7)
Werkzeug (0.10.1)
wsgiref (0.1.2)
WTForms (2.0.2)
xlrd (0.9.3)
XlsxWriter (0.5.7)
xlwt (0.7.5)

Thanks in advance!

**Comment by avaris** [comment]
Please post a [debug log](http://docs.getpelican.com/en/3.6.3/contribute.html#how-to-get-help):

> Upload detailed and complete output logs and backtraces 
> (remember to add the --debug flag: pelican --debug content [...])

From the small info you have:

> Done: Processed 2 articles

So it did successfully find and process 2 articles.

But failed for stuff like `._test.md`, which looks like an editor-generated file with invalid utf-8 chars.

**Comment by justinmayer** [comment]
It looks like you're trying to do things across a network. Try moving your content and output directories to a local volume instead. (Reference: http://lmgtfy.com/?q=mac+dot+underscore)

**Comment by avaris** [comment]
Ah, in that case, you can also consider `IGNORE_FILES` setting.

**Comment by lemonsong** [comment]
It works. Thanks a lot. I do use an external volume because of the limited space of my laptop. I finally add IGNORE_FILES = ['._*'] to pelicanconf.py
