### ISSUE TITLE
*_URL settings dont work with >2 path tokens (split by /)

### ISSUE THREAD

**Issue by koobs** [getpelican/pelican#1811]
It appears Pelican only uses the last two tokens in the path for *_URL settings.

```
CATEGORY_URL = "blog/category/{slug}/"
CATEGORY_SAVE_AS = "blog/category/{slug}/index.html"
```

Causes the following error:

```
WARNING:root:Unable to find `/category/<categoryname>/` or variations.
```

*_SAVE_AS settings dont appear to be affected (though they're probably worth checking)

**Comment by ingwinlu** [comment]
since I personally use one with 4 I highly doubt that.

why not follow the guidelines and post everything necessary to debug the issue?

**Comment by koobs** [comment]
@ingwinlu Apologies, I had already tested with default pelican config/theme as per the guidelines, and was unable to reproduce. This was expected (and an invalida test) as the default config/theme don't move articles/categories to /blog/*

Having said that, I identified the root cause:

https://github.com/frankV/twenty-pelican-html5up/blob/master/templates/base.html#L60

I switched this to: 

```
<a href="{{ SITEURL }}/{{ cat.url|lower}}">{{ cat }}</a>
```

cc @frankV
