### ISSUE TITLE
`404.md` not exported to `404.html`

### ISSUE THREAD

**Issue by cadadr** [getpelican/pelican#1812]
The file with name `404.md` does not export to anything. The only way that I can get a 404.html in the output is to make a file, e.g. `absent.md`, in the header of which is written `save_as: 404.html`.

**Comment by justinmayer** [comment]
Please read our docs on how to ask for help. There simply isn't enough information here to reproduce the behavior you describe.

**Comment by cadadr** [comment]
So, under `/content/pages/`, I have a file called `404.md`:

```
Title: 404 Not Found
Language: en

# 404
```

When I run the development server that's provided, this file is not exported into `/output/404.html`. But when I rename the file to be `absent.md`, and within that file, add this line to the header

```
Save_as: 404.html
```

I end up with the `/output/404.html` file.

**Comment by ingwinlu** [comment]
without renaming and without save_as you end up with a 404 page in your normal pages directory, as expected since it is a normal page like every other one you create.

so the renaming itself is not in any way related to your problem, it is just the added `save_as` line.

see http://docs.getpelican.com/en/3.6.3/tips.html#custom-404-pages

**Comment by cadadr** [comment]
@ingwinlu says:
> without renaming and without save_as you end up with a 404 page in your normal pages directory

So a `/content/pages/404.md` should have been exported to `/output/404.html`, with or without the save_as? Because in my case, it didn't, I had to have the save_as there. In my other pages within that directory, there is no `save_as` in the header, but they export to the expected file, i.e. `coffee.md -> coffee.html`, but in the case of `404.md`, I did not directly get a `404.html` out. Here is my website's source (at the now-HEAD):

https://github.com/cadadr/venii-vedo-andro/tree/264302305bd4d98f7fd157cd32d24d8226a19263

I run pelican on Python 3.4.3.

The error message I get with `404.html` without `save_as`:
```
sh-4.3$ cat content/pages/404.html 
Title: EX·NIHILO·NIHIL·FIT
Language: en

# CDIV Page not found

Nothing exists at the given URL.
sh-4.3$ make build
pelican content/
WARNING: Empty alt attribute for image delete2.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
WARNING: Empty alt attribute for image delete3.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
ERROR: Skipping pages/404.html: could not find information about 'NameError: title'
Done: Processed 15 articles, 0 drafts, 6 pages and 0 hidden pages in 5.07 seconds.
```

The error message I get with `404.html` with `save_as`:
```
sh-4.3$ cat content/pages/404.html 
Title: EX·NIHILO·NIHIL·FIT
Language: en
Save_as: 404.html

# CDIV Page not found

Nothing exists at the given URL.
sh-4.3$ make build
pelican content/
WARNING: Empty alt attribute for image delete2.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
WARNING: Empty alt attribute for image delete3.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
ERROR: Skipping pages/404.html: could not find information about 'NameError: title'
Done: Processed 15 articles, 0 drafts, 6 pages and 0 hidden pages in 5.10 seconds.
```

In both cases, there's no 404.html in output:
```
sh-4.3$ ls output/
archives.html	 colophon.html	goktug-kayaalp-feed.xml  scriptor
assets		 contact.html	index.html		 tags.html
authors.html	 emacs.html	parole			 theme
categories.html  feeds		parole-feed.xml		 turkish-coffee.html
coffee.html	 feed.xml	parole.html		 who.html
```

With `absent.md`:
```
sh-4.3$ git st
 D content/pages/absent.md
?? content/pages/404.html
sh-4.3$ git reset --hard
HEAD is now at 2643023 Remove coffee from nav.
sh-4.3$ rm content/pages/404.html 
sh-4.3$ cat content/pages/absent.md 
Title: EX·NIHILO·NIHIL·FIT
Language: en
Save_as: 404.html

# CDIV Page not found

Nothing exists at the given URL.
sh-4.3$ make build
pelican content/
WARNING: Empty alt attribute for image delete2.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
WARNING: Empty alt attribute for image delete3.jpg in /home/gk/Git/weblog/content/parole/delete-.textile
Done: Processed 15 articles, 0 drafts, 7 pages and 0 hidden pages in 5.04 seconds.
sh-4.3$ ls output | grep 404
404.html
```

**Comment by ingwinlu** [comment]
because 404.html in content means it gets parsed as a html input file, not just copied, read the documentation.

try 404.md and `ERROR: Skipping pages/404.html: could not find information about 'NameError: title'` resolves, producing the file you want. save_as overwrites the general save_as set in your config, since you already specify that all pages should be in / you don't even need a save_as to end up with 404.html in the output folder.
