### ISSUE TITLE
`{attach}` not working in style sheets of HTML pages

### ISSUE THREAD

**Issue by HiPhish** [getpelican/pelican#1818]
In HTML 5 it is valid to declare a style sheet inside the body of an HTML page. Suppose I have a page written in HTML and I define a style sheet to set the background image of a `div`:
~~~~
<div style="background-image: url({attach}my-image.jpg);">
~~~~
This will not work, Pelican will treat `{attach}` as if it was part of the file name. Declaring the style sheet in a style tag yields the same result:
~~~~
<html>
    </head>
        ...
    </head>
    <body>
        <style>
            div {background-image: url({attach}my-image.jpg);}
        </style>
        ...
    </body>
</html>
~~~~

EDIT: just to clarify, this is about content pages, not templates.

**Comment by ingwinlu** [comment]
does it work when you fix the body tag?

**Comment by avaris** [comment]
Correct, that won't work. Because [current regex](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L203) doesn't support that. PRs from people who have better regex-fu than me are welcome :).

**Comment by HiPhish** [comment]
Yet another reason to learn Python I guess.

@ingwinlu Oops, no my pages have to correct body tags. I wrote that in my browser and ever since I got used to Vim I feel like a fish out of water when I have to write anything in a regular text field.

**Comment by HiPhish** [comment]
@avaris Can you please help me make sense of the regex?

~~~~
(?P<markup><\s*[^\>]*  # match tag with all url-value attributes
(?:href|src|poster|data|cite|formaction|action)\s*=)
(?P<quote>["\'])      # require value to be quoted
(?P<path>{0}(?P<value>.*?))  # the url value
\2
~~~~
The first thing I see is a named group called `markup`, it starts with of literally `<` followed by zero or more whitespace and then zero or more not end of a word? I get the first two, the `<` is opening the tag, and there can be an arbitrary amount of whitespace between it and the name of the tag (e.g. `<  img`). What does `[^\>]*` mean? `\>` stands for the end of a word, and `[^\>]` then stands for not the end of a word? So the beginning of a word? The beginning and/or content of a word, like `img` not counting the g?

Inside the `markup` group there is an unnamed group that consists of the literal attributes that can use a URL.

Finally the `markup` group is terminated with zero or more whitespace and a `=` literal.

The next group is called `quote` and matches exactly one of the two quotation marks `"` or `'`. The exact same match is also repeated at the end of the regex. This is BTW not necessarily correct, an attribute value does not have to be quoted as long as there are no spaces in it, so `<img src=image.png >` is valid HTML.

The `path` group I don't get: `(?P<path>{0}(?P<value>.*?))`. It matches exactly zero what? And the inner group `value` matches any character (`.`) zero or more times `*` either zero or one time `?`? What does that mean? That it can match any string including an empty string like `my image.png` or nothing?

**Comment by ingwinlu** [comment]
let's see if I can shed some light on it

First, have some sample text:
```
<p>Sometimes Eclipse fails to store your EGit/<span class="caps">SVN</span> passwords in secure storage, so you have to enter them again and again. Workaround for this is to go into Git-View, open up your remotes, right click the one you want to save the password for and select <code>Configure Push</code>.
<img alt="Eclipse - Configure Git" class="img-responsive" src="{filename}/images/eclipse_configureGIT.PNG"></p>
```

Looking at the first group, your explanation was nearly correct:
`(?P<markup><\s*[^\>]*)` does search for open html tags, greedily. In our sample it would match `<p` and be done with it.  `<\s*[^\>]*` stands for the char `<`, whatever whitespace, then a group which grabs as many characters till `>` is read (the \ just escapes > and tells you it's the literal char >, not sure if that is needed because of some python fu, it is not in 'formal' regex).
https://regex101.com/r/tJ3wT1/1

Now add the second group and we end up with `(?P<markup><\s*[^\>]*(?:href|src|poster|data|cite|formaction|action)\s*=)`.
We are still greedily grabbing every character we see till we encounter a >, but we also now have the requirement of a non capturing group `?:` that needs to match to one of the listed words, and always needs to end with a `=`.
In our example we would now grab `<img alt="Eclipse - Configure Git" class="img-responsive" src=`.
https://regex101.com/r/rJ8sT0/2

The quote addition you identified correctly, so `(?P<markup><\s*[^\>]*(?:href|src|poster|data|cite|formaction|action)\s*=(?P<quote>["\']))` would still match the same as before for our markup group, and also match the quote group.
https://regex101.com/r/rJ8sT0/3

Now the final path group, where you sadly completly missed that the string gets called via `.format` and {0} gets replaced with whatever you have set in your `INTRASITE_LINK_REGEX`. The default regex looks likes this: `(?P<markup><\s*[^\>]*(?:href|src|poster|data|cite|formaction|action)\s*=)(?P<quote>["\'])(?P<path>[{|](?P<what>.*?)[|}](?P<value>.*?))\2`.

so, for our what group (this is what we are going to replace later, see the replacer function later in the code) we will look for any chars surrounded by either `{` or `|` (the | is for backwards compatibility, we don't really care about it anymore) (here it would match `filename`.
Note that the what group is 'inside' the path group as we later rewrite the path complety and what has to be removed, here we are simply matching everything (any amount of characters) till we reach the same quote that was used to open the path.
https://regex101.com/r/rJ8sT0/4

I hope that made some sense, I did not proofread.

**Comment by HiPhish** [comment]
@ingwinlu Thank you, that makes a lot of sense, in fact it makes more sense than the regex that's actually used. The regex in the code does not match the closing quote, nor does it have a `what` and `value`.

The question is what else do we need to catch? The `url` function occurs in CSS, and CSS can be embedded in two ways: inside a `style` tag and inside a `style`attribute:
~~~~
<style>
	color: white;
	background: url('{attach}myimage.png');
</style>

<div property=something style="color: white; background: url('{attach}myimage.png');">
~~~~

The former needs to match the opening `style` tag, then and arbitrary amount of CSS properties until coming across `url`. Here is a regex that matches the former:
~~~~
<style>(\s*.*\s*:\s*.*;)*(?P<property>\s.*\s*:\s*url\((['"])(?P<path>[{|](?P<what>.*?)[}|](?P<value>.*?))\3\))
~~~~
This will successfully skip over styles without URL:
https://regex101.com/r/qO5pV5/1

The style attribute is a mix of the two:
~~~~
(?P<markup><\s*[^\>]*(?:style)\s*=)(?P<quote>["\'])(\s*.*:\s*)*.*\s*:\s*url\((['"])(?P<path>[{|](?P<what>.*?)[}|](?P<value>.*?))\4\)
~~~~
https://regex101.com/r/dE8lD1/1

Did I miss something?

**Comment by ingwinlu** [comment]
@HiPhish that is the regex that is currently used

your regexes seem way to complicated and nested (did not have time to look at it yet).

The thing we need to decide is if we want to extend our replacer to add more functionality to it, more possible matches mean slower generation (though it should not be a big impact).
Then, if we want to go that road, we need to overhaul the whole replacer section and build something a bit more sophisticated than what we currently have, as there are also issues wanting to extend the replacer to also work on the summary attribute.

So just replacing / adding something to the regex is not enough imo.

**Comment by HiPhish** [comment]
@ingwinlu 
> that is the regex that is currently used

Really? This is what the file linked above says:
~~~~
(?P<markup><\s*[^\>]*  # match tag with all url-value attributes
(?:href|src|poster|data|cite|formaction|action)\s*=)
(?P<quote>["\'])      # require value to be quoted
(?P<path>[{|](?P<value>.*?))  # the url value
\2
~~~~
And your regex says
~~~~
(?P<markup><\s*[^\>]*
(?:href|src|poster|data|cite|formaction|action)\s*=)
(?P<quote>["\'])
(?P<path>[{|](?P<what>.*?)[|}](?P<value>.*?))
\2
~~~~
Notice the fourth line is different, it doesn't have the named `what` and it doesn't match the closing `}|`.

>your regexes seem way to complicated and nested (did not have time to look at it yet).

I haven't tried minimising it, I went step by step building it until it matched exactly what I wanted. Let's take the `<style>` tag: We need the following in the following order:
- The opening literal `<style>`
- Then an arbitrary amount of properties that don't have a url. Every property is preceded by optional whitespace, then the name of the property, arbitrary whitespace, a colon, arbitrary whitespace, the value of the property and a semicolon. In regex form `\s*.+\s*:\s*.+\s*;`
- There can be an arbitrary amount of these properties, so the entire thing is wrapped in `(...)*`
- After all this comes the property we are actually interested in: it starts again as `\s*.+\s*:\s*`, then the URL part comes into play. It consists out of literally `url(` and the rest is the same as for `href`, so it can be just copied. The result: `(["\'])(?P<path>[{|](?P<what>.*?)[}|](?P<value>.*?))\3` where `\3` is the quote. We can also include the closing brace literal into the match.

In total the regex is:
~~~~
<style>                       # tag
(\s*.+\s*:\s*.+\s*;)*         # non-url properties
(?P<property>\s.*\s*:\s*url\( # property : url(
(['"])
(?P<path>[{|](?P<what>.*?)[}|](?P<value>.*?))\3\))
~~~~
I don't see how that could be made any simpler. The `style` attribute is similar, the difference to `href` and others is that we can't just take the value of the attribute, because the value consists of many properties. We need to dig into the value to find the property with the URL. Here is the regex split to reflect the current one:
~~~~
(?P<markup><\s*[^\>]*
(?:style)\s*=)
(?P<quote>["\'])
(\s*.*:\s*)*.*\s*:\s*url\((['"])          # dig deeper
(?P<path>[{|](?P<what>.*?)[}|](?P<value>.*?))\4\)

~~~~
Note the *dig deeper* line.

There is still the issue of what happens when a style sheet has multiple properties with a URL. I don't know how to find matches within matches.

Would it be a better approach to find complete style sheets with regexes and then use another regex to find URL properties inside them?

>The thing we need to decide is if we want to extend our replacer to add more functionality to it, more possible matches mean slower generation (though it should not be a big impact).
Then, if we want to go that road, we need to overhaul the whole replacer section and build something a bit more sophisticated than what we currently have, as there are also issues wanting to extend the replacer to also work on the summary attribute.

I fear it might become ugly. I think it's better to treat style sheets separately from HTML tags. CSS is a different language from HTML and trying to find elements of one inside the other is a one-way trip to regex-hell. Instead I suggest what I said above, find CSS inside the HTML and then run CSS-specific regex on the matches. I don't know if that will be slower, but it will certainly be cleaner. Matching a `style` tag is very simple: `<style>(\s*.+\s*)*?<\/style>`. The `style` property is just like any other property. Finding the URL property works like before: `\s*.+\s*:\s*url\((?P<path>)(?P<quote>["'])[{|](?P<what>.+)[}|](?P<value>.+)\2\)`

**Comment by ingwinlu** [comment]
> Really?
yes really

**Comment by justinmayer** [comment]
Winlu said:
> I think it's better to treat style sheets separately from HTML tags. CSS is a different language from HTML and trying to find elements of one inside the other is a one-way trip to regex-hell.

I agree. Moreover, in-line CSS becomes a problem when implementing [Content Security Policy](https://scotthelme.co.uk/content-security-policy-an-introduction/) and thus is best avoided.
