### ISSUE TITLE
Piwik & Pelican : the generation of the files no works correctly 

### ISSUE THREAD

**Issue by Florianboux** [getpelican/pelican#1820]
*(Sorry if I make some mistakes, but I'm a young french man !)*

---

Hey !

I have a problem to configure Piwik on the Pelican. I explain me. In the configuration file (`pelicanconf.py`), I have added this snippet of "code" : 

```python
PIWIK_URL = 'florianboux.vv.si/analytics'
PIWIK_SITE_ID = 1
```
Only, on the generation of the files, a line pose some problems. Indeed, I get this : 

```javascript
        var pkBaseURL = "florianboux.vv.si/analytics";
    var _paq = _paq || [];
    _paq.push(["trackPageView"]);
    _paq.push(["enableLinkTracking"]);
    (function() {
        var u=(("https:" == document.location.protocol) ? "https" : "http")+"://"+pkBaseURL+"/";
        _paq.push(["setTrackerUrl", u+"piwik.php"]);
        _paq.push(["setSiteId", "1"]);
        var d=document, g=d.createElement("script"), s=d.getElementsByTagName("script")[0]; g.type="text/javascript";
        g.defer=true; g.async=true; g.src=u+"piwik.js"; s.parentNode.insertBefore(g,s);
    })();
```

This line : `var u=(("https:" == document.location.protocol) ? "https" : "http")+"://"+pkBaseURL+"/";`, it isn't correct. Here, I should have my Piwik server URL, no ? Like on my tracking code in Piwik interface, I think. The same line in Piwik interface, gives it : 

```javascript
  (function() {
    var u="//florianboux.vv.si/analytics/";
```

It's a real bug or I doing wrong things? For information, it's Pelican vers. 3.5.
Thanks for answer and your help !

**Comment by ingwinlu** [comment]
we don't support 3.5 anymore, get an upgrade.

that line that you think is not correct is correct, (it grabs the correct protocol http|https and then builds the url via pkBaseUrl, which was defined as `var pkBaseURL = "florianboux.vv.si/analytics";` earlier.

**Comment by Florianboux** [comment]
Thanks for your answer ! I will go see to Piwik. Maybe I make something wrong over there.
