### ISSUE TITLE
files in git repo break it all.

### ISSUE THREAD

**Issue by 22decembre** [getpelican/pelican#1821]
When running "make devserver" or "make html", some files in git management repos break the whole process :

         make devserver
         ...
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/qr/qrtools.php to   /home/stephane/pelican/output/theme/coin/qr/qrtools.php
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/qr/qrinput.php to /home/stephane/pelican/output/theme/coin/qr/qrinput.php
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/qr/qrmask.php to /home/stephane/pelican/output/theme/coin/qr/qrmask.php
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/qr/qrencode.php to /home/stephane/pelican/output/theme/coin/qr/qrencode.php
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/qr/errors.txt to /home/stephane/pelican/output/theme/coin/qr/errors.txt
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/packed-refs to /home/stephane/pelican/output/theme/coin/.git/packed-refs
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/index to /home/stephane/pelican/output/theme/coin/.git/index
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/description to /home/stephane/pelican/output/theme/coin/.git/description
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/config to /home/stephane/pelican/output/theme/coin/.git/config
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/HEAD to /home/stephane/pelican/output/theme/coin/.git/HEAD
        -> Copying /home/stephane/pelican/themes/dev-random3/static/coin/.git/objects/b4/23da540dea593b63aebd6a88233d723b086268 to /home/stephane/pelican/output/theme/coin/.git/objects/b4/23da540dea593b63aebd6a88233d723b086268
        Traceback (most recent call last):
           File "/usr/bin/pelican", line 9, in <module>
               load_entry_point('pelican==3.6.3', 'console_scripts', 'pelican')()
           File "/usr/lib/python2.7/dist-packages/pelican/__init__.py", line 481, in main
                 logger.critical('%s', e)
           File "/usr/lib/python2.7/logging/__init__.py", line 1210, in critical
                 self._log(CRITICAL, msg, args, **kwargs)
           File "/usr/lib/python2.7/dist-packages/pelican/log.py", line 139, in _log
    args = tuple(self._decode_arg(arg) for arg in args)
           File "/usr/lib/python2.7/dist-packages/pelican/log.py", line 139, in <genexpr>
    args = tuple(self._decode_arg(arg) for arg in args)
           File "/usr/lib/python2.7/dist-packages/pelican/log.py", line 152, in _decode_arg
    text = '%s: %s' % (arg.__class__.__name__, arg)
           UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 32: ordinal not in range(128)

**Comment by leotrs** [comment]
@22decembre I'm aware of the late response to this, but it would be nice to know how you dealt with it. Thanks!

**Comment by justinmayer** [comment]
@22decembre: Please feel free to comment here if you have more information about this or would like to submit a PR to address it. Thanks!
