### ISSUE TITLE
Cant find a way to use ghp-import on windows.

### ISSUE THREAD

**Issue by aloisdg** [getpelican/pelican#1822]
Hello,

I just start to decide to use Pelican as a blog engine with GitHub page.
I follow every steps of the [quickstart](http://docs.getpelican.com/en/3.6.3/quickstart.html) and everything works great.
Now, I want to push my output to GitHub. I tried to follow the tips [publishing to github](http://docs.getpelican.com/en/3.6.3/tips.html#publishing-to-github) but it failed. Powershell prints this error :

    ghp-import : The term 'ghp-import' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
    At line:1 char:1
    + ghp-import ..\output\ >> error.txt
    + ~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (ghp-import:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

ghp-import was installed with pip without any problem and is updated.

Any ideas?

cc @davisp

**Comment by ingwinlu** [comment]
we are neither powershell nor gh-pages, but we do have a note on ghp-import on windows in the docs that you linked.

**Comment by aloisdg** [comment]
So the problem is outside of your scope. I guess you can close this. I will ask somewhere else. Thank you for the answer.

**Comment by justinmayer** [comment]
Hi Alois. We'd certainly like to help, but as Winlu said, this issue isn't related to Pelican. Perhaps you could convince folks to merge the [related outstanding pull request](https://github.com/davisp/ghp-import/pull/25) that (most likely) will fix the cause of your problem?

**Comment by aloisdg** [comment]
Thank you for the link!
