### ISSUE TITLE
Add setting to use original date rather than modified date for pubDate in RSS feeds

### ISSUE THREAD

**Issue by a3nm** [getpelican/pelican#1829]
When generating an RSS feed, Pelican always uses the Modified date as the pubDate of items, if one exists. This seems to be done in https://github.com/getpelican/pelican/blob/master/pelican/writers.py#L57

The semantics of pubDate in RSS is not very detailed (see http://cyber.law.harvard.edu/rss/rss.html#ltpubdategtSubelementOfLtitemgt); however, for some RSS aggregators, changing the pubDate means that the corresponding blog entry will be displayed again to readers.

I do not find this desirable, and would like to be able to add a Modified date to my blog entries (only to be displayed in HTML in the templates), and yet use the creation date of entries as the value of pubDate in the RSS feed.

Would it be possible to add a setting to change this, so that item.date is always used in https://github.com/getpelican/pelican/blob/master/pelican/writers.py#L57 when the setting is set? Thanks!

**Comment by justinmayer** [comment]
Hi @a3nm. I believe this was addressed via #1937. If you find otherwise, please comment here and I will re-open the issue.

**Comment by a3nm** [comment]
I just tested this with Pelican 3.7.1 and indeed it seems that this has been fixed. Many thanks!
