### ISSUE TITLE
make publish failed

### ISSUE THREAD

**Issue by tjxiter** [getpelican/pelican#1830]
I add an xxxx.md in the content folder.
Then make publish to create the html，but it failed.Error info is:
tjx% make publish
pelican /Users/tjx/github_project/blog/content -o /Users/tjx/github_project/blog/output -s /Users/tjx/github_project/blog/pelicanconf.py
make: pelican: No such file or directory
make: *** [publish] Error 1

The related content in Makefile:
99 publish:
100     $(PELICAN) $(INPUTDIR) -o $(OUTPUTDIR) -s $(CONFFILE) $(PELICANOPTS)

I can post new article now. Anyone can help me ? Thank you in advance.

**Comment by ingwinlu** [comment]
you don't have pelican installed, or you don't have the virtualenv activated where you installed pelican

**Comment by tjxiter** [comment]
@ingwinlu
Thank you for reminding me. I have forgotten to activate the virtualenv.
