### ISSUE TITLE
Cannot Launch pelican command if install to a local folder

### ISSUE THREAD

**Issue by tns-yuq** [getpelican/pelican#1834]
I want to install pelican to my local directory '~/localdir/lib/python/' which I have already included in my PYTHONPATH. 
I run '$ pip install pelican -t ~/localdir/lib/python/', then the installation goes and ends up with successful information. ''Successfully installed pelican docutils unidecode jinja2 pytz blinker pygments six feedgenerator python-dateutil MarkupSafe''.

The package seems to be installed. But when I open a terminal and type 'pelican-quickstart', it complains there is no such command. 
My question is how do I fix this? I really want to install the packages in other folders but not the default one.

**Comment by ingwinlu** [comment]
scripts obviously need to be in `PATH`, not in `PYTHONPATH` as they are executed, not just modules that need to be searched

**Comment by tns-yuq** [comment]
$ pip install pelican -t ~/PelicanDir/
Downloading/unpacking pelican
  Downloading pelican-3.6.3-py2.py3-none-any.whl (130kB): 130kB downloaded
Downloading/unpacking feedgenerator>=1.6 (from pelican)
  Downloading feedgenerator-1.7.tar.gz
  Running setup.py (path:/tmp/pip_build_qiang/feedgenerator/setup.py) egg_info for package feedgenerator
    
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
Downloading/unpacking docutils (from pelican)
  Downloading docutils-0.12-py3-none-any.whl (508kB): 508kB downloaded
Downloading/unpacking pytz>=0a (from pelican)
  Downloading pytz-2015.6-py2.py3-none-any.whl (475kB): 475kB downloaded
Downloading/unpacking python-dateutil (from pelican)
  Downloading python_dateutil-2.4.2-py2.py3-none-any.whl (188kB): 188kB downloaded
Downloading/unpacking six>=1.4 (from pelican)
  Downloading six-1.9.0-py2.py3-none-any.whl
Downloading/unpacking jinja2>=2.7 (from pelican)
  Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB): 263kB downloaded
Downloading/unpacking blinker (from pelican)
  Downloading blinker-1.4.tar.gz (111kB): 111kB downloaded
  Running setup.py (path:/tmp/pip_build_qiang/blinker/setup.py) egg_info for package blinker
    
Downloading/unpacking unidecode (from pelican)
  Downloading Unidecode-0.04.18.tar.gz (206kB): 206kB downloaded
  Running setup.py (path:/tmp/pip_build_qiang/unidecode/setup.py) egg_info for package unidecode
    
Downloading/unpacking pygments (from pelican)
  Downloading Pygments-2.0.2-py3-none-any.whl (672kB): 672kB downloaded
Downloading/unpacking MarkupSafe (from jinja2>=2.7->pelican)
  Downloading MarkupSafe-0.23.tar.gz
  Running setup.py (path:/tmp/pip_build_qiang/MarkupSafe/setup.py) egg_info for package MarkupSafe
    
Installing collected packages: pelican, feedgenerator, docutils, pytz, python-dateutil, six, jinja2, blinker, unidecode, pygments, MarkupSafe
  Running setup.py install for feedgenerator
    
    warning: no files found matching '*' under directory 'tests'
    warning: no previously-included files matching '*.pyc' found under directory 'tests'
  Running setup.py install for blinker
    
  Running setup.py install for unidecode
    
    Installing unidecode script to /tmp/tmp_0vvba3x/bin
  Running setup.py install for MarkupSafe
    
    building 'markupsafe._speedups' extension
    gcc -pthread -Wno-unused-result -Werror=declaration-after-statement -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -DOPENSSL_LOAD_CONF -fPIC -I/usr/include/python3.4m -c markupsafe/_speedups.c -o build/temp.linux-x86_64-3.4/markupsafe/_speedups.o
    gcc -pthread -shared build/temp.linux-x86_64-3.4/markupsafe/_speedups.o -L/usr/lib64 -lpython3.4m -o build/lib.linux-x86_64-3.4/markupsafe/_speedups.cpython-34m.so
Successfully installed pelican feedgenerator docutils pytz python-dateutil six jinja2 blinker unidecode pygments MarkupSafe
Cleaning up...

**Comment by tns-yuq** [comment]
The above is exactly what I did and the corresponding output messages. I know the scripts need to be in PATH, but where are those scripts generated? I expect they are automatically created into my /usr/bin?
