### ISSUE TITLE
Installing a theme using --symlink doesn't work properly

### ISSUE THREAD

**Issue by realcr** [getpelican/pelican#1835]
I try to install the Nuja Pelican theme from here:  https://github.com/thndgonz/Nuja
This is what it looks like:

	$ ls
	Nuja
	$ pelican-themes -s ./Nuja --verbose
	Linking themes...
	Linking `./Nuja' to `/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/themes/Nuja' ...

Now when I list the pelican-themes I expect Nuja to show up, but it doesn't:

	$ pelican-themes -l
	notmyidea
	simple

Note that I can remove Nuja, so it does seem to be somehow installed:

	$ pelican-themes --remove Nuja
	$ pelican-themes -l
	notmyidea
	simple

If I try to remove it again, I get an error, which means that it was probably installed:

	$ pelican-themes --remove Nuja
	/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/themes/Nuja : no such file or directory

Besides not having Nuja on the list of themes, I can not use it when setting THEME='Nuja' in my pelicanconf file. This is what I get if I try to use the Nuja theme right after installing it with the -s commandline option:

	$ fab build
	[localhost] local: pelican -s pelicanconf.py
	Traceback (most recent call last):
	  File "/home/real/.virtualenvs/pelican_env/bin/pelican", line 11, in <module>
	    sys.exit(main())
	  File "/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/__init__.py", line 386, in main
	    pelican, settings = get_instance(args)
	  File "/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/__init__.py", line 372, in get_instance
	    settings = read_settings(config_file, override=get_config(args))
	  File "/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/settings.py", line 169, in read_settings
	    parsed_settings = configure_settings(local_settings)
	  File "/home/real/.virtualenvs/pelican_env/local/lib/python2.7/site-packages/pelican/settings.py", line 220, in configure_settings
	    % settings['THEME'])
	Exception: Could not find the theme Nuja

	Fatal error: local() encountered an error (return code 1) while executing 'pelican -s pelicanconf.py'

	Aborting.

Thank you for your help,
real.

**Comment by ingwinlu** [comment]
https://github.com/getpelican/pelican/pull/1384

**Comment by leotrs** [comment]
This could be closed.

**Comment by justinmayer** [comment]
Thank you for the help, Leo. Much appreciated!  (^_^)
