### ISSUE TITLE
Locale might be erronously documented

### ISSUE THREAD

**Issue by leksak** [getpelican/pelican#1836]
The following locale settings are provided on: 

```
LOCALE = ('usa', 'jpn',  # On Windows
    'en_US', 'ja_JP'     # On Unix/Linux
    )
```

I am on a Unix/Linux machine, and if I use the settings corresponding to the documentation, i.e.
```
LOCALE = ('en_US')
```
I get the following error:

```
CRITICAL: Error: unsupported locale setting
```

And using the Windows settings, i.e.
```
LOCALE = ('usa')
```
yields the following warning:
```
WARNING: LOCALE option doesn't contain a correct value
```
but has the expected output on the site, [you can check one of the posts for an example.](http://www.filipallberg.se/research.html)

The relevant file in the documentation is: [settings.rst](https://github.com/getpelican/pelican/blob/master/docs/settings.rst)

**Comment by ingwinlu** [comment]
output of `locale` and `locale -a`

**Comment by leksak** [comment]
`locale`:
```
LANG=en_US.UTF-8
LANGUAGE=en_US
LC_CTYPE=en_US.UTF-8
LC_NUMERIC=sv_SE.UTF-8
LC_TIME=sv_SE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=sv_SE.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=sv_SE.UTF-8
LC_NAME=sv_SE.UTF-8
LC_ADDRESS=sv_SE.UTF-8
LC_TELEPHONE=sv_SE.UTF-8
LC_MEASUREMENT=sv_SE.UTF-8
LC_IDENTIFICATION=sv_SE.UTF-8
LC_ALL=
```
`locale -a`:
```
C
C.UTF-8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
sv_SE.utf8
```

**Comment by avaris** [comment]
You don't have `en_US`. You have `en_US.utf-8`.

**Comment by ingwinlu** [comment]
I was actually gonna suggest that we add those commands and a listing of windows locale to the docs, but it is already there:
```
This is a list of available locales on Windows . On Unix/Linux, usually you can get a list of available locales via the locale -a command; see manpage locale(1) for more information.
```

**Comment by leksak** [comment]
Oh okay, thanks. My apologies!

**Comment by oulenz** [comment]
Could we add a sentence to the documentation like:

> Note that on Linux, the locales available may be of the form `en_US.utf8` rather than`en_US`.

I've found this really confusing, because as demonstrated above, if you check `locale`, you get shown `LANGUAGE=en_US`, so it is really easy to assume that that must be the name of the locale, with `.utf8` being just additional information.

**Comment by avaris** [comment]
Well, that's why the docs [tells you](http://docs.getpelican.com/en/stable/settings.html#LOCALE) to check `locale -a` (not `locale`).

**Comment by oulenz** [comment]
Yes sure, but this is one of those things where if you are familiar with locales, you know that `.utf8` is important, but if you've only ever encountered locales in the form `en_US`, you don't even realise that `.utf8` is part of the locale, even though that's what you see on the screen in front of you.

The documentation could be more helpful is all I am saying.
