### ISSUE TITLE
Prose like editor for Pelican 

### ISSUE THREAD

**Issue by ofenerci** [getpelican/pelican#1838]
Hello,
Everything is great with Pelican but I would like my students (high school) from their Github pages without hassling "git push " from their terminal. I wonder there is any continuing development similar to Jekyll that uses "prose.io".

**Comment by justinmayer** [comment]
Hi @ofenerci. I suggest you try http://blog.ziade.org/2016/01/21/a-pelican-web-editor/ by @tarekziade.
