### ISSUE TITLE
{filename} regex not catching multiple instances in single tag

### ISSUE THREAD

**Issue by patdavid** [getpelican/pelican#1840]
I have some image tags that are using data-swap-src as a means for defining an image swap url.

`<img class="comp" src="{filename}boost.jpg" alt="Alt Text" data-swap-src="{filename}original.jpg" />`

What I'm seeing is that the regex replacement for {filename} (and I suspect {attach}), does not trigger if there is more than one 'src' inside a single tag.

That is, `{filename}boost.jpg` does not get replaced, while `{filename}original.jpg` does.
If you swap their order, then the replacement swaps as well, indicating that only the _last_ `src=` gets replaced...

https://regex101.com/r/hQ5nL5/1

**Comment by patdavid** [comment]
I also just tested this using *different* attributes:

`<img alt="alt tag" src="{filename}boost.jpg" data="{filename}original.jpg"/>`

And the same behavior - only the last attribute gets replaced (https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L205)

**Comment by andreagrandi** [comment]
Could the problem I reported https://github.com/getpelican/pelican/issues/2175 be related to this one?

**Comment by charlesfleche** [comment]
Yes: https://github.com/getpelican/pelican/issues/2175#issuecomment-336554978

**Comment by justinmayer** [comment]
Who would be willing to work on implementing a fix for this issue?
