### ISSUE TITLE
rewrite replacer via beautifulsoup

### ISSUE THREAD

**Issue by ingwinlu** [getpelican/pelican#1841]
Proposal to replace the current regex replacer to solve issues like #1818 and #1840.
- add bs4 as a new dependency
- create a bs tree out of the generated html
- do replacements on that tree
- expose the tree to plugins (should speed up a lot of plugins out there that do html editing as they always had to create a new tree themselves)
- ???
- profit

thoughts on the matter?

**Comment by ingwinlu** [comment]
another thing I would like to address: we are currently only replacing in content, I am sure I already saw it pop up if we could extend the behaviour to also extend in custom metadata.

the way forward for me with this approach is move the actual content in so called 'Fields' which would either just be tuple like key,value stores, or a FormattedField which would updated value according to a passed siteurl.
Content itself would then just span across a collection across those fields, might drastically reduce memory footprint with relative urls enabled (because memoization).

To retain article.content like syntax for this we would need to store all those fields in a content, and implement a `__getattr__` function

**Comment by justinmayer** [comment]
@ingwinlu: Any chance you could propose an implementation for the ideas you raised in this issue?
