### ISSUE TITLE
Static markdown file

### ISSUE THREAD

**Issue by Kokxer** [getpelican/pelican#1845]
Hi, I have a static file in `content/static` named `README.md`. I want pelican directly copy it to output root folder, so I have:

```
STATIC_PATHS = [
    'static/README.md',
]
EXTRA_PATH_METADATA = {
    'static/readme.md': {'path': 'README.md'},
}
```

in my `pelicanconf.py` file. Bug when I run `pelican`, I got: 

```
ERROR: Skipping static/README.md: could not find information about 'NameError: title'
```

With `-D`, I got:

```
DEBUG: Read file static/README.md -> Article
ERROR: Skipping static/README.md: could not find information about 'NameError: title'
```

Anyone have ideas how to tell pelican do not render this file?

**Comment by justinmayer** [comment]
Try: Docs > Settings > `IGNORE_FILES`, applying it to your entire `static` folder.

**Comment by Kokxer** [comment]
Thanks for your reply, but `IGNORE_FILES` cause pelican completely ignore my `README.md`, it was not copied or rendered to `output`.

**Comment by ingwinlu** [comment]
`IGNORE_FILES` is global, if you don't want it to be treated as an article, set `ARTICLE_PATHS` to suite your needs or utilize `ARTICLE_EXCLUDES`

**Comment by justinmayer** [comment]
Thanks for the correction, Winlu.

**Comment by Kokxer** [comment]
@ingwinlu  `ARTICLE_EXCLUDES = ['static']` solved my problem, thanks you! But I'm doubting why `STATIC PATHS` isn't here to meet this requirement.

**Comment by ingwinlu** [comment]
because the ArticlesGenerator runs before the StaticGenerator

**Comment by Kokxer** [comment]
@ingwinlu  Thanks! Closing...
