### ISSUE TITLE
problems accessing pelican website

### ISSUE THREAD

**Issue by horstjens** [getpelican/pelican#1853]
during the last days i several times have run into problems when trying to reaching the official pelican website or documentation:
  * http://getpelican.com/
  * http://docs.getpelican.com/en/3.6.3/index.html

The site could not be found or reached. `DNS_PROBE_FINISHED_NXDOMAIN`

I usually works if i try again a few minutes later. Is there some problem with the webserver hosting the site? Is pelican becoming too popular?

**Comment by justinmayer** [comment]
I haven't seen this problem. If it persists, please let us know!
