### ISSUE TITLE
pagination pattern URL broken

### ISSUE THREAD

**Issue by HiPhish** [getpelican/pelican#1857]
I have the following pagination settings, inspired by the Pelican documentation:
```python
DEFAULT_PAGINATION = 10
PAGINATION_PATTERNS = (
    (1, '{base_name}', '{base_name}/index.html'),
    (2, '{base_name}/{number}', '{base_name}/{number}/index.html'),
)
```

The index pages are save correctly as `my-website.com/blog/index.html`, `my-website.com/blog/2/index.html`, `my-website.com/blog/3/index.html`, and so on. However, the URLs are broken, `{basename}` contains the full URL of the current page. I.e. on page 1 the URL to page 1 is `my-website.com/blog/blog/` `my-website.com/blog/blog/2/`, on page 2 the URL to page 1 is `my-website.com/blog/2/blog/` and to page 2 it is `my-website.com/blog/2/blog/2/`.

This is the code snipped I used to generate my pagination bar:
```
{% set range_of_pages = articles_paginator.page_range %}
...
{% for i in range_of_pages %}
<li class="{%if i == articles_page.number%}active{%endif%}">
	<a href="{{articles_paginator.page(i).url}}">{{i}}</a>
</li>
{% endfor %}
```

**EDIT:** Just to clarify, I also tried it without Multiblog, it was the same thing.

**Comment by ingwinlu** [comment]
please look at open issues before opening new ones #1615

**Comment by HiPhish** [comment]
Sorry.

**Comment by HiPhish** [comment]
It was a different issue altogether: the result of a pager's URL is relative, that's why the current path was always prepended. I had to change the link from
```html
<a href="{{articles_paginator.page(i).url}}">{{i}}</a>
```
to 
```html
``
