### ISSUE TITLE
Tag, category and authors are sorted by date.

### ISSUE THREAD

**Issue by icefoxen** [getpelican/pelican#1864]
When attempting to get a list of articles in a listing of categories, tags or authors, the articles are always sorted by date.

"https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L448 and bunch of similar sorts scattered around should be gone."

**Comment by justinmayer** [comment]
Hi @icefoxen. Is this something you would like to help address?

**Comment by icefoxen** [comment]
Potentially, though I wouldn't count on it happening any time soon...

**Comment by leotrs** [comment]
@icefoxen isn't this easily solvable by using a jinja filter to sort them by a different attribute?

**Comment by justinmayer** [comment]
If @icefoxen or someone else would like to work on this issue, please comment here and I will re-open.
