### ISSUE TITLE
pelican output directory instructions incorrect on documentation.

### ISSUE THREAD

**Issue by ericmjl** [getpelican/pelican#1867]
In https://github.com/getpelican/pelican/blob/3.6.3/docs/tips.rst, I have tried following the instructions, but they don't work.

Specifically, pelican's output for github user pages should be the master branch under the root directory of the git repository. The following line of code worked for me:

    pelican content -o . -s pelicanconf.py

as opposed to:

    pelican content -o output -s pelicanconf.py

The key change was to run pelican from repo root dir, and ask it to output the HTML pages there.

**Comment by ingwinlu** [comment]
>Specifically, pelican's output for github user pages should be the master branch under the root directory of the git repository.

Depends on the target you have, see the differences between our project pages and user pages documentation. Or the gh-pages docs which are probably better since that is what they are there for.

Also it is a terrible idea to mix content files with your output as you described.

**Comment by ericmjl** [comment]
@ingwinlu I agree, it is a bad idea to mix content and output, but having followed the instructions line by line (for the user pages), I keep getting a git error:

    error: failed to push some refs to 'git@github.com:ericmjl/ericmjl.github.io.git'
    hint: Updates were rejected because the tip of your current branch is behind
    hint: its remote counterpart. Integrate the remote changes (e.g.
    hint: 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.


I have looked at the Github Pages documentation: https://help.github.com/articles/user-organization-and-project-pages/ and there it states that:

> You must use the username.github.io naming scheme.
> Content from the master branch will be used to build and publish your GitHub Pages site.

**Comment by ericmjl** [comment]
I think there's a piece of information that may be insufficiently obvious in the documentation - that the git repo should be initialized in the output directory, pointing to the Github repository as remote, and not in the parent directory of the folder `output`. I realized this only after reading [this][1] page. Might I have missed this step somewhere in the instructions?

If I haven't missed it, is there any possibility I could submit a PR on the docs to clarify this? If so, where would you recommend that I do so?

[1]: http://mathamy.com/migrating-to-github-pages-using-pelican.html

**Comment by ingwinlu** [comment]
I am having a difficult time replying here.

First the error you are seeing and how you react to it leads me to believe you have close to no experience with git itself. The conclusions you draw from them are simply wrong. Please familiarize yourself with the system.

The documentation is correct and the commands work.

The blog post shows a different setup, which also works. I personally would not recommend doing it like that since you would not put your source data under version control.

PR's are always welcome, but please make sure you are familiar with what you are trying to improve and not just following some blog post blindly.

**Comment by ericmjl** [comment]
Hmm... I beg to differ to git experience, but I will assume you are right that I have set things up incorrectly, probably doing some things in an incorrect order.

What are specific instructions for getting setup? I have done things in the following order:

1. Set up github personal page repository (`ericmjl.github.io`).
1. Git clone repo to desktop. 
1. Inside the repo on desktop, I run pelican-quickstart, stating that:
    1. Where do you want to create your new web site? [.] 
    1. What will be the title of this web site? Eric J. Ma
    1. Who will be the author of this web site? Eric J. Ma
    1. What will be the default language of this web site? [en] en
    1. Do you want to specify a URL prefix? e.g., http://example.com   (Y/n) y
    1. What is your URL prefix? (see above example; no trailing slash) http://ericmjl.github.io
    1. Do you want to enable article pagination? (Y/n) 
    1. How many articles per page do you want? [10] 
    1. What is your time zone? [Europe/Paris] America/New_York
    1. Do you want to generate a Fabfile/Makefile to automate generation and publishing? (Y/n) 
    1. Do you want an auto-reload & simpleHTTP script to assist with theme and site development? (Y/n) 
    1. Do you want to upload your website using FTP? (y/N) 
    1. Do you want to upload your website using SSH? (y/N) 
    1. Do you want to upload your website using Dropbox? (y/N) 
    1. Do you want to upload your website using S3? (y/N) 
    1. Do you want to upload your website using Rackspace Cloud Files? (y/N) 
    1. Do you want to upload your website using GitHub Pages? (y/N) y
    1. Is this your personal page (username.github.io)? (y/N) y
1. I `cd` into `content`, and create an `about.md` file, and copied/pasted the example Markdown from [here][http://docs.getpelican.com/en/3.6.3/content.html#articles-and-pages]
1. I then run `pelican content -o output -s pelicanconf.py`
1. I then run `ghp-import output`.
1. I then run `git push git@github.com:ericmjl/ericmjl.github.io.git gh-pages:master`.

I get back the following error:

    To git@github.com:ericmjl/ericmjl.github.io.git
     ! [rejected]        gh-pages -> master (non-fast-forward)
    error: failed to push some refs to 'git@github.com:ericmjl/ericmjl.github.io.git'
    hint: Updates were rejected because the tip of your current branch is behind
    hint: its remote counterpart. Integrate the remote changes (e.g.
    hint: 'git pull ...') before pushing again.
    hint: See the 'Note about fast-forwards' in 'git push --help' for details.

Where have I gone wrong in this case?

**Comment by ingwinlu** [comment]
Why are you still ignoring the error message. If you know git you would recognize your error.

You created the git repository. You populated it with a readme and other files. Those files all lie in your master branch and are a commit. Your master points to it.

Now you are trying to push a new branch to master that does not have the same history, hence you get the no-ff warning.

**Comment by ericmjl** [comment]
Okay, so I guess you have uncovered a blind spot in my git knowledge then. Thank you for pointing this out.

**Comment by dannyroa** [comment]
FWIW, I followed the instructions on how to publish to Github as User Pages and I got the same error.

There seems to be a missing step.

I understand the error but why is `git push git@github.com:username/username.github.io.git gh-pages:master` there in the 1st place?

**Comment by zerodayz** [comment]
@dannyroa to workaround this:
1) delete the repository <your_username>.github.io from your profile.
2) create empty one <your_username>.github.io
3) do a 'git push git@github.com:<your_username>/<your_username>.github.io.git gh-pages:master'
