### ISSUE TITLE
Can pelican bind domian like http://example.com/blog?

### ISSUE THREAD

**Issue by hustlibraco** [getpelican/pelican#1869]
When I set siteurl = ‘http://example.com/blog’, It just get css, js files from that url, How can I set my blog  entry not http://example.com but http://example.com/blog?

**Comment by kernc** [comment]
You set `SITEURL` (uppercased), correct?

**Comment by hustlibraco** [comment]
I give it up. I user [hugo](https://github.com/spf13/hugo) instead.
