### ISSUE TITLE
Problem with plugin updating content

### ISSUE THREAD

**Issue by Bouni** [getpelican/pelican#1871]
Hi, maybe this is a stupid question but i don't know where else to ask.

I try to create my own plugin that simply should wrap all images in a link:

```
from os import path
from pelican import signals
from bs4 import BeautifulSoup

def content_object_init(instance):


    if instance.content is not None:

        content = instance._content
        soup = BeautifulSoup(content, "html.parser")

        wrapper = soup.new_tag('a')

        if 'img' in content:
            for img in soup('img'):

                img_path, img_filename = path.split(img['src'])

                img.wrap(soup.new_tag('a', **{"href":"test.html"}))


        instance._content = soup.decode()

def register():
    signals.content_object_init.connect(content_object_init)
```

If I print() the instance_content i see that the img is wraped in the a tag. But it does not get into the output html file.

I've no idea what's wrong here. I looked at a lot of other plugins and they seem to do it in the exact same way.

**Comment by avaris** [comment]
`.content` property is memoized, so this line

    if instance.content is not None:

causes it to be memoized before your changes. Switch it to:

    if instance._content is not None:

**Comment by Bouni** [comment]
@avaris 
You're right that was the problem. Oh man thank you so much for the hint!
