### ISSUE TITLE
Which signal to get final output data

### ISSUE THREAD

**Issue by Bouni** [getpelican/pelican#1872]
Hi,

which signal do i need to get the completed HTML of every page?
I want to append css/js files depending on the content.

**Comment by ingwinlu** [comment]
http://pelican.readthedocs.org/en/latest/plugins.html#list-of-signals
https://github.com/getpelican/pelican/blob/72ee73f886d05cea10c39bddec1ba99a3aae9504/pelican/generators.py#L366

**Comment by Bouni** [comment]
@ingwinlu 
If i see that right, that signal gives me just the inner HTML (the article itself) but not the entire HTML (including html, body, ...)

**Comment by ingwinlu** [comment]
There is currently no later signal than that. 

You would have to propose a CR and a Reason why you absolutely need that.
https://github.com/getpelican/pelican/blob/master/pelican/writers.py#L162

**Comment by Bouni** [comment]
@ingwinlu 
Ok, anyway thank you for the quick response!
