### ISSUE TITLE
Is it possible to adjust the metadata "date" field format?

### ISSUE THREAD

**Issue by sprnza** [getpelican/pelican#1877]
Hi there!
Guys, is it possible to change the date format in the metagata header to dd-mm-yyyy instead of current mm-dd-yyyy? Seems like DEFAULT_DATE_FORMAT doesn't affect to it.

**Comment by avaris** [comment]
`DATE_FORMATS` and `DEFAULT_DATE_FORMAT` control the *output* (e.g. `article.locale_date`). Pelican uses [dateutil](http://dateutil.readthedocs.org/en/latest/parser.html) to parse date fields. By default, dateutil assumes "month first" for ambiguous dates like `08/12/2015`.

I'm not sure how to properly handle this. Right now there is no way to alter this behavior. We *could* add a new setting for "day first", but I'm hesitant to grow the already long list of settings.

Can't you switch to an unambiguous date format such as ISO (`YYYY-MM-DD`)?

**Comment by justinmayer** [comment]
> Can't you switch to an unambiguous date format such as ISO (YYYY-MM-DD)?

Agreed. This is truly the best solution. If only the entire world would get the memo and adopt this as the _One and Only Standard™_!

**Comment by sprnza** [comment]
Got it. Thank you guys! Will train myself to use ISO format.
