### ISSUE TITLE
Including files in templates?

### ISSUE THREAD

**Issue by anjiro** [getpelican/pelican#1878]
I'd like to have a sidebar in my template with some custom information in it. Ideally, this custom information will be a Markdown file processed by Pelican. For example, the template might have (imagining a fictional `pelican_include()` function):

```.jinja
{% block sidebar %}
    <div class="sidebar">{{ 'about.md' | pelican_include }}`</div>
{% endblock %}
```
And `about.md` might then have something like

```.markdown
![Site logo]({attach}images/site_logo.jpg)

Welcome to my page!
```
This would allow more extensive customization within the "user" realm of Pelican (i.e., not having to modify templates) with a single template.

I welcome suggestions on how to implement this functionality as a plugin.

**Comment by smartass101** [comment]
What about making this page a hidden page and including it with an iframe?

**Comment by atodorov** [comment]
How about something like this:
https://github.com/gilsondev/pelican-clean-blog/pull/22

@anjiro - as far as I can tell you are either modifying the default Pelican template or the one you want to use to teach it about your about.md file and the new include function. IMO it is simper to just modify the template you want to use so it allows more customizations. I've done this for the one I use on my personal blog. In `pelicanconf.py` you can point it to another HTML template, which will be included. You can write anything you want in it.

**Comment by justinmayer** [comment]
Somewhat related: #1902

If you would like to help work on this feature, please post a comment on this issue with your proposal and I will re-open it.
