### ISSUE TITLE
Different locale_date rendering on different systems

### ISSUE THREAD

**Issue by kiddick** [getpelican/pelican#1879]
I've faced with strange behavior of `article.locale_date ` depending on which system it was rendering.
I am using a default `simple` theme.

```
<time class="published" datetime="{{ article.date.isoformat() }}"> {{ article.locale_date }} </time>
```

Settings in `pelicanconf.py` related to locale:

```
TIMEZONE = 'Europe/Moscow'

DEFAULT_LANG = u'en'
```
No other specific options for locale.
So on fedora it works as expected:
```
Fri 18 December 2015
```

But if I am trying to render it on Windows and Ubutu (virtual box on that windows machine) it gives me 
```
Пт 18 Декабрь 2015 
```

Any ideas? How it is possible to debug?

**Comment by ingwinlu** [comment]
your locale is different, we have a section on it in the docs

**Comment by kiddick** [comment]
@ingwinlu could you post a link?
Can't find it at all.
Thanks in advance.

**Comment by ingwinlu** [comment]
http://pelican.readthedocs.org/en/latest/settings.html?highlight=locale#date-format-and-locale
