### ISSUE TITLE
Why does pelican install themes under /usr/ instead of project folder?

### ISSUE THREAD

**Issue by felipe-alarcon** [getpelican/pelican#1884]
It seems like a bad idea because many people develop on different machines so you always have to go and chase the theme you're using and install it wherever you develop...

under linux, themes are installed here by default:

/usr/local/lib/python2.7/dist-packages/pelican/themes/

**Comment by justinmayer** [comment]
There's nothing preventing you from putting your theme wherever you want. Feel free to put it in `~/projects/yoursite/yourtheme` and then add the following to your settings file:

    THEME = "yourtheme"

In the future, please try us on IRC before submitting an issue on GitHub, as noted in our [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the docs. Thanks!

**Comment by felipe-alarcon** [comment]
Alright, thanks for that. I'll go for IRC next time.
