### ISSUE TITLE
Custom metadata gives char array

### ISSUE THREAD

**Issue by AngelMunoz** [getpelican/pelican#1887]
Hello, I've been trying to figure this out, I want to make a resume template and I want to add skills as file metadata so it's easier to just write the rst or md file but when I try to acces each metadata variable it is built like it was a char array

here's the code

    https://gist.github.com/AngelMunoz/efd21bce20e03600e977

lines 20, 40, 57 in **resume.html**

and this is what it's actually built
![resume](https://cloud.githubusercontent.com/assets/8684875/12111197/c49d77d6-b350-11e5-8b5a-32de1674e273.PNG)

So I don't know if i'm doing something wrong, or something is bad
I tried to look at the docs (amazing work with them by the way) but found nothing related to that

**Comment by ingwinlu** [comment]
skill is a string (which is an iterable, not an array), you are iterating
over it instead just printing it out.
Only specific metadata is parsed the way you are expecting it to be, you
can look at the code here [0].

[0]:
https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L34

**Comment by AngelMunoz** [comment]
thanks for the quick response
I was thinking about wether it was a string too forgot to mention it. So I could do some crazy stuff to make it work or just hardcode values?

**Comment by ingwinlu** [comment]
you can use a jinja filter. if you need to add your own you can use the `JINJA_FILTER` setting.
another possibility is creating a plugin that processes your `skill` attribute.
