### ISSUE TITLE
{filename} replacement is still broken in v3.6.3

### ISSUE THREAD

**Issue by urschrei** [getpelican/pelican#1890]
I've just upgraded to 3.6.3

My pelicanconf.py:

    …
    PATH = 'content'
    STATIC_PATHS = [
        'images'
        'media',
        'extra'
    ]
    …

the contents of my `content/images` folder:

    inset_demo.png

The line in my demo.md file, referencing this file:

    ![Bikeshare]({filename}/images/inset_demo.png "Bicycle Journey Times from Westminster Bridge")

The output of running `make html`

    WARNING: Unable to find `/images/inset_demo.png`, skipping url replacement.

The file definitely exists (I can reproduce this error with any file). This error occurs using a clean virtualenv, using Python 2.7.10 on OSX 10.11.2

**Comment by avaris** [comment]
Try without any plugins.

**Comment by urschrei** [comment]
Have just disabled all plugins. `make clean` followed by `make html` produces the same warning.

**Comment by ingwinlu** [comment]
can you post the full output of your pelican run with the -D flag set?

**Comment by urschrei** [comment]
Sure. Here you go: https://gist.github.com/urschrei/765b69c4c9c2b0ef5d06

**Comment by ingwinlu** [comment]
As you are able to see for yourself, your images folder is not copied at all (hence no replacement for the urls can be made). Can you also post your full config and directory structure.

**Comment by urschrei** [comment]
full config (personal metadata has been replaced):

    #!/usr/bin/env python
    # -*- coding: utf-8 -*- #
    from __future__ import unicode_literals

    AUTHOR = u'foo'
    SITENAME = u'foo'
    SITEURL = u'foo'
    TIMEZONE = u'foo'
    DEFAULT_LANG = u'foo'
    # Feed generation is usually not desired when developing
    FEED_ALL_ATOM = None
    CATEGORY_FEED_ATOM = None
    TRANSLATION_FEED_ATOM = None

    PATH = 'content'
    STATIC_PATHS = [
        'images'
        'media',
        'extra'
    ]

    # Social widget
    SOCIAL = (('twitter', 'https://twitter.com/foo'),
              ('github', 'https://github.com/foo'),
              ('linkedin', 'https://uk.linkedin.com/in/foo'))
    TYPOGRIFY = True
    DEFAULT_PAGINATION = True
    PLUGIN_PATHS = ['/users/sth/dev/pelican-plugins/']
    # Setting for the better_figures_and_images plugin
    FIGURE_NUMBERS = True
    RESPONSIVE_IMAGES = True
    MARKUP = ('md', 'ipynb')
    THEME = "/users/sth/dev/pelican-themes/pelican-bootstrap3"

    # Uncomment following line if you want document-relative URLs when developing
    RELATIVE_URLS = True
    GOOGLE_ANALYTICS = "foo"
    GITHUB_URL = "https://github.com/foo"
    TWITTER_USERNAME = "foo"
    TWITTER_INTEGRATION_ENABLED = True
    ADDTHIS_PROFILE = "foo"



Directory output:

Base dir:

    $ ls
    Makefile           content/           fabfile.py         output/            pelicanconf.py     publishconf.py     srv.pid
    cache/             develop_server.sh* fabfile.pyc        pelican.pid        pelicanconf.pyc    publishconf.pyc    venv/


`content` dir:

    bikeshare.md    extra/          hackathons.md   hello_world.md  images/         media/          pages/          pygis.md        rust_lonlat.md

**Comment by avaris** [comment]
```STATIC_PATHS = [
    'images'
    'media',
    'extra'
]```

note that there is no comma after `'images'`, so python concatenates the two strings and your STATIC_PATHS is effectively `['imagesmedia', 'extra']`

**Comment by urschrei** [comment]
Oh ffs. Sorry everyone.
