### ISSUE TITLE
Pelican changes encoding based on tld?

### ISSUE THREAD

**Issue by raymestalez** [getpelican/pelican#1892]
I have a weird problem.
I am using foundation icons font on my website, and when I set a variable SITEURL, all icons turn into weird symbols, when the variable is empty - everything works fine.

My website is on .io domain, so I'm guessing it could be because something sets a different encoding based on this domain?

I have tried setting locale to en_US, but that doesn't solve the problem.

Can you help me out?

**Comment by Scheirle** [comment]
If web icon fonts turn into weird symbols this normally means that the font couldn't be loaded. (And has nothing to do with encoding).

Make sure that the fonts are in the correct folder. As far as i can tell foundation icons font requires that all the fonts are in the same folder as the css file.

But it is strange that it seems to be affected by `SITEURL` (which it should not (I assume it's a theme error), but with so little information given there is nothing I can do.

**Comment by raymestalez** [comment]
Could you please look at the config [over here](https://github.com/raymestalez/orangemind)?  It really is a bizzare error..... These are not just the ususal missing font symbols, these are some ierogliphs. Maybe it's haunted)

**Comment by Scheirle** [comment]
I can't reproduce your error. The RSS icon is visible (bottom right).

What I did: 
```
git clone https://github.com/raymestalez/orangemind.git
rm -R __pycache__
rm -R cache
rm -R output
mkdir virtualenv
virtualenv -p python3 virtualenv
source virtualenv/bin/activate
pip install pelican
pip install markdown
# made the changes below to pelicanconf.py
pelican -o output -D
cd output
python3 -m http.server 8081
# visited localhost:8081 in my browser
```

Changes I made (nothing relevant):
```
--- a/pelicanconf.py
+++ b/pelicanconf.py
@@ -4,7 +4,8 @@ from __future__ import unicode_literals
 
 AUTHOR = 'Ray Alez'
 SITENAME = 'orangemind'
-SITEURL = '' #'http://orangemind.io'
+SITEURL = 'http://orangemind.io'
+RELATIVE_URLS = True
 
 LOCALE = ('en_US.UTF-8')
 
@@ -79,7 +80,7 @@ AUTHOR_SAVE_AS = ''
 
 DIRECT_TEMPLATES = ('index', 'tags', 'categories', 'archives', 'store','about',) #'about',
 
-THEME = "/home/ray/orangemind/themes/orangemind"
+THEME = "themes/orangemind"
 
 # Plugins
 PLUGIN_PATHS = ['/home/ray/orangemind/pelican-plugins']

```
Note that I had to set `RELATIVE_URLS`. Of cause I only had to set it because if `SITEURL` is specified the theme links to that url, e.g. `http://orangemind.io/theme/css/foundation-icons/foundation-icons.css` (and this currently returns a 404, because the site is not yet uploaded)

**Comment by justinmayer** [comment]
Sorry to hear about your troubles, Ray. Please feel free to re-open this issue with any additional detail you can provide.
