### ISSUE TITLE
how to serve on different port?

### ISSUE THREAD

**Issue by geohuz** [getpelican/pelican#1903]
Is it should be simple as make devserver port=3456? How ever it just doesn't work!

**Comment by muellermartin** [comment]
Looking at the [Makefile on line 88](https://github.com/getpelican/pelican/blob/24b7bca37d6350204b112670008b69be3f510895/pelican/tools/templates/Makefile.in#L88) there is a variable called PORT which allows to specify a custim port for the devserver. For example `PORT=1234 make devserver` starts the devserver on port `1234`.

Note: You must enable Makefile generation when creating the project (as far as I know) via `pelican-quickstart` when asked.

**Comment by geohuz** [comment]
oh yeah, thanks!
