### ISSUE TITLE
{filename} includes not working properly b/w articles and pages

### ISSUE THREAD

**Issue by atodorov** [getpelican/pelican#1905]
On a blog where I have in my markdown file
```
[subscribe]({filename}pages/subscribe.html)
```

and the directory layout is:
```
content/
      -- mypost.markdown
      -- pages/
             -- subscribe.html
```

and the page is 
```
<html>
    <head>
        <title>Activate Your Subscription</title>
        <meta name="save_as" content="subscribe.html" />
    </head>
    <body>
</body>
</html>
```

The generated HTML link points to `/activate-your-subscription.html` instead of `/subscribe.html`. I intend to work on this but any ideas and/or pointers in the right direction are welcome.

**Comment by ingwinlu** [comment]
working as intended, if you override **save_as** you have to provide an appropriate **url** too.

that is the behaviour everywhere else as well. if you want to change it you would have to work it for everything, not just for the replacer.

**Comment by atodorov** [comment]
Thanks, closing.

**Comment by ingwinlu** [comment]
you can keep it open, but change the title and description.

IMO it should be possible to figure out the resulting new url by prepending SITEURL (as well as making sure the new url is valid and does not need to be slugged).
