### ISSUE TITLE
"LOCALE option doesn't contain a correct value" error not guaranteed correct. 

### ISSUE THREAD

**Issue by Dokument** [getpelican/pelican#1906]
I received this error from settings.py when I had locale issues with the os but nothing wrong with the configuration (pelicanconf.py).

Suggested fix: Don't pass on locale exceptions as shown on line 275 of settings.py. At least print those errors in addition to the else print statement to help the user determine how to best fix the problem.

**Comment by ingwinlu** [comment]
I agree that the wording is not correct here, the exception output is not really useful though. What do you think about rewording the log message?
> "LOCALE could not be set; check the setting and available LOCALEs on your system."

We also have a [section about LOCALE in the pelican documentation](http://docs.getpelican.com/en/3.6.3/settings.html#date-format-and-locale) available. Though I am hesitant to include that in the log message.

Would agree to merge a PR that solves the issue if you want to go for it.

**Comment by justinmayer** [comment]
Hi Adam. Is this something you would like to help address?

**Comment by fuzzy76** [comment]
I got bit by this as well. Part of the problem is that pelican-quickstart does not really tell you what it really wants when it asks for "site language".

**Comment by justinmayer** [comment]
@fuzzy76: Actually, `pelican-quickstart` does indeed indicate what it's looking for by providing the default value at the end of the question:

    > What will be the default language of this web site? [en]

**Comment by justinmayer** [comment]
Fixed this issue by clarifying the error message. Thanks to @ingwinlu for the suggested text.
