### ISSUE TITLE
page.title missing at rendered page

### ISSUE THREAD

**Issue by kiddick** [getpelican/pelican#1910]
I am trying to figure out what happens with `page.title` in output after rendering.
For some reason it's missing.

I have [page.html](https://github.com/kiddick/kiddick.github.io-src/blob/master/themes/simple/templates/page.html#L2) template with such settings:

```
{% block title %}{{ page.title }}{%endblock%}
```

and [`base.html`](https://github.com/kiddick/kiddick.github.io-src/blob/master/themes/simple/templates/base.html#L5l)

there is actually `title` located

```
<title>{% block title %}{{ SITENAME }}{% endblock title %}</title>
```

But as you can see it missing at rendered page:

[rendered `title`](https://github.com/kiddick/kiddick.github.io/blob/master/making-a-flat-list-out-of-list-of-lists.html#L4)

```
<title>xi blog</title>
```

Any ideas?
Is there any way to debug this step by step?

**Comment by ingwinlu** [comment]
because it is an article, [article.html](https://github.com/kiddick/kiddick.github.io-src/blob/master/themes/simple/templates/article.html) is used

**Comment by kiddick** [comment]
Ah, I see.
Thank you a lot.
