### ISSUE TITLE
Disqus does not work from HTTPs sites

### ISSUE THREAD

**Issue by adamatan** [getpelican/pelican#1911]
# Abstract 

Disqus links use the http protocol, which does not work from within HTTPS sites.

# Configuration

I've been using the `DISQUS_SITENAME` to add Disqus to my blog:

```
THEME = 'gum'
DISQUS_SITENAME = "XXX"
```

In the background, the gum theme [checks if `DISQUS_SITENAME` is defined](https://github.com/getpelican/pelican-themes/blob/master/gum/templates/article.html#L32), and if so - replaces it with the proper disqus code block.

# The problem

The configuration worked locally, but from my blog's URL - https://adammatan.com - it failed to load. A quick look at the console showed that the disqus url prefix was http, and browsers will not load http resources from https pages.

# Proposed solutions

* **Define a `DISQUS_HTTPS` configuration parameter**: We can define a new boolean parameter in `pelicanconf.py` a-la `DISQUS_HTTPS` or `DISQUS_SECURE`, and choose https if the parameter is defined and set to True.
* **Use the `SITEURL` prefix**: If the `SITEURL` begins with `https://`, we can automatically use an https prefix for disqus.
** **Always use https**, even from http pages. We need to know what's the disqus policy on this one.

**I want to hear your opinion on this, and when we reach a conclusion I'll submit a pull request.**

**Comment by avaris** [comment]
If this is about `gum` theme, why is this here instead of `pelican-themes`? Am I missing something?

**Comment by adamatan** [comment]
@avaris I thought this is a better place than `pelican-themes`, because it involves global configuration variables - `DISQUS_SITENAME` and the proposed `DISQUS_HTTPS`. 

These global variables exist outside the themes, and affect the general design of pelican.

**Comment by justinmayer** [comment]
Hi Adam. @avaris is correct: this is an issue with the Gum theme and not Pelican itself. [Gum is hard-coding the http protocol](https://github.com/getpelican/pelican-themes/blob/master/gum/templates/article.html#L40), which is a bad idea and should be changed to `https://`.

There is no need for a DISQUS_HTTPS configuration parameter, since I can think of no instances in which it makes sense to use anything other than HTTPS. Unless I'm missing something, even on sites that are served via HTTP, Disqus references can and should always be via HTTPS.

**Comment by adamatan** [comment]
Great, will submit a pull request there.
Is there a way to move the thread from here to pelican-themes?

**Comment by justinmayer** [comment]
Not that I'm aware of. And I'm not sure that's necessary anyway. When you create your pull request from pelican-themes, include something like the following in your commit description:

    Change Disqus link from http to https
    
    Refs https://github.com/getpelican/pelican/issues/1911

**Comment by adamatan** [comment]
Sure, thanks

**Comment by adamatan** [comment]
https://github.com/getpelican/pelican-themes/pull/372

Moderators, can you please close the thread? I've made a pull requests on the themes repo.
