### ISSUE TITLE
Cloud Front caches not invalidated when using s3_upload

### ISSUE THREAD

**Issue by mlissner** [getpelican/pelican#1912]
Amazon recently made [SSL certificates free for custom domains][1] and so having pelican content hosted on Amazon is really pretty great. Pelican has the s3_upload command that makes this pretty easy, but if you want to use Amazon's free SSL feature, you have to use Amazon's CDN, CloudFront.

That makes things complicated because once you're using a CDN, it's not just a matter of pushing content to an s3 bucket. No, if you want it to be live, you need to either wait a day for the cache to timeout or you need to invalidate your CloudFront caches manually by logging into the console and invalidating them.

I have a feeling setting up CloudFront with S3 will be pretty popular due to the free SSL certificates. Would Pelican be interested in code that helped with the invalidation step?

[1]: https://aws.amazon.com/blogs/aws/new-aws-certificate-manager-deploy-ssltls-based-apps-on-aws/

**Comment by mlissner** [comment]
I looked into this a bit, and adding the amazon command line tool to the make file could do it with a command like:

    aws cloudfront create-invalidation --distribution-id <your-distro-id> --paths '/*'

So, I think we could add questions about CloudFront to the quick start and gather the needed info there, if we wanted.

**Comment by leotrs** [comment]
@mlissner makes sense to me. PRs are welcome n_n

**Comment by mlissner** [comment]
I've been using this in my makefile for a little while now, and it works wonderfully. But to merge it into mainline, I see a couple issues:

1. The quick start script needs to have a new question about CloudFront, and needs to do all the set up around that (which is somewhat complicated).

1. The command above clears the CloudFront cache for all pages, which is totally subpar. The right way to do it is to only clear the cache for the changed pages. This seems doable since the upload script only uploads changed files.

Anyway, I don't know anything about make files, and don't know much about AWS, so I'm not the right person for this, but I'm happy to file bugs, review approaches, etc.

**Comment by justinmayer** [comment]
If someone would like to work on better CloudFront support, please comment here and I will re-open the issue.

**Comment by andygoldschmidt** [comment]
`s3cmd` has an option `--cf-invalidate`. I added that in the Makefile and all updated files got invalidated in Cloudfront after publishing it. 

I didn't have the chance to test this with other setups, i.e. S3 uploads with no attached Cloudfront distribution, so I just leave that here as a comment.
