### ISSUE TITLE
Remove Coveralls integration

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#1919]
Recent pull requests are showing up with big red X's because of (what I perceive as) non-sensical Coveralls reports like this:

> Coverage decreased (-0.0%) to 68.819%

This has long been a thorn in our side. Ergo, I propose that we remove Coveralls integration.

@almet: Did you set this up? If so, could you remove it?

**Comment by avaris** [comment]
:+1:

**Comment by honzajavorek** [comment]
This can be fixed just by changing the settings, I believe:

<img width="387" alt="screen shot 2016-02-28 at 12 47 08" src="https://cloud.githubusercontent.com/assets/283441/13378993/6ea1da18-de19-11e5-9615-800b04724852.png">

**Comment by almet** [comment]
Integration removed.

**Comment by justinmayer** [comment]
Thanks, Alexis!
