### ISSUE TITLE
MD to HTML format

### ISSUE THREAD

**Issue by KrisLeeCoder** [getpelican/pelican#1925]
Hi, I'm wring transferring markdown file to html. And the contend is:
```
Title: markdown format test
Date: 2016-2-1 10:40
Category: Python
Tags: python, environment
Slug: Test
Auther: Kris Lee

1. title1
2. title2  

    ```shell 
    ls -alh
    cat UU
    head log | grep ESW
    ```

3. title3
```

In the preview in the markdown editor of Pycharm, the code area will be 3 lines, like:
```shell 
ls -alh
cat UU
head log | grep ESW
```
While, in the html file transferred by pelican, all the code will be set in the same line. And the html code will be:
```

  <div>
    <ol>
<li>title1</li>
<li>
<p>title2  </p>
<p><code>shell 
ls -alh
cat UU
head log | grep ESW</code></p>
</li>
<li>
<p>title3</p>
</li>
</ol>
  </div>
```

Actually, I just want the code to be in different lines.
**So, is this a bug of pelican. If not, pls show me how can i fix the md file. THQ**

**Comment by justinmayer** [comment]
Pelican uses the Python Markdown library to render HTML from Markdown content. That library only supports fenced code blocks at the document root level -- not nested inside lists, as you are doing here.

See the red-highlighted warning in the corresponding [fenced code block docs](https://pythonhosted.org/Markdown/extensions/fenced_code_blocks.html).

**Comment by KrisLeeCoder** [comment]
All right. THQ.
