### ISSUE TITLE
Hidden pages handled incorrectly

### ISSUE THREAD

**Issue by stefanv** [getpelican/pelican#1929]
In the latest version of Pelican, setting ``status: hidden`` results in

```
ERROR: Unknown status 'hidden' for file ./pagename.md, skipping it.
```

The problem is that `generate_context` in `generators.py` does not take this case into account.

**Comment by ingwinlu** [comment]
Or, more likely: you have misconfigured and pelican is trying to parse `pagename.md` as an article.

**Comment by stefanv** [comment]
Aha, so you cannot have hidden articles. That makes sense.

I guess we could still warn the user that that's what's happening?

**Comment by ingwinlu** [comment]
https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L547
https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L643

**Comment by stefanv** [comment]
@ingwinlu The lines above seem to be for the message I received originally, but it does not help the user to figure out what's wrong.  How about changing the message to say something along the lines of: "only pages can have status 'hidden'" for that specific case?
