### ISSUE TITLE
Unsightliness with typogrify and titles that start with quote

### ISSUE THREAD

**Issue by scarpent** [getpelican/pelican#1930]
With an .rst title like so:

    "double" 'single' "another double"
    ##################################

The first quote is handled  with a span that is rendered in the chrome tab title:

    <title><span class="dquo">&#8220;</span>double&#8221; &#8216;single&#8217; &#8220;another&nbsp;double&#8221;

Same issue when starting any line:

    <p><span class="dquo">&#8220;</span>blah blah&nbsp;blah&#8221;</p>

But it's really only the title that presents a problem since the browser shows it.

Maybe not a Pelican issue but thought I'd raise it.

**Comment by avaris** [comment]
This is likely a theme issue. It should really [strip tags](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/article.html#L2) from the title.

**Comment by leoxi** [comment]
ok

**Comment by scarpent** [comment]
Excellent! That takes care of it. Thank you so much!

**Comment by justinmayer** [comment]
Thanks for the help, @avaris!
