### ISSUE TITLE
markdown/html variants error

### ISSUE THREAD

**Issue by golfecholima** [getpelican/pelican#1932]
When I save a .md file Pelican outputs the .html file in the directory that the .md file was authored in.

Spits out this message:

```
-> Modified: content. re-generating...
WARNING: Meta tag in file /Users/george/Documents/repos/virtualenvs/pelican/content/article1.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
WARNING: There are 2 variants of "tk-the-most-amazing-title-cased-title" with lang en
WARNING: 	/Users/george/Documents/repos/virtualenvs/pelican/content/article1.html
WARNING: 	/Users/george/Documents/repos/virtualenvs/pelican/content/article1.md
WARNING: Caught exception "RuntimeError: File /Users/george/Documents/repos/virtualenvs/pelican/output/tk-the-most-amazing-title-cased-title.html is to be overwritten". Reloading.
```
At first I thought it was a slug issue but even after going through and making sure they were all unique, the behavior persisted.

I wind up having to delete the .html file that appears in /content, keyboard interrupt Pelican and restart at which point everything outputs normally and I see my changes reflected.

**Comment by ingwinlu** [comment]
setup your project to not put output into your content folder

**Comment by golfecholima** [comment]
Where might I have done that? I went through a fresh install and never found a place where I would've accidentally set outputs to flow into content folder. Also can't seem to find a place to change that now, where is that setting?

**Comment by golfecholima** [comment]
So I think I figured out the problem. I had set up Pelican to operate directly in my virtualenv directory rather than creating another subdir specifically for the project ... not sure why that fixes, but seems to do the trick.
