### ISSUE TITLE
Atom feed could/should use <published> date

### ISSUE THREAD

**Issue by scarpent** [getpelican/pelican#1933]
I've noticed that my atom feed will use `:date:` in the `<updated>` field in feed.xml, and will override that with `:modified:` if modified is specified. This results in an unwanted email re-send when using MailChimp's RSS --> Email feature. Going by this page, I think they would use `<published>` first if it existed:

http://kb.mailchimp.com/campaigns/rss-in-campaigns/troubleshooting-rss-in-campaigns

And I think in general it would be nice to call out both `<published>` to mark the original date, and `<updated>` for modifications. (And it aligns better with what I expect with `:date:` and `:modified:` meta in my .rst files.)

Not a big problem -- I'll just have to refrain from using :modified: to avoid this behavior, but I figured it wouldn't hurt to ask. :-)

**Comment by ingwinlu** [comment]
feedgenerator would need to be updated to the current django implementation, which would offer [updateddate](https://github.com/django/django/blob/master/django/utils/feedgenerator.py#L119)

After that it is trivial to adapt pelican's code to make use of it.

**Comment by karlcow** [comment]
The [current code](https://github.com/getpelican/pelican/blob/72ee73f886d05cea10c39bddec1ba99a3aae9504/pelican/writers.py#L57-L59) for individual item is:

```python
pubdate=set_date_tzinfo(
    item.modified if hasattr(item, 'modified') else item.date,
    self.settings.get('TIMEZONE', None)))
```
Current [feedgenerator.py](https://github.com/django/django/blob/60586dd7379b295b72d8af4e03423c286913b5e8/django/utils/feedgenerator.py) in Django.

The root element has 
https://github.com/django/django/blob/60586dd7379b295b72d8af4e03423c286913b5e8/django/utils/feedgenerator.py#L378

```python
 handler.addQuickElement("updated", rfc3339_date(self.latest_post_date()))
```
And for individual items
https://github.com/django/django/blob/60586dd7379b295b72d8af4e03423c286913b5e8/django/utils/feedgenerator.py#L404

```python
        if item['pubdate'] is not None:
            handler.addQuickElement('published', rfc3339_date(item['pubdate']))

        if item['updateddate'] is not None:
            handler.addQuickElement('updated', rfc3339_date(item['updateddate']))
```

The Atom specification for the [root feed element](http://tools.ietf.org/html/rfc4287#section-4.1.1) has 

```
   atomFeed =
      element atom:feed {
         atomCommonAttributes,
         (atomAuthor*
          & atomCategory*
          & atomContributor*
          & atomGenerator?
          & atomIcon?
          & atomId
          & atomLink*
          & atomLogo?
          & atomRights?
          & atomSubtitle?
          & atomTitle
          & atomUpdated
          & extensionElement*),
         atomEntry*
      }
```

There is no `published` element for the `feed` root element

So feedgenerator has already the capability to publish both `updated` and `published` for `item`.

So I guess we just need a patch for Pelican.

**Comment by karlcow** [comment]
OK proposed something because it would be useful for one of my blogs.

**Comment by karlcow** [comment]
Context for this discussion.
https://github.com/getpelican/pelican/issues/1938

**Comment by karlcow** [comment]
Also the current discussion on the PR for this issue.
https://github.com/getpelican/pelican/pull/1937

**Comment by scarpent** [comment]
Thanks, guys!
