### ISSUE TITLE
/r/Pelican subreddit is available

### ISSUE THREAD

**Issue by livibetter** [getpelican/pelican#1934]
## Current status (2016-03-31T02:22:51Z)

I've invited @justinmayer ([/u/SnowLprd][SnowLprd]), basically, we are proceeding the first option.

I'd prefer this to be kept open for a little while before I am certain that the subreddit is working.

[SnowLprd]: https://www.reddit.com/user/SnowLprd

----

## Opening post

I've managed to get the control of [/r/Pelican][rpelican]. I [requested][req] it and an admin unbanned it, then asking the still-active mods if they can let me have the sub, and 3 of 4 agreed in short time, the last one was removed by a senior mod.

Basically, I obtained it without any issues and I am currently the only mod. The subreddit is temporarily put under *restricted* mode during this period.

[rpelican]: https://www.reddit.com/r/Pelican/
[req]: https://www.reddit.com/r/redditrequest/comments/4b1qz7/requesting_rpelican_4month_banned_subreddit_will/

Originally, I was thinking about running it myself, but I now believe it's better to let [the development team][team] manages it as an official channel. So, here is how I would prefer, in order:

[team]: https://github.com/orgs/getpelican/people

### If the team wants /r/Pelican

And I hope they do, then I will mod at least one member from the team, who has expressed an interest. I will wait for a while before I am sure it stabilizes before I remove myself from the mods, at least until I see some activities from the mods. I don't intend to stay unless the team wants me to.

I will wait for a week if I don't get a response from the team before I proceed to the second option.

### If the team doesn't want it, I will run with other users

If the first option doesn't work out, I will recruit Pelican users who wants to help me to build a community for Pelican on the subreddit.

**Comment by justinmayer** [comment]
Hi Yu-Jie. Many thanks for requesting the subreddit and for reaching out to the dev team about it. Option 1 sounds great. I just sent you a message via email. I look forward to hearing from you regarding next steps!

**Comment by livibetter** [comment]
@justinmayer have you received my email reply?

**Comment by justinmayer** [comment]
Yes, and I replied in turn. Sorry for the delay — it's been a busy week.

**Comment by livibetter** [comment]
@justinmayer do you have any updates on the sub progress?

**Comment by livibetter** [comment]
I'm closing this with a final notice.

Before June 1, if you want to be a mod of r/pelican to help the sub, send me a message (to u/livibetter) on reddit, I will add you after checking you out.

On the day, I will remove myself from the modlist. I decide to do this because I haven't seen anything being done to the sub and as I said before I don't want to mod the sub. This is the best I am willing to do, and hopefully someone would step in.
