### ISSUE TITLE
feedgenerator

### ISSUE THREAD

**Issue by dmdm** [getpelican/pelican#1938]
Hello all,
long time no see, how are you?

I am following up on a request by @karlcow to update feedgenerator to version 1.9, which led me here. I am sorry, but I do not have time to maintain feedgenerator, and which I have not done for quite some time, as your repo being 22 commits ahead shows :)

Cheese Shop however still lists my parrot (read: package). Would you like to take that over? It would be nice if PyPi gets a current and maintained package. Trivia: and it would close the circle, as way back I took the package over from Alexis.

If you agree, I'll put a closed sign into my repo with a link to here.

Best wishes, Dirk

**Comment by justinmayer** [comment]
Hello, Dirk! Thank you for the friendly message. Your idea sounds sensible. I took the liberty of publishing a new release on PyPI, and I just merged a new pull request as well.

I'll also contact GitHub and ask them to extract the `getpelican/feedgenerator` repository into its own fork network.

Appreciate you reaching out and putting a notice on your repo. Much obliged!

**Comment by justinmayer** [comment]
Thanks to a very quick response by the fine folks at GitHub, the `getpelican/feedgenerator` repository has been extracted into its own fork network. Thanks again for all the great contributions, Dirk!
