### ISSUE TITLE
How can I reverse the list of articles?

### ISSUE THREAD

**Issue by raymestalez** [getpelican/pelican#1940]
In one of my pages, I want to list all the articles with

	{% for article in articles %}

but I want them to be displayed in order, starting from oldest. While I want index.html to keep displaying most recent articles(so I can't just change ARTICLE_ORDER_BY setting).

Can I somehow reverse the list of articles in the template? What else can I do?

**Comment by avaris** [comment]
[`reverse`](http://jinja.pocoo.org/docs/dev/templates/#reverse)

```jinja
{% for article in articles|reverse %}

**Comment by raymestalez** [comment]
Awesome! Thank you so much!
