### ISSUE TITLE
dates_* variables? Where are they come from??

### ISSUE THREAD

**Issue by isbm** [getpelican/pelican#1943]
Hi,
I am a bit confused. For example, [documentation says](http://docs.getpelican.com/en/3.6.3/themes.html#index-html) there are variable, called `dates_page`.

So when I do something like:
```jinja
{% for article in dates_page %}
...
```
Then I have exactly nothing. So the any `dates_*` or `articles_*` variables are actually empty, although my config says `DEFAULT_PAGINATION = 3`, so I suppose `dates_page` should contain 3 articles or? :confused: Then, if I grep of the the entire sources of the Pelican for something like `dates_page`, I don't even see this is in the code.

OK, what I am missing and where they are all coming from? I would like to have X articles per a page and have 1/2/3/4... paginator below.

How to do that?

**Comment by isbm** [comment]
OK, in order to get the pagination working elsewhere than just **index**, this is the recipe, which at least I didn't find from the documentation:

1. Add to pelicanconf.py
```bash
PAGINATED_DIRECT_TEMPLATES = ['index', 'archives']
```

2. In `templates/archives.html`:
```jinja
{% for article in dates_page.object_list %}
...
{% endfor %}
```

I would suggest to update your documentation on theme creation a bit more obvious, add some iterable properties etc.

**Comment by leotrs** [comment]
@isbm PR's that improve documentation are welcome. I agree the documentation is a bit lacking on how exactly the variables are used and what are their contents.

**Comment by leotrs** [comment]
@isbm please close this if no longer an issue.
