### ISSUE TITLE
How does one place a Pelican site in a subdirectory of an existing GitHub Pages site?

### ISSUE THREAD

**Issue by fusion809** [getpelican/pelican#1944]
Hi,

My [GitHub Pages website](https://fusion809.github.io) is mostly Jekyll-powered, but one subdirectory (https://fusion809.github.io/hubpress.io) contains a HubPress-powered part of the site. I was wondering if it might be possible to create a subdirectory of my GitHub pages website that is powered by Pelican as well. I have tried setting the URL of my site in my Pelican settings (set when I ran `pelican-quickstart`) to the subdirectory I would like to use (namely https://fusion809.github.io/pelican), but I suspect I will need to do more than this to get my Pelican subdirectory up and running. 

Thanks for your time,
Brenton

**Comment by MinchinWeb** [comment]
@fusion809 : I actually do that here: https://github.com/MinchinWeb/genealogy

In summary, set `SITEURL` to your path on the server including sub-directory. In my case:

```
SITEURL = 'http://minchin.ca/genealogy'
```

I created a separate variable (`SITE_ROOT_URL`) that I use in the template when I want to link to the "main" site.

**Comment by leotrs** [comment]
@fusion809: an update on @MinchinWeb's suggestion would be appreciated :)

**Comment by fusion809** [comment]
This was so long ago that I've since lost the interest in trying Pelican to power a subfolder of my website. The fact it took so long to get a reply tells me that Pelican doesn't have the level of support I need in order to write my site effectively. Sorry, I don't mean this to be rude I'm grateful to the two replies so far, it's just I've found the other SSGs I was checking out had a far more rapidly-responsive community when I asked questions about setting up a site in a subdirectory of an existing GitHub Pages site.

**Comment by leotrs** [comment]
To be honest, that's a fair statement and completely understandable.

**Comment by ingwinlu** [comment]
For faster responses on 'how to do x' questions check out our IRC channel. this is a bug tracker after all
