### ISSUE TITLE
Extending Author

### ISSUE THREAD

**Issue by skinless8** [getpelican/pelican#1950]
I would like to be able to automatically set the author based on the file path. To that end I was able to implement `PATH_METADATA = '\A(?P<author_id>[^/]*)/(?P<category>[^/]*)'`

Let's say I have the following in `pelicanconf.py`:
```python
AUTHOR_LOOKUP = {
    'jdoe' : {
        'name': 'John Doe',
        'twitter': '@jdoe',
        # maybe a few more e.g.: slug, author_page, etc.
}
```

What would be the proper path to create a plugin to extend the Author class so, I can use `author.name` (to be `John Doe`) and `author.twitter` (to be `@jdoe`) on the templates?

Cheers,
SL

**Comment by Scheirle** [comment]
You don't need a plugin, you can access all variables in `pelicanconf.py` directly from the templates.
e.g.: 
```
Name: {{ AUTHOR_LOOKUP[author.name]['name'] }}
Twitter: {{ AUTHOR_LOOKUP[author.name]['twitter'] }}
```
---
But I think instead of `author_id` you should use `author` in `PATH_METADATA`. (Haven't tested it)

**Comment by skinless8** [comment]
Thanks. I was able to make it work based on your suggestions.

Cheers,
SL

**Comment by justinmayer** [comment]
Thanks for helping out here, @Scheirle!
