### ISSUE TITLE
Add a option to config file to custom the slug of categories

### ISSUE THREAD

**Issue by inpool** [getpelican/pelican#1951]
I'm a Chinese user. When I set a category's name as `工具` and I want to the slug to be `Tools`, but the slug be automatic generated is 'gong-ju'. So I'd like there is a  way that I can custom the slug any thing I like it to be.

I think it can add a dict option named `CATEGORIES_SLUG`, that I can set as below:

```
CATEGORIES_SLUG = {
    '工具': 'Tools'
}
```

Or add a regexp option named `CATEGORY_RULE` for someone who use folder as category:

```
CATEGORY_RULE = '(?P<name>[^.]*).(?P<slug>.*)'
```

**Comment by Scheirle** [comment]
Related or fixed by https://github.com/getpelican/pelican/pull/1926

**Comment by inpool** [comment]
I am sorry for that I do the mistake! But I'm using the Pelican version 3.6.3 and I had not found any instruction about the options in the document on [readthedoc](docs.getpelican.com/en/3.6.3/settings.html). Now I find out it at the latest version. Thank you!
