### ISSUE TITLE
Fabric "rebuild" task ignores OUTPUT_RETENTION

### ISSUE THREAD

**Issue by bnice5000** [getpelican/pelican#1955]
In the generated fabric file, `rebuild` calls `clean` before calling `build`. `clean` wipes out the output directory. `clean` ignores `OUTPUT_RETENTION` because it just calls `shutil.rmtree(DEPLOY_PATH)`. 

The issue is compounded because `gh_pages` calls rebuild. This removes the `.git` directory and causes `gh_pages` to generate an error.

I propose that we change `rebuild` to call the builtin pelican cleaning system. Changing `rebuild` to:

```python
def rebuild():
    """`build` with the delete switch"""
    local('pelican -d -s pelicanconf.py')
```

**Comment by leotrs** [comment]
`pelican -d` also just removes the output dir. Would this not also remove `.git`?

If changing `shutil.rmtree(DEPLOY_PATH)` for `pelican -d` solves the problem, then it makes sense to me.

**Comment by bnice5000** [comment]
Yes, but it respects the `OUTPUT_RETENTION` directive in the `pelicanconf.py`. This means if you would like to keep the `.git` you just need to add ...

```python
OUTPUT_RETENTION = ['.git', '.gitignore']
```

...to your `pelicanconf.py`. Then it will not delete the directory. 

This will never be the case with `shutil.rmtree(DEPLOY_PATH)`. There is no easy way to exempt the `.git` directory using this command.

**Comment by leotrs** [comment]
Agreed, this should probably be merged. Maybe add some tests? I see how it could be tricky to write those, though.
cc. @justinmayer

**Comment by justinmayer** [comment]
By this logic, shouldn't the Fabfile's `clean()` method behavior be changed instead?

**Comment by bnice5000** [comment]
I would say yes, but I wasn't sure if other processes relied on `clean()`. `gh_pages()` relies on `rebuild()` that is why I made the change there. If you think there are no edge cases, I would advocate for changing `clean()` as well. To my mind, it would seem best to respect `pelicanconf.py` directives whenever possible.

**Comment by tjanez** [comment]
I'm also :+1: on the proposed change. I had to work-around the `clean()` problem by [writing a custom `clean()` for my site](https://github.com/tjanez/site/blob/708eab50e8aeb06e6d6c7782db20c21e36a9a52c/fabfile.py#L18-L30)

Note: Unfortunately, I didn't know about `OUTPUT_RETENTION` by then.

**Comment by tjanez** [comment]
> If changing `shutil.rmtree(DEPLOY_PATH)` for `pelican -d` solves the problem, then it makes sense to me.

@leotrs, @justinmayer one thing that would need to be changed if we want to replace Fabfile's `clean()` task with `pelican -d` is adding an argument to the `pelican` command that tells it to skip building the site.

Otherwise `pelican -d` will always rebuild the site after cleaning the output directory.

**Comment by justinmayer** [comment]
Fix merged. Thanks to @bnice5000 for reporting and fixing the issue.
