### ISSUE TITLE
Caching not working or documentation is incorrect

### ISSUE THREAD

**Issue by TierraDelFuego** [getpelican/pelican#1960]
Here are my expectations and maybe they are the problem.
I expect that if nothing changes in my source than nothing needs to be done when I run the pelican
```shell
pelican content -o output -s pelicanconf.py
```
So if I run this command before and after running pelican
```shell
ls -trl output/
```
there should be no change, but I see all the files output/*{html,txt,xml} have had their timestamps updated

Do I have incorrect expectations or misconfiguration or is something broken? I also tried using mtime.
I am using python 3.4.4

```python
    CACHE_CONTENT = True
    CONTENT_CACHING_LAYER = 'reader'
    CACHE_PATH = 'cache'
    LOAD_CONTENT_CACHE = True
    CHECK_MODIFIED_METHOD = 'sha224'
    GZIP_CACHE = False
```

**Comment by ingwinlu** [comment]
http://pelican.readthedocs.io/en/latest/faq.html#why-does-pelican-always-write-all-html-files-even-with-content-caching-enabled

**Comment by TierraDelFuego** [comment]
I think I need just a simple mechanism. One that at least does nothing if the source has no changes. That could be based on mtime or any hashlib method. I don't want it to check the derived output, I only want it to check the source content. Being new to this I had not put much thought into the pelican caching mechanism.  So my expectations were incorrect. I think the docs should have a section just on caching, starting with that FAQ.

**Comment by leotrs** [comment]
Please close this.
