### ISSUE TITLE
FORMATTED_FIELDS settings does not account for custom readers

### ISSUE THREAD

**Issue by h3** [getpelican/pelican#1962]
When using the `FORMATTED_FIELDS` setting to have parsed metadata, a custom reader connected with `signals.readers_init.connect` will not be taken into account and the metadata will be parsed with the vanilla pelican reader.

**Comment by avaris** [comment]
Can you explain more? I don't quite get what's the issue. `FORMATTED_FIELDS` is handled by the reader itself during the metadata processing (ex: [rst](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L186) and [md](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L255)). Unless the custom reader delegates some stuff to the built-in readers, that should not happen.

**Comment by h3** [comment]
I use a a modified versionof the [twitter_bootstrap_rst_directives](https://github.com/getpelican/pelican-plugins/blob/master/twitter_bootstrap_rst_directives/bootstrap_rst_directives.py) which override the RST Reader and the HTML Translator classes.

When I use a custom RST role in a meta field specified in `FORMATTED_FIELDS` it is not recognized by pelican and throws an error, it looks like pelican does not use the custom RST Reader / HTML Translator defined in the plugin.

I will try to put up a demo project with an example of the problem, but it might take some time ..

**Comment by avaris** [comment]
`CleanRSTReader` is a subclass of built-in `RstReader` and it doesn't define its own `_parse_metadata`. So, it should use the built-in one for that. That's normal. However, if that causes issues, then it's up to the plugin to override the method with a proper one.

PS: If you're getting errors, it does help to show the traceback.

**Comment by justinmayer** [comment]
@h3: Please feel free to comment here if you need additional guidance.
