### ISSUE TITLE
save_as and URL can't be arrays, but it's badly reported

### ISSUE THREAD

**Issue by JulienPalard** [getpelican/pelican#1963]
I had a problem with a file containing two "save_as" due to a bad `sed` (my fault):

```
$ grep -c ^save_as: content/the_problem.md 
2
```

The problem is an exception raised from the `os.path.join` called in [writers.py's write_file](https://github.com/getpelican/pelican/blob/master/pelican/writers.py#L157)

But I don't think catching the exception anywhere can be the right way to do, I'd rather prefer detecting the error upfront, like in the reader, but it look like a checker is already implemented, in `contents.py`, named `check_properties` and it seems the ideal place to drop something like:

```
def check_properties(self):
    """Test mandatory properties are set."""
    string_like_only_properties = {'save_as', 'url'}
    for prop in string_like_only_properties:
        if hasattr(self, 'save_as') and isinstance(self.save_as, list):
            raise ValueError("property save_as should not be a list in {}"
                             " (probably declared twice).".format(self))
    for prop in self.mandatory_properties:
        if not hasattr(self, prop):
            raise NameError(prop)
```

Giving:

> CRITICAL: ValueError: property save_as should not be a list in /home/mdk/pelican_test/content/the_problem.md (probably declared twice).

Instead of:

> CRITICAL: TypeError: join() argument must be str or bytes, not 'list'

But, before writing a PR, I'd like to know if there's other properties that have restrictions, I think of date being a parsable date, what else ? Why not checking if some properties are not empty ? Valid paths maybe ? I noted that starting a URL override with a `/` generate a link in the form `http://0.0.0.0/`, don't know if it's a real bug (I'm new to pelican) but if so, we can check it here too.

**Comment by leotrs** [comment]
+1 on checking missing properties. I think the only two necessary ones are Title and Date.
-1 on checking correct paths, I think pelican reports problematic paths well now.

**Comment by JulienPalard** [comment]
I'm not talking about checking paths, but checking that variables that should contains string (that will use string methods later) are not declared twice (and parsed as lists).

In other words: Forbid (and give verbose error message) lists where strings are intended, typically the "save_as" property, but others as well.

**Comment by leotrs** [comment]
So, perform type/sanity checks for some/all pelican settings? Sounds good to me.

**Comment by avaris** [comment]
Actually, there are [duplicate checks](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L268) for markdown. Just not for `save_as` or `url`. It might be sensible to add these to [`METADATA_PROCESSORS`](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L34) as no-op in order to benefit from that.

**Comment by JulienPalard** [comment]
@avaris Exactly why I opened a ticket: I was sure there were a clean way to do it! thanks!

I'll not push it now so if someone want to do it it's OK, else I'll check this later.

**Comment by justinmayer** [comment]
Thanks for the suggestion, @JulienPalard. Is this something you would be willing to help implement?

**Comment by justinmayer** [comment]
Status: Awaiting response from contributor to reviewer feedback on PR #2017.

**Comment by JulienPalard** [comment]
Sorry, forgot about this one, thanks for the heads up.
