### ISSUE TITLE
Hidden status for articles

### ISSUE THREAD

**Issue by rr-** [getpelican/pelican#1965]
I hesitated before creating this issue, since there are at least two workarounds for this:
- Changing file extension to something like `.md~`
- Just using `status: draft`

But `hidden` has a slightly different semantic value than `draft`, plus if pages can be _hidden_ (without the notion of being a _draft_), why can't some posts too? I believe combining `draft` and `hidden` status to be an alias of each other would be pretty reasonable.

**Comment by saschwarz** [comment]
According to the documentation that is an option: http://docs.getpelican.com/en/3.6.3/content.html?highlight=status#pages

I tried using it for a 404 page as described: http://docs.getpelican.com/en/3.6.3/tips.html?highlight=status#custom-404-pages

Unfortunately an error is generated: ``ERROR: Unknown status 'hidden' for file ./404.rst, skipping it.``

**Comment by ingwinlu** [comment]
what would a hidden post do?

**Comment by rr-** [comment]
Personally I'd like to mark some old posts as hidden so that they no longer appear on the main site (obsolete information etc.), but I can access them in the file system.

**Comment by iKevinY** [comment]
Semantically, I think there's two distinct ideas being discussed here. Like with pages, a `hidden` post would be generated but not included in the index page (and perhaps the archive as well). In other words, you could still link to a `hidden` post via `example.com/blog/2016/06/my-post/`, much like you can link to a `hidden` page via `example.com/page`.

On the other hand, there could also be an `unpublished` status, where Pelican would ignore the file completely. One possible use case for this could be people who keep their Pelican content in a Git repository that automatically builds on pushes; this would allow them to iteratively work on a post without pushing anything new to their live site. It's pretty niche, but I think having a `unpublished → draft → published` "workflow" could be valuable.

**Comment by alexwlchan** [comment]
I’ve been working around this with some ropey template code and monkey-patching bits of the feed generator. I’d be happy to have a go at incorporating this into Pelican core, if nothing else so I can tidy up my local install. :-)

I don’t have much free time this weekend, but I’ll try to put a patch together at some point.

**Comment by justinmayer** [comment]
@rr- / @alexwlchan: Is this something you would like to work on implementing?

**Comment by Telofy** [comment]
+1. My hack for now: I’ve set the article to draft and then configured a permanent redirect from the old URL to the draft URL in the Nginx I use to serve the files.

**Comment by avaris** [comment]
@Telofy you can setup `DRAFT_URL/DRAFT_SAVE_AS` same as `ARTICLE_*` to get rid of redirects.

**Comment by Telofy** [comment]
@avaris, thank you! That’s very convenient! (Since no one knows the slugs of new actual drafts, they remain hidden too.)

**Comment by justinmayer** [comment]
This issue has been around for a while without much movement. If someone wants to submit a proposed implementation, we are happy to review pull requests.

**Comment by justinmayer** [comment]
Since @GiovanH has expressed an interest in implementing `Status: hidden` for articles, I am re-opening this issue. 

If anyone is currently using `Status: hidden` for articles (which reportedly causes articles not to be generated at all), then I suggest finding another solution, since that seems like unintended behavior that I don't feel we need to preserve.

**Comment by GiovanH** [comment]
https://github.com/getpelican/pelican/pull/2866 is ready for review, although I'll poke at it a couple more times for hardening's sake.

**Comment by avaris** [comment]
Fixed in #2866 via add3628.

**Comment by s-nt-s** [comment]
I am using pelican 4.6.0 and my hidden articles sometimes are not generated and sometimes are generate as published so they are listed in index.
