### ISSUE TITLE
Confusing error message when date is not set

### ISSUE THREAD

**Issue by The-Compiler** [getpelican/pelican#1968]
I'm just trying to start using pelican, and the [docs say](http://docs.getpelican.com/en/3.6.3/content.html):

> Note that, aside from the title, none of this article metadata is mandatory: if the date is not specified and `DEFAULT_DATE` is set to `'fs'`, Pelican will rely on the file’s “mtime” timestamp

I didn't notice that I had to set `DEFAULT_DATE` and tried to run `pelican content` - what I got was:

> ERROR: Skipping ./00_Hello_World.rst: could not find information about 'NameError: date'

I think an error like "Missing required metadata field `date`" or so would have made things clearer.

**Comment by leotrs** [comment]
I think the error and the docs are clear enough.

**Comment by leotrs** [comment]
Please close this.

**Comment by justinmayer** [comment]
Thanks, Leo.

@The-Compiler: If you would like to submit a pull request that makes the error clearer, I'm sure that would be a welcome change.  (^_^)
