### ISSUE TITLE
Translation.url is not valid target, but translation.save_as is

### ISSUE THREAD

**Issue by iranzo** [getpelican/pelican#1970]
Hi,
When using an article with a translation, the same slug is defined for both, identifying different titles and different languages.

From there,sitemap or translation loop uses translation.url which points to slug path plus -$LANG but that url is not valid.

Instead, the one stored in translation.save_as works,for example:

### Works

~~~
% if article.translations %}
Translations: 
    {% for translation in article.translations %}
        <a href="{{ SITEURL }}/{{ translation.save_as }}">{{ translation.lang }}</a>
    {% endfor %}
{% endif %}
~~~

### Doesn't work

~~~
% if article.translations %}
Translations: 
    {% for translation in article.translations %}
        <a href="{{ SITEURL }}/{{ translation.url }}">{{ translation.lang }}</a>
    {% endfor %}
{% endif %}
~~~

As this also happens with the 'sitemap' plugin, I'm not sure if it's an error in pelican or something in my setup, but didn't found enough information.

Thanks,
Pablo

**Comment by iranzo** [comment]
Translation.save_as:  http://localhost:8000/blog/2007/03/09/Gestor-de-Volumenes-Logicos-LVM/index.html
Translation.url: http://localhost:8000/Logical-volume-manager-LVM-es.html
translation.slug: http://localhost:8000/Logical-volume-manager-LVM-es.html


Hope this helps

Article 1:

~~~
slug: Logical-volume-manager-LVM
layout: post
title: Gestor de Volúmenes Lógicos (LVM)
date: 2007-03-09T16:39:35Z
tags: linux, lvm
lang: es
save_as: blog/2007/03/09/Gestor-de-Volumenes-Logicos-LVM/index.html
~~~

Article 2:

~~~
slug: Logical-volume-manager-LVM
title: Logical volume manager (LVM)
layout: post
date: 2008-04-20T23:03:52Z
tags: linux, lvm
lang: en

~~~

**Comment by iranzo** [comment]
save_as was put on the first article (translation) to ensure it contained the same url as it had before it was defined as a translation.

**Comment by avaris** [comment]
If you define `save_as` metadata in the article, you should also define `url` as well so that both point to the same position. Pelican doesn't derive one from the other. In your case, you should do:

```
save_as: blog/2007/03/09/Gestor-de-Volumenes-Logicos-LVM/index.html
url: save_as: blog/2007/03/09/Gestor-de-Volumenes-Logicos-LVM
```

If you don't define them, Pelican will use `ARTICLE_LANG_SAVE_AS` and `ARTICLE_LANG_URL` to generate them. Since you only define `save_as`, pelican auto-generates `url` from the setting but your overridden `save_as` doesn't match it.

**Comment by iranzo** [comment]
Thanks,
I've did as you suggested and now it works.

I'll do it for the one I already had when migrated as I didn't wanted to lose the old url and updated the config file for:

~~~
ARTICLE_LANG_URL = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}-{lang}/'
ARTICLE_LANG_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}-{lang}/index.html'
~~~

To use a similar schema for newer ones

Thanks
