### ISSUE TITLE
Localize defaults in pelican-quickstart

### ISSUE THREAD

**Issue by nstinus** [getpelican/pelican#1971]
Now, default language and timezone are hard-coded ('en', 'Europe/Paris').
Use system locale to adjust default values.

**Comment by leotrs** [comment]
@nstinus seems sensible enough to me. Your commit also seems like a simple fix. Care to submit a PR for further review?

**Comment by nstinus** [comment]
@leotrs, if I am not mistaken, #1972 exists since I pushed my first commits.

**Comment by leotrs** [comment]
Not except get someone to review the PR.

cc. @justinmayer
