### ISSUE TITLE
Problem with double backslashes [Windows]

### ISSUE THREAD

**Issue by gerbill** [getpelican/pelican#1974]
Hi!
So I'm trying to generate a pelican based website. Html's been generated fine, but now pelican thinks that the path to these html pages are like:
`j:\\DROPBOX\\PyCharmProjects\\site\\output\\my-page.html`

which results in an error 
`OSError: [Errno 22] Invalid argument: 'j:\\DROPBOX\\PyCharmProjects\\site\\output\\my-page.html'`

Thanks in advance!

**Comment by leotrs** [comment]
@gerbill Could you run `make html DEBUG=1` and post the entire output, including the error? Thanks.

**Comment by justinmayer** [comment]
@gerbill: Please feel free to comment here if you need additional guidance.
