### ISSUE TITLE
Solved delete it

### ISSUE THREAD

**Issue by BabyBichu** [getpelican/pelican#1976]
Solved delete it

**Comment by BabyBichu** [comment]
Retried and it returned:
sent 2,492 bytes  received 2,400 bytes  889.45 bytes/sec
total size is 68,422  speedup is 13.99
rsync warning: some files vanished before they could be transferred (code 24) at main.c(1183) [sender=3.1.1]
Makefile:106: recipe for target 'rsync_upload' failed
make: *** [rsync_upload] Error 24

**Comment by ingwinlu** [comment]
close it yourself

**Comment by leotrs** [comment]
@BabyBichu please close this
