### ISSUE TITLE
(Feature request) Mix categories and pages in menu, specify order

### ISSUE THREAD

**Issue by emtiu** [getpelican/pelican#1979]
## The Situation
My page uses both categories and pages, and they should both appear on the menu, mixed in an order I specify. I might want the menu to look like this:

> Page1 — Category1 — Category2 — Page2 — Page3 — Page4 — Category3

Currently, I cannot do this, as pages and categories are listed each all in one go.

## My current hack
In pelicanconf.py, I define a list of slugs in the order I would like the corresponding pages and categories to appear in the menu:
```python
CUSTOM_MENU_ORDER = ['page1', 'category1', 'category2', 'page2', 'page3', 'page4', 'category4']
```
Then, in the template, I iterate over that list and compare the slugs of each category and page to determine which one should be inserted next:
```jinja
{% for M in CUSTOM_MENU_ORDER %}
  {% for cat, null in categories %}
    {% if cat.slug == M %}
      <li{% if cat == category %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ cat.url }}">{{ cat }}</a></li>
    {% endif %}
  {% endfor %}
  {% for p in PAGES %}
    {% if p.slug == M %}
      <li{% if p == page %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ p.url }}">{{ p.title }}</a></li>
    {% endif %}
  {% endfor %}
{% endfor %}
```
This does what I want, althought it is obviously quite *inefficient* (because it iterates over all pages and categories many times) and *uncomfortable* (because it requires me to manually enter slugs into the config file).

## Better solutions
Ideally, a "menu order" property could be encoded in the content paths to determine the position in the menu when `USE_FOLDER_AS_CATEGORY` is active. The above situation could then be easily reflected in the source tree like so:
```
content/
`- 10_page1.md
`- 20_category1/
   `- somepost.md
`- 30_category2/
   `- anotherpost.md
`- 40_page2.md
`- 50_page3.md
`- 60_page4.md
`- 70_category3/
   `- moreposts.md
   `- evenmoreposts.md
```
I have looked at implementing this with `PATH_METADATA`, but I haven't found out how to attach metadata to a category that way.

**Comment by leotrs** [comment]
Some themes define a `MENUITEMS` variable, which defines which pages/links go in the menu and in which order. [Example](https://github.com/getpelican/pelican-themes/tree/master/pelican-bootstrap3).

I think this is more of a theme-related issue. Other than defining a `MENUITEMS` variable by default in `pelicanconf.py`, there's little the core pelican codebase can do. It would be the responsibility of theme designers to use it.

**Comment by leotrs** [comment]
@justinmayer would this be considered a themeing issue?

**Comment by justinmayer** [comment]
I agree with Leo that this is (at this point) best solved in the theme.

@emtiu: There is a plugin in our repository that relates to category metadata. You might want to take a look at it if you decide to create a plugin that implements the functionality you desire.
