### ISSUE TITLE
(feature request) Offsite image links without hardcoded urls -- {imgroot}

### ISSUE THREAD

**Issue by mlabbe** [getpelican/pelican#1980]
I put all of my Blog images on Amazon servers, but host the blog on my own server.  Images are offsite.

Currently, each time I add a blog image, I have to type a wordy offsite, fully formed URL.  I also have to sync to s3 to see my images even though I haven't published my content.

It would be wonderful if there was a configuration defined value that let me specify a base URL for all image links that *may or may not be relative* to my blog in my markdown.  {imgroot} would be one possibility.

I would assign {imgroot} to be the same as {filename} (possibly the default option) on local builds of my site and then assign it to the s3 http URL on remote builds.  

Thanks for your hard work on Pelican!  I have been using it for 3 years and I really appreciate it!

**Comment by adeverteuil** [comment]
Hi,

I think this plugin can do what you want: https://github.com/getpelican/pelican-plugins/tree/master/interlinks

**Comment by leotrs** [comment]
@mlabbe Please check out @adeverteuil's suggestion and close or extend as necessary. Thanks!

**Comment by mlabbe** [comment]
Thank you for the plugin suggestion!  I deployed this change at frogtoss.com/labs and it seems to work perfectly!
