### ISSUE TITLE
index.html shows up in menu

### ISSUE THREAD

**Issue by ror6ax** [getpelican/pelican#1985]
As far as I understand, current way of setting index.html is save_as method.
Unfortunately if that page has a title, that produces a link in the menu, which is confusing sometimes.

Is there a way to skip one page from being added to menu?
Special tratment for index.html?

Thanks!

**Comment by leotrs** [comment]
Different themes do it in different ways. For example, some add all pages by default (which is probably why index is showing up in your menu. Others define a `MENUITEMS` variable that you can customize in perlicanconf.py. Check out your theme's documentation and/or the `base.html` template to see which links get added to the menu.

**Comment by avaris** [comment]
`status: hidden` should do it.

**Comment by leotrs** [comment]
This should be closed now.

**Comment by justinmayer** [comment]
Thanks, Leo.

@ror6ax: If you need further guidance, please comment here and we will assist if we can.

**Comment by diazgilberto** [comment]
I have a similar question about the `index.html`. When I set the `Title: Home`, Home appears in the menu bar and in the content. If I use the `status: hidden` Home is just in the content. How can I setup the `index.html` to utilize `Home` in the menu bar **BUT NOT** in the content.
