### ISSUE TITLE
Changing Content._content doesn't change the output of the property Content.content

### ISSUE THREAD

**Issue by leotrs** [getpelican/pelican#1986]
...because `Content.content` returns the output of `Content.get_content`, which is [`@memoized`](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L280).

My plugin is modifying the contents of articles. After [the warning](http://docs.getpelican.com/en/3.6.3/plugins.html#list-of-signals) on the docs about using `_content` and not `content`, it seems there is only one chance to write to `_content`: before pelican reads it at all, since it's memoized.

What is the current best way to modify the contents of articles?

**Comment by leotrs** [comment]
A possible solution is to add `self._content` as an argument for the memoized `Content.get_content`. Since it's memoized based on its arguments, if I call with a modified `_content`, it should force it to recompute.

Right now my workaround is to disable memorization altogether.

cc. @justinmayer

**Comment by avaris** [comment]
The problem with working around memoization is that if `content` was memoized, it means that something, somewhere used `content`. And you'll be modifying it afterwards (i.e. unchanged `content` is still somewhere). Proper way to handle it is to modify `._content` as early as possible. That's usually means `content_object_init` signal.

**Comment by leotrs** [comment]
@avaris Just tried. Ran my code at `content_object_init`, didn't read `content` at all, and it doesn't work unless I disable memoization.

**Comment by avaris** [comment]
@leotrs can you show your code?

**Comment by leotrs** [comment]
False alarm. Apparently, when I posted two hours ago I didn't test carefully enough.

The problem was that I was reading `.content`, modifying it, and writing to `._content`. If I read and write `._content` instead, this is solved (presumably because there is no memoization being performed).

The warning in the docs warns against reading `._content` during `content_object_init`, and I am doing everything at `article_generator_finalized` so I guess it was all right to read it. That's a bad excuse, but I still think the warning should probably be clearer and say that reading `.content` instead of `._content` is risky at any point.

**Comment by avaris** [comment]
Well, the warning is about reading `content`, not modifying, and in that sense it is correct. But it might be useful to add some info about how to modify `content` properly.

**Comment by leotrs** [comment]
Is anyone specifically in charge of writing documentation?

**Comment by avaris** [comment]
No, you can send a PR if you're willing to do it.

**Comment by leotrs** [comment]
> But it might be useful to add some info about how to modify content properly.

If "properly" means read and write from `_content`, do it as soon as possible, and leave `content` alone, then sure, I can do it.
