### ISSUE TITLE
Reference to a nonexistent regex group on contents.py

### ISSUE THREAD

**Issue by leotrs** [getpelican/pelican#1987]
The code on [line 214](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L214) references a group named `what`, but there is no group with such name in the regex (defined on line 205).

**Comment by TierraDelFuego** [comment]
Are you reporting a problem you're seeing with your env?

**Comment by TierraDelFuego** [comment]
Please close this.

**Comment by leotrs** [comment]
You're right, didn't catch that.
