### ISSUE TITLE
[ Question / Help ] For Loop Over  MetaData Returns Null

### ISSUE THREAD

**Issue by CelticParser** [getpelican/pelican#1988]
I am trying to generate list items by looping the metadata `Category: musicians` who donate to the current "active charity" page where the key:value pair `Charities: {CHARITY_NAME}` within a musician's page matching that of the current `Title: {CHARITY_NAME}`.  I cannot seem to get my head around how `context` and `for` loops works in 'Pelican' / 'Jinja2' yet (just started playing with it this week).  My apologies for opening an issue - We don't have access to IRC here and I am getting no traction with this question on S.O.

 Any help would be greatly appreciated.

**charity-test.md:**

    Title: Charity Test
    Category: charities
    Template: charity

**musician-test.md**

    Title: Some Musician
    Category: musicians
    Template: musician
    Charities: Charity Test

**charity.html** (template):

    ...
    <h3>Donations made to {{ article.title }} by&colon;</h3>
    <ul>
    {% for charity, articles in charities %}
        {% if charity == article.title %}
        <li><a href="/{{ article.url }}">{{ article.title }}</a></li>
        {% endif %}
    {% endfor %}
    </ul>
    ...

**Should return:**

    <h3>Donations made to Charity Test by&colon;</h3>
    <ul>
        <li><a href="/some-musician.html">Some Musician</a>(1)</li>
    </ul>

**But I get:**

    <h3>Donations made to Charity Test by&colon;</h3>
    <ul>
      </ul>

**Comment by leotrs** [comment]
Try printing both the string you're comparing to see their values. Poor man's debugging.
```
<h3>Donations made to {{ article.title }} by&colon;</h3>
<ul>
{% for charity, articles in charities %}
    <p>{{ charity }}</p>
    <p>{{ article.title }}</p>
    {% if charity == article.title %}
    <li><a href="/{{ article.url }}">{{ article.title }}</a></li>
    {% endif %}
{% endfor %}
</ul>
```

Maybe `charity` is not evaluating to the actual name, and you need to do `charity.name` or some such.

**Comment by CelticParser** [comment]
I tried your method  and I still get no returns.  If I try the following based from a theme example to learn off of:

```
{%- for tag, articles in tags %}
    <p>{{ tag }}</p>
    {%- if tag == article.title %}
    <li>{{ article.title }}, {{ article.url }}, {{ article.category }}</li>
    {% endif %}
{% endfor %}}
```

If I add `tags: Charity Test` to the charity .md files

.. I get a return, but from the current page context, not from the page(s) I am trying to loop over. Obviously I've got something wrong or misunderstanding it completely.  Any ideas or where to look. Thnx!

**Comment by CelticParser** [comment]
@leotrs , If you need to poke at my files:

[pelicanconf.py](https://github.com/CelticParser/unstrungheroes/blob/dev/pelicanconf.py)
[charity.html](https://github.com/CelticParser/unstrungheroes/blob/dev/private/app/themes/default/templates/charity.html)
[charity-test.md](https://github.com/CelticParser/unstrungheroes/blob/dev/private/content/charities/charity-test.md)
[musician-test.md](https://github.com/CelticParser/unstrungheroes/blob/dev/private/content/musicians/musician-test.md)

**Comment by leotrs** [comment]
Can you do
```
<h3>Donations made to {{ article.title }} by&colon;</h3>
<ul>
    <p>{{ charities|length }}</p>
</ul>
```
If it says 0 or None, then there's nothing inside `charities` and the loop is not even running.

Setting a `Charities` metadata at the top of your files is going to make it available as `article.charities` when you are rendering the template for that particular article. But I'm not sure it automatically stores a list of all charities and its corresponding articles as you are assuming. That works for `categories` because `categories` (and `tags`) are handled separately by pelican.

**Comment by CelticParser** [comment]
Thnx - That shed a lot of light to pelican's capability out of the box.

**Comment by leotrs** [comment]
Please post your solution if you were able to do what you wanted.
