### ISSUE TITLE
Links should be relative, not absolute

### ISSUE THREAD

**Issue by klahnakoski** [getpelican/pelican#1990]
I followed the quickstart instructions [1] to make a test page.   The links on that page are all absolute, and consequently do not work.   This is a poor default, or a bug. 

For example, the css link is wrong:

    <link rel="stylesheet" href="/theme/css/main.css" /> 

Please remove the leading slash

    <link rel="stylesheet" href="theme/css/main.css" /> 

[1] http://docs.getpelican.com/en/3.6.3/quickstart.html

**Comment by ingwinlu** [comment]
did you set up your `SITEURL`? The template is setup to lead with that on all links. If you did not set it more than just that like will be broken.

**Comment by klahnakoski** [comment]
Please mention that detail in the quickstart.

**Comment by ingwinlu** [comment]
don't quite agree on that. quickstart is not the right place for it.

might make more sense to force `RELATIVE_URLS` to true if `SITEURL` is empty and print out a warning

**Comment by justinmayer** [comment]
Saying that links "do not work" is not particularly descriptive. If you mean you are opening `.html` files directly in your browser, than you aren't properly following the [Preview your site](http://docs.getpelican.com/en/stable/quickstart.html#preview-your-site) section of the QuickStart guide.

**Comment by klahnakoski** [comment]
justinmayer,

You are correct, I did assume that the `output` directory would hold a set of files that can be served by any vanilla web server (and "just work" when viewed with a browser).  I was not aware the `pelican.server` was specially suited to serve these absolute URLs.

It would be nice to have the URLs be relative.  This would allow other web servers to serve the content, and allow other tools, like IDEs, be able to process the `output` content.  ingwinlu's suggestion of setting `RELATIVE_URLS` to true seems like good default behaviour.

**Comment by justinmayer** [comment]
> I was not aware the pelican.server was specially suited to serve these absolute URLs.

The links you pasted above are not absolute. They are root-relative.

> It would be nice to have the URLs be relative.

They are. They are relative to site root. You are referring to document-relative links. If you want those, the RELATIVE_URLS setting may work for you.

That said, I think that setting can lead to unexpected and confusing behavior for the majority of people, and for that reason I do not think it wise to make that the default.
