### ISSUE TITLE
How can I use particular category as a default index.html?

### ISSUE THREAD

**Issue by Casyfill** [getpelican/pelican#1994]
I have three categories - texts, projects, and blog, having a separate menu item for each. However, I would like to use blog category item as a default index.html for the whole site, as now I've got all the entries together on the index.html page.

**Comment by leotrs** [comment]
There are ways of changing the URL for all categories (`CATEGORY_SAVE_AS`), and there are ways of using a static page as `index.html`, but I can't think of a way of setting just one category page as the index.

@justinmayer?

**Comment by ingwinlu** [comment]
create a index.html template to filter articles by category title

**Comment by leotrs** [comment]
@Casyfill did you end up trying ingwinlu's suggestion?

**Comment by Casyfill** [comment]
Won't  changing the index template will affect ALL index.html on the website?
I tried to add something like `for article in articles if article.category=='BLOG'` but this didn't help

More generally, - can I somehow customize template for only one category representation?

**Comment by leotrs** [comment]
There's only one page that is rendered from the `index.html` template: the index/landing/home page. Other pages are rendered from `category.html` and `categories.html`.

Did you try using two different jinja statements?
```
{% for article in articles %}
    {% if article.category == "BLOG" %}
        <p>content</p>
    {% endif %}
{% endfor %}
```

**Comment by justinmayer** [comment]
@Casyfill: Please feel free to comment here if you need additional guidance.
