### ISSUE TITLE
Can't make internal link

### ISSUE THREAD

**Issue by Jibec** [getpelican/pelican#1995]
hi there
I'm having two issues with page links : 

1. the link on the first footnote is wrong on my page : https://jibecfed.fedorapeople.org/l10n/appdata-fr/pages/a-propos.html

the page "à propos.md" should link to the page "contribuer.md" by using the following markdown syntax : `[contribuer](({filename}/contribuer.md))`
At the end, with full path, I should have https://jibecfed.fedorapeople.org/l10n/appdata-fr/pages/contribuer.html

the source code is there : https://pagure.io/L10N-AppData/blob/master/f/content/pages
the two pages are static and not automatically generated.

2. I do not understand how to point to categories.html and tags.html in that page https://jibecfed.fedorapeople.org/l10n/appdata-fr/pages/contribuer.html
I tried with {PATH} and {filename} but it failed

Those questions would have been better on a mailing lists, but I haven't found one, and I can't really use IRC. I love pelican, thanks a lot for this great tool! :)

btw : I am looking for a good way to internationalize this website about AppData translation (AppData are metadata used by Gnome-Software in Fedora/Debian/Ubuntu, etc) but I have the following issue : each article can be specialized for dozens for languages and the UI can also be translated in dozens of languages. I don't really know how to start.

**Comment by ingwinlu** [comment]
- `[^1]: Le mode opératoire détaillé est disponible sur la page [contribuer](({filename}/contribuer.md)) !`

   should be
   `[^1]: Le mode opératoire détaillé est disponible sur la page [contribuer]({filename}/contribuer.md) !`

  as is documented in the [writing content/linking to static files section](http://pelican.readthedocs.io/en/latest/content.html#linking-to-static-files) of the pelican docs

- information about your second question should be covered by the [url settings](http://pelican.readthedocs.io/en/latest/settings.html#url-settings).
   >URLs for direct template pages are theme-dependent. Some themes use corresponding *_URL setting as string, while others hard-code them: 'archives.html', 'authors.html', 'categories.html', 'tags.html'.

**Comment by Jibec** [comment]
oh, it was so easy, thank you!
