### ISSUE TITLE
Markdown import from Wordpress generates invalid Markdown

### ISSUE THREAD

**Issue by rossburton** [getpelican/pelican#1997]
With the following XML fragment in a WordPress export:

`<a href="http://www.flickr.com/photos/35468147630@N01/16995308217/" title="Family ride at Thetford Forest" rel=""><img src="http://farm8.staticflickr.com/7680/16995308217_bb4f7a3867.jpg" width="500" height="375" alt="Family ride at Thetford Forest" title="Family ride at Thetford Forest" class="aligncenter"></a>`

A Markdown attribute list is generated after the image:

`![alt-text](url){width="500"
height="375"}`

Note the new line in the attribute list.  This causes Markdown to throw ValueError: too many values to unpack.

**Comment by leotrs** [comment]
What new line?

Also, as a general comment: the import functionality is meant to let people migrate as many posts as possible, as fast as possible. I'm not sure how much effort was put into perfect migration.

Not to discourage you though, this looks like a legitimate issue that should be looked into.

**Comment by avaris** [comment]
`pelican-import` uses `pandoc` to generate markdown from html. This is likely an issue coming from `pandoc`.

**Comment by justinmayer** [comment]
@rossburton: Not sure this is a Pelican issue, but if you can verify it is, please comment here and I will re-open.
