### ISSUE TITLE
Typogrify is incorrectly modifying page titles

### ISSUE THREAD

**Issue by Cartroo** [getpelican/pelican#1998]
I have Typogrify enabled on my site and since I created a page (not an article) with an ampersand in the title, I've noticed that the generated HTML ends up like this:

    <title>Trips <span class="amp">&amp;</span>&nbsp;Events</title>

I'd be quite surpriesd if `<span>` isn't valid within the `<head>` section and certainly at least Chrome renders this text literally in the tab title.

I'm afraid I don't yet have a test case online (this is still a draft) but you can easily replicate by creating a page and using an ampersand in the `Title` metadata.

**Comment by avaris** [comment]
see #1930

**Comment by justinmayer** [comment]
As mentioned in the issue @avaris pointed out, themes should ensure tags are stripped from titles.
