### ISSUE TITLE
Add 'reviewers' team to Pelican organization

### ISSUE THREAD

**Issue by iKevinY** [getpelican/pelican#2009]
Since GitHub added better [code review tools](https://help.github.com/articles/reviewing-changes-in-pull-requests/), how does adding a 'reviewers' team to the Pelican organization sound? We could make use of [required reviews](https://help.github.com/articles/about-required-reviews-for-pull-requests/), and it would be easier to bring relevant people into the conversation via mentions.

/cc @justinmayer @almet @kylef @avaris @ingwinlu

**Comment by Scheirle** [comment]
Maybe https://github.com/facebook/mention-bot could be useful.

**Comment by justinmayer** [comment]
I created @getpelican/reviewers and sent out some invitations. 😺

**Comment by Scheirle** [comment]
It would be nice if the Reviewers team could add/change issue labels.
But I'm not sure if this can be configured independent of the repository write access.

**Comment by leotrs** [comment]
This is done and seems to be working. Maybe we can close it unless there is some follow-up to @Scheirle 's suggestion. cc @justinmayer

**Comment by justinmayer** [comment]
Thanks, Leo. I agree with @Scheirle that such a feature would be nice. I imagine GitHub will add that capability at some point soon.

For now, this task is complete.
