### ISSUE TITLE
Category is formatted as lowercase and first uppercase

### ISSUE THREAD

**Issue by gbraad** [getpelican/pelican#2010]
Currently, the category I specify gets changed to lowercase with a starting uppercase. This means that a category like 'CI/CD', or 'PaaS' will never work correctly.

I noticed the category is processed after by process_if_not_empty, by processor(name, settings). So I assume this behaviour can be over-ridden... how and where? If not, where should I implement this?

**Comment by avaris** [comment]
What you're describing isn't the default behavior of pelican. Category names should be preserved as is. Are you using any plugins? Maybe one of them is the culprit?

Try running pelican without any plugins.

**Comment by gbraad** [comment]
The page is automatically built as described in https://gitlab.com/gbraad/blog/blob/master/.gitlab-ci.yml. I pull the plugins repository, but only activate:

```
PLUGINS = [u"disqus_static"]
```

in `pelicanconf.py`. But, could this behaviour be related to the Theme? I derived mine from the Bootstrap3 theming.

**Comment by avaris** [comment]
Yes, looks like theme is the one doing [that](https://github.com/gbraad/blog-theme/blob/master/templates/base.html#L133). Specifically, the `capitalize` call.

**Comment by gbraad** [comment]
Thanks... closing as it is unrelated to Pelican itself.
