### ISSUE TITLE
USE_FOLDER_AS_CATEGORY prevents setting category in PATH_METADATA or FILENAME_METADATA

### ISSUE THREAD

**Issue by jpli** [getpelican/pelican#2012]
The user needs to explicit set `USE_FOLDER_AS_CATEGORY` to `False` to make category settings in PATH_METADATA of FILENAME_METADATA to work (see the example in #2011), this is consistent with [documentation](http://docs.getpelican.com/en/stable/content.html)

> If you would like to organize your files in other ways where the name of the subfolder would not be a good category name, you can set the setting USE_FOLDER_AS_CATEGORY to False.

What's wrong with this behavior? If category is specified as a part of the path metadata, the user probably won't want to use the folder name as category, and the code before pull request  #795, commit a9c530281e1928e9f9f3c2cb78312db784505ca1 supports this logic.

So I suggest reverting to the previous behavior, it is also easy to accomplish, just append the check to the end of path metadata checks:

```python
         if settings.get('USE_FOLDER_AS_CATEGORY', None):
            # checks.insert(0, ('(?P<category>.*)', subdir))
            checks.append(('(?P<category>.*)', subdir))
```

If no category is specified in `PATH_METADATA` or `FILENAME_METADATA`, it falls back to `USE_FOLDER_AS_CATEGORY`, which defaults to `True`.

Anyone in?

**Comment by ingwinlu** [comment]
i would rather remove `USE_FOLDER_AS_CATEGORY`. no need for unintuitive behaviour if you can actually set a regex to get all path information you could possible want

**Comment by jpli** [comment]
It's much better if `USE_FOLDER_AS_CATEGORY` can be removed, looks simpler. @ingwinlu 

If `PATH_METADATA` is changed to a list, `FILENAME_METADATA` can be removed too, the user can decide which metadata to extract from each path level, without having to worry about OS-specific path seperators.

**Comment by avaris** [comment]
Well, `USE_FOLDER_AS_CATEGORY` is a shortcut for people who doesn't know or want to bother with regex. That doesn't mean it has to stay, but it's a point of consideration.

Apart from regex related ones, the overall `metadata` settings is a complete mess with duplicates like (`AUTHOR`, `DEFAULT_LANG`, etc vs `DEFAULT_METADATA`). A more general overhaul to the whole `metadata` system might be a good idea.

Also, related: #1128

**Comment by jpli** [comment]
#1128 already has this topic covered. Sorry for having not checked all the opening issues. Closing this issue.
