### ISSUE TITLE
Atom feed invalid: shows all entries as new on each update

### ISSUE THREAD

**Issue by azrdev** [getpelican/pelican#2014]
I could reproduce wallabag/wallabag.org#25 on my on pelican blog:
Whenever there is a new entry in the atom feed, each of the previous entries appears again as new/unread. The feed is missing <updated> tags in each entry, which are mandatory according to the spec.

**Comment by ingwinlu** [comment]
update to feedgenerator 1.9 should solve that issue

**Comment by justinmayer** [comment]
@azrdev: Have you tested on FeedGenerator 1.9? Please let us know.

**Comment by azrdev** [comment]
@justinmayer sorry, yes, I did, the `<updated>` tags are now present and have the desired effect (only updated posts showing in the feedreader)
