### ISSUE TITLE
Development server stops updating on RST warning

### ISSUE THREAD

**Issue by keisetsu** [getpelican/pelican#2018]
I am trying to have a span for the first letter of certain paragraphs in text. For example:

:first-letter:\`T\`esting

This generates a warning from the development server (develop_server.sh), and any conversion just stops. I believe this an rst limitation (rst seems to want whitespace after the second backtick), but the point is that it kills the conversion process because of a warning. 

Now, even if I fix this, the conversion process seems to be dead, and it doesn't notice any more changes. I have to run `develop_server.sh restart`. 

Possibly related to #1759

**Comment by justinmayer** [comment]
Thanks for the heads-up, Jesse. Closing this in favor of the pre-existing issue linked in your issue description.
