### ISSUE TITLE
Add configuration option that allows overriding theme template files

### ISSUE THREAD

**Issue by pedrohdz** [getpelican/pelican#2021]
It would be useful to allow overriding theme template files without having to fork an existing theme.  There are times where just a single file needs to be replaced, `article.html` as an example, and everything else can stay the same.  Even overriding multiple files would be helpful.

Having to fork an existing theme seems a little excessive and having to do a 3-way merge to keep up with upstream changed to an existing theme increases friction unnecessarily.

Adding a new variable, like `THEME_TEMPLATE_OVERRIDES`, to the configuration file should do the trick.

``` python
THEME_TEMPLATE_OVERRIDES = (
    'templat_overrides/pelican-bootstrap3/templates',
    'templates')
```

`EXTRA_TEMPLATES_PATHS` already does something **similar**, but the issues with it are:
1. It seems to be targeted towards managing `DIRECT_TEMPLATES`.
2. It is processed/scanned **after** the theme templates.  Theme templates take precedence so there is no chance of overriding using `EXTRA_TEMPLATES_PATHS`.
3. Moving `EXTRA_TEMPLATES_PATHS` up might have some un intended consequences.
4. The name `EXTRA_TEMPLATES_PATHS` does not match up with what we are trying to do.

The change in `pelican/generators.py` would look something like:

```
        self._templates_path = []
        self._templates_path += self.settings['THEME_TEMPLATE_OVERRIDES']
        self._templates_path.append(os.path.expanduser(
            os.path.join(self.theme, 'templates')))
        self._templates_path += self.settings['EXTRA_TEMPLATES_PATHS']
```

This would be a quicker solution than what is being discussed in getpelican/pelican#1092.  It is not the same as _Inheriting from an arbitrary theme_, but is a decent stopgap IMHO.

I will try and get a PR in for this later next week.  I'm hoping there is interest.

Cheers...

**Comment by digitalrounin** [comment]
I will gladly change this into a plugin if that is the best place for this type a change.

**Comment by justinmayer** [comment]
Ostensibly addressed via linked PR.
