### ISSUE TITLE
optionally exit "autoreload" on errors

### ISSUE THREAD

**Issue by omiday** [getpelican/pelican#2029]
As discussed in #1759 `autoreload` should not exit on document parsing errors, however for particular circumstances this is desirable (see #1224).

On IRC @avaris suggested:

> 14:16 <          Avaris > as a devil's advocate, i do understand the original PR's intent but right now it's incomplete. if a failfast approach is needed it can be an option for every reader error (not just a single case).
> 14:16 <          Avaris > say a `--failfast` option for pelican which will exit with non-zero code for any error
> 14:18 <         justmay+> I agree that having that as a non-default option makes more sense than the current behavior.

I'll take it from here.

**Comment by avaris** [comment]
Right, I forgot about that.
