### ISSUE TITLE
Overhaul settings table in documentation

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#2037]
At some point, the previous settings table width:

http://docs.getpelican.com/en/stable/settings.html

... was changed to a much wider format that falls off the right-hand side of the screen:

http://docs.getpelican.com/en/latest/settings.html

I would like the previous formatting to be restored before releasing Pelican 3.7.

Would any @getpelican/contributors care to help out with this?

**Comment by omiday** [comment]
Editing tables can be tricky when the editor is set to wrap in Python mode or not wrap at all. There is also no way to control the table width. The tables on the settings page are actually quite complex and if the goal is to stay within the Python convention of 79 chars width, personally I would forgo the tables and adopt the style of [Python Built-in Constants](https://docs.python.org/3/library/constants.html). I've uploaded a sample output at http://dev.infrabit.net/pelican/settings.html. 

With that being said, I'll happily just fix the broken table :)

**Comment by ingwinlu** [comment]
i approve of @omiday 's approach. Editing the tables always was a mess.

**Comment by justinmayer** [comment]
@omiday: I agree with Winlu — your idea seems sensible. Assuming we switch to that format, we'll probably also want to add a table of contents at the top, since the switch will cause that page to become considerably longer.
