### ISSUE TITLE
Forcing the feed generator to use the post summary as feed summary

### ISSUE THREAD

**Issue by rubik** [getpelican/pelican#2039]
I have a post which is a Jupyter notebook. It looks like this:
```
Title: My post
Category: notebooks
Slug: my-post
Summary: Short summary about post

{% notebook notebooks/my_post.ipynb %}
```

When I activate the atom generator, I see something like
```xml
<feed xmlns="http://www.w3.org/2005/Atom">
<title>Blog title</title>
[ ... ]
<entry>
<title>My post</title>
[ ... ]
<summary type="html">The whole Jupyter notebook here</summary>
</entry>
</feed>
```

The feed generator includes the whole notebook in the summary, but it should just include the post summary which I provided in the post metadata.

How can I force that behaviour?

**Comment by justinmayer** [comment]
Hi Michele. Have you read the [How to Get Help](http://docs.getpelican.com/en/latest/contribute.html#how-to-get-help) docs thoroughly? (Hint: it specifically mentions that we need to know what version you are running.)

Have you looked at existing issues, including those that have already been closed?

**Comment by rubik** [comment]
Hi, sorry, the Pelican version is 3.6.3. Yes, I looked into the old issues and found an option `FEED_USE_SUMMARY = True`, which does not change anything for me.

**Comment by justinmayer** [comment]
As far as I can tell, this is essentially a dup of #1886, which has already been addressed in current master.

**Comment by rubik** [comment]
Yes, that was the issue I found. I tried the pelican master but it didn't work with `pelican-plugins/liquid_tags` (master as well), so I thought there could be another solution. Anyway, now I made it work. I am sorry to have wasted your time.

**Comment by justinmayer** [comment]
No worries. Glad you resolved the problem.
