### ISSUE TITLE
Tags support for pages in pelican

### ISSUE THREAD

**Issue by srivignes** [getpelican/pelican#2041]
I wanted to create all the .html files as the pages for my site. But there is no tag folder or category folder created for 'pages' like it creates for 'articles'. So is there any way to activate those features for pages ?

For instance, If I create my project with this folder structure:

                  - content
                        - pages
                             - hello.md
                             - world.md
The content of the hello.md:

------------------------------------------------------------------------------------------------------------------
Title: Hello
Category: samples
Tags: hello, hi

Hello to everyone!

------------------------------------------------------------------------------------------------------------------

The content of the world.md:

------------------------------------------------------------------------------------------------------------------

Title: World
Category: data
Tags: hello, world

Hello World!

------------------------------------------------------------------------------------------------------------------

The output generated is:

                  - output
                       - pages
                             - hello.html
                             - world.html
                       - index.html
                       - categories.html
                       - tags.html
Again, If I create my project with this folder structure with the same content:

                 - content
                       - articles
                             - hello.md
                             - world.md
The output folder was generated with:

                 - output
                      - articles
                             - hello.html
                             - world.html
                      - category
                             - samples.html
                             - data.html

                      - tag
                             - hello.html
                             - hi.html
                             - world.html

                      - index.html
                      - categories.html
                      - tags.html  
So I need the category and tag folder to be created for the 'pages' like it gets created for 'articles'. I looked into a pelican plugin named 'autopages' which makes me to externally create the tag folder and create .md files inside the tag folder as there will be more number of tags added. But I don't need that, I need the tag and category folder to be automatically created for pages. Is there any way to activate those features in pelican ?

**Comment by justinmayer** [comment]
As noted in #1757, neither categories nor tags are supported for pages. Pull requests to that effect are welcome, but so far nobody has stepped up to contribute said functionality.
