### ISSUE TITLE
Automatically restarting devserver

### ISSUE THREAD

**Issue by gokul-uf** [getpelican/pelican#2048]
Posting here because I couldn't find a user-group/ dev-chat. Apologies!
One of the things I found interesting about Pelican is when I do `make devserver` , the server regenerates the files every time I update the Markdown. I am looking to implement a similar functionality in one of my projects. Could you guys tell me how you did it?

Thanks!

**Comment by justinmayer** [comment]
Hi Gokula. The code for the auto-reload functionality is here: https://github.com/getpelican/pelican/blob/master/pelican/__init__.py#L413

As mentioned in the docs, the "dev chat" occurs in the [#pelican IRC channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). If you have any follow-up questions, please ask in that forum. Thanks!
