### ISSUE TITLE
Please add split line feature for summary

### ISSUE THREAD

**Issue by Inndy** [getpelican/pelican#2055]
If I have a post with super long image (like 800 * 12000), you must spend some time to scroll through this super long image.

It will be great to hove a feature like `<!--more--><br />` which provided by blogspot.

Content after splitter will be hidden from summary. It will be useful to hide something very long or NSFW from the list.

**Comment by avaris** [comment]
There is a plugin for that: [summary](https://github.com/getpelican/pelican-plugins/tree/master/summary)

**Comment by Inndy** [comment]
@avaris thanks!
