### ISSUE TITLE
pre build script hook

### ISSUE THREAD

**Issue by sdementen** [getpelican/pelican#2057]
I need to run a script before the build process of the website (conversion of markdown file to html files).
To get a bit of context, the script takes a csv file and then generates a series of markdown files based on a template and the content of the script.

Is there some way to hook such "pre build" command to pelican ?
And if so, how could I also notify to pelican than the "autoreload" option should watch for changes in the csv file too ?

sebastien

**Comment by justinmayer** [comment]
> I need to run a script before the build process of the website (conversion of markdown file to html files). To get a bit of context, the script takes a csv file and then generates a series of markdown files based on a template and the content of the script.

Hi Sebastien. The easiest method would be automation via Make, Fabric, et cetera, that would call your script and then subsequently call Pelican.

> Is there some way to hook such "pre build" command to pelican? And if so, how could I also notify to pelican than the "autoreload" option should watch for changes in the csv file too?

That's more complicated and would likely require writing a plugin for Pelican.

If you have any further questions, please reach out via the [Pelican IRC channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). Thanks!
