### ISSUE TITLE
Bokeh plots doesn't display in blogs made using pelican and github pages

### ISSUE THREAD

**Issue by arjan-hada** [getpelican/pelican#2061]
I got my website up and running however, the plots I have made using Bokeh doesn't show up.
Please look at code cell 12 in this link:-
https://arjan-hada.github.io/enron-fraud.html

Here is the console output for the error:-

Console Output

enron-fraud.html:1818 Uncaught ReferenceError: $ is not defined
at https://arjan-hada.github.io/enron-fraud.html:1818:15
enron-fraud.html:2087 Bokeh: BokehJS plotting callback run at Sat Dec 10 2016 21:14:02 GMT-0800 (Pacific Standard Time)
enron-fraud.html:2073 Bokeh: BokehJS failed to load within specified timeout.
enron-fraud.html:2009 Bokeh: all callbacks have finished
enron-fraud.html:2317 Bokeh: BokehJS plotting callback run at Sat Dec 10 2016 21:14:03 GMT-0800 (Pacific Standard Time)
enron-fraud.html:2306 Uncaught ReferenceError: $ is not defined
at run_inline_js (https://arjan-hada.github.io/enron-fraud.html:2306:20)
at https://arjan-hada.github.io/enron-fraud.html:2318:9
at https://arjan-hada.github.io/enron-fraud.html:2237:67
at Array.forEach (native)
at run_callbacks (https://arjan-hada.github.io/enron-fraud.html:2237:38)
at load_libs (https://arjan-hada.github.io/enron-fraud.html:2249:9)
at https://arjan-hada.github.io/enron-fraud.html:2316:7
at https://arjan-hada.github.io/enron-fraud.html:2321:4
enron-fraud.html:2317 Bokeh: BokehJS plotting callback run at Sat Dec 10 2016 21:14:03 GMT-0800 (Pacific Standard Time)
enron-fraud.html:2306 Uncaught ReferenceError: $ is not defined
at run_inline_js (https://arjan-hada.github.io/enron-fraud.html:2306:20)
at https://arjan-hada.github.io/enron-fraud.html:2318:9
at https://arjan-hada.github.io/enron-fraud.html:2424:67
at Array.forEach (native)
at run_callbacks (https://arjan-hada.github.io/enron-fraud.html:2424:38)
at load_libs (https://arjan-hada.github.io/enron-fraud.html:2436:9)
at https://arjan-hada.github.io/enron-fraud.html:2503:7
at https://arjan-hada.github.io/enron-fraud.html:2508:4
enron-fraud.html:2317 Bokeh: BokehJS plotting callback run at Sat Dec 10 2016 21:14:03 GMT-0800 (Pacific Standard Time)
enron-fraud.html:2306 Uncaught ReferenceError: $ is not defined(…)

**Comment by justinmayer** [comment]
Those look like JS errors and are likely unrelated to Pelican. Perhaps someone in the Pelican IRC channel might be able to assist. That's our preferred medium for support, as mentioned in the [Getting Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of our docs.
