### ISSUE TITLE
Is there any way to setting article url as markdown filename

### ISSUE THREAD

**Issue by sincerefly** [getpelican/pelican#2062]
Now, I am using hexo blog, and the markdown filename will the url name, If using prlican, How can I do to setting it

**Comment by justinmayer** [comment]
Perhaps try something like the following in your Pelican settings file:

    SLUGIFY_SOURCE = 'basename'
    ARTICLE_URL = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/'
    ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/index.html'

The **Settings** section of the docs will have more detail. In the future, please refer to the [Getting Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the docs and reach out via the Pelican IRC channel with any further questions.

**Comment by sincerefly** [comment]
@justinmayer Thank you very much
