### ISSUE TITLE
A configuration option for adding gettext to the jinja environment is needed

### ISSUE THREAD

**Issue by jranke** [getpelican/pelican#2064]
It seems that upgrading to Pelican 3.7.0 makes it impossible to use the i18n extension for jinja, see getpelican/pelican-themes/issues/460.

When using the i18n extension via `JINJA_ENVIRONMENT = {'extensions': ['jinja2.ext.i18n']}`, `gettext` needs to be installed into the jinja environment using a call to `jinja2.Environment.install_gettext_callables` as documented [here](http://jinja.pocoo.org/docs/dev/extensions/).

I think a configuration option for pelicanconf.py is needed here. Or maybe pelican should attempt to install gettext (and ngettext?) into the jinja environment when the setting of `JINJA_ENVIRONMENT` requests the i18n extension.

**Comment by justinmayer** [comment]
@rjames86: As the contributor of #1999, do you have any thoughts on this?

**Comment by rjames86** [comment]
Looking into it. Keeping the conversation in one place here: https://github.com/getpelican/pelican-themes/issues/460

**Comment by justinmayer** [comment]
I'm not yet convinced that anything needs to be changed in Pelican core. We can re-open if and when such evidence is presented in the linked issue in the other repository.
