### ISSUE TITLE
Weird make problem

### ISSUE THREAD

**Issue by richyvk** [getpelican/pelican#2066]
Hi

I've been playing around with Pelican and come across what I think is an issue. I've created a repo on github and cloned it. Everything works fine, except it seems when I clone the repo into my Google Drive folder. Then make commands seem to blow up, e.g.

`make html` gives: 

`pelican: error: unrecognized arguments: Drive/projects/github-pages/content Drive/projects/github-pages/output Drive/projects/github-pages/pelicanconf.py
make: *** [html] Error 2`

Doing the exact same thing in my Documents folder gives no problems.

I'm guessing it's something to do with my Google Drive folder having a space in its name?

I'm running mac ox 10.11.6, pelican 3.7.0 installed via pip

Not sure if this is something you can help with or if it's even a bug??

**Comment by jkpr** [comment]
You are exactly correct, source code is here: 
https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/Makefile.in#L64

Escape the space, as in `\ `, or put quotes around the directory path. It might work to have `"$$(PELICAN)" "$$(INPUTDIR)" -o "$$(OUTPUTDIR)" -s "$$(CONFFILE)" "$$(PELICANOPTS)"` to replace the line linked to above.

**Comment by papajohn** [comment]
The suggested fix above didn't work for me, FYI.

**Comment by richyvk** [comment]
I didn't ry the fix, just renamed my Google Drive folder to Google_Drive :)

**Comment by aldoridhoni** [comment]
I have the problem with space in directory name too. I just add a quote or double quote at the usage of directory in file Makefile and develop_server.sh. Can someone make a pull request, IMHO this has to be fix in master.

**Comment by justinmayer** [comment]
Anyone care to submit a pull request to address this issue?

**Comment by justinmayer** [comment]
The file in question no longer exists, having been replaced with a Jinja2 template.
