### ISSUE TITLE
pelican-quickstart failed to start

### ISSUE THREAD

**Issue by faraco** [getpelican/pelican#2070]
System: Ubuntu 16.04
Python version: 2.7
pelican version: 3.7.0
Installation method: (pip) `sudo pip install pelican`

* Issue:running pelican-quickstart failed
    - traceback
```
$ pelican-quickstart
Traceback (most recent call last):
  File "/usr/local/bin/pelican-quickstart", line 7, in <module>
    from pelican.tools.pelican_quickstart import main
  File "/usr/local/lib/python2.7/dist-packages/pelican/tools/pelican_quickstart.py", line 52, in <module>
    'lang': locale.getlocale()[0].split('_')[0],
AttributeError: 'NoneType' object has no attribute 'split'
```

Is this a known issue?

**Comment by justinmayer** [comment]
Have you looked at existing open issues?

**Comment by faraco** [comment]
I don't see any that is similar to thi.

**Comment by justinmayer** [comment]
Dupe of #2043. Pull request #2068 is pending.

**Comment by faraco** [comment]
alright thanks

**Comment by justinmayer** [comment]
Pelican 3.7.1 has been released, containing a fix for this problem. Apologies for any frustration caused!
