### ISSUE TITLE
blog.getpelican.com down

### ISSUE THREAD

**Issue by Rentier** [getpelican/pelican#2079]
For me, http://blog.getpelican.com/ is down.

**Comment by justinmayer** [comment]
@almet: It seems the ns1.lolnet.org nameserver is not responding. Have you made any changes recently?

(Thanks for letting us know, @Rentier.)

**Comment by tjcim** [comment]
Documentation site is also down: http://docs.getpelican.com/

**Comment by begueradj** [comment]
I am developing a responsive theme, but this is at least the fourth consecutive day on which I can not access the documentation website http://blog.getpelican.com/

Have you moved the documentation elsewhere or ...?

**Comment by tjcim** [comment]
I am in the same boat.  Super frustrating.  I am not sure if there is a difference but here is some documentation that will hopefully tide you over:  http://pelican.readthedocs.io/en/stable/settings.html

**Comment by justinmayer** [comment]
Frustrating for me as well. Rest assured that I'm working on it.

**Comment by begueradj** [comment]
@tjcim That is wonderful ! Thank you very much !

**Comment by avaris** [comment]
You can always [build the docs](https://github.com/getpelican/pelican/blob/master/docs/contribute.rst#building-the-docs) from source.

**Comment by begueradj** [comment]
@justinmayer Thank you :) I asked twice in StackOverflow Python chat room about this issue, but did not get answer. For the moment, the link provided by your colleague above is just nice for me, but other people working on Pelican may not know about the link above if they do not land on this page. Thank you for the good job and help you are providing.

**Comment by begueradj** [comment]
@avaris Very interesting, thank you very much.

**Comment by justinmayer** [comment]
@begueradj: Please try the [Pelican IRC channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel) next time.  :smile:

Docs and main site should be back up.
