### ISSUE TITLE
Tips-n-tricks on wiki is outdated

### ISSUE THREAD

**Issue by a3nm** [getpelican/pelican#2081]
Hello,

I think that <https://github.com/getpelican/pelican/wiki/Tips-n-Tricks> is outdated: it talks about using MD_EXTENSIONS, but I think this is now called MARKDOWN and used differently in 3.7.0 (cf <http://docs.getpelican.com/en/3.7.0/settings.html>), so it should probably be updated. (Not doing it myself because I'm not sure of how exactly to do it.)

Thanks!

**Comment by ix5** [comment]
I [updated it](https://github.com/getpelican/pelican/wiki/Tips-n-Tricks/_compare/aea882ccc6fef4c8b21f3068c32551d259a0c092...e4a7d64b2420d9d4ff6d1aac80ca96b6139270e2), ran into this myself. Hope it helps, @a3nm 
Please remember to mark this issue as closed if your problem is resolved, as this keeps the issue tracker clean.

**Comment by a3nm** [comment]
Thanks for the update @ix5! However I'm confused by something: the page says "Markdown does allow instances of extension classes to be passing in rather than the string names of the extensions", but the example config snipped afterwards is passing the string names of the extensions rather than instances, isn't it? Shouldn't this be updated as well? Thanks!

**Comment by ix5** [comment]
Yes, you are right. You do not need to import the markdown extension classes in your `pelicanconfig.py` any more.

**Comment by a3nm** [comment]
OK, I understand. I have tried to rephrase accordingly. Everything looks good to me now, so I am closing. Thanks for your help!

**Comment by avaris** [comment]
Just to make it clear. It's not really about `pelican`, rather about the `python-markdown`. [As of 2.6](https://pythonhosted.org/Markdown/release-2.6.html#extension-configuration-as-part-of-extension-name-deprecated), passing configs to built in extensions via a string is deprecated. Before that it was possible to pass, say, `'codehilite(css_class="foo")'` to extensions and it would work. After 2.6, you either needed to use `extension_configs` (which wasn't possible with the old setting `MD_EXTENSIONS`) or import the extension, create an instance with the settings and use that instead. And that's the main reason for the switch to the new `MARKDOWN` setting. You can still do that (passing an extension instance to `'extensions'`), by the way.

**Comment by a3nm** [comment]
@avaris: Thanks for the explanation! I think it would be good to add this clarification to the wiki page as well. :)
