### ISSUE TITLE
Makefile issue after vanilla install of Pelican 3.7.1

### ISSUE THREAD

**Issue by Bridouz** [getpelican/pelican#2087]
Hi,

I wanted to test Pelican 3.7.1 but after the installation (following the doc) I have a strange issue when using _make_

`CRITICAL: AttributeError: 'bool' object has no attribute 'lstrip'
make: *** [Makefile:65: html] Error 1
`

**Comment by avaris** [comment]
@Bridouz can you show the output of `DEBUG=1 make html`?

**Comment by Bridouz** [comment]
hmmm, I just cleaned up the directory and recreated a fresh blog and everything seems to work...
