### ISSUE TITLE
Injecting metadata into `STATIC_SAVE_AS`

### ISSUE THREAD

**Issue by NoiSek** [getpelican/pelican#2088]
I would like to have Pelican generate additional metadata when reading static files, such that I could do something arbitrary like:

`pelicanconf.py`
```
STATIC_SAVE_AS = 'blog/{base_directory}/files/{sub_directory}'
```

With the end result being that: 

`root/files/article-name/filename.jpg` becomes 
`root/blog/article-name/files/filename.jpg`

and also

`root/files/article-name/sub-dir/other-dir/filename.jpg` becomes 
`root/blog/article-name/files/sub-dir/other-dir/filename.jpg`

Is this currently possible with the plugin system without using monkeypatching?

As far as I understand it, this occurs in `pelican.contents.Content` which the plugin API isn't allowed to touch, meaning that the build step errors out before a Reader can be initialized.

Is there maybe a better way to go about doing this, otherwise?

**Comment by justinmayer** [comment]
@NoiSek: Were you able to find a solution to your problem here?

**Comment by NoiSek** [comment]
Not a satisfactory one, I had to monkeypatch in order to get the result I was after. 

Ideally there should be a way to specify and retrieve arbitrary fields in Pelican without having to rely on the above (in a pre-process and post-process hook).

**Comment by ingwinlu** [comment]
did you try using `PATH_METADATA`?

**Comment by justinmayer** [comment]
@NoiSek: If we can be of further assistance, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
