### ISSUE TITLE
Importing HTML/CSS/JavaScript site

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican#2089]
### 1. Briefly

Is it possible import to Pelican site, written only in HTML, CSS and JavaScript?

### 2. Detail

I never use CMS or site generators, I write my static sites only in HTML, CSS and JavaScript. Now I want to use Pelican. What I must do, that quickly import my site to Pelican? My site — **<http://kristinita.ru>**, page example of my site — **<http://kristinita.ru/Sublime-Text/SashaSublime>**.

### 3. Did not help

I read documentation page [**Importing an existing site**](http://docs.getpelican.com/en/3.6.3/importer.html#examples), but in that page I see import information only about CMS.

Thanks.

**Comment by rackonnoiter** [comment]
@Kristinita, you can only import the following formats listed in the [documentation](http://docs.getpelican.com/en/stable/importer.html):
* WordPress XML export
* Dotclear export
* Posterous API
* Tumblr API
* RSS/Atom feed

A custom site, like yours, would not fall into those categories.

**Comment by justinmayer** [comment]
@Kristinita: You can use HTML as an input format, as described in the [docs](http://docs.getpelican.com/en/stable/content.html). Some customization will still be required — for example, you'll likely need to put post meta-data in the `<meta>` tags as described in the link above.

Alternatively, you can use conversion tools to convert your HTML to Markdown, using the converted Markdown as your source files.
