### ISSUE TITLE
[Question] Installing markdown extensions

### ISSUE THREAD

**Issue by ZerataX** [getpelican/pelican#2091]
I've read through the whole documentation concerning this and other resources, but I just can't seem to wrap my head around it.
So far I've put [latex.py](https://github.com/justinvh/Markdown-LaTeX) into `lib/python2.7/site-packages/
` and then added this to my `pelicanconf.py`
```python
MARKDOWN = {
    'extensions' : ['codehilite', 'extra', 'latex'],
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```
But that just results in `ModuleNotFoundError: No module named 'mdx_latex'`
How do I need to adjust this to enable this extensions?

```
python --version
Python 2.7.13
(virtualenv)
pelican --version
3.7.1
markdown.version
'2.6.7'
```

**Comment by Scheirle** [comment]
The preferred way to add extensions is by instance and not by name [1].

e.g.:
```python
from latex import MarkdownLatex

MARKDOWN = {
    'extensions' : ['codehilite', 'extra', 'meta', MarkdownLatex()],
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        # if you have nothing to configure there is no need to add a empty config
        #'markdown.extensions.meta': {}, 
    },
    'output_format': 'html5',
}
```


[1] http://pythonhosted.org/Markdown/reference.html#markdown

**Comment by ZerataX** [comment]
Thank you very much this helped me a long way and solved my problem with pelican.
For completeness I quickly want to add how I actually managed to get it working.
After adjusting the configuration as you described I got this error.
`dvipng: Fatal error, PRE does not occur first - are you sure this is a DVI file?`
But after some researching I found this thread in a [mailinglist](https://www.mail-archive.com/search?l=mnemosyne-proj-users@googlegroups.com&q=subject:%22%5C%5Bmnemosyne%5C-proj%5C-users%5C%5D+Re%5C%3A+Fixed+PATH%2C+still+no+TeX+joy%22&o=newest&f=1)

So I changed [line 112](https://github.com/justinvh/Markdown-LaTeX/blob/master/latex.py#L112) from
```python
status = call(('latex -halt-on-error -output-directory={:s} {:s}'
```
to
```python
status = call(('pdflatex -output-format=dvi -interaction=nonstopmode  -output-directory={:s} {:s}'
```
And now I finally have latex in my markdown!
