### ISSUE TITLE
adding first post 

### ISSUE THREAD

**Issue by najeex** [getpelican/pelican#2093]
hey, i am first time use pelican and i get some warning and errors...i try to add first post..
there is error i face in ubuntu..

`najeeb@najeeb:~/Documents/web$ pelican -s pelicanconf.py -o content output
WARNING: Meta tag in file /home/najeeb/Documents/web/output/authors.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./authors.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/tags.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./tags.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/archives.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./archives.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/index.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./index.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/categories.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./categories.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/testing.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./testing.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/category/paper.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping category/paper.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/author/najeeb-choudhary.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping author/najeeb-choudhary.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/output/tag/paper.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping tag/paper.html: could not find information about 'date'
Done: Processed 0 articles, 0 drafts, 0 pages and 0 hidden pages in 0.21 seconds.
`

**Comment by avaris** [comment]
You command has a problem:
```
pelican -s pelicanconf.py -o content output
```

`-o` denotes the output folder and the one without an option is the content folder. So you're trying to write your output to the `content` folder while using the `output` folder as content. It should be the other way around:
```
pelican -s pelicanconf.py -o output content
```

**Comment by najeex** [comment]
@avaris if try this **pelican -s pelicanconf.py -o output content** 

this happen..!!

> najeeb@najeeb:~/Documents/web$ pelican -s pelicanconf.py -o output content
WARNING: Meta tag in file /home/najeeb/Documents/web/content/authors.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./authors.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/content/tags.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./tags.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/content/archives.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./archives.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/content/index.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./index.html: could not find information about 'date'
WARNING: Meta tag in file /home/najeeb/Documents/web/content/categories.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
ERROR: Skipping ./categories.html: could not find information about 'date'
Done: Processed 1 article, 0 drafts, 0 pages and 0 hidden pages in 0.48 seconds.

**Comment by avaris** [comment]
@najeex your `content` folder contains the output from the previous (wrong) command. You need to clear it and have only the actual content there.

**Comment by justinmayer** [comment]
@najeex: Please let us know if you need further assistance. Better yet, please find us on the [#pelican channel](http://docs.getpelican.com/en/stable/contribute.html#the-pelican-irc-channel). 😄
