### ISSUE TITLE
pages not shown after upgrading to 3.7.1

### ISSUE THREAD

**Issue by junjiecai** [getpelican/pelican#2097]
Hi

After I upgraded pelican to 3.7.1, I met a problem and maybe that's a bug.

In pelican 3.7.1, pages html files are successfully generated in the output directory but they are not collected into PAGES variable in jinja2 template. In 3.7.1 ```{{PAGES|length}}``` has a value of 0.

This problem doesn't occur if I use 3.6.3

**Comment by ingwinlu** [comment]
http://docs.getpelican.com/en/latest/faq.html#since-i-upgraded-pelican-my-pages-are-no-longer-rendered

**Comment by junjiecai** [comment]
Thank you. It works fine now!

**Comment by colinbrislawn** [comment]
I also had this issue.

Thanks for the clear advice and easy fix!

**Comment by hartwork** [comment]
I think this may need a re-open and more fixes: Default theme `notmyidea` still uses `PAGES` [at one place](https://github.com/getpelican/pelican/blob/d6ac93a4708684cf16af8226d8b536897b44b74f/pelican/themes/notmyidea/templates/index.html#L54).

**Comment by colinbrislawn** [comment]
Good catch! 

I found that that issue has been fixed in the [main pelican-themes repo](https://github.com/getpelican/pelican-themes/blob/master/notmyidea-cms/templates/index.html).

Maybe we could replace the included `pelican/themes/notmyidea` with a git submodule link to the fully updated pelican-themes repo. This would stay up to date, and give users many more choices.

Thoughts?

**Comment by hartwork** [comment]
Probably the right direction but I suspect it's a bigger move? It would be awesome if the sub-module would be considered but still not hold back the tiny fix this ticket needs to get the page listing back to healthy. I'll offer a pull request in a minute. Can we re-open this ticket? I lack permissions to.

**Comment by colinbrislawn** [comment]
Let's leave this ticket closed and focus on updating the old themes that are using depreciated the depreciated `pages`. After all, the issue is with the theme(s), not with pelican itself.

They will merge and fix this in a few days. No need to rush.

**Comment by hartwork** [comment]
It's the default theme so I don't really agree that it's just a theme.
