### ISSUE TITLE
Reason that Draft articles are read twice?

### ISSUE THREAD

**Issue by brownnrl** [getpelican/pelican#2098]
Hello!  Thank you very much for all the work on Pelican!  It's a great tool.

I'm probably doing something that I shouldn't, which is holding some stateful information in RST directives.  I like to know how many times each directive is hit when a page is generated for generally nefarious purposes.

Everything works wonderfully for regular articles, but drafts gave me a bit of trouble because it turns out they are processed twice.  I traced the behavior to the method ```generate_context``` in ```generators```, which has the lines

``` python
                # TODO needs overhaul, maybe nomad for read_file
                # solution, unified behaviour
                try:
                    article_or_draft = self.readers.read_file(
                        base_path=self.path, path=f, content_class=Article,
                        context=self.context,
                        preread_signal=signals.article_generator_preread,
                        preread_sender=self,
                        context_signal=signals.article_generator_context,
                        context_sender=self)
                except Exception as e:
                    logger.error(
                        'Could not process %s\n%s', f, e,
                        exc_info=self.settings.get('DEBUG', False))
                    self._add_failed_source_path(f)
                    continue

                if not is_valid_content(article_or_draft, f):
                    self._add_failed_source_path(f)
                    continue

                if article_or_draft.status.lower() == "published":
                    pass
                elif article_or_draft.status.lower() == "draft":
                    article_or_draft = self.readers.read_file(
                        base_path=self.path, path=f, content_class=Draft,
                        context=self.context,
                        preread_signal=signals.article_generator_preread,
                        preread_sender=self,
                        context_signal=signals.article_generator_context,
                        context_sender=self)
```

So the article is read, with an exception handling mechanism which passes on it anyway and then if it is in a published state, we continue.  However, if it's not in a published state, we end up reading the same article again.

Before I rework my plugin to account for this double read, I was just curious if this was the desired behavior?  It seems at first glance that the elif conditional block is redundant?

**Comment by brownnrl** [comment]
Oh, I think I see now that I write the issue... the ```content_class``` is ```Article``` to start, but you can't get the status until after you read it.  So you have to read it twice, once to tell that it is a draft, and then a second time to pass the correct ```content_class``` parameter.

**Comment by avaris** [comment]
Correct. And, no, it's not the *desired* behavior, but it's the behavior we have now. It wasn't worth to introduce somewhat ugly code to optimize it since people don't tend to have many drafts. Having said that, it's pretty likely that it'll be *fixed* in a later release.

**Comment by brownnrl** [comment]
Understood.  I used the context signal and knowledge of the twice over read to fix the bug I encountered on my end.  So up to you if you want to close the issue, I'll keep a look out for the change in behavior if there is one in the future.  Thank you again for Pelican.

**Comment by ingwinlu** [comment]
the solution is to let the inheritance build the other way round as not all drafts are valid articles, but all articles are valid drafts.

so read it as draft first and write a copy constructor that builds an article out of it.

**Comment by ingwinlu** [comment]
@justinmayer should be resolved via https://github.com/getpelican/pelican/commit/089b46b7eb86cb55491d3c8e8bccb956b6dceeff

**Comment by justinmayer** [comment]
Thanks, Winlu!
