### ISSUE TITLE
jinja2 alerts when use bootstrap3

### ISSUE THREAD

**Issue by crazy-canux** [getpelican/pelican#2101]
![capture](https://cloud.githubusercontent.com/assets/14313415/22641588/4e1d3ab6-ec92-11e6-86b4-c385b3436f0b.PNG)

**Comment by avaris** [comment]
See getpelican/pelican-themes#460

**Comment by justinmayer** [comment]
@crazy-canux: Theme-related issues should always be reported in the themes repo.

Thanks to @avaris for pointing to the relevant issue there.
