### ISSUE TITLE
ImportError: No module named pelican.server

### ISSUE THREAD

**Issue by crazy-canux** [getpelican/pelican#2102]
Hello,
      I use virtualenv for pelican, and I want to use fab, but got this error.
      I can use make, but fab is unavaliable.
      Can someone help?

 $ fab clean                                                                          
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 658, in main
    docstring, callables, default = load_fabfile(fabfile)
  File "/usr/lib/python2.7/dist-packages/fabric/main.py", line 165, in load_fabfile
    imported = importer(os.path.splitext(fabfile)[0])
  File "/home/chengca/myCode/blog_pelican/fabfile.py", line 8, in <module>
    from pelican.server import ComplexHTTPRequestHandler
ImportError: No module named pelican.server

 $ pip list                                    
argparse (1.2.1)
blinker (1.4)
cryptography (1.7.2)
docutils (0.13.1)
enum34 (1.1.6)
Fabric (1.13.1)
feedgenerator (1.9)
idna (2.2)
ipaddress (1.0.18)
Jinja2 (2.9.4)
Markdown (2.6.7)
MarkupSafe (0.23)
paramiko (2.1.1)
pelican (3.7.1)
pip (1.5.4)
pyasn1 (0.2.2)
Pygments (2.1.3)
python-dateutil (2.6.0)
python-gettext (3.0)
pytz (2016.10)
setuptools (34.1.1)
six (1.10.0)
Unidecode (0.04.20)
wsgiref (0.1.2)

**Comment by radoeka** [comment]
Same over here:
output> python -m pelican.server
/usr/bin/python: No module named pelican


This is a new installation using openSUSE rpms (python3-pelican)

This works:
# pelican content
Done: Processed 1 article, 0 drafts, 0 pages and 0 hidden pages in 0.23 seconds.

What's wrong, why is the webserver not started?

**Comment by ingwinlu** [comment]
make sure you use the right python environment if you have both python2 and python3 installed

**Comment by radoeka** [comment]
Indeed.  Solved by using python3 instead of just python.

**Comment by justinmayer** [comment]
Can't replicate. Please feel free to re-open if needed.

**Comment by egberts** [comment]
I ran into this problem.

And I've attributed this to some old Python modules installed under `/usr/lib/python3` AND `/usr/local/lib/python3`.  

Cleared out both of those directories and reinstalled all needed modules (which ended up in their latested `/usr/lib/python3.7` and `/usr/local/lib/python3.7`.

That fixed it for me.
