### ISSUE TITLE
Summary is sliced from content

### ISSUE THREAD

**Issue by honmaple** [getpelican/pelican#2105]
I usually write summary just copy some text from content ,so it's useful to set summary is sliced from content.
I try to achieve it  

**pelican/readers.py 291 line**
```
class MarkdownReader(BaseReader):
    ......
    def read(self, source_path):
        """Parse content and metadata of markdown files"""

        self._source_path = source_path
        self._md = Markdown(**self.settings['MARKDOWN'])
        with pelican_open(source_path) as text:
            content = self._md.convert(text)

        if hasattr(self._md, 'Meta'):
            metadata = self._parse_metadata(self.set_header(text))
        else:
            metadata = {}
        return content, metadata

    def set_header(self, text):
        '''set summary'''
        x = self._md.Meta
        if 'summary' not in x.keys() or (set(x['summary']) ^ set([''])):
            summary = text[:self.settings['SUMMARY_MAX_LENGTH']]
            x['summary'] = [summary]
        return x
```

Can it added to source code?

**Comment by avaris** [comment]
`pelican` already does that?

> `SUMMARY_MAX_LENGTH = 50`
> When creating a short summary of an article, this will be the default length (measured in words) of the text created. This only applies if your content does not otherwise specify a summary. Setting to None will cause the summary to be a copy of the original content.

**Comment by honmaple** [comment]
Thank you for your reply,I have paid attention to the description,
and I have set  `SUMMARY_MAX_LENGTH = 50` but it couldn't work,so I modified pelican source code.
but I found it's my problem just now,my file header is 
```
Title: title
Author: honmaple
Date: 2016-12-11
Category:Python
Tags:python
Slug: title
Summary:

```
the **Summary** return **''**
Now I can use pelican better,thank you.
