### ISSUE TITLE
`TAG_FEED_ATOM = 'label.{slug}.atom.xml'` breaks Pelican

### ISSUE THREAD

**Issue by MinchinWeb** [getpelican/pelican#2106]
When defining *_URL and *_SAVE_AS settings, `{slug}` replacements are valid. That is to say the following are valid:

```
TAG_URL = 'label/{slug}/'
TAG_SAVE_AS = 'label/{slug}/index.html'
```

However, if the same form is tried on RSS/Atom feed name settings, Pelican breaks with a critial error. That is to say, the following (which would follow from the above) is NOT valid:

```
TAG_FEED_ATOM = 'label.{slug}.atom.xml'
```

Instead, `%s` substitution must be used. That is to say, the following is valid:

```
TAG_FEED_ATOM = 'label.%s.atom.xml'
```

This seems to be the case for all RSS/Atom feed name settings.

Is it possible to get feed name settings to support `{}` substitution, to match *_URL and *_SAVE_AS settings?

**Comment by justinmayer** [comment]
@MinchinWeb: Were you able to find a solution to your problem here?

**Comment by MinchinWeb** [comment]
@justinmayer I was able to use the `%s` notation to do what I wanted, but I was hoping that the `{slug}` notation could be more universally implemented.

**Comment by avaris** [comment]
It is possible, yes, if someone is willing to implement it :).

**Comment by justinmayer** [comment]
@MinchinWeb: To that end, is that something you would like to help implement?

**Comment by MinchinWeb** [comment]
@justinmayer : sure, I can be helpful. Can you point me to the code sections that process `TAG_URL` and `TAG_FEED_ATOM`?

**Comment by justinmayer** [comment]
@MinchinWeb: I'm not at my desk at the moment, but repository search should indicate that:

https://github.com/getpelican/pelican/search?q=TAG_URL
https://github.com/getpelican/pelican/search?q=TAG_FEED_ATOM

**Comment by avaris** [comment]
It's [here](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L292)

**Comment by justinmayer** [comment]
Hi @MinchinWeb. Any update on this endeavor?

**Comment by MinchinWeb** [comment]
@justinmayer Much delayed, but check out #2383!

I never could find the code that `TAG_URL` uses, but I updated the code for all the `FEED` settings. Note that this is a breaking change: there is no parallel support for `%s` formatted strings (can Python transparently/easily support `%s` and `{slug}` formatting at the same time? I've never even heard of someone trying...).

Documentation and new project template have both been updated.

I'm not certain how to set up testing locally for the project, so it will be a little publicly messy as I run the tests through Travis.

**Comment by MinchinWeb** [comment]
I got testing set up locally, but because I'm on Windows, a full half (124 of 213 tests) fail, many because of path matching issues...

**Comment by MinchinWeb** [comment]
(most of the failing test above were actually because `unidecode` wasn't installed...)
