### ISSUE TITLE
Miss last line when push to github.

### ISSUE THREAD

**Issue by crazy-canux** [getpelican/pelican#2108]
Test on my local workstation, everything is ok.
But after push to github, and check the website, I can not see the last line on every page.

Anybody konws what's going on?

http://canuxcheng.com/

I mean I can not see the last line in every blog, and even I can not see the last article in the catetory page.

**Comment by ssteinerx** [comment]
If it's working locally then it would seem that Pelican is generating the correct output.

I don't think this is a Pelican issue.

**Comment by crazy-canux** [comment]
Sure, it's a theme issue.
I already fix it.
