### ISSUE TITLE
tutorial and immediately a bummer on Windows

### ISSUE THREAD

**Issue by denfromufa** [getpelican/pelican#2109]
This does not work in Windows:

```
C:\Users\denis>mkdir -p ~/projects/yoursite
The syntax of the command is incorrect.
```

http://docs.getpelican.com/en/stable/quickstart.html

**Comment by sm1th** [comment]
That is not a Windows path... Windows paths use backslashes.. See your command prompt: "C:\Users\denis"

**Comment by justinmayer** [comment]
There seem to be at least a few [Windows-centric articles on Pelican](https://encrypted.google.com/search?hl=en&q=pelican%20static%20windows). If you learn something from those that are applicable to the project/docs, please re-open this issue.

**Comment by khorn** [comment]
Also mkdir on Windows doesn't have a -p switch, and won't expand "~" to the user's directory.

The poster's point is that the tutorial only includes a command that works on Unix-y systems, and a Windows equivalent would be nice.

The Windows equivalent is something like:
```
mkdir %USERPROFILE%\projects\yoursite
```

**Comment by justinmayer** [comment]
Given the low number of folks in the Pelican community that use Windows, I think it's unlikely that a Windows-specific documentation overhaul is forthcoming.

Moreover, Windows 10 now has the ability to run a Bash prompt. 🤓

**Comment by denfromufa** [comment]
pelican trove classifiers on PYPI show "OS Indepedent", but tutorial depends on *nix. Win10 is not yet dominant, people still use Win7 a lot. Even if bash prompt is available, not everyone will open it by default or at all.

Anyway the pelican is working on Windows (haven't checked deployment yet), but the tutorial is not useful to novice users on Windows.
