### ISSUE TITLE
Output doesn't load directly in browser

### ISSUE THREAD

**Issue by mixmastamyk** [getpelican/pelican#2112]
As a new user I was disappointed to find that when loading the `output/index.html` in my browser, the content is not styled.  The culprit is this line in the output that prevents the css from loading:

```html
        <link rel="stylesheet" href="/theme/css/main.css" />
                                     ^
```

The forward slash at the beginning of the path prevents the theme from working from a relative folder.   When removed, things work as expected.

```
> pelican --version
3.7.1
```

**Comment by mixmastamyk** [comment]
Just found 

```
RELATIVE_URLS = False
```

In the conf file, perhaps it should be default?

**Comment by justinmayer** [comment]
That's unlikely to become the default, as it can produce unexpected results for folks who don't know what they are doing. You can compare the output with the setting as True vs. False to see why.

As mentioned in the docs, output should generally be served via `python -m pelican.server`  and not via the `file:///` scheme.

**Comment by mixmastamyk** [comment]
Thanks for the reply.  True was broken, while False works.  ;)  Is there something else I haven't considered?

Also, if I ever need to move the site from / to /blog/ or what have you, relative FTW.

I've got a lot of tooling from using Sphinx already, but pelican wants me to do things its way.  Not the end of the world, but not what I expected.  I like to start from a primitive "hello world" state and work my way up.
