### ISSUE TITLE
notmyide theme missing classes for rst figures

### ISSUE THREAD

**Issue by mixmastamyk** [getpelican/pelican#2113]
Hi,

```rst
.. figure:: {filename}/images/foo.jpg
    :align: right
    :figwidth: 30%

    Caption
```

Looks like the default theme is missing important classes to support figures, such as align-right (float: right)  and caption, so it does not align or float correctly.  In addition the img tag needs a width: 100% to fill the figure as it is not the right size.

**Comment by justinmayer** [comment]
Hi @mixmastamyk. Thanks for bringing this up. Is this something you would like to help address?

**Comment by mixmastamyk** [comment]
Sure, though I don't know much right now, just started with pelican last night.  But, if you can point me to the right css file I'll be happy to add a few classes.

**Comment by justinmayer** [comment]
I imagine `main.css` is what you're looking for.

**Comment by mixmastamyk** [comment]
Thanks, made request.
