### ISSUE TITLE
About blog SITELOGO

### ISSUE THREAD

**Issue by chenjiandongx** [getpelican/pelican#2116]
I want to know how can I set blog website logo,like ![](http://p1.bpimg.com/587386/89d97182471d7418.png),I put a pic logo.jpg in content\images\logo.jpg,and modify pelicanconf.py ,![](http://p1.bpimg.com/587386/0516ea877c07ae8d.png) , exec 'pelican content -s e:\blog\pelicanconf.py' in cmd,but it does not work,still like ![](http://p1.bpimg.com/587386/130f03de87ec2942.png) 
Can guys help me ? BTW,don't care my poor English.

**Comment by pawelad** [comment]
You're talking about a site favicon, not a logo in Pelican sense. These links should help you set up a favicon:
- http://stackoverflow.com/questions/31270373/how-to-add-a-favicon-to-a-pelican-blog
- https://en.wikipedia.org/wiki/Favicon

**Comment by chenjiandongx** [comment]
thanks,I do as you say and it work.

**Comment by pawelad** [comment]
Glad I could help : )
Also, you can close the issue to let Pelican team know that it's resolved.
