### ISSUE TITLE
[Question] How to disable some warnings in console output?

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican#2119]
### 1. Briefly

I don't find, how I can disable warnings in console output.

### 2. Detail

For example, I have `SashaWarning.md` file in my content folder. Part of content of this file:

    <img src="http://i.imgur.com/gQywm8B.png" alt="">

If I run pelican content command in my terminal, I get output:

```
WARNING: Empty alt attribute for image gQywm8B.png in D:\Kristinita.bitbucket.org\content\SashaWarning.md
```

How I can disable this warning?

### 3. Did not help

1. I don't find answer in Google, Pelican documentation and in issues of this repository.

### 4. Do not offer

1. Yes, I know, that better to fill the value of alt attribute. This is an example. Please, don't tell me, that I need to fill value of alt attribute.

Thanks.

**Comment by avaris** [comment]
It is [documented](http://docs.getpelican.com/en/stable/settings.html#logging).

**Comment by Kristinita** [comment]
Thanks, it works for me!
