### ISSUE TITLE
URL builds incorrectly, adds an extra hash and slug

### ISSUE THREAD

**Issue by lianhuilui** [getpelican/pelican#2121]
I'm having this issue only on the server, but the files are exactly the same as local.

My URL configuration is: ARTICLE_URL = '{slug}/'
BUT, it is showing as `site-url/slug#slug` where it should be just `site-url/slug`

Same pelican version (3.6.3), but different python versions:
Server: python version 2.7.6 (doesn't work)
Local: python version 2.7.9 (works)

SO link: https://stackoverflow.com/questions/42868333/why-is-pelican-static-site-generator-adding-hash-and-slug-in-url

**Comment by ingwinlu** [comment]
where is it showing? and what theme?

**Comment by Bridouz** [comment]
I can assume by looking at your profile that you forked Flex theme and you light have this issue with that theme enabled.

It's normal with Flex theme that URLs end with #foo. The function is mainly here for mobile browsing and the capacity to jump directly to the post beginning and thus, do not show the headerbar.

**Comment by lianhuilui** [comment]
I had been trying with different versions of python and different machines..
Finally found what you guys had been trying to say all along: the theme (yes, Flex) was adding the #hash. I had forgotten that I had removed it from the theme locally.

**Comment by lianhuilui** [comment]
Thank you Bridouz for pointing out why the hash is there. I guess it's function over nice looking URLs.
