### ISSUE TITLE
[Question] Disable rendering some md and html files

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican#2123]
### 1. Briefly

I don't find, how I can to disable rendering some files with `md` and `html` extensions.

### 2. Detail

I use Pelican and write my articles use Markdown markup. For example, [**I want to create custom 404 page in GitHub Pages**](https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/). I need to have 2 files in root directory of my site: `404.md` and `404.html`. I create these files in my `content` folder → I run `pelican content` command → I get output.

```c++
D:\Kristinita>pelican content
WARNING: Meta tag in file D:\Kristinita\content\404.html does not have a 'name' attribute, skipping. Attributes: http-equiv="X-UA-Compatible", content="IE=edge"
ERROR: Skipping .\404.md: could not find information about 'title'
```

### 3. Example of expected behavior

I set in `pelicanconf.py`:

```python
NOT_RENDERING = ['404.md', '404.html']
```

I run `pelican content` → `404.md` and `404.html` files don't have modifications in output.

### 4. Did not help

1. I set in `pelicanconf.py` file:

```python
STATIC_PATHS = ['']
```

Files with other extension, exclude `md` and `html`, copy to the output directory without modification, warnings and errors, but it no work for `md` and `html` files.

2. I use “hack” — I write extensions in UPPERCASE. For example, I create files `404.MD` and `404.HTML` files instead of `404.md` and `404.html`. But I don't get custom 404 page in GitHub Pages with UPPERCASE extensions.
3. I find `OUTPUT_SOURCE` setting [**in documentation**](http://docs.getpelican.com/en/latest/settings.html?highlight=OUTPUT_SOURCES#basic-settings) → I set:

```python
OUTPUT_SOURCES = True
OUTPUT_SOURCES_EXTENSION = '.md'
```

I run `pelican content` command → I get error and warning in output, I don't get original `404.md` in output. It don't solve my problem.

Thanks.

**Comment by justinmayer** [comment]
Have you read the docs? http://docs.getpelican.com/en/stable/tips.html#custom-404-pages

**Comment by Kristinita** [comment]
I'm sorry, I get this problem, because I set `PAGE_PATHS = ['']` in my `pelicanconf.py` file. [**I add folders as values of this setting**](https://github.com/Kristinita/KristinitaPelican/blob/master/pelicanconf.py#L96) and I solve the problem. Sorry, that I spend your time. Thanks.
