### ISSUE TITLE
Are there any solution of migration from hexo?

### ISSUE THREAD

**Issue by moreoronce** [getpelican/pelican#2131]
i've checked doc about pelican and found that some plugin could make a migration from tumblr or other website.  Are there any solution of migration from hexo (another static blog program )?

**Comment by justinmayer** [comment]
Not specifically, no. Given that Pelican supports HTML as an input source (as long as appropriate header metadata is added), perhaps that might be an option for you?

**Comment by avaris** [comment]
I'm not familiar with `hexo` but, at a quick glance, looks like it uses Markdown for input files. You should be able to use those directly with minor modification.
