### ISSUE TITLE
<br /> Support

### ISSUE THREAD

**Issue by Linuturk** [getpelican/pelican#2132]
According to this [markdown reference](https://daringfireball.net/projects/markdown/syntax#p), adding two spaces to the end of a line should result in a `<br />` tag being inserted.

Given my source file [here](https://raw.githubusercontent.com/Linuturk/www.onitato.com/master/content/articles/hush_little_baby.markdown) and the associated [GitHub preview](https://github.com/Linuturk/www.onitato.com/blob/master/content/articles/hush_little_baby.markdown), I would expect this to work when it is a draft on my site.

Unfortunately, it looks like the [published draft](http://www.onitato.com/drafts/hush-little-baby.html) is not inserting the `<br />` tag.

**Comment by ingwinlu** [comment]
report it upstream. markdown parsing is out of scope of pelican.

(also markdown is not well defined, hence different implementations might result in different output)

**Comment by Linuturk** [comment]
@ingwinlu Given the output from https://github.com/waylan/Python-Markdown/issues/561 it looks like this isn't an upstream issue. Can you help me get more information that might help us debug?

**Comment by avaris** [comment]
I do see breaks (`<br>`) in the source.

```
<p>Hush little baby, don't say a word.<br>
Daddy's gonna buy you a mockingbird.</p>
<p>If that mockingbird doesn't sing,<br>
daddy's gonna buy you a golden ring.</p>
...
```
