### ISSUE TITLE
static content not copied or found

### ISSUE THREAD

**Issue by mayou36** [getpelican/pelican#2135]
Hi all,
I tried a lot of times and fixes with my website to copy and link static content. It never worked and no one else seemed to know about it. So I tried it for a minimal example and it still does not work. More specific here:

I am using : 
  * conda-env
  * python2.7
  * pelican 3.7.1
  * on ubuntu
no themes or plugins installed

After the quickstarter (with autogenerated makefile), I created a simple structure:

content
&nbsp;&nbsp; |_static
&nbsp;&nbsp;&nbsp;&nbsp; |_test1.png  (<-actual picture)
&nbsp;&nbsp; |_first_article.rst  (<-containing a link to test1.jpg: \`not working file <{attach}/static/test1.png>\`\_)

and added STATIC_PATH = ['static'] to the pelicanconf.py.

If I run 'make publish' or 'fab build', both yield the same result: no static folder is copied to the output-directory (nor the image itself). It's the same result if I include or exclude the link in the first_article.rst, only when adding the link, I also get the error-message
WARNING: Unable to find `/static/test1.png`, skipping url replacement.

What do you think could be the problem?
Thanks for your effort!

**Comment by joshmorel** [comment]
This could just be a typo - can you try STATIC_PATHS instead (with the final S)

**Comment by mayou36** [comment]
-.- that should do the trick (cannot try atm but I wrote without S)
Thanks for your help! If that does not work I will reopen
