### ISSUE TITLE
test.pip should install tox

### ISSUE THREAD

**Issue by ssteinerx** [getpelican/pelican#2138]
While getting set up for development, the first thing I do after I've got all the project requirements set up is to run `tox` to make sure that what I've checked out is passing all of its tests before I start work.

I do not, purposely, have tox (or anything else) installed in my global Python environment.

I tried this while setting up to work on Pelican: `tox` isn't installed as a requirement.

Maybe there's some reason I don't know that tox shouldn't be installed in the current virtualenv?

If not, it's a one-line fix to `requirements/test.pip`.

If it should be there, should I do a pull request or just add this one line to my work on child themes?  I'm a big fan of "one thing per pull request" but this seems pretty minor...

**Comment by ingwinlu** [comment]
That behaviour is on purpose.

tox manages virtual environments, hence installing it with all the other 'requirements' does not make sense. Additionally we don't want to dictate what people should use to run their tests (you could also go and create a venv yourself and run tests like that).

**Comment by ssteinerx** [comment]
Ok, thanks.  

I prefer to install everything in the virtual environment but I guess that's a personal preference.

Closing.
