### ISSUE TITLE
Drop Python 3.3 Support

### ISSUE THREAD

**Issue by ssteinerx** [getpelican/pelican#2139]
I'm working on Pelican itself and the Python 3.3 tests are failing because I don't have, never have had, and am not going to have Python 3.3.  It's in "source only" mode at this point so it's a huge PITA to install.

Kind of a minor bookkeeping issue, but it's used so little (and even less i.e. not at all by the developers who are the target audience for this project) that I would think dropping it now makes sense.

- It's in "source only" mode
- Hasn't been patched in over a year
- Support will completely end in a few months (Sept 2017)
- Wouldn't impact anyone
- Would speed up every `tox` run
- Would let me say that all tests pass without a 3.3 caveat 😺 .

**Comment by justinmayer** [comment]
I agree that it's time to drop official support for Python 3.3. Any opinions from @getpelican/reviewers on this topic?

**Comment by ingwinlu** [comment]
if it is not just cutting 3.3 tags from the test environment and setup.py, i.e. also remove any 3.3 traces in the code that we might have in there...

**Comment by hugovk** [comment]
Python 3.3 support ends in 10 days.
 
https://en.wikipedia.org/wiki/CPython#Version_history

**Comment by avaris** [comment]
Source-wise, I think [`test_testsuite.py`](https://github.com/getpelican/pelican/blob/master/pelican/tests/test_testsuite.py#L12) has the only 3.3 specific piece of code apart from documentation.

**Comment by justinmayer** [comment]
Thanks, Avaris. I removed that reference in the CONTRIBUTING docs.

Anyone want to submit a pull request that removes Python 3.3 references from the test environment, setup.py, and any other needed places?

**Comment by oulenz** [comment]
The documentation still says under `Installing Pelican` that `Pelican currently runs best on Python 2.7.x and 3.3+; earlier versions of Python are not supported.` Just wanted to point this out because I was trying to get the tests to work under 3.3 before I saw this. (I can't install Pelican under 3.3 because `feedgenerator` requires 3.4.)

**Comment by jorgesumle** [comment]
Actually the documentation from the file `docs/install.rst` says this:

> Pelican currently runs best on Python 2.7.x and 3.4+; earlier versions of Python are not supported.

The text you quoted is not in the development version of Pelican, so I suppose you must have confused looking at some outdated version of the documentation.

**Comment by avaris** [comment]
You need to look at the `latest` documentation: http://docs.getpelican.com/en/latest/install.html

`stable` is the last release (3.7.1) which was before these changes.

**Comment by oulenz** [comment]
You are absolutely right. I think I was redirected to an older version by
Google. I apologise for the noise.

16. feb. 2018 4.14 p.m. skrev "Jorge Maldonado Ventura" <
notifications@github.com>:
