### ISSUE TITLE
[v3.7.1]CRITICAL: AttributeError: 'list' object has no attribute 'setdefault'

### ISSUE THREAD

**Issue by ZoomQuiet** [getpelican/pelican#2140]
after `pip install --upgrade pelican` , can not working:

    $ pelican content -o output -s pelicanconf.py -D
    DEBUG: Pelican version: 3.7.1
    DEBUG: Python version: 2.7.12
    DEBUG: Adding current directory to system path
    DEBUG: Temporarily adding PLUGIN_PATHS to system path
    DEBUG: Loading plugin `_plugins.sitemap`
    DEBUG: Registering plugin `_plugins.sitemap`
    DEBUG: Loading plugin `_plugins.extract_toc`
    DEBUG: Registering plugin `_plugins.extract_toc`
    DEBUG: Restoring system path
    CRITICAL: AttributeError: 'list' object has no attribute 'setdefault'
    Traceback (most recent call last):
      File "/Users/zoomq/.pyenv/versions/dama2712/bin/pelican", line 11, in <module>
        sys.exit(main())
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/__init__.py", line 394, in main
        readers = Readers(settings)
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/readers.py", line 471, in __init__
        self.readers[fmt] = reader_class(self.settings)
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/readers.py", line 250, in __init__
        settings.setdefault('extension_configs', {})
    AttributeError: 'list' object has no attribute 'setdefault'

and my pyenv installed pip:

    Package                            Version    
    ---------------------------------- -----------
    appdirs                            1.4.3      
    appnope                            0.1.0      
    argh                               0.26.2     
    attrs                              16.3.0     
    backports-abc                      0.5        
    backports.shutil-get-terminal-size 1.0.0      
    beautifulsoup4                     4.5.3      
    bleach                             2.0.0      
    blinker                            1.4        
    bs4                                0.0.1      
    certifi                            2017.1.23  
    cffi                               1.9.1      
    cheroot                            5.4.0      
    CherryPy                           10.2.1     
    click                              6.7        
    configparser                       3.5.0      
    constantly                         15.1.0     
    cryptography                       1.6        
    cssselect                          1.0.0      
    decorator                          4.0.11     
    docopt                             0.6.1      
    docutils                           0.12       
    ecdsa                              0.13       
    entrypoints                        0.2.2      
    enum34                             1.1.6      
    Fabric                             1.12.0     
    feedgenerator                      1.9        
    fmovice                            0.1.0      
    functools32                        3.2.3.post2
    future                             0.16.0     
    Glances                            2.7.1      
    html5lib                           0.999999999
    idna                               2.1        
    incremental                        16.10.1    
    ipaddress                          1.0.17     
    ipykernel                          4.6.1      
    ipython                            5.3.0      
    ipython-genutils                   0.2.0      
    ipywidgets                         6.0.0      
    Jinja2                             2.7.3      
    jsonschema                         2.6.0      
    jupyter                            1.0.0      
    jupyter-client                     5.0.1      
    jupyter-console                    5.1.0      
    jupyter-core                       4.3.0      
    livereload                         2.5.1      
    lxml                               3.6.4      
    Markdoc                            0.6.6      
    Markdown                           2.4.1      
    MarkupSafe                         0.23       
    mistune                            0.7.4      
    mkdocs                             0.16.2     
    nbconvert                          5.1.1      
    nbformat                           4.3.0      
    notebook                           5.0.0      
    ordereddict                        1.1        
    packaging                          16.8       
    pandocfilters                      1.4.1      
    paramiko                           1.17.2     
    parsel                             1.1.0      
    pathlib2                           2.2.1      
    pathtools                          0.1.2      
    pelican                            3.7.1      
    pexpect                            4.2.1      
    pickleshare                        0.7.4      
    Pillow                             3.4.2      
    pip                                9.0.1      
    portend                            1.8        
    prompt-toolkit                     1.0.14     
    psutil                             4.3.1      
    ptyprocess                         0.5.1      
    pyasn1                             0.1.9      
    pyasn1-modules                     0.0.8      
    pycparser                          2.17       
    pycrypto                           2.6.1      
    PyDispatcher                       2.0.5      
    PyGithub                           1.32       
    Pygments                           1.6        
    pyOpenSSL                          16.2.0     
    pyparsing                          2.2.0      
    python-dateutil                    2.5.3      
    python-jose                        1.3.2      
    pytz                               2015.7     
    PyYAML                             3.11       
    pyzmq                              16.0.2     
    qtconsole                          4.3.0      
    queuelib                           1.4.2      
    requests                           2.13.0     
    scandir                            1.5        
    Scrapy                             1.2.1      
    service-identity                   16.0.0     
    setuptools                         35.0.0     
    simiki                             1.6.0.1    
    simplegeneric                      0.8.1      
    singledispatch                     3.4.0.3    
    six                                1.10.0     
    smartypants                        1.8.6      
    tempora                            1.6.1      
    terminado                          0.6        
    testpath                           0.3        
    tornado                            4.4.2      
    traitlets                          4.3.2      
    Twisted                            16.5.0     
    typogrify                          2.0.7      
    tzlocal                            1.2        
    Unidecode                          0.4.19     
    w3lib                              1.16.0     
    watchdog                           0.8.3      
    wcwidth                            0.1.7      
    webencodings                       0.5.1      
    WebOb                              1.7.2      
    wheel                              0.29.0     
    widgetsnbextension                 2.0.0      
    zope.interface                     4.3.2

**Comment by ingwinlu** [comment]
update/disable plugins and try again

**Comment by ZoomQuiet** [comment]
@ingwinlu thanks suggest;

- my pelicanconf.py is:
    + https://gist.github.com/ZoomQuiet/5f1cfc7d29548e42c223f92ded463184
- try:
    + upgrade from https://github.com/getpelican/pelican-plugins
    + or cancel all plugins

error message is same:

    $ pelican content -o output -s pelicanconf.py -D
    DEBUG: Pelican version: 3.7.1
    DEBUG: Python version: 2.7.12
    DEBUG: Adding current directory to system path
    DEBUG: Temporarily adding PLUGIN_PATHS to system path
    DEBUG: Restoring system path
    CRITICAL: AttributeError: 'list' object has no attribute 'setdefault'
    Traceback (most recent call last):
      File "/Users/zoomq/.pyenv/versions/dama2712/bin/pelican", line 11, in <module>
        sys.exit(main())
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/__init__.py", line 394, in main
        readers = Readers(settings)
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/readers.py", line 471, in __init__
        self.readers[fmt] = reader_class(self.settings)
      File "/Users/zoomq/.pyenv/versions/2.7.12/envs/dama2712/lib/python2.7/site-packages/pelican/readers.py", line 250, in __init__
        settings.setdefault('extension_configs', {})
    AttributeError: 'list' object has no attribute 'setdefault'

**Comment by ssteinerx** [comment]
What is your `MARKDOWN` variable set to in your settings?

It's supposed to look like this:
```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```

It doesn't, it's a list.

**Comment by ZoomQuiet** [comment]
@ssteinerx thanks, that it:

my old settings:

    #   upgraded Pelican 3.3 must self open them
    MD_EXTENSIONS = (['codehilite(css_class=highlight)'
        , 'extra', 'abbr', 'attr_list', 'def_list', 'fenced_code', 'smart_strong'
        , 'admonition', 'meta', 'tables', 'sane_lists'
        , 'toc'
    ])

i just try as:

    MARKDOWN = (['codehilite(css_class=highlight)'
        , 'extra', 'abbr', 'attr_list', 'def_list', 'fenced_code', 'smart_strong'
        , 'admonition', 'meta', 'tables', 'sane_lists'
        , 'toc'
    ])

so check about: [Settings — Pelican 3.7.1 documentation](http://docs.getpelican.com/en/stable/settings.html)

upgrade as:

    MARKDOWN = {
        'extension_configs': {
            'markdown.extensions.codehilite': {'css_class': 'highlight'},
            'markdown.extensions.extra': {},
            'markdown.extensions.meta': {},
        },
        'output_format': 'html5',
    }

it is working now.

thanks for all.
