### ISSUE TITLE
Drafts are indexed by robots

### ISSUE THREAD

**Issue by ahmetb** [getpelican/pelican#2141]
Can we add the following meta tag automatically to the `status:draft` pages?

    <meta name="robots" content="noindex, nofollow">

This would serve almost as good as a robots.txt for the unpublished content.

**Comment by justinmayer** [comment]
@ahmetb: Makes sense to me. Would you like to help us out and implement this feature?

**Comment by ahmetb** [comment]
Unfortunately I can't help due to AGPL license.

**Comment by justinmayer** [comment]
I'm confused. Why submit the issue, then?

**Comment by ahmetb** [comment]
Just because I suggest a feature it doesn't imply that I am willing to or able to implement the feature?

**Comment by rackonnoiter** [comment]
I'd be willing to give it a go with a bit of guidance. First, a couple questions:
1. Wouldn't adding a meta tag such as this usually be rendered from the template?
2. If the answer is yes, where would be a good place to to inject the tag?

**Comment by ahmetb** [comment]
I actually didn't think about it this way before. Yeah, I guess technically the template can find out if it's a template and can add a meta tag indicating that. It'd be between `<head>..</head>`.

I'll close this as this is actually up to templates to implement currently. I don't think there can be a better solution just yet. I personally created a `robots.txt` myself and placed it on the root of my domain name to prevent `[...]drafts/` from getting indexed.
