### ISSUE TITLE
Provide an exporter

### ISSUE THREAD

**Issue by rixx** [getpelican/pelican#2143]
Alongside with an importer it would be nice to have an exporter that exports all published posts (or all posts) and their metadata. I recently wrote my own export script and it was kind of painful and hacky, especially things like constructing the post's date etc.

**Comment by ssteinerx** [comment]
The input format's pretty simple and the desired output varies as much as the tools into which you might want to import the data.

I would think that importing would be best left to the tool into which you want to import the data, not something for Pelican to implement.

e.g. There's no "Export to Drupal" built into WordPress ;-).

**Comment by rixx** [comment]
No, but there could be an export to any easily processable format, eg some kind of JSON, that can be easily parsed. I didn't find the input format too comfortable to parse (sure, split on ':', then remember to re-join everything except the first part, etc), especially since I had to use pelican's `slugify`, which is also something an exporter could provide.

**Comment by justinmayer** [comment]
Even if an exporter were to be implemented, that would be best done in the form of a plugin as opposed to Pelican core. If someone wants to write and submit an exporter plugin, please do so in the Pelican Plugins repository.
