### ISSUE TITLE
import wordpress backup xml file gets "AttributeError" error

### ISSUE THREAD

**Issue by hitrust** [getpelican/pelican#2144]
> Traceback (most recent call last):
>   File "/usr/local/bin/pelican-import", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.4/dist-packages/pelican/tools/pelican_import.py", line 896, in main
>     attachments=attachments or None)
>   File "/usr/local/lib/python3.4/dist-packages/pelican/tools/pelican_import.py", line 684, in fields2pelican
>     kind, in_markup) in fields:
>   File "/usr/local/lib/python3.4/dist-packages/pelican/tools/pelican_import.py", line 148, in wp2fields
>     if item.find('status').string in ["publish", "draft"]:
> AttributeError: 'NoneType' object has no attribute 'string'

- wordpress version: 4.7.3
- pelican: 3.7.1

`pelican-import --wpfile -o content  ~/-.wordpress.2017-03-14.xml`

part of xml file cotent import sucessfully

**Comment by bandantonio** [comment]
I had the same issue previously and solved it by exporting `published` posts, `pages` and `drafts` in 3 separate `.xml` files. After that I was able to run `pelican-import` three times accordingly and all my content was imported successfully.

**Comment by hitrust** [comment]
thanks a lot, @bandantonio! I'll try it out

**Comment by hitrust** [comment]
After I tried above way， the same error still accoured,  so I just leave it behind,  recently I am trying to solve it, and I located the issue in the 'content',  and I also think the 'status' need to be adjusted. now I imported totally successfully , just depended on some manual adjust。so the **pelican_import.py** still need to be modified properly,  someday maybe I'll try.

**Comment by ingwinlu** [comment]
Provide an xml file that fails as an example and we can have a look at it.

**Comment by hitrust** [comment]
about at line 873-874, seems like character encoding issue.

![2017-08-17_173914](https://user-images.githubusercontent.com/3360631/29406525-eaa3e15a-8373-11e7-977a-156bf35d8b9d.png)

[ed2ked2kbt-.wordpress.Part_01.zip](https://github.com/getpelican/pelican/files/1230850/ed2ked2kbt-.wordpress.Part_01.zip)

**Comment by avaris** [comment]
Yes, looks like an encoding issue and that messes up the xml parser in a weird way. `lxml` pretty much gave up at that point and truncated the xml.

**Comment by hitrust** [comment]
Is there a way to get rid of the weird characters by code,  cause it's a lot of labor  to find out them.
