### ISSUE TITLE
Pelican Chokes on HTML files on tags with no 'name' attribute when "itemprop" exists

### ISSUE THREAD

**Issue by swk** [getpelican/pelican#2145]
give a .html with proper meta tags for say Google+.
example:
```html
<meta itemprop="name" content="Blog" />
```

Pelican refuses to render these meta tags into the resultant HTML skipping them with the following message

WARNING: Meta tag in file .../test.html does not have a 'name' attribute, skipping. Attributes: itemprop="name", content="Blog"

The problem here lies that you arent supposed to have "itemprop" and "name" attributes at the same time...

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
