### ISSUE TITLE
Weird side-effect of REALTIVE_URLS

### ISSUE THREAD

**Issue by tobycheese** [getpelican/pelican#2152]
I wrote this short plugin to fix ipython notebook images for my theme. The weird thing is, the plugin works when RELATIVE_URLS=True and does nothing when RELATIVE_URLS=False.

```python
from pelican import signals
from bs4 import BeautifulSoup

def add_spans_around_ipynb_images(article_generator, content):
    """ add <span class="image fit"> around all images in ipython notebook
        content so that their resulting page width is not too large
    """

    if content.source_path.endswith('.ipynb'):
        soup = BeautifulSoup(content.content, 'html.parser')
        for img in soup.select("div.output_png > img"):
            span_wrapped = img.wrap(soup.new_tag("span"))
            span_wrapped['class'] = 'image fit'
        content._content = str(soup)

def register():
    signals.article_generator_write_article.connect(add_spans_around_ipynb_images)
```

The offending line seems to be `content._content = str(soup)`, everything above works independently of the RELATIVE_URLS setting.

I admit I didn't spend much time in teaching myself how to properly program a pelican plugin (documentation is a bit sparse in this respect, if I may say so), thus it's probable that I just did something weird in my plugin. But I thought 'hey, it works, let's move on' when in fact it didn't once I wanted to publish my site without relative urls.

To reproduce the issue (if it even is one):
- pelican-quickstart with pelican 3.7.1
- add to pelicanconf.py:
```
PLUGIN_PATHS = ['plugins']
PLUGINS = ['ipynb.markup', 'postprocess']
MARKUP = ('ipynb')
```
- copy above plugin (along with an __init__.py) and ipynb.markup from the official repo to plugins/
- copy an a ipython notebook with an image to content/, for example [this](https://raw.githubusercontent.com/LeiG/Applied-Predictive-Modeling-with-Python/master/notebooks/Chapter%202.ipynb)
- add a corresponding .ipynb-meta file ([Chapter 2.ipynb-meta.txt](https://github.com/getpelican/pelican/files/991171/Chapter.2.ipynb-meta.txt))
- generate once with RELATIVE_URLS = True and find the added <span> around the base64 image and once with RELATIVE_URLS = False and find that the <span> around the base64 image is now absent

Thanks for any hints.

**Comment by avaris** [comment]
Actually, the offending line is this:

```python
soup = BeautifulSoup(content.content, 'html.parser')
```

`.content` property is cached for performance reasons (as opposed to `._content`). So it's saved to that state and any subsequent calls to it will return the "unmodified" version. i.e. your replacement of `._content` at the end will have no effect.

Why it works with `RELATIVE_URLS` is a long and probably not that related topic. tl,dr; `RELATIVE_URLS` causes `.content` to be retrieved with different arguments and you don't hit the cache.

Replace the above line with:

```python
soup = BeautifulSoup(content._content, 'html.parser')
```

**Comment by tobycheese** [comment]
Hi

Thanks for the quick reply, much appreciated. While I see my mistake (first reading from `.content` but then replacing `._content`) and understand the correction you suggested, I don't get your explanation entirely. If `.content` is being cached, how can the line `content._content = str(soup)` have any effect at all?

How do `.content` and `._content` relate? Should I even use `._content` (given the leading underscore is sometimes interpreted as an indication that an object should be viewed as private)?

I made the replacement you suggested, and it is still not working with `RELATIVE_URLS = False`.

**Comment by avaris** [comment]
`.content` is a wrapper property for `._content` that does some extra stuff, like replacing the intrasite links defined with `{filename}`. Since that can be costly, we do cache it so that if you call it with same arguments it's not regenerated and the cached result is returned. So, in order to be able to replace the `._content`, `.content` shouldn't have been accessed at all.

And yes, for these reasons, plugins should work with `._content` and shouldn't touch `.content`. It's not ideal, but it's the best solution for now.

Another issue I see is that the signal you use (`article_generator_write_article`) might be too late. Some other template (like `index.html`) might have been written before which used the `.content` of articles and therefore created a cache. Try an earlier signal, like `all_generators_finalized`.

**Comment by tobycheese** [comment]
That was the hint I needed. I initially chose `article_generator_write_article` because that one receives `content` as an argument. From the documentation, I couldn't figure out how to access an articles content with signals that don't get `content` passed.

After looking at some of the existing plugins, I came up with the following, which works. Thanks!

```
from pelican import signals
from pelican.generators import ArticlesGenerator
from bs4 import BeautifulSoup

def add_spans_around_ipynb_images(article):
    """ add <span class="image fit"> around all images in ipython notebook
        content (only articles, not pages) so that their resulting page
        width is not too large
    """

    if article.source_path.endswith('.ipynb'):
        soup = BeautifulSoup(article._content, 'html.parser')
        for img in soup.select("div.output_png > img"):
            span_wrapped = img.wrap(soup.new_tag("span"))
            span_wrapped['class'] = 'image fit'
        article._content = str(soup)

def run_plugin(generators):
    for generator in generators:
        if isinstance(generator, ArticlesGenerator):
            for article in generator.articles:
                add_spans_around_ipynb_images(article)

def register():
    signals.all_generators_finalized.connect(run_plugin)
```
