### ISSUE TITLE
My blog does not recognize css

### ISSUE THREAD

**Issue by LordJhony** [getpelican/pelican#2156]
Hi..
I am making a blog with pelican using github pages and travis. Also, i am using this theme https://github.com/gilsondev/pelican-clean-blog. The problem is that my page once travis finish the integration, load my post, load the theme, but it has not any style. Just charge but without css style. 
This is my blog https://lordjhony.github.io

**Comment by ingwinlu** [comment]
> http://lordjhony.github.io/theme/css/bootstrap.css

blocked:mixed-content

your site is https, but the link to stylesheets is http

**Comment by LordJhony** [comment]
Thank you so much... I was two days searching how to resolve that issue
