### ISSUE TITLE
Invalid HTML generated when using attr_list and an empty tag

### ISSUE THREAD

**Issue by AWegnerGitHub** [getpelican/pelican#2157]
I have the following configuration settings for `MARKDOWN`:

```
MARKDOWN = {'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'codehilight code'},
        'markdown.extensions.toc': {'permalink': 'true'},
        'markdown.extensions.attr_list': {},
    },
	'output_format': 'html5',
}
```

I have the following content that I want to be converted to HTML:

```
This is a paragraph
{ itemscope itemtype="http://schema.org/Movie"}
```

Pelican generates the following block of HTML:

    <p itemscope="" itemtype="http://schema.org/Movie">This is a paragraph</p>

If I run the same content through markdown itself, I get a different block. Example:

```
import markdown
t = """This is a paragraph
{ itemscope itemtype="http://schema.org/Movie"}
"""
markdown.markdown(t, extensions=['attr_list'], output_format="html5")
```

This generates:

    <p itemscope itemtype="http://schema.org/Movie">This is a paragraph</p>

Notice the difference between the two. Pelican adds `itemscope=""` versus markdown `itemscope` without the equal sign.

How do I get Pelican to generate the HTML without the empty equals sign?

---

Versions:

 - Pelican: 3.7.1
 - Markdown: 2.6.8

**Comment by ingwinlu** [comment]
I can't reproduce this behaviour.

maybe try without plugins or post your full config.

**Comment by AWegnerGitHub** [comment]
@idning What config settings would you like to see? I've provided several that may be relevant below:

```
THEME = '../pelican-themes/elegant'
PLUGIN_PATHS = ['../pelican-plugins', 'plugins']
PLUGINS = ['neighbors', 'extract_toc', 'tipue_search', 'sitemap', 'keyboard.kb', 'series', 'post_stats']
MARKDOWN = {'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'codehilight code'},
        'markdown.extensions.toc': {'permalink': 'true'},
        'markdown.extensions.attr_list': {}
    },
    'output_format': 'html5'
}

DEFAULT_LANG = u'en'
READERS = {'html': None}
```

**Comment by justinmayer** [comment]
@AWegnerGitHub: Were you able to find a solution to your problem here?

**Comment by AWegnerGitHub** [comment]
I was not able to resolve this

**Comment by justinmayer** [comment]
@AWegnerGitHub: Perhaps consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
