### ISSUE TITLE
github pages - how to use?

### ISSUE THREAD

**Issue by denfromufa** [getpelican/pelican#2160]
Following this page: http://docs.getpelican.com/en/3.7.1/tips.html#user-pages

I do not recall the requirement to configure a git repo in the pelican demo:

```
pelican content -o output -s pelicanconf.py
Done: Processed 1 article, 0 drafts, 0 pages and 0 hidden pages in 0.38 seconds.

ghp-import output
Usage: ghp-import [OPTIONS] DIRECTORY

ghp-import: error: Not a git repository (or any of the parent directories): .git
```

**Comment by jorgesumle** [comment]
I don't know. But Gitlab pages work good for me, maybe you can copy something from my setup: https://gitlab.com/CNT-Almeria/web/

**Comment by justinmayer** [comment]
@denfromufa: Were you able to resolve your problem?

**Comment by denfromufa** [comment]
Yes, but I used Nikola, which shows go to configure git with the template.
