### ISSUE TITLE
I can not work with scss files

### ISSUE THREAD

**Issue by LordJhony** [getpelican/pelican#2166]
Hello..
In my page i am trying to use assets plugin for build scss files.
I am using in the page base.html of the theme the instruction

{% assets filters="sass, cssmin", output="css/menu.min.css", "css/menu.scss" %} <link rel="stylesheet" href="{{ SITEURL }}/{{ ASSET_URL }}"> {% endassets %}

but when i deploy the site, it shows the next issue

FilterError: sass: subprocess returned a non-success result code: 65, stdout=, stderr=Error: Invalid CSS after "0": expected expression (e.g. 1px, bold), was ";"

**Comment by justinmayer** [comment]
1. Please do not cross-post issues to multiple repositories.
2. This is a plugin-related issue, so the [other issue](https://github.com/getpelican/pelican-plugins/issues/908) you filed was in the correct place.
