### ISSUE TITLE
Resume name article in url

### ISSUE THREAD

**Issue by LordJhony** [getpelican/pelican#2167]
Hello..
Is it posible to resume name article in the url?
 I explain me. I have my blog with some articles but the title is so long, and for that the url is long to.
For example, I have and article called "CHAINS AND ITS LINKS: INTRODUCTION TO SOCIAL ENGINEERING", then the url is myblog.github.io/date/CHAINS-AND-ITS-LINKS-INTRODUCTION-TO-SOCIAL-ENGINEERING.html
I want that the url will be myblog.github.io/date/social-engineering 
is it posible get that?

**Comment by ingwinlu** [comment]
try adding slug metadata overwriting the automatically set one, i.e. slug: social-engineering.
but this can fail depending on your settings. see http://pelican.readthedocs.io/en/stable/settings.html#url-settings.

**Comment by LordJhony** [comment]
Thank you.. Your answer was very helpful.
