### ISSUE TITLE
Can't create a table

### ISSUE THREAD

**Issue by bandantonio** [getpelican/pelican#2169]
It is a really shameful question, but I tried everything I knew about Markdown syntax and still can't create even a basic table. There are some plugins for this purpose, like [this one](https://github.com/burakkose/just_table), but why should I use them, whereas Markdown supports tables out-of-the-box? Can someone help me, please?

Tried the following combinations:

```
1)
Test  | Test
----- | -----
Test  | Test
Test  | Test

2)
| Test   | Test  |
| ------ | ----- |
| Test   | Test  |
| Test   | Test  |

3)
| Test | Test |
| --- | --- |
| Test | Test |
| Test | Test |

4)
| Test   | Test  |
| :----: | :---: |
| Test   | Test  |
| Test   | Test  |

5)
| Test  | Test  | Test  |
|-------|-------|-------|
| Test  | Test  | Test  |
| Test  | Test  | Test  |
```

The result is always the same: 

| Test | Test | | --- | --- | | test | Test | | test | Test |

This issue appears both in default theme and custom. Pelican version: 3.7.1

**Comment by justinmayer** [comment]
Pelican uses the Python Markdown library. Docs for how that library handles tables: https://pythonhosted.org/Markdown/extensions/tables.html

In the future, please give folks on IRC some time to respond to your question. Helps us keep the issue clutter to a minimum. Thanks!
