### ISSUE TITLE
|filename| is not evaluated if I move article to a directory in content/

### ISSUE THREAD

**Issue by ahmetb** [getpelican/pelican#2172]
(pelican==3.7.1)

All my articles are under the default `content/` directory, however I have hundreds of articles over the period of 12 years, so I'm trying to move them to year-based directories, e.g. `content/2010/`.

For instance, I have an article called `content/2010-01-01-test.md` that has:

    ![](|filename|images/2016/08/govvv-1.gif)

This is correctly rendered with the `|filename|` evaluated.

If I move this article to `content/2010/2010-01-01-test.md` path, it still gets build and listed on my blog, however the HTML rendering does not correctly evaluate the `|filename|` tag:

    <p><img alt="" src="|filename|images/2016/08/govvv-1.gif"></p>

Any ideas why this might be the case?

**Comment by avaris** [comment]
`{filename}` (or `|filename|`) has two modes of operation:
 - absolute from content root: paths **start** with `/`. 
    (e.g.: `|filename|/path/from/content/to/file.ext`)
 - relative to the linking file: paths **doesn't start** with `/` 
    (e.g.: `|filename|path/next/to/article.ext`)

Yours is the second one and I'm guessing it should actually be first one. i.e. your file paths are relative to the content root, not the linking file. That's probably why you lose the links when you move the articles to a subfolder.

**Comment by ahmetb** [comment]
@avaris Thanks, referring to the image as absolute path (`|filename|/images/...`) solved the problem. I will close the issue.
