### ISSUE TITLE
Missing setting: ARCHIVES_URL 

### ISSUE THREAD

**Issue by DjalelBBZ** [getpelican/pelican#2173]
Hi Folks, 

There a couple of URL-related settings that work in couple
DRAFT_URL / DRAFT_SAVE_AS
ARTICLE_URL / ARTICLE_SAVE_AS
CATEGORY_URL / CATEGORY_SAVE_AS
etc.

It mainly allows to have clean url without the .html extension. 

Except for ARCHIVES_SAVE_AS which doesn't have it's equivalent ARCHIVES_URL

**Comment by ingwinlu** [comment]
https://github.com/getpelican/pelican/issues/1111
