### ISSUE TITLE
{filename} is not being rendered outside of a (...) link scope

### ISSUE THREAD

**Issue by andreagrandi** [getpelican/pelican#2175]
Hi,

this is what I'm writing in one of my articles:

```[{filename}my_page.md]({filename}my_page.md)```

This is what I expect to be rendered:

```<a href="https://mydomain.com/my_page">https://mydomain.com/my_page</a>```

This is what I get instead:

```<a href="https://mydomain.com/my_page">{filename}my_page.md</a>```

What am I doing wrong? Why **{filename}** is not being rendered inside ```[......]``` ?

**Comment by charlesfleche** [comment]
`{filename}` is replaced after the HTML code has been generated and only in html attributes that could potentially be links, as in `href=`, `src=`, … I don't think that you can render `{filename}` into `[ ]` blocks at the moment.

**Comment by voidplayer** [comment]
we need a pelican setting to add arbitrary attributes that have links

Something like ```ATTRIBUTES_WITH_LINKS```

**Comment by justinmayer** [comment]
Who would be willing to work on implementing a fix for this issue?
