### ISSUE TITLE
Getting "CRITICAL: AttributeError: 'unicode' object has no attribute 'slug'" on file

### ISSUE THREAD

**Issue by mandaris** [getpelican/pelican#2177]
I've been using an older version for a while and wanted to move everything to a clean environment to make sure that I could recover properly after a major failure.

It seems like this one file is throwing this error. I was tempted to just delete it but I wanted to know why.

[hyde_doc_sucks.md.zip](https://github.com/getpelican/pelican/files/1137675/hyde_doc_sucks.md.zip)

If possible, is there directions on how to debug in situations like this?

Sorry for the title, I was going through a phase where I didn't know how to use my big developer words to express my frustration.

**Comment by avaris** [comment]
You have
`tag: hyde`
and it should be:
`tags: hyde`

This was a bug introduced in the recent version. Normally `tag` metadata isn't anything special and would be ignored (i.e. would be left alone as a string metadata). New addition treats it will `Tag` object but it isn't.

**Comment by mandaris** [comment]
Thank you @avaris!
I've made the change and will close the issue. I hope that someone else will find this if they run into this issue.

**Comment by drummonds** [comment]
+1 Thanks

**Comment by JonathonReinhart** [comment]
This exact thing just bit me on Pelican 1.7.1. I accidentally typed `Tag` instead of `Tags`.
