### ISSUE TITLE
Default themes should not breach users' privacy

### ISSUE THREAD

**Issue by josch** [getpelican/pelican#2178]
The "notmyidea" theme includes css and javascript from third party servers. Specifically:

 - pelican/themes/notmyidea/static/css/main.css imports https://fonts.googleapis.com/css?family=Yanone+Kaffeesatz&subset=latin

 - pelican/themes/notmyidea/templates/base.html includes the script https://html5shiv.googlecode.com/svn/trunk/html5.js

It would be nice if the default themes that pelican ships would not report its usage to external services not under the user's control.

**Comment by jorgesumle** [comment]
Exacly, the code should be always in one's server. Not only for privacy, but also for reliability. There is not any guarantee that those servers will run in the future. For downloading the Google fonts, you can use [google-font-download](https://github.com/neverpanic/google-font-download).

**Comment by justinmayer** [comment]
Addressed via the linked PR.
