### ISSUE TITLE
EXTRA_PATH_METADATA doesn't accept regexes

### ISSUE THREAD

**Issue by andrew-vant** [getpelican/pelican#2180]
I was trying to apply certain metadata to all files under a given directory. Looking at the docs it seems like EXTRA_PATH_METADATA is the correct way to do this, but I couldn't find any way to specify files in a more general way than individually, e.g. giving it the folder path or a path regex doesn't work. I inquired on IRC and was told regexes aren't supported here.

I would like them to be. In my case I'm trying to apply a different style to files in that directory, but I can think of a few other use cases, e.g. it provides a way to apply status: draft to a whole folder when appropriate.

I'd be willing to work on a patch if someone can point me in the right direction.

**Comment by ingwinlu** [comment]
use 'PATH_METADATA'

**Comment by justinmayer** [comment]
@andrew-vant: If you need further assistance with this, please reach out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
