### ISSUE TITLE
Documentation and copyright date

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2182]
I have been trying to find if Pelican is free culture. I want to translate Pelican into my language, and also make a guide based on that translation, but the copyright restrictions may cause me some problems. I could only find the following line relative to the copyright of the documentation.

https://github.com/getpelican/pelican/blob/ce38e318bd4905f75c988ee930620ebcd65588c0/docs/conf.py#L20

The problem is that if we want to change it, we would need to ask every contributor ('2015, Alexis Metaireau and contributors'). Another issue is that the year is a bit outdated, but that is not very important and can be fixed easily.

**Comment by justinmayer** [comment]
Hi Jorge.

> I have been trying to find if Pelican is free culture.

I have no idea what that means. The license is clearly stated in the repository root: https://github.com/getpelican/pelican/blob/master/LICENSE

> I want to translate Pelican into my language, and also make a guide based on that translation

Can you be more specific? What is it exactly that you are trying to do?

> ...but the copyright restrictions may cause me some problems.

What restrictions? I think you might be confused about licenses vs. copyrights.

> Another issue is that the year is a bit outdated, but that is not very important and can be fixed easily.

That is not how copyright dates work. Everything I have read on this topic states that the proper treatment is to display the **year of first publication**. If that is true, all the folks who update the copyright date every year are doing things exactly backwards.

Ergo, I've made a note to myself to correct the year to 2010, the year Pelican was first published.

**Comment by jorgesumle** [comment]
> I have no idea what that means. The license is clearly stated in the repository root: https://github.com/getpelican/pelican/blob/master/LICENSE

Yes, but that is a _software license_, I didn't know it applied to the documentation too.

> What restrictions? I think you might be confused about licenses vs. copyrights.

Maybe I'm confused. Under plain copyright I can't distribute a translation. And I am not sure if Pelican has copyright. But if the AGPLv3 applies to the documentation too, then there shouldn't be any problem.

> That is not how copyright dates work. Everything I have read on this topic states that the proper treatment is to display the year of first publication. If that is true, all the folks who update the copyright date every year are doing things exactly backwards.

I thought you should write something like 2010-2016 for copyright for websites and digital resources, and that first year of publication was for books, magazines, etc. See how Emacs documentation is licensed:

> Copyright © 1985–1987, 1993–2017 Free Software Foundation, Inc.

But anyway I'm not an expert about copyright, so I'm not sure which method is the best or most valid.

**Comment by jorgesumle** [comment]
> I have been trying to find if Pelican is free culture.
>> I have no idea what that means. The license is clearly stated in the repository root: https://github.com/getpelican/pelican/blob/master/LICENSE

[I forgot to to answer this one]

You can read about it in [Wikipedia](https://en.wikipedia.org/wiki/Free_culture_movement). It's like free software, but for cultural works.

**Comment by justinmayer** [comment]
Thanks for your reply, Jorge. I am not an expert in copyright law, either. But if you want to translate Pelican's documentation and distribute that translation in an unencumbered, "libre" fashion, I can't think of any reason why you cannot. We would certainly welcome the translation, and I imagine end users would as well.

Would you please let us know if and when you publish your translation?

**Comment by jorgesumle** [comment]
Sure, I am trying to figure out how can I use Sphinx for that, and if there is a way to keep the translation up-to-date. I mean, when there is a change in the English version, be notified that I should update the Spanish version. But yes, maybe I should finish the translation, and then worry about that stuff.

**Comment by jorgesumle** [comment]
I started with the translation. Spanish speakers, you can help me if you want by submitting a pull request in the [NotABug jorgesumle/pelican-docs-es repo](https://notabug.org/jorgesumle/pelican-docs-es).
