### ISSUE TITLE
Insecure content

### ISSUE THREAD

**Issue by casouri** [getpelican/pelican#2183]
I do not know if it is gcc's problem or pelican's. On my html page the link to style sheet is `http` link instead of `https`. This causes the browser complain about insecure content and not showing css.
I generate html with `make publish`.

**Comment by justinmayer** [comment]
GCC? In any case, this is probably defined in your theme's base.html template file and is not related to Pelican itself.

**Comment by casouri** [comment]
In my base.html they are mentioned as
```
<link rel="stylesheet" href="{{ SITEURL }}/theme/css/screen.css" type="text/css" />
<link rel="stylesheet" href="{{ SITEURL }}/theme/css/pygments.css" type="text/css" />
```

Now I am a total beginner, but seems to me, it is the problem of whoever generated the html.
Do you have any ideas about which part of the process caused it?

**Comment by casouri** [comment]
I found it.
It is the `SITEURL` in the publishconf.py. I set my page url with `http`

**Comment by justinmayer** [comment]
Glad you found the problem.
