### ISSUE TITLE
Dynamically display data from a json or a yaml file

### ISSUE THREAD

**Issue by ishu3101** [getpelican/pelican#2185]
In **Jekyll**, you can dynamically display data from a json or yaml file by adding the file inside the `_data` directory and access them using the `site.data` variable, How do you do the same using **Pelican**?

for eg:

    _data
     - events.json
    _includes
    _layouts
    index.html

**index.html**

    {% for event in site.data.events %}
      {{ event.name }} - {{ event.type }}
    {% endfor %}

**Comment by justinmayer** [comment]
Pelican doesn't do this explicitly, but there are most likely existing plugins that will address this use case. Also, another option might be to read in the file data from Python code inside the settings file, assign that data to one or more variables, and then call those variables within your templates.

**Comment by ishu3101** [comment]
I checked the [pelican plugins](https://github.com/getpelican/pelican-plugins/) repository but not of the plugins does what I mentioned above.
