### ISSUE TITLE
Add the ability to access years/months/days with posts in themes

### ISSUE THREAD

**Issue by josch** [getpelican/pelican#2188]
My old blog engine (blogofile) had the feature of displaying an entry in the sidebar like this:

```
September 2011 (6)
August 2011 (3)
July 2011 (4)
June 2011 (7)
```

Clicking on these entries would show me the view of all articles in the respective month. If I'm not missing anything then it seems that creating a theme for pelican that does do something similar is not possible. Specifically, it would be nice if pelican would offer the list of years, months and days with posts in them and then the theme could link to the respective `YEAR_ARCHIVE_SAVE_AS`, `MONTH_ARCHIVE_SAVE_AS` or `DAY_ARCHIVE_SAVE_AS` page.

I'm not asking for the ability to produce something like a real calendar (that should probably go into a plugin) but just a plain list of years, months, days with posts in them would suffice to implement this feature if I'm not mistaken.

**Comment by jorgesumle** [comment]
You can do that.

![captura de pantalla de 2017-07-30 12 13 42](https://user-images.githubusercontent.com/14212780/28752468-96c69f66-7520-11e7-8890-44f0ee6a033a.png)

You should find a theme that does what you want or program it yourself.

**Comment by josch** [comment]
@jorgesumle Thanks for the tip! Do you have the part of the source handy that generated the screenshot that you pasted?

**Comment by josch** [comment]
Turns out, the theme foundation-default-colours already did what I wanted. I created a pull request against the pelican-bootstrap3 theme to support this as well. Let me link it here in case anybody else stumbles upon this: https://github.com/getpelican/pelican-themes/pull/533

Closing, since this is not a bug.

**Comment by jorgesumle** [comment]
> @jorgesumle Thanks for the tip! Do you have the part of the source handy that generated the screenshot that you pasted?

Here it is: https://notabug.org/Freak-Spot/Freak-Spot/src/master/freak-theme/templates/archives.html
