### ISSUE TITLE
How to speed up generation time with lots of static content

### ISSUE THREAD

**Issue by josch** [getpelican/pelican#2191]
Hi,

some directories in my `STATIC_PATHS` contain 125 MB of data. This means, that even with only 1 article, generating the blog takes 16 seconds. Is there a way to speed this up?

Or is it maybe possible for pelican to *not* copy over static content that didn't change at all every time I regenerate the site?

**Comment by avaris** [comment]
See #1982

**Comment by josch** [comment]
My apologies, the problem is not the 125 MB of data but the sheer *number* of files. I was using 3.7.1 before but now used the version from git and set `STATIC_CREATE_LINKS = True`. Still, generating my site takes 16 seconds. I suppose this is because pelican needs to investigate the around 10k static files.

This is fine when doing a fresh run but when using `--autoreload` there is no need to look at 10k files if only a single file changed.

I used cProfile and put the output here https://pastebin.com/n5yiCGq2 maybe you see something.

**Comment by avaris** [comment]
What I see is what you predicted. Well, I would've seen it easier if you sorted the `cProfile` output by `cumtime`, i.e. add `-s cumtime` argument to it :).

`pelican` is going over a large number of static files and `StaticGenerator.generate_output` is taking up the 
bulk of processing time:
```1   0.165   0.165   12.893  12.893  generators.py:723(generate_output)```

And quite a bit of it is calculating `save_as`:
```22056   0.078   0.000   7.934   0.000   contents.py:410(save_as)```

This could potentially use caching to avoid recalculation. It should help a bit.

But... I also see that the files are **copied**:
```11108   0.059   0.000   3.995   0.000   shutil.py:122(copy2)```

Are you sure you're working on master and have the setting proper?

That being said, looking at the number, these will result in only incremental speedups. If the `--autoreload` process isn't about static files, I'd suggest you take those out during it (via `STATIC_PATHS`).

**Comment by josch** [comment]
Whoops, indeed it seemed to have preferred my system-installed pelican version over the python module from git. Here is the top of the updated profiler output:

```
Done: Processed 6 articles, 0 drafts, 1 page and 0 hidden pages in 16.95 seconds.
         8193086 function calls (8110694 primitive calls) in 17.493 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        2    0.003    0.001   17.497    8.748 __init__.py:2(<module>)
        1    0.000    0.000   17.179   17.179 __init__.py:385(main)
        1    0.000    0.000   16.948   16.948 __init__.py:144(run)
        1    0.062    0.062    7.171    7.171 generators.py:685(generate_output)
    10962    0.154    0.000    6.969    0.001 generators.py:708(_file_update_required)
        1    0.100    0.100    6.640    6.640 generators.py:662(generate_context)
    11240    0.052    0.000    6.418    0.001 contents.py:225(get_url_setting)
    10962    0.050    0.000    6.356    0.001 contents.py:475(save_as)
    11240    0.091    0.000    6.336    0.001 contents.py:219(_expand_settings)
    10976    0.025    0.000    6.312    0.001 contents.py:378(save_as)
    11240    0.213    0.000    6.114    0.001 contents.py:203(url_format)
    10969    0.366    0.000    4.146    0.000 readers.py:510(read_file)
    22209    0.185    0.000    3.483    0.000 contents.py:388(get_relative_source_path)
    21945    0.493    0.000    3.457    0.000 utils.py:266(slugify)
   126678    0.283    0.000    3.153    0.000 posixpath.py:358(abspath)
    35607    0.454    0.000    3.029    0.000 posixpath.py:424(relpath)
   137645    1.926    0.000    2.785    0.000 posixpath.py:329(normpath)
    22013    0.175    0.000    2.196    0.000 __init__.py:148(striptags)
161036/159063    0.164    0.000    1.915    0.000 {method 'join' of 'unicode' objects}
    11286    0.043    0.000    1.908    0.000 urlwrappers.py:139(slug)
      671    0.007    0.000    1.850    0.003 environment.py:809(get_template)
      671    0.028    0.000    1.842    0.003 environment.py:794(_load_template)
       19    0.000    0.000    1.781    0.094 writers.py:143(write_file)
       19    0.001    0.000    1.778    0.094 writers.py:168(_write_file)
      102    0.001    0.000    1.760    0.017 loaders.py:401(load)
      141    0.014    0.000    1.758    0.012 loaders.py:99(load)
       19    0.000    0.000    1.755    0.092 environment.py:993(render)
       64    0.002    0.000    1.731    0.027 environment.py:553(compile)
    11345    0.075    0.000    1.688    0.000 urlwrappers.py:115(slug)
```

Are you suggesting that during development with `-autoreload` I remove some paths from `STATIC_PATHS` to avoid this issue? I rather expected that pelican wouldn't need to look at files at all that didn't change in incremental mode. Why does it have to do that?

**Comment by avaris** [comment]
> Are you suggesting that during development with -autoreload I remove some paths from STATIC_PATHS to avoid this issue?

Pretty much.

> I rather expected that pelican wouldn't need to look at files at all that didn't change in incremental mode. Why does it have to do that?

First, there is no "incremental" mode. `--autoreload` triggers a site rebuild on every change.

It needs to do that to check if something is changed. It's not as simple as "static files aren't changed, why do you bother". You could change `STATIC_SAVE_AS` in your settings and suddenly everything needs to go someplace else. Or `FILENAME_METADATA`, etc... You could even have a plugin that decides the `save_as` values in some weird complicated manner and it's next to impossible to predict if a change will have an effect on things you're looking at.

That's more or less the reason for the lack of an incremental build mode. There is way too much freedom in plugins, themes etc. that given a change in some file, it's really, *really* hard to figure out what'll be different and what needs to be rebuild.

Could there be optimizations? Sure. The new `STATIC_CREATE_LINKS` setting just saved you ~4s.

But, `pelican` isn't optimized for that many files, at least for now.

**Comment by josch** [comment]
Okay, then I guess this is a wontfix bug. Lets close it. Thanks for your input!

**Comment by avaris** [comment]
I wouldn't say "wontfix". Lets say, it's not trivial to implement (correctly). And these kind of features often come from brave contributors who are affected enough to work on it :).
