### ISSUE TITLE
STATIC_CREATE_LINKS fails with symlinks in contents folder

### ISSUE THREAD

**Issue by josch** [getpelican/pelican#2192]
With current pelican git master I get the following error when some of the directories in my contents folder are symlinks and I have `STATIC_CREATE_LINKS=True`:

```
-> Linking /home/josch/git/afk.mister-muffin.de/content/static/img/zoom-minus-mini.png and static/img/zoom-minus-mini.png
CRITICAL: OSError: [Errno 1] Operation not permitted
Traceback (most recent call last):
  File "/tmp/pelican/pelican/__init__.py", line 498, in <module>
    main()
  File "/tmp/pelican/pelican/__init__.py", line 487, in main
    pelican.run()
  File "/tmp/pelican/pelican/__init__.py", line 179, in run
    p.generate_output(writer)
  File "/tmp/pelican/pelican/generators.py", line 691, in generate_output
    self._link_or_copy_staticfile(sc)
  File "/tmp/pelican/pelican/generators.py", line 734, in _link_or_copy_staticfile
    self._link_staticfile(sc)
  File "/tmp/pelican/pelican/generators.py", line 766, in _link_staticfile
    raise err
OSError: [Errno 1] Operation not permitted
```

This makes sense because `/home/josch/git/afk.mister-muffin.de/content/static/img` is a symlink to a directory elsewhere in my filesystem. Thus, it's not possible to create a hardlink to a path that is only a symlink.

I guess what would solve this problem is, if `_link_staticfile` would use `os.readlink` on the `source_path` to figure out the true location of the file it is trying to hardlink.

Alternatively, it could also fall back to symlinking these files.

**Comment by voidplayer** [comment]
Can you reproduce this?

I use ```STATIC_CREATE_LINKS = True``` and just tried to link a file and a folder

The link to the file copied the link itself, the link to the folder copied the folder

No errrors

**Comment by justinmayer** [comment]
@josch: If you need further assistance with this, please reach out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
