### ISSUE TITLE
using sym links or alias to add external .md files into content folder does not work

### ISSUE THREAD

**Issue by johnmathews** [getpelican/pelican#2194]
It would be super useful to be able to be able to put a link/alias to a file in the content/articles directory, because this would allow only one copy of the .md to be maintained. Currently I need to copy the file into the content/articles directory every time I make an edit, which is tedious. 

If I make an alias, I get the following error message:

ERROR: Could not process articles/week1.md
  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 40: invalid start byte
  |___
  | Traceback (most recent call last):
  |   File "/usr/local/lib/python3.6/site-packages/pelican/generators.py", line 523, in generate_context
  |     context_sender=self)
  |   File "/usr/local/lib/python3.6/site-packages/pelican/readers.py", line 526, in read_file
  |     content, reader_metadata = reader.read(path)
  |   File "/usr/local/lib/python3.6/site-packages/pelican/readers.py", line 293, in read
  |     with pelican_open(source_path) as text:
  |   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 82, in __enter__
  |     return next(self.gen)
  |   File "/usr/local/lib/python3.6/site-packages/pelican/utils.py", line 246, in pelican_open
  |     content = infile.read()
  |   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 698, in read
  |     return self.reader.read(size)
  |   File "/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codecs.py", line 501, in read
  |     newchars, decodedbytes = self.decode(data, self.errors)
  | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 40: invalid start byte

**Comment by ssteinerx** [comment]
The modification required would be just to determine whether the file's a link and read from the symlink's destination if so.  The functions are all readily available in the Python stdlib.

You'd have to catch a bad link (i.e. symlink to non-existent file), but a small function to do this whole chase-down could be used wherever this behaviour is desired.

This would probably be a good time to see where else this behaviour might be helpful e.g. static files and use the new function there as well.

**Comment by justinmayer** [comment]
@johnmathews: Were you able to find a solution to your problem here?
