### ISSUE TITLE
timezone and default_lang setting throw out "SyntaxError: invalid syntax"

### ISSUE THREAD

**Issue by hitrust** [getpelican/pelican#2195]
```
#Timezone & Language
TIMEZONE = 'Asia/Tokyo'
DEFAULT_LANG = 'zh'
```

> pelican -D
> DEBUG: Pelican version: 3.7.1
> DEBUG: Python version: 3.4.2
> CRITICAL: SyntaxError: invalid syntax (pelicanconf.py, line 24)
> ....
> File "pelicanconf.
> TIMEZONE = 'Asia/Tokyo'
>            ^
> SyntaxError: invalid syntax

Guys, get any idea?  thanks.

**Comment by hitrust** [comment]
> DEFAULT_LANG = 'zh'
lang setting also has the same problem.

**Comment by ingwinlu** [comment]
syntax error usually means you have exactly that, a syntax error, can you post a non cropped report?

**Comment by avaris** [comment]
Look at the lines above that. 
**\<wild guess>** It's usually a parenthesis that's not closed **</wild guess>**.
...or paste the full file.

**Comment by hitrust** [comment]
after reading all above， I adjusted the indentation and the comments in 'pelicanconf.py',  now It seems  alright. Thanks a lot.
