### ISSUE TITLE
TOC Markdown Extension not Accepting Configuration

### ISSUE THREAD

**Issue by tohuw** [getpelican/pelican#2198]
I'm having trouble passing options to the TOC Markdown extension. Can someone take a look and tell me what I'm doing wrong? The extension works, but the options do not take effect: 

https://gitlab.com/tohuw/tohuwnet/blob/849e8fa1b5aec3577dea37910dfedf66544efdb2/pelicanconf.py#L111-128

**Comment by melentye** [comment]
If that is of any help - copy-pasting your MARKDOWN property to my config worked fine, I got the anchors, permalinks and TOC header. I am running Pelican 3.7.1 and tested this in devserver locally.

**Comment by justinmayer** [comment]
Thanks for the follow-up, Andrey.

@tohuw: Were you able to resolve this problem?

**Comment by tohuw** [comment]
Apologies for the delay here. It still does not work. I get the anchors, permalinks and such, but changing the options does nothing.
