### ISSUE TITLE
Avoid Markdown Wrapping a Block Element from a Macro in <p> Tags

### ISSUE THREAD

**Issue by tohuw** [getpelican/pelican#2199]
I've made a macro: https://gitlab.com/tohuw/qalal/blob/24bdd9e1a2c0fe852d0bd1cc04a014162740c81a/templates/includes/macros.html#L9-14

It works fine, except that if it is called on a line all by itself in a Markdown post (via jinja2content plugin), it is always wrapped in <p> tags. Is there a way to prevent this without some hokey fix in the MD file? For example, I don't want to have to wrap it in a div or something.

**Comment by justinmayer** [comment]
@tohuw: Were you able to find a solution to your problem here?

**Comment by tohuw** [comment]
Yes, sorry for not returning to close this:
[The current, working macro](https://gitlab.com/tohuw/anew/blob/master/templates/includes/macros.html#L9-19)

[The diff](https://gitlab.com/tohuw/anew/commit/24bdd9e1a2c0fe852d0bd1cc04a014162740c81a)
