### ISSUE TITLE
Add a "Current Page" Context

### ISSUE THREAD

**Issue by tohuw** [getpelican/pelican#2200]
In Jekyll, `page` always referenced the current page, even if it was a post, or something else. While that's confusing in its own right, it'd be great to have a `this` context, so one could extract properties from the current page without caring what the type or template was.

An example use case: maybe I want a quick macro I could use in several places that could just (if called `with context`) reference e.g. `this.url` and get the URL of the current page. Or maybe I have an HTML widget that needs to make sure it displays certain content on a specific kind of post, and could check that via `this.metaattribute`.

**Comment by Frogging101** [comment]
I wonder how this would be implemented. The generators don't output a single common "page" class like this.

**Comment by justinmayer** [comment]
@tohuw: Is this something you would like to work on implementing?

**Comment by tohuw** [comment]
@justinmayer I fear it's beyond my amateur Python competence. That said, I can take a look soon-ish to see where this might be inserted, at least.

**Comment by justinmayer** [comment]
Given the lack of activity regarding this topic, I think it's best to close this issue for now. If someone wants to implement a solution and discuss it further, please post a comment here and we can resume discussion about it.
