### ISSUE TITLE
Disable index pagination

### ISSUE THREAD

**Issue by hojati** [getpelican/pelican#2207]
Dear Team,
Is it possible to disable pagination for index.html not whole site ?
I want to have pagination in my categories but not index page, but in the output directory I have
index.html
index1.html
index2.html 
....
which are all the same because of my theme.
I really dont want them, is there any option in setting that I can set to disable pagination only for my index page ?
Thank you

**Comment by avaris** [comment]
[docs](http://docs.getpelican.com/en/stable/settings.html#template-pages)

> `PAGINATED_DIRECT_TEMPLATES = ['index']`
Provides the direct templates that should be paginated.

**Comment by justinmayer** [comment]
@hojati: Hopefully @avaris was able to assist you in this case. In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
