### ISSUE TITLE
Odd truncation by Markdown in an HTML block...

### ISSUE THREAD

**Issue by jerryasher** [getpelican/pelican#2209]
I'm trying to embed a script into a markdown page, but failing. It appears to me that the markdown processor at times will mangle the script, by truncating characters and sticking in an ellipsis.

So a "perfectly" fine script will end up looking like:

```

function getPosition2(position)
   {
   document.getElementById("location2").innerHTML = "Longitude: " + position.coords.longitude …</script> 

```

I've reproduced my problem using a freshly cloned pelican, run against the samples/pelican.conf.py and the notmyidea theme. **I did modify pelican.conf.py** slightly since its value of *TEMPLATE_PAGES* is not none as the default is. So I commented that out and inserted this:

```
PAGE_PATHS = ['pages']

STATIC_PATHS = ['images', 'pdfs', 'downloads', 'assets', 'ferries']

DIRECT_TEMPLATES = ['index', 'tags', 'categories',
                    'authors', 'archives']
PAGINATED_DIRECT_TEMPLATES = ['index']
DEFAULT_PAGINATION = 5
```

I created three posts:

1. [mapit.md](https://gist.github.com/jerryasher/cf1b47cbfadc3ac0077bc5e2b3ca0b21)
2. [mapbetter.md](https://gist.github.com/jerryasher/b5864ec282fffc6b4f03e303d86b8820)
3. [map.md](https://gist.github.com/jerryasher/f6c3ec82fc505621b864c857f8f4cd3f)

I recreate the site

```
$ rm -rf public && pelican -v content -s ../pelican/samples/pelican.conf.py -t ../pelican/pelican/themes/notmyidea -o public
$ make serve
```

And I see this site:

![fresh site](https://i.imgur.com/LdYsgg2.png)

Chrome Dev Tools will complain:

```
Uncaught SyntaxError:  Invalid or unexpected token (index 115)
```
and sure enough, in the second post, mapbetter, there is an ellipsis where script should be:

![mangled script](https://i.imgur.com/gvidUT6.png)

If you click the [Where am I] buttons, your browser may ask you for permission to locate you, and if you consent, your lat and lon will be inserted below each button, except for in MapBetter, where nothing will happen and the javascript console will log an error.

![broken site](https://i.imgur.com/mYgcUXk.png)

AND NOW TO MAKE IT INTERESTING....

If you would like MapBetter to work, just delete MapIt and rebuild the site.

```
$ cd content/posts/
$ rm mapit.md
$ cd ..
$ rm -rf public && pelican -v content -s ../pelican/samples/pelican.conf.py -t ../pelican/pelican/themes/notmyidea -o public
$ make serve
```

![mapbetter now works](https://i.imgur.com/NuHeakA.png)

**Comment by avaris** [comment]
It looks like automated `summary` generation is the cause here. Can you try with `SUMMARY_MAX_LENGTH = None` setting?

**Comment by jerryasher** [comment]
Thanks @avaris, yes, so that does seem to have fixed it, thank you.
