### ISSUE TITLE
Is there a way to generate a site programmatically?

### ISSUE THREAD

**Issue by MichaelMartinez** [getpelican/pelican#2211]
Hi all,

I am banging my head about this a bit... looking to see if there is a way to generate a site from inside another Python script. If I am missing it in the docs please ignore after pointing me to where it is :v:

Instead of this:

`pelican /path/to/your/content/ [-s path/to/your/settings.py] `

We do something like this:

```python
import pelican

DEFAULT_CONFIG = 'pelicanconf.py'

# things and stuff here

# generate Site function...
def generate_mysite('DEFAULT_CONFIG')
   pelican.run()
   # do more stuff here...

```

I am going to do some hacky stuff with the `__init__.py` and the `main()` method herein to get what I need for now. I thought I would throw this out there... see if there is interest...  :tada:

**Comment by vanessa-luna** [comment]
I can't help you run Pelican from within a python script, but if you're looking to build programmaticaly in general, you can get a copy of a preconfigured shell script that will help

If you run `pelican-quickstart` you will be asked a question about generating test and build scripts for you.

**Comment by ssteinerx** [comment]
As @vanessa-luna said, test and build scripts are created for you.

Not sure what you're trying to accomplish, exactly, but you can just call out to those scripts from within your code without reinventing the proverbial wheel.

**Comment by MichaelMartinez** [comment]
Sorry, I wasn't very clear. I want to build the Pelican site from another python script.... one without the command line being used at all. Looking at the architecture of Pelican, I think this might not be worth the trouble. The coupling between the command line (__inti__.py, etc.) and the rest of the library is super tight. So for now I am going to use `subprocess` to gain programmatic access to build...

```python
import subprocess


#do stuff ... then

subprocess.run(['pelican', '-s', 'pelicanconf.py'])

```

**Comment by ingwinlu** [comment]
pseudecode

```
import pelican

from pelican.settings import read_settings

settings = read_settings(settings_file)

pelican = Pelican(settings)

pelican.run()

```

https://github.com/getpelican/pelican/blob/master/pelican/tests/test_pelican.py
might also be helpful as some of our integration tests actually use
that approach


BR

**Comment by justinmayer** [comment]
Nice tip, Winlu. Thanks for the guidance here!
