### ISSUE TITLE
Set html lang attribute for each post according to its lang metadata

### ISSUE THREAD

**Issue by bingen13** [getpelican/pelican#2212]
The lang attribute is set globally for the entire blog, taken from the DEFAULT_LANG setting. However, posts and pages may be written in different languages, which are indicated on their metadata through the Lang field. This should change the language for those posts when shown together, and for the post URL when shown alone.

**Comment by justinmayer** [comment]
Hi David. Is this something you would like to help implement?

**Comment by ingwinlu** [comment]
isn't that a theming problem? it should check if there is article language
set and fallback to the global setting.. i think i have seen this approach
in a number of themes already.

**Comment by Postroutine** [comment]
Manage it in the pelican code would avoid problem with theme that don't manage it correctly.

**Comment by avaris** [comment]
How can pelican manage this? All the meta fields in the final HTML output is handled by the theme. Pelican only supplies the content as HTML.

**Comment by jorgesumle** [comment]
Here is the solution:

1. Add the following code to the `base.html` of the theme:

```
<html lang="{% block html_lang %}{{ DEFAULT_LANG }}{% endblock %}">
```
2. Add the following code to the file `article.html`:

```
{% block html_lang %}{{ article.lang }}{% endblock %}
```
3.  Add the following code the file `page.html`:
```
{% block html_lang %}{{ page.lang }}{% endblock%}
```

@Postroutine, I think that changing three lines of code is not very difficult. You can submit a pull request to the theme you are using or just change it to fit your needs. With that said, I would vote to close this issue.

**Comment by justinmayer** [comment]
Is there any value in adding @jorgesumle's suggested changes to the default theme's [base.html](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/base.html#L2), [article.html](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/article.html), and [page.html](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/page.html)?
