### ISSUE TITLE
File not Found when calling Pandocs with relative paths

### ISSUE THREAD

**Issue by W7PEA** [getpelican/pelican#2213]
When trying to process the WPCandy sample file (or my own file) I get an error that the output file cannot be found.

```
pelican-import --wpfile wp-export\posts.xml
output\a-simple-post-with-text.rst
pandoc: output\a-simple-post-with-text.html: openFile: does not exist (No such file or directory)
pandoc --normalize --parse-raw --from=html --to=rst -o "output\a-simple-post-with-text.rst" "output\a-simple-post-with-text.html"
Please, check your Pandoc installation.
```
If I add --dump-args to the pandocs command in pelican_import:

```FileNotFoundError: [Errno 2] No such file or directory: 'output\\a-simple-post-with-text.rst'```

IRC has been super helpful, but I feel like this is either a bug or a dependency issue that would easier to sort out in Github. 

Thanks for the help!

---- Environment ----
Windows 10
Virtualenv in use

pip -list 
    astroid (1.5.3)
    beautifulsoup4 (4.6.0)
    blinker (1.4)
    colorama (0.3.9)
    docutils (0.14)
    feedgenerator (1.9)
    feedparser (5.2.1)
    flake8 (3.4.1)
    isort (4.2.15)
    Jinja2 (2.9.6)
    lazy-object-proxy (1.3.1)
    lxml (4.0.0)
    Markdown (2.6.9)
    MarkupSafe (1.0)
    mccabe (0.6.1)
    pelican (3.7.1)
    pip (9.0.1)
    ply (3.10)
    pycodestyle (2.3.1)
    pyflakes (1.5.0)
    Pygments (2.2.0)
    pylint (1.7.2)
    python-dateutil (2.6.1)
    pytz (2017.2)
    setuptools (36.5.0)
    six (1.11.0)
    Unidecode (0.4.21)
    wheel (0.30.0)
    wrapt (1.10.11)

pandoc --version
    pandoc 1.19.2.1
    Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
    Default user data directory: C:\Users\...\AppData\Roaming\pandoc
    Copyright (C) 2006-2016 John MacFarlane
    Web:  http://pandoc.org
    This is free software; see the source for copying conditions.
    There is no warranty, not even for merchantability or fitness
    for a particular purpose.

python --version
    Python 3.6.1

**Comment by W7PEA** [comment]
Just as I hit save on this, I noticed that pandoc was in another folder (I hd actually copied it locally as welll) but in seeing that path.. it made me realize that passing it full paths might work.


```
cmd = cmd.format(parse_raw, out_markup,
                             os.path.abspath(out_filename),
                             os.path.abspath(html_filename))
```
Fixed it for me. If that looks like it should work on all OSes I'll submit a PR.

**Comment by justinmayer** [comment]
Ostensibly addressed already. Please feel free to comment here if you feel the issue should be re-opened.
