### ISSUE TITLE
add "sticky posts" and "the specified category does not appear on the home page " support

### ISSUE THREAD

**Issue by hitrust** [getpelican/pelican#2214]
As the title said,

**Comment by jorgesumle** [comment]
I would prefer this functionality implemented in a plugin, instead of adding it to Pelican. I'm not sure if this is what you mean, @hitrust, but there is already one plugin which seems to do that: https://github.com/Shaked/pin_to_top

**Comment by jorgesumle** [comment]
> "the specified category does not appear on the home page " support

Sorry, I forgot to answer to this one. What do you mean with that?

**Comment by hitrust** [comment]
thanks for your reply, @jorgesumle and sorry for my said is not clear，specified category's post are excluded to show on homepage's post list.

**Comment by justinmayer** [comment]
I agree with @jorgesumle. This type of functionality is more appropriately implemented at the plugin/theme level than in Pelican core.
