### ISSUE TITLE
Error using `PAGE_SAVE_AS`

### ISSUE THREAD

**Issue by Nikratio** [getpelican/pelican#2215]
http://docs.getpelican.com/en/stable/themes.html#page-html says:

> This template will be processed for each page, with output generated according to the PAGE_SAVE_AS setting (Default: pages/{page_name}.html).

However, when I set this variable:

```
$ grep PAGE settings.py
PAGE_SAVE_AS = '{page_name}.html'
```

Running Pelican fails with:

```
$ make html
pelican [path]/content -o [path]/output -s [path]/settings.py 
CRITICAL: KeyError: u'page_name'
Makefile:40: recipe for target 'html' failed
make: *** [html] Error 1
```

This is with:

```
$ pelican --version
3.7.1
```

**Comment by avaris** [comment]
That's a documentation error. Actual settings are [here](http://docs.getpelican.com/en/stable/settings.html#url-settings).

**Comment by ix5** [comment]
I've prepared a PR to address this: #2259 `Fix documentation for *_SAVE_AS in themes.rst`

**Comment by justinmayer** [comment]
Fixed via above PR.
