### ISSUE TITLE
Feature request: only reprocess modified files with --autoreload

### ISSUE THREAD

**Issue by gbrener** [getpelican/pelican#2219]
Pelican's `--autoreload` mode currently reprocesses every file, regardless of how many were modified. Because many use this feature for interactive editing - where usually only one file is modified at a time - a significant speed boost could be gained if Pelican only reprocessed the modified file(s). One potential approach for this is in #2171.

**Comment by ingwinlu** [comment]
read the thread you linked.

we would need to track the influence of every input artefact (be it setting
or 'article'/'page' file) on all output files which are currently not doing.

if you feel up to the task of implementing go ahead and do it.

**Comment by gbrener** [comment]
Sounds like someone was having a bad day. I hope things get easier for you.

It turned out to be less time-consuming to port my site to [Hugo](gohugo.io), which already includes this feature. Feel free to re-open this issue if you think someone else will find it helpful.

**Comment by ingwinlu** [comment]
Hugo is great as a more general static site generator than pelican. However that particular feature is not supported by them afaik https://github.com/gohugoio/hugo/issues/1643 or https://stackoverflow.com/questions/34714442/hugo-incremental-builds-is-there-an-undocumented-switch-somewhere (yet).

**Comment by gbrener** [comment]
Great to see that they take this issue seriously and are actively working on it. Hugo is so fast that I assumed that's what they were already doing; I was really asking for "fast interactive feedback while editing" which is what they provide, (surprisingly) without this feature.

**Comment by Grk0** [comment]
For anyone else finding this issue, check out [Reading only modified content](http://docs.getpelican.com/en/latest/settings.html#reading-only-modified-content) in the settings documentation. Enabling caching (``CACHE_CONTENT = LOAD_CONTENT_CACHE = True``) brought render times for my ~200 page site down to 2 seconds in autoreload mode.
