### ISSUE TITLE
Problem with static generating on pelican

### ISSUE THREAD

**Issue by henriquenasc** [getpelican/pelican#2220]
Hello guys!
I have a problem with the **pelican**, I installed a theme and every time I run the commands:

`pelican content` or
`pelican -s pelicanconf.py content`

It's all right, though...
it returns to the old default theme and I want it to stay on the theme I installed.

Thank you in advance. : D

**Comment by justinmayer** [comment]
Hi Henrique. As noted in [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, the problem you describe is almost certainly related to either your settings or your theme. Without knowing more about both of those, it's impossible to help.

Please reach out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, and ask your questions along with links to your theme and a pastebin of your settings file. Thanks!
