### ISSUE TITLE
Is there a way to configure pelican to execute code before generation ?

### ISSUE THREAD

**Issue by jadjay** [getpelican/pelican#2223]
In my case it is needed for use of sass before publishing,

It could be a plugin with table variable like : 
```
EXEC_BEFORE=('sass path/to/x.sass path/to/x.css',
'whatever ...',)
```

**Comment by avaris** [comment]
For your use case there is [assets](https://github.com/getpelican/pelican-plugins/tree/master/assets) plugin.

**Comment by justinmayer** [comment]
I agree with @avaris; the Assets plugin is probably your best solution for this use case. For other use cases, I suggest using Ansible, Fabric, Make, or a similar automation tool for chaining together pre/post-processing tasks.

In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
