### ISSUE TITLE
Trouble using EXTRA_TEMPLATES_PATHS, mutliple pelican_conf in folder

### ISSUE THREAD

**Issue by vanessa-luna** [getpelican/pelican#2229]
I am hoping to use EXTRA_TEMPLATES_PATHS to "override" direct templates, but cannot seem to get it to work. 

I actually run 4 pelican configs now for my project. I know, messy. But Pelican has a lot of limitations, but are easily overcome by using multiple configs. This latest config, requires different direct templates than the rest. 

HOW DO I USE EXTRA_TEMPLATES_PATHS?

The templates path I want it to use is in a subfolder of templates `theme/templates/product/index.html' `

do I provide an absolute path?
how can I verify that it's working?

The code says `self._templates_path += self.settings['EXTRA_TEMPLATES_PATHS']` Does this not mean it checks the extra path AFTER the default path? can I turn this around so it checks the extra paths first?

**Comment by vanessa-luna** [comment]
Well, like normal, writing out the problem, helped me discover an option. I went into the source code and swapped the code around to add the extra templates paths first and it worked... This is a simple solution it seems... and will fallback to any templates not overriden...

generators.py
`self._templates_path = self.settings['EXTRA_TEMPLATES_PATHS']`
`        self._templates_path.append(os.path.expanduser(os.path.join(self.theme, 'templates')))`


I've seen other override templates issues... And this may be the stupid simple solution for most people.
Let me know if I can clarify...

**Comment by vanessa-luna** [comment]
Additionally, however the Jinja environment works, it does a sneaky thing that I really appreciate!

I have a `base.html` template that sets up some blocks and stuff. Then I extend that in every page. This new "product site in a sub folder"  needed an extra .css file for every page to override some css in the main project. So, by creating a `base.html` in my EXTRA_TEMPLATES_PATH, it used that base.html even if the template I had not overriden was used.

### Example: 
Sorry if this is overkill for a github issue, but I wanted this info to be somewhere that's visible, crawled, and maybe others will see. My setup is obviously more complex than this, but it should give the basics to doing this yourself. 

**generators.py**
This is what I changed to get this magic to happen...
``` python
class Generator(object):
    """Baseclass generator"""

    def __init__(self, context, settings, path, theme, output_path,
        ....
        # templates cache
        self._templates = {}
        # __________THESE LINES __________
        self._templates_path = self.settings['EXTRA_TEMPLATES_PATHS']
        self._templates_path.append(os.path.expanduser(
            os.path.join(self.theme, 'templates')))
        # ______________________________
```

**blog_conf.py**
This is the main pelican conf that builds the root content
``` python
THEME                      = 'theme'
DIRECT_TEMPLATES           = ['index', 'archives']
PAGINATED_DIRECT_TEMPLATES = ['index']
EXTRA_TEMPLATES_PATHS      = []
```

**product.py**
This is the pelican conf that builds the product content in <URL>/product. **Note** that I import the main blog conf to avoid repetition in simplify changes in the future. DRY as can be!
``` python
from blog_conf import *
THEME                      = 'theme'
DIRECT_TEMPLATES           = ['index', 'archives']
PAGINATED_DIRECT_TEMPLATES = ['index']
EXTRA_TEMPLATES_PATHS      = ['theme/templates/product']
```

This is my folder structure
```
theme/templates/
    base.html
    archives.html
    index.html
    fragments/
        sidebar.html
        footer.html
    product/
        base.html
        index.html
        fragments/
            menu.html
            footer.html
```

**theme/templates/base.html**
This is the ROOT base.html I use. Note the sidebar and footer fragments
``` html
<!DOCTYPE html>
<html lang="{{ DEFAULT_LANG }}">
<head>
    <title>{% block page_title %}{% endblock page_title %} | Main Blog</title>
    {% include 'fragments/head.html' %}
    {% block assets %} {% endblock %}
</head>
<body>
    {% include 'fragments/sidebar.html' %}
    <div class="content">
        {% block title %} {% endblock %}
        {% block content %} {% endblock %}
        {% include 'fragments/footer.html' %}
    </div>
</body>
</html>

```


**theme/templates/_product_/base.html**
NOTE: I remove the above sidebar and put in the menu. I add in another asset reference that will override some of the other default css from the original theme using the webassets plugin. Pelican plugins FTW! :+1: 
``` html
<!DOCTYPE html>
<html lang="{{ DEFAULT_LANG }}">
<head>
    <title>{% block page_title %}{% endblock page_title %} | Product</title>
    {% include 'fragments/head.html' %}
    {% block assets %} {% endblock %}
    {% assets "css-product-base" %}
        <link rel="stylesheet" href="{{ SITEURL }}/{{ ASSET_URL }}">
    {% endassets %}
</head>
<body>
    <div class="content">
        {% include 'fragments/menu.html' %}
        {% block title %} {% endblock %}
        {% block content %} {% endblock %}
        {% include 'fragments/footer.html' %}
    </div>
</body>
</html>
```

**theme/templates/archives.html**
This is where it gets awesome. While this relative url in the archive folder looks like it is pointing to the same folder, the environment picks up the base.html in the product folder first. So we need to change nothing in order to reuse the same template but get all the same benefits. The power of abstraction right? :rofl: 
``` html
{% extends "base.html" %}
```

**Comment by justinmayer** [comment]
Thanks for the detailed write-up, @vanessa-luna. Hopefully others who search for related topics will find it to be helpful.
