### ISSUE TITLE
Redundancy in documentation (publish.rst) 

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2233]
> Note that you must specify the path to the generated output file — not the source content. **To determine the output file path, use the --debug flag to determine the correct file name and location**. If desired, --write-selected can take a comma-separated list of paths or can be configured as a setting. (See: :ref:`writing_only_selected_content`)

(Emphasis added.) I find this redundant and a bit confusing. I'm sure we can improve it a bit. Maybe I don't understand it right. To determine the output path you just use the `--debug` flag, what does file name and location mean? Aren't the file name and location included in the path? In my case, I can see `Writing /privatepath/output/instalacion-de-un-servidor-glamp/index.html`, being `/privatepath/output/instalacion-de-un-servidor-glamp/` the *location* and `index.html` the *file*.

**Comment by justinmayer** [comment]
> what does file name and location mean?

I understand it as:

full path = location (parent directory hierarchy) + file name

> Aren't the file name and location included in the path?

Yes.
