### ISSUE TITLE
pelican in shell/cli - must specify path but don't want to...

### ISSUE THREAD

**Issue by vanessa-luna** [getpelican/pelican#2236]
What is the point of the PATH setting in the config, if I cannot rely on it? I'm a novice at shell and using the quickstart scripts as a basis.

### I want

``` python
PELICAN=${PELICAN:-pelican}
$PELICAN -s /path/to/config.py
```

### I Must

``` python
$PELICAN -s /path/to/config /path/to/content
```

### How do?
Am I doing something wrong? I am trying to be DRY here...
I want to just tell it the config and go...

**Comment by avaris** [comment]
I'm a little lost here. You can definitely set `PATH` in your config and not have to give as an argument. What's the issue here? Are you getting an error if you don't supply it?

**Comment by vanessa-luna** [comment]
Yes I get an error when I try to only provide a config. The same error occurs in either Command line or in Shell script.


conf.py 
``` python 
PATH="content/site1"
```

test.sh
``` bash
PELICAN=${PELICAN:-pelican}
$PELICAN -s $(pwd)/config/conf.py 
```

OUTPUT
``` cli
~/blog: ./tesh.sh
CRITICAL: Exception: You need to specify a path containing the content (see pelican --help for more information)

~/blog: pelican -s config/conf.py
CRITICAL: Exception: You need to specify a path containing the content (see pelican --help for more information)

```

**Comment by justinmayer** [comment]
Do you get an error if you specify an absolute PATH?

**Comment by vanessa-luna** [comment]
I get the same error using an absolute path.

```
pelican -s /home/luna/blog/config/conf,py
CRITICAL: Exception: You need to specify a path containing the content (see pelican --help for more information)
```

### NEW DEVELOPMENT

I am inheriting from other configs and this seems to be the problem.

blog_conf.py - holds most of the settings
site2_conf.py - imports blog_conf then alters some settings
``` python
import os
import sys
sys.path.append(os.path.dirname(__file__))
from blog_conf import *
```

IF, I remove the import statement, and only that statement, pelican does not yell about the PATH, but does yell about other missing variables that in the parent config...

Now I am well beyond my depths... Thank you for your input :) IF you want to see the exact configs I am using they live here: 
[Parent Config](https://github.com/vanessa-luna/pelican-setup/blob/master/config/blog_conf_dev.py)
[Sub Config](https://github.com/vanessa-luna/pelican-setup/blob/master/config/shadows_conf.py)

Any of the important settings and what not will be at the top should you choose to view them.

**Comment by justinmayer** [comment]
> I get the same error using an absolute path.
> `pelican -s /home/luna/blog/config/conf,py`

That's not what I meant. I meant all-uppercase PATH, as in [that specific variable](https://github.com/vanessa-luna/pelican-setup/blob/master/config/shadows_conf.py#L20).

**Comment by vanessa-luna** [comment]
My bad... :) 
I tried an absolute path inside the config and I get the same error.

``` python
PATH = '/home/luna/files/forge/blog/config/shadows_conf.py'
```

However, if I remove the import statement like above, it does work.

**Comment by justinmayer** [comment]
That's not what `PATH` is for. Please read Docs > Settings carefully.

Try setting `PATH` to the absolute path to your **content**.

**Comment by vanessa-luna** [comment]
So you don't have to try to rummage through my repo to get it...

I run `dev.sh` in the root folder. It needs to reference configs that life in `config` and output to the .output folders seen below.  I have three different "sites" each with separate configs. 

```
blog/
  ├ .dev-output     - testing output
  ├ .output         - production output
  ├ config
  ├ content
  │   ├ blog
  │   ├ shadows
  │   └ liner
  ├ theme
  ├ build.sh
  └ dev.sh
```

### It WORKS

if I move the config back into the root folder, outside of the config folder... It must be a python level pathing problem... right?

 If it is too much effort to resolve for such a minor thing like this, please don't worry about it. I feel silly even asking.

**Comment by vanessa-luna** [comment]
> That's not what PATH is for. Please read Docs > Settings carefully.

> Try setting PATH to the absolute path to your content.

I'm sorry, I'm bleh, I am not referencing the conf.py in the conf.py I'm just translating poorly because I'm a little too frazzled right now. Like you saw in my linked config, it is  referencing the **content** folder.

**Comment by justinmayer** [comment]
> Like you saw in my linked config, it is referencing the content folder.

Not absolutely, it isn't.

**Comment by vanessa-luna** [comment]
Okay. Using an absolute path did work in the PATH setting. 

The first time you suggested it I only used a "~/" path, which I guess doesn't work... using "/home/luna/" path DID work. 

Thank you fro your patience with me Justin. I'm still novice at Linux stuff.

**Comment by justinmayer** [comment]
No worries. Does that resolve your issue?

**Comment by vanessa-luna** [comment]
Not ideally. I would prefer not to use absolute paths. I would prefer relative paths, however this is an easy fix. I work alone on this site so I can try to squelch the inner OCD demons get the best of me. Thank you

**Comment by justinmayer** [comment]
Relative to settings file may work.

**Comment by avaris** [comment]
If you want to expand `~`:
```python
PATH = os.path.expanduser('~/foo/bar')
```

if you want the path relative to settings file
```python
PATH = os.path.join(
    os.path.abspath(os.path.dirname(__file__)), 
    'foo/bar')
```

**Comment by vanessa-luna** [comment]
So, relative worked. I only needed to adjust the relative url with an parent folder reference `PATH = "../content/blog"` - ugh, sometimes I truly surprise myself. 

 I got so caught up in this problem because of the error message...

``` python
 if 'PATH' not in settings or not os.path.isdir(settings['PATH']):
        raise Exception('You need to specify a path containing the content'
' (see pelican --help for more information)')
```

This would have helped!!!
``` python
if 'PATH' not in settings :
    raise Exception('You need to specify a path containing the content (see pelican --help for more information)')
if not os.path.isdir(settings['PATH']):
    raise Exception('PATH not found')
```
