### ISSUE TITLE
pelican-import: handle the multiple categories from Wordpress

### ISSUE THREAD

**Issue by fgallaire** [getpelican/pelican#2239]
As #349 and #350 are closed with no fix, I re-open here.

I'm trying to migrate two Wordpress blogs that have multiple categories by post.

The most important problem is that the great ``pelican-import`` is broken for a widespread Wordpress feature (whether it is a good or a bad one is not the point here). And I think it will have more and more Wordpress migrations in the coming years.

The most objectionable problem is that Pelican is not even coherent in its way of handling multiple categories. ``pelican-import --dir-cat`` take the first categorie as directorie name, but the Category metadata is the list of the categories separated by commas, and treated by Pelican as a weird category name.

I'm sure nobody wants this result:

    Categories

    Documentation (2)
    Documentation, Media (1)
    Documentation, Site (2)
    Documentation, Tools (1)
    Documentation, Translations (13)

**Comment by justinmayer** [comment]
Addressed by #2434.
