### ISSUE TITLE
Category/Tag/Author slugs are not settable

### ISSUE THREAD

**Issue by zackw** [getpelican/pelican#2242]
URLWrapper objects have a setter for their 'slug' property, but all of the concrete URLWrapper subclasses override the _getter_ for 'slug', which, because of the way Python's property accessors work, makes the setter inaccessible.  This breaks the 'category_meta' plugin and probably other things as well.

**Comment by justinmayer** [comment]
Status: @zackw submitted PR #2243, which needs additional work before it can be merged.
