### ISSUE TITLE
Missing DISPLAY_TAGS_ON_MENU option

### ISSUE THREAD

**Issue by fgallaire** [getpelican/pelican#2244]
There is the two options:
DISPLAY_PAGES_ON_MENU
DISPLAY_CATEGORIES_ON_MENU

But the DISPLAY_TAGS_ON_MENU option is missing.

The [pelican-twitchy](https://github.com/ingwinlu/pelican-twitchy) theme has implemented it, but it should be a Pelican built-in.

**Comment by jorgesumle** [comment]
> But the DISPLAY_TAGS_ON_MENU option is missing.

Just add a variable to the configuration file and place an `if` in your theme. I'm not in favour of adding more variables to Pelican, when it's the plugin developers who should worry about this.

**Comment by avaris** [comment]
Technically those are theme settings. Not much to do with pelican itself other than the fact that default theme uses them.

And, definition of "MENU" in default theme varies quite a bit from twitchy (from what I've seen). Usually, you'll have quite a lot more tags than categories or pages. I don't think placing them on menu for default theme will be appealing.

**Comment by fgallaire** [comment]
As ``DISPLAY_PAGES_ON_MENU`` and ``DISPLAY_CATEGORIES_ON_MENU`` are in the official documentation:
http://docs.getpelican.com/en/3.6.3/settings.html
theme writers are aware about and support them in their themes.
So we need a ``DISPLAY_TAGS_ON_MENU = False`` officially documented in the default settings to expect some theme supports.

Which needs? I'm trying to find a path to port Wordpress sites with multiple categories by post, and that is not possible with Pelican "who only supports one category by design", so a conversion to tags is an option. But for that, tags shouldn’t remain second-class citizens in Pelican, i.e, have theme support to be shown in the menu, i.e. have a ``DISPLAY_TAGS_ON_MENU`` option.

**Comment by justinmayer** [comment]
The stated motivation behind adding a `DISPLAY_TAGS_ON_MENU` setting was to work around the (intentional) inability to assign multiple categories to a post. Since there is now a [More Categories](DISPLAY_TAGS_ON_MENU) plugin that provides that ability, there does not seem to be much reason to proceed with adding a `DISPLAY_TAGS_ON_MENU` setting at this time.
