### ISSUE TITLE
Category names slugification problem

### ISSUE THREAD

**Issue by fgallaire** [getpelican/pelican#2248]
In ``pelican-import`` with the ``--dir-cat`` option, categorie names are slugified to generate the directory names.

But it's not coherent with the handling of the Category header where there's no slugification.

This leads to problems in very simple cases. After an import if you had the category `Documentation`, all the files are in the directory ``documentation`` and have ``Categorie: Documentation`` in the header. The post category is shown as `Documentation` . Now create a new content file whitout Categorie header, the post category is shown as `documentation`.

A same category should only have one and only one visible name.

So it could be possible to have the slugified category names added in the header. But I'm sure I don't want that since I prefere to have an uppercase first letter category names.

Slugification is for URL, but it this really needed for filenames (i.e. file system question) ?
Or maybe make category names slugification an option ?

**Comment by fgallaire** [comment]
Slugification is for URL, but it this really needed for file systems ?
Or maybe make category names slugificatio an option ?

**Comment by fgallaire** [comment]
Slugification is for URL, but it this really needed for file systems ?
Or maybe make category names slugificatio an option ?

**Comment by avaris** [comment]
Allowed characters in file/folder names are file system and OS dependent and it's generally a mess. Slugification is a safer route to be fairly platform independent. So, I'd say it's kind of needed. It can be an option, sure, if you are OK with any non-obvious errors the system might throw at you.

You generally do `pelican-import` only once. Is it a big deal to go over the output and make some finer touches afterwards (either manually or by some kind of scripting if necessary)?

**Comment by fgallaire** [comment]
The best importing experience seems important to me, it directly impacts on the choice of a SSG.

Slugification is for URL, but used for directory names for safety purposes.

A sane default could be to use a sightly softer algo: as uppercase letters are not "file system" dangerous, we could use slugification without the lowercase convertion.

**Comment by justinmayer** [comment]
Update: @fgallaire submitted PR #2249, which is awaiting review.

**Comment by justinmayer** [comment]
If @fgallaire would be willing to add the additional tests mentioned in the PR's discussion thread, we would be happy to merge those changes.
