### ISSUE TITLE
HTMLParser: handle_ref() is broken

### ISSUE THREAD

**Issue by ramonsuarez** [getpelican/pelican#2258]
I have imported my site from Jekyll (already an import from wordpress and then from posterous) to transfer it to pelican. When I try to build the html I get an error when writing the 3rd index page (actual pagination links, not files in my `content/` directory). 

This is [the error](https://dpaste.de/rLvY). Note:I've changed the name of the directory to `rsj2p/`, so it is no longer "importrs".

The [ Pelican repository of the blog is here](https://github.com/ramonsuarez/rsj2p). 

This is [the blog](http://ramonsuarez.com) hosted on github pages. The current [Jekyll repository is here](https://github.com/ramonsuarez/ramonsuarez.github.io). 

After the error I can serve the page, and the index links are displayed but only the first 2 work. 

I've tested this in a vanilla install of Pelican and with 3 different themes (both default themes and a third one). 

I tried IRC to get help, but as I got disconnected I could not see the history to check if there was an answer.  

None of my searches have provided a solution (also searched within the issues of Pelican). 

Thanks for your help.

**Comment by ix5** [comment]
Some of your links are breaking the HTMLParser that is supposed to generate a summary, e.g. in [this article](https://github.com/ramonsuarez/rsj2p/blob/67dd924c2c8c2a9e7d728944b687116bb805a6df/content/seniority-of-the-betagroup-linkedin-group-members-owners-rule.md).
I think it is the `&gid` that is responsible, `handle_ref` is looking for a closing semicolon but there is none.
Could you see if this fixes it? https://github.com/ix5/pelican/tree/fix_entity_parsing

**Comment by ramonsuarez** [comment]
Thanks @ix5 . I will try it when I get home. The weird tags are probably legacy from the previous imports, namely from Posterous and its clipping feature. Where should I use fix_entity_parsing? And the hack? I'm learning programming and need a bit of direction. Not afraid of changing things with my mastery of hard resets ;)

**Comment by ix5** [comment]
Hey Ramon, what I meant is this:

Download the fix_entity_parsing branch from my repo:
```
git clone https://github.com/ix5/pelican/
git checkout fix_entity_parsing
```
Then uninstall your pelican version, you might have to activate your virtualenv for that
`pip uninstall pelican`
Then install the fix_entity_parsing branch version of pelican
`pip install -e /home/ramon/where/you/downloaded/the/repo/to/pelican`
Run pelican as you usually would:
`pelican --with-your-usual-options ...`

But: You will have to do some work on your content. I have downloaded your repo from [github](https://github.com/ramonsuarez/rsj2p) and saw a lot of issues:
- Every `<div>` tag has to go, best to strip `<div>` and `</div>` everywhere
- Every one of those curly-braces-tags has to go, e.g. `[![link text]{.class width="500"}](https://link.com)` has to be replaced with `[![link text]](https://link.com)`. Or maybe there's a plugin for those kind of tags?
- Check all the facebook embeds, they most likely will not work anymore

Oh, btw, I enjoyed your post 'Ramon's Madrid Top 10 Eating and Drinking Spots', might have to check whether this holds up - 7 years later - next time I'm in Spain :)

Could you also please rename the title of this issue to: **HTMLParser: handle_ref() is broken**

**Comment by ramonsuarez** [comment]
Thanks a lot @ix5 ! I'm on it :) The list for Madrid should still be good. If you want something in particular I can always check with my friends for an update .

**Comment by ramonsuarez** [comment]
It woks great, thanks a million @ix5 . I'm now cleaning the old posts and looking forward to write new ones :)
