### ISSUE TITLE
Is the size of generated files too large?

### ISSUE THREAD

**Issue by hitrust** [getpelican/pelican#2261]
one of my sites that has 40 thousands posts, use pelican to generate the site,  ten all the output files has to be nearly 1GB, the generated files too large or not, maybe can use js to  import the same template part to reduce the files's size?

**Comment by mwcz** [comment]
If you want to implement this, it can be done with a custom theme.  I'm just a user, not a contributor, but I don't think this needs to be part of Pelican core.

**Comment by justinmayer** [comment]
I'm open to well-reasoned solutions for larger sites, but I'm not sure JS is right approach. That said, alternative proposals are welcome.
