### ISSUE TITLE
Assign Banner Photos to Articles

### ISSUE THREAD

**Issue by joshfuggle** [getpelican/pelican#2264]
Hello!

Is it possible to either:

1) Assign a banner photo (via a static image) to an article, or
2) Loop through all images in an article, then grab the first one for use as a banner photo in the template?

Appreciate your time in answering this.

Thanks,
Josh

**Comment by mosra** [comment]
Hi! I'm having something similar in [m.css](http://mcss.mosra.cz/) for creating [jumbo articles](http://mcss.mosra.cz/pelican/theme/#jumbo-articles). Basically it's about adding a new metadata field (e.g., `:cover:`) that the theme then has to pick up and treat as an image URL. It's a bit more involved if you want to support the [internal content linking](http://docs.getpelican.com/en/stable/content.html#linking-to-internal-content) capabilities in it, there was [a PR](https://github.com/getpelican/pelican/pull/2164) that I later converted to a [standalone plugin](http://mcss.mosra.cz/plugins/htmlsanity/#internal-link-expansion) that does so via a Jinja2 filter called by the theme.

**Comment by joshfuggle** [comment]
Hey @mosra thanks so much for the tip, it has helped me a lot. The knowledge that I can arbitrarily add metadata keys has transformed pelican for me. I have added three new keys to my theme: `Cover` url for a cover image, `CoverAlt` the alt string for the image, `Blurb` a piece of text which is longer than `Summary` and can used when there is more space available on the relevant pages.
You can see my theme in action here: https://www.joshfuggle.com/

**Comment by mosra** [comment]
You're welcome :) Your theme looks super nice.

I'm still hoping that I can get the related PRs (#2196, #2260) merged to make the extra metadata more usable than now. Anybody? :D

**Comment by joshfuggle** [comment]
Thanks @mosra, I am constantly changing the design, but once it is stable and I have cleaned up the code then I hope to open source it. Still got a lot of ideas to improve the overall experience. Also, since the theme expects non-standard metadata attributes you can't really just drop it in and use it immediately. This is unfortunate, but I wouldn't have achieved everything that I wanted without non-standard attributes.

**Comment by peterdesmet** [comment]
Hi, just stumbled upon this issue for something unrelated... but I also had a need for cover images in pages/articles and created a plugin: https://github.com/peterdesmet/pelican-cover-image. Works with local and linked images + can add a default image.

**Comment by justinmayer** [comment]
@joshfuggle: Were you able to find a solution to your problem here?

**Comment by joshfuggle** [comment]
Hey @justinmayer, thanks for following up on this. Yes, I did indeed! Though, somewhat convoluted.
