### ISSUE TITLE
Eliminate footnotes from post summaries (Markdown)

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2266]
Is it possible to remove the footnotes from the post summary?

In the changelog I found this: 

> "* Summaries in Markdown posts no longer include footnotes" (3.3.0 version)

But that's not so.

If there are footnotes in the summary:

* the id from the first footnotes from two articles repeats, making `id`s not unique (wrong HTML)
* The footnote's link usually don't work, because the footnote's content doesn't appear in the summary.

**Comment by avaris** [comment]
That changelog item refers to #885. A whole different issue. 

If I'm understanding correctly, I believe you're talking about a different case: **Links to the footnotes** remaining in the summary-ed portion. For clarity, those are not the footnotes. 

foo<sup>1 <- (this is identifier)</sup>

Targets of those will be the footnotes. 

Can they be removed? Sure, with enough effort :). But, you'll be modifying the html itself at that point. I suspect it'll be fragile and special cased.

**Comment by jorgesumle** [comment]
The best solution is not to have links to footnotes in the summary. I don't think that is a good idea to modify the original content.
