### ISSUE TITLE
Is it possible to have multiple slugs for a page?

### ISSUE THREAD

**Issue by sloria** [getpelican/pelican#2270]
I would like to change the slug for a page without breaking the old URL. Is it possible to assign multiple slugs to a page?

The following did not work:

```
title: Foo bar
slug: foobar, foo-bar
```

**Comment by mosra** [comment]
This plugin might be exactly what you need: https://github.com/Nitron/pelican-alias

**Comment by sloria** [comment]
Thanks @mosra ! That's exactly what I needed.
