### ISSUE TITLE
Copying static files fails when content dir has symlinks

### ISSUE THREAD

**Issue by ahmetb** [getpelican/pelican#2271]
This one is a bit complicated issue, sorry in advance.  I have the following directory structure:

- $HOME
  - `blog-builder/`
    - `pelicanconf.py`
    - `content` (symlink to `../blog-content-fake/content`)
  - `blog-content-fake/`
    - `content/`
      - `2017/` symlinked to &rarr; `../../blog-content/content/2017`
      - `images/`
        - `2017/` symlinked to &rarr; `../../blog-content/content/images/2017`
          - `foo.jpg`
  - `blog-content/`
    - `content/`

Now when I do this,

```
$ cd ~/blog-content

$ pelican content -o ./output/blog -s pelicanconf.py
WARNING: Cannot get modification stamp for /Users/ahmetb/blog-builder/content/images/2017/2017
  | 	OSError: [Errno 2] No such file or directory: '/Users/ahmetb/blog-builder/content/images/2017/2017'
CRITICAL: IOError: [Errno 2] No such file or directory: u'/Users/ahmetb/blog-builder/content/images/2017/2017'
```

For some reason it thinks  `images/2017/2017` is a real thing, but it isn't.

I think there’s the code that determines the list `staticfiles` has a bug causing this.

**Comment by ahmetb** [comment]
This is a user error. Apologies.

**Comment by mazicky** [comment]
> This is a user error. Apologies.

@ahmetb hello, I'm facing the exatly same issue, but I cannot figure it out. I have symlink'ed folder inside static folder.
What was a user error in your case? Could you share it?
