### ISSUE TITLE
Dump variables on debug

### ISSUE THREAD

**Issue by voidplayer** [getpelican/pelican#2275]
Having a double verbose debug which dump variables both CONF variables and variables used in templates would help a lot while debugging :)

**Comment by avaris** [comment]
See #1984

**Comment by rask004** [comment]
@voidplayer if #1984 resolves this, could you close this issue, please?

**Comment by justinmayer** [comment]
@voidplayer: The new `--print-settings` flag is in master and should help with debugging.
