### ISSUE TITLE
List of available metadata keywords

### ISSUE THREAD

**Issue by gDelgado14** [getpelican/pelican#2279]
Is there a list somewhere containing the set of allowed metadata keys? (Title, Date, Tags, etc ..)??

**Comment by voidplayer** [comment]
Probably is documented somewhere. But what this is what I did
* Use a non-existent metadata key
* In debug mode, pelican will crash and raise the exception
* Capture with debug program
* Examine existing variables (I dont remember the name, but theres a dict used to make the substitutions with all the valid metadata values)
* ???
* profit

**Comment by gDelgado14** [comment]
Ouu, so it looks like the snippet that @avaris shared is the set of reserved names.

I'm super down to add a section to the docs if it's deemed helpful!

**Comment by justinmayer** [comment]
@gDelgado14: Please feel free to submit a PR that would add this to the docs. Thanks!

**Comment by justinmayer** [comment]
Addressed by above-referenced PR.
