### ISSUE TITLE
Markdown for mdash

### ISSUE THREAD

**Issue by reagle** [getpelican/pelican#2281]
Whichever markdown processor pelican uses doesn't seem to support `--` or `---` or dash or emdash. Is that correct?

**Comment by jorgesumle** [comment]
You can use HTML: write an en dash with `&ndash;` and an em dash with `&mdash;`.

**Comment by justinmayer** [comment]
Pelican uses [Python-Markdown](https://github.com/Python-Markdown/markdown), so you'd need to check there. That said, Typogrify should convert `--` to an emdash via SmartyPants.

**Comment by reagle** [comment]
@mitya57 I did that, but nothing changes in the generation. Do I have to add a plugin as well?

**Comment by reagle** [comment]
@mitya57, I'm finding conflicting documentation that one should also use this:

```
MARKDOWN = {
    'extension_configs': {
        # https://pythonhosted.org/Markdown/extensions/smarty.html  
        'markdown.extensions.smarty': {},
    },
}
```

**Comment by reagle** [comment]
After updating my version of pelican it works; thanks!
