### ISSUE TITLE
[feature request] ATOM/RSS-Feed filter by language

### ISSUE THREAD

**Issue by fnadde42** [getpelican/pelican#2283]
When I'm writing posts in multiple languages, I think it would be nice if one would be able to subscribe to posts only in that language. I, for one, wouldn't want posts in my reader in foreign languages. Yay or ney?

**Comment by jorgesumle** [comment]
Then you have to provide various links. You can generate them using the option [TRANSLATION_FEED_ATOM](http://docs.getpelican.com/en/stable/settings.html#translations)

**Comment by justinmayer** [comment]
As @jorgesumle noted (thanks, Jorge!), this functionality already exists.

**Comment by fnadde42** [comment]
Uhmm.... well this was embarrasing. I went through the manual and somehow I missed this... Oh well. Case closed.

**Comment by justinmayer** [comment]
No worries. Not really your fault. We should probably have a link in Settings > Feeds that points to the aforementioned section. Otherwise, clearly it's too easy to miss.
