### ISSUE TITLE
need separate output directories for dev and publish in Makefile

### ISSUE THREAD

**Issue by svenkreiss** [getpelican/pelican#2284]
I am using `pelicanconf.py` and `publishconf.py` such that less files get produced with `make publish`. However, files would still be in the output directory from previous runs with `pelicanconf.py`.
To get the expected behavior, I had to separate my output directories for the two commands. 

Example with `OUTPUTDIRPUBLISH` added: [Makefile](https://github.com/svenkreiss/svenkreiss.github.io/blob/pelican/Makefile)

**Comment by justinmayer** [comment]
This kind of workflow is normally when one would use the provided "clean out the output folder" options.
