### ISSUE TITLE
Translated page as homepage gives erronious translations URL:s

### ISSUE THREAD

**Issue by fnadde42** [getpelican/pelican#2287]
### Pelican version
3.7.1

### Problem
I want to have a static homepage where users land and can navigate from to other pages and the blog. I set `Save_as: index.html` and it renders the site with the page with the url `/index.html` as the homepage instead of `/pages/initiative.html`. However, since I have translations to that page, it jumps to the translation at `/pages/initiative-sv.html`. That works as expected but when I try to go back to the original page, it tries to access it by going to `/pages/initiative.html` which doesn't exist since i set `Save_as` to `index.html`.

As I see it, there is two solution. Either there is some way to configure Pelican to keep track on where to get pages and to make the translation link go to `/index.html` instead of `/pages/initiative.html` or it would be to redirect the user from the homepage to the url `/pages/initiative.html` directly.

Here is what I found in docs: [**Docs:** How can I use a static page as my home page?](http://docs.getpelican.com/en/stable/faq.html?highlight=save_as#how-can-i-use-a-static-page-as-my-home-page)

### File structure, configs and logs

This is how my file structure looks like in contents:
```
├── content
│   └── pages
│       ├── initiative.md
│       └── initiative-sv.md
```
#### initiative.md
```
Title: The initiative  
Date: 2018-02-01 14:00  
Lang: en  
Slug: initiative  
Authors: me  
Save_as: index.html  
```

#### initiative-sv.md
```
Title: Initiativet
Date: 2018-02-01 14:00  
Lang: sv  
Slug: initiative  
Authors: me  
Save_as: index.html
```

[pelicanconf.txt](https://github.com/getpelican/pelican/files/1710064/pelicanconf.txt)
[publishconf.txt](https://github.com/getpelican/pelican/files/1710065/publishconf.txt)
[log.txt](https://github.com/getpelican/pelican/files/1710085/log.txt)

**Comment by avaris** [comment]
Set the `url` metadata as well. 

That FAQ (silently) assumes that there is not internal linking to the index page and more or less any links will be kind of hard coded.

**Comment by justinmayer** [comment]
If you need further assistance with this, please reach out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
