### ISSUE TITLE
How to differentiate between manual and automatic article.summary?

### ISSUE THREAD

**Issue by peterdesmet** [getpelican/pelican#2293]
For a theme I'm creating, I want to use the metadata `summary` as a lead paragraph for articles/pages:

```html
{% if article.summary %}
    <div class="lead">
        {{ article.summary }}
    </div>
{% endif %}
```

Pelican however **always** sets a summary for articles/pages, either from the metadata `summary` or from the content (using `SUMMARY_MAX_LENGTH`). Here however, I don't want to show the automatically generated summary, but only the manually set one. **Is there a way to differentiate between the two?**

---

Note: one could leave the `summary`  tag empty, but then articles in an index.html no longer get their automatic summary. I'm currently thinking of dropping `summary` altogether, and using the custom metadata tag `intro`. For index.html I will then use:

```html
{% if article.intro %}
    {{ article.intro|striptags }}<!-- from metadata -->
{% else %}
    {{ article.summary|striptags }}<!-- automatic -->
{% endif %}
```

But I'd rather use something more straightforward. 😄

**Comment by jorgesumle** [comment]
I use a [modified version](https://notabug.org/Freak-Spot/Freak-Spot/src/master/plugins/another_read_more_link) of the plugin [another_read_more_link](https://github.com/fangpeishi/another_read_more_link) for that. Read its README to learn how it works.

**Comment by avaris** [comment]
If you don't want automated summary generation, just set `SUMMARY_MAX_LENGTH = 0`. You'll get empty string instead. Then, it's basically a `{% if article.summary %}` check after that.

**Comment by peterdesmet** [comment]
@jorgesumle so for pages where I don't have a manual summary and don't want an automatic summary, I'd have to place the `<!-- more -->` at the very top of my content?

@avaris I like the automatic summary generation, I just hoped I'd be able to differentiate between automatic and manual in my theme.

**Comment by peterdesmet** [comment]
This aptly named plugin can differentiate between the two: https://github.com/getpelican/pelican-plugins/tree/master/summary with `has_summary`. Closing issue
