### ISSUE TITLE
Mixed Content with HTTPS

### ISSUE THREAD

**Issue by nonatomiclabs** [getpelican/pelican#2294]
> I apologize in advance for this long and vague issue. I have read Pelican's documentation, searched the Web and tried my best to solve it but found no answer so far. I would love to give a MWE but it is difficult as it involves serving HTTPS (which I found difficult to do locally).
> I have also asked this question [on StackOverflow](https://stackoverflow.com/questions/48888667/mixed-content-with-pelican) but I feel like it can get more attention here.

## Context

I have a Pelican blog hosted on GitHub pages. I have a CNAME record for a custom domain to point to this blog.

## The aim

I'm trying to achieve serving this blog with HTTPS, which is possible [with CloudFlare](https://blog.cloudflare.com/secure-and-fast-github-pages-with-cloudflare/) (GitHub support told me it's the only solution at the moment).

## The problem

After setting everything as indicated, I can access my blog securely but CSSs are not loaded because they are indicated as mixed content.

[![Console errors][1]][1]

However, when I look at the page source, all CSSs should be served with HTTPS (as it's included with protocol-relative URLs):

    <head>
        <meta charset="utf-8">
        ...
        <link href="//nonatomiclabs.github.io/theme/css/ipython.css" rel="stylesheet">
        <link href="//nonatomiclabs.github.io/theme/css/bootstrap.min.css" rel="stylesheet">
        <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
        <link href="//nonatomiclabs.github.io/theme/css/local.css" rel="stylesheet">
        <link href="//nonatomiclabs.github.io/theme/css/pygments.css" rel="stylesheet">
    </head>

I have tried setting Pelican `SITEURL` variable to both `//nonatomiclabs.github.io` and `https://nonatomiclabs.github.io` and this does not change anything (so the problem is not due to the use of protocol-relative URLs).

CloudFlare also has an "Automatic HTTPS Rewrites" feature which is supposed to get rid/reduce mixed content problems but does not help in my case.

## Questions

I'm not quite sure of who is responsible for the problem but I would appreciate any input on that issue, maybe someone encountered this problem already.

Precisely, my questions would be:

1. How is it possible that the browser (both Chrome and Safari at least) shows the page source with HTTPS or protocol-relative URLs but that those seem not to be respected?
2. Who is "responsible" for the problem? Pelican, CloudFlare, the browser, etc.?
3. How to solve the problem?

----

If one needs to see the code:

- the website is served at https://nonatomiclabs.com
- the source code can be found at https://github.com/nonatomiclabs/nonatomiclabs.github.io
    - the `source` branch contains the Pelican source
    - the `master` branch contains the published site)

  [1]: https://i.stack.imgur.com/n5q6i.png

**Comment by justinmayer** [comment]
Replied via S.O., as this is almost certainly unrelated to Pelican and instead caused somewhere in the interaction between GitHub Pages, CloudFlare, and associated domain re-direction.
