### ISSUE TITLE
Pelican theme rendering fails, can not find css files

### ISSUE THREAD

**Issue by ramonsuarez** [getpelican/pelican#2295]
I'm trying to change the theme of my pelican blog but after installing with `pelican-themes` and changing `pelicanconf.py` I get these errors:

> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/pygments.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/pygments.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/pygments.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/pygments.css` or variations.
> WARNING:root:Unable to find `/theme/css/screen.css` or variations.
> WARNING:root:Unable to find `/theme/css/print.css` or variations.

I've tried a few themes (Blue penguin, chunk, iris, martin, and bulrush) in 2 different computers (both running Ubuntu 17.10. I've updated pelican in virtualenv. 

The previous theme I was using (pelican-clean-blog) displays ok and without errors. Notmyidea also works fine. Both have been installed for a few months. Back then I tried some more themes and had no issues. 

I've tried installing copying the files into themes, as a git submodule and as a symlink. 

Toggling RELATIVE_URLS does nothing. 

I've not tried to publish to github-pages as there is something wrong with the html. 

My searches have not provided a solution. 

Thanks!

**Comment by justinmayer** [comment]
The `pelican-themes` tool is mainly for folks who want to use pre-built themes _without_ customizing them. If you want to customize a theme, I suggest you use the [`THEME`](http://docs.getpelican.com/en/stable/settings.html#THEME) setting.

**Comment by ramonsuarez** [comment]
Thanks, that is what I was trying to do, try some themes.
