### ISSUE TITLE
Need to uninstall and reinstall themes to see changes to theme

### ISSUE THREAD

**Issue by ramonsuarez** [getpelican/pelican#2296]
When I change the images used by the theme, any of the templates or the css none of the changes are reflected until I uninstall and reinstall the theme. 

I'm using the latest pip version of Pelican in an Ubuntu 17.10 box under virtualenv. 

The problem has been happening for a few months. 

The latest theme I've tried to update is [pelican-theme-blog](https://github.com/gilsondev/pelican-clean-blog).

**Comment by justinmayer** [comment]
Not enough information provided here to diagnose. (e.g., the precise path to the theme images that you changed, etc.). Please read the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation thoroughly and then consider reaching out via the Pelican IRC channel, as noted in those docs. Thanks!

**Comment by ramonsuarez** [comment]
Thanks @justinmayer . I have an issue with IRC: my computer or phone are not always connected, so I loose part of the conversation when I get back to it. I did try it before the new year.

**Comment by justinmayer** [comment]
You can always review the [IRC chat history](https://botbot.me/freenode/pelican/), so there shouldn't be any risk of losing any of the conversation.
