### ISSUE TITLE
Markdown extensions link is a 404 in content.rst

### ISSUE THREAD

**Issue by scarpent** [getpelican/pelican#2301]
Links to http://pythonhosted.org/Markdown/extensions/

**Comment by cupen** [comment]
It's here. https://python-markdown.github.io/extensions/

**Comment by scarpent** [comment]
Nice! I would have PR'ed it myself if I had been able to find it. Thank you! :-)

**Comment by jorgesumle** [comment]
@scarpent, I used `grep -R 'pythonhosted' docs/` to find it. [GNU grep](https://www.gnu.org/software/grep) is very useful. Maybe next time you can use it too.

**Comment by justinmayer** [comment]
Fixed via #2302
