### ISSUE TITLE
articles with duplicate slugs

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican#2303]
I have a project where a large number of articles have the same slug, and so I get swamped in warnings `There are 2 original (not translated) items with slug` so-and-so. I could either just ignore these warning or hack together some way to differentiate the slugs, like in #1427.

But I'd rather contribute a cleaner solution. I am thinking of either a setting that suppresses this warning, or a  setting that skips looking for translations altogether. Would this be desirable, and if so, which would you prefer?

**Comment by voidplayer** [comment]
Not sure if this is bug of feature

I was using the slug as a part of the url as in ```subcategory/slug``` so even tho there were many articles with the same slug, there wasnt really a url conflict

I just removed the slug and added a metadata called ```path``` and used that instead of the slug to craft the urls

No more warnings :)

**Comment by avaris** [comment]
A setting to turn off translation processing would be a fine solution.

*Warning*: This might end up being a moderate sized refactoring. Currently article ordering is embedded into translation processor. A decent solution would require decoupling them, which is the preferred behavior (at least for me :) ).

**Comment by oulenz** [comment]
@avaris I already had to decouple them in another pull request. :-) Would be great if you or someone else could review that https://github.com/getpelican/pelican/pull/2292

**Comment by oulenz** [comment]
I thought of another potential solution: give people the option (by way of a new value for ` SLUGIFY_SOURCE`) to incorporate the category of an article in its slug (e.g. `category/title`). That would even allow for otherwise duplicate slugs in combination with translations.

(Disabling translations could still be a setting independent of this.)
