### ISSUE TITLE
links in area tag are not recognized by pelican

### ISSUE THREAD

**Issue by voidplayer** [getpelican/pelican#2307]
area have an href attribute that is not being replaced

```
<area href="https://example.net ">
```

Also #2175 to look for arbitrary attributes would be nice :)

**Comment by louismin** [comment]
In my attempt to resolve this open issue, Pelican was able to reproduce the correct href attribute link. For further inspection, It will be helpful if further information concerning your particular issue is provided.

**Comment by voidplayer** [comment]
Thanks for woking on this!

how to reproduce:

- create a .md
- put ```<area href="{filename} ">```
- links dont get replaced. Pelican doesnt recognize href in areas tags as having a link 

Thats just about scanning places where links can be in html5

#2175 is also interesting. Being able to have links show up in random places

**Comment by avaris** [comment]
@voidplayer Did you literally put `<area href="{filename} ">`? `{filename}` syntax requires you to actually link to a file. That's how the URL is constructed. `"{filename} "` won't match anything and would not be replaced... By design.

**Comment by voidplayer** [comment]
No, i was actually linking to subcategories. I tried other links and they actually work in area too :)
I opened a proper issue in the plugin instead :)
getpelican/pelican-plugins#1016
