### ISSUE TITLE
More flexible implementation of slug substitutions

### ISSUE THREAD

**Issue by oulenz** [getpelican/pelican#2316]
My use case is that I want to preserve `'+'` in slugs. With respect to the setting `SLUG_SUBSTITUTIONS`, the docs say:

> `skip` is a boolean indicating whether or not to skip replacement of non-alphanumeric characters. Useful for backward compatibility with existing URLs.

I therefore expected that setting `SLUG_SUBSTITUTIONS = ((' ', '-', True, ), )` would leave slugs unchanged (except for replacing spaces by dashes), and in particular, preserve instances of `'+'`.

But I discovered to my surprise that  `skip` only takes effect if the slug was changed by any of the substitutions provided by the user.:

https://github.com/getpelican/pelican/blob/81b7e7481f78c0fe0a2ff1af169525e225df6286/pelican/utils.py#L304

What is the rationale behind this?

I would like to propose that a new setting be introduced that can be set with a list of regex replacement pairs, with the default being the current removal of non-alphanumerical characters. If you agree, I could write a PR.

**Comment by jonathan-s** [comment]
What is the reason you would like to preserve `+` in slugs? I'm curious about the underlying purpose.

**Comment by oulenz** [comment]
I have two subcategories named simply `+` and `++`, and I want that to be part of their urls. As far as I can tell `'+'` is url-safe.

**Comment by rlafuente** [comment]
Seconding this problem; I'm trying to preserve period characters (`.`) in my slugs, and the only way is to add a filler character to the category names so that they can be replaced and fill the non-matching condition. #2330 seems to be a useful fix to avoid clunky hacks.
