### ISSUE TITLE
pelican-import getting error with pandoc@2.1.3

### ISSUE THREAD

**Issue by TheMushrr00m** [getpelican/pelican#2322]
Trying to import all of my content from wordpress i am getting this error:

![screenshot_20180405_042617](https://user-images.githubusercontent.com/6392644/38357952-9f3540b2-3889-11e8-8bbb-7a0fef477fb2.png)

I am using the command:
`pelican-import --wpfile -o output laesporadelhongo.wordpress.2018-04-05.xml --dir-page --dir-cat -m markdown
`
The error it's related with the most recent pandoc's version 2.1.3 in Arch Linux.

**Comment by TheMushrr00m** [comment]
I think that changing in [this line](https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_import.py#L731) how `pelican-import` invokes to `pandoc` the errors will be resolved.

**Comment by sagamusix** [comment]
I changed the invocation of pandoc in `pelican_import.py` like this, it works with recent pandoc releases then:
```
            parse_raw = '-raw_html' if not strip_raw else ''
            cmd = ('pandoc  --from=html'
                   ' --to={1}{0} -o "{2}" "{3}"')
```

**Comment by TheMushrr00m** [comment]
@sagamusix your solution works for me.
Thanks!

**Comment by sagamusix** [comment]
Note that there is also a pending pull request which might be a bit more comprehensive and correct than my quick hack: #2289

**Comment by TheMushrr00m** [comment]
I see, but your "quick hack" was what I needed at the moment and with that I was able to resolve my situation. Thanks again.
