### ISSUE TITLE
Allow disabling DEFAULT_CATEGORY

### ISSUE THREAD

**Issue by nurupo** [getpelican/pelican#2323]
If an article author forgets to specify a category metadata, I want Pelican to fail when processing/generating that article, rather than it silently hiding the issue by using `DEFAULT_CATEGORY` for that article. The behavior I want is that setting `DEFAULT_CATEGORY` to `None` would disable the default category logic and make Pelican error on articles with no category set. Currently when setting `DEFAULT_CATEGORY` to `None` you get some internal error in Pelican, even despite all articles having `Category:` metadata.

**Comment by nurupo** [comment]
I guess `False` instead of `None` would be more in line with the other options.

**Comment by justinmayer** [comment]
@nurupo: I understand where you are coming from, but I don't think there is sufficient interest in the proposed functionality to warrant such a change. That said, perhaps a plugin could be implement to override the current behavior. Cheers.
