### ISSUE TITLE
Manually trigger generation of author pages

### ISSUE THREAD

**Issue by GillesVandewiele** [getpelican/pelican#2325]
Is it possible to trigger the generation of the author pages manually? I would like a page to be generated for each author in my `AUTHORS` dictionary, but this only gets triggered as soon as they are an author of an article.

Kind regards,
Gilles

**Comment by justinmayer** [comment]
I don't know. How long do you expect this period of time (an author without having authored any articles) will last? If it were me, I'd duplicate an existing generated author's page, hand-edit the HTML, and copy it to the server. Presumably that author will write an article soon, obviating the need for any further manual action for that particular author.

**Comment by GillesVandewiele** [comment]
Hey justin,

Avaris helped me out in IRC. Thank you for all the support.

This small plugin did the trick:

```
from pelican import signals
from pelican.urlwrappers import Author

def add_missing_authors(generator):
    # AUTHORS defined in pelicanconf
    # presumably an iterator with string keys/items as author names
    authors = generator.settings.get('AUTHORS', {})
    added_authors = set(author.name for author, articles in generator.authors)
    for author in set(authors)-added_authors:
        generator.authors.append((Author(author, generator.settings), []))

def register():
    signals.article_generator_finalized.connect(add_missing_authors)
```
