### ISSUE TITLE
no valid files when  i run `pelican content`

### ISSUE THREAD

**Issue by elseagle** [getpelican/pelican#2329]
`$ pelican content
WARNING: PLUGIN_PATH setting has been replaced by PLUGIN_PATHS, moving it to the new setting name.
/home/oluwasogo/staticblog/staticblog/lib/python3.6/site-packages/IPython/nbconvert.py:13: ShimWarning: The `IPython.nbconvert` package has been deprecated since IPython 4.0. You should import from nbconvert instead.
  "You should import from nbconvert instead.", ShimWarning)
ERROR: Cannot load plugin `ipynb.markup`
  | ModuleNotFoundError: No module named 'IPython.nbconvert.preprocessors'
WARNING: No valid files found in content.
Done: Processed 0 articles, 0 drafts, 0 pages and 0 hidden pages in 0.24 seconds.`

**Comment by thelou1s** [comment]
@elseagle  As [docs](http://docs.getpelican.com/en/3.6.3/faq.html) says, you should do this first:

` (pelican-blog) E:\Python\pelican-blog\pelican>pip install markdown`
