### ISSUE TITLE
Pelican eats double backslashes followed by apostrophe in rst files

### ISSUE THREAD

**Issue by spookylukey** [getpelican/pelican#2332]
Steps:

1. Put the following in a `.rst` content file:

    \\\\'

(That is, two backslashes followed by apostrophe)

2. Run pelican on the project.

Expected HTML output:

    <p>\'</p>

(as per the spec, http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html - this is what happens if you run rst2html.py on the rst file).

Actual HTML output:

    <p>&#39;</p>

Pelican is eating backslashes somehow.

**Comment by spookylukey** [comment]
OK, if I put `TYPOGRIFY = False` in my settings this doesn't happen.

**Comment by justinmayer** [comment]
That being the case, my guess is that this is something best addressed within the Typogrify project rather than Pelican.

**Comment by spookylukey** [comment]
This issue filed - https://github.com/mintchaos/typogrify/issues/51
Thanks.
