### ISSUE TITLE
OUTPUT_PATH ignored?

### ISSUE THREAD

**Issue by jkw** [getpelican/pelican#2333]
I have set OUTPUT_PATH = '**docs/**', but still it generates to **output/** bug or am I missing something?
Gist of my [pelicanconf.py](https://gist.github.com/jkw/49acd06b174003d6dbbaf1cbfa0cb1a9).

**Comment by jorgesumle** [comment]
It's not a bug, it works fine for me. What's the command you executed?

Next time, please read [our feedback guidelines](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) before opening an issue.

**Comment by jkw** [comment]
./develop_server.sh start 

According to the manual at http://docs.getpelican.com/en/stable/settings.html?highlight=output_path it states if setting OUTPUT_PATH in conf, that is were the generated files should be placed. What in the guidline did I miss?

**Comment by jorgesumle** [comment]
Change `OUTPUTDIR=$BASEDIR/output` to `OUTPUTDIR=$BASEDIR/docs` from the script `develop_server.sh`. The file `develop_server.sh` doesn't take into account the settings file.

**Comment by avaris** [comment]
If you're using `make` or `fabric`, they override it with command line arguments.

**Comment by jkw** [comment]
Thanks @jorgesumle & @avaris, I will try that.
Is there any other way to run the development server so that it uses the config?

**Comment by avaris** [comment]
Two terminals:
* one running pelican with autoreload: `pelican content -s pelicanconf.py --autoreload [other stuff]`
* the other from output folder: `python -m pelican.server`

**Comment by jkw** [comment]
Thanks a bunch, I'll try it out. Editing the SH-file worked btw.

Issue solved.

Den sön 22 apr. 2018 17:38Deniz Turgut <notifications@github.com> skrev:
