### ISSUE TITLE
How to use pelican together with pandoc; Add pandoc support

### ISSUE THREAD

**Issue by geniusupgrader** [getpelican/pelican#2334]
I have found some issues in the pelican repo, which mentioned pandoc.
But there is no documentation how to use pelican together with pandoc. Is it even possible?
My solution is for the moment is, that I use pandoc standalone to generate some html files and then just copying them to my content folder in pelican to use it as a page or whatever.
This solution is not optimal and pandoc should be more integrated into pelican.
Is there someone, who has tried out how to use pelican with pandoc or is there even a recommended way to use pandoc with pelican?

**Comment by avaris** [comment]
Use `pandoc` for what exactly?

`pelican` currently uses `pandoc` in the initial import process to convert existing `html` files to other supported formats (like `markdown` or `reStructuredText`).

**Comment by geniusupgrader** [comment]
@avaris  ah, yeah pandoc is used for the import process in pelican. Had forgot that.
But what I meant is as an input format for the content, so that you dont write in Markdown, but in Pandocs Markdown flavor and then when executing the command `pelican` it should runs pandoc (externally?) to convert the markdown to html or similar to render it.

**Comment by justinmayer** [comment]
@gangelop: Pelican uses the Python-Markdown library to parse Markdown-formatted source content. Given the wide variety of Markdown flavors, it is not feasible for Pelican core to support all of them. Ergo, support for any other Markdown variants is best implemented in the form of a plugin.

Have you reviewed the Pelican plugin list? It seems to me there is already a plugin related to your request. You might consider trying it, and if it does not do what you want it to do, extending/updating it such that it does.

**Comment by geniusupgrader** [comment]
@gangelop  would you mind telling me the plugin? Maybe I've overseen something..

**Comment by justinmayer** [comment]
@geniusupgrader:
1. Go to the [Pelican Plugins](https://github.com/getpelican/pelican-plugins) repo. 
2. Search the page for "pandoc"
3. Find result with "pandoc_reader" in the title

**Comment by geniusupgrader** [comment]
ok thanks, have found these three:

- https://github.com/liob/pandoc_reader
- https://github.com/marienfressinaud/Pelidoc
- https://github.com/bsmith89/pelican-pandoc-reader

So, I see this must be done with a plugin and I close this issue
