### ISSUE TITLE
Is it possible to use a different template for markdown and restructuredtext content?

### ISSUE THREAD

**Issue by FunkyLoveCow** [getpelican/pelican#2337]
My content is currently written in Markdown. I have many years worth of content in said format, I'm comfortable with it. However, I want to add some micro-data to only certain types of content - mainly the occasional review. Markdown doesn't have a nice way to do this. RestructuredText has a decent looking [plugin](https://pypi.org/project/pelican-microdata/).

My question: Can I build a template for markdown content and a template for restructuredtext content? The restructuredtext template would fit a "review" better - show the final rating is one of the big differences. 

If I can't have different templates for different input files, is there a problem using both markdown and RST files? As I mentioned, I'm comfortable with markdown and would prefer to not convert everything to restructuredtext.

**Comment by mosra** [comment]
I'm achieving a similar thing by having a template that branches on presence of a particular metadata. For example, some articles have a "cover" image, some not, which is in the reST sources done like this:

```rst
My Article
##########

:date: 2018-04-26
:cover: some-image.jpg
```

Then the Jinja2 `article.html` template just branches on presence on the `:cover:` metadata:

```html+jinja
{% if article.cover %}
   ... show the cover image on top
{% else %}
   ... or not
{% endif %}
```

[The full thing is here](https://github.com/mosra/m.css/blob/3dbd64ddbd92b00518a216c7c287794519e5cea6/pelican-theme/templates/article.html#L52), if you want to have a look.

**Comment by avaris** [comment]
Couple of different ways to go around it.

First, pelican puts the name of the reader used into a `reader` metadata. So, something like this is possible:

```jinja
{% if article.reader == 'MarkdownReader' %}
   ...
{% elif article.reader == 'RstReader' %}
   ...
{% else %}
   ...
{% endif %}
```

Or, pelican lets you to choose template used by providing a `template` metadata for the content. So, say you put `md` and `rst` into different categories and extract the folder name using `PATH_METADATA` into template metadata. And provide said named templates in the theme.

Or, you can write a simple plugin that'll do this for you based on the reader used (again probably based on the `reader` metadata).

**Comment by justinmayer** [comment]
Many thanks for the excellent suggestions here, @avaris and @mosra! Considering this one addressed.
