### ISSUE TITLE
Saving complete static file tree in root?

### ISSUE THREAD

**Issue by sagamusix** [getpelican/pelican#2338]
In my config, I have defined `STATIC_PATHS = [ 'static' ]` and I have the following directory setup:
```
static/
    robots.txt
    foo/
       bar.txt
```
Using the default `STATIC_SAVE_AS = '{path}'`, these files end up being copied to a sub directory called `static`. However, I would like them to end up in the root (where e.g. `robots.txt` has to reside), so the next thing I tried was `STATIC_SAVE_AS = ''`, but this flattens the entire static directory structure into the root (so `bar.txt` resides next to `robots.txt`).

I am having a hard time figuring out if there is some variable other than `{path}` that I can use, in particular since there does not seem to be a full list of these variables and the contexts they are available in. So I don't know if there is maybe a variable that could help me here, or if it is not possible at all to do this.

I'm using Pelican 3.7.1.

**Comment by avaris** [comment]
If the list of files isn't long, you can do that "manually" by [`EXTRA_PATH_METADATA`](http://docs.getpelican.com/en/stable/settings.html#metadata). There is even an example for similar scenario. But you need to list all files that are affected by this. Folders don't work. So anything inside `foo` will have to be listed.

Or, you can extract the sub-hierarchy via `PATH_METADATA` into a metadata and give that to `STATIC_SAVE_AS`.

Or... a plugin.

**Comment by sagamusix** [comment]
Doing it manually is sadly not an option, since files get added to that folder at irregular intervals. Hence that approach would be too error-prone.

I'll give the second option a try.

**Comment by sagamusix** [comment]
This works as intended:
```
PATH_METADATA = '(static/)?(?P<full_path>.*)'
STATIC_PATHS = [ 'static' ]
```
Thanks for the quick help!

**Comment by sagamusix** [comment]
Hmm yeah, I guess that might actually be a cleaner solution. I didn't even think of that! It might also work better with referencing those files though `{filename}`, which with the method I used above doesn't work, as far as I can see.

**Comment by sagamusix** [comment]
For anyone going the `os.walk` path (no pun intended) on Windows - it is worth noting that paths should be converted to forward slashes for `EXTRA_PATH_METADATA` to work. In the end, this is what I came up with:
```
STATIC_PATHS = []
EXTRA_PATH_METADATA = {}
static_basedir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static' + os.sep)
for root, dirs, files in os.walk(static_basedir):
    for file in files:
        dst_path = os.path.relpath(os.path.join(root, file), static_basedir).replace(os.sep, '/')
        src_path = os.path.join('static', dst_path).replace(os.sep, '/')
        STATIC_PATHS.append(src_path)
        EXTRA_PATH_METADATA[src_path] = { 'path' : dst_path }
```
