### ISSUE TITLE
{filename} does not work with directories

### ISSUE THREAD

**Issue by sagamusix** [getpelican/pelican#2339]
I would like to create a link to a directory that's part of my static folder structure. {filename} only seems to recognize files for substitutions though, not folders, i.e. `{filename}/static/foo/bar.txt` can be linked but `{filename}/static/foo/` can not. For the reference, threre is *no* index.html in that folder that I could link to as a workaround.

I'm using Pelican 3.7.1.

**Comment by avaris** [comment]
That is correct. Purpose of `{filename}` is to resolve `*_SAVE_AS` settings and point the link to where the content *will* be. That can be done on file level. Directory itself doesn't have any context for that. So. I'm not sure how that can be implemented.
