### ISSUE TITLE
Derive modification date from file modification time if `Date` is specified

### ISSUE THREAD

**Issue by sagamusix** [getpelican/pelican#2340]
When the article's original publication date is specified manually by means of the `Date` tag, the modification date is set to the same date if not specified manually. I think it would be nice to at least optionally be able to automatically set the modification date to the filesystem date instead. Semantically, this makes sense because the original publication date can be preserved by a manual tag, while the modification date will be updated automatically anytime the article is touched.

**Comment by avaris** [comment]
This would be nice idea for a plugin (if there isn't one already. I didn't check).

**Comment by sagamusix** [comment]
I made a super simple plugin (well, 99% of the code is derived from the `filetime_from_git` plugin), and it does the job:
```
# -*- coding: utf-8 -*-
from pelican import signals
from pelican.utils import set_date_tzinfo
from datetime import datetime
import os

def datetime_from_timestamp(timestamp, content):
    return set_date_tzinfo(datetime.fromtimestamp(timestamp), tz_name=content.settings.get('TIMEZONE', None))

def set_content_mtime(content):
    if not hasattr(content, 'modified'):
        content.modified = datetime_from_timestamp(os.stat(content.source_path).st_mtime, content)

def register():
    signals.content_object_init.connect(set_content_mtime)
```

Does what I need, YMMV.

**Comment by avaris** [comment]
You may want to also set `content.metadata['modified']`. We do `setattr` any metadata on content, yes, but some plugin or template out there might be using `metadata` directly. Just in case...
