### ISSUE TITLE
Organize article output into folders

### ISSUE THREAD

**Issue by skypanther** [getpelican/pelican#2342]
My apologies if this is documented somewhere or available as a plugin but I was unable to find it.

I would like to organize the generated articles into folders by year. So any articles I write this year would end up in a 2018 folder.

While the following will generate links containing the year, the output files aren't put into those folders. All the files end up in the output folder so all the links end up broken.

```
ARTICLE_URL = '{date:%Y}/{slug}.html'
```

Is this possible and what am I doing wrong?

* Pelican version 3.7.1
* Python 3.6.3
* Flex theme
* Only the tag-cloud plugin installed

**Comment by ingwinlu** [comment]
you need to specify the correct SAVE_AS settings as well

**Comment by justinmayer** [comment]
@skypanther: As @ingwinlu mentioned, that information is in the Settings section of the documentation. In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!

**Comment by skypanther** [comment]
_/me wonders why I didn't choose Jekyll, Hugo, Hexo, or ..._
