### ISSUE TITLE
Extra attributes for Tag, Category and Author

### ISSUE THREAD

**Issue by arulrajnet** [getpelican/pelican#2346]
The tag, category and author class have only following properties in current version for pelican (3.7.1)

* Name
* Slug

Ref [urlwrappers.py](https://github.com/getpelican/pelican/blob/d6ac93a4708684cf16af8226d8b536897b44b74f/pelican/urlwrappers.py#L114)

If we add more attributes to that it will be useful. For example ghost supports following properties for Tag

* Tag Image: the tag image
* Tag Name: the tag name
* Tag URL: the tag ‘slug’
* Description: the tag description, displayed on the tag archive page
* Meta Data: extra content for SEO and social media

We can get those information from pelicanconf.py 

your thoughts..?

**Comment by mosra** [comment]
There are plugins that support this functionality:

- One is mine, part of m.css: [m.metadata](http://mcss.mosra.cz/plugins/metadata/) (though it's standalone, doesn't require the theme to work) -- supports images, names, arbitrary text, Twitter Cards, OpenGraph etc.
- Another one is [autopages](https://github.com/getpelican/pelican-plugins/tree/master/autopages)
- Or there is [category_meta](https://github.com/getpelican/pelican-plugins/tree/master/category_meta) for categories, for example

**Comment by justinmayer** [comment]
@arulrajnet: Were @mosra's suggestions here sufficient for your intended use cases?

**Comment by arulrajnet** [comment]
@justinmayer I have evaluated all three. autopages and m.metadata are close to my requirement.  But all are have their own way of configuration, own way of solving the problems and learning curve.

It would be good if the core framework itself have that options.

**Comment by mosra** [comment]
I don't think this is a good idea to add this *in full* to Pelican core, especially regarding images and the "social media tags" -- there's too many and everyone might want their slightly different way of presenting them.

Maybe a stripped-down version where Pelican just provides special pages for a tag/category/author (containing just title and content and nothing else) and allows each theme to add its own metadata could be worth it. Then the users no longer need a plugin but everything can be handled just by the theme itself.

**Comment by arulrajnet** [comment]
@mosra thanks for your valuable comment. 

My thought is if the Object Model has core properties and ability to add extra information about that Object then theme can present in a nice way.

**Comment by justinmayer** [comment]
@arulrajnet: Thank you for your input. I'm not sure there is enough interest in this functionality to support its implementation. If you want to implement something in plugin form in order to address your use case, that might be best. Cheers.
