### ISSUE TITLE
Add slug as class to body tag

### ISSUE THREAD

**Issue by nerdoc** [getpelican/pelican#2348]
To apply some custom css on certain pages, I muss a html class. Drupal e.g. does this using the page machine name (=slug) as body class:

    <body class="... page-blah">
    ...
    </body>

This could be easily implemented in  Pelican...?

**Comment by avaris** [comment]
General HTML output is handled via themes. So, yes, in the theme.

**Comment by nerdoc** [comment]
Ok, that's right... ;-) Thanks.
