### ISSUE TITLE
Is it possible to access configuration variables in the articles and pages?

### ISSUE THREAD

**Issue by joshfuggle** [getpelican/pelican#2349]
Hi team,

I want to be able to access variables defined in my config file in my articles.

Heres the use case:

1. I serve my site from AWS S3
2. I would like to create a seperate bucket to host all my media, with its own cloudfront distribution
3. Media would then have it's own seperate domain
4. To prevent spamming my media server while testing, base url would be injected ...

Example:

```
# Dev
BASE_MEDIA_URL = 'http://localhost:8003'

# Production
BASE_MEDIA_URL = 'https://media.mydomain.com'
```

In the articles ...

```
.. figure:: {BASE_MEDIA_URL}/medium/coolbeans.jpg
    :alt: Cool pic
    :target: {BASE_MEDIA_URL}/large/coolbeans.jpg
```

Thanks all

**Comment by mosra** [comment]
I admit this would affect *all* static files, but why not use a different `STATIC_URL` for this? In my case I have all images, binaries, webassembly files, CSS styles etc. served from `http://static.magnum.graphics/` while the dynamic content (HTML, feeds) is from http://magnum.graphics/. This won't work with stock Pelican 3.7.1, but current `master` (in particular, #2196) should work well.

Just for completeness, in [pelicanconf.py](https://github.com/mosra/magnum-website/blob/2a4b52e34b005274e0b43f78d1f08138c22a0ffb/pelicanconf.py#L18-L19) I have:

```py
STATIC_URL = 'static/{path}'
STATIC_SAVE_AS = 'static/{path}'
```

And in [publishconf.py](https://github.com/mosra/magnum-website/blob/2a4b52e34b005274e0b43f78d1f08138c22a0ffb/publishconf.py#L11) it's overriden to:

```py
STATIC_URL = '//static.magnum.graphics/{path}'
```

**Comment by joshfuggle** [comment]
@mosra Great, yes doesn't need to be the solution I suggested if there is a better alternative.

So now that you have got the static url defined, how to you access that URL in the article and page files?

**Comment by joshfuggle** [comment]
Thanks @mosra , yeah I suspected as much. However, it still is failing with this approach when referencing a externally hosted file. The warning I am receiving [is this one](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L285), which is saying that the file does not exist inside [this 'filenames' structure](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L271). The filenames structure I believe is being [inflated here with local file paths](https://github.com/getpelican/pelican/blob/5ca1cabe78b9a67b56fdb7197861861ecc83fdec/pelican/generators.py#L758). However, since the file doesn't exist locally and is on a different host it is never placed in the filenames structure.

I have never coded in this project or debugged it before, so probably I am dead wrong and missed something really simple. Please correct me if so.

**Comment by joshfuggle** [comment]
Something else actually is the snippet:

```
.. figure:: {filename}/medium/coolbeans.jpg
    :alt: Cool pic
    :target: {filename}/large/coolbeans.jpg
```

You may notice has paths: `/medium/`, and `/large/`, rather than `/ images/`. I read that `STATIC_PATHS` defaults to [`images`](https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L41), so I swapped mine out with `["medium", "large"]`. This is correct, no? Are there any other settings changes I should make? I saw reference in the code to `RELATIVE_URLS`, but enabling and disabling made no difference.

**Comment by joshfuggle** [comment]
Something else strange to me is that [in the test case](https://github.com/getpelican/pelican/blob/2d24d6b997795f15da87e3b291977778b21f615e/pelican/tests/test_contents.py#L413), they are injecting the file url which they are testing against. But how could this url end up in the `filenames` structure in a normal situation when they exist on a remote server?

**Comment by mosra** [comment]
> However, since the file doesn't exist locally and is on a different host it is never placed in the filenames structure.

Ahh, well, the file (or at least some placeholder for it) has to exist locally for the `{filename}` replacement to work properly. Then I totally misunderstood you, sorry: thought you have the files locally and then only want to swap to a different server when publishing.

If you would have the files locally, the `STATIC_PATHS` would be everything you need to set up, yes.

**Comment by joshfuggle** [comment]
Hmm yeah I could do that - have them local in develop then swap them in production. But wouldn't setting the STATIC_URL to a remote host in the publish configuration fail as it still has to run the same generation code?

**Comment by mosra** [comment]
No. Let me explain:

1. at generation time, Pelican gathers all static files from `STATIC_PATHS`, putting them to output as defined by `STATIC_SAVE_AS`. The `STATIC_URL` is not used at this point at all.
2. the URLs containing `{filename}` survive verbatim all the way to the resulting HTML file.
3. URLs containing `{filename}` are matched in the HTML file using a complicated regex.
4. The `{filename}` in matched URLs gets replaced by a combination of `SITEURL` and `STATIC_URL` if the files referenced by them exist in the list gathered at step 1. If `STATIC_URL` is absolute, `SITEURL` gets ignored, otherwise they get concatenated. If given file doesn't exist in the list from 1, the `{filename}` URL is left as-is, without replacing anything. (In other words, `STATIC_URL` is just used on output, you can set it to absolutely anything, Pelican won't check if the location is valid or try to upload things there. That's what `STATIC_SAVE_AS` is for.)

(The above doesn't take into account additional path metadata, which can override `STATIC_URL` for particular files, but that's not the point here.)

**Comment by justinmayer** [comment]
@joshfuggle: I hope @mosra's suggestions were helpful here. If you want to continue this particular discussion, comment here and I can re-open. Cheers!
