### ISSUE TITLE
Markdown Extensions Setting for TOC Not Honored

### ISSUE THREAD

**Issue by tohuw** [getpelican/pelican#2350]
It seems my settings for the TOC Markdown plugin aren't being honored.

The relevant part of my `pelicanconf.py`:

    MARKDOWN = {
        'extension_configs': {
            'markdown.extensions.toc': {
                'marker': '[TOC]',
                'title': 'Contents',
                'anchorlink': True,
                'permalink': True,
                'baselevel': 2,
            },
        }
    }

Rather than honoring these settings, the defaults are always used.

**Comment by ingwinlu** [comment]
Before I have a look at it, can you at least expand your issue with the information [listed as required](https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst#how-to-get-help).

Especially interesting would be version numbers of pelican and python-markdown.

**Comment by tohuw** [comment]
Sorry:
Pelican 3.7.1
Markdown 2.6.9

I will also create a clean Pelican environment as a repo and attempt to re-create the issue. I apologize for the incomplete submission. Thanks!

**Comment by tohuw** [comment]
This won't surprise you @ingwinlu, but my test found the problem is in my implementation. [The simple TOC options test I created](https://github.com/tohuw/pelicanmdoptionstest) works as expected.

To save others who might run into this at some point, I'll spend some time now fixing it and report back on what my actual issue was. If I can't find it soon enough, I'll close this as CNR to save you the open issue. Thanks!

**Comment by tohuw** [comment]
Turns out if I had followed the proper discipline here, I'd have found this was solved by an outdated extension. In case someone else ends up with this exact or nearly same issue, [the details of my MD options not being honored in pelicanconf.py are here](https://gitlab.com/tohuw/tohuwnet/issues/1).
