### ISSUE TITLE
Tags translations aren't translated

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2361]
Pelican doesn't generate tags for translations, producing 404 HTTP errors.

Let's say I have this article...

```
Title: Etikedo
Date: 2018-06-23 20:57
Tags: etikedo
Slug: etikedo

Reta etikedo
```

and the following translation...

```
Title: Tag
Date: 2018-06-23 20:57
Tags: tag
Slug: etikedo
Lang: en

Tag
```

The `tag` HTML page won't be created, but links will appear, causing 404 HTTP errors.

**Comment by avaris** [comment]
This is mostly intentional (see #219 and #810). Otherwise you'll get duplications. I'd suggest `i18n_subsites` plugin.

**Comment by jorgesumle** [comment]
> I'd suggest i18n_subsites plugin.

Thanks to your suggestion I solved my issue
