### ISSUE TITLE
Use a faster markdown parser

### ISSUE THREAD

**Issue by jonathan-s** [getpelican/pelican#2362]
There are some benchmarks here -> https://github.com/commonmark/cmark/blob/master/benchmarks.md

And python markdown doesn't do great in that comparison. A suggestion would be to look into importing a markdown parser from a lower level language such as rust. That could significantly improve the speed when you've got a lot posts that needs to be rendered.

**Comment by avaris** [comment]
Do you have any benchmarks where the parser is indeed a significant bottleneck? 

From my memory on previous benchmarks, parser times were not that critical.

**Comment by gstein** [comment]
Please take a look at issue #2387 ... my `gfm_reader.py` uses GitHub's fork of the commonmark library, and calls into it via ctypes. If the non-forked library has the same API (??), then it should work fine.

**Comment by lambdaq** [comment]
I think it's suitable for a plugin.

**Comment by justinmayer** [comment]
If someone would like to run and provide detailed benchmarks that show an alternate Markdown parser would provide very significant performance gains, we could then re-open this issue and discuss it further.
