### ISSUE TITLE
Maybe release next version. 

### ISSUE THREAD

**Issue by jbzdak** [getpelican/pelican#2363]
3.7.1 was released year and half ago, and a lot of good stuff landed in master in the meantime. Could you please release? 

Is any help needed with the release?

**Comment by jorgesumle** [comment]
See #2162

If you need the latest features you can execute `pip install -U git+https://github.com/getpelican/pelican`.

**Comment by justinmayer** [comment]
Please feel free to lend a hand, as noted in the issue Jorge linked to.
