### ISSUE TITLE
Allow slug translations

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2364]
> Pelican uses the article’s URL “slug” to determine if two or more articles are translations of one another.

Translations are identified with slugs. That means you cannot have translations with different slugs. Because of this limitation, I also get warnings like `WARNING: There are 3 original (not translated) items with slug "slug"` when using the [i18nsubsite plugin](http://github.com/getpelican/pelican-plugins/tree/master/i18n_subsites).

I propose adding an optional `id` metadata, so that we don't depend slugs to identify translations. `id`s could have the value of slug by default to be backward compatible. Of course, when solved, we should add that information to the [translation section](http://docs.getpelican.com/en/stable/content.html#translations) of the documentation.

**Comment by oulenz** [comment]
To rephrase what @mosra said: `slug` really is the `id` metadata you are looking for.

**Comment by jorgesumle** [comment]
All in all, what I want to do requires setting both `save_as` and `url` to the URL translation.
