### ISSUE TITLE
More detailed config file needed for pelican-quickstart.

### ISSUE THREAD

**Issue by ruttydm** [getpelican/pelican#2382]
I am creating a blog using pelican but I think there is really a need for a more thoroughly config file. 
Maybe it is possible to add some other options that are commented out.

**Comment by jorgesumle** [comment]
See the [Settings section of the documentation](http://docs.getpelican.com/en/stable/settings.html). Next time read [filling issues](http://docs.getpelican.com/en/stable/contribute.html#filing-issues), this issue tracker is only for bug reports.

**Comment by justinmayer** [comment]
@ruttydm: If you need specific assistance, please reach out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
