### ISSUE TITLE
Move FeedBurner docs to Wiki

### ISSUE THREAD

**Issue by jorgesumle** [getpelican/pelican#2386]
There is a recommendation to use a proprietary service called FeedBurner in the [settings page](http://docs.getpelican.com/en/stable/settings.html) of the documentation, which I don't think it's relevant. I vote to keep advertisements of third party tools out of the documentation to ease maintenance and to keep it focused, or at the very least move them to the [Tips page](http://docs.getpelican.com/en/stable/tips.html) or to the [Wiki](https://github.com/getpelican/pelican/wiki/Tips-n-Tricks) (I prefer the wiki, because everyone can add their tips and recommendations there).

What do you think?

**Comment by justinmayer** [comment]
I added those docs when I first started using Pelican six years ago. A lot has changed since then.

While the cited paragraph is neither an advertisement nor a recommendation, I agree that these docs should be moved to the wiki. A pull request to that effect would be welcome.

**Comment by askpatrickw** [comment]
https://github.com/getpelican/pelican/wiki/FeedBurner-Configuration
