### ISSUE TITLE
additional entries in html header 

### ISSUE THREAD

**Issue by vv01f** [getpelican/pelican#2399]
Besides additional `meta` tag via the `name` attribute I could not find how to add e.g. tag with the attribute `http-equiv` for the purpose of e.g. forwarding. 

Any advise on how to accomplish the same in pelican without javascript?

**Comment by mosra** [comment]
You should be able to do that by modifying the template to treat a specifically-named metadata as a http-equiv entry.

The relevant portion of the `article.html` template could look like this:

```html
<html>
<head>
  ...
  {% if article.forward_url %}
  <meta http-equiv="refresh" content="0;URL='{% article.forward_url %}'" />
  {% endif %}
</head>
...
</html>
```

And then your article source like this, if it's in reST (note the `:forward_url:`  metadata):

```rst
An article
##########

:date: 2018-09-12
:forward_url: https://there.you.go/this/place/

...
```

*or*, in case your article source is in HTML (I guess that's your case?), it'll look like this (yes, it's may look unusual):

```html
<html>
<head>
  <title>An article</title>
  <meta name="date" content="2018-09-12" />
  <meta name="forward_url" content="https://there.you.go/this/place/" />
  ...
```

A similar approach could be used for pages.

Shameless plug: if you just need to have multiple URLs for an article, I have an [alias plugin](http://mcss.mosra.cz/plugins/links/#aliases) that makes this a lot easier -- just specify the additional URLs the article should be available at and it'll generate redirect files for them.

**Comment by justinmayer** [comment]
@mosra: Many thanks for your assistance with helping with @vv01f's query!
