### ISSUE TITLE
Simple theme places pages or categories, but not both, on nav bar.

### ISSUE THREAD

**Issue by greeder59** [getpelican/pelican#2404]
There is a logic error in the base.html file of the simple theme. It prevents Pelican from placing links to both static pages and categories on the menu bar.  You get one  or the other, not both.

I know how to fix this. How would you like me to go about it?

**Comment by rask004** [comment]
@greeder59 Gordon this is likely an issue with the simple theme in [pelican-themes repository](https://github.com/getpelican/pelican-themes). 

you could open a new issue in that repository, checkout a new branch from master (in your fork of pelican-themes), make your changes and then submit a pull request. It will be reviewed when possible.

**Comment by justinmayer** [comment]
@rask004: There are two themes that are "bundled" with Pelican: `simple` and `notmyidea`. I believe Gordon is referring to the bundled `simple` theme.

@greeder59: Thank you for tracking down the problem. Would you be willing to submit a pull request with your proposed fix?

**Comment by greeder59** [comment]
Indeed I am referring to the bundled Simple theme. There doesn't appear to be a Simple theme in the pelican-themes repository. Just a Simple-bootstrap theme. But it uses different logic for building it's nav bar. So, nothing to change there.  I'm a bit slammed right now; Planning a party for this weekend. I'll work on getting the fix done when I have some free time on Sunday

**Comment by avaris** [comment]
You don't need to assign the issue. Just create a PR stating that it's a fix for this one.

**Comment by greeder59** [comment]
Changes made, Pull request generated. I'm a newbie at this. I hope I did everything correctly.

**Comment by justinmayer** [comment]
Fixed by #2424.
