### ISSUE TITLE
Gather all articles' tags for a category?

### ISSUE THREAD

**Issue by sprnza** [getpelican/pelican#2405]
Hi there!
Is there an easy way to gather all articles' tags in category.html template? Since there is no category.tags variable available I think I'll need something like this (in jinja2 syntax obviously):

```
taglist=[]
for article in articles:
    for tag in article.tags:
        if tag.name not in taglist:
             taglist.append(tag)
```

Look cumbersome, maybe there is another way to achieve this? Or does it sound like a feature request? Or an idea for a plugin?

**Comment by sprnza** [comment]
Another related idea is if I click on a tag on a category page to get only articles belonged to the category.

**Comment by oulenz** [comment]
To me this sounds like an idea for a plugin, since adding this to the main code would essentially boil down to adding a fork in the code and a setting that controls which branch is executed, corresponding to whether a user wants this or not.

**Comment by avaris** [comment]
I agree with the plugin option, but I don't think your second option is suitable for a static generator. To work that out you'd need a separate index (a.k.a seperate file or files if paginated) for each `tag + category` pair.

**Comment by rask004** [comment]
@sprnza For both ideas I'd suggest popping over to [pelican-plugins](https://github.com/getpelican/pelican-plugins), and opening a new issue there as a feature suggestion (one per idea).

Of course you can fork pelican-plugins and start working on plugins for your ideas.

The first idea can definitely be done. 

The second idea would require some kind of filtering to replace the nominal category list with the tag-related one. And a visitor might want to go to the tag page of that tag, not a page for only related categories, so maybe a means to switch it off dynamically is needed too.

**Comment by justinmayer** [comment]
Thanks for the helpful comments, everyone!

@sprnza: If you are interested in implementing this functionality in the form of a plugin, please feel free to submit a pull request in that repository.
