### ISSUE TITLE
UnicodeDecodeError in pelican/cache.py line 35

### ISSUE THREAD

**Issue by mcepl** [getpelican/pelican#2409]
When switching local pelican installation from Python 2 one to the Python 3 one, it breaks on incompatible pickle formats.
```
/home/matej/archiv/knihovna/blog/develop_server.sh restart
Stale PID, deleting
Stale PID, deleting
Starting up Pelican and HTTP server
/usr/bin/python: No module named pelican
DEBUG: Pelican version: 3.7.1
DEBUG: Python version: 3.6.5
DEBUG: Adding current directory to system path
DEBUG: Temporarily adding PLUGIN_PATHS to system path
DEBUG: Loading plugin `zot4rst.pelican_plugin`
DEBUG: Registering plugin `zot4rst.pelican_plugin`
DEBUG: Restoring system path
DEBUG: Missing dependencies for md, markdown, mkd, mdown
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---

-> Modified: content, theme, settings, [static]images. re-generating...
The HTTP server didn't start. Is there another service using port ?
make: *** [Makefile:99: devserver] Chyba 1
~/Dokumenty/clanky/blogposts/research
matej@stitny: research (master *+%)$ CRITICAL: UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/pelican", line 11, in <module>
    load_entry_point('pelican==3.7.1', 'console_scripts', 'pelican')()
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 465, in main
    pelican.run()
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 160, in run
    ) for cls in self.get_generator_classes()
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 160, in <listcomp>
    ) for cls in self.get_generator_classes()
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 277, in __init__
    super(ArticlesGenerator, self).__init__(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 217, in __init__
    **kwargs)
  File "/usr/lib/python3.6/site-packages/pelican/generators.py", line 50, in __init__
    self.readers = Readers(self.settings, readers_cache_name)
  File "/usr/lib/python3.6/site-packages/pelican/readers.py", line 479, in __init__
    caching_policy, load_policy,
  File "/usr/lib/python3.6/site-packages/pelican/cache.py", line 87, in __init__
    load_policy)
  File "/usr/lib/python3.6/site-packages/pelican/cache.py", line 37, in __init__
    self._cache = pickle.load(fhandle)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd4 in position 1: ordinal not in range(128)
```

This [patch](https://github.com/getpelican/pelican/files/2401620/fix-python3-incompatibility.patch.txt) describes and fixes the problem.

I haven't included any tests, but these [pickles](https://github.com/getpelican/pelican/files/2401615/pickles.zip) break python3 ``pickle``.

**Comment by justinmayer** [comment]
Thank you for the contribution, @mcepl. The above output appears to come from version 3.7.1 instead of current master. The problem may be the same in both cases, but just to be certain, would you please test on current master and confirm the problem — and your proposed solution — are both still relevant?

**Comment by mcepl** [comment]
Sorry, I have fixed my problem and shared a solution with you. If you cannot be bothered to check for yourself, I have too much to do.

**Comment by justinmayer** [comment]
I'm not convinced that kind of tone was warranted or necessary, but taking the time to report the issue and propose a solution is nonetheless appreciated.

**Comment by mcepl** [comment]
I am sorry, but I am filling tens of reports with patches weekly (to be on the conservative side), and half of the maintainers first question how to make me to do more for them: either how can I just attach the patch and not made my own fork and proposed pull request, or like you. It is getting a bit tiring. Yes, you are right, that tone was probably not warranted just for you.

**Comment by mosra** [comment]
@Okroshiashvili it's [this line](https://github.com/Okroshiashvili/Jupyter-Notebooks/blob/469f782fe4b704fd384f506a98a2c309296d727b/Linear%20Algebra/Linear%20Algebra%20-%20Intermediate.ipynb#L14), right? To me it looks like the default locale or encoding setting is incorrect. Do you have a `pelicanconf.py` file? Can you try setting the [LOCALE](http://docs.getpelican.com/en/stable/settings.html#LOCALE) setting there to this?

```py
LOCALE = ('ka_GE.utf8', 'en_US.utf8')
```

It's a wild guess and I'm not using ipynb files myself, sorry in advance if it doesn't help :)

**Comment by Okroshiashvili** [comment]
Thanks a lot, @mosra that works for my case perfectly.

**Comment by justinmayer** [comment]
@avaris: Do you have any thoughts on the fix @mcepl proposed in this issue?

**Comment by justinmayer** [comment]
So the proposed fix for this issue is to replace [this line](https://github.com/getpelican/pelican/blob/bf85991ee648665f2abc224b9d3719c27470e696/pelican/cache.py#L36) with:

    except (IOError, OSError, UnicodeDecodeError) as err:

How relevant is this in a Python 3-only world?

**Comment by avaris** [comment]
This happens when you have a cache from `python2` and try to use it in `python3`. This might be relevant for the immediate future since we went `python3-only` and people (who were on python2) wanting to upgrade *must* switch to `python3`.

**Comment by justinmayer** [comment]
Fixed via 3031ca64. Many thanks to @mcepl for tracking down a solution for this error and to @avaris for pointing out its continued relevance.

**Comment by justinmayer** [comment]
Leaving this here in case anyone wants to dunk on `pickle` in the future: https://nedbatchelder.com/blog/202006/pickles_nine_flaws.html

**Comment by avaris** [comment]
Second one bite us before :).
