### ISSUE TITLE
Dividing rst content in parts

### ISSUE THREAD

**Issue by mauriciogardini** [getpelican/pelican#2410]
Is there a way to achieve this with Pelican?

theme/templates/article.html
```
(...)
<div id="content-wrapper">
{% block content %}
    <div id="content1">
        {% block content1 %}  
        {% endblock %}  
    </div>
    <div id="content2">
        {% block content2 %}
        {% endblock %}
    </div>
    <div id="content3">
        {% block content3 %}
        {% endblock %}
    </div>
{% endblock %}
</div>
(...)
```

content/test.rst (with some added logic/division of content, which is what I'm looking for)
```
Test
####

:date: 2018-01-22 19:16
:modified: 2018-01-22 19:16

Content 1

Content 2

Content 3
```

After making the build, it would result in:

test.html
```
<div id="content-wrapper">
    <div id="content1">
        Content 1
    </div>
    <div id="content2">
        Content 2
    </div>
    <div id="content3">
        Content 3
    </div>
</div>
```

My content file has all the information that I need, but it needs to be semantically separated on my template file. Is there a way to divide my information in parts?

Or, is there any (not that ugly) way to achieve what I want?

Thanks!

**Comment by oulenz** [comment]
One thing I have done in a project of mine is store the different pieces of content as separate articles, with the same category, and then don't generate articles (`ARTICLE_SAVE_AS = ''`), just the category pages. In fact, I was using subcategories (with a plugin), so I still had some categorisation on top of this. Depending on how your content is structured and whether you need tags or period archives, you could try to repurpose those for this as well.

**Comment by mauriciogardini** [comment]
> One thing I have done in a project of mine is store the different pieces of content as separate articles, with the same category, and then don't generate articles (`ARTICLE_SAVE_AS = ''`), just the category pages. In fact, I was using subcategories (with a plugin), so I still had some categorisation on top of this. Depending on how your content is structured and whether you need tags or period archives, you could try to repurpose those for this as well.

Good idea, indeed. So, in my example, my article would be divided in 3 articles.

But I think that, for my use case, it would result in a kinda hectic content page. Imagining that, if I have 100 articles, it would be needed 300 article files to create them.

I was doing some research and I discovered jinja2content (https://github.com/getpelican/pelican-plugins/tree/master/jinja2content). I'm not sure yet, because I didn't have time to test it yet, but I think that this plugin will solve my problem.

The reason for me to want to divide my content in parts is to not bring HTML markup to my .rst file. But, by using jinja2content, looks like that I can do something like this:

content/test.rst
```
Test
####

:date: 2018-01-22 19:16
:modified: 2018-01-22 19:16

{% from 'contents.html' import content1 %}
{{ 
Content 1
Content 1
Content 1
}}

{% from 'contents.html' import content2 %}
{{ 
Content 2
Content 2
Content 2
}}

{% from 'contents.html' import content3 %}
{{ 
Content 3
Content 3
Content 3
}}
```


contents.html
```
{% macro content1(content) -%}
<div id="content1">
  {{ content }}
</div>
{%- endmacro %}

{% macro content2(content) -%}
<div id="content2">
  {{ content }}
</div>
{%- endmacro %}

{% macro content3(content) -%}
<div id="content3">
  {{ content }}
</div>
{%- endmacro %}
```


theme/templates/article.html
```
(...)
<div id="content-wrapper">
{% block content %}
{% endblock %}
</div>
(...)
```


test.html
```
<div id="content-wrapper">
    <div id="content1">
        Content 1
        Content 1
        Content 1
    </div>
    <div id="content2">
        Content 2
        Content 2
        Content 2
    </div>
    <div id="content3">
        Content 3
        Content 3
        Content 3
    </div>
</div>
```

I will do some testing when I have time, but I hope to be able to do this. If yes, it will be enough to solve my problem.

**Comment by mauriciogardini** [comment]
Unfortunately I wasn't able to achieve what I wanted with the code above.

A lot of errors would happen when I tried to build (like `/var/folders/m8/prl4d8n16xv58mqr07cfb42w0000gn/T/tmp94vxvw4b:25: (WARNING/2) Definition list ends without a blank line; unexpected unindent.`) and, when I finally managed to build it (basically, by stripping parts out), the resulting HTML I got was this:

```
<dl class="docutils">
<dt>&lt;div&nbsp;id=”content1”&gt;</dt>
<dd>&lt;h1&gt;Content&nbsp;1&lt;/h1&gt;</dd>
</dl>
```

It looks like it didn't treated the above code as raw HTML, and considered it a comment or something like that.

As I really have no clue on how to solve that, I'll give up on this idea for now.

If anyone reading this can see the problem on my approach, please, tell me.

**Comment by mosra** [comment]
What's exactly the "Content 1" / "Content 2" / "Content 3" you are talking about? Could these be just headings? In [m.css](http://mcss.mosra.cz) I'm having a custom HTML writer that causes each heading in the reST source to be put in a separate HTML `<section>`, so basically the following source:

```rst
A page
######

Content 1
=========

Text 1.

Content 2
=========

Text 2.

Content 3
=========

Text 3.
```

is turned into this:

```html
<h1>A page</h2>
<section id="content-1">
  <h2>Content 1</h2>
  <p>Text 1.</p>
</section>
<section id="content-2">
  <h2>Content 2</h2>
  <p>Text 2.</p>
</section>
<section id="content-3">
  <h2>Content 3</h2>
  <p>Text 3.</p>
</section>
```

I'm then using that to highlight active sections (for example [like here](http://mcss.mosra.cz/pelican/theme/#extra-css)) and other things. I think this is sufficiently close to what you want to achieve and further modifications could be done by implementing a [docutils Transform](http://docutils.sourceforge.net/docs/ref/transforms.html) (for example removing the headings etc.). and adding that as a Pelican plugin. If you really need these to be separate for the template, it should be also possible to take the parsed docutils tree (before it gets turned into HTML), again for example in the Transform implementation, split it into in three (or however many) parts and then render each part as HTML and expose it to the template separately. But then you will probably lose things like internal references between the parts. 

Sorry that I'm handwaving this a bit, there's no real docs or tutorials on how to operate docutils so you would need to experiment and figure out some of things ;) Had to do that myself as well.

**Comment by ingwinlu** [comment]
i did a single page theme for pelican some years ago. maybe you can find inspiration on how to achive what you want there:
https://github.com/ingwinlu/pelican-GRAYSCALE

**Comment by justinmayer** [comment]
What do you think, @mauriciogardini? Did any of the responses here provide you with sufficient guidance?

**Comment by mauriciogardini** [comment]
Sorry for taking so long to answer, @justinmayer . Had to stop working on my side project and forgot to answer here.

Well, I think the answers here provided a very interesting discussion, proposing solutions to problems that are similar to mine.

As for me, for now, I took the "ugly way" and used metadata to store the information I needed. Far from ideal, but got the job done.

Thank you all for all the answers!
