### ISSUE TITLE
Site with error "Your connection is not private" only while using https in URL.

### ISSUE THREAD

**Issue by KedarKalambe** [getpelican/pelican#2411]
My website loads with the https sign if I try to access it using just the link prekshaconsultants.com however if i try https://prekshaconsultnats.com it gives the red triangle with "!" mark error in Chrome saying "your connection is not private" 
I have loaded my css and img assets in my index.html with https://prekshaconsultants.com/css/style.css and same for images still the issue persists. Please assist. Thanks in advance. 
My project folder link is : https://github.com/KedarKalambe/PrekshaConsultantsOfficial/
Also the http://prekshaconsultants.com works perfectly fine and further the link loads with https sign.

I am using domain from godaddy. Following are the current DNS records:-

Type | Name | Value | TTL | 
-- | -- | -- | -- |
A | @ | 192.30.252.153 | 600 seconds | 
A | prekshaconsultants.com | 184.168.131.241 | 600 seconds |  
CNAME | www | kedarkalambe.github.io | 600 seconds|

**Comment by bortzmeyer** [comment]
Nothing to do with Pelican. Your browser tells you the reason (here, Firefox) : "The certificate is only valid for the following names: *.github.com, github.com, *.github.io, github.io "

**Comment by KedarKalambe** [comment]
@bortzmeyer I don't follow
