### ISSUE TITLE
Some "convention over config" ideas for faster hands-on of Pelican

### ISSUE THREAD

**Issue by lambdaq** [getpelican/pelican#2413]
1. Provide an `pelican new` command for bootstrapping an example folder structure for new static sites
2. use `pelican config` for a step-by-step wizard style config generator.
3. `pelican .` should scan `.md` by default, prompt users to `pip install Markdown`. Instead of silently exit with "WARNING: No valid files found in content.". It's hard to catch this step in wall of text help docs.
4. Should have a default config for `PATH = 'content'` for less confusion. Because when users run `pelican .`  again, it will scan the `output` folder and get something stupid like 

        WARNING: Meta tag in file pelican_test/output/archives.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
        ERROR: Skipping output/archives.html: could not find information about 'date'
        WARNING: Meta tag in file pelican_test/output/authors.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"
        ERROR: Skipping output/authors.html: could not find information about 'date'
        WARNING: Meta tag in file pelican_test/output/categories.html does not have a 'name' attribute, skipping. Attributes: charset="utf-8"   

5.  For an article/page without the `Date` metadata, we should use posix file `mtime` as a substitute, and show a warning for them. (Or even better, a `--fix-date` to automatically add to source article/page)

The goal is to provide users with a *working site out of the box*, be ready to browse as fast as possible, as few obstacles as possible, cost only the minimal amount of action. But users can always config further.

If these ideas looks OK to maintainers, I can submit a PR for this.

**Comment by avaris** [comment]
1. `pelican-quickstart`
2. `pelican-quickstart`
3. #2310 (and documentation)
4. I'm not sure why would someone run `pelican .` as first thing... But having a default `PATH = 'content'` means nothing in this case. Command line arguments supersede defaults and the settings file. You'll have same result regardless.
5. `DEFAULT_DATE = 'fs'`

**Comment by lambdaq** [comment]
Thanks. I didn't know `pelican-quickstart`  until now. Gotta recommend that.
