### ISSUE TITLE
How about getting rid of 'siteurl' value in internal links?

### ISSUE THREAD

**Issue by jungsubk** [getpelican/pelican#2418]
How about getting rid of 'siteurl' value in internal links, so we could distinguish between internal links and external links by CSS. (eg. a[href^=http] {....})

**Comment by avaris** [comment]
`RELATIVE_URLS =True`

**Comment by jungsubk** [comment]
I see your point, @avaris, but I'm afraid it causes lots of '../..' things.
I'd like to keep href property tidy.

**Comment by rask004** [comment]
You can refer internal links to other articles using the {filename} variable.
Additionally (depending on host and site setup), statics can be referred to from root ('/') if specified in STATIC_PATHS and EXTRA_PATH_METADATA.

**Comment by rask004** [comment]
Also consider that a difference between internal and external links, is internal links refer to the site in the siteurl. So you could try CSS like:

`a[href^={{ SITEURL }}/] {....}`

though you would have to put this in a `<style> ` tag within the base file of the theme, or maybe in your articles / pages.

**Comment by avaris** [comment]
FYI, your `SITEURL` can also be protocol relative (`'//example.com'`) or root relative (`''`, `'/blog'`, etc.)

**Comment by jungsubk** [comment]
`a[href^={{ SITEURL }}/] {....}`

Problem solved!
Thanks! :-)
