### ISSUE TITLE
Markdown in title

### ISSUE THREAD

**Issue by fancsali** [getpelican/pelican#2419]
At first sight it does not make sense, but that would allow us to use the same extensions (e.g. Smarty) in a consistent way; so one would be able to type ```---``` to have ```@emdash;``` in the final output.

**Comment by justinmayer** [comment]
Much easier to just type the `—` m-dash directly in the title. Any other use cases that would warrant supporting Markdown in the title?

**Comment by avaris** [comment]
`TYPOGRIFY = True`
(see [typogrify](https://github.com/mintchaos/typogrify))

**Comment by justinmayer** [comment]
Ah, that's right. As @avaris mentioned, Typogrify should address this.

**Comment by fancsali** [comment]
All fair points, however:

- Typing an em-dash, is not that easy after all. Also, in theory we could type everything, since we're using UTF-8, but for practicality reasons we chose Markdown. But to be honest, the inconsistency was the reason, I felt this might be a reasonable suggestion.
- Trust me, I did try enabling Typogrify, but unfortunately that is a rather old version, and I couldn't find any way to pass arguments/config settings to that. And thus, I was unable to type an en-dash for example. I felt, the 'Smarty' filter that comes with Markdown is much more flexible, and up-to-date.

I do accept, there are other ways, and from a non-Markdown-only perspective it does make sense to structure the system as it is at the moment. I just felt, it might be worthwhile thinking about this aspect as well.

**Comment by justinmayer** [comment]
I agree that it's a reasonable enough suggestion to put forth. Like most software development, it's a question of costs and benefits. On macOS, for example, shift-option-hyphen produces an em-dash, so it's a quick way of addressing that need (on that platform, anyway). Absent other use cases, it's hard to conjure up the motivation to prioritize adding Markdown processing to titles.

I'm also one of the maintainers of Typogrify, so if you'd like to help improve it and make it do what you want it to do, I'd happy to try my best to review any contributions and help get them merged.

**Comment by avaris** [comment]
@fancsali 
[`default`](https://pythonhosted.org/smartypants/reference.html#smartypants._Attr.default) for `smartypants` is to only convert `--` into `em-dash`. Add this to your settings file:
```python
import smartypants
smartypants.Attr.default = smartypants.Attr.set2
```
Then `--` should be `en-dash` and `---` should be `em-dash`. With that, following markdown content:
```markdown
Title: A---markdown--powered article
Date: 2018-01-01

Content
```
generates
```
A—markdown–powered article
```
with source
```html
A&#8212;markdown&#8211;powered&nbsp;article
```
