### ISSUE TITLE
pelican-importer: pandoc check **eats all content** before it is written

### ISSUE THREAD

**Issue by stuaxo** [getpelican/pelican#2448]
fields2pelican is passed a generator called 'fields'
https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_import.py#L768

The check to see if pandoc is needed uses the 'in' operator consuming this
https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_import.py#L744

The loop afterwards is passed the now empty generator and so won't write any files
https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_import.py#L784-L785

**Comment by avaris** [comment]
Wait, what? 

You're correct obviously but, that code doesn't make sense at all. 
First, `filter` in python 3 is a generator. Using that in an if basically saying `if True:`. So, in python 3, this will "work", since that filter won't consume anything until it was looped. But this will always require `pandoc`, whether or not it was needed.

**Comment by avaris** [comment]
Also, it is a bit dirty that the tests are doing [`list(...)`](https://github.com/getpelican/pelican/blob/master/pelican/tests/test_importer.py#L94-L95) so that this won't be noticed :confused: : .

**Comment by stuaxo** [comment]
That's a good reminder, I probably should recreate my virtualenv as python3.7 :)

I thought removing the list would slow things down, but actually the tests run faster, patch incoming...

**Comment by stuaxo** [comment]
Updated the above PR, removing ```list(...)``` from setup in tests for WP importer and Blogger import (for consistency)

Before patch:
```Ran 26 tests in 3.212s```

After patch:
```Ran 26 tests in 2.354s```

Seems like a win.
