### ISSUE TITLE
Wordpress import - draft pages import as '-'

### ISSUE THREAD

**Issue by stuaxo** [getpelican/pelican#2454]
This is the bug for PR https://github.com/getpelican/pelican/pull/2447

Draft WP pages can have no slug yet, or it can just be spaces somehow.

Thus you can end up with at least one file called '-.md' after importing.

It would be great if this can be applied, I'd forgotten how annoying a file just called '-.md' can be in a folder, it makes it really difficult to use wildcards for stuff like grep :(

**Comment by stuaxo** [comment]
Let me know if having a bug and PR is excessive, seemed like a good idea to note what bug some of these PRs help with.

**Comment by mosra** [comment]
I think just having the bug clearly described in the PR itself is enough. Having both a PR and an issue opened at the same time for the same thing is in my opinion a bit too much noise in which other things get drowned ;)
