### ISSUE TITLE
pelican serve: Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2459]
Executing:

    pelican serve

Then visiting the Pythonized test server using:

    firefox http://localhost:8000/

resulted in the following Firefox 61 error:

    Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://arca.egbert.net/blog/theme/font/fa-solid-900.woff2. (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘https://example.com/*’).

Looks like we have to add additional headers to the Pythonized web server.

**Comment by egberts** [comment]
Nevermind, I had inadvertly added `{{ SITEURL }}` in my own template `url=`.

Once removing the `{{ SITEURL }}` from my template, the ability to support both RELATIVE_URL or not now works.

**Comment by justinmayer** [comment]
I use two settings files, for local dev and production deployment, respectively. If you set `SITEURL = ""` in your local dev settings file, you may find your CORS issue subsides.
