### ISSUE TITLE
Could not process *.rst

### ISSUE THREAD

**Issue by edmondchuc** [getpelican/pelican#2460]
Hi guys,

I've just started using Pelican and it works great when the content is written in markdown, however, it fails to perform `pelican content` for any content written in reStructured Text (.rst). 

The error is:

```python
(venv) C:\Users\edmon\PycharmProjects\blog-site>pelican content
ERROR: Could not process .\test.rst
  | SystemMessage: C:\Users\edmon\PycharmProjects\blog-site\content\test.rst:: (WARNING/2) language "english" not supported: Docutils-generated text will be in English.
Done: Processed 2 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 2.26 seconds.

```

I even copied the example from the [documentation](http://docs.getpelican.com/en/latest/content.html) suggesting how the reStructured Text metadata should be formatted.

```
My super title
##############

:date: 2010-10-03 10:20
:modified: 2010-10-04 18:40
:tags: thats, awesome
:category: yeah
:slug: my-super-post
:authors: Alexis Metaireau, Conan Doyle
:summary: Short version for index and feeds

```

Is this supposed to happen? Am I supposed to enable reStructured Text somewhere? The documentation does not mention anything besides:

* Write your content directly with your editor of choice in **reStructuredText** or Markdown formats

Any feedback would be appreciated. Thanks.

**Comment by avaris** [comment]
Do you have `DEFAULT_LANG = 'english'` in your config? That's passed as `language_code` and tl,dr; `docutils` wanst two-letter language codes. IOW, use `DEFAULT_LANG = 'en'` instead.
