### ISSUE TITLE
Numeric MD filename gets copied as '.html'

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2464]
I have a 404.md in `content/pages`.

404.md is simple:

```
Title: 404
Status: hidden
Date: 2018-11-17 01:00


Page not found

If you entered a web address please check it was correct.

You can also search {{ SITEURL }} or browse from
the homepage to find the information you need.
```

After performing `pelican -s pelicanconf.py`, it copied the generated file to `output/pages/.html`.

I was sort of expecting `404.html`

Then I realized that it may be also happening to ANY files whose filename before `.md` filetype is all numeric.

Pelican: 3.7.1-p1
Debian: 9

**Comment by egberts** [comment]
Took a while...  and it WORKS!

I took the `404.md` file (and of course, I did not rename the file as `"404".md`, but edited the 404.md file itself...  Made it look like:

```
title: "404".html
date: ...
```

Reran `pelican html`, and presto.  Thank you, @justinmayer .

**Comment by egberts** [comment]
Maybe a notation in the documentation where metadata and 'title:' is covered that we should note that all-numeric filename should be wrapped with double-quotes?

I zero'd down to this page and didn't find it there:  http://docs.getpelican.com/en/latest/content.html#file-metadata

**Comment by egberts** [comment]
Documentation update request to content.html#file-metadata?  That quotes must surround the title field if it is a numeric?

Or is it a bug in Python for assuming it is an integer?

**Comment by avaris** [comment]
Can we first understand the cause of the issue before jumping to conclusions?

I cannot reproduce the issue with a skeleton `pelican-quicstart` output:
```shell
$ cat content/pages/404.md
Title: 404

Content

$ pelican content -s pelicanconf.py -D
[snip...]
DEBUG: Read file pages/404.md -> Page
[snip...]
-> Writing /home/avaris/workspace/pq/output/pages/404.html
```

Some things that could help:
* Try removing plugins if there are any and see if problem persists
* Settings file and/or a repo that reproduces the problem

**Comment by egberts** [comment]
Can no longer recreate this problem in Pelican 4.0.0.   I'm not even sure this was a problem anymore.
