### ISSUE TITLE
Pelican/Python variable for current URL? (Canonical URL, best practice)

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2465]
What is the Python/Pelican variable can we use to indicate the 'current' URL?

So I can update this head element of HTML for proper [Canonical URL](https://support.google.com/webmasters/answer/139066?hl=en) in most `base.html` template files:

```html
    <head>
    ...
        <link rel="canonical" url="{{ current.url }}">
    ...
    </head>
```

**Comment by avaris** [comment]
[`output_file`](http://docs.getpelican.com/en/stable/themes.html) should be able to give you that.
```jinja
{{ SITEURL }}/{{ output_file }}
```

**Comment by egberts** [comment]
That `output_file` did the trick.

Unfortunately after `make publish ssh_upload`, the variable `SITEURL` was stuck at `../../archives.html` as in:

```html
<link rel="canonical" href="../../blog/archives/index.html">
```

Had to duplicate `SITEURL` as `ABSOLUTE_SITEURL`, and I'm good to go.

**Comment by egberts** [comment]
And for those who need more lowercase variables for their template, see http://docs.getpelican.com/en/stable/themes.html
