### ISSUE TITLE
cannot extract empty bibliographic field :Authors:  

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2466]
an error message appears:

```
/home/work/websites/example.com/content/articles/pelican-restructuredtext.rst:8: \
    (WARNING/2) Cannot extract empty bibliographic field "Authors".
```

In `content/articles/pelican-restructuredtext.rst`:
```
:title: example in RST
:Tags: rst
:Date: 2018-11-20 16:58
:Modified:
:Status: draft
:Category: example
:Author: johndoe
:Authors:
:Slug: rst-example
:Summary:
:Template:
:Save_as:
:Url:
```

In `pelicanconfig.py`:
```python
## Website info settings
AUTHOR = ''
if len(AUTHOR) == 0:
    AUTHOR_URL = ''
    AUTHORS_URL = ''
    AUTHOR_SAVE_AS = ''
    AUTHORS_SAVE_AS = ''
```

Couple of questions:
1.  Which metadata field relating to author should we be using?  
* :Author:
* :Authors:
* both?

2. Since AUTHOR is empty, shouldn't the Pelican logic not be checking and enforcing for the "author" metadata?  

3. How come this doesn't happened in Markdown-type files?  What should be an normative expectation?

**Comment by egberts** [comment]
Yep.  I copied the Pelican example as-is (from [Pelican doc](http://docs.getpelican.com/en/stable/content.html#file-metadata)) which had both.   

Once I had to choose one of the two "author" metadata fieldnames and we're good to go.  No error after that.

**Comment by avaris** [comment]
That error is coming from RST parser, not pelican. It doesn't like empty metadata fields.
