### ISSUE TITLE
Bad MD file but DEBUG doesn't tell me which file the WARNING is for...

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2467]
In effort to chase down the error message, it is painful to rely on Python debugger just to find out where the error occur at:

```
DEBUG: Read file pages/404.md -> Page
DEBUG: Read file pages/uses.md -> Page
WARNING: There is no "date" attribute in the item metadata. Defaulting to slug order.
DEBUG: Read file extra/favicon.ico -> Static
```
Please note that the file 'page/about.md' is missing in above output.

The above error message was generated using:

```bash
pelican -v -v -v -v -D -s pelicanconf.py
```
And examining the `pages/uses.md` file shows that it has a perfectly filled out 'Date:' value.

```markdown
    Title: uses
    Date: 2018-11-20 12:51
   ...
```

After much debugging of Python, I find out that the `about.md` was missing a `Date:` metadata tag and its value.  And nothing to do with that `uses.md` file.

Notice that `about.md` file name was not mentioned in the terminal output?

Shouldn't that debug message be printing  "DEBUG: Reading file pages/about.md" BEFORE the warning message.

**Comment by bryanbrattlof** [comment]
Hi @egberts, I'm sure someone with more experience than me will chime in here, but I had a few things pop into my head when I read this. 

I know we are talking about having the logs elaborate more, but would using a `grep` command work to find the problem files?
```bash
grep -Lr "Date:" path/to/your/content | grep ".md$"
```

If not, then someone with more knowledge of the code might have some better ideas.

My suggestion would be to loop through the `AttributeError` in `utils.ordered_content` until we find the Pages/Articles in the `content_list` that causes the problem
```python
...

try:
    content_list.sort(key=attrgetter(order_by),
                      reverse=order_reversed)
except AttributeError:
    for content in content_list:
        if hasattr(content, order_by):
            continue
        logger.warning(
            "There is no '{attr}' attribute in the '{path}' "
            "file. Defaulting to slug order.".format(
                attr=order_by,
                path=content.relative_dir
        ))
...

```

This would let all the pages that are missing the `order-by` attribute emit a `WARNING:`, but this might be a little noisy for some.
```bash
WARNING: There is no 'date' attribute in the 'pages/first-page' file. Defaulting to slug order.
WARNING: There is no 'date' attribute in the 'pages/second-page' file. Defaulting to slug order.
```

**Comment by egberts** [comment]
@bryanbrattlof ,  yep.  That's how I found the bug (using a grep command).  But some poor lost soul will have to wade through Pelican issues for that grep command again.  A more concise message would be better.

Besides, the current error output:
```
DEBUG: Read file pages/uses.md -> Page
WARNING: There is no "date" attribute in the item metadata. Defaulting to slug order.
```
will give me absolutely no clue as to which file to jump in and edit directly to add/update the 'Date:' value field for.

**Comment by bryanbrattlof** [comment]
Thanks for the link, @egberts, I didn't know Python2 eats exceptions like that. (I learn something new every day). 

I switched to using `getattr` with a default being `None` (I can't think of a reason why an `order_by` attribute would be `None`) and emit a `WARNING` for every offending file. Giving in an output like this:
```bash
WARNING: There is no "date" attribute in the file "pages/first.md". Defaulting to slug order.
WARNING: There is no "date" attribute in the file "pages/second.md". Defaulting to slug order.
WARNING: There is no "date" attribute in the file "pages/third.md". Defaulting to slug order.
WARNING: There is no "date" attribute in the file "pages/fourth.md". Defaulting to slug order.
WARNING: More files are missing needed attribute.
```
I wanted to keep the ability to list all the files missing the `order_by` for `utils.order_content` to work and let `logging` limit the number of message about missing tags, in the event of someone adding more than one file at a time.

I was getting tired formatting code-blocks so I'll just link to the changes on my fork 58683ec39a77eaa067b4380d432d3ef27dba6f82.
