### ISSUE TITLE
Quickstart script default language is incompatible with reStrcturedText articles

### ISSUE THREAD

**Issue by spollard** [getpelican/pelican#2481]
I understand that the quickstart script is only for markdown articles, but it would be nice if it were also compatible with reStructuredText articles. Fix #2068 causes the DEFAULT_LANGUAGE from the quickstart script to be "English", which breaks docutils converting reStructuredText into html. Docutils requires a two letter language tag, like 'en', and at least on my Windows machine using `locale.getdefaultlocale()` to get the locale results in `DEFAULT_LANGUAGE='en'` in pelicanconf.py. This change was almost suggested by @lucasplus here https://github.com/getpelican/pelican/pull/2068#issuecomment-268659728. It might be reasonable to change the fallback default language (on line pelican_quickstart.py:37) to be 'en' also. 

This fix works on my machine and doesn't break anything for me, but I can't test on other platforms.

**Comment by avaris** [comment]
#2479 should "fix" the `rst` issue... with a warning until you change `'English'` to `'en'`.

**Comment by mosra** [comment]
Looking at #2068, why exactly is it `English` and not `en`, why `getdefaultlocale()` was not chosen over `getlocale()`? Most of the libraries that can be involved here (docutils, [pyphen](https://pyphen.org/), ...) expect the standard two-letter code (`en`, `cs`, `tr`...), no library I know of can handle the Windows long-form names.

On my Linux machine at least, `getlocale()` and `getdefaultlocale()` returns both the same value (`cs_CZ`), so this doesn't affect people on Linux / macOS at all (majority of Pelican users?), but to have nice behavior on Windows I would vote for changing it to use `getdefaultlocale()` instead.

**Comment by avaris** [comment]
Well, technically, what `locale.getdefaultlocale()` returns on Windows is wrong:

```python
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '')
'English_United States.1252'
>>> locale.getlocale()
('English_United States', '1252')
>>> locale.getdefaultlocale()
('en_US', 'cp1252')
>>> locale.setlocale(locale.LC_ALL, locale.getlocale()[0])
'English_United States.1252'
>>> locale.setlocale(locale.LC_ALL, locale.getdefaultlocale()[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\applications\code\python\27\lib\locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

Up until #2256, `DEFAULT_LANG` (at least in `pelican` core) was mostly informative. Only significant use case was to determine if a content was translation or not. And that didn't care about the specifications of lang codes, RFCs etc... Only thing that mattered is that you were consistent.

**Comment by mosra** [comment]
Ah! I see. Oh damn those platform differences. 

So what we need, basically, is translating the whatever-platform-specific-locale-there-is string to something that Docutils / ... understands, right? What about using `locale.normalize()` [here](https://github.com/getpelican/pelican/blob/3596e04639035a70c164ccf4a739d419c08b09b5/pelican/readers.py#L222) so it becomes `lang_code = locale.normalize(self.settings.get('DEFAULT_LANG', 'en')).split('_')[0]`? 

On my machine it does this:

```py
>>> locale.normalize('English').split('_')[0]
'en'
>>> locale.normalize('en').split('_')[0]
'en'
>>> locale.normalize('Czech').split('_')[0]
'cs'
```

**Comment by avaris** [comment]
`locale.normalize` is also dumb on Windows. Documentation of that claims:
> The returned locale code is formatted for use with setlocale().

...but:
```python
>>> locale.normalize('en')
'en_US.ISO8859-1'
>>> locale.normalize('English')
'en_EN.ISO8859-1'
>>> locale.setlocale(locale.LC_ALL, locale.normalize('English'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\applications\code\python\27\lib\locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting
```

There is a giant dict in `locale.locale_alias`, all `locale.normalize` tries to do is a successful lookup in that dict with variations of input.

That being said, all that variable doing is providing a default for a question. In the end, I don't mind how you set it, or if it is a valid locale :). You could even do this in the end:
```python
locale.setlocale(locale.LC_ALL, '')
_DEFAULT_LANGUAGE = locale.getdefaultlocale()[0]
if _DEFAULT_LANGUAGE is None:
    _DEFAULT_LANGUAGE = 'en'
else:
    _DEFAULT_LANGUAGE = _DEFAULT_LANGUAGE.split('_')[0].lower()
    if len(_DEFAULT_LANGUAGE) != 2:
        _DEFAULT_LANGUAGE = 'en'
```
But, we need to update the question as well as the documentation for `DEFAULT_LANG` to state that `docutils` requires a 2-letter language code.

PS: Every time I dive into this locale stuff, I end up with a headache :).

**Comment by mosra** [comment]
> `locale.setlocale(locale.LC_ALL, locale.normalize('English'))`

Yeah, I suspected this would blow up as well :face_with_head_bandage: I meant using the output from `normalize()` *only* to give a reasonable value to docutils, not using it anywhere else.

So, in other words, if I understand correctly:

- we need to keep `DEFAULT_LANG` as the "full name" (on Windows, at least) so `setlocale()` works correctly with it (where is `setlocale()` used, btw?)
- but docutils needs the two-letter code so we need to always `normalize()` the (whatever the user has) value of `DEFAULT_LANG` to get it

**Comment by avaris** [comment]
No, no, no. 

We don't care if `DEFAULT_LANG` is a valid locale or not. It's not used like that. Use `getlocale` or `getdefaultlocale` or any other method, doesn't matter. In the end we have to end up with a 2-letter code (which still might not make `docutils` happy BTW :)). But, [this question](https://github.com/lucasplus/pelican/blob/master/pelican/tools/pelican_quickstart.py#L244-L245) and the docs for `DEFAULT_LANG` should also make it clear that valid values are 2-letter codes.

**Comment by justinmayer** [comment]
@avaris / @mosra: From your perspective, is there anything that should be done here?

**Comment by justinmayer** [comment]
@avaris mentioned:

> But, [this question](https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_quickstart.py#L236-L237) and the docs for DEFAULT_LANG should also make it clear that valid values are 2-letter codes.

Who would be willing to implement the clarifications that @avaris suggested above?

**Comment by jezeniel** [comment]
I can try working on this one.
