### ISSUE TITLE
Need to insert HTML comment of original content filename

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2484]
This `:Slug:` else `:Title:` makes it harder to determine what the original content file name is.  So, when you want to go back and edit the file, the output file name may not be similar enough with the content filename and the end-user is often forced to use `grep` tool to locate the original/content file.

The objective is to update each page with an HTML comment notation where the original content file is:
```html
<title="slugified title">
<!-- content filename: article/original-filename.md -->
```

What is the variable name that has the original content filename so that it can be written into the base.html in form of

**Comment by bryanbrattlof** [comment]
Hi'ya @egberts, I was just doing this myself. 

This isn't documented anywhere, nor is it setup like the other variables for use in the templates, so I guess it's a *"use at your own risk"* kind of thing, but [```article.get_relative_source_path()```](https://github.com/getpelican/pelican/blob/49c77d7412673c38306fd9a69a073544302148ba/pelican/contents.py#L441) works for me.

It's a part of the base ```Content``` object so ```Page```, ```Article```, and ```Static``` have it when building.

Hope that helps.

**Comment by egberts** [comment]
Yep, that does it, @bryanbrattlof .

I inserted the following to the beginning of my template file, in this example `article.html`:

```html
<!-- articles.html begins -->
<!-- source file: {{ article.get_relative_source_path() }} -->
{% extends "base.html" %}
{% block title %}{{ article.title }}{% endblock %}
```
And got the resultant output file:
```html
<!-- articles.html begins -->
<!-- source file: articles/api-security-checklist.md -->
<!-- base.html begins, seeded by blog/articles/api-security-checklist.html  -->
<!DOCTYPE html>
```

Closing this as solved.

**Comment by avaris** [comment]
There is `article.source_path` which is [documented](http://docs.getpelican.com/en/stable/themes.html#article).

**Comment by egberts** [comment]
I too went with Bryan because I also emulated GitLab's funky top-level directory that results in a longer SITEURL for our blog's top-level directory.

Simple example supported is:

    SITEURL=https://example.net/

The ideal but complex examples that I am trying to get supported are:

    SITEURL=https://example.net/blog
    SITEURL=https://gitlab.com/builds/egberts/<repo>

As a result, I've had to make an extension to the SITEURL:

    SITEURL = 'https://example.net'
    SITE_SUBPATH = 'blog'
    RELATIVE_URLS = True if developing_site else False
    SITE_DIR = ''
    SITE_URL_TOP_LVL = '/'   # do not use double-slash here
    if len(SITE_SUBPATH):
        # Do not let SITE_DIR be an absolute file path    
        SITE_DIR = SITE_SUBPATH + '/'
        if RELATIVE_URLS:
            SITE_URL_TOP_LVL = '/' + SITE_SUBPATH + '/'
        else:
            SITE_URL_TOP_LVL = SITEURL + '/' + SITE_SUBPATH + '/'

And prefix in all the various variable names using either SITE_DIR or SITE_URL_TOP_LVL
