### ISSUE TITLE
On fresh install: "simple" theme build error using publishconf.py

### ISSUE THREAD

**Issue by julien-h** [getpelican/pelican#2487]
```
❯ pelican --version
4.0.1
```

If I use the "simple" built-in theme:

```
THEME = 'simple'
```

Then the following command works:

```
pelican content
```
But not:

```
pelican content -s publishconf.py
```

Outputs this error:
```
CRITICAL: TypeError: not all arguments converted during string formatting
```

But not if I use the "notmyidea" built-in theme.

EDIT: Same problem with a fresh install using `pelican-quickstart`.

**Comment by rask004** [comment]
Is anyone else able to replicate this? I tried with a quickstarted project but using publishconf.py worked.

Additionally, I cannot find the mentioned error when searching in pelican.

**Comment by rask004** [comment]
@julien-h What plugins are you using? Also, what settings are different between your pelicanconf.py and publishconf.py?

**Comment by Julian** [comment]
Similar issue here, I'm on pelican `4.2.0`, site works fine with the default theme but not simple:

```
⊙  rm -rf output && pelican -t notmyidea .                                                                                                                                                        julian@Air
Done: Processed 32 articles, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 2.71 seconds.

~/Development/til is a git repository on master
⊙  rm -rf output && pelican -t simple .                                                                                                                                                           julian@Air
CRITICAL: TypeError: not all arguments converted during string formatting
```

Not sure from looking at #2442 quickly what an end user was supposed to do there, but putting this here anyhow in case anyone else finds this ticket, will try to update it if I figure out where the TypeError comes from and how to fix it.
