### ISSUE TITLE
Article from WP import has no date -> TypeError: can't compare offset-naive and offset-aware datetimes

### ISSUE THREAD

**Issue by unformatt** [getpelican/pelican#2488]
pelican==4.0.1
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin

- Did Quick Start from docs, created 1 example article. No errors
- Imported WordPress XML, ran `pelican content`. It imported a draft from WP and for some reason it had no date in the resulting .rst file. This resulted in `TypeError: can't compare offset-naive and offset-aware datetimes` error when trying to sort the articles in  [`pelican/utils.py` line 763](https://github.com/getpelican/pelican/blob/master/pelican/utils.py#L763). 

I printed the dates it's trying to sort. 9999 is the date from the draft article with no date. It's worth noting other draft articles from the WP import have dates.

```
SafeDatetime(2010, 11, 2, 19, 38, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)
SafeDatetime(2011, 4, 20, 1, 11, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)
datetime.datetime(9999, 12, 31, 23, 59, 59, 999999)
SafeDatetime(2010, 5, 7, 12, 47, tzinfo=<DstTzInfo 'America/New_York' EDT-1 day, 20:00:00 DST>)
```

**Comment by avaris** [comment]
Hmm... [This](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L520-L521) doesn't set timezone like [usual](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L129-L139)

**Comment by joshkehn** [comment]
> Hmm... [This](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L520-L521) doesn't set timezone like [usual](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L129-L139)

Setting this:

> self.date = SafeDatetime.max.replace(tzinfo=pytz.utc)

locally resolved the issue for me. I'm also upgrading from a way-too-old version of Pelican (last ran under Python 2.7) so there's other wonkiness in my setup.

**Comment by justinmayer** [comment]
I pushed a commit (cff6a829c2c3962f0c0d7a706d4bc6791966ce20) that uses a timezone when setting a date on date-less drafts, so hopefully that will resolve this issue.

**Comment by justinmayer** [comment]
Presumably this has been resolved by the aforementioned commit(s).
