### ISSUE TITLE
Determine where TypeError: not all arguments converted during string formatting is occuring?

### ISSUE THREAD

**Issue by AWegnerGitHub** [getpelican/pelican#2489]
With Pelican 4.0 there was a change made regarding position argument formatting: 

> Some user-submitted themes use positional argument formatting on object-related feed URLs, which will cause sites to fail to build with: "TypeError: not all arguments converted during string formatting". In that case, the theme needs to be updated.

The one that I fixed was `CATEGORY_FEED_ATOM = 'feeds/%s.atom.xml'` to `CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'`

My problem is that I am still encountering this `TypeError` and I'm not sure where. This is my verbose build output:

```
$ pelican content --output output --settings publishconf.py --verbose
-> Writing /home/andy/my_repos/test_pelican/output/feeds/all.atom.xml
-> Writing /home/andy/my_repos/test_pelican/output/feeds/review.atom.xml
-> Writing /home/andy/my_repos/test_pelican/output/hello-world.html
-> Writing /home/andy/my_repos/test_pelican/output/index.html
-> Writing /home/andy/my_repos/test_pelican/output/tags.html
CRITICAL: TypeError: not all arguments converted during string formatting
```

If I run --print-settings, the only setting with a `%` in it is `DEFAULT_DATE_FORMAT` which is unchanged from the default value of `'%a %d %B %Y'` set in Pelican's [settings.py on line 118](https://github.com/getpelican/pelican/blob/71650b408cefc5d29fe81a91984b6ecd02e1d513/pelican/settings.py#L118)

How can I determine where or what is causing the TypeError?

**Comment by julien-h** [comment]
This error occurs even with the builtin theme "simple". I opened an issue about this here: https://github.com/getpelican/pelican/issues/2487

**Comment by bryanbrattlof** [comment]
Hi'ya @julien-h and @AWegnerGitHub

I've been messing around with this for a little bit, but I'm unsure if the error I'm getting is the same as yours.  The `TypeError` I'm getting is related to the `base.html` template using the old format to generate the urls.
```
CATEGORY_FEED_ATOM|format(category.slug)
TAG_FEED_ATOM|format(tag.slug)
```
If that's the same error then we just need to use the keyword argument
```
CATEGORY_FEED_ATOM|format(slug=category.slug)
TAG_FEED_ATOM|format(slug=tag.slug)
```
If you don't mind posting what ```pelican``` in debug mode (```pelican -D content```) tells you, I think that might help here.

There was some work done to bring the atom/rss feed settings inline with the rest of the settings, #2437, #2383 but I'm guessing there are some bugs still.

**Comment by AWegnerGitHub** [comment]
```Traceback (most recent call last):
  File "/home/andy/.virtualenvs/pelican_test/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/__init__.py", line 623, in main
    pelican.run()
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/__init__.py", line 190, in run
    p.generate_output(writer)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/generators.py", line 689, in generate_output
    self.generate_pages(writer)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/generators.py", line 600, in generate_pages
    self.generate_direct_templates(write)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/generators.py", line 551, in generate_direct_templates
    page_name=os.path.splitext(save_as)[0], url=url)

  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/writers.py", line 254, in write_file
    override_output)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/pelican/writers.py", line 186, in _write_file
    output = template.render(localcontext)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/andy/my_repos/test_pelican/pelican-themes/elegant/templates/categories.html", line 1, in top-level template code
    {% extends 'base.html' %}
  File "/home/andy/my_repos/test_pelican/pelican-themes/elegant/templates/base.html", line 48, in top-level template code
    {% block feed_links %}
  File "/home/andy/my_repos/test_pelican/pelican-themes/elegant/templates/categories.html", line 29, in block "feed_links"
    {% include '_includes/feeds_categories.html' %}
  File "/home/andy/my_repos/test_pelican/pelican-themes/elegant/templates/_includes/feeds_categories.html", line 4, in top-level template code
    <link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(cat_name) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME|striptags|e }} - {{category[0]}} Category Atom
Feed" />
  File "/home/andy/.virtualenvs/pelican_test/lib/python3.6/site-packages/jinja2/filters.py", line 685, in do_format
    return soft_unicode(value) % (kwargs or args)
TypeError: not all arguments converted during string formatting```

I am using the elegant theme. This helped me find the issue. Thank you for the `-D` pointer.

**Comment by moorepants** [comment]
I am getting this same error on Travis where I build the website, but the `-D` flag doesn't seem to offer any insight, for example:

https://travis-ci.org/mechmotum/mechmotum.github.io/builds/468508535?utm_source=github_status&utm_medium=notification

I cannot reproduce the error locally with the same Python and Pelican versions.

**Comment by bryanbrattlof** [comment]
the only thing that is making me a little confused it this line in the Travis output

``` sh
git clone --depth=50 --branch=source https://github.com/mechmotum/mechmotum.github.io.git
```
Is Travis cloning the source branch or master when it fails?

**Comment by moorepants** [comment]
It clones the source branch. It is supposed to. For the doctr tool to work with github pages it has to be on a branch other than master.

**Comment by moorepants** [comment]
This is docs for doctr that shows why I'm using the source branch: https://drdoctr.github.io/recipes.html#using-doctr-with-github-io-pages

**Comment by moorepants** [comment]
Hmm, it is supposed to clone the PR branch maybe.

**Comment by moorepants** [comment]
No, it is working as expected. I think the theme just needs to be updated.

**Comment by bryanbrattlof** [comment]
Haha I came here just to say that, #2437 makes it so we have to update the theme repository to the new ways for the atom/rss feeds

**Comment by moorepants** [comment]
That's unfortunate. Would be nice if it was backwards compatible and a deprecation warning was raised instead of triggering the TypeError with no useful traceback when themes are using the old API.

**Comment by justinmayer** [comment]
A pull request to that effect would be welcome... 😁

**Comment by moorepants** [comment]
Should the themes have something like:

```
if pelican < 4.0:
   don't use slug=
else:
   use slug=
```

Or do themes not need to work with older versions of pelican?

**Comment by joetechem** [comment]
@moorepants @bryanbrattlof 
Try editing base.html, worked for me. I guess it's just the theme (nest) is outdated for Pelican 4.0

Had to add in a `slug=`

nest/templates/base.html:

`<link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_ATOM|format(slug=category.slug) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME }} Categories Atom Feed" />
        {% endif %}
        {% if CATEGORY_FEED_RSS and category %}
        <link href="{{ FEED_DOMAIN }}/{{ CATEGORY_FEED_RSS|format(slug=category.slug) }}" type="application/rss+xml" rel="alternate" title="{{ SITENAME }} Categories RSS Feed" />
        {% endif %}
        {% if TAG_FEED_ATOM and tag %}
        <link href="{{ FEED_DOMAIN }}/{{ TAG_FEED_ATOM|format(slug=tag.slug) }}" type="application/atom+xml" rel="alternate" title="{{ SITENAME }} Tags Atom Feed" />
        {% endif %}
        {% if TAG_FEED_RSS and tag %}
        <link href="{{ FEED_DOMAIN }}/{{ TAG_FEED_RSS|format(slug=tag.slug) }}" type="application/rss+xml" rel="alternate" title="{{ SITENAME }} Tags RSS Feed" />
        {% endif %}
        `

**Comment by mirajpatel19** [comment]
Go to base.html file, which is usually in templates folder of any theme. Then find '|format(' and replace it with '.format(slug=' without quotes. That should fix the error ''TypeError: not all arguments converted during string formatting."

**Comment by monperrus** [comment]
Many themes in https://github.com/getpelican/pelican-themes/ are broken, I get this error for for 3/4 themes I tried: `simple`, `neat`, `medius`

**Comment by alarig** [comment]
I had this issue even if I don’t call CATEGORY_FEED_ATOM and CATEGORY_FEED_RSS in base.html and I already have 'feeds/{slug}.atom.xml' and 'feeds/{slug}.rss.xml' respectively. Commenting them in the config solved the issue for me.

**Comment by philippludwig** [comment]
So, is there any fix for this? I can’t publish anything on my blog anymore because of this issue.
