### ISSUE TITLE
Are the _URL settings available for direct templates?

### ISSUE THREAD

**Issue by AWegnerGitHub** [getpelican/pelican#2490]
In the [Settings documentation](http://docs.getpelican.com/en/4.0.1/settings.html) for 4.0.1 there are two contradictory explanations of what can be used to access direct template values.

(Search for "Direct Templates" on the documentation)

Explanation 1:

> `DIRECT_TEMPLATES` work a bit differently than noted above. Only the `_SAVE_AS` settings are available, but it is available for any direct template.

Explanation 2:

> URLs for direct template pages are theme-dependent. Some themes use corresponding `*_URL` setting as string, while others hard-code them: `'archives.html'`, `'authors.html'`, `'categories.html'`, `'tags.html'`.

My question:

Can I use `ARCHIVES_URL` or is `ARCHIVES_SAVE_AS` the only value available?

**Comment by avaris** [comment]
They are not really contradicting. For direct templates, pelican doesn't do anything with `*_URL`. `*_SAVE_AS` on the other hand will be used to define where the file will be outputted. 

Sure, you can define `ARCHIVES_URL`. It's treated as any other `ALL_UPPER_CASE` variables you defined: i.e. it will be available for themes to use. Whether or not it's used in the templates is theme dependent. Some themes might use them for generating links, and some might be hardcoding the links instead.

**Comment by AWegnerGitHub** [comment]
> For direct templates, pelican doesn't do anything with `*_URL`. `*_SAVE_AS` on the other hand will be used to define where the file will be outputted.

So that I'm understanding correctly, this means that the theme author has to define the `*_URL` variables for the direct templates, right? They are not set by Pelican?

**Comment by avaris** [comment]
Theme author doesn't define them. Theme author *can use* them in the templates. It is up to the user to define them in settings if theme can utilize `*_URL` variables.

`pelican` itself doesn't use or generate `*_URL` variables for direct templates.

It is different than `ARTICLE_URL` in the way that you can do `article.url` and get a URL specific to that article based on your config. For direct templates there is no object to do `.url`. But if you define `ARCHIVES_URL` and your theme does something like this:
```jinja
<a href='{{ SITEURL }}/{{ ARCHIVES_URL or 'archives.html' }}'>Link to archives</a>
```
Then you have the option to, say, do `ARCHIVES_SAVE_AS = 'archives/index.html'` and `ARCHIVES_URL = 'archives'`.

**Comment by avaris** [comment]
Also, I have to add that if you use pagination then you'll get an object to do `.url`: `page` (see `PAGINATED_TEMPLATES`). In that case you have the option to define `URL` as well as `SAVE_AS` via `PAGINATION_PATTERNS`.

**Comment by AWegnerGitHub** [comment]
Thank you @avaris . That explanation was very helpful.
