### ISSUE TITLE
Comma-separated custom metadata

### ISSUE THREAD

**Issue by mauriciogardini** [getpelican/pelican#2496]
Is it possible for a custom metadata to behave in the same way that tags work? I mean, I wanted to pass a comma-separated list of data.

I looked into the source code and found this: https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L50

From what I understood, it's on this variable (METADATA_PROCESSORS) that the magic happens, so I would need to customize it so it parses my custom metadata in a different way.

What would be the best solution to accomplish that in an elegant way?

**Comment by avaris** [comment]
* You can handle it in the theme/template:
```jinja
{% for mytag in article.custom_tag.split(',') %}
  ...
{% end for %}
```

* A plugin to do it as you read (i.e. from `content_object_init` or `article_generator_context` signals).

* Alternatively, a bit hacky but theoretically you can patch the `METADATA_PROCESSORS` from settings (not tested but IMO should work).
```python
from pelican import readers
readers.METADATA_PROCESSORS['custom_tag'] = lambda x, y: x.split(',')
```

**Comment by mauriciogardini** [comment]
>     * You can handle it in the theme/template:
> 
> 
> ```
> {% for mytag in article.custom_tag.split(',') %}
>   ...
> {% end for %}
> ```
> 
>     * A plugin to do it as you read (i.e. from `content_object_init` or `article_generator_context` signals).
> 
>     * Alternatively, a bit hacky but theoretically you can patch the `METADATA_PROCESSORS` from settings (not tested but IMO should work).
> 
> 
> ```python
> from pelican import readers
> readers.METADATA_PROCESSORS['custom_tag'] = lambda x, y: x.split(',')
> ```

The first solution is so simple that it hurts that I didn't think about it... Heh. Will try it.

The second solution looks a little more laborious...

The third solution do indeed looks hacky, and I will have to try it at home.

Thanks!

**Comment by Phuker** [comment]
I guess we could follow what [readers.py](https://github.com/getpelican/pelican/blob/main/pelican/readers.py)
 does and patch `METADATA_PROCESSORS` so that it behaves the same way `tags`/`authors` do:

```python
import pelican

pelican.readers.METADATA_PROCESSORS['custom_tag'] = lambda x, y: (pelican.readers.ensure_metadata_list(x) or pelican.readers._DISCARD)
```

Tested on version 4.11.0 and it works.
