### ISSUE TITLE
Need to supply SITEURL for disqus to work

### ISSUE THREAD

**Issue by azzamsa** [getpelican/pelican#2500]
Hi

Just migrated to pelican this morning. I stuck with this workflow:

a) Disqus didn't work if `SITEURL = '/'`. I must supply the url e.g 'http://localhost:8000/' or 'https://mysite.com'

b) The problem is: Whenever I use `SITEURL = 'https://mysite.com'` I can't debug my site locally. Cause all the `{{ SITEURL }}` point to mysite.com. 

So (a) and (b) are like chicken - egg problem. My current hack is to use `SITEURL = 'https://mysite.com'` before deploying and change it into `SITEURL = 'http://localhost:8000'` when I do local development. I need to cycle this every time. Any solution for this ?

I didn't face this problem with jekyll. Maybe because there are two variable : the `root: /` and the `url: http://mysite.github.io`

Thank you for pelican :)

**Comment by avaris** [comment]
I don't know enough about disqus to comment how to resolve this completely, maybe it needs full URL to id pages?

But you can use multiple config files that build on others. e.g.: If you used `pelican-quickstart` you'd end up with [`pelicanconf.py`](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/pelicanconf.py.jinja2) for local builds and [`publishconf.py`](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/publishconf.py.jinja2) for deploying. Note that `publisconf.py` doesn't redefine everything but import `pelicanconf.py` and override some settings.

**Comment by azzamsa** [comment]
> maybe it needs full URL to id pages?

Disqus worked. I just stuck with my "cycling" worklfow. Need to change 'SITEURL' everytime I need to deploy.

> Note that publisconf.py doesn't redefine everything but import pelicanconf.py and override some settings.

Oh my bad. I never read other 'make' command, turn out there is 'make publish'. Before, I always use 'make html', then ghp-import manually. After reading the Makefile. turn out 'make github' also use ghp-import. The first time I use 'make github' it produced an error. Not so helpful. It should say that I don't have 'ghp-import' installed.

@avaris Thank lot for the help. Problem solved. So it's mean you don't use any commenting system ?

**Comment by avaris** [comment]
No, I don't have comments.
