### ISSUE TITLE
Embedding Bokeh plots with pelican

### ISSUE THREAD

**Issue by dtaylor072** [getpelican/pelican#2505]
Hi, does anyone have experience using pelican to embed interactive Bokeh plots into markdown posts? I know that Bokeh allows exporting to standalone html with CDN, but I'm unsure how to use that standalone html to embed an interactive plot in-line in a post. When I try to story the .html plot file in `assets`, pelican treats the .html plot as an article, instead of static, so it skips it because it lacks metadata. I would really appreciate some help with this! Thanks

**Comment by rask004** [comment]
Pelican treats html files as pages and articles (as well as markdown and restructured, of course). So exporting bokeh plots as html would raise issues.

One suggestion, is to export the plot as SVG, then embed that.

There may already exist pelican plugins for embedding SVG, and it would be possible to write one.

**Comment by mosra** [comment]
If you're writing articles in reStructuredText, embedding SVG (or HTML, or anything else) is as simple as this, no need for a plugin:

```rst
.. raw:: html
    :file: your-file.svg
```

The filename is taken relative to the article file.

**Comment by flothesof** [comment]
Another possibility, which I use on my blog, is to display the plot in a Jupyter notebook and then embed the notebook directly in the markdown or rst article.

This is what I use on my blog, for instance here:
http://flothesof.github.io/harmonic-waves-group-velocity.html

Correction: in fact, I use another toolkit (Holoviews) to create the chart, which is rendered as Bokeh HTML and Javascript. So my comment is slightly off topic...

**Comment by justinmayer** [comment]
Thanks to @rask004, @mosra, and @flothesof for the great suggestions here.
