### ISSUE TITLE
Can I contribute a headless cms blog example?

### ISSUE THREAD

**Issue by jakelumetta** [getpelican/pelican#2509]
Hi! I'd like to contribute a headless cms blog example to the Pelican docs.  It would use ButterCMS API free developer account for the blog content.  Where would the best place for this in the docs be?

Having an alternative to using Markdown for non-technical marketers can help with adoption of Pelican within an organization so I think this guide could really help in that regard; please let me know your thoughts!

**Comment by justinmayer** [comment]
Hey Jake. Congrats on launching your ButterCMS SaaS product. The [ButterCMS Plugin for Pelican](https://github.com/ButterCMS/buttercms-pelican) looks cool.

We are actually moving in the direction of removing commercial service references from our documentation (I'm looking at you, Disqus), so I imagine the most appropriate location for your Pelican+ButterCMS-powered blog example would be on https://buttercms.com/blog/. Once your post is live, I can create a new section on our [External Tools](https://github.com/getpelican/pelican/wiki/Externally-hosted-plugins-and-tools) page and add a link to your article.

Thank you for reaching out. I live in Europe but happen to be writing this from Chicago at the moment and noticed that you're here as well. Small world! 🌍

**Comment by jakelumetta** [comment]
Sounds good, thanks! Small world indeed! Stay warm :)

**Comment by justinmayer** [comment]
Cool stuff! Some day we'll have a better place to keep links to deployment targets like ButterCMS. Cheers!
https://buttercms.com/blog/static-site-generators-for-non-technical-users
https://buttercms.com/pelican-cms/
https://buttercms.com/pelican-blog-engine/
