### ISSUE TITLE
IRC #pelican at Freenode is moderator only and no one can speak there

### ISSUE THREAD

**Issue by iranzo** [getpelican/pelican#2516]
#pelican at FreeNode is listed in the help as the way to contact the developers and get user help, but in fact, the channel is moderator only and no one can speak there.

Please, have it fixed

**Comment by justinmayer** [comment]
This is a known issue. Unfortunately, the flood of IRC spam on Freenode over the last few months has made things very difficult. Every time we remove the “voiced only” flag, the spam overwhelms the channel again.

I have some ideas regarding how to handle this going forward, but I don’t have anything to announce just yet.

**Comment by iranzo** [comment]
Fedora does use an approach (via bot) that kicks all users which are not registered, seems that 'matrix' irc bridge does use something similar, where non registered users are not allowed to open chats

**Comment by ingwinlu** [comment]
> the channel is moderator only and no one can speak there.

afaik you need to be 'registered' on freenode and you should be good.

**Comment by mosra** [comment]
Random idea: what about opening a chat room on [Gitter](https://gitter.im)? Everyone with a github/gitlab/twitter account can join and I have only positive experience from moderating them :) 

It has tight integration with GitHub and so I'm often using it for example to discuss PRs and issues in more detail with the people involved, without needing to overwhelm all repository watchers with GitHub comment notifications.

**Comment by iranzo** [comment]
I'm registered on freenode and I do have channels also registered against my account (and I'm even able to use chanserv message to get 'oped'.

Mode for channel is '+m':

Only opped and voiced users can send to the channel. This mode does not prevent users from changing nicks.

If we want registered users we need '+r'

(actual mode is +cmtz)

**Comment by justinmayer** [comment]
I believe I have tried `+crt` in the past, but spam still managed to get through. Regardless, I have set the channel to that mode for now so we can see what happens. Anyone want to test it and report back here?

**Comment by iranzo** [comment]
I'll be there during EMEA hours, I'll report back

**Comment by justinmayer** [comment]
It seems like setting to `+crt` has resolved the issue for now.

**Comment by justinmayer** [comment]
@mosra: I've considered Gitter. I want to also consider open-source / self-hosted / federated options such as Matrix.

**Comment by iranzo** [comment]
So far, I've seen other people asking, and travis / github informing on repo activity: so far, so good
