### ISSUE TITLE
WARNING: Docutils has no localization for 'english'. Using 'en' instead.

### ISSUE THREAD

**Issue by askpatrickw** [getpelican/pelican#2517]
1. pipenv install pelican markdown
2. pelican-quickstart
3. create an article in content
4. run pelican

**Expected**: Clean run and output created 
**Observed**: Warning 

> WARNING: Docutils has no localization for 'english'. Using 'en' instead.

When I change DEFAULT_LANG = 'English' in my seetings to DEFAULT_LANG = 'en' it runs fine.

Should I PR that as a fix or is there some reason it is English and not en.

**Comment by timp** [comment]
Still happening.
