### ISSUE TITLE
feature_request(update): site list

### ISSUE THREAD

**Issue by Kristinita** [getpelican/pelican#2518]
### 1. Summary

It would be nice, if [**Pelican sites list**](https://github.com/getpelican/pelican/wiki/Powered-by-Pelican) will be updated. In the list we have deprecated or migrated sites, that may takes a user time.

([**GitHub wiki doesn't support pull requests**](https://github.com/isaacs/github/issues/846))

#### 2.1. Non-existing

+ **<http://www.vegasfur.com/>**
+ **<http://www.azizmb.in/>**
+ **<https://www.williamting.com/>**
+ **<http://johz.me/>**
+ **<http://pythonrs.org>**
+ **<https://blog.bogosity.se/>**
+ **<http://www.binsblog.com>** — redirect to casino

#### 2.2. Migrated

+ **<https://bunnyman.info/>** — Hugo
+ **<https://varunksaini.com/>** — Hugo
+ **<http://www.sportpistol.com/>** — WordPress

Thanks.

**Comment by justinmayer** [comment]
Many thanks for making those edits, Miroslaw. Much appreciated!
