### ISSUE TITLE
Support python -m pelican

### ISSUE THREAD

**Issue by segevfiner** [getpelican/pelican#2523]
It would be nice to support doing `python -m pelican` to run the main pelican cli. To do that the main script will need to live in `__main__.py` in the root of the package rather than `__init__.py`. (Be sure to update `setup.py` when making such changes).

It would also be nice to support that for the secondary script such as quickstart too. e.g. `python -m pelican.quickstart`. That too can be done by adding relevant files inside the package.

**Comment by justinmayer** [comment]
Thanks to @timgates42, this issue has been addressed via https://github.com/getpelican/pelican/commit/577d18a7789a6f5817f05f0d93c554a38cca5208. As @avaris [mentioned](https://github.com/getpelican/pelican/pull/2582#issuecomment-501455650), quick-start can be invoked via:

    python -m pelican.tools.pelican_quickstart
