### ISSUE TITLE
Is there any way to get a “Read on →” option in pelican?

### ISSUE THREAD

**Issue by TheChymera** [getpelican/pelican#2527]
I have previously run my blog using Octopress (deprecated as of 2016), and I am now looking to transition to pelican.

Octopress had a nifti feature where `<!-- more -->` in the source code of the document would lead to the document becoming truncated in the main view with a “Read on →” box acting as a link to the full article (see [example](http://www.tutorials.chymera.eu/)).

Is there any way to obtain this functionality in pelican?

**Comment by avaris** [comment]
[summary](https://github.com/getpelican/pelican-plugins/tree/master/summary) plugin is what you're looking for.

**Comment by justinmayer** [comment]
If you want to be able to add the `<!-- PELICAN_BEGIN_SUMMARY -->` and `<!-- PELICAN_END_SUMMARY -->` directly in the content body, then yes, the plugin is probably the best way to do that. If the method I described above is adequate, I'm not sure that plugin is strictly necessary. I imagine it just depends on what flow you prefer.

**Comment by drivet** [comment]
@TheChymera You may be interested in the [paragraphed-summary](https://github.com/drivet/paragraphed-summary) plugin.  It tries to honor the SUMMARY_MAX_LENGTH setting, but does so in units of whole paragraphs. 

The result is a series of automatically generated, variable length summaries without any need to manually add markers in your articles.

You can see the result [here](https://desmondrivet.com/blog/)

**Comment by TheChymera** [comment]
@drivet I have tried [your theme](https://github.com/drivet/pelican-website/tree/master/static) (as it looks fabulous), and it seems to automatically display a summary on the main webpage view. It does not seem to ship your plugin, though. How then is this implemented?

Also, I would like to control the summary explicitly (e.g. via something like `<!-- PELICAN_END_SUMMARY -->` ), but this does not seem to work out of the box with your theme. What's the best way to make it work with it?

**Comment by justinmayer** [comment]
> Is there no way around the fact that in order to use `Summary:`, the summary needs to be concatenated in one line?

Good question. I'm not sure. For Markdown content, this aspect is managed not by Pelican itself but instead by the [Python-Markdown](https://python-markdown.github.io/) dependency's [meta-data extension](https://python-markdown.github.io/extensions/meta_data/).

Have you tried indenting subsequent summary lines by at least four spaces? For example:
```
Summary:  This is a summary intended to demonstrate  
          metadata that spans multiple lines, yet  
          is treated as a single value.
```

**Comment by drivet** [comment]
> @drivet I have tried [your theme](https://github.com/drivet/pelican-website/tree/master/static) (as it looks fabulous  ), and it seems to automatically display a summary on the main webpage view. It does not seem to ship your plugin, though. How then is this implemented?
> 
> Also, I would like to control the summary explicitly (e.g. via something like `<!-- PELICAN_END_SUMMARY -->` ), but this does not seem to work out of the box with your theme. What's the best way to make it work with it?

There are two distinct concepts here: the paragraphed-summary plugin and the website theme.  They are in different repos.  They do not ship together.

The paragraphed-summary plugin, by design, does not use markers (i.e.  PELICAN_END_SUMMARY) in the articles.  It's very similar to the standard summary plugin, except I try to make the summary land on paragraph breaks and I treat the SUMMARY_MAX_LENGTH setting as a suggestion.

The website theme is kinda specialized for my particular needs.  Your mileage may vary with it.

If by "the main webpage view" you mean the homepage, then that one is a on-off template (hompage.html in the theme).  I have a markdown file which uses it in an override in my actual website.

**Comment by TheChymera** [comment]
@drivet I'm continuing to try and use your theme, think this issue is better suited for the issue I opened on it :)

In the mean time, it turns out the **summary** plugin is exactly what I was looking for, and all other alternatives do not provide equivalent functionality. Many thanks.
