### ISSUE TITLE
Implementing article "types"

### ISSUE THREAD

**Issue by drivet** [getpelican/pelican#2529]
Hi,

I might be missing something obvious here, but I haven't seen it yet.  Thanks for any advice you can give me.

I'm trying to implement the notion of article "types" in pelican, the idea being that some articles are actual blog entries while other articles are much shorter, title-less "notes" and others might be simple "bookmarks" that simply share links.

I'd like a master reverse-chronological index with all my content, across all types, which is easy, as this is just what pelican does out of the box.  But I would also like a reverse-chronological index for each type of article - one for the blog entries, one for the notes, with each index potentially being rendered with a different template.

I know I can implement something close to this with categories.  I could have a category called "blog" and another called "notes", for example.  But I'd like to reserve the notion of categories for actual subject matter, like "travel" or "technology", etc.  I'd like my categories to "cut across" my article types (selecting the index for "travel" should show all the blog entries *and* notes that are in the travel category).

I know I can accomplish all this with a simple plugin, but I just wanted to make sure I wasn't missing anything before I do that.

Thanks in advance!

**Comment by avaris** [comment]
Besides `category`, `tags` (or with considerable "abuse" `author`) can be an option. 

Alternatively, if you don't need pagination you can handle it in the template itself. Add an entry to `DIRECT_TEMPLATES` and filter articles based on the type. i.e. a `blog.html` template might look like:
```jinja
{% for article in articles if article.type == 'blog' %}
    ...
{% endfor %}
```

Otherwise plugin is the way to go.

**Comment by drivet** [comment]
Thank you!
