### ISSUE TITLE
Is it possible to make ARTICLE_URL and ARTICLE_SAVE_AS totally different?

### ISSUE THREAD

**Issue by Magnetic2014** [getpelican/pelican#2531]
I try to use pelican 4.0.1 to customize my articles' URL and organize my articles via ARTICLE_URL and ARTICLE_SAVE_AS settings. 

The example usage mentioned in documentation is:
`ARTICLE_URL = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/'`
`ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}/index.html'`

But I want to make these two settings totally different, such as:
`ARTICLE_URL = 'posts/{slug}/'`
`ARTICLE_SAVE_AS = 'posts/{date:%Y}/{date:%b}/{date:%d}/{slug}.html'`
Because I want to make URL shorter and make articles well organized in folders at the same time.

But when I tried to do so, I found the actual URL is controlled by ARTICLE_SAVE_AS instead of ARTICLE_URL, which caused unavailable URL links on my blog's index page.

Is there any possible solution for that issue?

**Comment by avaris** [comment]
I don't understand... Your actual file will reside on `/posts/2019/02/10/slug.html` but your URL will be `www.example.com/posts/slug/`? This has nothing to do with `pelican`. It's about your server. Server needs to know `/posts/slug` is actually `posts/2019/02/10/slug.html`... somehow... and serve that page.

**Comment by Magnetic2014** [comment]
I think I understand. So I need to configure my custom routing at the server side instead of pelican.

Thank you so much.
