### ISSUE TITLE
Import Dotclear needs improvements

### ISSUE THREAD

**Issue by toitoinebzh** [getpelican/pelican#2532]
Hi,

I tried to import my dotclear website using pelican-import.
I see that most of the article are not correctly imported.

Please find enclosed an example file

# Step to reproduce 

```bash
antoine@Talos:~/Bureau/export_dotclear$ ~/.local/bin/pelican --version
4.0.1
antoine@Talos:~/Bureau/export_dotclear$ ~/.local/bin/pelican-import   --dotclear -o output 2019-02-14-toitoinebzh-backup.txt  -m markdown
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
33 posts read.
output/wolfenstein-enemy-territory-sous-ubuntu-904.md
output/dell-latitude-e4310-et-asus-eeebox-eb1012.md
output/mise-en-place-dune-seedbox-automatisee.md
output/futjitsu-esprimo-p3520-e85.md
...
antoine@Talos:~/Bureau/export_dotclear$ 
```

Look at .md files with a file editor like Retext : 
 *  Tags are not imported 
`Tags: <?xml version="1.0" encoding="utf-8"?>`
 * Links and images are not correct
`![\\"debian\\"](\%22/public/2009/debian.jpg\%22 "\"debian,")`
 * apostrophe does not appear correctly
`Pour avoir une installation dite \\"minimal\\" (`
 * code block are not well imported
Le disque dur du serveur a été partitionné de manière à séparer / de /home et une partition /document a également été crée.
```
    \rantoine@Ninja:~$ lsblk\rNAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT\rsda      8:0    0 465,8G  0 disk \r├─sda1   8:1    0  19,5G  0 part /\r├─sda2   8:2    0  19,5G  0 part /home\r├─sda3   8:3    0     2G  0 part [SWAP]\r└─sda4   8:4    0 424,8G  0 part /document\rsr0     11:0    1  1024M  0 rom  \rantoine@Ninja:~$\r

Une fois l'installation terminée, il est nécessaire de s'assurer de la mise en place de l'accès ssh en installant le paquet openssh-server sur le serveur
```

[export_dotclear.zip](https://github.com/getpelican/pelican/files/2867083/export_dotclear.zip)

**Comment by oulenz** [comment]
The Dotclear import code essentially hasn't changed since it was first added eight years ago. There may have been changes to the format in the meantime (e.g. how tags are encoded), and the original code probably didn't cover everything to begin with (e.g. code blocks).

I have no experience with Dotclear, not sure about other active contributors. Would you be able to improve [the code](https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_import.py) yourself?

**Comment by toitoinebzh** [comment]
Thank you for your feedback
I finally corrected the *.md files manually.

when I have time, I may try to improve the code (function dc2fields, I guess)

**Comment by justinmayer** [comment]
@toitoinebzh: Any contributions you can offer would of course be welcome. Thanks!
