### ISSUE TITLE
pelican-import generates .rst despite -m MARKDOWN

### ISSUE THREAD

**Issue by lesatdgl** [getpelican/pelican#2533]
Pelican 4.01.
Pandoc 2.6
ubuntu 16.04
python 3.6

importing wordpress xml

cmd: pelican-import --markup MARKUP --wpfile  ~/Downloads/wealthyourdecision.wordpress.2018-04-28.xml

[wealthyourdecision.wordpress.2018-04-28.xml.zip](https://github.com/getpelican/pelican/files/2877899/wealthyourdecision.wordpress.2018-04-28.xml.zip)

[lst-content.zip](https://github.com/getpelican/pelican/files/2877892/lst-content.zip)

**Comment by avaris** [comment]
Checked the code. It's looking for `markdown` (lowercase) and defaults to `rst` otherwise.

**Comment by lesatdgl** [comment]
Cool, given that the docs show MARKDOWN

Thanks

Les Dunaway
770-490-7546

**Comment by oulenz** [comment]
I think you're misinterpreting the docs and confusing the terms _markup_ and _markdown_ (in the body and title of your post). The import option is called `--markup`. `MARKUP` is used only as a placeholder for the value users can supply, which is either `markdown` or `rst` (anything else will actually default to `rst`).

**Comment by lesatdgl** [comment]
Thanks for helping me feel like a dummy ;-) It's important to personal development

Les Dunaway
770-490-7546

**Comment by oulenz** [comment]
Nah I know from personal experience how easy it is to miss things when you're not attuned to paying attention to them. :-)

**Comment by lesatdgl** [comment]
Yes, that's how personal / professional growth happens - by falling over your feet ;-)

Basic rule of creating courses / tests - make sure the student fails! (Not a lot, just enough to learn)

I started teaching, writing courses, ... in 1966, so I've earned the right to an opinion

Les Dunaway
770-490-7546

**Comment by justinmayer** [comment]
Glad you resolved the issue, Les. Welcome to the Pelican community! 🎊
