### ISSUE TITLE
IndexError when ARTICLE_TRANSLATION_ID

### ISSUE THREAD

**Issue by rminderhoud** [getpelican/pelican#2534]
Hello, I upgraded my project to Pelican 4.x and I have a very minimal config. It revealed the following error when the `ARTICLE_TRANSLATION_ID` setting is not defined in a config file

```
CRITICAL: IndexError: tuple index out of range
Traceback (most recent call last):
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/bin/pelican", line 11, in <module>
    sys.exit(main())
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/lib/python3.6/site-packages/pelican/__init__.py", line 623, in main
    pelican.run()
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/lib/python3.6/site-packages/pelican/__init__.py", line 178, in run
    p.generate_context()
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/lib/python3.6/site-packages/pelican/generators.py", line 652, in generate_context
    self.articles, self.translations = _process(all_articles)
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/lib/python3.6/site-packages/pelican/generators.py", line 648, in _process
    arts, translation_id=self.settings['ARTICLE_TRANSLATION_ID'])
  File "/home/ralph/.local/share/virtualenvs/ram-F3HMn9Ws/lib/python3.6/site-packages/pelican/utils.py", line 682, in process_translations
    .format(*translation_id).format(*id_vals)
IndexError: tuple index out of range
```

**Version**: Pelican 4.0.1
**Steps**:
1. Remove `ARTICLE_TRANSLATION_ID`  from your pelican file
2. Run `pelican -s conf.py --debug`

**Comment by oulenz** [comment]
It took me a long time to come up with a scenario that would cause that error message on that line, but I think I've got it.

Do you have one or more articles with an empty slug?

**Comment by rminderhoud** [comment]
Ah, yes I do. I have a few articles where I don’t use the slug tag but let
it generate a slug from the file name. I apologize, didn’t realize that was
also part of the issue.

**Comment by oulenz** [comment]
If you don't set `ARTICLE_TRANSLATION_ID`, it defaults to using the slug. So if in fact you're not using translations on your website, you should be able to fix this by setting `ARTICLE_TRANSLATION_ID = None`.

That said, I do believe you've found a subtle bug. On any of the articles where the slug is generated from the filename, is the filename essentially empty (save possibly for whitespace or non-ascii characters)?

**Comment by rminderhoud** [comment]
The `ARTICLE_TRANSLATION_ID = None` fixes the issue as I don't use translations. I don't have any articles that have unusual names like that but I narrowed down the "article" which is causing the issue. On my previous host, I was using letsencrypt so I created an HTML article that contained the necessary challenge data. It seems this file was that causes the issue. File name is `letsencrypt.html`.

Contents:
```
<html>
<head>
    <title></title>
    <meta name="date" content="1960-01-01">
    <meta name="save_as" content=".well-known/acme-challenge/Zpzcw1rGsdTZYfEk5ZVjsagOHcMzTMDW5mJGHBjZ5iY/index.html">
    <meta name="template" content="plaintext">
</head>
<body>Zpzcw1rGsdTZYfEk5ZVjsagOHcMzTMDW5mJGHBjZ5iY.ywNe8_JukfemUJYBQU6nyoQ5Dhu9pc--6ctLqzdrzYs</body>

</html>
```

Removing this file or setting `ARTICLE_TRANSLATION_ID = None` fixes the issue.
