### ISSUE TITLE
Theme added with pelican-themes; refed in pelicanconf.py; not found by pelican content

### ISSUE THREAD

**Issue by lesatdgl** [getpelican/pelican#2537]
I've imported a Wordpress site - successfully

Site comes up in notmyidea

I'm trying to try various themes

**Installed atilla using pelican-themes**

_(pelican-projects-xtj21HM1) (xenial)les@localhost:~/dgl-home/dglEnvironments/pelican-projects/WYD$ pelican-themes -l
simple
attila
notmyidea_

I've got atilla in my pelicanconf.py

(pelican-projects-xtj21HM1) (xenial)les@localhost:~/dgl-home/dglEnvironments/pelican-projects/WYD$ cat pelicanconf.py
_#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = 'Les'
SITENAME = 'WealthYourDecision'
SITEURL = ''

PATH = 'content'

TIMEZONE = 'America/New_York'

DEFAULT_LANG = 'en'

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'http://getpelican.com/'),
         ('Python.org', 'http://python.org/'),
         ('Jinja2', 'http://jinja.pocoo.org/'),
         ('You can modify those links in your config file', '#'),)

# Social widget
SOCIAL = (('You can add links in your config file', '#'),
          ('Another social link', '#'),)
# Theme
THEME = "atilla"

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
#RELATIVE_URLS = True_

I'm getting theme not found

_(pelican-projects-xtj21HM1) (xenial)les@localhost:~/dgl-home/dglEnvironments/pelican-projects/WYD$ pelican content
CRITICAL: Exception: Could not find the theme atilla

Used this sample to specify theme

_Following are example ways to specify your preferred theme:

# Specify name of a built-in theme
THEME = "notmyidea"
# Specify name of a theme installed via the pelican-themes tool
THEME = "chunk"
# Specify a customized theme, via path relative to the settings file
THEME = "themes/mycustomtheme"
# Specify a customized theme, via absolute path
THEME = "/home/myuser/projects/mysite/themes/mycustomtheme"

How can I specify the theme to use for genetation?

**Comment by justinmayer** [comment]
It appears you have misspelled the name of the theme in your settings file:

    THEME = "atilla"

Try the correct spelling:

    THEME = "attila"
