### ISSUE TITLE
Cannot suppress generation of tags.html or categories.html

### ISSUE THREAD

**Issue by codecachet** [getpelican/pelican#2546]
I do not want to generate a tags.html or categories.html. In peliconconf.py, I have commented out the DIRECT_TEMPLATES completely, yet they are still being generated.

**Comment by avaris** [comment]
Commenting out `DIRECT_TEMPLATES` would result in `pelican` using the default value, which includes `tags` and `categories`. If you don't want them, you *need to have* a `DIRECT_TEMPLATES` setting without them.

**Comment by codecachet** [comment]
That worked! Thank you.
