### ISSUE TITLE
Use Docutils html5 writer for reST content

### ISSUE THREAD

**Issue by sscherfke** [getpelican/pelican#2549]
It looks like Pelican is still using the `html4css1` writer. Would it be possible to switch to an HTML5 writer in a future major release?

**Comment by mosra** [comment]
Unless something drastically changed in a very recent `docutils` release, from my experience even the HTML5 writer was far from producing an actual valid HTML5. I ended up rewriting most of it myself and if you want, you can grab it as a Pelican plugin [m.htmlsanity](https://mcss.mosra.cz/plugins/htmlsanity/) from the m.css theme -- you can (but don't need to) use the whole theme if you want, but just the plugin is enough to get valid HTML5 output out of docutils.

In my opinion, until the builtin docutils HTML5 writer is really capable of producing HTML5, switching to it would only break existing themes and styling but have no real advantage.

**Comment by justinmayer** [comment]
Given @mosra's plugin, I think we can consider this closed until such time as Docutils can natively produce properly valid HTML5.
