### ISSUE TITLE
Footnote links mixed up when multiple articles are generated into a single page

### ISSUE THREAD

**Issue by eliben** [getpelican/pelican#2551]
In the main page (`index.html` template) of my blog I'm displaying the 3 most recent posts (template code shown below)

When more than one post has footnotes, the links between them get mixed up. For example if you look at https://eli.thegreenplace.net right now, the footnote for `[1]` in the third post points into the second post.

I'm using ReST for my posts (they're all `.rst` files), and unnumbered footnotes (`[#]_`) so I'd expect them to be numbered properly when all pasted together.

Is this a known issue?

----

```
        {% for article in articles[:3] %}
            <article>
                <h1><a href="{{ SITEURL }}/{{ article.url }}">{{ article.title }}</a>
                </h1>

                <span class="published">
                    <i class="fa fa-calendar"></i>
                    <time> {{ article.date.strftime('%B %d, %Y at %H:%M') }}</time>
                </span>
                <br/><br/>

                <div class="entry-content">
                    {{ article.content }}
                </div>
            </article>
            <!-- Don't emit the hr after the last article, since there's already
                 one there from the footer -->
            {% if loop.index != 3 %}<hr class="style-eight"/>{% endif %}
        {% endfor %}
```

**Comment by avaris** [comment]
Well, it's not unexpected. The autonumbering for `[#]_` footnotes is done at parse time. So each article gets their numbers in isolation. At that point you have `HTML` with fixed numbering (each article starting at `1`). When you put multiple articles into one page, wires start to cross.

Only solution that comes to mind is adding (unique) labels to footnotes (`[#name]_`), in order to avoid collisions between articles.

**Comment by eliben** [comment]
Thanks for the details, @avaris, and for the workaround suggestion.

I suspected this is the issue, but wasn't sure how hard it is to fix. It seems that such auto-generating links would force parsing to happen after pasting, but I can see how this is a different design that could be difficult from other aspects. It seems that showing multiple posts on one page is problematic in general, then.

**Comment by justinmayer** [comment]
@eliben: Hopefully the workaround @avaris suggested has been helpful. If you have any other information to share about how you resolved this issue, or have any other questions, please feel free to add follow-up comments here. Cheers!
