### ISSUE TITLE
Greater and Less than symbols in code block

### ISSUE THREAD

**Issue by mutcato** [getpelican/pelican#2553]
What i write in editor:
    ::python
    def positive_number(number):
        if number > 1:
            pass

What i see in browser:
def positive_number(number):
    if number &gt; 1:
        pass

Somebody replaces < and > signs with &lt; and &gt;

**Comment by justinmayer** [comment]
In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
