### ISSUE TITLE
How do I run from source? and upgrade from 3.7 -> 4.0.1 woes

### ISSUE THREAD

**Issue by vanessa-luna** [getpelican/pelican#2554]
I want to contribute. 

I cloned the repo and have it locally. However I cannot figure out how to run pelican to test out changes. I also could not find any answers to this in the official docs, or the wiki here or any issues here or the readme. Plz help. 

I have experience modding python code but no project experience. I even modded my local installed 3.7.1 version of pelican and some plugins for pelican. Still I cannot figure out how to run from source.

**How do I run from:**
 - Bash script
 - Python file?

**Comment by justinmayer** [comment]
Hi there. What have you tried so far?

Have you seen this section of the docs? http://docs.getpelican.com/en/stable/contribute.html#setting-up-the-development-environment

**Comment by vanessa-luna** [comment]
Gosh I am too tired. I did not even see that part of the docs. I am sorry. Thank you for replying so quickly. Your commitment to this project is wonderful.

I am only 4 years on the linux train so I am still a novice... The thing I have been most eager to avoid is using virtualenv. The last time I tried installing it, a bunch of my stuff got messed up and I couldn't figure out how to fix it. Or, it was going to take days to work it all out. However this happened only 2 years into my linux switch and been afraid to touch it and forget all the details of what went wrong. 

I hoped I could run __init__ from the command line but get "no module named pelican" And I tried to run pelican from a pyhton file and got "no module blinker". 

The dependencies are gonna be the nightmare if I don't use virtualenv right?

**Comment by oulenz** [comment]
I personally use conda (miniconda to be precise) rather than virtualenv, and it's always been unproblematic to install and uninstall on linux. But I would expect that to be true for virtualenv too.

To run from source, I have the pelican directory added to my path, and use `python -c 'import pelican.__init__; pelican.__init__.main()'` instead of `pelican`. This works both on the command line and in the Makefile.

**Comment by avaris** [comment]
Even though you can "run" pelican from source directly, it's basically same as installing. It is a package, not a single file. You would need to add it to `PYTHONPATH`. And then you need to manage requirements manually... It will be a pain (IMO).

I would *really* suggest using a virtualenv and doing a development install (`pip install -e ...`) as outlined in the docs.

PS: Personally, I use `virtualenvwrapper` to manage `virtualenv`s. Makes life much easier.

**Comment by justinmayer** [comment]
If all you want to do is run Pelican (or other Python packages) from an isolated environment, and you have no reason to use `virtualenv` for development or other purposes, you could try using [PipX](https://github.com/pipxproject/pipx) to install Pelican via:
```
python3 -m pip install --user pipx  # Install PipX
pipx ensurepath                     # Ensure PipX executable can be found
pipx install pelican                # Install Pelican via PipX
```

**Comment by vanessa-luna** [comment]
Thank you for the options. I will explore. I can't wait to use the new features in 4.0

**Comment by justinmayer** [comment]
You're quite welcome. It's also worth mentioning that on Python 3, you don't have to install `virtualenv` — you can use the built-in `venv` module. Here's a related video tutorial in case it's helpful: https://youtu.be/Kg1Yvry_Ydk

**Comment by vanessa-luna** [comment]
I want to update with progress. 

I tried using pipx. However I got a "missing module markdown" which is likely because it is using Python3 rather than my current install of Pelican which is using python2.7. I have not had time to make significant progress otherwise. Also, with Pipx, I had to change the name of the installed binaries because it conflicted with my current install. I hope that doesn't cause me too many troubles.

I am going to close this issue but still provide updates to it and keep it closed in case this thread helps others in the future.

**Comment by vanessa-luna** [comment]
Hi. I have made some progress but gotten stuck again. After exploring options I decided to try virtualenv again. I have got it setup and I am trying to compile my project. I am stuck on an error and need help figuring out what is going on.

> Note: I am upgrading from Pelican 3.7 & Python 2.7 --> Pelican 4.0.2 & Python 3.6.4

Process:
1. I followed the instructions listed here: http://docs.getpelican.com/en/stable/contribute.html#setting-up-the-development-environment
2. I updated my bash script for testing to include `. /path/to/virtualenv/activate` before running pelican
3. I needed to modify the path to `plugins` folder for some reason and ended up using absolute path for now
4. Installed all plugin dependencies 
5. got the `TypeError: can't compare offset-naive and offset-aware datetimes` and fixed via [this thread](https://github.com/getpelican/pelican/issues/2488#issuecomment-446807771) by ensuring all `status: draft` had a valid date either in filename or in metadata
6. Then I got stuck here: 

`CRITICAL: UndefinedError: 'dict object' has no attribute 'iteritems'`

I have no idea how to figure out where this is coming from and a search in the issues here did not reveal anything. My background is in UI dev and my Python is budding. 

* I changed to verbose output and debug level to DEBUG gave nothing useful. 
* Pelican manages to output the `feed` folder and some of the `theme` folder. Only `.webassets-cache` and one `css/article.min.css` file (which is part of my webassets config). So maybe I should assume something is wrong with my webassets config? My first looks have provided nothing.
* I confirmed both setups are using the same version of webassets
* My entire config process is kept here if anyone is willing to dive into it: https://github.com/vanessa-luna/pelican-setup (although the theme folder might not be up to date)
* Finally, I was testing under `master` branch. When I checkout `4.0.1` It barely gets anywhere producing a `CRITICAL: KeyError: 'extensions'` 

This is a huge upgrade to a complex project and I wish I knew enough to figure this out on my own. Thank you for any input or questions which might help me.

Luna

**Comment by avaris** [comment]
`verbose` and `debug` are mutually exclusive. Provide only `debug`. Besides that, the error about `iteritems` is a difference between Python 2 and 3. Python 3 no longer has `dict.iteritems`. `dict.items` does that job. Quick search in your repo shows a bunch of places in the theme uses `iteritems`.

**Comment by justinmayer** [comment]
As an aside that I'm only bringing up because I mentioned PipX above, I wonder whether optional, not-strictly-required dependencies (in this case, Python-Markdown) can be installed at the same time as the "main" target package. But I don't know whether multiple packages can be installed via something like:

    pipx install pelican Markdown

Perhaps @cs01 might know the answer?

**Comment by cs01** [comment]
Hi all, thanks for looping me in.

There many ways to get this working, but here are two. Either one is fine, so pick on you are more comfortable with.

## workflow 1: use pipx
One way you can use pipx to do this would be to first clone pelican:
```
git clone git@github.com:getpelican/pelican.git
cd pelican
```
then install pelican in editable mode:
```
>> pipx install pelican --spec . -e
  installed package pelican 4.0.2.dev0, Python 3.6.7
  These binaries are now globally available
    - pelican
    - pelican-import
    - pelican-quickstart
    - pelican-themes
done! ✨ 🌟 ✨
```

Now when you run `pelican` from the terminal, any changes made in the pelican source code you cloned will be reflected.

If you want to inject other packages into the pelican environment that pipx uses, you can use the `inject` command (very close to your guess, @justinmayer ):
```
pipx inject pelican Markdown
```

When you are done, you can reinstall the PyPI version of pelican if you want:
```
pipx uninstall pelican
pipx install pelican
```
## workflow 2: use venv
The other way to accomplish making and testing changes would be to run the following commands from the `pelican` directory (i.e. `~/git/pelican`) after you clone the repository. As @justinmayer mentioned, don't use `virtualenv`; use `venv` instead. 
```
python3 -m venv venv
. venv/bin/activate
pip install -e .
pip install Markdown
# make/test changes
# when done, run
deactivate
```

**Comment by vanessa-luna** [comment]
Thanks for continued replies everyone. I want to do my best to learn so I don't bother you all so much. I am going to close this again because I have a lot more info about this all I can play with and don't expect to run into a block again for a little while. Thank you <3

* I was able to compile without errors. 
* But things are not running perfect yet.
* It is clear I am now up against the challenge of learning the differences between the versions of python and pelican. 

@avaris Thank you. After modifying the instances of iteritems, I was able to get pelican to finish compilation.

@cs01 Pipx
I tried using pipx, but I am still actively using pelican 3.7. When I first jumped in to pipx I got pelican installed, but my machine still defaulted to the old installation, I'm guessing because the environment variables are after the original install (or something). I was able to modify the name of the binaries in the setup file but then, yes I ran into the confusion of installing dependencies. 

Aside,
I am happy to see the EXTRA_TEMPLATES_PATH was replaced with THEME_TEMPLATES_OVERRIDES. The change in the generator.py was the same thing I had done locally. However there is no mention in the docs this was changed and or removed. Also the main reason I am upgrading pelican is to get use of the symbolic linking changes. I have gigs of statics I need to stop wasting time and energy copying.

**Comment by avaris** [comment]
> I am happy to see the EXTRA_TEMPLATES_PATH was replaced with THEME_TEMPLATES_OVERRIDES. The change in the generator.py was the same thing I had done locally. However there is no mention in the docs this was changed and or removed.

Looks like that one slipped from the changelog, commit list was *very* long :). But you should see a warning about deprecation when you run with the old settings.
