### ISSUE TITLE
Content not accessible "online" until pelican finishes

### ISSUE THREAD

**Issue by drivet** [getpelican/pelican#2555]
Hi all,

I'm attempting to write a plugin that unfortunately requires that my articles are available "online" before moving on to another task.  I'm not sure if I'm doing something wrong, but it doesn't look like pelican is writing the files until it exits.

What I did was as follows:

- I added a new article to my pelican content folder
- I wrote a plugin which provided a function which connected to the finalized signal (i.e. after everything is written).  The function did nothing but call a time sleep for 45 seconds.
- I generated my html with the pelican command

The new article was not accessible at its URL until 45 seconds later, when the sleep ended.  Until that time I'd get 404, and then after I'd get 200.

Am I doing something wrong?  Is there a signal I can connect to that gets fired after the articles are actually written to disk and accessible?

Thanks for any help you can give me.

**Comment by avaris** [comment]
I can't be sure without actually seeing what you're doing. Which finalized signal did you connect to?

* `finalized`: This should work. This is signaled pretty much before `pelican` ends. Everything should be written by now.
* `article_writer_finalized`: At this point all articles (including collection pages like `index` and `feeds`) should be written. Not necessarily pages.
* `article_generator_finalized`: No, this is signaled after content is read but before written.
* `page_*_finalized`: Similar to articles but for pages.
* `all_generators_finalized`: Again no. This is more or less combined version of `*_generator_finalized` signals. It's fired after *everything* is read, but before written.

**Comment by drivet** [comment]
I used the first one.  My first thought was that there is some kind of buffering happening that is flushed when pelican exits. My print statements seen to confirm it - they don't show up in my log file until the end.

Thanks for the IRC tip. I'll take a look.

**Comment by avaris** [comment]
Neither pelican, nor python does that kind of buffering. It is basically "open a file, write stuff and close". The moment you see [`Writing foo.html` in the pelican log](https://github.com/getpelican/pelican/blob/master/pelican/writers.py#L212-L214) (you need `--debug` mode), that content is written and should exist in the output.

What is your publish process? Could it be that your publish process *waits* for pelican to finish before putting files to the location server is searching?

**Comment by drivet** [comment]
Hmmm.  I just checked and I don't *think* this is the case.  My deployment script compiles the HTML files directly into the folder that NGINX is expecting.

I do use the -d parameter with pelican (i.e. I delete the output folder beforehand) so maybe that messes with NGINX's caching mechanism.

One thing I noticed is that a similar thing happens when I try this locally.  For example, I'll have a local clone of my blog repo on my machine, and I'll do the following:

- I'll run the local HTTP server by running "python -m pelican.server"
- I'll manually delete the output folder.  In production, I use the -d flag.
- I'll add a post to my content folder.  I don't commit it or anything.
- I'll run the pelican command the generate the html files
- Via the "finalize" signal, the plugin goes to sleep using a "time.sleep(45)" (i.e. the process is suspended for 45 seconds)
- During this 45 second interval, I'll try to access the file in my browser using the URL it's supposed to be at.  This fails with a 404
- The 45 second interval ends.  At this point I usually have to re-run "python -m pelican.server" to see anything.

I guess the deletion of the output folder messes things up a bit?

**Comment by avaris** [comment]
Well, I can't reproduce it here. 
* Added this to the settings:
```python
import time
from pelican.signals import finalized

def fn(*args, **kwargs):
    print('SLEEP START')
    time.sleep(45)
    print('SLEEP END')

finalized.connect(fn)
```
* Add a new article in content
* Browse to output folder and run `python -m pelican.server`
* Run `pelican content -s pelicanconf.py -d`
* I can browse to the new article page between `SLEEP START` and `SLEEP END` with no issues.

**Comment by drivet** [comment]
Well, this is embarrassing.  I believe I am, in fact, only copying the html files over when pelican finishes running.  My bad!

I'll look into this further and let you know :)

**Comment by avaris** [comment]
No worries. Although now I'm curious. What does you plugin do that requires files to be "online"?

**Comment by drivet** [comment]
The plugin sends a [webmention](https://www.w3.org/TR/webmention/) to [bridgy](https://brid.gy/) to syndicate the post.  Sending a webmention informs a target URL that a source URL (i.e. my post) has linked to it.  The source URL has to actually be available on the web so the target URL can fetch it for verification purposes.

**Comment by drivet** [comment]
I appear to have it working now.  Sorry for the bother!

**Comment by justinmayer** [comment]
Hi Desmond. Is your Bridgy webmention plugin published somewhere? Would be interesting to see it. 😸

**Comment by drivet** [comment]
Hi there,

It's a work in progress, but it's here:

https://github.com/drivet/pelican-indieweb-kit

The repo contains all the stuff I need to make my website "indieweb ready". The pelican web mention code is under pelican_webmention.

It's not totally clear to me how much of the code is specific to my website and how much is of general interest.

**Comment by justinmayer** [comment]
Many thanks for sharing your endeavors, Desmond. I look forward to checking it out! 🚀

**Comment by silverhook** [comment]
@drivet, I’d be interested in running this on my blog. I would try to implement it in the [Pelican Elegant theme](https://github.com/Pelican-Elegant/elegant/issues/450), if you make it as a Pelican plugin :)

**Comment by justinmayer** [comment]
I added [Pelican IndieWeb Kit](https://github.com/drivet/pelican-indieweb-kit) to the [Externally hosted plugins and tools](https://github.com/getpelican/pelican/wiki/Externally-hosted-plugins-and-tools) wiki page. I think that wraps up this issue, but feel free to comment here if that's not the case so we can re-open it.
