### ISSUE TITLE
Category not available on atom feed

### ISSUE THREAD

**Issue by mauriciogardini** [getpelican/pelican#2556]
I just noticed that, when Pelican generates the atom feed, the category of the post isn't in the feed content.

Searching for the reason, I found this line:

https://github.com/getpelican/pelican/blob/de71f39232947014149436a4205029d3a1b39f3e/pelican/writers.py#L87

Basically, instead of passing the category on the categories field, it passes the tags.

Is there any reason for this behavior than I am not aware of?

Wouldn't be more correct to pass the post category on the categories field, or, at least, to pass the category AND the tags?

**Comment by avaris** [comment]
`category + tags` makes sense to me.

**Comment by justinmayer** [comment]
Hi @mauriciogardini. Would you like to work on implementing a solution for the issue you raised here?

**Comment by mauriciogardini** [comment]
Hi @justinmayer,

Sure, I can try!

Does the solution that @avaris proposed reflects what you think that's correct?

For me, that would be OK.

**Comment by justinmayer** [comment]
Yes, since an article can only have one category, I think any tags should be included as well.

**Comment by mauriciogardini** [comment]
OK!

Tags are what's being added as feed item categories in the present. I will work on adding the category to the feed item category as well, then.

**Comment by mauriciogardini** [comment]
I didn't create a branch yet because I was just fiddling around for now, and I don't think that this is worthy of getting a branch yet.

---

Anyway, I tried implementing what I intended.

The first problem that I was getting is that, because the write_feed method is called once for every kind of feed (all, category, author, tag...)...

https://github.com/getpelican/pelican/blob/de71f39232947014149436a4205029d3a1b39f3e/pelican/generators.py#L301-L461
...and also because the articles are passed by reference, what was processed in the first feed generation process ends up appearing in the second feed generation, and so on.

So, the code below (ignore the minor differences on my version to the trunk one, I was just testing my idea on the code that's on my virtualenv)...

```
     def _add_item_to_the_feed(self, feed, item):
          title = Markup(item.title).striptags()
          link = self.urljoiner(self.site_url, item.url)
          is_rss = isinstance(feed, Rss201rev2Feed)
          categories = item.tags if hasattr(item, 'tags') else list()
          if not is_rss or self.settings.get('RSS_FEED_SUMMARY_ONLY'):
              description = item.summary
          else:
              description = item.get_content(self.site_url)
          # Only adds a Category to the list if there isn't a Category on it

          if hasattr(item, 'category'):
              categories.append(item.category)
          feed.add_item(
              title=title,
              link=link,
              unique_id=get_tag_uri(link, item.date),
              description=description,
              content=item.get_content(self.site_url),
              categories=categories if categories else None,
              author_name=getattr(item, 'author', ''),
              pubdate=set_date_tzinfo( 
                  item.date, self.settings.get('TIMEZONE', None)),
              updateddate=set_date_tzinfo(
                  item.modified, self.settings.get('TIMEZONE', None)
                  ) if hasattr(item, 'modified') else None)
```

which is a customization to the function _add_item_to_the_feed...

https://github.com/getpelican/pelican/blob/de71f39232947014149436a4205029d3a1b39f3e/pelican/writers.py#L55-L93

...ends up appending the category once for every feed generation. Like so:

```
1) "all" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>
2) "category" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>, <c1>
Note the repetition on the <c1>, because this was already "calculated" on the "all" feed generation
3) "author" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>, <c1>, <c1>
Note the repetition on the <c1>, because this was already "calculated" on the "all" and on the "category" feed generation
```

So, for me to achieve the uniqueness of the Category, I had to include an "isinstance" check, like it's shown below:

```
from pelican.urlwrappers import Category

(...)

     def _add_item_to_the_feed(self, feed, item):
          title = Markup(item.title).striptags()
          link = self.urljoiner(self.site_url, item.url)
          is_rss = isinstance(feed, Rss201rev2Feed)
          categories = item.tags if hasattr(item, 'tags') else list()
          if not is_rss or self.settings.get('RSS_FEED_SUMMARY_ONLY'):
              description = item.summary
          else:
              description = item.get_content(self.site_url)
          # Only adds a Category to the list if there isn't a Category on it

          if hasattr(item, 'category') and not any(isinstance(i, Category)
                  for i in categories):
              categories.append(item.category)
          feed.add_item(
              title=title,
              link=link,
              unique_id=get_tag_uri(link, item.date),
              description=description,
              content=item.get_content(self.site_url),
              categories=categories if categories else None,
              author_name=getattr(item, 'author', ''),
              pubdate=set_date_tzinfo( 
                  item.date, self.settings.get('TIMEZONE', None)),
              updateddate=set_date_tzinfo(
                  item.modified, self.settings.get('TIMEZONE', None)
                  ) if hasattr(item, 'modified') else None)
```

With this modification, this happens:
```

1) "all" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>
2) "category" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>
3) "author" feed generation
Post 1 - Tags <t1>, <t2> | Category <c1>
This post ends up having a "categories" list on its feed item composed by:
<t1>, <t2>, <c1>
```

---

The problem is that, after all this, I'm not sure that this generates the result that was intended.

Despite having the expected result on the Atom feed that was generated (the category is being included as a `<category>` on the generated feed), a collateral effect of my implementation was that the Category is now a tag on the article Tags.  So, with the implementation I proposed above, the last tag of a post will not be really a tag, but a link to the Category of the post.

As I stated before, this wasn't a intended effect. It still isn't clear for me why the content of the "categories" parameter of the feed.add_item function that's being called above ends up in the "tags" property of the article.

Any help on why I'm getting this result? I use Pelican as a user for quite some time, but just now that I'm trying to get into Pelican's entrails as a developer, so maybe I didn't get some concept about its organization yet.

**Comment by avaris** [comment]
Because you're getting the `tags` list of an article:
```python
categories = item.tags if hasattr(item, 'tags') else list()
```
and afterwards appending to it:
```python
categories.append(item.category)
```
That appends the category to the original list (which is `article.tags`). So now, you have category in your tags.

This should be all you need:
```python
# in _add_item_to_the_feed
categories = []
if hasattr(item, 'category'):
    categories.append(item.category)
if hasattr(item, 'tags'):
    categories.extend(item.tags)

# ...

feed.add_item(
    # ...
    categories=categories
    # ...
)
```

**Comment by mauriciogardini** [comment]
@avaris, you're totally right.

Do you know those moments when you're so "into" your code and can't see the simple thing that's right in front of your eyes?

Thanks for pointing that out, will work on the implementation.

**Comment by justinmayer** [comment]
Any thoughts from @getpelican/reviewers on this pull request?

**Comment by mauriciogardini** [comment]
Hello... Do I need to make any changes for this to go live? Just let me know.

**Comment by mauriciogardini** [comment]
Thanks, @justinmayer !
