### ISSUE TITLE
Is there interest in an incremental upload option?

### ISSUE THREAD

**Issue by paultopia** [getpelican/pelican#2557]
Hi there, 

So one issue I'm running into is that while build times are lightning fast (yay!), deploy can be slow, especially on large sites, because the built-in upload options (i.e., in the makefile) just upload the entire output directory to the target.  (For my own site, for example, I need to make available to users PDFs of most posts, but uploading all those on every deploy, even for posts that haven't changed a bit, takes *forever* just because the internet is slow.) 

I see that over some years there's been a ton of talk about caching things, and it looks like some was implemented in response to #224 on the build side.  But is there any interest in carrying this over to the deploy side, either by tweaking the makefile or by building separate deploy scripts?  

I was planning to roll my own solution that just stores a hash of every file in the output directory in a sqlite table and only uploads those that are changed on each deploy.  But happy to try to produce a version that can be contributed to the broader public if there's interest.

**Comment by justinmayer** [comment]
Hi Paul. To begin with some background... All of the automation convenience tooling options included with Pelican (Make, Invoke, etc.) are meant to be starting points for folks to use, not use, and/or customize as they see fit. But we get enough support requests for these extras that I'm inclined to remove them from Pelican core in the next major release and instead have them live in another repository.

With that tangential aside behind us... The Quickstart script should ask how you want to upload your files. If you choose the Rsync option, only the modified files should be transmitted to the server. At least that's how it works for me.

**Comment by paultopia** [comment]
Thanks Justin!  I somehow completely missed the rsync option myself (oops!  And thinking about rsync would have been helpful!  I got into a weird rabbit hole with my own customizations, already have all sorts of weird hashing with my own bolted-on PDF generation, when it came time to think about upload it didn't even... occur... to me that rsync exists. LOL)---but yeah, that clearly meets this need, so there's no reason to build more tooling.  Thanks for indulging my silliness!  Easiest issue to close ever.

**Comment by justinmayer** [comment]
Hehe. No worries! I find it's usually better to rely on "do one thing well" utilities like Rsync than to re-invent the wheel. 😉
