### ISSUE TITLE
CRITICAL: NameError: name 'date' is not defined

### ISSUE THREAD

**Issue by thelou1s** [getpelican/pelican#2563]
Hi, 
  I compile it using 'pelican content' in Windows7, python3.5.2,  and got this error. Could anyone
help me? thanks in advance.

```
(pelican-blog) E:\Python\pelican-blog\pelican>pelican content
CRITICAL: NameError: name 'date' is not defined
```

**Comment by justinmayer** [comment]
Hard to say based on such limited info, but perhaps you didn't add date metadata to your article(s). Also, please read (thoroughly) the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
