### ISSUE TITLE
Inconsistent ordering of plugin hooks

### ISSUE THREAD

**Issue by VorpalBlade** [getpelican/pelican#2564]
I have multiple plugins that do some form of post-processing:

* A SVG minifying plugin (https://github.com/getpelican/pelican-plugins/tree/master/optimize_images)
* CSS minifier (https://github.com/getpelican/pelican-plugins/tree/master/yuicompressor)
* HTML minifier (https://github.com/rdegges/pelican-minify)
* A gzipping plugin (https://github.com/getpelican/pelican-plugins/tree/master/gzip_cache)

All use the `finalized` hook, but the order of execution seems random, since sometimes both the compressed and uncompressed files are minified but sometimes only the uncompressed versions are minified. In this case I obviously want to run the minifiers first and only create the gzip cache at the very end.

Maybe consider changing so that plugins that register for the same hook execute in e.g. the order they are added in the  `PLUGINS` list of `pelicanconf.py`, or offer some other way of specifying ordering for these sorts of plugins.

Environment:
* OS: Ubuntu 18.04
* Python: Python 3.7

**Comment by justinmayer** [comment]
Indeed. Seems like a reasonable and valid use case. Is something you would like to help implement?

**Comment by avaris** [comment]
Unfortunately, it is [not possible](https://pythonhosted.org/blinker/#blinker.base.Signal.send) without ditching `blinker` and switching to a different signaling package.

**Comment by VorpalBlade** [comment]
@justinmayer I might be able to help yes, depending on how much time I have and when. (I do know python).

@avaris Python dicts are ordered by default since Python 3.6 (as an undocumented implementation detail though!). Since I'm using Python 3.7 I would suspect it might be slightly more complicated than that to fix.

I had a quick look at the source code of the Signal class, and it seems to have some advanced features, such as filtering on which sender of the signal it is (see e.g. `receivers_for`) that is the crux of the problem. Specifically I believe that the `_by_receiver`/ `_by_sender` members (`defaultdict(set)`) adds the unpredictable behaviour. That set would need to be replaced by a list, but then handling adding the same receiver more than once would have to be handled manually.

**Comment by avaris** [comment]
Yes, that's why I said "may" :). It needs a bit hacking around. An `OrderedSet` implementation based on `dict/OrderedDict` is doable.

Perhaps a better alternative is to have an intermediate dispatcher that collects functions, combines them into one with order and that dispatcher is connected to the blinker signal instead. Something like:

```python
class PelicanSignal(object):
    def __init__(self, signal):
        self.signal = signal
        signal.connect(self)
        self.receivers = []

    def connect(self, receiver):
        self.receivers.append(receiver)

    def __call__(self, *args, **kwargs):
        for receiver in self.receivers:
            receiver(*args, **kwargs)
```

and our signals will instead be:
```python
finalized = PelicanSignal(signal('finalized'))
```

Obviously, the above is very incomplete and doesn't support `sender` style filtering but could be a starting point.

**Comment by VorpalBlade** [comment]
Something like that might certainly work. If I were to implement it (probably not before June), one question of interest is where sender style filtering is used on pelican so that this can be tested (or maybe it is already covered by unit tests?).

**Comment by avaris** [comment]
`pelican` itself doesn't use signals, plugins might. But given that it works by object identity, not much use for it. `content_object_init` signal would have been perfect, say if you could filter by class (`Article` or `Page`), except we send the instance and therefore useless.

**Comment by justinmayer** [comment]
Hi Arvid. Any updates on your implementation of a solution for this issue?

**Comment by VorpalBlade** [comment]
Very sorry, but I have been dealing with unexpected real life issues. I have no idea when I will have time to look at this again.

**Comment by justinmayer** [comment]
No problem. When you do have time, please comment here and we can re-open the issue. In the interim, I hope you get through the current unexpected bumps in the road. Sending good vibes. ✨
