### ISSUE TITLE
Summary ellipses are placed within a link tag

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican#2567]
I'm writing a custom theme, and I noticed that if the end of `Article.summary` is an unclosed link, the ellipses from `summary` are placed within the resulting `<a>` tag.

For instance, I have a [markdown file](https://pastebin.com/X0z1zM2D) (pastebin used because of length) and I'm using the following markup for a theme:

```jinja
{% for article in articles %}
    <h2>{{ article.title }}</h2>
    <p>{{ article.summary }}</p>
{% endfor %}
```

The end of the summary is `[Droid Bishop](https://droidbishop.bandcamp.com/)`, but pelican renders it as `<a href=https://droidbishop.bandcamp.com/>Droid Bishop ...</a>` instead of placing the `...` outside the `<a>` tag. Ideally, this should be rendered as `<a href=https://droidbishop.bandcamp.com/>Droid Bishop</a> ...` instead.

**Comment by justinmayer** [comment]
I think this occurs because of where the automatic truncation is occurring. Seems to me the best solution is to manually specify summary metadata in these cases.
