### ISSUE TITLE
Markdown Syntax highlighting - Broken HTML escaping

### ISSUE THREAD

**Issue by ekaitz-zarraga** [getpelican/pelican#2569]
HTML escaping fail because of the the syntax highlighter is breaking the HTML code in different `spans` in order to make the highlighting.
It's hard for me to explain it, better see this example: 

Input code looks like this:

```
    ::clojure
    (defn- ->tempfile
    ; Shortened for brevity

```

But the generated HTML with the Codehilite extension added breaks the `>` symbol, and in the rendered website it looks like this:

```
(defn- -&gt;tempfile
```

This happens because the generated HTML separated the `&gt;` in different `span`s:
```html
<pre>
<span></span>
(<span style="color: #008000; font-weight: bold">defn- </span><span style="color: #19177C">-</span><span style="color: #666666">&amp;</span><span style="color: #19177C">gt</span><span style="color: #408080; font-style: italic">;tempfile</span>
<!-- shortened for brevity -->
</pre>
```

I think this happens because the Code piece from the markdown is being escaped before sending it to the Codehilite extension and codehilite extension is getting the `&gt;` instead of the `>` directly to be escaped later.

**The HTML escaping should be done after the extension parses the code or not done at all.**

EDIT: It also happens with pygments disabled, the generated HTML looks like this:
``` html
<pre class="codehilite"><code class="language-clojure">(defn- -&amp;gt;tempfile
<!--shortened for brevity--></code></pre>
```

This is obviously wrong. Inside the `code` tag there's no need to scape HTML and that's why it's also being rendered wrong. I'd say the reason is the same than in the previous example.

**Comment by avaris** [comment]
python-markdown issue. See #2493.

**Comment by ekaitz-zarraga** [comment]
Oh! It was already filed.
I added an issue in Python-Markdown:
https://github.com/Python-Markdown/markdown/issues/821
There should be a simple solution for this.

**Comment by ekaitz-zarraga** [comment]
Looks like it's solved in Python Markdown 3.1, time to move to Python Markdown 3.1 version?

**Comment by avaris** [comment]
Well, sure? Not much to do on pelican side though. We don't have markdown as a dependency. It's up to the user to install a particular version. Only relevant part to pelican is some tests. And due to some output inconsistency between markdown 2.x and 3.x it was fixed as 2.x. Could be relaxed I guess to `!= 3.0.*` if feasible.

**Comment by justinmayer** [comment]
Fix via: `pip install -U markdown`

Closing in favor of [aforementioned issue](https://github.com/getpelican/pelican/issues/2569#issuecomment-490084943).
