### ISSUE TITLE
Meta fields not working in Pelican 4.0.1

### ISSUE THREAD

**Issue by prahladyeri** [getpelican/pelican#2573]
I've just installed `pelican` package and learning about this static site generator by going through the docs. In the Quickstart section, I came across:

> Linking to authors, categories, index and tags
> You can link to authors, categories, index and tags using the {author}name, {category}foobar, {index} and {tag}tagname syntax.

So, I tried to use these and other meta fields in my first "hello" article as follows:

	Title: My First Review
	Date: 2019-05-17 10:20
	Category: Review
	Tags: Python, PHP
	Summary: Short version of my post

	Following is a review of my favorite mechanical keyboard.

	{date}
	{title} /foobar
	{author}name, {category}foobar
	{index} and {tag}tagname
	|filename|an_article.rst
	|tag|tagname

But when I generate the site using `pelican content`, the meta tags are shown as it is in the browser output, they are not "processed" to what they are as they are supposed to:

![pelican_meta_fields_issue](https://user-images.githubusercontent.com/5732256/57925913-6f248480-78c7-11e9-8fe7-60d6edf3acaa.png)

**Comment by avaris** [comment]
Links (`href` or similar) is processed. Not plain text. i.e.:

```
[Link to an author page]({author)authorname)
```

**Comment by prahladyeri** [comment]
Thanks @avaris! Yep, I can see that `{author}` field could be processed as a link, but not the others such as `{date}`, `{title}`, etc. or even a custom one. Is there a way to use them anywhere in the article other than through a link?

**Comment by avaris** [comment]
Well, no... But what is the use case? 

I get the feeling that you're trying to place stuff in content body that would normally go to theme/template.

**Comment by prahladyeri** [comment]
Yep, now that I realize, I got into the theming part pretty soon I guess! I'll revisit this part once I read more about creating themes and calling these variables there. Closing this issue for now.
