### ISSUE TITLE
Markdown generation not working

### ISSUE THREAD

**Issue by phschoen** [getpelican/pelican#2574]
I followed the pelican example to get a first setup running. However the markdown files are not generated the reST files are. Am i missing some extra option which are not there?

    $mkdir test && cd test

    $pelican-quickstart	
        Welcome to pelican-quickstart v4.0.1.

	This script will help you create a new Pelican-based website.

	Please answer the following questions so this script can generate the files
	needed by Pelican.

	    
	> Where do you want to create your new web site? [.] 
	> What will be the title of this web site? test
	> Who will be the author of this web site? tester
	> What will be the default language of this web site? [en] 
	> Do you want to specify a URL prefix? e.g., https://example.com   (Y/n) n
	> Do you want to enable article pagination? (Y/n) n
	> What is your time zone? [Europe/Paris] 
	> Do you want to generate a tasks.py/Makefile to automate generation and publishing? (Y/n) 
	> Do you want to upload your website using FTP? (y/N) n
	> Do you want to upload your website using SSH? (y/N) n
	> Do you want to upload your website using Dropbox? (y/N) n
	> Do you want to upload your website using S3? (y/N) n
	> Do you want to upload your website using Rackspace Cloud Files? (y/N) n
	> Do you want to upload your website using GitHub Pages? (y/N) n
	Done. Your new project is available at /tmp/test

so far so good then i create 2 example files with markdown and reST

       $echo "Title: test-md
	Date: 2019-02-02 01:01
	Tags: python
	Summary: test 

	test
	" > content/file.md

	$echo "test-rst
	########
	:Date: 2019-02-02 01:01
	:Tags: python
	:Summary: test 

	test
	" > content/file.rst
       
now on processing only the rst is processed:

      $make html 
      pelican /tmp/test/content -o /tmp/test/output -s /tmp/test/pelicanconf.py 
      Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.11 seconds

even seting the following option in the `pelicanconf.py` did not change this 

	MARKUP = ('md',)
	# Markdown Configuration:
	MARKDOWN = {
	    'extension_configs': {
		'markdown.extensions.codehilite': {'css_class': 'highlight'},
		'markdown.extensions.toc' : {},
		'markdown.extensions.extra': {},
		'markdown.extensions.meta': {},
	    },
	    'output_format': 'html5',
	}

<details>
<summary>pelican version 4.0.1</summary>

	sudo pip install --upgrade pelican
	[sudo] password for phschoen: 
	Requirement already up-to-date: pelican in /usr/lib/python3.7/site-packages (4.0.1)
	Requirement already satisfied, skipping upgrade: blinker in /usr/lib/python3.7/site-packages (from pelican) (1.4)
	Requirement already satisfied, skipping upgrade: pygments in /usr/lib/python3.7/site-packages (from pelican) (2.4.0)
	Requirement already satisfied, skipping upgrade: jinja2>=2.7 in /usr/lib/python3.7/site-packages (from pelican) (2.10)
	Requirement already satisfied, skipping upgrade: unidecode in /usr/lib/python3.7/site-packages (from pelican) (1.0.23)
	Requirement already satisfied, skipping upgrade: python-dateutil in /usr/lib/python3.7/site-packages (from pelican) (2.8.0)
	Requirement already satisfied, skipping upgrade: pytz>=0a in /usr/lib/python3.7/site-packages (from pelican) (2019.1)
	Requirement already satisfied, skipping upgrade: feedgenerator>=1.9 in /usr/lib/python3.7/site-packages (from pelican) (1.9)
	Requirement already satisfied, skipping upgrade: six>=1.4 in /usr/lib/python3.7/site-packages (from pelican) (1.11.0)
	Requirement already satisfied, skipping upgrade: docutils in /usr/lib/python3.7/site-packages (from pelican) (0.14)
	Requirement already satisfied, skipping upgrade: MarkupSafe>=0.23 in /usr/lib/python3.7/site-packages (from jinja2>=2.7->pelican) (1.1.1)

</details>

<details>
<summary>markdown version 3.1</summary>

    sudo pip install --upgrade markdown
    Requirement already up-to-date: markdown in /usr/lib/python3.7/site-packages (3.1)
    Requirement already satisfied, skipping upgrade: setuptools>=36 in /usr/lib/python3.7/site-
    packages (from markdown) (41.0.1)
</details>

**Comment by avaris** [comment]
Can you show output of `DEBUG=1 make html`?

**Comment by prahladyeri** [comment]
Try saving the markdown and rst files as `content/file-markdown.md` and `content/file-restructured.rst` respectively. Since you've omitted the `Slug` attribute which is basically the URL of your post, I think it is defaulting the `Slug` to the filename which happens to be `content/file` without the extension in both cases, so it is generating only one post instead of two. The titles should also be separate for the two posts.

**Comment by justinmayer** [comment]
Thanks to @avaris and @prahladyeri for the help. Much appreciated!

@phschoen: Feel free to post a comment here if you need further help with this issue.
