### ISSUE TITLE
Quickstart deleted my content completely

### ISSUE THREAD

**Issue by ctivanovich** [getpelican/pelican#2576]
I ran pelican.server and saw a notice to update my makefile and other files by running pelican-quickstart. I thought, okay, sure. I ran the command, and boom, all of my content disappeared, not even to be found in the Recycle Bin (Windows). The generated html files remain, at least, so I am attempting to extract the ipython notebook info to reconstruct the notebooks, but, that's ridiculous. If running quickstart is the recommended method to update pelican files for my site, it should warn me it's going to do that!

**Comment by justinmayer** [comment]
I'm sorry that happened to you, Christopher. I tried to replicate what you experienced but could not. If I run `pelican-quickstart` (latest master) with an existing `content` directory, the code [checks](https://github.com/getpelican/pelican/blob/master/pelican/tools/pelican_quickstart.py#L322-L325) for that and yields an error:

    Error: [Errno 17] File exists: '/pelicantest/content'

I did the above test on macOS; perhaps the behavior on Windows is different. I don't believe any Pelican maintainers use Windows (myself included), so this isn't something we can easily test. Perhaps you could perform a few sample tests and see whether you can reliably replicate the behavior you describe?

**Comment by avaris** [comment]
I tested on Windows and can't replicate it.
```text
(pelican-py3.7) λ dir /B content
article.md

(pelican-py3.7) λ cat content\article.md
Title: test
Date: 1/1/2019

Content
(pelican-py3.7) λ pelican-quickstart
Welcome to pelican-quickstart v4.0.1.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.


> Where do you want to create your new web site? [.]
> What will be the title of this web site? Test
> Who will be the author of this web site? Me
> What will be the default language of this web site? [English]
> Do you want to specify a URL prefix? e.g., https://example.com   (Y/n) n
> Do you want to enable article pagination? (Y/n)
> How many articles per page do you want? [10]
> What is your time zone? [Europe/Paris]
> Do you want to generate a tasks.py/Makefile to automate generation and publishing? (Y/n)
> Do you want to upload your website using FTP? (y/N)
> Do you want to upload your website using SSH? (y/N)
> Do you want to upload your website using Dropbox? (y/N)
> Do you want to upload your website using S3? (y/N)
> Do you want to upload your website using Rackspace Cloud Files? (y/N)
> Do you want to upload your website using GitHub Pages? (y/N)
Error: [WinError 183] Cannot create a file when that file already exists: 'D:\\workspace\\pelican-test\\content'
Error: [WinError 183] Cannot create a file when that file already exists: 'D:\\workspace\\pelican-test\\output'
Done. Your new project is available at D:\workspace\pelican-test

(pelican-py3.7) λ dir /B content
article.md

(pelican-py3.7) λ cat content\article.md
Title: test
Date: 1/1/2019

Content
```
