### ISSUE TITLE
Ability to set page as index instead of articles

### ISSUE THREAD

**Issue by prahladyeri** [getpelican/pelican#2578]
This is in reference to [bug #400](https://github.com/getpelican/pelican/issues/400) of similar title which was marked as fixed but I couldn't find any details of "How To" anywhere on that issue thread or in the pelican docs.

I tried setting the `INDEX_URL` and `INDEX_SAVEAS` settings in the `pelicanconf.py` but it doesn't seem to make any difference. The index page ("/") still consists of only articles list and the `INDEX_URL` (`blog/` in this example) still returns a 404.

    INDEX_URL = 'blog/'
    INDEX_SAVEAS = 'blog/index.html'

In this example, I want the articles list to appear on the `blog/` URL link and the home page should consist of my `about.md` page. I simply don't understand how to do that.

**Comment by avaris** [comment]
http://docs.getpelican.com/en/stable/faq.html#how-can-i-use-a-static-page-as-my-home-page

**Comment by justinmayer** [comment]
Thanks for the pointer, @avaris!

@prahladyeri: If in doubt, the FAQ is always a good place to look. :wink:
