### ISSUE TITLE
Version requirements on Markdown package?

### ISSUE THREAD

**Issue by szhorvat** [getpelican/pelican#2579]
I was not able to find any other support channel, so I am asking here. Please let me know if there is another place to ask (e.g. mailing list). The IRC channel is mostly dead in recent months and the channel logs are gone (so we can't check responses received when not logged in).  Most of us can't afford to stay logged in continuously for 24 hours, or even for longer than a couple of hours.

----

Is there a list of requirements on the versions of dependencies, in particular the Markdown package?  I am using Pelican 4.0.1.  With Markdown 3.x, I see `<` converted to `&lt;` even in code blocks. With Markdown 2.x, everything is fine (so for now I simply downgraded).

Before I invest too much time into trying to debug this, it would be useful to know whether this is already known issue, and whether this is a problem Pelican or Markdown, or more likely an issue with my own setup.

**Comment by justinmayer** [comment]
> it would be useful to know whether this is already known issue

Hi Szabolcs. As mentioned in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, one of the best first steps is to check existing issues. It took me a matter of seconds to search for and locate the relevant existing issue: https://github.com/getpelican/pelican/issues/2493

As noted in that thread, some folks report that the latest version (3.1.x) of Python-Markdown resolves the problem. If that's not the case for you, let's discuss potential resolution in the existing issue thread.

**Comment by szhorvat** [comment]
Thanks for pointing to that issue. My search attempts did not lead me to this one. I confirm that 3.1 fixes it.
