### ISSUE TITLE
While running online w3 validator on generated webpage it complains because of 'space'

### ISSUE THREAD

**Issue by iranzo** [getpelican/pelican#2581]
error: line 140: Bad value “/Supported Plugins/photogallery.png” for attribute “src” on element “img”: Illegal character in path segment: space is not allowed.

When the source content folder contains an img that is linked with {static}

Should this be escaped from pelican on generation to use %20 ?

**Comment by justinmayer** [comment]
Any thoughts on this from @getpelican/reviewers?

**Comment by avaris** [comment]
So, I guess `Content.url` should be encoded?
