### ISSUE TITLE
Summary metadata with newline is truncated

### ISSUE THREAD

**Issue by askpatrickw** [getpelican/pelican#2583]
This is on Markdown. No idea, about RST.

When using the Summary metadata field, if you have a newline to keep your line lengths short, the summary is truncated at the newline and any following metadata is then added to the body of the post along with the rest of the summary after the newline.

Works
```
athor: patrick
summary: I am a very longwinded hamster rancher from Rodentville, RI and I am looking forward to Pelican fixes.
open_graph: {static}/images/hamster-rancher.png
```

Does Not Work
```
athor: patrick
summary: I am a very longwinded hamster rancher from Rodentville, RI and
I am looking forward to Pelican fixes.
open_graph: {static}/images/hamster-rancher.png
```

**Comment by avaris** [comment]
You need to indent it by 4+ spaces:
```markdown
summary: first line
    second line
```

https://python-markdown.github.io/extensions/meta_data/#syntax

**Comment by justinmayer** [comment]
I hesitate to suggest “Then don’t do that,” but at the moment I don’t have a better recommendation. I always imagined line breaks to be significant in content metadata. It never occurred to me that one *could* add a line break and expect the parser to sort out what’s what. But that’s just me. 😊

Anyone else have any ideas?

**Comment by askpatrickw** [comment]
Yep... indenting works. Sorry about that. ;-)
