### ISSUE TITLE
Best Practices - modify downloaded theme

### ISSUE THREAD

**Issue by lesatdgl** [getpelican/pelican#2587]
pelican-themes installs downloaded themes at /home/<user id>/.local/share/virtualenvs/pelican-projects-xtj21HM1/lib/python3.6/site-packages/pelican/themes/<theme>

I'm making changes to the clean-blog theme.

What's best? Copy clean-blog to my-clean-blog and hack away or ????

**Comment by avaris** [comment]
This is one of the reasons for avoiding `pelican-themes`. 

Clone the theme repo, modify and use path for `THEME` setting.

**Comment by lesatdgl** [comment]
If I understand you, I'd have a dir next to my content dir /theme, into which I'd clone the theme; I'd do my hacking there and point to it with the THEME setting?

Les Dunaway
770-490-7546

**Comment by lesatdgl** [comment]
If I understand you, I'd have a dir next to my content dir /theme, into which I'd clone the theme; I'd do my hacking there and point to it with the THEME setting?

OR

I'd install the theme with pelican-themes, copy the one I want to hack into said dir, ...

??/

Les Dunaway
770-490-7546
