### ISSUE TITLE
Using Makefile with paths containing spaces fails

### ISSUE THREAD

**Issue by rpmzandwijk** [getpelican/pelican#2591]
When answering "Yes" to the question "Do you want to generate a tasks.py/Makefile to automate generation and publishing?" while running pelican-quickstart, a Makefile is created.

However, when the pelican site is located in a directory of which the path contains spaces, stuff like 'make html' fails. This could easily be fixed by using quotes. E.g.:

`html:`
`    $(PELICAN) "$(INPUTDIR)" -o "$(OUTPUTDIR)" -s "$(CONFFILE)" $(PELICANOPTS)`

**Comment by justinmayer** [comment]
Have you checked existing issues / PRs? I seem to recall this topic has already been raised.

**Comment by avaris** [comment]
Yes, #2542

**Comment by rpmzandwijk** [comment]
> Have you checked existing issues / PRs? I seem to recall this topic has already been raised.

Apparently, I forgot to check the PRs. Sorry for the noise.
