### ISSUE TITLE
Live reload does not work ARTICLE_URL does not end at ".html"

### ISSUE THREAD

**Issue by talha131** [getpelican/pelican#2595]
1. Create a default blog using `pelican-quickstart`
1. Add a test `.md` file
1. In your `pelicanconf.py` set this option
    ```python
    ARTICLE_URL = "{slug}"
    ```
1. Run `invoke livereload`

All links to articles will NOT end with a `.html`. For example, 

```
http://localhost:8000/contributing-new-features
```

But clicking on them gives error.

```
404: Not Found
```

live-reload server logs show

```log
[I 190719 22:27:29 handlers:135] Browser Connected: http://localhost:8000/
[W 190719 22:27:35 log:200] 404 GET /contributing-new-features (127.0.0.1) 0.62ms
[W 190719 22:28:32 log:200] 404 GET /contributing-new-features (127.0.0.1) 0.58ms
```

This issue is because, live-reload does not support extension less files. There is a PR for it in 2016 but it has not been accepted.

https://github.com/lepture/python-livereload/pull/131

**Comment by avaris** [comment]
OK... What would you suggest `pelican` do for this?

**Comment by justinmayer** [comment]
Yeah, I think I’m with @Avaris on this one. I suggest either using `{slug}/index.html`, using some other URL setting that includes an extension, or submitting an issue to the LiveReload repo. Otherwise, these kinds of edge cases start to dis-incentivize including ancillary tooling alongside Pelican core — at some point the support burden starts to outweigh the intended benefits.

That said, perhaps this could be addressed by including an advisory warning such that folks are at least aware that extension-less URLs don’t currently function correctly with LiveReload. PRs welcome.

**Comment by talha131** [comment]
@avaris @justinmayer totally agree with you guys. My intention behind this issue was not to make Pelican team fix a bug or lack of feature in an external project, but to save times of other users who may stumble on this bug.

-----

Anyone else coming to this issue from Google.

## Easiest Workaround

Remove this setting from your configuration or move it to publish configuration

```python
ARTICLE_URL = "{slug}"
```

This should work for most users. You local links will end at `.html` but the production version will have pretty URLs.

## Use Alternative Tools

I opted to use [gulp.js](https://gulpjs.com/) and [BrowserSync](https://www.browsersync.io/). 

You can read about why [here](https://elegant.oncrashreboot.com/live-reload-elegant-documentation-using-gulpjs#why-browsersync-is-better-than-python-livereload).

And on how to setup, see these links:

1. [Prerequisites](https://elegant.oncrashreboot.com/live-reload-elegant-documentation-using-gulpjs#prerequisites)
1. [gulp configuration](https://github.com/Pelican-Elegant/elegant/blob/master/gulpfile.babel.js)
1. [package.json](https://github.com/Pelican-Elegant/elegant/blob/master/package.json)

---

<sup>Related to https://github.com/Pelican-Elegant/elegant/issues/285</sup>
