### ISSUE TITLE
WRITE_SELECTED does not work

### ISSUE THREAD

**Issue by stgatilov** [getpelican/pelican#2601]
I am looking into ways to accelerate pelican generation for faster articles editing.
I have tried to use [WRITE_SELECTED](http://docs.getpelican.com/en/stable/settings.html#writing-only-selected-content) setting, but it turned out that it does not work properly.

I have Windows 10, and use Python 3.7 with pelican 4.1.0.
Here is how I reproduced it on fresh install.

1. Install pelican in virtualenv:

        pipenv install pelican markdown

2. Create quickstart blog:

        pipenv run pelican-quickstart

3. Add some markdown article to `content/test.md` with title `Hello`.

4. Add the following line to `pelicanconf.py`:

        WRITE_SELECTED = ['hello.html']

5. Go to file `.venv\Lib\site-packages\pelican\utils.py` and add on line 896 (in `is_selected_for_writing`):

        print("'%s'   vs   '%s'" % (path, settings['WRITE_SELECTED']))

6. Generate blog:

        pipenv run pelican -s pelicanconf.py

This is what I see in stdout:

    'output\hello.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\index.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\tags.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\categories.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\authors.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\archives.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\category/misc.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    'output\author/myself.html'   vs   '['D:\\StevePrograms\\Blog\\temp\\hello.html']'
    Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.23 seconds.

The file `hello.html` is not generated in `output`.

As far as I understand the code in `is_selected_for_writing`, writing is triggered only if the path matches exactly something from the list. It seems that I have no way to achieve that currently.

**Comment by hipe** [comment]
(As of this writing, this feature silently fails for me. I offer a patch that fixes it for me in #2678)
