### ISSUE TITLE
Code blocks in comments loose leading spaces

### ISSUE THREAD

**Issue by GadgetSteve** [getpelican/pelican#2603]
On a site generated with pelican any code blocks that contain leading spaces have them stripped in the comment display. This is incredibly bad for languages like python where they are significant and messy in other languages like C/C++ where they help to clarify the code.

For instance, **in a comment**:

&lt;code>
def fn(x):
&nbsp;&nbsp;&nbsp;&nbsp;""" Do something to x """
&nbsp;&nbsp;&nbsp;&nbsp;# Doing something!
&nbsp;&nbsp;&nbsp;&nbsp;return result
&lt;/code>

is displayed as:

<pre>
def fn(x):
""" Do something to x """
# Doing something!
return result
</pre>
Which will not work if copied and pasted without reformatting and doesn't get the intent across.

**Comment by avaris** [comment]
What's a "comment display"?

**Comment by GadgetSteve** [comment]
@avaris When a web site has adding comments enabled you can type them in fine but when displayed the leading spaces are suppressed. _(Still there when you go to edit)._

See my comment at the end of https://pbpython.com/papermil-rclone-report-2.html - I eventually managed to get the code to look OK by putting it in a &lt;pre> &lt;/rep> block.

**Comment by avaris** [comment]
Well, that's disqus issue. Everything in that comment block is handled by them.

**Comment by justinmayer** [comment]
As @avaris pointed out, Disqus is an external service. While Pelican has convenience hooks for Disqus at the moment (but perhaps not in the future), Disqus comments are not related to Pelican itself.
