### ISSUE TITLE
livereload does not work correctly with recursive glob

### ISSUE THREAD

**Issue by 1oglop1** [getpelican/pelican#2604]
Hi, I wanted to test a new feature with `livereload` however the watchers do not pick up recursive glob correctly due to a bug reported in 
lepture/python-livereload/issues/156

This affects a current code:
https://github.com/getpelican/pelican/blob/9154d8f42e7e7ca2dc5c417e3e1de987ed49b238/pelican/tools/templates/tasks.py.jinja2#L103

However, there is a PR lepture/python-livereload/pull/203 to fix the recursive glob.

**Current behaviour**
Only files in subdirectories cause the server to reload.

**Expected behaviour**
All watched files should cause the server to reload.

**Steps to reproduce:**

1. `pelican-quickstart` -> Yes to automation
2. Recreate this file structure 
    ```
    content/
    ├── hello.rst
    ├── images
    │   ├── img.png
    │   └── sub
    │       └── asterix.jpg
    └── subdir
        └── hello2sub.rst
    ```
3. Start livereload `invoke livereload`
4. Navigate to http://127.0.0.1:8000
5. Make a change in `content/subdir/hello2sub.rst`
6. Observer the server reloading the content
7. Make a change in `content/hello.rst`
8. The server will not reload the content

**Comment by justinmayer** [comment]
Hi Jan. Given that this seems to be related to a Python-LiveReload bug and not related to Pelican, what is _this_ issue for? 😊

**Comment by 1oglop1** [comment]
It's here in case someone else runs in to the same problem because it took me some time to find workaround (requires to edit `tasks.py`).
I will post the temp workaround later and then close the issue

**Comment by 1oglop1** [comment]
The workaround is to install the version from pullrequest lepture/python-livereload/pull/204/

`pip install git+https://github.com/lepture/python-livereload.git@refs/pull/204/head`

Or modifying `tasks.py` by adding own custom watcher from here: lepture/python-livereload/issues/156
