### ISSUE TITLE
improperly formatted URL in formatted metadata

### ISSUE THREAD

**Issue by emii** [getpelican/pelican#2605]
URLS are formatted with an absolute path when specified in the *metadata* (unexpected), while URLS are formatted with a relative path when specified in the *content* (expected).

The relevant settings in `conf.py` are the following:

`RELATIVE_URLS = True`
`SITEURL = 'http://abcde.xyz'`
`FORMATTED_FIELDS = ['summary']`

In the same article the relevant metadata and the content are the following:

**Metadata:**
`Summary: ![image1]({static}img/IMAGE1.JPG)`
**Content:**
`![image1]({static}img/IMAGE1.JPG)`

In this case, unexpectedly the link for the image specified from the **metadata** will look like:
`<p><img alt="image1" src="http://abcde.xyz/static/img/IMAGE1.JPG"></p>`

While the link for the **content** will look like:
`<p><img alt="image1" src="../../static/img/IMAGE1.JPG"></p>`

**Comment by justinmayer** [comment]
Thank you for the detailed issue report, Emi. Is this issue something you would be willing to help us track down and fix? 😊

**Comment by avaris** [comment]
I think the issue is [`get_summary`](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L389-L402) isn't running `_update_content` like [`get_content`](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L377-L382)

**Comment by Marlene85** [comment]
hi @justinmayer, unfortunately I little knowledge on the pelican internals, maybe @avaris ?

**Comment by justinmayer** [comment]
@emii: Now that @avaris has provided some guidance regarding how this might be addressed, would you be willing to try implementing a fix? @avaris and I are available here and on IRC should you need assistance or pointers.
