### ISSUE TITLE
STATIC_PATHS = ['images', 'js'] - images copied ; js not ????

### ISSUE THREAD

**Issue by lesatdgl** [getpelican/pelican#2606]
I have content/static and theme/static to separate static from a particular use of the theme from static applying to all uses of the theme

I have content/static/images, content/static/js and have specified STATIC_PATHS = ['images', 'js']
The content of content/static/images is copied to output/static/images -
The content of content/static/js is not copied  

What's the proper incantation?

**Comment by lesatdgl** [comment]
Sorry, left off the files
[WYD.zip](https://github.com/getpelican/pelican/files/3490341/WYD.zip)

**Comment by avaris** [comment]
`STATIC_PATHS` needs full path from content:

```python
STATIC_PATHS = ['static/images', 'static/js']
```

PS: `images` (or part of it) got copied probably because you have linked files. `pelican` will auto-add a linked file as `Static` even if it's not in `STATIC_PATHS`.

**Comment by lesatdgl** [comment]
Awesome! 

Should docs example of STATIC_PATHS "STATIC_PATHS = ['images']" be updated to show required full path?

Les Dunaway
770-490-7546

**Comment by avaris** [comment]
That is the full path :). Default `STATIC_PATHS` will include `images` (that is `content/images`, *not* `content/static/images`).

Maybe, you are confusing it with theme. In theme `static` folder has special purpose. But in content, not so much. `STATIC_PATHS` (or anything static related) won't require you to put stuff in a `static` folder.

**Comment by lesatdgl** [comment]
No, not confusing it. I understand what you are saying. It seems that scattering dirs all around without a plan or a convention is bad

I created content/static/images and js and css (if I'd had any) because they are static and I wanted anyone looking to know that.
I'd never have a content/images dir and for sure not a content/js or content/css or ...

Is there any kind of "best practices"? 

Les Dunaway
770-490-7546

**Comment by avaris** [comment]
Well, `pelican` tries to be flexible enough so that you can tailor it to your workflow, instead of the other way around. So "best practice" is pretty much what you want it to be :).

**Comment by lesatdgl** [comment]
Not all bad - it just means I must invent my workflow
