### ISSUE TITLE
Getpelican.com not available in Russia

### ISSUE THREAD

**Issue by sio** [getpelican/pelican#2613]
Unfortunately, getpelican.com is not available in Russia.

This is not due to any fault of yours. Looks like the IP Linode gave you was also used by Telegram at some point in time, and you've fallen victim to our government's clumsy attempts to block Telegram. The court order is dated by April, 2018.

I'm not sure you can or should do something about this, just letting you know.

**Comment by jorgesumle** [comment]
You can clone https://github.com/getpelican/pelican-blog, generate its documentation from this repository with Sphinx and host it on some server without an IP blocked by Russia. The simplest option is to use Tor.

**Comment by justinmayer** [comment]
@sio: Thank you for reporting this. When I find enough time, I would indeed like to switch IP addresses so this problem can be resolved.

**Comment by epogrebnyak** [comment]
Can confirm https://blog.getpelican.com/ is visible from Russia now, either due to IP switch or lifting of some restrictions. Probably can close the issue?

**Comment by justinmayer** [comment]
@epogrebnyak: That is great to hear. Thank you for letting us know! If anyone runs into trouble accessing the Pelican site from Russia in the future, please feel free to comment here.

**Comment by epogrebnyak** [comment]
Glad it is off the list, at least for now. @justinmayer - can you please look at another closed issue https://github.com/getpelican/pelican/issues/398 - maybe worth reopening. Keen to create a clean starting example for getpelican, at par with other static site generators.
