### ISSUE TITLE
pelican --listen cannot find index.html

### ISSUE THREAD

**Issue by tyleha** [getpelican/pelican#2626]
Having this problem both with brand new pelican projects and older ones of mine. Running the latest pelican at version 4.1.2. 

Steps to reproduce: Follow [quickstart](http://docs.getpelican.com/en/latest/quickstart.html) instructions to the letter including running `pelican content`. Then `cd output` and run `pelican --listen`. When I hit localhost:8000 with a browser, the generated error message is:

```
WARNING: Unable to find `` or variations:
  | .html
  | /index.html
  | /
  | 
```

However, there is an index.html file sitting right there in my cwd. This warning can be traced back to an error in https://github.com/getpelican/pelican/blob/master/pelican/server.py#L81. Note that `original_path` is undefined as shown in the log message between backticks.

What's going on here?

Note that simply running `python -m SimpleHTTPServer` works perfectly.

**Comment by avaris** [comment]
`--listen` reads out your settings and figures out the output folder. You *don't* `cd` into it. Run it from the same place you run `pelican`.

**Comment by tyleha** [comment]
Ah! Yes, that seems to work :grimacing:. However, this conflicts with the quickstart docs instructions which state:

> Open a new terminal session, *navigate to your generated output directory* and run the following command to launch Pelican’s web server: `pelican --listen`

Which is where I got the idea. I think the docs just need a quick tweak.

**Comment by avaris** [comment]
Ah, yes. "navigate" part should've been taken out when `pelican --listen` was introduced inplace of `python -m pelican.server` (which should still work by the way). PRs welcome :).

*PS*: We should probably switch [these](http://docs.getpelican.com/en/stable/publish.html#viewing-the-generated-files) to `--listen`, as well.

**Comment by justinmayer** [comment]
Sorry, Tyler — my fault. I obviously wasn't thinking clearly when I ["clarified"](https://github.com/getpelican/pelican/commit/2ab91bbaaa565dcb89726b6cac0002c1e0644dc3) that part of the documentation. 😓 

I fixed that, as well as switched to `pelican --listen` in the Publish docs as @avaris helpfully suggested, via 047d8843.

**Comment by tyleha** [comment]
Y'all the best, thanks for the quick fixes.
