### ISSUE TITLE
Some unit tests seem to be failing.

### ISSUE THREAD

**Issue by stuaxo** [getpelican/pelican#2631]
It looks like the unit tests are failing  https://travis-ci.org/getpelican/pelican/jobs/594828892

![image](https://user-images.githubusercontent.com/179677/66391914-4ad85a00-e9c6-11e9-8255-32c743909302.png)

![image](https://user-images.githubusercontent.com/179677/66391943-5e83c080-e9c6-11e9-8643-89b644a34763.png)

**Comment by stuaxo** [comment]
Trying to run `python setup.py test` locally I get some different failures :/   (can't paste them right now)

**Comment by avaris** [comment]
Well the above log is for a PR, that is not yet merged. [Here](https://travis-ci.org/getpelican/pelican/builds) is the history for master. If you share the errors you are getting locally we can figure out the issue.

**Comment by justinmayer** [comment]
All tests pass when I run [`python -Wd -m unittest discover`](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite) locally on current master.

**Comment by stuaxo** [comment]
Doh, good catch.

I wonder how easy it is to update `setup.py test` to run the tests in the same way.

**Comment by avaris** [comment]
`python -Wd setup.py test`?

**Comment by stuaxo** [comment]
Looks like I hadn't installed everything when running tests locally, and wasn't paying enough attention to the branch when I opened this, apologies for the noise :) !
