### ISSUE TITLE
Add Repology badge to README

### ISSUE THREAD

**Issue by luzpaz** [getpelican/pelican#2633]
### Summary
A way for users to see what downstream repositories carry pelican

### Proposed design
The compact badge looks like so:  
[![Packaging status](https://repology.org/badge/tiny-repos/pelican.svg)](https://repology.org/project/pelican/versions)

The full badge looks like so (but may be too "bulky"):  
[![Packaging status](https://repology.org/badge/vertical-allrepos/pelican.svg?header=pelican)](https://repology.org/project/pelican/versions)  

---------

**Note:** There is also a possibility to add the full badge in to its own section, like so:

```
### Packaging Status

<details>
  <summary>Expand to see the packaging status of pelican...</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/pelican.svg?header=pelican)](https://repology.org/project/pelican/versions)  

</details>
```

**Which gives us:**  

### Packaging Status

<details>
  <summary>Expand to see the packaging status of pelican...</summary

[![Packaging status](https://repology.org/badge/vertical-allrepos/pelican.svg?header=pelican)](https://repology.org/project/pelican/versions)  

</details>

**Comment by ivanhercaz** [comment]
@getpelican, any comment about it? It might be a good idea. I will use the compact badge to the right of the PyPI badge.

**Comment by luzpaz** [comment]
Bump?

**Comment by avaris** [comment]
I'm OK with the compact one.

**Comment by luzpaz** [comment]
Bump

**Comment by justinmayer** [comment]
Thanks to @luzpaz for the contribution and to @ivanhercaz and @avaris for reviewing.
