### ISSUE TITLE
docs.getpelican.com is down

### ISSUE THREAD

**Issue by Lucas-C** [getpelican/pelican#2637]
This seems to be a domain (or VHost) issue :

    $ host docs.getpelican.com
    Host docs.getpelican.com not found: 3(NXDOMAIN)

<https://getpelican.com> still redirect to <https://blog.getpelican.com> and seems OK

**Comment by Lucas-C** [comment]
By the way can someone confirm that they can connect to the IRC chat #pelican ?
It is mentioned [here](https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst#the-pelican-irc-channel) and [here](https://github.com/getpelican/pelican/wiki#getting-help).

I'm not very familiar with IRC and its registration process, so I'm not sure the message I sent on https://webchat.freenode.net/#pelican went through.

**Comment by Kristinita** [comment]
+1, see [**isup.me**](https://downforeveryoneorjustme.com/docs.getpelican.com).

Thanks.

**Comment by avaris** [comment]
You can still reach docs using `readthedocs`: https://pelican.readthedocs.io/en/stable/

Just leaving it here in case anybody needs.

**Comment by justinmayer** [comment]
Sorry about that, folks. I had to make some DNS changes yesterday and obviously forgot the documentation sub-domain. It’s fixed now. ✨
