### ISSUE TITLE
Generating plain text from reST (similar to sphinx TextBuilder)

### ISSUE THREAD

**Issue by 1oglop1** [getpelican/pelican#2639]
I'm trying to find out what is the best way to generate plaintext files from `rst` similar so I could use them to generate an index for `whoosh`.

I found out that Sphix has this feature built-in http://www.sphinx-doc.org/en/master/#sphinx.builders.text.TextBuilder

So I went thorough pelican docs and read about `Writers`, `Readers` and `Generators` but I could not find a way to get the structure of `rst` before generation of HTML.

It seems like I should create a custom `Reader` but I'm not sure how to do it properly.

**Comment by avaris** [comment]
I am not quite sure what you mean by "plain text" here.

Do you want the exact `rst` input? With all the `rst` syntax elements? `content.source_path` contains the corresponding file. You can just open and read it.
Or do you want (readable) text after parsing the `rst` file? Like the displayed text in an HTML file? Then doing [beautifulsoup4 `get_text()`](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#get-text) on the generated HTML content would be easiest.

**Comment by 1oglop1** [comment]
Yes, but I would like to avoid using `beautifulsoup`.
It doesn't seem necessary to use it. Or is docutils documentation overcomplicated and hidden behind the "old" wall of svn and sourceforge on purpose to use other tools instead of that?

**Comment by avaris** [comment]
docutils can be fiddly, for sure. If you want to go that route, I suppose you can "borrow" from Sphinx. [`TextWriter`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/text.py#L373) and [`TextTranslator`](https://github.com/sphinx-doc/sphinx/blob/master/sphinx/writers/text.py#L392) might be used similar to [how `pelican` converts it to HTML](https://github.com/getpelican/pelican/blob/master/pelican/readers.py#L185-L204).

**Comment by 1oglop1** [comment]
This is exactly what I'm trying to do, but I could not crack how sphix does it exactly.
And I cannot use it's classes directly because it requires to set up a Sphinx app instance. I'm hoping that I'd be able to find out what's the main functionality of sphix.Text* object and borrow just that. But so far it's quite difficut what's needed and what's not.

**Comment by 1oglop1** [comment]
I fell back to bs4 because I could not find the properly hook up the `document` object to the translator.
@avaris do you have any experience with that? I can share the code on Monday.
