### ISSUE TITLE
Fix Pytest-incompatible test

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#2650]
As far as I can tell, the only test that currently fails when running Pelican's test suite via `pytest` (5.2.2) is the `test_error_on_warning` test:

```
――――――――――――――――――――――――――――― TestSuiteTest.test_error_on_warning ―――――――――――――――――――――――――――――

self = <pelican.tests.test_testsuite.TestSuiteTest testMethod=test_error_on_warning>

    def test_error_on_warning(self):
        with self.assertRaises(UserWarning):
>           warnings.warn('test warning')
E           AssertionError: UserWarning not raised

pelican/tests/test_testsuite.py:13: AssertionError
```

Who would like to earn a gold star by making this test compatible with `pytest`? ✨

**Comment by avaris** [comment]
I'm not that much of a `pytest` user and I don't have my dev environment handy to test right now but according to [docs](https://docs.pytest.org/en/latest/warnings.html), putting a `pytest.ini` at project root with content as below *might* resolve it.

```ini
[pytest]
filterwarnings =
    error
```

**Comment by justinmayer** [comment]
That does indeed do the trick. I'll add a commit for this. Thanks! 👍

**Comment by justinmayer** [comment]
Thanks again for tracking that down, Deniz. For the moment, rather than adding yet another configuration file to the project, I added a commit containing the above stanza to our existing `tox.ini` file: https://github.com/getpelican/pelican/pull/2651/commits/e713407f898f964f927053ffa924edb9adbcc1bb

Feel free to comment in that PR with any suggested changes.
