### ISSUE TITLE
if i hava diferent pc whether should i

### ISSUE THREAD

**Issue by zerols** [getpelican/pelican#2652]

**Comment by zerols** [comment]
Is it possible to upload the entire folder to github for easy switching between different devices? The machine only needs to download and modify the push without having to start from scratch.

**Comment by justinmayer** [comment]
If by "folder" you are referring to your source content (settings file, Markdown/reST articles, etc.), than yes — committing that via Git is a common practice.

In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
