### ISSUE TITLE
Possible syntax error in tasks.py

### ISSUE THREAD

**Issue by sio** [getpelican/pelican#2655]
I was browsing `tasks.py` to get a sense of what `invoke` feels like and noticed a weird syntax for paths:

https://github.com/getpelican/pelican/blob/bae6de5d26646872fedbd00d37a849bba1837a3b/tasks.py#L16

Unless `invoke` does some hacky operator overloading for strings the last part of that statement seems to be syntactically invalid: Python would attempt division operation, which is not supported for strings.

Since that is a fallback value I assumed it might have gone unnoticed in initial test runs.

**Comment by avaris** [comment]
That's the built-in [`pathlib`](https://docs.python.org/3/library/pathlib.html) module.

**Comment by sio** [comment]
Oh, today I learned. Thank you :-)
