### ISSUE TITLE
test fail when run the PyPI tarball

### ISSUE THREAD

**Issue by sgn** [getpelican/pelican#2656]
I'm packaging pelican 4.2.0 by from PyPI tarball.

pytest fail because it doesn't have required files for testing.

> FileNotFoundError: [Errno 2] No such file or directory: '/builddir/pelican-4.2.0/pelican/tests/content/article_with_mdown_extension.mdown'

And some other error
> Ran 252 tests in 5.992s
>
> FAILED (failures=4, errors=8, skipped=6)
> Test failed: <unittest.runner.TextTestResult run=252 errors=8 failures=4>

**Comment by sgn** [comment]
Using github generated tarball, I only meet 2 errors.
- first one requires git, is it desirable?
- second one is about user warning

**Comment by justinmayer** [comment]
Hi Danh. In what ways is this *not* a duplicate of #2635 ?

**Comment by avaris** [comment]
> first one requires git, is it desirable?

Not sure about *desirable* but it is very convenient and robust to use `git diff` for comparing outputs.

> second one is about user warning

For 4.2 or below you need to use the [documented testing method](http://docs.getpelican.com/en/stable/contribute.html#running-the-test-suite). `pytest` needs some more nudging to fully work (see: #2650). Next release should be fine.

**Comment by sgn** [comment]
> Hi Danh. In what ways is this _not_ a duplicate of #2635 ?

Sorry for the noise, I forgot to check the issue list.

> > first one requires git, is it desirable?
> 
> Not sure about _desirable_ but it is very convenient and robust to use `git diff` for comparing outputs.

Doesn't pytest have something to diff already?
But pulling the whole stack of git for `git-diff` is _not_ so convenient.
I don't know about Windows but `cmp(1)` and `diff(1)` is both specified by POSIX.

**Comment by avaris** [comment]
I don't disagree. There is a soft assumption that if you're getting `pelican` from github, you have `git` already. Which is not necessarily true of course. Platform independent alternative would require time and effort, PRs are welcome :).
