### ISSUE TITLE
Custom Regenerate Conditions / Functionality

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [getpelican/pelican#2657]
I have a website I'm currently working on that uses a JSON file parsed and loaded into the configuration file  (`pelicanconf.py`) to store a load of data and provide an interface for artists / creatives to insert new data elements. It looks something like:

```
try:
    from . import custom_parser
except:
    sys.path.insert(0, str(Path().absolute()))
    import custom_parser

PROJECTS = custom_parser.get_projects()
```

Where `customparser.get_projects()` does the initial JSON parsing and then stores it into the `PROJECTS` variable.  I use this data when generating HTML pages using for loops / other pelican commands.

This works great with every individual `make` command, but doesn't work with `make regenerate` because any JSON file changes don't trigger a page regeneration. My assumption would be that it's a side effect of using a JSON file instead of a standard 'post' style syntax for something like a blog.

I'm not sure if it's possible, but it would be nice if this type of functionality was better supported by pelican. It would certainly help with data-heavy websites and cases where integration with other applications are expected. Ideally, you could actually create custom events so that specific changes cause a regeneration. For instance, changing a JSON file or even adding content to a README. 

Perhaps there's already a way to do this, and if so, let me know because it would definitely speed up my current workflow. :)

**Comment by avaris** [comment]
Yes, right now you can't watch arbitrary files for `autoreload`. Current watchers are 
* "readable" files in `content`, i.e. `.md`, `.rst` etc
* `theme` folder
* your settings file, but only that single file. Can't really resolve everything you do in that setting file (imports, external file reads etc)
* anything defined in `STATIC_PATHS`

So... as a (ugly) workaround, you can put your `.json` file somewhere in `STATIC_PATHS` and it will be watched. But it will be copied to the output as well. Up to you whether or not that's a workable compromise.

For a solution, a setting could be added for listing specific files/folders to "watch" in addition to the standard ones in `autoreload` mode. PRs welcome :).

**Comment by Eoin-ONeill-Yokai** [comment]
Cool, I might poke around for a solution if I get some time. It would be pretty useful in general to support JSON parsing since a lot can be done (especially regarding product pages, WYSIWYG editors and the like.)

**Comment by justinmayer** [comment]
@Eoin-ONeill-Yokai: I don't know whether it would work for your use case, but you might look at the [Invoke tasks template](https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/tasks.py.jinja2#L102-L106) that is optionally generated by `pelican-quickstart`. Having added other file extensions to the template in the past, I wonder whether you could add JSON files to that function in order to trigger builds on JSON file modification.

**Comment by Eoin-ONeill-Yokai** [comment]
@justinmayer That might actually be useful, thanks for the heads up!

**Comment by justinmayer** [comment]
Unless there's evidence that the aforementioned LiveReload task can't be used for this purpose, I'll assume that it indeed can be, and thus this need has been addressed.
