### ISSUE TITLE
CRITICAL: AttributeError: 'str' object has no attribute 'slug'

### ISSUE THREAD

**Issue by GerBreOwn** [getpelican/pelican#2663]
I have been using Pelican for several months with NO problems.  Yesterday I upgraded the Elegant theme and started getting the following error: **CRITICAL: AttributeError: 'str' object has no attribute 'slug'**
I followed all of the suggestions at "https://github.com/getpelican/pelican/issues/1742" about deleting the cache but still get the error using "pelican content" or "make html"
The Elegant technician suggested that I had my pelicanconf.py file misconfigured.  No where in that file do I have the word "slug".
Are there any other suggestions to solve this problem as I am now dead in the water and can't make any changes to my blog which worked fine on 12/12/19.  I thought it might have something to do with **Friday the 13th** but still on the 14 the problem persists!!!
I also tried several other themes with same problem so it was not connected to the Elegant theme.

**Comment by justinmayer** [comment]
@GerBreOwn: If you review the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, follow the steps listed there, and post the relevant information here, we'd be better equipped to help you.

**Comment by mr-chrome** [comment]
Maybe you don't have interest in this anymore, but maybe you tried to manipulate metadata with a plugin? I can see that trying to push a string as category metadata gives this weird error response.

**Comment by richardgourley** [comment]
Very late to the conversation, but this might help someone:

I received the above error when creating articles programmatically inside a plugin. 

The error 'CRITICAL: AttributeError: 'str' object has no attribute 'slug' appears when you add a string directly to the mandatory category field (and other fields).

You have to make sure all data is passed through the **baseReader.process_metadata** function.

WRONG: "category": a_python_dict['category']
CORRECT: "category": baseReader.process_metadata("category", a_python_dict['category'])
