### ISSUE TITLE
Markdown including other files

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican#2669]
Currently it seems this requires a 3rd party extension (plugin):

https://github.com/neurobin/mdx_include

is this still the case? Other projects have this built in:

https://gohugo.io/functions/readfile

**Comment by avaris** [comment]
Yes, that's delegated to extensions. We tend to avoid code duplication.

Related: #2628

**Comment by cup** [comment]
I will close this for now. I am going to give reStructuredText a try

https://docs.getpelican.com/en/stable/content.html#including-other-files
