### ISSUE TITLE
listen: print server address

### ISSUE THREAD

**Issue by cup** [getpelican/pelican#2671]
When you do this:

~~~
pelican --autoreload --listen
~~~

You get this output:

~~~
-> Modified: content, theme, settings. re-generating...
Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages
in 0.14 seconds.
~~~

I think Pelican should tell you where the site is. Granted its listed here:

https://docs.getpelican.com/en/stable/quickstart.html

but it would be helpful.

**Comment by justinmayer** [comment]
@cup: Seems like a reasonable suggestion. Would you be willing to submit a pull request that adds that information to the output?

**Comment by cup** [comment]
@justinmayer I closed this as I discovered a more important issue - I didnt want to spam so I will wait until the other issue has been addressed

thanks

**Comment by cup** [comment]
Workaround:

~~~
$ pelican --listen --verbose
-> Serving at port 8000, server 127.0.0.1.
~~~
