### ISSUE TITLE
Is there a way to make content compatible with Firefox's Reader View?

### ISSUE THREAD

**Issue by godofgrunts** [getpelican/pelican#2672]
I've started messing around with Pelican, but I'd really like my site to be compatible with Firefox's Reader View.

There doesn't seem to be any great documentation that I can find so I'm not 100% sure what I need to do.

**Comment by justinmayer** [comment]
I empathize with what you're trying to achieve, but you haven't provided much information to go by. What theme are you using? Can you provide an exact URL that points to an article on your site that does not cause the _Toggle reader view_ button to appear?

That said, this topic is quite far beyond Pelican's bailiwick. Firefox looks at HTML content and uses a scoring system to determine whether to display the _Toggle reader view_ button. The HTML that is generated is dependent on what **theme** is being used, and therefore this topic isn't related to Pelican itself.

Underscoring that point, following are two example articles generated by Pelican that properly display the _Toggle reader view_ button in Firefox:
* https://justinmayer.com/posts/multi-factor-authentication-phone-sms/
* https://blog.getpelican.com/pelican-4.1-released.html

Related reading: https://support.mozilla.org/en-US/questions/1140969

In the future, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation.

**Comment by godofgrunts** [comment]
Oh. I appreciate the response and I apologize for using the wrong avenue for requesting help. I'll close the issue.

Thank you!
