### ISSUE TITLE
KeyboardInterrupt

### ISSUE THREAD

**Issue by cup** [getpelican/pelican#2676]
If you run:

~~~
pelican --listen
~~~

Pelican does not tell you how to stop. Compare with other projects:

~~~
Press Ctrl+C to stop
~~~

I assume that Pelican accepts the same key, but this is produced:

~~~
Traceback (most recent call last):
  File "/usr/bin/pelican", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 559, in main
    settings.get("OUTPUT_PATH"))
  File "/usr/lib/python3.6/site-packages/pelican/__init__.py", line 495, in listen
    httpd.serve_forever()
  File "/usr/lib/python3.6/socketserver.py", line 236, in serve_forever
    ready = selector.select(poll_interval)
  File "/usr/lib/python3.6/selectors.py", line 376, in select
    fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
~~~

**Comment by cup** [comment]
Here is fix:

~~~diff
diff --git a/pelican/__init__.py b/pelican/__init__.py
index 17f4f92..d3889b2 100644
--- a/pelican/__init__.py
+++ b/pelican/__init__.py
@@ -474,6 +474,9 @@ def listen(server, port, output, excqueue=None):
             excqueue.put(traceback.format_exception_only(type(e), e)[-1])
         return

+    except KeyboardInterrupt:
+        logger.info("Shutting down server.")
+        httpd.socket.close()

 def main(argv=None):
     args = parse_arguments(argv)
~~~

Copied from here:

https://github.com/getpelican/pelican/blob/70c8d2a47431cc5de29b08a830d1af4f8e6f6e30/pelican/server.py#L138-L140

**Comment by cup** [comment]
at any rate, I built my own server until a new Pelican build is available:

https://github.com/cup/suede/blob/master/go/serve.go

**Comment by iKevinY** [comment]
Hi @cup, thanks for the bug report! I agree that it would be more user-friendly to have a nice error message instead of just the raw `KeyboardInterrupt` event. If you submit a pull request, I think the @getpelican team would be happy to merge it.

**Comment by cup** [comment]
https://github.com/getpelican/pelican/pull/2683

**Comment by cup** [comment]
@iKevinY ?
