### ISSUE TITLE
Add metadata to author before rendering an article

### ISSUE THREAD

**Issue by johanvergeer** [getpelican/pelican#2679]
I'm working on a plugin to add metadata to an author. With this plugin authors can create a markdown file, with some metadata and a description. 

```python3
import logging
import os
from os.path import exists

import markdown
from pelican import signals
from pelican.generators import Generator
from pelican.urlwrappers import Author

logger = logging.getLogger(__name__)


def add_metadata(author: Author, generator: Generator):
    authors_dir = generator.settings["AUTHORS_PATH"]
    author_file_path = os.path.join(authors_dir, f"{author.slug}.md")

    if not exists(author_file_path):
        logger.warning(f"No author file found for {author} in {authors_dir} directory")
        return

    md = markdown.Markdown(extensions=['meta'])

    with open(author_file_path, 'r') as f:
        author_file = md.convert(f.read())

    setattr(author, 'description', author_file)
    for name, value in md.Meta.items():
        setattr(author, name, value[0])


def add_author_metadata(generator: Generator):
    for article in generator.articles:
        for author in article.authors:
            add_metadata(author, generator)
    for author, _ in generator.authors:
        add_metadata(author, generator)


def register():
    signals.article_generator_finalized.connect(add_author_metadata)
```

The markdown file would look like this, but you can put any metadata you want in there.

```markdown
---
name: Johan Vergeer
github: https://github.com/johanvergeer
job_description: Software Engineer
---

Something about me
```

The values do show up on the author page, but they do not show up on an article page. I have tried several [signals ](https://docs.getpelican.com/en/stable/plugins.html#list-of-signals) but I can't get this to work.

What do I have to do to set the values on the author so they are available in the article?

**Comment by mosra** [comment]
I already have such a plugin, feel free to use anything from it: https://mcss.mosra.cz/plugins/metadata/

**Comment by avaris** [comment]
Code looks fine to me. What exactly is in the `article` template and what is the html output of relevant bits?

**Comment by johanvergeer** [comment]
@avaris The information didn't show up because the post status was `draft`. Once I changed that to `published` the information showed. Do you know if it's possible to show it also on `draft` pages?

**Comment by johanvergeer** [comment]
@mosra I looked at your plugin and it looks pretty cool. 

I do have two questions:

1. Does it support Markdown?
1. Do you have a pip package?

**Comment by avaris** [comment]
@johanvergeer sure. You only loop through published ones. Go through the others as well and it will show up:
https://github.com/getpelican/pelican/blob/70c8d2a47431cc5de29b08a830d1af4f8e6f6e30/pelican/generators.py#L643-L644

**Comment by johanvergeer** [comment]
That was easy:

```python3
def add_author_metadata(generator: Generator):
    for article in generator.articles:
        for author in article.authors:
            add_metadata(author, generator)
    for draft in generator.drafts:
        for author in draft.authors:
            add_metadata(author, generator)
    for author, _ in generator.authors:
        add_metadata(author, generator)
```

Thanks for your help
