### ISSUE TITLE
Create pelican create-article cli plugin

### ISSUE THREAD

**Issue by johanvergeer** [getpelican/pelican#2681]
Is it possible to create a plugin that can add a command to the `pelican` cli. 

I would like to create a plugin to create articles. I have the following in mind:

```sh
$ pelican create-article
title: <enter article name>
category: <enter article category>
article tags: <enter article tags>
... questions for other meta ...
```
I'm also planning on showing a list of current tags and categories, and showing a warning when the given tag or category does not exist yet. (To prevent typo's).

**Comment by jorgesumle** [comment]
You can use simple Bash commands to achive what you want (see 
["make newpost" from wiki](https://github.com/getpelican/pelican/wiki/Tips-n-Tricks#make-newpost)). Personally, I use [custom Vim UltiSnips snippets](https://notabug.org/jorgesumle/.vim/src/master/UltiSnips/markdown.snippets). 

> I'm also planning on showing a list of current tags and categories, and showing a warning when the given tag or category does not exist yet.

That sounds nice, but you need a database or something to store the used categories and tags, I guess.

**Comment by johanvergeer** [comment]
> That sounds nice, but you need a database or something to store the used categories and tags, I guess.

I also thought about that, but I figured users can always just add tags or change categories manually, so than I wonder how to keep it up-to-date. For now I will just look into the current posts and get the info from there.

**Comment by mirekdlugosz** [comment]
I don't think you can create plugin providing it's own command line option. Arguments parser is created in [single function](https://github.com/getpelican/pelican/blob/master/pelican/__init__.py#L234) and parsed object is returned. There are no signals there that you could hook into.

Facing the same problem, I've created GUI app [pelican-metadata-generator](https://github.com/mirekdlugosz/pelican-metadata-generator/). Maybe you will find it useful for now. Major drawback of external app approach is that I needed to implement all files parsers on my own, i.e. I can't use pelican plugins that add readers for new file types. I've always wanted it to be more integrated with Pelican, but I've never get around to actually do that.

**Comment by johanvergeer** [comment]
@mirekdlugosz That is too bad, but not something to stop me from creating this plug-in. It will be a stand-alone cli tool in this case.

Maybe something to keep in mind for Pelican 5?
