### ISSUE TITLE
Theme install instruction

### ISSUE THREAD

**Issue by ghost** [getpelican/pelican#2686]
With Hugo, exact instructions are given how to install a theme:

~~~sh
git init
git submodule add git://github.com/budparr/gohugo-theme-ananke themes/ananke
echo 'theme = "ananke"' >> config.toml
~~~

https://gohugo.io/getting-started/quick-start#step-3-add-a-theme

However Pelican doesnt seem to offer this same instruction. I see this:

https://docs.getpelican.com/en/stable/settings.html#themes

but it doesnt tell you how to install a theme, only what settings are available
for themes. That section does have a link for this tool:

https://docs.getpelican.com/en/stable/pelican-themes.html

but its again confusing, as even if you "install" a theme, its not actually
installed in your website folder, but in some system folder:

~~~sh
$ pelican-themes --install ../pelican-hyde-master --verbose
Installing themes...
Copying '../pelican-hyde-master' to
'/usr/lib/python3.6/site-packages/pelican/themes/pelican-hyde-master' ...
~~~

I would suspect that many people dont want this, as they would want the theme
installed locally to allow them to customize it. Finally on the settings page
I see this:

https://docs.getpelican.com/en/stable/themes.html

but again it doesnt actually tell you what to do with the files youve created.

**Comment by cup** [comment]
Here is a similar instruction for Pelican:

~~~sh
git init
git submodule add git://github.com/jvanz/pelican-hyde
echo 'THEME = "pelican-hyde"' >> pelicanconf.py
~~~

Or:

~~~sh
git clone git://github.com/jvanz/pelican-hyde /tmp/pelican-hyde
mv /tmp/pelican-hyde/static .
mv /tmp/pelican-hyde/templates .
echo 'THEME = "."' >> pelicanconf.py
~~~

**Comment by avaris** [comment]
Because you don't need to install a theme. In fact it's better you don't install it for customization (i.e. avoid `pelican-themes`). `THEME` setting can be a location to a folder. It doesn't even need to reside in the "source" folder.

**Comment by cup** [comment]
> Because you don't need to install a theme.

Yes you do. Else Pelican uses the default theme. Do you expect every single user
to use the default theme with no modification?

> In fact it's better you don't install it for customization (i.e. avoid
> pelican-themes).

To customize a theme, a theme must first be installed.

> THEME setting can be a location to a folder. It doesn't even need to reside in
> the "source" folder.

The question is given a path like `pelican-hyde/templates` or `pelican-hyde`,
how do you install it. Answering that would involve both clarifying where the
folders would need to go in both cases, as well as any settings that might need
to be changed.

**Comment by avaris** [comment]
Perhaps we have a different definition of "install". When I say install, I mean acquiring the theme. It doesn't matter how you get it, as long as you end up with a folder containing the required bits. e.g.:

- `git clone`
- download a zip file and extract
- copy from USB drive
- develop locally
- etc

After that you don't need to do anything special to use it. You don't need to run a command or place it in a special place. Using it in a project is as simple as providing the folder to the theme in `THEME` setting:
```
THEME = '/path/to/pelican-hyde'
```
