### ISSUE TITLE
SameFileError when path outside `content` is used to load static files

### ISSUE THREAD

**Issue by johanvergeer** [getpelican/pelican#2690]
I try to load static files from the theme using `STATIC_PATHS`, but I get a `SameFileError` when the server starts.

# Project structure

```
myblog
|_ content
|  |_ ...
|  |_ img
|  |  |_ img1.jpg
|  |  |_ ...
|  |_ ...
|_ themes
   |_ mytheme
      |_ static
        |_ img
           |_ ...
           |_ img2.jpg
```

# pelicanconf.py

```python
from pathlib import Path

...

PROJECT_ROOT = Path().absolute()

STATIC_PATHS = [
    PROJECT_ROOT / "themes" / "mytheme" / "static" / "img",
    PROJECT_ROOT / "img"
]

...
```

Now when I run the application I get the following output:

```shell
...
WARNING: A problem occurred copying file /Users/me/myblog/img/img2.jpg to /Users/me/myblog/img/img2.jpg; SameFileError: '/Users/me/myblog/img/img2.jpg and /Users/me/myblog/img/img2.jpg are the same file
...
```

The goal is to copy files to output that are used in css files.

How can I accomplish this?

**Comment by avaris** [comment]
You don't need the `static` path from your theme in `STATIC_PATHS`, `pelican` already copies that. Possibly the reason it tries to copy same file twice and errors.

PS: Configurable with [`THEME_STATIC_PATHS`](https://docs.getpelican.com/en/stable/settings.html#themes) if needed

**Comment by justinmayer** [comment]
Thanks for the guidance, @avaris. Closing as the question seems to have been resolved.
