### ISSUE TITLE
Use language name instead of language code in UI

### ISSUE THREAD

**Issue by jean** [getpelican/pelican#2691]
Currently Pelican displays e.g. 

> This post is also available in: th

That isn't very user-friendly. Is there by any chance an API handy to get e.g.

> This post is also available in: ไทย

?

**Comment by avaris** [comment]
Not that I know of. But you can place a dictionary in your settings for the used languages, like:
```python
LANGUAGE_CODES = {
    'en': 'English',
    ...
}
```
and in the template, instead of
```jinja
{{ article.lang }}
```
do this:
```jinja
{{ LANGUAGE_CODES[article.lang] }}
```

**Comment by jean** [comment]
Ah, thanks @avaris , that will do fine for now :-)
I'll leave this issue open though.

**Comment by justinmayer** [comment]
Hi Jean. Is this a feature you want to work on implementing?

**Comment by jean** [comment]
@justinmayer I'd love to, but no idea when I'll have the time to dig into it properly.

**Comment by shmcgrath** [comment]
@justinmayer Is this something that should be in Pelican itself or in a plugin?

**Comment by avaris** [comment]
Probably, it is not very feasible to keep a language code database in `pelican` itself. A plugin would be better. Just keep in mind that `article.lang` is used in other places (`i18n_subsites` plugin comes to mind), so replacing the code with language might not be the best idea. It's probably better to add a new attribute (`article.language`) and adjust themes accordingly.

**Comment by justinmayer** [comment]
Hi @shmcgrath. Would you be interested in working on a plugin that implements this feature? If so, let me know and I will create a separate repository for it under the new [Pelican Plugins](https://getpelican.com/pelican-plugins) organization.

**Comment by justinmayer** [comment]
If anyone would like to work on this, please feel free to comment here so we can re-open the issue.
