### ISSUE TITLE
Separate output directories: js, css, images, media, fonts

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2692]
When tightening the Content-Security-Protection in the HTTP header, I had to break out the 'theme' OUTPUT directory into the following separate subdirectories:

```
   /blog
    +-- js
    +-- media
    +-- css
    +-- images
    +-- fonts
    +-- feeds
```
It would appear to me that there is nothing that can allow me to perform split copying from the Pelican theme into its respective OUTPUT sub-directories.

Please advise.

The HTTP Content-Security-Policy header of my web server is currently set for:
```
default-src https://example.com/; 
base-uri 'none'; 
script-src https://example.com/js/ 'strict-dynamic'; 
object-src 'none';
style-src 'self' 'unsafe-inline' https://example.com/css/; 
img-src https://example.com/favicon.ico https://example.com/images/ data:; 
media-src https://example.com/media/ data:; 
frame-src https://example.com/frames/; 
frame-ancestors 'none'; 
worker-src 'self'; 
child-src 'self'; 
font-src https://example.com/fonts/;
connect-src 'self' https://example.com/; 
form-action 'none'; 
sandbox; 
report-uri https://ssoseo1.report-uri.com/r/d/csp/enforce; 
report-to endpoint-1; upgrade-insecure-requests; 
block-all-mixed-content;";
```
Using Pelican 4.2.0, Python 3.7.2, and @mosra's m.css template

**Comment by avaris** [comment]
I did not try it but brief glance at the code suggests setting:
```
THEME_STATIC_DIR = ''
```
should do that ([doc](https://docs.getpelican.com/en/stable/settings.html#themes))

**Comment by egberts** [comment]
That's what I saw.  It only allows for a singular (one) output directory.

**Comment by avaris** [comment]
I'm not sure what you mean by one directory, but I just tested. With a theme structure like this:
```
mytheme
├── static
│   ├── css
│   ├── fonts
│   └── images
│       └── icons
└── templates
```
Normally you'd get this:
```
output/
├── feeds
└── theme
    ├── css
    ├── fonts
    └── images
        └── icons
```
but after setting `THEME_STATIC_DIR = ''`, I end up with this:
```
output/
├── css
├── feeds
├── fonts
└── images
    └── icons
```

**Comment by egberts** [comment]
Not much control between input and output mapping; it's nearly 1:1 mapping.

In order to fit into someone else's directory layout, I must change the subdirectories in `content/theme`  to reflect this.

**Comment by avaris** [comment]
I don't think I understand your use case then. Do you want to put all files into a single `theme/static` folder in the output and want to split those into separate folders based on `js`, `css`, ... etc?

**Comment by egberts** [comment]
If I assume that Pelican can only output the same directory structure as its input (theme), then it would force me to alter an existing theme to properly reflect the more subdirectories approach.  Correct?

**Comment by avaris** [comment]
Currently it's like that, correct. And, that is sort of required. Theme needs to know in advance where the files will be in output, because they are referred in templates. So, in a way, static folder structure is part of "theme design" process.
