### ISSUE TITLE
asciidoc code blocks contain interspersed empty lines

### ISSUE THREAD

**Issue by traits** [getpelican/pelican#2694]
System: Win10, Pelican 4.2.0

This seems not to be a plugin error.  All rows inside code blocks generated from asciidoc sources utilizing the maintained asciidoc_reader plugin contain an additional CR (no linefeed!) after every single row in the generated html output. This leads to redundant empty lines between these rows while rendering. The html output shows the spurious `0D` also between other parts of the same html files (not affecting rendering there). An independent explicit command line call `asciidoctor -s source.adoc` produces the correct result.

**Comment by justinmayer** [comment]
Hi Michael. Given that Asciidoc support takes the form of a plugin and isn't built into Pelican, why do you suspect the fault lies with Pelican core and not the Asciidoc-related Pelican plugin?

**Comment by traits** [comment]
Hi Justin

I have since removed asciidoc from my workflow, because of this. AFAIR (I debugged the plugin at that time), the following line returned correct results: 

https://github.com/getpelican/pelican-plugins/blob/666716e1f678f0d7f2ed020ad239fabb3a3c6a49/asciidoc_reader/asciidoc_reader.py#L53

This indicated to me, that the suspicious transformation happens after calling the plugins `read` at some point in the general framework.  Hence my assumption, that it is not a plugin problem.

**Comment by traits** [comment]
> 
> 
> Only suspicious thing touching content HTML from `pelican` side would be `typogrify` and that doesn't really fit the problem description. Could another plugin be doing this?

To answer that, I would have to understand more of Pelican's overall architecture.

At least,  I have re-added the current asciidoc plugin to my project and checked again. Same result. I haven't yet the smallest possible example reproducing the effect, but I think its close enough.

I will attach the example source (`features.adoc`) and two processed files `21-asciidoc-example.html` and `a.html`. The first one is the result of pelican+plugin, the second of a a direct call "`asciidoctor features.adoc -o a.html`" from the installed ruby gem (also called by the plugin). With any editor able to show line ending characters properly, single additional CR characters are found in the first variant (not from the beginning, and also ending at some `</div>` just before the closing `</article>` tag in the created html output). In contrast, the output of the direct asciidoctor call contains only CRLF sequences as line-endings.

[attachments.zip](https://github.com/getpelican/pelican/files/4441049/attachments.zip)

**Comment by avaris** [comment]
Aha... You said you checked the output of the line below but something is up with that line:
https://github.com/getpelican/pelican-plugins/blob/666716e1f678f0d7f2ed020ad239fabb3a3c6a49/asciidoc_reader/asciidoc_reader.py#L53

I checked with `asciidoc` (not `asciidoctor`! I had no desire to install `ruby`) but, the output of `-o -` (output to stdout) and `-o file` is very different, at least on windows. In `-o -` mode, line endings are `\r\r\n` for some reason (one more `\r` than required), as opposed to `\r\n` for file:
```
In [48]: sp.Popen('py -2.7 asciidoc-8.6.9/asciidoc.py --no-header-footer -o - features.adoc', stdout=sp.PIPE, stderr=sp.PIPE, shell=True).communicate()[0].decode('utf-8')
Out[48]: '<div class="sect1">\r\r\n<h2 id="_code">Code</h2>\r\r\n<div class="sectionbody">\r\r\n<div class="paragraph"><p>Issue: Code inclusion adds redundant empty lines between rows</p></div>\r\r\n<div class="sect2">\r\r\n<h3 id="_code_block">Code block</h3>\r\r\n<div class="literalblock">\r\r\n<div class="content">\r\r\n<pre><code>from torch.utils.data import TensorDataset\r\r\nfrom torch import Tensor, LongTensor, FloatTensor\r\r\n\r\r\n\r\r\ndef loadData(path) -&gt; Tuple[np.ndarray, np.ndarray]:\r\r\n
   \'\'\'\r\r\n    Load data from kaggle mnist set.\r\r\n    \'\'\'\r\r\n    # Read\r\r\n    df = pd.read_csv(str(path))  # 40.000 entries\r\r\n    # tdata = pd.read_csv(data_raw_dir + sep + \'train.csv\') # 28.000 entries\r\r\n\r\r\n    has_labels = True if \'label\' in df.columns else False</code></pre>\r\r\n</div></div>\r\r\n<div class="paragraph"><p>Some <code>inline code</code>.</p></div>\r\r\n</div>\r\r\n</div>\r\r\n</div>\r\r\n'
```

Now, the `\r\n` is actually the newline setting for `asciidoc` and can be customized with `-a "newline=\n"`. I'm still not sure where the extra `\r` comes from but it's not there if you output to a file.

**Comment by traits** [comment]
In the meantime I did some digging by inserting test code at [the suspicious location](https://github.com/getpelican/pelican-plugins/blob/666716e1f678f0d7f2ed020ad239fabb3a3c6a49/asciidoc_reader/asciidoc_reader.py#L53) :

```
            content = call("%s %s -o - %s" % (cmd, options, source_path))
            with open('adoc-bin.html', 'wb') as f:                # correct: CRLF
                f.write(str.encode(content)) 
            with open('adoc-txt.html', 'w') as f:                 # incorrect: CRCRLF
                f.write(content) 
            with open('adoc-txt2.html', 'w', newline='') as f:    # correct: CRLF
                f.write(content) 
```
Explanations are  [here](https://stackoverflow.com/questions/43528959/python-3-how-to-pass-binary-file-as-text-without-saving-first) and [here](https://stackoverflow.com/questions/4025760/python-file-write-creating-extra-carriage-return). Or, from the [Python documentation](https://docs.python.org/3/library/functions.html#open):

> When writing output to the stream, if newline is None, any '\n' characters written are translated to the system default line separator, os.linesep. If newline is '' or '\n', no translation takes place. If newline is any of the other legal values, any '\n' characters written are translated to the given string.

os.linesep is CRLF on Windows, so it will replace for `newline=None` any LF in the CRLF sequences, returned from the asciidoc plugin, leading to the erroneous form.

I couldn't find any usage of the 'newline' parameter for file.open() in pelican core, but it provides opened text files without utilizing the parameter [here](https://github.com/getpelican/pelican/blob/a9a651ce4d58f8fe6119e43a9a8383a1ea7b240f/pelican/writers.py#L116). I have a feeling, this is also used for serializing the strings, returned by the conversion plugins.

**Comment by avaris** [comment]
Python built-in `open` is actually `io.open`, which is defined [here](https://github.com/python/cpython/blob/3.8/Lib/_pyio.py).

**Comment by avaris** [comment]
OK, what you write above suggests that the line endings are `\r\n` from the output of `asciidoctor` *. That's still a problem. So, yes, `pelican` behaves under the assumption that python uses universal newlines mode, i.e. any text inside uses `\n` for newline. That's true for all built-in parsers: Markdown or reStructuredText parsers returns text with `\n` in windows, not `\r\n`. So, messing with the file writing newline will cause other issues. It's kind of the responsibility of readers to ensure this.

* That might be the side effect of reading stdout in binary mode via subprocess.

**Comment by traits** [comment]
I don't think I agree here. I have not much skin in the game, as an user I simply need a working overall system. But as a software developer it is different.

IMO, there is no asciidoctor problem. It simply returns his results in a platform sensible way. So the consumer - pelican - is responsible for adjusting this result transparently to his own needs. Even if asciidoctor would be able to configure his line endings , a platform-specific pelicanconf.py would be the result. 

By the way

> Now, the \r\n is actually the newline setting for asciidoc and can be customized with -a "newline=\n"

I couldn't find anything like this mentioned in asciidoc or docbook documentation and the switch has no effect at all, it is silently ignored.

> ** That might be the side effect of reading stdout in binary mode via subprocess.

This is consistent, on the Windows command line the results of `asciidoctor features.adoc -o adoc.html` and `asciidoctor features.adoc -o - > adoc-redir.html` is nearly identical (up to an additional empty line at the end of the whole output for the redirected variant).

But this is a side track. As I said above, IMO pelican should respect the plugins output as-is and do the necessary adjustments itself. Otherwise it has to require these things in its policies for plugin developers in general.

**Comment by avaris** [comment]
I agree with you, partially :).

> I couldn't find anything like this mentioned in asciidoc, asciidoctor or docbook documentation and the switch has no effect at all, it is silently ignored. So, there is no setting lever for the pelican user.

That was from [here](http://asciidoc.org/userguide.html#_miscellaneous_section). That setting might or might not be relevant for `asciidoctor`, but it does have an affect on `asciidoc`.

> This is consistent, on the Windows command line the results of asciidoctor features.adoc -o adoc.html and asciidoctor features.adoc -o - > adoc-redir.html is nearly identical (up to an additional empty line at the end of the whole output for the redirected variant). An why not, this is a valid Windows text stream, line endings and all.

I can't speak for `asciidoctor` but, those two are not identical for me in `asciidoc`. Also note the change to "`\n` only newlines" when you *read* the file in python3 in default mode. File still contains `\r\n`.
```
In [12]: sp.Popen('py -2.7 asciidoc-8.6.9/asciidoc.py --no-header-footer -o - features.adoc', stdout=sp.PIPE, stderr=sp.PIPE, shell=True).communicate()[0].decode('utf-8')
    ...:
Out[12]: '<div class="sect1">\r\r\n<h2 id="_code">Code</h2>\r\r\n<div class="sectionbody">\r\r\n<div class="paragraph"><p>Issue: Code inclusion adds redundant empty lines between rows</p></div>\r\r\n<div class="sect2">\r\r\n<h3 id="_code_block">Code block</h3>\r\r\n<div class="literalblock">\r\r\n<div class="content">\r\r\n<pre><code>from torch.utils.data import TensorDataset\r\r\nfrom torch import Tensor, LongTensor, FloatTensor\r\r\n\r\r\n\r\r\ndef loadData(path) -&gt; Tuple[np.ndarray, np.ndarray]:\r\r\n
   \'\'\'\r\r\n    Load data from kaggle mnist set.\r\r\n    \'\'\'\r\r\n    # Read\r\r\n    df = pd.read_csv(str(path))  # 40.000 entries\r\r\n    # tdata = pd.read_csv(data_raw_dir + sep + \'train.csv\') # 28.000 entries\r\r\n\r\r\n    has_labels = True if \'label\' in df.columns else False</code></pre>\r\r\n</div></div>\r\r\n<div class="paragraph"><p>Some <code>inline code</code>.</p></div>\r\r\n</div>\r\r\n</div>\r\r\n</div>\r\r\n'

In [13]: sp.Popen('py -2.7 asciidoc-8.6.9/asciidoc.py --no-header-footer -o - features.adoc > test.txt', stdout=sp.PIPE, stderr=sp.PIPE, shell=True).communicate()[0].deco
    ...: de('utf-8')
Out[13]: ''

In [14]: open('test.txt').read()
Out[14]: '<div class="sect1">\n\n<h2 id="_code">Code</h2>\n\n<div class="sectionbody">\n\n<div class="paragraph"><p>Issue: Code inclusion adds redundant empty lines between rows</p></div>\n\n<div class="sect2">\n\n<h3 id="_code_block">Code block</h3>\n\n<div class="literalblock">\n\n<div class="content">\n\n<pre><code>from torch.utils.data import TensorDataset\n\nfrom torch import Tensor, LongTensor, FloatTensor\n\n\n\n\n\ndef loadData(path) -&gt; Tuple[np.ndarray, np.ndarray]:\n\n    \'\'\'\n\n    Load data from kaggle mnist set.\n\n    \'\'\'\n\n    # Read\n\n    df = pd.read_csv(str(path))  # 40.000 entries\n\n    # tdata = pd.read_csv(data_raw_dir + sep + \'train.csv\') # 28.000 entries\n\n\n\n    has_labels = True if \'label\' in df.columns else False</code></pre>\n\n</div></div>\n\n<div class="paragraph"><p>Some <code>inline code</code>.</p></div>\n\n</div>\n\n</div>\n\n</div>\n\n'

In [15]: sp.Popen('py -2.7 asciidoc-8.6.9/asciidoc.py --no-header-footer -o test2.txt features.adoc', stdout=sp.PIPE, stderr=sp.PIPE, shell=True).communicate()[0].decode(
    ...: 'utf-8')
Out[15]: ''

In [16]: open('test2.txt').read()
Out[16]: '<div class="sect1">\n<h2 id="_code">Code</h2>\n<div class="sectionbody">\n<div class="paragraph"><p>Issue: Code inclusion adds redundant empty lines between rows</p></div>\n<div class="sect2">\n<h3 id="_code_block">Code block</h3>\n<div class="literalblock">\n<div class="content">\n<pre><code>from torch.utils.data import TensorDataset\nfrom torch import Tensor, LongTensor, FloatTensor\n\n\ndef loadData(path) -&gt; Tuple[np.ndarray, np.ndarray]:\n    \'\'\'\n    Load data from kaggle mnist set.\n
 \'\'\'\n    # Read\n    df = pd.read_csv(str(path))  # 40.000 entries\n    # tdata = pd.read_csv(data_raw_dir + sep + \'train.csv\') # 28.000 entries\n\n    has_labels = True if \'label\' in df.columns else False</code></pre>\n</div></div>\n<div class="paragraph"><p>Some <code>inline code</code>.</p></div>\n</div>\n</div>\n</div>\n'
```

> But this is a side track. As I said above, IMO pelican should respect the plugins output as-is and do the necessary adjustments itself. Otherwise it has to require these things explicitly in its policies for plugin developers in general.

Well, that is an implicit requirement coming from "general python good practices". Ever since python made "universal newlines" mode default in python3, it's saying that best way to deal with these platform specific issues is to have consistent representation of text inside python. So anything dealing with IO has to handle that before passing the text string across. For this case, that responsibility is with the plugin.

**Comment by traits** [comment]
> For this case, that responsibility is with the plugin.

Meanwhile I also tend to this variant. But because the plugin allows for both asciidoc incarnations - asciidoc and asciidoctor - advantages and disadvantages should be weighted:

Following your link, asciidoc can manipulate newlines, but this must be configured at user level and - biggest disadvantage to me - it is some extra Python2-based software in maintenance and somewhat hard to install on Windows. On the other hand, the doctor probably cannot massage the line endings and is Ruby (also for me an extra). There exists though, a transpiled version for node (Asciidoctor.js - not checked yet). Another other language, but personally I have a few node requirements anyway, in particular katex. I probably wouldn't skip the possibility to have a choice between all of the three asciidoc converters.

So for me, the asciidoc-reader plugin should adjust its output before transparently providing it to Pelican core. And as said, it should be communicated as a binding contract for all such plugins at  this interface.

**Comment by avaris** [comment]
> I couldn't find anything like this mentioned in asciidoc, asciidoctor or docbook documentation and the switch has no effect at all, it is silently ignored. So, there is no setting lever for the pelican user.

It was from [here](http://asciidoc.org/userguide.html#_miscellaneous_section). That setting may or may not be relevant for `asciidoctor`, but it does affect `asciidoc` output.

**Comment by avaris** [comment]
Sorry, that was a "close by accident", but I'm tempted to close this here and pass the issue to plugin.

**Comment by traits** [comment]
Thats OK for me as long as it is solved :)

**Comment by avaris** [comment]
As a potential solution, instead of dealing with stdout from subprocess, most reliable way to get the content seems to be writing to a temporary file and reading it from python (and letting python deal with newline differences).

**Comment by traits** [comment]
This quick hack is working here:

```
            content = call("%s %s -o - %s" % (cmd, options, source_path))

            # Beware!
            # Don't use tempfile.NamedTemporaryFile under Windows: https://bugs.python.org/issue14243
            # and use mkstemp correctly (Linux and Windows): https://www.logilab.org/blogentry/17873

            fd, temp_name = tempfile.mkstemp() 
            f = open(temp_name, 'w', newline='')
            f.write(content)
            f.close()
            f = open(temp_name, 'r')
            content = f.read()
            f.close()
            os.close(fd)
            os.unlink(temp_name)
```

**Comment by avaris** [comment]
Looks mostly good, but I'd avoid reading `stdout` from `subprocess` completely by doing something like this:

```python
            # Beware!
            # Don't use tempfile.NamedTemporaryFile under Windows: https://bugs.python.org/issue14243
            # and use mkstemp correctly (Linux and Windows): https://www.logilab.org/blogentry/17873

            fd, temp_name = tempfile.mkstemp()
            content = call("%s %s -o %s %s" % (cmd, options, temp_name, source_path))
            with open(temp_name, 'r') as f:
                content = f.read()
            os.close(fd)
            os.unlink(temp_name)

**Comment by traits** [comment]
Unfortunately the changes (your and my variant) is breaking some things. I'm using pelican-latex, that will work only for the integrated markup languages (at least this is what I am seeing - untouched LaTeX source code in the html output) .
For asciidoctor at least an additional gem must be installed to support katex processing. This works more or less well for the current version of the asciidoc-reader plugin, but the temp file solution introduces some encoding issue, seen as wrong character values in the mathml part of the resulting html of an asciidoc source containing LaTeX.

**Comment by traits** [comment]
Replacing

`f = open(temp_name, 'w', newline='')`

by

`f = open(temp_name, 'w', newline='', encoding='utf8')`

fixed it (don,t know where to place the encoding in your variant).

**Comment by avaris** [comment]
Probably, here:
```python
            with open(temp_name, encoding='utf-8') as f:
                content = f.read()
```

However, I must say it's a bit strange that your version "works" by specifying the encoding just for the write part but not for the read part.

**Comment by traits** [comment]
>  but not for the read part.

Sloppiness - I also did it for the `read` call...

> asciidoc and asciidoctor seems to use utf-8.

... so it might be sufficient to apply the explicit coding for read access alone in the case of immediate writing to the temporary file utilizing one of both tools.

**Comment by traits** [comment]
Only to clarify: Would you guys keep taking care of  the final fix / forward the problem to plugin developers or should I open an issue in the plugin repository?

**Comment by avaris** [comment]
Well, there are no "dedicated" developers for plugins. It is a community effort driven by PRs from users like you :). I can try to look into it when I have time.

**Comment by traits** [comment]
Of course, we all have limited resources. In this case, I prefer to be the reporter. I've given some input for a basic implementation, that should be enough for now.

**Comment by justinmayer** [comment]
Thanks to both @traits and @avaris for all your work on this. I do not use Asciidoc, and given the lack of something that I can easily Pip-install and use, it is highly unlikely that I ever will.

That said, I reviewed this thread and made what I surmised to be the relevant changes to the plugin via https://github.com/getpelican/pelican-plugins/commit/22831d1da399ef54d732c395b0c6a28767622542, so hopefully that fixes the reported problem. If it doesn't, or I screwed it up and broke something horribly, by all means please submit a PR in the repository where the plugins actually live. #YOLO
