### ISSUE TITLE
Feed-related code is mixed into articles and settings code

### ISSUE THREAD

**Issue by kurtmckee** [getpelican/pelican#2695]
I'm reviewing Pelican's feed-related code and I've found that it is mixed into `ArticlesGenerator.generate_feeds()` (in `generators.py`) and `configure_settings()` (in `settings.py`, which generates a warning if `SITEURL` isn't set)

I'm interested in isolating the feed-related code into its own generator and contributing the changes back to the project but I'd like to confirm whether this work would be considered for inclusion.

Please let me know. Thanks!

**Comment by avaris** [comment]
What would be the benefit of that? Currently, feeds are for articles and their generation is part of article related output process. So it feels natural to have them in `ArticlesGenerator`.

PS: I would be very opposed to moving that warning out of `configure_settings`. The job of that function is to perform certain adjustments and sanity checks on the defined settings upon initialization and that warning very much belongs there.

**Comment by kurtmckee** [comment]
@avaris, I may have misunderstood the point of `ArticlesGenerator`.

My goal is to improve and isolate the XML feed writer and to introduce a JSON feed writer for my site.

However, Pelican explicitly discards all but the first Writer it finds (I'm looking at `__init__:Pelican.get_writer()`) so feed generation is hard-coded into the Articles code so that two distinct types of writers (HTML files and XML feeds) can still be written.

It looks like I can separate the HTML and XML feed writers into separate Writer objects and then rely solely on signals for both of those and for a JSON feed writer plugin.

Are there better ways to add additional writers in this situation?

**Comment by justinmayer** [comment]
Link to JSON-feed-related issue on FeedGenerator repository: https://github.com/getpelican/feedgenerator/issues/11

**Comment by avaris** [comment]
Yes, current design requires that there can only be one writer and base writer delegates a lot of the feed related tasks to `feedgenerator`. So it's probably best to extend `feedgenerator` with JSON feed option (^ issue linked by @justinmayer) amd provide that functionality in `pelican` core alongside with ATOM and RSS.

**Comment by justinmayer** [comment]
@kurtmckee: Any follow-up thoughts regarding this issue?

**Comment by justinmayer** [comment]
Hi Kurt. As @avaris suggested, if you would like to extend FeedGenerator to support JSON and then submit a PR to Pelican that uses that support, your contributions would be most welcome. Hopefully that answers your original question. I look forward to seeing what you come up with! ✨

**Comment by kurtmckee** [comment]
Good suggestions, Justin!

No, that doesn't answer my original question. My stated goal is JSON feeds but I can accomplish that any ol' which way. I'm wanting to implement it the "right" way and that led me to feeling that something isn't quite right with the current generators/writers pattern. That's the root issue in this bug report, but that feeling of hasn't been resolved through this discussion.

However, time has prevented me from doing a deep dive into the Pelican internals, so this is probably just a case of me not understanding something.

Thank you both for your time and responses, I really appreciate it!
