### ISSUE TITLE
Task "serve-global" in Makefile generated by pelican-quickstart requires port, but it is not defined

### ISSUE THREAD

**Issue by nikolausschueler** [getpelican/pelican#2696]
The task "serve-global" requires that the PORT variable is defined, but it is defined nowhere in the Makefile. 

The problem is in the Makefile template (pelican/tools/templates/Makefile.jinja2):

```
serve-global:
ifdef SERVER
  $(PELICAN) -l $(INPUTDIR) -o $(OUTPUTDIR) -s $(CONFFILE) $(PELICANOPTS) -p $(PORT) -b $(SERVER)
else
  $(PELICAN) -l $(INPUTDIR) -o $(OUTPUTDIR) -s $(CONFFILE) $(PELICANOPTS) -p $(PORT) -b 0.0.0.0
endif
```

The "serve" task checks for port, but "serve-global" only checks for the server. Maybe the solution is a nested check for port (as done in "serve").

**Comment by nikolausschueler** [comment]
Error message is as follows:

```
pelican -l /home/nik/pelican/content -o /home/nik/pelican/output -s /home/nik/pelican/pelicanconf.py  -p  -b 0.0.0.0
usage: pelican [-h] [-t THEME] [-o OUTPUT] [-s SETTINGS] [-d] [-v] [-q] [-D]
               [--version] [-r]
               [--print-settings [SETTING_NAME [SETTING_NAME ...]]]
               [--relative-urls] [--cache-path CACHE_PATH] [--ignore-cache]
               [-w SELECTED_PATHS] [--fatal errors|warnings]
               [--logs-dedup-min-level {DEBUG,INFO,WARNING,ERROR}] [-l]
               [-p PORT] [-b BIND]
               [path]
pelican: error: argument -p/--port: expected one argument
make: *** [Makefile:65: serve-global] Fehler 2
```

**Comment by justinmayer** [comment]
@nikolausschueler: I don't use Make and thus am ill-equipped to handle this one. Would you like to submit an appropriate fix?

**Comment by nikolausschueler** [comment]
Sure. I'm working on it.

**Comment by nikolausschueler** [comment]
Hi Justin, I tried a fix, using a virtualenv with Python 3.7. When I run pelican-quickstart, I get this error (excerpt):

```
> Do you want to upload your website using GitHub Pages? (y/N) 
Traceback (most recent call last):
  File "/home/nik/virtualenvs/pelican-2696-python-3/bin/pelican-quickstart", line 11, in <module>
    load_entry_point('pelican==4.2.0', 'console_scripts', 'pelican-quickstart')()
  File "/home/nik/virtualenvs/pelican-2696-python-3/lib/python3.7/site-packages/pelican-4.2.0-py3.7.egg/pelican/tools/pelican_quickstart.py", line 312, in main
    'w', 'utf-8') as fd:
TypeError: an integer is required (got type str)

```

The reason seems to be the way open is used:

```
       with open(os.path.join(CONF['basedir'], 'pelicanconf.py'),
                  'w', 'utf-8') as fd:
```

It expects a "buffering" parameter after the mode, which is must be an integer, hence the error.

If you change the lines above to 

```
       with open(os.path.join(CONF['basedir'], 'pelicanconf.py'),
                  'w', encoding='utf-8') as fd:
```

it works. 

Note that without a virtualenv everything works fine. 

Do I use virtualenvs in the wrong way and is this a known problem? If not, should I create a new issue?

BR

Nik

**Comment by avaris** [comment]
@nicholaskuechler You are right and I'll take the [blame](https://github.com/getpelican/pelican/pull/2649/commits/49bc6ed47f75cb29eade8e2b1a4cf10bfaf73d92) :). I hastily switched `codecs.open` to `open` without considering inconsistencies. I don't think a new issue is needed. Just add a commit that puts `encoding` keywords to open arguments to the PR you're currently working on.

**Comment by nikolausschueler** [comment]
Hi Avaris,

I will submit a pull request for that. I don't think this should be mixed up with my (still to be written) Makefile template change.

BR

Nik

**Comment by iKevinY** [comment]
> You are right and I'll take the blame :).

Also my bad for not catching this in review.
