### ISSUE TITLE
Issue converting Google Blogger feed.atom to Pelican blog site

### ISSUE THREAD

**Issue by espressobeanies** [getpelican/pelican#2703]
I'm still trying to confirm several Google Blogger feed.atom files I have into a Pelican blog site, but it looks like I'm still being hit with errors. Not sure what I'm doing wrong here:

```
[root@blog www]# pelican-import --blogger -m MARKDOWN -o /var/www/pelican-blog/ /home/eb/Blogger/Blogs/Install\ Guides/feed.atom
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check http://docs.getpelican.com/en/latest/settings.html#timezone for more information
Traceback (most recent call last):
  File "/usr/local/bin/pelican-import", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 1026, in main
    attachments=attachments or None)
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 787, in fields2pelican
    kind, in_markup) in fields:
  File "/usr/local/lib/python3.7/site-packages/pelican/tools/pelican_import.py", line 207, in blogger2fields
    'category', {'scheme': 'http://schemas.google.com/g/2005#kind'}
AttributeError: 'NoneType' object has no attribute 'get'
```

Specs: Pelican Blog 4.2.0 installed with Markdown and Pandoc dependencies

**Comment by davidag** [comment]
Hi @espressobeanies, are you using the backup feature in [the Blogger control panel](https://support.google.com/blogger/answer/41387?hl=en) to generate the xml?

The error you provided happens when using the feed available in your blog page instead of the mentioned backup file.

I hope this helps!

**Comment by espressobeanies** [comment]
No I'm not. The filetype for Google Blogger is 'feed.atom' so the extension is '.atom' not '.xml'.

**Comment by davidag** [comment]
When I say "the feed" I mean the atom file that you would use to subscribe to a given blog. This is public, everyone has access to it, usually in a known URL.

The backup file is also an atom file, but it is generated in the Blogger control panel following the steps provided in [the reference in my previous comment](https://support.google.com/blogger/answer/41387?hl=en). This is private to the owner of the blog.

I'm not 100% sure that this is the problem you are facing, but I did a test and I got your exact error using the "public atom feed", while everything went fine using the "private atom backup file".

I hope it is more clear now :)

**Comment by justinmayer** [comment]
@espressobeanies: Were you able to resolve your importing issue?

**Comment by espressobeanies** [comment]
Hey guys, sorry for the delay. Thanks for the follow-up. So I did the backup of my Blogger site and deleted another Gmail account I was using with the Blogger site. Those backups I took from Google, it doesn't appear I can do much with them since I didn't export them to another format. I'm not sure what the best solution would be in this circumstance but I thought for some reason I could import the .atom files into Pelican and go from there.

**Comment by oulenz** [comment]
So just to be clear, you no longer have access to the original Blogger site?

And when you say 'backups', do you mean the feed.atom files you mentioned in your first post? Or do you mean a full backup of your blogger site?

**Comment by justinmayer** [comment]
Hi @espressobeanies. I hope you were able to resolve your issue. If you need further assistance, please consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation. Thanks!
