### ISSUE TITLE
Listen server does not listen to Ctrl-C

### ISSUE THREAD

**Issue by domeniko-gentner** [getpelican/pelican#2704]
I was trying this out to maybe replace Jekyll and so far, it was very painful. The most annoying thing is that the server cannot be cancelled on Windows with Ctrl-C. I have to kill the process.

**Comment by justinmayer** [comment]
Not sure what you mean by "the server", but I recommend the following instead:
1. Run `pelican-quickstart` to generate an up-to-date Invoke `tasks.py` file
2. `pip install invoke livereload`
3. `invoke livereload`
