### ISSUE TITLE
Json to content

### ISSUE THREAD

**Issue by Lowell130** [getpelican/pelican#2708]
Hello it's possible generate content from data stored in a single or multiple jsons file?
thanks

**Comment by avaris** [comment]
Sure, if you write a `Reader` for it.

**Comment by Lowell130** [comment]
> Sure, if you write a `Reader` for it.

i am not python expert, where i can get help?

**Comment by avaris** [comment]
There is an [example reader in the docs](https://docs.getpelican.com/en/stable/plugins.html#how-to-create-a-new-reader). You need a version of this that reads the JSON file and return appropriate content and metadata from it (depends on the JSON structure). You can use the built in python module [json](https://docs.python.org/3/library/json.html) to parse it. After that you need the logic for extracting content and metadata from it.

**Comment by justinmayer** [comment]
Hope that helps, Stew. Let us know if you need further guidance.
