### ISSUE TITLE
Issues of code block inside a list

### ISSUE THREAD

**Issue by dclong** [getpelican/pelican#2709]
I found that there are issues with a code block in a list. 
The following code 
```
1. Remove images without versions (with the help of `awk`).

    ```bash
    docker images | awk '{ if ($2 == "<none>") print $3 }' | xargs docker rmi
    ```
```
generates (notice bash at the begining of the code block).
![image](https://user-images.githubusercontent.com/824507/78610258-5263a900-7819-11ea-9878-605f29568421.png)

However, if I use 8 space indention inside a list, some characters in the code are escaped. 
For example,
the following code
```
2. Remove images without names or versions (with the help of `awk`).

        docker images | awk '{ if ($1 == "<none>" || $2 == "<none>") print $3 }' | xargs docker rmi
```
generates (notice escaped characters)
![image](https://user-images.githubusercontent.com/824507/78610402-99ea3500-7819-11ea-9925-3e6526aea07b.png)

Version of Tools:
OS: macOS Catalina
Python: 3.7.6
Pelican: 4.0.1

**Comment by justinmayer** [comment]
Pelican doesn't do said rendering itself — it relies on Python-Markdown for Markdown content and Docutils for reST content. Presumably, your source content is Markdown.

You can try rendering your test file directly with Python-Markdown via something like this:

    markdown_py -f your-output.html your-source-content.md

… which in theory should confirm that Pelican isn't related to the problem you describe here.

**Comment by davidag** [comment]
[Pelican activates by default](https://docs.getpelican.com/en/stable/settings.html#basic-settings) the CodeHilite plugin of Python-Markdown:

```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```

In the [plugin documentation](https://python-markdown.github.io/extensions/code_hilite/) there are several ways to specify the language to do the syntax highlighting, but the one you have used does not appear. Maybe you could try a different one?

**Comment by avaris** [comment]
That's a limitation of Python-Markdown, see Python-Markdown/markdown#53. Not much to do on `pelican` side.

**Comment by dclong** [comment]
Thank you all for the information! I will watch the issue in the markdown repository.
