### ISSUE TITLE
Wrong logic for searching themes?

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2717]
Pelican allows setting `THEME` to just the name of the theme and not a path.  However, when it tries to resolve a specified name (in https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L518) it calculates the base directory relative to itself (in my case Pelican is installed system-wide and the code above produces `/usr/lib/python3.8/site-packages/pelican/` - surely there are no themes under that path).

I think that line needs to be fixed to calculate the base directory using the following cascade logic:

1. try `themes/` relative to `pelicanconf.py`
2. try `themes/` relative to the current working directory
3. fail with "Could not find theme ..."

**Comment by galaxy4public** [comment]
It is actually the same for the `DEFAULT_THEME` (in https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L25), where Pelican assumes that it is installed locally and not system-wide.  I would suggest to use the same logic as above and anchor it around `pelicanconf.py` and the current working directory instead.

**Comment by avaris** [comment]
> surely there are no themes under that path

Yes, [there are](https://github.com/getpelican/pelican/tree/master/pelican/themes). And, it doesn't matter whether you install `pelican` locally or system wide. `pelican` ships with a theme. So, in the place it is installed, there will be theme (`DEFAULT_THEME` as well as `basic`). There is also a legacy script called `pelican-themes` that could "install" themes to that location. But don't use it, putting stuff inside `site-packages` afterwards isn't the best idea :). I'd suggest specifying full paths to theme. If you want to tie it to the settings you could do this:

```
import os
settings_path = os.path.abspath(os.path.dirname(__file__))

THEME = os.path.join(settings_path, 'mytheme')
```

**Comment by galaxy4public** [comment]
@avaris, thanks for a prompt and comprehensive answer (as always!).  This is munch appreciated and I hope will help others in the future to find their answer to this question too.
