### ISSUE TITLE
Should STATIC_EXCLUDES honour THEME_STATIC_PATH?

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2718]
It is more of a question rather than a bug report.

According to the code `STATIC_EXCLUDES` only operates on files/directories in `PATH`.  However, my understanding of the intent for this configuration variable is that it should allow the end user to control what will eventually end up in their output directory.

Themes also have static content and sometimes the user may want to suppress parts of that static content to be copied to their output. A natural expectation is that if one puts a path to exclude into `STATIC_EXCLUDES` (e.g. `themes/your_theme/static` that matches one of `THEME_STATIC_PATHS`) then the objects matching it would be excluded from the output.

This actually brings another question on the theme self-configuration, e.g. as a theme creator I am making some choices and instead of asking my potential users to update their `pelicancong.py` with this and that it would be nice if the theme itself could provide defaults to the settings.  Just an additional thought :)

**Comment by avaris** [comment]
Maybe. But, I'm leaning into the more easier option of "not putting excluded stuff there in the first place". One potential use case I can think of is things like `LESS` etc files that will be processed later with `assets` plugin into `CSS`. I don't recall exactly, but I think `assets` works on the output rather than input, i.e. files need to be copied first. Exclude is useless for this case.

**Comment by avaris** [comment]
Regarding, theme self-configuration. We would like to switch to themes as python packages (see #1564). This could provide the option for themes to provide their own configuration that could be accessed by `pelican`. So, ~some~ a lot of work is required on that front :).

**Comment by galaxy4public** [comment]
Re: theme self-configuration - I am about to push a PR with a simple, yet I think elegant solution for the mean time (it is a bit limited in what it can do, but gives enough flexibility to give theme authors ability to provide defaults for their themes).

**Comment by galaxy4public** [comment]
#2719 is created to address the themes self-configuration. 

Re: the original question - I see your point.  My question was born out of the following: I try to minimise the number of tools my static website depends on (I am deploying to GitGub Pages using GitHub Actions, and right now it is as simple as `pip -r requirements && pelican`).  In my theme I am using PrismJS which is being attached to the theme using git submodule (I am not interested in developing PrismJS, yet it is frequently updated).  Out of the whole PrismJS I am interested in just handful of files, hence I was searching for an option to exclude the entire directory, but pick a few files from there.

Anyway, as I said, I see your point and maybe what I want is just wrong :)

**Comment by avaris** [comment]
You could put the submodule outside `static` and symlink the files you want to their `static` locations.

**Comment by galaxy4public** [comment]
You are very helpful! Yes, in a virtual world we can do all kind of crazy stuff.  But what you propose is not any better than introducing a post processing (read, post-`pelican`) hook into the GitHub Action and just fix the output.  I would say it is even worse since it brings chaos into the configuration structure.

The thoughts I had when I was posting the question were along side the following: the end user of Pelican cares about the result of the generator, i.e. what will be produced in the output directory.  Hence, as an end-user I want control over that directory to be able to choose what ends up there (no matter how and where it was sourced or generated).

Then, my train of thought was derailed by looking for a possible answer and I stuck with `STATIC_EXCLUDES`, when in truth, I think this should be implemented as a set of:

**Comment by avaris** [comment]
> You are very helpful! Yes, in a virtual world we can do all kind of crazy stuff. But what you propose is not any better than introducing a post processing (read, post-pelican) hook into the GitHub Action and just fix the output. I would say it is even worse since it brings chaos into the configuration structure.

I don't get this. You said you submodule PrismJS to get updates (fair) but need a few files from that (also fair). What exactly is wrong with what I proposed? Submodule it outside of `static` but *keep* it inside theme so it's still version controlled along with the theme (somewhere like `theme/sources`). Then, symlink the files from submodule to `static/whatever`. From your description, this is exactly what you want.

**Comment by galaxy4public** [comment]
@avaris , yes, it is.  Please don't be upset -- you provided a perfectly fine solution to the problem I described.  I am just really bad at expressing myself, I did not intend to offend you in any way.  I will take onboard your suggestion and suggest to close this thread as a non-issue since as I mentioned before, I see your point, it is a valid one, and I am not sure that I want to pursue this direction any further - I agree that the whole "crappy source tree" is not Pelican's responsibility. :)

**Comment by avaris** [comment]
No worries, I'm not offended :). I was just wondering if I understand the issue clearly or not.

**Comment by galaxy4public** [comment]
I am closing this as a non-issue since the proposed solution works great.
