### ISSUE TITLE
Rendering static links in subclass of BaseReader

### ISSUE THREAD

**Issue by nandac** [getpelican/pelican#2722]
Hi Pelican Team,

I have adapted the code from the pandoc_reader plugin and added some extra capabilities and I am having issues where the rendering of links such as:
`{filename}/images/myblog/myimage.svg`

renders in the HTML as

`%7Bfilename%7D/images/bushido/four-times-three.svg`

If I were to use the default readers the rendering of the static links works as expected.

I think for some reason the BaseReader rendering is being overwritten by Pandoc's rendering perhaps but I do not see why that should happen.

The images are being moved to the right location in outputs it is just the link rendering that is not working.

The code for my version of the plugin is here:
https://github.com/nandac/pandoc_reader/blob/master/pandoc_reader.py

I hope you will be able to assist me in finding the root cause of this issue as I only started on Pelican a week ago.

Many thanks.

**Comment by avaris** [comment]
`BaseReader` doesn't do any rendering. That's what `pandoc` gives you. For the record `pandoc` is percent-encoding your URLs, which is fine in regular case but for this use case it is undesired. I'm not really familiar with `pandoc` much, I'd suggest checking its documentation to see if there is an option for not encoding URLs.

**Comment by nandac** [comment]
Thank you for your reply @avaris. I had not thought of getting Pandoc to switch off encoding of URLs. I will look into that.

Would you be able to point me to the code that sets up the static file links?

If the links are being encoded as shown above I may need to get the static files links setup before it is sent to the Pandoc reader which is what I am thinking.

Many thanks.

**Comment by avaris** [comment]
Static file resolution is *after* the content is rendered into HTML. The reader needs to output content HTML with `{filename}` in the links (*not encoded*). `pelican` resolves those when it's writing the output, because links will depend on where the output will be, both the file that is written as well as the file link points to.

**Comment by nandac** [comment]
Thank you so much @avaris!

I modified the plugin to replace the encoded `%7Bfilename%7D` with `{filename}` and it is working for me now.

**Comment by avaris** [comment]
I just want to point out the two other similar keywords `pelican` uses: `{static}` and `{attach}`. You might want to include them in your conversion too.

**Comment by nandac** [comment]
Thanks for the heads up I will add these in too.
