### ISSUE TITLE
Google Analytics missing from simple theme

### ISSUE THREAD

**Issue by jimpudar** [getpelican/pelican#2728]
I will open a PR to add this shortly...

**Comment by justinmayer** [comment]
Hi Jim. Good morning! Do you actually use Simple theme by itself? I'm trying to understand the motivation here. Could you perhaps elaborate and let me know more about the thought process that led to this?

**Comment by jimpudar** [comment]
Hi @justinmayer, sorry for the late reply - yes indeed I am using the simple theme by itself.

**Comment by justinmayer** [comment]
No worries, Jim. I think it's best to keep the Simple theme as eponymously simple as possible. Moreover, my general feeling these days is that we should be reticent about adding anything to FLOSS projects that are even tangentially related to corporate ad tracking business models.

**Comment by jimpudar** [comment]
Yeah definitely makes sense, in any event if the functionality is desired it's not difficult for the end user to extend the Simple theme.
