### ISSUE TITLE
Incorrect anchor link to TIMEZONE setting docs

### ISSUE THREAD

**Issue by DustinCraig** [getpelican/pelican#2732]
When using the pelican-quickstart tool I was asked what the timezone of the site would be and I wasn't sure exactly what to put down so I said EST which later on gave me a warning stating that the timezone was invalid and to check https://docs.getpelican.com/en/latest/settings.html#timezone for more information. When I clicked on the link it brought me to the settings page correctly but it did not set my scroll position to the timezone section. I have tried the link on the latest versions of Firefox and Google Chrome.

**Comment by avaris** [comment]
Yes, link should be: https://docs.getpelican.com/en/latest/settings.html#TIMEZONE

I don't remember when the links changed, but seems like that message wasn't updated.

**Comment by justinmayer** [comment]
Fixed via 4a7cff76. Many thanks to @DustinCraig for reporting and to @avaris for providing the correct link anchor. 💫
