### ISSUE TITLE
pelican conf "from future" no longer required?

### ISSUE THREAD

**Issue by datakid** [getpelican/pelican#2740]
Given that Python3 is now default and Py2 EoL, remove 

```
from __future__ import unicode_literals
```

from pelicanconf.py

**Comment by justinmayer** [comment]
Hi Lachlan. Did you check what is in `master` or are you reporting on the last release, which was six months ago? As far as I can tell, that was addressed in `master` already: https://github.com/getpelican/pelican/blob/master/pelican/tools/templates/pelicanconf.py.jinja2

**Comment by datakid** [comment]
My apologies, I didn't check against master but I should have. Sorry.

**Comment by justinmayer** [comment]
No worries. I appreciate the intention! 😊
