### ISSUE TITLE
Improve documentation of STATIC_URL for CDN resource split

### ISSUE THREAD

**Issue by bitkeks** [getpelican/pelican#2743]
Greetings, thank you all for your work on pelican! It's a wonderful tool and I'm a user since many years! 

This issue is related to #2349. I'd like to suggest an improvement in documentation and awareness of the `STATIC_URL` and `STATIC_SAVE_AS` parameters, which might lead to a better utilization of this feature for external static domains/origins. In [the current 4.2.0 docs](https://docs.getpelican.com/en/4.2.0/content.html) the reference to `STATIC_*` is kinda hidden. Only by accidentally looking at [the respective tests](https://github.com/getpelican/pelican/blob/e87717d27c8689ae288d1ab244648f38d20e3ddf/pelican/tests/test_contents.py#L478) I came to learn about the possibility to use another domain for `{static}` assets. 

This search was based on an experiment to add a `{cdn}` placeholder, which can easily be integrated [into the list of existing placeholders](https://github.com/getpelican/pelican/blob/e87717d27c8689ae288d1ab244648f38d20e3ddf/pelican/contents.py#L304), replacing the placeholder with a value from the config, e.g. `CDN_URL_PREFIX`. Example code (not tested):
```python
elif what == 'author':
    origin = joiner(siteurl, Author(path, self.settings).url)
elif what == 'cdn':  # new placeholder type
    origin = joiner(self.settings["CDN_URL_PREFIX"], path)
else:
    logger.warning(
```
This implementation would also allow to use different domains for testing and production, by setting different `CDN_URL_PREFIX` values in pelicanconf and publishconf. So, since this feature is already in place – I guess people might benefit from a more explicit hint explaining the usage of `STATIC_` and split domains for static assets.

**Comment by avaris** [comment]
It is probably better to expose parts of this or have a `dict` with `'keyword': function` mapping to get URL. This won't be user friendly (requiring user to write python functions), but at least plugins can place custom mappings and implement an easier configuration.

**Comment by justinmayer** [comment]
Many thanks for the kind words, @bitkeks! Very kind of you.

@bitkeks / @avaris: What do you think is the best way to proceed here? Any chance you could collaborate on this issue and come up with an appropriate remedy?
