### ISSUE TITLE
Parent/child theme structure, like WordPress?

### ISSUE THREAD

**Issue by thinkhuman** [getpelican/pelican#2744]
I'd like to propose a feature: 
As a Pelican user, I want to create theme customizations (templates, static, any) that inherit from a published 'parent' theme, so I can continue to update the parent theme while retaining my set of customizations.

This is a key feature of WordPress theming, and makes it easy to keep updating published 'parent' themes while making a subset of child customizations for a specific site. 

I think smoothing the path of theme customization and use could contribute much to broader adoption of Pelican.

I'm aware of `THEME_TEMPLATE_OVERRIDES`, but I don't think that accomplishes this (and it doesn't help with CSS).

**Comment by avaris** [comment]
See #1092

**Comment by thinkhuman** [comment]
@avaris I saw that one, but if I read it right:
1. It only applies to one theme ('simple')
2. It addresses templates for that single theme, but doesn't account for CSS inheritance (i.e., if I create some custom CSS, will all the non-customized CSS in the 'parent' theme still apply?)

Otherwise, it looks like a similar idea.

**Comment by avaris** [comment]
Initial post is limited in scope but if you follow the conversation, it turns into theme inheritance, which is basically (child) theme building on another (parent) theme.

**Comment by justinmayer** [comment]
Hi James. As @avaris mentioned, the topic of theme inheritance that has been around for while.

> It only applies to one theme ('simple')

Regardless of what may happen later in the thread, the genesis of the issue — which is titled _Inherit from arbitrary theme_ — is clearly **not** about the Simple theme:

> It would be useful to have the ability to inherit from themes other than simple.

In any case, setting aside implementation detail differences between proposals therein, I think both issues are about theme inheritance.

I understand and appreciate your desire for this feature to exist. [As I suggested when I closed that issue](https://github.com/getpelican/pelican/issues/1092#issuecomment-514273473) — six years after it was opened — it is extremely unlikely that such a feature will materialize unless someone steps forward to work on it. Is this feature something you would be interested in implementing?

**Comment by thinkhuman** [comment]
Hi @justinmayer I'd be interested in implementing it, but I'm not sure I have the chops to program it. I'd need a fair amount of mentoring/guidance. 

Also: my questions about this potential feature are probably naive, since I'm a newcomer to Pelican.

**Comment by justinmayer** [comment]
That's okay. Perhaps some more than others, but every single person who has contributed to Pelican has had to learn something in order to participate. I know I certainly did.

We would be happy to provide as much guidance as our respective schedules afford. With that in mind, would you like to work on this? Please let me know, in which case I'll close this issue and re-open the other one.

**Comment by thinkhuman** [comment]
@justinmayer One question first: In the docs, [Inheritance](https://docs.getpelican.com/en/stable/themes.html#style-css) mentions using a custom stylesheet, but it's not clear--does that work like the template inheritance, or does specifying a `static/css/style.css` mean the 'parent' theme's stylesheet gets ignored?

**Comment by avaris** [comment]
@thinkhuman That's from [`simple`](https://github.com/getpelican/pelican/tree/master/pelican/themes/simple

**Comment by thinkhuman** [comment]
Ah, thanks @avaris. If it were possible to code your own stylesheet, then @import all the styles from the theme, then use your stylesheet, I think we'd be 99% of the way to parent>child theme inheritance.

**Comment by justinmayer** [comment]
Since it doesn't make sense to have three duplicate theme-inheritance issues floating around (@copperchin just filed an issue related to theme inheritance), I am closing this in favor of the original issue on this topic, #1092. Looking forward to your contributions toward this feature.
