### ISSUE TITLE
Cache busting?

### ISSUE THREAD

**Issue by thinkhuman** [getpelican/pelican#2749]
I'm new to Pelican, but caching seems to be a real problem. When I change themes by changing the THEME variable and regenerating, it often doesn't take. It *seems* like a caching problem, so I've tried `LOAD_CONTENT_CACHE = False` -- no luck at all. I tried the ignore flag, too. Nothing. Sometimes one page will have one theme, and a second page another. I also deleted the browser cache for localhost.

So, I tried *deleting* the contents of the output folder. Pelican regenerated it--but now, the home page won't display (or isn't generated--I'm not sure); all I see is a directory listing in the browser for the main page.

Any ideas what might cause this? I'm trying canned themes from pelicanthemes.com.

[EDIT] Seems to have resolved, though I'm not sure why. Deleting and redoing DIRECT_TEMPLATES resolved the home page issue; also site seems to have correct theme now.

**Comment by justinmayer** [comment]
Hi James. Glad you were able to resolve this issue. Before I close this one… We have seen your questions in the Pelican IRC channel regarding full-content vs. article summaries, but when it came time to reply, each time you had already left the channel. I replied instead via [your S.O. query](https://stackoverflow.com/questions/61670792/in-pelican-how-do-i-display-the-full-latest-article-post-on-the-home-page/61692634#61692634). Did that answer your question?

**Comment by thinkhuman** [comment]
Thanks @justinmayer, I think that's what I was looking for. My main stumbling block with Pelican has been templating/themeing, and I didn't get a clear picture from the docs. To be fair, I've had a similar experience with this topic while experimenting with Hugo and Jekyll (I'm trying to choose). For all three generators, 'make your own theme from scratch' seems the best option (for me, anyway). This is why I think parent>child themeing would blow open the doors to adoption for many users like me.

About IRC: for some reason, the web client kept kicking me off. Sorry I missed your responses.

**Comment by justinmayer** [comment]
Having recently adapted an HTML+CSS-only theme for use with Pelican, I found it to be a straightforward and pleasant process. I imagine that is indeed your best bet.

I imagine that comprehensive parent ⇆ child theme inheritance is difficult to implement in any meaningful way, thereby rendering the endeavor impractical. I suspect that is why you aren't finding it.
