### ISSUE TITLE
Adding certain tags to new page causes a CRITICAL error

### ISSUE THREAD

**Issue by warsaw** [getpelican/pelican#2754]
The last addition to my blog was in 2018, and in that time I've updated to pelican 4.2.0.  I am now creating a new page for my blog, but certain tags cause fatal errors.  I've used both the `python` and `python3` tags in previous articles, and I've even used them in combination.  I've used many other tags too.

In the new one, if I add the `python3` tag, everything works.  If instead I add the `python` tag, I get the following critical error:

```
pelican /Users/barry/projects/websites/wefearchange/content -o /Users/barry/projects/websites/wefearchange/output/htdocs -s /Users/barry/projects/websites/wefearchange/pelicanconf.py 
CRITICAL: RuntimeError: File /Users/barry/projects/websites/wefearchange/output/htdocs/tag/python3.html is to be overwritten
make: *** [html] Error 1
```

Running with `DEBUG=1` does not provide any additional information for debugging the problem.

**Comment by avaris** [comment]
I'm guessing but this might be related to pagination. [Default pagination](https://docs.getpelican.com/en/stable/settings.html#pagination) will add numbers to the name. For the `python` tag:
* first page: `python.html`
* second page: `python2.html`
* third page: `python3.html`
so on.

Third page obviously creates a clash with `python3` tag (where the first page would be `python3.html`).

You need to somehow disambiguate these. By changing how other pages are handled (via `PAGINATION_PATTERNS`) or by how they are saved (`TAG_SAVE_AS`).

**Comment by justinmayer** [comment]
Hi Barry. As @avaris mentioned, one way to solve the problem would be to use a different pagination pattern. There is an example that yields `/page/2/`, `/page/3/`, etc. at the end of the relevant section of the docs: https://docs.getpelican.com/en/stable/settings.html#using-pagination-patterns

Anything else we can help you with here?

**Comment by warsaw** [comment]
@avaris @justinmayer - Thank you both for your responses.  One thing I'm still not clear on is how `PAGINATION_PATTERNS` applies to tags, which is where I'm having the problem.  It looks like this setting is all about pages, so how does Pelican know what patterns to apply to multi-page tags?  Also, what would be the default setting of `PAGINATION_PATTERNS`?  I wouldn't want to mess anything else up.

**Comment by warsaw** [comment]
I do have a temporary workaround though: I can set `DEFAULT_PAGINATION` to 20, and then all my `#python` tags would fit on 2 pages.

BTW, Here's the site: [We Fear Change](https://wefearchange.org/).  Thanks for the great tool.  I love it for generating my blog.

**Comment by justinmayer** [comment]
Nice site! Thanks for the kind words and for sharing the link. It's always great to see what people create with Pelican. 😁

The error you encountered occurs when the generator notices it is about to write to the same filesystem path more than once, thereby overwriting the first file written. Since Pelican generates per-tag HTML pages such as https://wefearchange.org/tag/python.html, those pages paginate via the `PAGINATION_PATTERNS` setting when the number of `python`-tagged posts gets high enough, eventually leading to https://wefearchange.org/tag/python2.html and https://wefearchange.org/tag/python3.html pages. But since you already have a `python3` tag, that latter page is where the collision occurs.

Regarding default settings, those are always listed for every setting in the documentation, on the Settings page. See the Pagination section of that page for pagination setting-related details.

**Comment by warsaw** [comment]
Thanks again for the help but I can't seem to make it work.  I started with something like this:

```
PAGINATION_PATTERNS = (
    (1, '{url}', '{save_as}'),
    (2, '{base_name}/tag/{number}', '{base_name}_{number}.html'),
    )
```
and that seemed to do the trick:

```
% ls output/htdocs/tag/python*.html
output/htdocs/tag/python.html		output/htdocs/tag/python_2.html
output/htdocs/tag/python3.html		output/htdocs/tag/python_3.html
```

I did have to make some changes to my theme's `templates/index.html` file to use the new naming scheme.  However, all of my non-tag regular page indexes are messed up:

```
% ls -l output/htdocs
...
-rw-rw-r--   1 barry  staff  50728 May 17 15:51 _2.html
-rw-rw-r--   1 barry  staff  45949 May 17 15:51 _3.html
-rw-rw-r--   1 barry  staff  40333 May 17 15:51 _4.html
-rw-rw-r--   1 barry  staff  30236 May 17 15:51 _5.html
-rw-rw-r--   1 barry  staff  36287 May 17 15:51 _6.html
...
```

Because I really don't know what I'm doing, I tried this:

```
PAGINATION_PATTERNS = (
    (1, '{url}', '{save_as}'),
    (2, '{base_name}/tag/{number}', '{base_name}_{number}.html'),
    (2, '{base_name}/index_{number}.html', '{base_name}/index_{number}.html'),
    )
```

and now my indexes look right:

```
-rw-rw-r--   1 barry  staff  44224 May 17 15:54 index.html
-rw-rw-r--   1 barry  staff  50728 May 17 15:54 index_2.html
-rw-rw-r--   1 barry  staff  45949 May 17 15:54 index_3.html
-rw-rw-r--   1 barry  staff  40333 May 17 15:54 index_4.html
-rw-rw-r--   1 barry  staff  30236 May 17 15:54 index_5.html
-rw-rw-r--   1 barry  staff  36287 May 17 15:54 index_6.html
```

but my tags don't:

```
-rw-rw-r--  1 barry  staff  47915 May 17 15:54 output/htdocs/tag/python.html
-rw-rw-r--  1 barry  staff  40497 May 17 15:54 output/htdocs/tag/python3.html
```

(aside from the fact that I can't figure out where to change my templates to use the underscored numbered indexes).

What am I missing?  I'm using [this documentation](https://docs.getpelican.com/en/stable/settings.html#pagination).

**Comment by avaris** [comment]
@warsaw You don't need to change much to get an `_` between name and number. Try this:

```python
PAGINATION_PATTERNS = (
    (1, '{name}{extension}', '{name}{extension}'),
    (2, '{name}_{number}{extension}', '{name}_{number}{extension}'),
)
```

**Comment by warsaw** [comment]
@avaris Thank you! I think that's fixed all my problems!  With the small update to my template, it looks like everything is happy.  I *really* appreciate all the patience and help.

**Comment by justinmayer** [comment]
Very glad to hear it. You made it a pleasure to be of assistance. Looking forward to reading more of your posts. 💫

**Comment by warsaw** [comment]
FYI: https://wefearchange.org/2020/05/zenofpython.rst.html

**Comment by andreagrandi** [comment]
> @avaris Thank you! I think that's fixed all my problems! With the small update to my template, it looks like everything is happy. I _really_ appreciate all the patience and help.

Hi! I was having the same problem then someone pointed me to this post. I've tried the `PAGINATION_PATTERNS` suggested by @warsaw and it works for me too. What is not clear is: what changes did you have to do to the template to make it work? 🤔. I simply added this settings, recreated the pages and now "Older posts" are being correctly linked in the template without me changing anything. What am I missing? Thanks
