### ISSUE TITLE
Get a list of installed Pelican plugins

### ISSUE THREAD

**Issue by dclong** [getpelican/pelican#2759]
Is it possible to get a list of installed pelican plugins (in the upcoming release)? Or if there any way to configure pelican to throw exceptions (rather keep proceeding) if a plugin is missing? Basically, I don't want my bog to be messed up due to a missing plugin.

**Comment by avaris** [comment]
> Is it possible to get a list of installed pelican plugins (in the upcoming release)?

Current master contains `pelican-plugins` command that will list you the installed namespace plugins.

> Or if there any way to configure pelican to throw exceptions (rather keep proceeding) if a plugin is missing?

Yes, see [`--fatal` option](https://github.com/getpelican/pelican/blob/d0457dcfb8a10e48fdf6d6f7535ce0194bf601ee/pelican/__init__.py#L306-L309) from `pelican --help`

**Comment by justinmayer** [comment]
To my knowledge, the answer to this question is already be clearly explained in the `latest` version of the docs.

**Comment by justinmayer** [comment]
It turns out my previously-mentioned "knowledge" is not very reliable: I couldn't find any mention of the `pelican-plugins` command in the documentation, so I just added a commit (9db937e5) that mentions it early in the Plugins docs to improve the odds that folks will notice it.
