### ISSUE TITLE
writers/generators description in internals.rst

### ISSUE THREAD

**Issue by epogrebnyak** [getpelican/pelican#2765]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

Got a question about https://docs.getpelican.com/en/stable/internals.html#overall-structure.

My suggestions:

- [ ] put description in linear order reader first, then writer
- [ ] specify what generator does - is it internal representation of markdown/rst source or a filter after the writer?
- [ ] maybe specify entry points for pelican if one wants to use the package programmatically

In pandoc, for example, by reading the docs it becomes clear there are different input formats, so there are readers, and there are different output formats, so there are writers. The mindmap is following `a file -> reader -> internal representation -> writer -> output file`. 

Reading the https://docs.getpelican.com/en/stable/internals.html#overall-structure I do not understand the flow, even though it is apparently simple:

- writers make different output files, but they pass something to generators (confusing - is this the start, middle or end of pipeline?)
- readers read source files, split metadata and generate html content (this I understand, but why not make this step 1 in the description?)
- generators:
  - _given a configuration, they can do whatever they want_ (confusing in general, maybe there is some behavior intent what we want them to do) 
  - _Most of the time, it’s generating files from inputs_ (what is the input? a writer's output?)

Is the chain described `source files -> readers -> writers -> generators -> output html files`?

**Comment by epogrebnyak** [comment]
If applicable, on this chart - what is a writer? or it is off this chart?

![изображение](https://user-images.githubusercontent.com/9265326/83943233-2194f580-a803-11ea-8468-d639b5118ab1.png)

**Comment by avaris** [comment]
> Reading the https://docs.getpelican.com/en/stable/internals.html#overall-structure I do not understand the flow, even though it is apparently simple:

That wasn't meant as flow more like describing the internal structure, like the building block pieces. Order there doesn't imply process order. I'll try to make a (rough) flow below.

> writers make different output files, but they pass something to generators (confusing - is this the start, middle or end of pipeline?)

No, they don't pass something to generator. Generators are *passed* a `writer` to use (".. then passed to the generators")

> readers read source files, split metadata and generate html content (this I understand, but why not make this step 1 in the description?)

It's not a linear chain.

> generators:
> given a configuration, they can do whatever they want (confusing in general, maybe there is some behavior intent what we want them to do)

Internally, they can do whatever they want. Externally, they need two methods for `pelican` to drive process, [explained below](https://docs.getpelican.com/en/stable/internals.html#how-to-implement-a-new-generator).

> Is the chain described source files -> readers -> writers -> generators -> output html files?

Flow is roughly like this:
```text
                             +-------------------+      File       +-----------------+
                             |      Readers      +---------------->+    RstReader    |
                             |  (collection of   |                 |    MdReader     |
                             |  file readers)    +<----------------+    etc...       |
                             |                   |     Content     |                 |
                             +-------+---+-------+     Metadata    +-----------------+
                                     ^   |
                                     |   |
                               Source|   |Content
                               Files |   |Objects
                                     |   |
                                     |   v
+---------------+            +-------+---+-------+             +---------------+            +--------------+
|               |            |                   |             |               |            |              |
|               |            |                   |             |               |            |              |
|    Pelican    +----------->+     Generators    +------------>+    Writer     +----------->+    Output    |
|               |   Config   |                   |   Context   |               |    HTML    |              |
|               |            |                   |             |               |    Feed    |              |
+---------------+            +-------------------+             +---------------+    Static  +--------------+
```
In words:
* `pelican` starts by initializing `Generator`s and a `Writer`
* `generate_context` is called on generators that would then collect `Content` objects and populate context. Usually it is finding the relevant source files from file system and passing them to the `Reader`s to obtain content objects. But essentially, `Generator` is free to do whatever it wants for creating the context.
* `generate_output` is called on generators passing the `Writer`. `Generator` will now use the `context` created and pass relevant bits (template, content objects, static files, etc..) to `Writer` to create output.
* Done

**Comment by epogrebnyak** [comment]
@avaris, thank you so much for the flow explianation and the chart in particular (what did you use for ascii-art?) 

I understand [generators](https://github.com/getpelican/pelican/blob/e87717d27c8689ae288d1ab244648f38d20e3ddf/pelican/generators.py) are central to pelican operation.

Is any version of https://docs.getpelican.com/en/stable/internals.html#overall-structure welcome (PR or here) or do you prefer the existing version?

**Comment by avaris** [comment]
It is hard for me to judge what could use more information or what would be confusing to someone who is not as familiar. I know too much I guess :). If you're willing to write a PR to add more details, sure it is always welcome.

PS: I started with [asciiflow](http://asciiflow.com/) and hand curated the output a little.

**Comment by justinmayer** [comment]
@epogrebnyak: Do you need any other assistance related to this issue?

**Comment by epogrebnyak** [comment]
Got all questions answered for me. Can close if you prefer.

I'm planning a writeup for the Pelican documentation, based on the answers,
but can do PR for closed issue.

пн, 22 июн. 2020 г. в 17:21, Justin Mayer <notifications@github.com>:
