### ISSUE TITLE
end-up with many identical index[N].html

### ISSUE THREAD

**Issue by psychonaute** [getpelican/pelican#2769]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **windows 10**: 
- **Python 3.8.3**: 
- **Pelican 4.2.0**: 
- **Plugins: 'i18n_subsites', 'subcategory', 'sitemap',**: 

## Issue
both:
- invoke build
- pelican content -s pelicanconf.py

create **22 identical** index.html files named index[N].html

any know issues? or did something wrong somewhere along the way?

**Comment by justinmayer** [comment]
No known issues of that sort that I am aware of. Chances are good it's something in your settings file or related to plugins. As noted in the [How to Get Help](https://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation, have you tried without any plugins enabled? Have you run `pelican-quickstart` in order to generate a fresh `pelicanconf.py` settings file and used that to generate your site?

**Comment by psychonaute** [comment]
I did just that and still multiple version of index.html, author\author.html, few other custom template. Some have 22 some only 2 or 4. is there a cache i could try flush or something?

**Comment by justinmayer** [comment]
So you are getting index2.html, index3.html, etc? If you have many posts, categories, etc., then what you’re seeing is totally normal and expected behavior. That is the result of pagination.

**Comment by psychonaute** [comment]
Right! Indeed with a fresh `pelicanconf.py` it works as expected. Now I'll investigate why the different pagination files have all identical content when I use my template/plugins...

**Comment by avaris** [comment]
@psychonaute here is a guess: you're using full list of articles (`articles`) instead of page ones (`articles_page`) in your template. So, even though you have pages, you populate all pages with everything.

**Comment by psychonaute** [comment]
yeah that was it! The template I forked haven't been designed for pagination. Çok tesekur @avaris

**Comment by avaris** [comment]
Glad it was fixed :).
