### ISSUE TITLE
{filename} {static} and such unexpanded in article title pictures

### ISSUE THREAD

**Issue by githubgilhad** [getpelican/pelican#2776]
I use autocompleting filenames in editor, so I would like use {filename} {static} or something similar in images followed relative path to image. It works inside article body, but not in article title. 

I use icons in titles (mainly on the start) as kind of category indication (or like other mark - star, bomb, shocking, nice ...) so i have lot of such emoticons and logos in one shared directory (/logos) and my titles are like "|bomb| |happy| It really worked !! |smile|"

I did read  **contributing guidelines**, I did clone actual version, added **logos/logo.png** and **cat1/test.rst** generated output as described and the problem persists

---

ISSUE:
-------------
content/cat1/test.rst

```
.. |logo| image:: {static}../logos/logo.png

The static here - |logo| - is unexpanded
################################################################################

:tags: tag1,tag2

some title - |logo| - is OK
-------------------------------------------------
The static here - |logo| - is OK

```
generates HTML file (the-static-here-is-unexpanded.html) with this fragments

```
<h1>...The static here - <img alt="logo" src="{static}../logos/logo.png" /> - is unexpanded</a></h1>
<h2>some title - <img alt="logo" src="/logos/logo.png" /> - is OK</h2>
The static here - <img alt="logo" src="/logos/logo.png" /> - is OK</p>
```

EXPECTED:
-------------------

```
<h1>...The static here - <img alt="logo" src="/logos/logo.png" /> - is OK</a></h1>
<h2>some title - <img alt="logo" src="/logos/logo.png" /> - is OK</h2>
The static here - <img alt="logo" src="/logos/logo.png" /> - is OK</p>
```
---

If I change  the definition in the file into 
`.. |logo| image:: /logos/logo.png
`
then correct code is generated as no {static} is present, but that makes {static} meaningless.

I still think, that it should work with {static} too ...

```
pelican --version
4.2.0

```

**Comment by avaris** [comment]
See #2360

**Comment by avaris** [comment]
On a tangentially related note and maybe a suggestion for your workflow: I'd use an icon font for all those common images and handle this with CSS.

**Comment by justinmayer** [comment]
@githubgilhad: If this issue is something you would like to work on implementing, by all means please comment here and we can re-open the issue. Cheers!
