### ISSUE TITLE
keywords not in page object when keywords defined in HTML meta tag

### ISSUE THREAD

**Issue by marcus-clements** [getpelican/pelican#2778]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

From the documentation I understood that keywords in the HTML meta tag should be available to the page template. 
If I have this in my HTML content (e.g. legal.html):
`<meta name="keywords" content="legal, intellectual property, terms of use, data, GDPR" />`
Then I'm expecting them to be available in a template using `{{ page.keywords }}` 
e.g in page.html
`<meta name="keywords" content="{{ page.keywords|striptags|escape }}" />`

Keywords are coming through fine from pages Markdown format, but not in pages in HTML format.

Am I missing a setting or doing something wrong? Thanks in advance.

**Comment by bryanbrattlof** [comment]
Hi @marcus-clements:

You're right about being able to use both `keywords` or `tags` in the HTML content. So these two lines mean the same thing:

```html
<meta name="keywords" content="legal, intellectual property, terms of use, data, GDPR" />
<meta name="tags" content="legal, intellectual property, terms of use, data, GDPR" />
```

However, these will only be availabe in the template using `{{ page.tags }}`. So you example should look like this:
```jinja
<meta name="keywords" content="{{ page.tags|striptags|escape }}" />
```

Let me know if this helps!

**Comment by avaris** [comment]
`keywords` is an alias to `tags` for HTML content. `pelican` understands both as `tags` metadata. This is covered in the [docs](https://docs.getpelican.com/en/stable/content.html#file-metadata)

>With HTML, there is one simple exception to the standard metadata: tags can be specified either via the `tags` metadata, as is standard in Pelican, or via the `keywords` metadata, as is standard in HTML. The two can be used interchangeably.

**Comment by marcus-clements** [comment]
Thanks for the clarification
