### ISSUE TITLE
Generate permanent ID to each article even the article is changed

### ISSUE THREAD

**Issue by jackieveev** [getpelican/pelican#2781]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I want something like ID to each article to follow the changes of articles(like the comments, votes etc.), now seems like to use slug as an unique flag but its tedious because it will change every time when the title was changed.It also not cool If I do it manually.I try to do it with plugin but it seems hard to do such work, any suggestions please?

**Comment by avaris** [comment]
What is the hard part for a plugin?

**Comment by jackieveev** [comment]
> What is the hard part for a plugin?

there is no file ID or something useful of each md file in the content directory, I'm confused how to give them an ID, or just write someting to the md file everytime when I rebuild?

**Comment by jackieveev** [comment]
Now I use plugin to detect md file if it has a Slug row, not a perfect solution but works well, hope it will be helpful if someone has the same issue.
```python
def add_uuid_slug(pelican):
    for root, dirs, files in os.walk(pelican.path):
        for file in files:
            if (file.endswith('.md')):
                with open(os.path.join(root, file), 'r+') as f:
                    data = f.readlines()
                    for line in data:
                        if line == '\n':
                            f.seek(0)
                            data.insert(0, 'Slug: {}\n'.format(uuid.uuid4().hex))
                            f.writelines(data)
                            break
                        if line.startswith('Slug:'):
                            break

def register():
    signals.initialized.connect(add_uuid_slug)
```

**Comment by justinmayer** [comment]
@jackieveev: Glad you found an appropriate solution. Many thanks for sharing the code — much appreciated! ✨
