### ISSUE TITLE
"Template pages" link links to same section

### ISSUE THREAD

**Issue by jwodder** [getpelican/pelican#2784]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

[In the "Settings" page of the docs, under "Template pages"](https://docs.getpelican.com/en/stable/settings.html#template-pages), the description of the first setting begins:

> A mapping containing template pages that will be rendered with the blog entries. See Template pages.

"See Template pages" is a link, but it links to the very same "Template pages" section that the link is located in (barely even moving the page), and this section contains no information on what "template pages" actually are.

**Comment by justinmayer** [comment]
Thanks for catching this, John. I removed the self-referential link via d2bbfd96. As for what template pages are, I'm going to leave that for someone else to address and submit in a pull request. Volunteers welcome.
