### ISSUE TITLE
Pip installation problem

### ISSUE THREAD

**Issue by cmcknight** [getpelican/pelican#2786]
<u>Environment</u>
Computer: iMac
Operating System: MacOS 10.15.6 (19G73)
Python Version: 3.8.5 (from python.org)
Pip Version 20.2.1

<u>Steps To Reproduce</u>
1. Installed Python 3.8.5 from python.org.
2. Created subdirectory for test site.
3. Changed to subdirectory for test site.
4. Created Python 3 virtual environment (python3 -m venv venv)
5. Activated virtual environment (source venv/bin/activate)
6. Upgraded pip (pip install --upgrade pip)
7. Attempted to install pelican (pip install pelican[Markdown])

Received error message from pip:  "no matches found pelican[Markdown]".

<u>Workaround</u>
1. Installed Pelican separately (pip install pelican)
2. Installed Markdown separately (pip install Markdown)

**Comment by avaris** [comment]
I did a quick test on Ubuntu with python 3.8.2 and everything seems fine (see below). I'll try to replicate your setup when I have time.

```console
$ pip install -U pip
[skip...]
Successfully installed pip-20.2.1
$ pip install pelican[Markdown]
[skip...]
Successfully installed MarkupSafe-1.1.1 blinker-1.4 docutils-0.16 feedgenerator-1.9.1 jinja2-2.11.2 markdown-3.1.1 pelican-4.2.0 pygments-2.6.1 python-dateutil-2.8.1 pytz-2020.1 six-1.15.0 unidecode-1.1.1
$ python -V
Python 3.8.2
```

**Comment by justinmayer** [comment]
I can't replicate this either, using macOS 10.13.6 + Python 3.8.5 + Pip 20.2.1, so I don't think there is anything wrong with the documentation. As a workaround, you can instead try installing via: `pip install pelican markdown`

**Comment by jwodder** [comment]
I believe this is an issue with your shell and quoting.  Your shell is interpreting `pelican[Markdown]` as a glob pattern for matching against a file named "pelican" plus one of the characters in "Markdown", and it couldn't find a match for that pattern.  Due to how your shell is configured (Do you have the "failglob" setting on?), it then errored out; note that some shells, depending on configuration, would instead react to the failure by treating "pelican[Markdown]" literally.

The correct way to handle this is to quote the argument: `pip install 'pelican[Markdown]'`

**Comment by cmcknight** [comment]
Hmm, I’m running zsh and hadn’t noticed that. 

Thanks!

**Comment by justinmayer** [comment]
@avaris: In our docs, is there any reason to recommend `pip install pelican[markdown]` instead of `pip install pelican markdown`? Just wondering if that might reduce the likelihood of problems like this occurring.

**Comment by justinmayer** [comment]
Since this might be an isolated incident, let's wait until we get at least another similar report before making a change.

**Comment by cmcknight** [comment]
Hi,

If you plan on keeping installation with pip, I’d suggest putting the quotes around pelican[Markdown]. Otherwise I would suggest changing the docs to reflect installing Markdown as a separate item.

Regards,

Charles

**Comment by justinmayer** [comment]
@cmcknight: I added quotation marks around the `pip install` commands via: 863421b
