### ISSUE TITLE
make devserver failing

### ISSUE THREAD

**Issue by cmcknight** [getpelican/pelican#2787]
<u>Environment</u>
Computer: iMac
Operating System: MacOS 10.15.16
Python Version: 3.8.5
Pip Version: 20.2.1

<u>Step to Reproduce</u>
1. Ran pelican-quickstart
2. Attempted to make devserver (make devserver)

Received error message:

"pelican -lr /Users/chuck/mysites/senestone/content -o /Users/chuck/mysites/senestone/output -s /Users/chuck/mysites/senestone/pelicanconf.py
CRITICAL: TypeError: cannot pickle 'generator' object
make: *** [devserver] Error 1

**Comment by davidag** [comment]
This seems to be a known issue on MacOS. Take a look at: https://github.com/getpelican/pelican/issues/2674#issuecomment-603692008

**Comment by avaris** [comment]
Yes, this is a duplicate of #2674 and it is fixed in current master (via #2750).
