### ISSUE TITLE
"Override settings from command line" feature errors when no overrides given

### ISSUE THREAD

**Issue by jwodder** [getpelican/pelican#2789]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- **OS version and name**: macOS 10.13.6
- **Python version**: 3.8.3
- **Pelican version**: master branch, commit 74692a37a64c6f51647427e2a83d37a900bd15b0
- **Theme**: simple
- **Configuration**: https://gist.github.com/jwodder/9e70dce1ba8e3a24742a8870e9067fee

## Issue

After [this commit](https://github.com/getpelican/pelican/commit/1c50a18d0a45d76f6b50647536faf25954740d20) was made, trying to build with the latest development version of Pelican errors out.  Running `pelican -s pelicanconf.py --debug` outputs the following:

```
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.3 
CRITICAL: 'NoneType' object has no attribute 'items'
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/kbits/.nox/build/bin/pelican", line 8, in <module>  
    sys.exit(main())
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 486, in main
    pelican, settings = get_instance(args)
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 395, in get_instance
    settings = read_settings(config_file, override=get_config(args))
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 383, in get_config
    config.update(coerce_overrides(args.overrides))
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/settings.py", line 667, in coerce_overrides
    for k, v in overrides.items():
AttributeError: 'NoneType' object has no attribute 'items'
```

I believe the problem is that `args.overrides` is `None` when no `--extra-settings` arguments are given on the command line.  Attempting to test this theory by adding `--extra-settings AUTHOR=Me` made pelican fail with a different error:

```
DEBUG: Pelican version: 4.2.0
DEBUG: Python version: 3.8.3
CRITICAL: 'AUTHOR'
Traceback (most recent call last):
  File "/Users/jwodder/work/dev/kbits/.nox/build/bin/pelican", line 8, in <module>
    sys.exit(main())
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 486, in main
    pelican, settings = get_instance(args)
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 395, in get_instance
    settings = read_settings(config_file, override=get_config(args))
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/__init__.py", line 383, in get_config
    config.update(coerce_overrides(args.overrides))
  File "/Users/jwodder/work/dev/kbits/.nox/build/lib/python3.8/site-packages/pelican/settings.py", line 671, in coerce_overrides
    setting_type = type(DEFAULT_CONFIG[k])
KeyError: 'AUTHOR'
```

**Comment by justinmayer** [comment]
@sabaini : Any thoughts on this?

**Comment by avaris** [comment]
My bad. Missed some obvious issues in the review. After a quick look, following might be enough to fix. Here: https://github.com/getpelican/pelican/blob/74692a37a64c6f51647427e2a83d37a900bd15b0/pelican/settings.py#L664-L665

this addition
```python
def coerce_overrides(overrides):
    if overrides is None:
        return {}
    coerced = {}
```
And this:
https://github.com/getpelican/pelican/blob/74692a37a64c6f51647427e2a83d37a900bd15b0/pelican/settings.py#L668
changed to:
```python
        if k not in DEFAULT_CONFIG:
```

**Comment by justinmayer** [comment]
Thanks for reporting this, @jwodder. The fix proposed by @avaris seems to resolve the problem in my (admittedly limited) testing, so I just pushed a commit including those changes: https://github.com/getpelican/pelican/commit/45c5cb9029bc2d475ae7440ee1fed3065e353811 Thank you, @avaris! 👏 

Another thing I noticed is that capitalized Boolean values, such as the one I provided as an example in the docs, yield this error:

    CRITICAL: Expecting value: line 1 column 1 (char 0)

Lower-case Boolean values seem to work fine. For the moment, I changed the example in the docs to use a lower-case Boolean value. But it would be nice to fix this properly and help users avoid running into critical errors.

**Comment by justinmayer** [comment]
Changing from:
```python
types_to_cast = {int, str}
```
… to:
```python
types_to_cast = {int, str, bool}
```
… seems to fix the aforementioned error and works with both lowercase and uppercase Boolean values. Anyone see any potentially unforeseen problems with this fix?

**Comment by justinmayer** [comment]
I went ahead and made the above-mentioned Boolean-related change. Despite tests passing locally, GitHub CI is reporting some kind of internal error that I don't understand and that I suspect is unrelated to the small change in the last commit. Maybe related to parallel testing via `pytest-xdist`. Who knows.

@jwodder: Can you test latest master and see whether the first item you reported here has been resolved?

**Comment by jwodder** [comment]
@justinmayer The problem has been resolved.

**Comment by rryan** [comment]
> PS: `-e AUTHOR=Me` will issue a warning and will be ignored, since it's not in `DEFAULT_CONFIG`. Unfortunately, that's the limitation of implementation.

This is pretty limiting since we can't override a user-defined setting. What if in this case we simply delegated to whatever `json.loads` would produce for the value type? If you use `true`, you get a bool, `'true'`, you get a str, etc.

Using the below implementation this is working well for me:
* `-e FOO=true` -> `True`
* `-e FOO=\"true\"` -> `"true"`

```python
def coerce_overrides(overrides):
    if overrides is None:
        return {}
    coerced = {}
    types_to_cast = {int, str, bool}
    for k, v in overrides.items():
        if k not in DEFAULT_CONFIG:
            setting_type = None
        else:
            setting_type = type(DEFAULT_CONFIG[k])
        if setting_type not in types_to_cast:
            coerced[k] = json.loads(v)
        else:
            try:
                coerced[k] = setting_type(v)
            except ValueError:
                logger.debug('ValueError for %s override with %s, try to '
                             'load as json', k, v)
                coerced[k] = json.loads(v)
    return coerced
```
