### ISSUE TITLE
Rename GitHub Pages branch in Invoke tasks.py template

### ISSUE THREAD

**Issue by rsip22** [getpelican/pelican#2790]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I have just quickstarted a new Pelican project and I realized that the "Github Pages configuration" from the fabfile.py is still being set to "master" as a default. Many repositories and organizations have been moving away from this and the [latest version of Git (2.28)](https://github.blog/2020-07-27-highlights-from-git-2-28/) already allows to set up names other than "main" when starting a repository. Even though I know it's possible to go and manually change this setting in the fabfile, it would be awesome if the fabfile generated for new projects had this new setting already. I would be willing to try and help implementing this.

**Comment by justinmayer** [comment]
Many thanks for bringing this up, Renata. I just pushed a change via ade70cb2. Would that do the trick?

**Comment by rsip22** [comment]
Awesome! :tada: 

Thank you for this improvement.
