### ISSUE TITLE
'list' object has no attribute 'replace

### ISSUE THREAD

**Issue by iosonofabio** [getpelican/pelican#2795]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Linux 5.8.3-arch1-1 #1 SMP PREEMPT Fri, 21 Aug 2020 16:54:16 +0000 x86_64 GNU/Linux 
- **Python version**: 3.8.5 
- **Pelican version**: 4.5.0.r0.g0ab6ac97 
- **Link to theme**: https://github.com/Parbhat/pelican-blue 
- **Links to plugins**: https://github.com/mortada/pelican_javascript 
- **Link to your site**: http://fabilab.org 
- **Link to your source**: NA 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: https://gist.github.com/iosonofabio/b6e1bda51f827c672b1079d32ae7ed09 

## Issue

Pelican was working like a charm until today. Today, when I run the devserver I get:

```bash
ERROR: Could not process pages/teaching.md
  | 'list' object has no attribute 'replace'
[... more errors like this]
Done: Processed 0 articles, 0 drafts, 4 pages, 0 hidden pages and 0 draft pages in 0.15 seconds.
```

Because this has worked for half a year, including with python 3.8 for a while, I'm surprised this broke now.

Is this known and would you mind trying to figure out how to fix it? Happy to help.

Cheers,
Fabio

**Comment by avaris** [comment]
Can you run with `DEBUG=1 make devserver` to get the actual traceback?

**Comment by iosonofabio** [comment]
```bash
DEBUG: Read file pages/join.md -> Page
DEBUG: Signal page_generator_preread.send(PagesGenerator)
DEBUG: Signal page_generator_context.send(PagesGenerator, <metadata>)
DEBUG: Read file pages/teaching.md -> Page
ERROR: Could not process pages/teaching.md
  | 'list' object has no attribute 'replace'
  |___
  | Traceback (most recent call last):
  |   File "/usr/lib/python3.8/site-packages/pelican/generators.py", line 721, in generate_context
  |     page = self.readers.read_file(
  |   File "/usr/lib/python3.8/site-packages/pelican/readers.py", line 623, in read_file
  |     context_signal.send(context_sender, metadata=metadata)
  |   File "/usr/lib/python3.8/site-packages/blinker/base.py", line 266, in send
  |     return [(receiver, receiver(sender, **kwargs))
  |   File "/usr/lib/python3.8/site-packages/blinker/base.py", line 266, in <listcomp>
  |     return [(receiver, receiver(sender, **kwargs))
  |   File "/home/fabio/university/PI/fabilab/fabilab/pelican-plugins/pelican_javascript.py", line 48, in add_files
  |     files = metadata[key].replace(" ", "").split(",")
  | AttributeError: 'list' object has no attribute 'replace'
DEBUG: Read file pages/contact.md -> Page
```

and similar for other markdown pages

**Comment by avaris** [comment]
I don't remember any such change that would result in this kind of error. Can you show metadata section of a failing page?

**Comment by iosonofabio** [comment]
Here the top of the markdown, including the first line of actual page content:

```markdown
title: Teaching
slug: teaching
category: pages
date: 2020-03-23
order: 3
javascripts: d3.min.js


# Lectures
```

**Comment by avaris** [comment]
That all looks fine actually. I don't see any reason plugin would receive a `list` at that point. I even copied your metadata to make a page and tested with the plugin using pelican 4.5.0. No error. If your source is available publicly I can try with that. If you're willing to debug, you could try adding some `print(metadata)` at the start and end of [this function in the plugin](https://github.com/mortada/pelican_javascript/blob/58e7335e5f5fa0acc945425c2d12bf9dcadb150f/pelican_javascript.py#L36) and see what is passed.

**Comment by iosonofabio** [comment]
Thanks for doing all that work. I actually don't need the plugin 100% yet. So I'll close the issue for now and then do some testing as soon as I find time and reopen if it is still there.
