### ISSUE TITLE
Custom links to Navigation bar

### ISSUE THREAD

**Issue by manojap** [getpelican/pelican#2796]
###  A customizable Navigation links
I am using Pelican with Elegant theme, I found that the top nav bar not customizable. Make a config variable could be 
full fill my needs,
I do the following

#### Created a config variable
`OTHER_WEB_PRECENSES=[{
    'name': 'Blog',
    'url': 'https://developermblog.wordpress.com'},]`

#### Update the base template
`       {% if OTHER_WEB_PRECENSES %}
                                {% for w in OTHER_WEB_PRECENSES %}
                                <li > 
                                    <a href="{{ w.url }}" target="_blank"> {{ w.name }}</a>
                                </li>
                                {% endfor %}
                                {% endif%}`

I think this feature will help others

**Comment by justinmayer** [comment]
Hi Manoj. As far as I can tell, what you describe is already provided by the [`MENUITEMS`](https://docs.getpelican.com/en/latest/settings.html#MENUITEMS) setting. As such, I'm closing this issue. Cheers!
