### ISSUE TITLE
ChangeLog for 4.5.0 mentions SUMMARY_END_MARKER instead of SUMMARY_END_SUFFIX

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2798]
There was a discussion that SUMMARY_END_MARKER was clashing with the summary plugin, so #2792 has been merged that renamed that configuration variable, yet the changelog mentions the old (unreleased) name.

**Comment by justinmayer** [comment]
Fixed via 7a6686f4. Many thanks for the heads-up!
