### ISSUE TITLE
Pelican implementation

### ISSUE THREAD

**Issue by dbwest1** [getpelican/pelican#2801]
Hi, new to Python/Pelican...trying to find some support for a tech issue...

If not right place, please redirect me.  Thanks.

- [ x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Hi, I am new to Python / Pelican and whilst making progress, I have the following error when compiling the site… … Any advice / assistance would be greatly appreciated.

ERROR: Cannot load plugin …

Please see link for screen/pelicanconf.py/pubishconf.py for more details.
 https://drive.google.com/file/d/11sB_dOvAEfSgIak8xLWoSemCaEq3OqH-/view?usp=sharing

I've ran the pip install -r requirements.txt, to install the plugins.

Best regards, D.

**Comment by justinmayer** [comment]
The configuration files in this issue contain links to a rash of ridiculous conspiracy hoaxes. I am deeply saddened by the realization that Pelican might be used to publish such disinformation campaigns, and we certainly will not abet them by providing support.
