### ISSUE TITLE
Tags with numbers conflict with existing paginated tags without numbers but same prefix

### ISSUE THREAD

**Issue by andreagrandi** [getpelican/pelican#2806]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: MacOS / Linux
- **Python version**: 3.8.1
- **Pelican version**: 4.5.0
- **Link to theme**: custom Flex https://github.com/andreagrandi/andreagrandi.it/tree/master/themes/Flex
- **Links to plugins**: https://github.com/andreagrandi/andreagrandi.it/tree/master/plugins
- **Link to your site**: https://www.andreagrandi.it/
- **Link to your source**: https://github.com/andreagrandi/andreagrandi.it
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**:

## Issue

When you use tags, pelican generate multiple pages for the same tag (and until here it's fine). When you use the same tag in many pages, multiple tag pages are generated.

Example: `python` tag
Pelican generates `tag/python1.html`, `tag/python2.html`, `tag/python3.html`, etc.... (because I'm using the tag `python` in many posts, so Pelican generates multiple pages for that tag).

At this point, if you create a post with tag `python3` there is a conflict with the existing pagination for `python` tag and you get this error:

```
(andreagrandi.it) ➜  andreagrandi.it git:(change-title-pyenv) pelican content
CRITICAL: File /Users/andrea/Projects/andreagrandi.it/output/tag/python3.html is to be overwritten
```

Page 3 of `python` tag (`tag/python3.html`) conflicts with `python3` tag (`tag/python3.html`).

Workaround: just by removing `python3` from my latest post tags, fixes the problem and nobody tries to override `tag/python3.html`

**Comment by avaris** [comment]
Well, this is not a bug. Also a duplicate of #2754 .

**Comment by andreagrandi** [comment]
> #2754

Sorry, I tried to look for it but I couldn't find. I must have searched in the wrong way 😓
I'm going to read that one, thanks.

**Comment by andreagrandi** [comment]
Closing this one and commenting on the other issue, thanks again
