### ISSUE TITLE
Centralization of media/images from all articles' subdirectory of images.

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2809]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request
I have been using the content subdirectory approach where content files are stored in its own subdirectory:
```
content
  |-+ articles
    |-+ how-to-fix-things
       |- how-to-fix-things.md
       |-+ images
          |- exploding-cutaway.png
          +- overview.png
```
In the past, I wanted a feature to output these subdirectories as is, images being under its own content's subdirectory.  But the latest vanity website providers seem to be putting an end to this, hence this new feature request.

Since the newer security design for a secured website is becoming more and more based on latest Content-Security-Policy that are pushing toward separation of images/media from HTML/text...
```
Content-Security-Policy
  default-src 'none'; 
  base-uri 'none';
  script-src 'strict-dynamic';
  img-src https://website.home/favicon.ico https://website.home/images/ https://website.home/blog/ data:;
  media-src https://website.home/media/ data:;
  font-src https://website.home/fonts/;
  sandbox allow-same-origin;
```

I have to relocate all image fles into a single image subdirectory (and same thing for media, fonts, and script) for the purpose of complying with this centralized part of content policy control.  Oh, did I mention that people who sign up for this newer vanity websites won't be able to issue these CSPs so we're being herded into single-subdir approach now.

That being said, need to relocate the all media and images into their respective centralized subdirectory (of the provider's choice) of the OUTPUT directory.

**Comment by jorgesumle** [comment]
> need to relocate the all media and images into their respective centralized subdirectory (of the provider's choice) of the OUTPUT directory.

So why is this an issue with Pelican? You can adapt it to your needs, can't you?

**Comment by egberts** [comment]
How would one separate the images into a centralized image subdirectory and videos into a centralized video subdirectory ... outside of the OUTPUT directory.?

**Comment by avaris** [comment]
What do you expect `pelican` to do here?

**Comment by egberts** [comment]
Take several new settings:

* `OUTPUT_SUBDIR_IMAGES`
* `OUTPUT_SUBDIR_MEDIA`
* `OUTPUT_SUBDIR_FONTS`

and maybe 
* `OUTPUT_SUBDIR_SCRIPTS`

**Comment by avaris** [comment]
Why not organize your files inside `content` folder to match your desired output structure?

**Comment by egberts** [comment]
That is certainly a most doable option  (of matching content folder to the desired output structure).

It's a shame that I've been some 25 years in the making of using subdirectory to hold all images associated with a content (document) file.   And that model works well for me when it comes to finding images associated with a doc.

Now, I must change.... somehow.

;-P

**Comment by avaris** [comment]
I don't think this belongs in the `pelican` core. You can make a plugin if you want: going through `Static` files and setting `override_save_as/override_url` attributes matching the output structure should do it.

I have to mention that some of these are not feasible or easy:
* As far as pelican is concerned these are all "files". It doesn't know if content of that file is image, video, text, archive, etc... So that classification is not that trivial.
* Fonts and scripts are generally managed by themes and templates would almost certainly expect them in predetermined locations. Randomly relocating those would be a sure way to break a theme.

**Comment by egberts** [comment]
Interesting... perhaps ...
For CSP `media-src`, these are easily denoted as HTML `<video>...</video>` or `<audio>...</audio>` tag element.
For CSP `script-src`, this is easily denoted as `<script>...</script>` tag velement.
For CSP `image-src`, perhaps we can use `<img=` tag element to catch those.

Offtopic: I was investigating a design to devise a Pelican plugin for auto-stamping `<script ...>` with a `nonce` hash value of selectable algorithm (ie., `sha256`, `sha386`, or `sha512`) until the vanity website came with a plan to throw a proverbial monkeywench into my scheme.
