### ISSUE TITLE
Absolute path is not built for OUTPUT_PATH setting when not set in pelicanconf.py

### ISSUE THREAD

**Issue by MaevaBrunelles** [getpelican/pelican#2814]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: macOS Mojave 10.14.6
- **Python version**: 3.8
- **Pelican version**: 4.5

## Issue
**Context:**
I encounter an issue on [my plugin](https://github.com/pelican-plugins/seo) here: https://github.com/pelican-plugins/seo/blob/master/pelican/plugins/seo/seo_enhancer/html_enhancer/breadcrumb_schema_creator.py#L32
This line fail if `OUTPUT_PATH` setting is not set in `pelicanconf.py`, but it does not fail if the setting is set.
To understand why, I've created a new project thanks to `pelican-quickstart`. I did not install any plugins (neither mine). I put a breakpoint in Pelican [here](https://github.com/getpelican/pelican/blob/master/pelican/__init__.py#L397) when Pelican is instancied and has build all the settings.

**Problem:** 
I run twice `pelican content`, and print the setting when the breakpoint run.
First without any `OUTPUT_PATH` in `pelicanconf.py` (so default was filled by Pelican), here is the result:
```
-> settings['OUTPUT_PATH']
'output'
````

Second with `OUTPUT_PATH = 'output'` in `pelicanconf.py`, here is the result:
```
-> settings['OUTPUT_PATH']
'/Users/mbrunell/Documents/Dev/pelican-seo/sandbox/output'
````

**Exceptation:**
I would except to have the absolute path in both case.

**Proposed solution**:
I think it's missing a condition somewhere [here](https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L175) to handle the case: if dealing with default `OUTPUT_PATH`, then add it to `settings` variable. Thus, [this condition](https://github.com/getpelican/pelican/blob/master/pelican/settings.py#L190) will handle it and will get the absolute path for default `OUTPUT_PATH`.

What do you think?

**Comment by avaris** [comment]
> I think it's missing a condition somewhere here to handle the case: if dealing with default OUTPUT_PATH, then add it to settings variable. Thus, this condition will handle it and will get the absolute path for default OUTPUT_PATH.

Not exactly. That's when you a settings file is specified and paths are made absolute with respect to that file. If no settings was given, it essentially uses current working directory. I am not opposed to making it absolute, just that it won't be the way you proposed :).

That being said, is there a reason you don't use `Path` instead of `PurePath` and `.resolve()` it beforehand? That should give you an absolute path in any case.

**Comment by justinmayer** [comment]
Relevant docs: https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve

**Comment by kdeldycke** [comment]
> That being said, is there a reason you don't use Path instead of PurePath and .resolve() it beforehand? That should give you an absolute path in any case.

Agreed. I think that's the way to go too. I proposed that change here: https://github.com/pelican-plugins/seo/pull/15/files

**Comment by MaevaBrunelles** [comment]
> That's when a settings file is specified and paths are made absolute with respect to that file.

Whether I specify or not a setting file, I get the same result. It seems that the behaviour I described only applies to the `OUTPUT_PATH` setting. 

If `OUTPUT_PATH` is filled with the default value `"output"`, Pelican returns a relative path.
If `OUTPUT_PATH` is explicitly filled in `pelicanconf.py` with the same value `"output"`, Pelican returns an absolute path.

IMHO, Pelican should be consistent and give the same output for the same input, which it is not doing here.

> That being said, is there a reason you don't use Path instead of PurePath and .resolve() it beforehand?

I use PurePath because my plugin does not need to access the filesystem, it just needs to handle paths. While using `Path.resolve()` would work, it would make the plugin access the filesystem to find the output folder, something that is already done by Pelican for other cases.

In my point of view, a plugin should be not affected by the way that Pelican is called or the settings are provided.

I don't really expect an _absolute_ path for both case, I'm just expecting a consistent value.

**Comment by avaris** [comment]
Yes, that's what I was trying to say. If you specify paths in your config, they are made absolute with respect to the settings path. If you omit them, they default to current working directory. That applies to all path related settings (listed [in this line](https://github.com/getpelican/pelican/blob/e4d9c41a77b45cb7ff6b8d1732623990adf65931/pelican/settings.py#L189)), not just `OUTPUT_PATH`.

It could be argued that this is inconsistent (and I would *partially* agree): i.e. setting `OUTPUT_PATH = 'output'` in settings file or not essentially changes resulting folder. So, making it to be absolute with respect to config file (if specified) always could be considered (what you solution proposes basically). But that is kind of a different behavior to previous and thus a breaking change.

Not to mention, this does not cover the case where no settings file was given.

> I use PurePath because my plugin does not need to access the filesystem, it just needs to handle paths. While using Path.resolve() would work, it would make the plugin access the filesystem to find the output folder, something that is already done by Pelican for other cases.

> In my point of view, a plugin should be not affected by the way that Pelican is called or the settings are provided.

Ideally yes, but also no. You're dealing with paths generated outside of your code (i.e. you don't have full control over how they are structured). It would be better to err on the side of caution and normalize them. Even if `pelican` made them consistent and absolute always, there is no guarantee that another plugin would not change them to something different.

**Comment by MaevaBrunelles** [comment]
> there is no guarantee that another plugin would not change them to something different.

I find weird that plugins can modify settings, but maybe it's relevant in some case, I don't know. I reckon that a child (plugin) should be able to trust what it receives from his parent (Pelican), otherwise we (plugin dev) have to check any Pelican output each time when it could be centralized.

But I understand it'll represent a breaking change, so I'll use the workaround you proposed. Thanks for your detailed answers :)

I let you decide what to do with this issue, if you want to close it or keep it for a future Pelican version.

**Comment by avaris** [comment]
[As I said in another issue](https://github.com/getpelican/pelican/issues/2678#issuecomment-571362010), path handling is currently a little messy. We should switch to `pathlib` from plain strings and this issue would probably be handled in that effort as well. I just need to find some time to work on it. Or, a kind soul could volunteer :).

> I find weird that plugins can modify settings, but maybe it's relevant in some case, I don't know. I reckon that a child (plugin) should be able to trust what it receives from his parent (Pelican), otherwise we (plugin dev) have to check any Pelican output each time when it could be centralized.

You can trust that it is a valid value, otherwise things would probably break even before it hits your plugin. But my advice was mostly limited to paths, and specifically when you're comparing them. You generally *should* normalize them to be on the safe side, especially if you're getting them from outside. That can be true even if everything was handled in the same code base as well, the issue I linked at the start is probably caused by this.
