### ISSUE TITLE
Generic metadata names

### ISSUE THREAD

**Issue by daturkel** [getpelican/pelican#2819]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

There are certain pieces of metadata that exist across template types, but which (I think) can only be accessed in a template by prepending the correct object. In particular, there's no way I can write a base template which references `title` and have the page template know this means `page.title` and the article template know this means `article.title`.

Is there a workaround for this? It would be nice if there were a generic metadata object that can be used across template types. E.g. `{{ meta.title }}` would find the `title` value in the metadata regardless of whether we're in the page template or article template, etc.

**Comment by avaris** [comment]
Why do you need a workaround? Jinja has a powerful [template inheritance system](https://jinja.palletsprojects.com/en/2.11.x/templates/#template-inheritance) which allows you to [override](https://github.com/getpelican/pelican/blob/e4d9c41a77b45cb7ff6b8d1732623990adf65931/pelican/themes/simple/templates/page.html#L4) blocks from [parent templates](https://github.com/getpelican/pelican/blob/master/pelican/themes/simple/templates/base.html#L5).

**Comment by daturkel** [comment]
> Why do you need a workaround? Jinja has a powerful [template inheritance system](https://jinja.palletsprojects.com/en/2.11.x/templates/#template-inheritance) which allows you to [override](https://github.com/getpelican/pelican/blob/e4d9c41a77b45cb7ff6b8d1732623990adf65931/pelican/themes/simple/templates/page.html#L4) blocks from [parent templates](https://github.com/getpelican/pelican/blob/master/pelican/themes/simple/templates/base.html#L5).

In my particular case, it's a slightly more complex setup. For instance, I have this nav block:
```
{% block nav %}
  <nav>
    <ul>
      {% for nav_page in NAV_MENU %}
      {% if nav_page.url == #### %}
      <li class="active"><mark><a href="{% if not nav_page.ext %}{{ SITEURL }}/{% endif %}{{ nav_page.url }}">{{ nav_page.title }}</a></mark></li>
      {% else %}
      <li><a href="{% if not nav_page.ext %}{{ SITEURL }}/{% endif %}{{ nav_page.url }}">{{ nav_page.title }}</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock nav %}
```

The `####` represents the part that I'd like to dynamically fetch the correct `url` (`article.url` or `page.url` in this case). I *think*, to be able to override the value of `####`, the smallest block I could make here would have to include at least from the opening if block to the closing endif block. I don't believe you could have _just_ an if statement in a jinja block.

Maybe the proper method to handle this would be to have an [assignment statement](https://jinja.palletsprojects.com/en/2.11.x/templates/#assignments) inside an overridable block.
```
# base.html
{% block context %}
{% endblock context %}
{% block nav %}
  <nav>
    <ul>
      {% for nav_page in NAV_MENU %}
      {% if nav_page.url == context.url %}
      <li class="active"><mark><a href="{% if not nav_page.ext %}{{ SITEURL }}/{% endif %}{{ nav_page.url }}">{{ nav_page.title }}</a></mark></li>
      {% else %}
      <li><a href="{% if not nav_page.ext %}{{ SITEURL }}/{% endif %}{{ nav_page.url }}">{{ nav_page.title }}</a></li>
      {% endif %}
      {% endfor %}
    </ul>
  </nav>
{% endblock nav %}
```

```
# page.html
{% block context %}
{% set this = page %}
{% endblock context %}
```

**Comment by avaris** [comment]
For what it's worth, you can also do this somewhere in your base:

```
{% if article %}
  {% set content=article %}
{% else if page %}
  {% set content=page %}
{% end if %}
```
then your condition can be
```
{% if content and content.url == nav_page.url %}
```

**Comment by daturkel** [comment]
That fits my use-case perfectly, thanks!

**Comment by daturkel** [comment]
Closing because an alternative was provided
