### ISSUE TITLE
pygments version riquired <2.7.0, current version is 2.7.2

### ISSUE THREAD

**Issue by verga** [getpelican/pelican#2820]
- [x ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [ x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: linux opensuse tumbleweed version N/A kernel 5.9
- **Python version**: 3.8.5
- **Pelican version**: 4.5.1
- **Link to theme**: custom
- **Links to plugins**: math
- **Link to your site**: verga.cpt.univ-mrs.fr
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

``pelican`` command send Error:

    pkg_resources.DistributionNotFound: The **'pygments<2.7.0,>=2.6.1'** distribution was not found and is required by pelican

My installed version is effectively **pygments==2.7.2**; I think that a dependency on a specific (old) version of a package is a bug.

Thanks!

**Comment by avaris** [comment]
No, it's not a bug to have limitations on the versions of a dependency. [Using virtual environments](https://docs.getpelican.com/en/latest/install.html#installing-pelican) is recommended to avoid clashes between dependencies for different applications, precisely for this reason.

**Comment by verga** [comment]
OK, thank you!

**Comment by justinmayer** [comment]
@avaris is right. Pygments is pinned to a specific version because otherwise it causes things to break unexpectedly. Case in point: tests currently fail on Pygments v2.7.2. Pull requests to address that would be welcome! 😁
