### ISSUE TITLE
Controlling drafts from the command line

### ISSUE THREAD

**Issue by Holzhaus** [getpelican/pelican#2827]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

It would be great if drafts could be controller via command line flags:
- using `pelican --drafts=publish` could display draft articles like regular posts (treat drafts exactly like non-drafts)`
- using `pelican --drafts=ignore` could completely ignore drafts (not even create a `drafts` directory)

Some background why this is useful:
- We're using a git-based workflow (Articles are submitted via GitHub Pull Requests). Because it's not feasible to always update the `date:` metadata field all the time in each PR, we just leave the field unset and use `status: draft` instead. After merge, we have a GitHub Actions workflow that automatically removes the draft status, updates the `date:` field to the commit date of the merge commit and then commits that change.
- We use Netlify's "deploy previews" that build a preview of the website for each pull request. Here, `pelican --drafts=publish` would be useful so see how the website would look if the new post was not a draft.
- For production deploys, it would be convenient to use `pelican --drafts=ignore` to avoid drafts from ever getting published. For now, we use a custom script that just runs `rm -rf output/drafts` after build.

**Comment by avaris** [comment]
Can I suggest writing a plugin? It should be relatively straightforward to do this with a plugin.

**Comment by Holzhaus** [comment]
I can look into it if you consider my use case too esoteric to integrate such a flag into pelican itself 😉

**Comment by avaris** [comment]
Maybe slightly esoteric 😄. We could integrate it into pelican if there is enough interest, but I tend to lean towards keeping core small and delegate tasks that can be done by plugins to, well, plugins. It is usually easier to maintain two (somewhat) isolated pieces of code rather than one interconnected blob.

**Comment by Holzhaus** [comment]
I know this is a bug tracker, but how can I read the command line arguments passed to pelican from a plugin?

**Comment by justinmayer** [comment]
> Because it's not feasible to always update the date: metadata field all the time in each PR […]

It seems to me you could set `DEFAULT_DATE = 'fs'` and skip this entire process. In fact, doing so would appear to obviate the need for all the other functionality mentioned in the issue description, but perhaps that's just my perspective… 🤷‍♂️

**Comment by Holzhaus** [comment]
> > Because it's not feasible to always update the date: metadata field all the time in each PR […]
> 
> It seems to me you could set `DEFAULT_DATE = 'fs'` and skip this entire process. In fact, doing so would appear to obviate the need for all the other functionality mentioned in the issue description, but perhaps that's just my perspective…

If I clone a git repository, the file system timestamp is the *current* date. That would mean that each time the CI clones the git repository and rebuilds the site, all articles would have the current date, not the actual date.

(Also, the naming convention for articles in the repo is `YYYY-MM-DD-slug.md`, so I need the post-merge job to update the filename anyway).

**Comment by justinmayer** [comment]
Huh. I download files from the Internet all the time that retain their timestamps; it didn't occur to me that Git doesn't.

**Comment by Holzhaus** [comment]
In case someone else has this use case as well, here's my plugin:

```python
import datetime
import os

from pelican import signals


def article_generator_context(article_generator, metadata):
    if metadata.get("status") != "draft":
        return

    # This environment variable is set when building a deploy preview on
    # Netlify. We use it to update the draft status of articles to "published",
    # so we get a nice preview. That way we don't have to navigate to the
    # drafts/ directory manually and we can also check that the summary is
    # displayed correctly in the article listing.
    if os.getenv("CONTEXT") != "deploy-preview":
        return

    if "date" not in metadata:
        metadata["date"] = datetime.datetime.now()
    metadata["status"] = "published"


def register():
    signals.article_generator_context.connect(article_generator_context)
```

I didn't find a way to skip writing the drafts directory from a plugin (maybe be overriding `save_as` and setting it to None or something.. need to check.)
