### ISSUE TITLE
Markdown relative includes not working as expected

### ISSUE THREAD

**Issue by danrossi** [getpelican/pelican#2829]
I've followed through from the minimal documentation on markdown content including. The mdx-include config should be picking up relative paths but isn't. 

A config like, it won't see a parent markdown file. 

```
{! path/includes/features.md !}
```

It needs to be

```
{! fullpath/path/includes/features.md !}
```

```

MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'mdx_include': {
            'base_path': "content",
            'recursive_relative_path': True,
            'allow_local': True,
            'allow_remote': True,
            'recurs_local': True,
            'recurs_remote': True
        }
    },
    'output_format': 'html5',
}
```

**Comment by justinmayer** [comment]
Hey @danrossi. I don't have any experience with Python-Markdown's `mdx_include` extension. Were you ever able to resolve this issue?

**Comment by justinmayer** [comment]
Hi Dan. If you have more information about this, by all means please share it here. I'm closing this in the interim.
