### ISSUE TITLE
Writing Plugins: Signal / Variable combination to modify the html of an article before writing it to a file?

### ISSUE THREAD

**Issue by Moini** [getpelican/pelican#2830]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate - actually, I have found an issue from 2015, but it only contains a solution in the form of a script that runs over all articles after they've been written, and I intend to not do it the 'dirty' way.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Hello!

I'm currently updating my (very) old Pelican site, which also features a couple custom plugins, where this still worked (the txt file is a .py file really):

[remove_paragraphs.txt](https://github.com/getpelican/pelican/files/5726358/remove_paragraphs.txt)

This uses the signal `article_generator_write_article` and writes the result into `content._content` to modify the article's html before it is being written (this is not the only plugin I have that needs to do that, it's just the first step in a row - the end goal is to remove paragraphs around image tags, replace all images by figures, detect if they're animated, add some js if they are for controlling the animation, generate thumbnails for animations and videos etc.).

I would also like to be able to modify the article.summary, but Pelican tells me that I can't when I try it, so I had to add a summary_modified attribute (and modifying the images there works). I want to avoid doing that for the articles, in case I need some other, non-customized plugins in the future.

Trying to modify the article's html in the current Pelican version fails to update the article content that is being written out to a file.

Could someone please tell me the signal/variable combination that I need to use to modify the generated html of an article? 

I've also tried with `content_object_init` and modifying content._content, but while that does actually change the contents of the variable, it's also not written out (despite the same thing working with another plugin - the summary one that removes the summary indicators, like SUMMARY_START (or similar)).

As an additional question: Is there a way to set the order of plugins that run after an identical signal? If one depends on the result of another? (okay... maybe by adding a new signal...?)

Thank you for any help that you can give me!

**Comment by MaevaBrunelles** [comment]
Hello @Moini,

> Could someone please tell me the signal/variable combination that I need to use to modify the generated html of an article?

Did you try the `content_written` signal? For [my plugin](https://github.com/pelican-plugins/seo/blob/master/pelican/plugins/seo/seo.py), I use it [to add HTML tags on each generated HTML file](https://github.com/pelican-plugins/seo/blob/master/pelican/plugins/seo/seo_enhancer/__init__.py#L77).

**Comment by Moini** [comment]
Thanks - I've resorted to 'all_generators_finalized'... which works. 

Even though I still cannot change the summary directly (neither with `_summary` nor with `summary`), I can change `_content` there and it's written.

I'm still kind of looking for an explanation about why there is this inconsistency with the summary vs. content, and using which signals it should be possible to edit the content from a plugin, and whether not being able to do so might be a bug.

**Comment by avaris** [comment]
@Moini `.content` and `.summary` are cache-able properties. So accessing them "fixes" their value. Correct way to alter these, is with `._content` or `._summary`. If after modifying these, you don't see any changes in the final output then, yes, something is wrong. My bet would be another plugin, that accesses `.summary` (wrongly) and triggers a cache. I'd suggest removing all other plugins other than the one you are writing, and check if that makes things behave correctly.

**Comment by Moini** [comment]
@avaris Thank you for the explanation!

So, after fixing my own plugin to not access `.summary` for reading (had thought that reading would be uncritical), I searched for the use of `.summary` in all active plugins and didn't find any. 

There is one that accesses _summary (actually, replaces it, the 'summary' plugin). 

My own plugi still doesn't work to change the contents of the summary that I'm using in the template. 

Order of plugins in the configuration file does matter in that it really changes the processing order, but I can only change the `_content` (and change the derived summary along with that), but not the `_summary` explicitly on its own.

As it's kind of cleaner to use a summary that is derived from a changed content, than modifiying content and summary independently from each other, I'll still keep the changes I made. So thanks for helping me improve my code a bit!

**Comment by justinmayer** [comment]
@Moini: Glad the community could be of assistance here. ✨ 

Many thanks to @MaevaBrunelles and @avaris for your input on this topic.

**Comment by TheCrowned** [comment]
@avaris I've stumbled upon a similar issue, and nailed it down to the `clean_summary` plugin, which indeed accesses `.summary` and `.content` (at a time when `._summary` seems available, though). If `clean_summary` is loaded earlier than my own custom plugin, then my plugin's edits to `._content` have no effect. Is this a bug in `clean_summary`, or something I am doing wrong?

**Comment by avaris** [comment]
> Is this a bug in clean_summary?

I'd say so. Granted it's not the best design, but in my opinion (until it changes) plugins should not access `.content` or `.summary` and use `._content` or `._summary`.

**Comment by TheCrowned** [comment]
For a reason I can't understand, `._summary` is not available when the clean summary function runs, while `.summary` is :man_shrugging:
