### ISSUE TITLE
make regenerate vs. pelican -r behave differently, pelican -r sees modifications that are not there

### ISSUE THREAD

**Issue by Moini** [getpelican/pelican#2837]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Linux Mint 20
- **Python version**: 3.8.5
- **Pelican version**: 4.5.3
- **Link to theme**: custom, irrelevant to the issue
- **Links to plugins**: some custom ones, irrelevant here
- **Link to your site**: updated version not public yet
- **Link to your source**: nope, contains private data
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: no, but I'll copy the relevant part here.

## Issue

According to the documentation:
`pelican -r ` is supposed to "Relaunch pelican each time a modification occurs on the content files. (default: False)"

### Problem 1: 

When I use `pelican -r` in my project, it reloads every second, even when there was no modification. Does it maybe monitor the output directory, too? That would be the only explanation I can come up with. On the other hand, `make regenerate` does the right thing and only updates when it's supposed to do so. I'm launching both from the same current directory.

### Problem 2: 

Additionally, `pelican -r` and `make regenerate` seem to look for static files in different places. `make regenerate` takes the `PATH` variable into account (adds '/content/' to the variable set in `STATIC_PATHS`, while `pelican -r` does not add that to the path, so it cannot find the files. 

My directory tree looks like this:

```
.
├── output
│   ├── ...
├── pythonenv
│   ├── bin
│   ├── include
│   ├── lib
├── setup_environment.sh
└── website - THIS IS FROM WHERE I RUN BOTH COMMANDS
    ├── content
    │   ├── articles
    │   │   ├── ...
    │   ├── comments
    │   │   ├── ...
    │   ├── extra - THIS IS ONE OF THE DIRECTORIES WHICH ARE NOT FOUND (1/3)
    │   │   ├── favicon.png
    │   │   └── robots.txt
    │   ├── extra_pages
    │   │   └── ..
    │   ├── files - THIS IS ONE OF THE DIRECTORIES WHICH ARE NOT FOUND (2/3)
    │   │   ├── directory
    │   │   │   └── file
    │   │   ├── ...
    │   ├── images - THIS IS ONE OF THE DIRECTORIES WHICH ARE NOT FOUND (3/3)
    │   │   ├── category
    │   │   │   ├── article_fallback.svg
    │   │   │   └── paper.svg
    │   │   └── identicon
    │   │       └── moini.png
    │   └── pages
    │       ├── ...
    ├── forked_plugins
    │   ├── pelican_comment_system
    │   │   └── ...
    │   ├── remove_paragraphs
    │   │   └── ...
    │   └── tipue_search
    │       └── ...
    ├── Makefile
    ├── output
    │   └── ...
    ├── pelicanconf.py
    ├── plugins
    │   ├── ... (old plugin repository here)
    ├── publishconf.py
    ├── __pycache__
    │   └── ...
    ├── tasks.py
    ├── themes
    │   └── palustra
    │       ├── static
    │       │   ├── css
    │       │   │   └── ...
    │       │   ├── fonts
    │       │   │   └── ...
    │       │   ├── images
    │       │   │   └── ...
    │       │   ├── js
    │       │   │   └── ...
    │       │   └── tipuesearch
    │       │       └── ...
    │       └── templates
    │           └── ...
    └── TODO.md
```

The PATH variable is set to: 
`PATH = 'content'`

The STATIC_PATHS variable is set to:
`['extra', 'images', 'files']`

The files that are found / not found are:
```
./content/extra
./content/images
./content/files
```

**Comment by avaris** [comment]
I cannot reproduce this (see example run below). Regenerate runs once and waits. I forced the second run by modifying `article.md`.
```console
$ pelican --version
4.5.3
$ tree
.
├── content
│   ├── article.md
│   └── extra
│       └── foo.txt
├── output
│   └── [...]
├── pelicanconf.py
└── __pycache__
    └── pelicanconf.cpython-38.pyc

13 directories, 49 files
$ cat pelicanconf.py
PATH = 'content'
STATIC_PATHS = ['extra']
$ pelican -r
WARNING: Feeds generated without SITEURL set properly may not be valid
WARNING: No timezone information specified in the settings. Assuming your timezone is UTC for feed generation. Check https://docs.getpelican.com/en/latest/settings.html#TIMEZONE for more information
  --- AutoReload Mode: Monitoring `content`, `theme` and `settings` for changes. ---

-> Modified: settings, content, theme, [static]extra. re-generating...
Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.11 seconds.

-> Modified: content. re-generating...
Done: Processed 1 article, 0 drafts, 0 pages, 0 hidden pages and 0 draft pages in 0.08 seconds.

```

**Comment by Moini** [comment]
Yes, I'm sorry. 

I have overlooked a variable, had the 'PATH' defined twice :roll_eyes:  - so it was different in the makefile vs. the pelican settings file. The settings used an absolute path to the 'website' directory, and the makefile gave pelican the content directory as input directory. Interestingly, both worked in that they generated the website :shrug: .

Thank you very much for your help.
