### ISSUE TITLE
Atom feeds now always deliver all the page content

### ISSUE THREAD

**Issue by Moini** [getpelican/pelican#2839]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [ ] I am willing to lend a hand to help implement this feature.  - potentially... 

## Feature Request

Since https://github.com/getpelican/pelican/issues/1886 has been implemented, it seems no longer possible to deliver *only* a summary in Atom feeds. Now my blog articles are heavily formatted, contain lots of relevant CSS, and are very long, so my feed files are large, and the result that people get in the 'content' tag is not very useful.

Additionally, as a user of feed readers, I personally dislike it when irrelevant articles open up as huge full text things, I wouldn't wish that onto any subscribed readers (if in fact there are any, lol).

So I would like to have a preferences option to *only* deliver a summary in the Atom feed, as it was before the linked issue, so people will then be able to see the full article with the correct, usable layout directly in their web browser.

**Comment by justinmayer** [comment]
Hi @Moini. The question of full-content feeds versus summary-only feeds has been an ongoing discussion here for the better part of a decade. Over the years, I have grown quite weary of the topic, so please forgive me if I come across as gruff at any point. 😅 

The short version is that the authors of Pelican (present company included) have long considered summary-only feeds to be a user-hostile anti-pattern. If users want to use their feed readers to read the content, why force them to open articles in a separate browser window?

Regarding formatting, I suspect that anyone who is savvy enough to use a feed reader is well-aware that feed readers focus mainly on text content and may not present the article content as it was originally intended. When I skim an article in my feed reader, find it interesting enough, and suspect opening it in a browser will yield a better experience, I do so. But it's important that as the end user, I have the option to read the article in my feed reader if I so choose.

I tried to see what your site's [Atom feed](https://vektorrascheln.de/feeds/all.atom.xml) content looks like in my feed reader, but I only see article summaries. I inspected the XML, and sure enough, there is no content. Are you hand-editing your feeds to remove the article content?

In any case, Pelican by default offers feed-reading folks a choice: subscribe to the RSS feed for summaries-only or subscribe to the Atom feed for the full article content.

For posterity, via b17e4a5f I added a new FAQ entry that *summarizes* (see what I did there) these thoughts: https://docs.getpelican.com/en/latest/faq.html#can-i-force-atom-feeds-to-show-only-summaries-instead-of-article-content

Before I take my leave, allow me to say that your site is **lovely**. The design, colors, ladybug animation, articles about making books… It’s all just so full of whimsy and magic. As someone who comes across Pelican-powered sites every day, yours stands out as something truly special. I and the other members of the Pelican dev team put a lot of time into working on this project, and knowing that Pelican played a small part in the publication of creative works of art such as yours… It fills me with joy and fulfillment and makes all the time invested in Pelican worth it. So, thank you for filing this issue, if for no other reason than making me aware of your wonderful site’s existence.

**Comment by Moini** [comment]
> I tried to see what your site's Atom feed content looks like in my feed reader, but I only see article summaries. I inspected the XML, and sure enough, there is no content. Are you hand-editing your feeds to remove the article content?

Haha, no, the website is still generated with an old Pelican version. I'm working on rebuilding it with the current version, which seems to be a rather complex process ... (and I'm not going to hand-edit, I'll automate, I'm not crazy!). I'm almost there, though. Just needs compression of assets (do you maybe know if there's a way that doesn't require Java or NodeJS?), and the feed thing working again, then I'll be able to finally switch and focus on updating and creating new content.

Guess then the intended way to do this would be to move to RSS instead of Atom feeds – one type of feed is enough for my little site.

(and you didn't sound gruff at all - thanks for making an FAQ item about it, and for responding)

**Comment by justinmayer** [comment]
You could try the [Image Process plugin](https://github.com/pelican-plugins/image-process) for image processing.

Rather than replace your Atom feeds with RSS, I suggest adding the RSS option and leaving the Atom feed in place so users can choose what works best for them. Just my two cents, of course. 😊

**Comment by Moini** [comment]
It's okay, I've been able to make my old plugin work, and it does exactly what I need, so I'm not currently looking into other image resizing software.

Only thing left is finding a Python CSS + JS compressor that is trustworthy and works good enough. Need to check out the assets plugin more closely, but at a first glance, it looks like it won't work without Java (which is way oversized for my purposes).

**Comment by justinmayer** [comment]
While I can't say for certain that Java isn't required, the recently-migrated [WebAssets Plugin](https://github.com/pelican-plugins/webassets) doesn't mention Java as a requirement, and the upstream [WebAssets dependency](https://github.com/miracle2k/webassets) README implies Java 7 is only required to run the test suite.

**Comment by Moini** [comment]
Just confirming that there are indeed some options to compress web assets if one uses that plugin that do not require either node.js or Java, but run with Python, and that are either already part of the package, or easy to install.
