### ISSUE TITLE
Option to link to internal content without requiring {filename} in link.

### ISSUE THREAD

**Issue by ldv8434** [getpelican/pelican#2842]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

### What
Currently, to link to internal content, the link must contain "{filename}" before the entry. To take the example from the documentation:
```[a link relative to the content root]({filename}/category/article1.rst)```
However, I'd like to be able to use relative paths so that I can click the link within my Markdown editor to bring up the associated file. I understand that this will not work with absolute path syntax due to how OS paths work, but assuming a file was in the same folder as "article1.rst", using "./article1.rst" or "article1.rst" should be able to be changed to "example.com/wherever/article1.html" without needing the "{filename}" part. 
Syntax example (assuming the file was in the same folder as article1.rst):
```[a link relative to the content root](./article1.rst)```

### Why
When writing content, it is a lot easier to verify page links if you can click on them and have them resolve in your editor. It also helps when you use a flurry of Markdown/reST files to build a local knowledge base that gets prettified and hosted elsewhere using Pelican. 

---

Please let me know if this is better done (and if possible) as a plugin rather than being part of the core program.

**Comment by avaris** [comment]
Well, the point of `{filename}` is to make it clear which links are internal (a.k.a. "explicit is better than implicit"). It is used to filter links that would go through this lookup. This also makes it possible to warn user if a link like this does not exist. Doing this for all possible links in a file is 1) slower 2) would produce a lot of failed lookups for regular links (therefore many more warnings). Not to mention, there are companion flags to `{filename}`: `{static}` and `{attach}`. And those carry a lot more functionality than just flagging for "internal link".

**Comment by virtadpt** [comment]
Why not just use Markdown hyperlinks with the URLs of the files you intend to link to?  It's more intuitive than anything else.

**Comment by ldv8434** [comment]
> Why not just use Markdown hyperlinks with the URLs of the files you intend to link to? It's more intuitive than anything else.

That works if everything is accessible via a web address, but not if you're trying to reference things that are all local.



> Well, the point of `{filename}` is to make it clear which links are internal (a.k.a. "explicit is better than implicit"). It is used to filter links that would go through this lookup. This also makes it possible to warn user if a link like this does not exist. Doing this for all possible links in a file is 1) slower 2) would produce a lot of failed lookups for regular links (therefore many more warnings). Not to mention, there are companion flags to `{filename}`: `{static}` and `{attach}`. And those carry a lot more functionality than just flagging for "internal link".

I'm not looking for the current system to be replaced - it's useful. It just isn't useful for the system I use. 
I'd imagine that a boolean option in the config could allow for switching to toggling an implicit mode the same way that the [current relative URL toggle works](https://github.com/getpelican/pelican/blob/659c4cbf0f0cd823d5eb199220e5a087f167733d/pelican/contents.py#L239).

**Comment by avaris** [comment]
> I'm not looking for the current system to be replaced - it's useful. It just isn't useful for the system I use.
> I'd imagine that a boolean option in the config could allow for switching to toggling an implicit mode the same way that the current relative URL toggle works.

I'm afraid it'll be a bit more complicated than that. Would you like to volunteer for implementing it?

**Comment by ldv8434** [comment]
Certainly! Though, would it be better to implement it as an extension instead?

**Comment by avaris** [comment]
If feasible, a plugin would be better solution, yes.

**Comment by hmijail** [comment]
For any googlers, found it among his repos: https://github.com/ldv8434/pelican_implicit_internals/

Thank you @ldv8434 !

**Comment by justinmayer** [comment]
Pelican does not “force” you to break your Markdown links. As far as I am aware, there is nothing preventing you from organizing your source files in the same way as your generated output files and then using `[relative links to your content](/link/to/a/post.html)`.
