### ISSUE TITLE
Auto-links in names wreak havoc with page titles and menu links

### ISSUE THREAD

**Issue by chrysn** [getpelican/pelican#2843]
In a first exploration of Pelican and pages, I've created a pages/about.rst with this content (in a 4.5 pelican-quickstart created site):

```rst
about:me
========

This is me.
```

What appears to happen is that `about:me` is recognized as a URI and made into a link that encompasses the whole title. While surprising, I can't really argue that it's wrong per se -- if you're making browser-themed puns in setup, don't be surprised if something made for browsers gets it.

Things, however, go wrong in two places:

* The link in the menu goes to literally href="about:me" (which is correctly interpreted by the browser to be a URI, but one it won't let me go to). More precisely, the internal link is referenced:

  ```html
  <li><a href="/pages/aboutme.html"><a class="reference external" href="about:me">about:me</a></a></li>
  ```

  What IMO should happen is that whatever fancy is in the title gets converted to something expressible without triggering HTML stuff when being put into a link. (A bit like LaTeX's `\section` etc. commands have their main title, but can optionally have a toc-title that only contains things safe to do inside the ToC).

* Similar happens to the aboutme.html page's title:

  ```html
  <title><a class="reference external" href="about:me">about:me</a></title>
  ```

  which renders as something containing angular brackets in the browser's view of the title.

The example at hand is probably stupid (if I keep having an `about:me` somewhere, I could probably escape it somehow), but there might be a more serious problem behind it in that HTML content is rendered into fields that don't expect anything but plain text in there. I don't expect this to have security ramifications (whoever authors pages already owns the site as I understand), but it still indicates that there's some mismatch.

**Comment by avaris** [comment]
Just wanted to say, having HTML content in title is a normal use case. In fact `typogrify` puts a bunch of more HTML tags when enabled. If you want to use that without any markup (e.g. `<title>`), I suggest using `striptags` Jinja filter (like [here](https://github.com/getpelican/pelican/blob/8bb5f1b786b6f2b22d1dc4501796d6df9a658a05/pelican/themes/notmyidea/templates/article.html#L10)). So, that part is more of a theme issue.

**Comment by justinmayer** [comment]
@chrysn: As @avaris mentioned, HTML tags in fields like the title is indeed a normal use case and can easily be removed at the theme level. Do you think there is anything actionable here for Pelican core?

**Comment by justinmayer** [comment]
Hi @chrysn. If you have more information about this, by all means please share it here. I'm closing this in the interim.

**Comment by chrysn** [comment]
I don't know if there's anything to *do* for Pelican -- to me, the default theme getting HTML escaping wrong sounds like something the engine should do something about, but if it's the agreed-on policy that themes need to take care of that: where is the default theme hosted? (Repository search in the getpelican group turned up dry on "smashing").

**Comment by justinmayer** [comment]
@chrysn: Bundled themes are in this repository under: pelican/themes/

**Comment by chrysn** [comment]
Then there *is* an actionable item for this repository: the default theme should striptags at least its title (for that literally shows as `<a class="reference external" href="about:me">about:me</a>`, or as `it is <em>not</em>` for a page titled `it is *not*`).

As for the content of the menu links, it's harder for me to make a recommendation as I don't know what can reasonably be escaped away. The inner links do break the layout and some navigation, but for links in a title it could be argued "then just don't do it". The ideal behavior I'd expect (of a template, if that's where this lives) would be to leave prettifying HTML and strip out links as they break the layout -- but that's probably complicated.

**Comment by justinmayer** [comment]
@chrysn: I just pushed https://github.com/getpelican/pelican/commit/88953d45d55d55ee7e79804749a40d47aa08c412. Does that fully address this topic?

**Comment by justinmayer** [comment]
Agreed. Will merge this for now, and we can decide later if further work is warranted.

Thanks for your help in improving Pelican! 💫
