### ISSUE TITLE
slugify is no longer hyphenating 

### ISSUE THREAD

**Issue by ingwinlu** [getpelican/pelican#2845]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Pelican version**: pelican @ git+https://github.com/getpelican/pelican.git@8bb5f1b786b6f2b22d1dc4501796d6df9a658a05

## Issue
slugify seems to no longer make hyphens out of spaces:
```python
from pelican.utils import slugify

assert slugify("asdf fdsa") == "asdf-fdsa"
```

This is breaking plugins that depend on that behaviour.

Either change the docstring to indicate that hyphenating is no longer happening or restore old behaviour.

**Comment by ingwinlu** [comment]
I think the default for the substitution handling changed, making it not take the default config but instead not replacing. Will be able to handle it plugin side.

But maybe still take action and change the docstring.

**Comment by avaris** [comment]
Most of the old default processing is [moved to settings](https://github.com/getpelican/pelican/blob/8bb5f1b786b6f2b22d1dc4501796d6df9a658a05/pelican/settings.py#L147-L152) and controlled from there for more flexibility (via #2326). So old behavior still there but you need to pass the settings entry for it:

```python
>>> from pelican.utils import slugify
>>> from pelican.settings import DEFAULT_CONFIG
>>> assert slugify("asdf fdsa", regex_subs=DEFAULT_CONFIG['SLUG_REGEX_SUBSTITUTIONS']) == "asdf-fdsa"
```

But, yeah, docstring could use an update.

PS: long time no see :)
