### ISSUE TITLE
Support for custom attributes in Markdown files

### ISSUE THREAD

**Issue by gjain0** [getpelican/pelican#2849]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Would be great if we can detect custom attributes in the *.md file along with the ones that are defined. consider below example.
```
Title: Some Title
date: 2000-01-01
Tags: Python
Authors: Developer
Summary: summary goes here
MyCustomAttr1: val1
MyCustomAttr2: val2
```
Here two custom attributes are being defined for each post/page and can be used in the jinja template along with other attributes.

**Comment by justinmayer** [comment]
Am I mistaken, or is this not already covered in the FAQ? https://docs.getpelican.com/en/latest/faq.html#can-i-use-arbitrary-metadata-in-my-templates

**Comment by avaris** [comment]
Yes, it should already work. Do you get any errors etc when you try to do that?

**Comment by gjain0** [comment]
@justinmayer @avaris Yes, I already saw that. I was using an attribute called **coverImage** but it didn't work. I also realise that if I do not capitalize the **I**, then it works(i.e **coverimage**). Looks like camel case is not working properly. Is there something undocumented?

**Comment by gjain0** [comment]
@justinmayer @avaris Yes, I have seen that. I was using an attribute called **coverImage** but it didn't work. I also realise that if I do not capitalize the **I**, then it works(i.e **coverimage**). Looks like camel case is not working properly. Is there something undocumented?

**Comment by gjain0** [comment]
Ohh, I missed that. Thanks for pointing that out.
