### ISSUE TITLE
compendium of Pelican settings

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2853]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

enclosed is my compilation of settings found in Pelican. 

https://egbert.net/blog/articles/pelican-configuration-settings.html

**Comment by vkuehn** [comment]
@egberts your blog Link seems to be dead ?

I am searching for setting/configuration for the allowed tags. Does that even exists ?

**Comment by egberts** [comment]
Mmmmm.  VPS trouble.   Old link was 

https://egberts.github.io/egberts/tags/pelican.html

Latest original source link is in:

**Comment by mart-e** [comment]
Is that different from https://docs.getpelican.com/en/latest/settings.html ?

**Comment by egberts** [comment]
Problem with Pelican website is that Google cannot reach these settings.

**Comment by mart-e** [comment]
What do you mean it can not reach? Looks like it's correctly indexed by Google
https://www.google.com/search?hl=en&q=pelican%20USE_FOLDER_AS_CATEGORY
![Screenshot 2023-11-06 at 21-42-35 pelican USE_FOLDER_AS_CATEGORY - Google Search](https://github.com/getpelican/pelican/assets/564822/26ee0e7b-7805-4746-8878-47084a7cbf44)

**Comment by egberts** [comment]
Closing this issue as now being reference-able on Google.

(Mind you, it still doesn't reveal the absolute list, but closing this issue as wontfix.)
