### ISSUE TITLE
Lowercasing of DEFAULT_LANG en-GB to en-gb in template

### ISSUE THREAD

**Issue by kleinbottle** [getpelican/pelican#2855]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

In my Pelican settings file, I had set up my `DEFAULT_LANG` as `en-GB` which got converted to `en-gb` in the template. After searching through the pelican code I found this [code](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L83) which converts the `DEFAULT_LANG` to lowercase.

I can understand that converting `DEFAULT_LANG` lowercase was probably done for validation purposes but I think a simple fix that checks for a hyphen (-) in the `DEFAULT_LANG` and then lowercasing the first two letters and uppercasing the last two letters would be a good fix since most language codes pretty much follow the format `two-letter-kanguage-code|two-letter-country-code`.

I am quite happy to help out in making a pull request for this feature but would like to get input from the community on any issues that may arise from such a fix and get different perspectives.

I have got around the issue by changing the `DEFAULT_LANG` in the theme template using Jinja's functions and filters which is not ideal as I would rather do it in Python code than in Jinja.

**Comment by avaris** [comment]
> I have got around the issue by changing the DEFAULT_LANG in the theme template using Jinja's functions and filters which is not ideal as I would rather do it in Python code than in Jinja.

Well, you can. Define a function in your settings and set a custom filter for jinja via `JINJA_FILTERS`:

```python

def format_lang(lang_code):
    ...

JINJA_FILTERS = {'format_lang': format_lang}
```

and template:

```jinja2
{{ article.lang|format_lang }}
```

**Comment by kleinbottle** [comment]
@avaris Thank you for your suggestion works like a charm.
