### ISSUE TITLE
should feedparser, smartypants  be listed as dependencies?

### ISSUE THREAD

**Issue by suliuzh** [getpelican/pelican#2858]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

Hi
I am wondering if **feedparser** and **smartypants**  should be listed in requirements,txt?
As we can see, smartypants is used in pelican/readers.pyas. Besides, if they are not hardcore dependencies, to make dpendency management clear, should they be listed as extra dependencies in sub-folders?
![image](https://user-images.githubusercontent.com/27858725/110488573-91853300-8129-11eb-93aa-6a66f13963e0.png)

**Comment by justinmayer** [comment]
Hi @suliuzh. I'm a bit perplexed by your questions. What exactly is the perceived problem? Could you perhaps start by explaining what problem situations would be resolved by doing what you're proposing?

Nikola? Huh? As for html5lib, that's not a Pelican dependency.

Feedparser is only used by the importer, and it is [already listed as a dependency in the relevant docs](https://github.com/getpelican/pelican/blob/7a6686f4679adabdd690668a4ba7cedaf494e243/docs/importer.rst#dependencies) for folks who need to use the importer.

As for Smartypants, that is [already a dependency of Typogrify](https://github.com/mintchaos/typogrify/blob/master/setup.py#L27), so there really is no reason to separately specify it as a Pelican dependency.

As a side note, all of this is made even more complicated by the various places that dependencies are currently listed: `pyproject.toml`, `setup.py`, `requirements/**.pip`, etc. Eventually, I imagine we will fully switch to `pyproject.toml` and remove all of the `setup.py` and `requirements/**.pip` files, but in this interim period it's even messier than usual to try to list every single transitive dependency.

When you talk about "making dependency management clear," I imagine that should be handled at the individual site level, shouldn't it? Like, I already have a `pyproject.toml` file for each of the sites that I publish, and _that_ is where I specify the dependent packages that are relevant for each site. (Even then, I feel no need to list dependencies of dependencies of dependencies, but to each their own.)

Anyway, my apologies if I sound gruff — that's certainly not my intention. I'm sure you have reasons for the suggestions you proposed, so perhaps you can enlighten me as to what those are. 😊
