### ISSUE TITLE
autoreload

### ISSUE THREAD

**Issue by AndreaCrotti** [getpelican/pelican#286]
Looking at the autoreload code makes me think that it's not such a good idea:

```
    if args.autoreload:
        while True:
            try:
                # Check source dir for changed files ending with the given
                # extension in the settings. In the theme dir is no such
                # restriction; all files are recursively checked if they
                # have changed, no matter what extension the filenames
                # have.
                if files_changed(pelican.path, pelican.markup) or \
                        files_changed(pelican.theme, ['']):
                    pelican.run()
                time.sleep(.5)  # sleep to avoid cpu load
```

What if the process of checking and running takes more than half a second for example?

And is anyone really actually using this feature?
If we want some real autoreloading for me it might be interesting to add optional support for
http://home.gna.org/py-notify/

inotify is Linux-specific, but there are alternatives also for the other OS, and we could then
avoid the naughtl time.sleep ;)

**Comment by josch** [comment]
But would you accept a PR adding inotify support and using it on systems where it's available and falling back to the old methods on systems where it's not available?

The advantage of using inotify would be that instead of polling the filesystem every half second, the disk and the CPU could remain idle until something is *actually* changed in the filesystem. So using inotify would reduce the load on disk and CPU (and thus saves battery). Even though both loads are tiny, they are frequent. With the current situation I would not be comfortable of having pelican running for hours on my system while it's on battery.

**Comment by cunhaax** [comment]
The CPU usage introduced by pelican is relatively high, considering that we always have at least a browser and other applications open at the same time...
I work with an i5 laptop and the cpu usage by pelican is very noticeable.

@josch I noticed that you have a forked repo with some changes, did you implement these changes using inotify?
@almet can you consider, reopening this issue?

**Comment by justinmayer** [comment]
@cunhaax: Pull request #2176 has already been submitted by @josch, so there is no need to re-open this issue; any further discussion can and should occur there.

If you would like to test @josch's work and provide feedback via comments on his pull request, that would be helpful and much appreciated.

**Comment by josch** [comment]
@cunhaax don't mix up my pull request #2176 with this issue. They are separate topics.

I did not work on implementing autoreload using inotify yet. I will only start preparing a patch implementing that feature if it has the blessing of the pelican devs.

**Comment by justinmayer** [comment]
@josch: Quite right. I think your concept has merit and would think that a PR that added `inotify` support would be warmly received. Do you need any further guidance?

**Comment by josch** [comment]
@justinmayer: Awesome! Then I'll look into it soon. :)

We'll talk details in the PR I'll open about it. ^^
