### ISSUE TITLE
Use index for a particular category the main site index

### ISSUE THREAD

**Issue by samfrances** [getpelican/pelican#2862]
I can't find a way to use an index for a particular category as the main site index. Essentially, I want /index.html to have the same content (apart from relative URLs adjusted) as /blog/index.html. Is this something pelican can do? If not, it would be a welcome feature.

**Comment by justinmayer** [comment]
Hi Sam. What have you tried so far? And what happened when you tried?

**Comment by samfrances** [comment]
The only thing I have tried so far is copying the index file from /blog/index.html to the top-level of the output folder, as part of a Makefile command. But that's a bit of a hack...

**Comment by justinmayer** [comment]
I'm not sure that it's a hack. After all, you seem to want the same `index.html` page generated and saved in two different places, which as far as I'm aware is a use case I've never heard of. If I may ask, why do you want the contents of the home page to be the same as `/blog/`?

**Comment by samfrances** [comment]
Ok, in that case I guess I'll stick with my solution.

> If I may ask, why do you want the contents of the home page to be the same as /blog/?

I guess the blog is just the most interesting landing page for the site.

**Comment by justinmayer** [comment]
If the thought process is that, someday, you might want something else besides the blog content to be on the main home page, I would probably redirect requests for `/` to `/blog/`. That way you aren't duplicating content on multiple URLs, and you can later remove the redirect if and when you ever want to put something else on the main home page.

**Comment by samfrances** [comment]
Ok, good idea. Thanks for your help, I'll close the issue for now.
