### ISSUE TITLE
Setting SUMMARY_MAX_LENGTH doesn't apply to CJK content

### ISSUE THREAD

**Issue by ImBearChild** [getpelican/pelican#2863]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: openSUSE Tumbleweed 20210320
- **Python version**: Python 3.8.8 (default, Feb 19 2021, 16:53:21) [GCC] on linux
- **Pelican version**: 4.5.4
- **Link to theme**: N/A, I use my self-made theme
- **Links to plugins**: None
- **Link to your site**: I'm just testing my theme,so there's no link to my site
- **Link to your source**: It‘s not published.
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: https://gist.github.com/ImBearChild/103ae20e8ddb9182f1f83d415e097bd9

## Issue

When a site contains articles in Chinese, Japanese or Korean, the summary on index page generated by pelican will be much longer than English articles. I set SUMMARY_MAX_LENGTH = 50, but it's obviously more than 50 words. I copied some generated HTML code here, so that you can have a direct compare:

### Example

<ol id="article-list">
        <li><article class="hentry">
                <header> <h2 class="entry-title"><a href="/articles/cao-test/" rel="bookmark" title="Permalink to 从百草园到三味书屋">从百草园到三味书屋: Too Long Summary</a></h2> </header>
                
                <div class="entry-content"> <p>我家的后面有一个很大的园，相传叫作百草园。现在是早已并屋子一起卖给朱文公的子孙了，连那最末次的相见也已经隔了七八年，其中似乎确凿只有一些野草；但那时却是我的乐园。</p>
<p>不必说碧绿的菜畦，光滑的石井栏，高大的皂荚树，紫红的桑葚；也不必说鸣蝉在树叶里长吟，肥胖的黄蜂伏在菜花上，轻捷的叫天子(云雀)忽然从草间直窜向云霄里去了。单是周围的短短的泥墙根一带，就有无限趣味。油蛉在这里低唱，蟋蟀们在这里弹琴。翻开断砖来，有时会遇见蜈蚣；还有斑蝥，倘若用手指按住它的脊梁，便会啪的一声，从后窍喷出一阵烟雾。何首乌藤和木莲藤缠络着，木莲有莲房一般的果实，何首乌有臃肿的根。有人说，何首乌根是有像人形的，吃了便可以成仙，我于是常常拔它起来，牵连不断地拔起来，也曾因此弄坏了泥墙，却从来没有见过有一块根像人样。如果不怕刺，还可以摘到覆盆子，像小珊瑚珠攒成的小球，又酸又甜，色味都比桑葚要好得远。</p>
<p>长的草里是不去的，因为相传这园里有一条很大的赤练蛇。</p>
<p>长妈妈曾经讲给我一个故事听：先前，有一个读书人住在古庙里用功，晚间，在院子里纳凉的时候，突然听到有人在叫他。答应着，四面看时 …</p> </div>
        </article>
    </li>
        <li><article class="hentry">
                <header> <h2 class="entry-title"><a href="/articles/the-arrival/" rel="bookmark" title="Permalink to The Arrival">The Arrival</a></h2> </header>
                
                <div class="entry-content"> <p>At 19.00 hours, ship’s time, I made my way to the launch- 
ing bay. The men around the shaft stood aside to let me 
pass, and I climbed down into the capsule. </p>
<p>Inside the narrow cockpit, there was scarcely room to 
move. I attached the hose to the …</p> </div>
        </article>
    </li>
</ol>

**Comment by justinmayer** [comment]
Thanks for raising this issue, NianQing. Clearly the "word count" here could be improved for CJK languages. Is this something you would be willing to help us enhance? We could really use your assistance! 😁

**Comment by ImBearChild** [comment]
That's a bit of complex. I've just looked into your code, where you use regular expression `\w[\w'-]*` to match words, which **only** match English words. A simple solution is change it with `(\w[\w'-]*)|([\u4E00–\u9FFC])`, which matches every *CJK Unified Ideographs character* as a independent sub-string.

But *CJK Unified Ideographs character* only contains *Chinese Characters* or *汉字*, like this *一个好用的博客引擎*, other characters used by east Asia is not included, for example *にほんご* (which means Japanese). The regular expression `(\w[\w'-]*)|([^\x00-\xff])` can be used to match every character that takes two byte, but other character like Cyrillic (mainly used in east Europe) will be taken as a independent sub-string.

It's hard for me to find out an real international solution. 🤣

**Comment by ImBearChild** [comment]
This is the solution: `(([\u0030-\u024f]|[\u0400-\u04FF])([\u0030-\u024f]|[\u0400-\u04FF]|-|')*)|([\u4E00-\u9FFC])|([\u3040-\u318F])|([\uAC00-\uD7FF])`. A bit of ugly, but work for Chinese, Janpanese, Korean, Español and Russian.

**Comment by justinmayer** [comment]
Addressed via 22192c148a88b30dd942d7bad2a1ab243de59bc3.
