### ISSUE TITLE
Cannot get right order in my categories

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#2867]
Hi all!
Pelican 4.6.0 on a Linux system

I have followed the instructions for the new pages order.
I changed the index.html template that - actually - contains the for cycle and it works well.
The tag.html and category.html template pages simply extends index.html
tags.html works as expected while category.html shows articles in a reverse order (new first).
I really cannot understand how it can happen...
Thanks,
Maurizio

**Comment by justinmayer** [comment]
Hi Maurizio. I *think* you are referring to the new archive ordering functionality @arty-name enabled via #1401 and which I tried to document in the [Pelican 4.6 release notes](https://blog.getpelican.com/pelican-4.6-released.html).

I only have one category on the site in which I have tested this functionality. Perhaps @arty-name might have an idea why your category template page isn't showing your articles in the expected order?

**Comment by mpaglia0** [comment]
Ciao @justinmayer this is exactly my problem.
I do not use tags page in my blog but categories and - despite the fact both are built in the same way - categories order is wrong.
Thanks

**Comment by arty-name** [comment]
Could it be affected by the `REVERSE_CATEGORY_ORDER` configuration option? It is `False` by default.

**Comment by mpaglia0** [comment]
@arty-name sorry but nothing is changing...
I tried also ```REVERSE_ARTICLES_ORDER = True``` (actually I cannot understand how many config params this feature has)

**Comment by arty-name** [comment]
Well, the feature itself only allows using a special URI for the last page, nothing else. The rest is using other configuration options to hack together a desired outcome. I’ve never used categories for my blog, so I didn’t know how that works with them. 

Though looking at your initial comment I see that you  say "newest first" is the reverse order. But the documentation describes what to do to get exactly that: newest first. You don’t want that?

**Comment by mpaglia0** [comment]
@arty-name
I put in my config file
```
ARTICLE_ORDER_BY = "date"
REVERSE_ARCHIVE_ORDER = True
NEWEST_FIRST_ARCHIVES = True
```
The index page (collection of all articles) looks right. But if I open a category, articles have a reverse order!
This looks so strange to me since the for cycle for article list pagination is taken from the index page...

**Comment by arty-name** [comment]
I understand you confusion. But tell me first: does "look right" mean "newest first" or "newest last" to you?

**Comment by mpaglia0** [comment]
@arty-name please apologize for my confusion.
Look right means I see the newest article (i.e. the last/ more recent published article) on TOP of the list

**Comment by mpaglia0** [comment]
@arty-name another information (and then I will stop to bother you).
Page collecting articles belonging a single TAG works also good (i.e. newest article on top).
Only Category pages are working in a reverse way (older article on top).
Nevertheless I have written the for cycle for article list only in my index.html template and index.html is used in both category.html and tag.html template (with {% extends "index.html" %}).
Thank you again for your patience.

**Comment by mpaglia0** [comment]
@arty-name  I have changed my Pelican configuration in order to have the same articles ordering but without your feature. Nevertheless I think your feature is really nice and useful since it is SEO friendly. I suggest to extend the feature also on categories to make it more consistent. Thank you.

**Comment by arty-name** [comment]
I just started looking into that yesterday, but no results yet. I think if the issue is valid this ticket should rather remain open until we fix it. Sorry for the slow processing, even my PR was open for 7 years :)

**Comment by mpaglia0** [comment]
Uh! If the ticket can help you I will open it right now! You do not need to excuse, I wrote because your idea is very good and I will really appreciate to have it fully working.
Have a nice day!!
