### ISSUE TITLE
Extra-settings for plugin-provided configuration

### ISSUE THREAD

**Issue by sabaini** [getpelican/pelican#2870]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x ] I am willing to lend a hand to help implement this feature. 

## Feature Request
In PR #2752 a cli flag for providing configuration via cli args has been implemented.

This only works for pelican core settings however. It would be great if this could be made to work with plugin-defined settings as well.

If this is not possible that fact should be documented.

**Comment by sabaini** [comment]
My original intention to skip settings that are non-core was to get better user feedback for typos, and to try and get type info for settings 

Afaict when parsing settings I can't really know which settings plugins would provide

To deal with this I'm leaning towards not skipping non-core settings and change the logic of type coercion so that non-core settings always get loaded as json.

Happy to hear about other options too though.

**Comment by avaris** [comment]
This should be fixed in #2940. If problem persists, comment here and issue can be reopened.
