### ISSUE TITLE
Azure Static Web Site Support

### ISSUE THREAD

**Issue by askpatrickw** [getpelican/pelican#2871]
This is not an issue that needs work in Pelican, but I thought it was worth also posting here if only to inform that it is being worked on.

But, If you know C# (I don't) and would like to see Pelican as an option for Azure Static websites, please offer suggestions on this PR I started. 

https://github.com/microsoft/Oryx/pull/991

When that ^^ is merged, I'll update this with any docs\steps required to get going.

**Comment by justinmayer** [comment]
@askpatrickw: I don't know anything about C# or Azure, but I nonetheless send good vibes your way and look forward to hearing how it all goes.  💫
