### ISSUE TITLE
4.6 pagination and full first entry

### ISSUE THREAD

**Issue by reagle** [getpelican/pelican#2874]
I upgraded to 4.6 and tried to [reverse the pagination as suggested on the dev blog](https://blog.getpelican.com/pelican-4.6-released.html). I think I got much of it working except that the first entry on the default/latest page is supposed to be full -- not an abbreviation. After the reversal, [the *very* first and oldest entry, now on page 1, is the only one that is showing as full](https://reagle.org/joseph/pelican-test/page-1/). The [most recent page only shows the abbreviations](https://reagle.org/joseph/pelican-test/).

**Comment by avaris** [comment]
In default theme, the logic for displaying an article in full [assumes it will be on the first page](https://github.com/getpelican/pelican/blob/14afc6c54a7e361bbc465fdc25511831cce29812/pelican/themes/notmyidea/templates/index.html#L8). So, you'd need to adjust that as well:

```jinja2
{% if loop.first and not articles_page.has_next() %}
```

**Comment by justinmayer** [comment]
Hey Joseph! Did the suggestion by @avaris help you sort out the needed template changes? You can also look for instances of `{{ article.content }}` and `{{ article.summary }}` in templates and adjust them to see if doing so yields the results you're looking for.

**Comment by reagle** [comment]
Yes, that helps on that front, but then my links to tag pages are broken for reasons I can't understand. Doing the switch will take more effort than I can manage, so I'll close for now.
