### ISSUE TITLE
Sub-resource Integrity (SRI)

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2875]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Does Pelican have anything like Subtresouce Integrity (SRI) in the way of computing SHA386 hash value for each URL referenced within its own website?

Reference: https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by justinmayer** [comment]
Hi Egbert. While I use SRI on my Pelican-powered sites, I computed and added the hashes manually, since I'm not aware of any existing facility that automates this process in a Pelican context. I think that would be a valuable addition to the Pelican ecosystem, particularly if it were implemented in the form of a plugin. Is that something you would be willing to collaborate on?

**Comment by jpralves** [comment]
The plugin assets (which uses webassets) has support for a SRI Tag.
Not very well documented but it can be used like this (in the template):
```
<script async src="{{ SITEURL_OPT }}/{{ ASSET_URL }}" crossorigin="anonymous" integrity="{{ ASSET_SRI }}"></script>
```

**Comment by justinmayer** [comment]
@jpralves: Thank you for the helpful information! Would you mind providing a link to the plugin and/or any other details? I looked in the migrated [Web Assets](https://github.com/pelican-plugins/webassets) plugin, the legacy [Assets](https://github.com/getpelican/pelican-plugins/tree/master/assets) plugin, and the upstream [`webassets` library](https://webassets.readthedocs.io/), but I don't see any SRI references in any of them.

**Comment by jpralves** [comment]
The plugin I've used is [assets](/getpelican/pelican-plugins/tree/master/assets). Although it is pretty undocumented, it works for me. I'm using:
webassets==2.0
mincss==0.11.6
jsmin==2.2.2

The code is in webassets library.

Usage example:
```
{% assets filters="cssmin", output="css/packed.css",
    bootstrapcss,
    "css/style.css"
    %}
<link rel="stylesheet" href="{{ SITEURL_OPT }}/{{ ASSET_URL }}" type="text/css" crossorigin="anonymous" integrity="{{ ASSET_SRI }}"/>
{% endassets %}
```

**Comment by justinmayer** [comment]
Indeed, I see that now. It was implemented in: https://github.com/miracle2k/webassets/pull/521.

I created a new issue in the Web Assets plugin repository to ensure this feature is documented: https://github.com/pelican-plugins/webassets/issues/9

Many thanks for your assistance!
