### ISSUE TITLE
Include a TOC attribute for article objects

### ISSUE THREAD

**Issue by zar3bski** [getpelican/pelican#2877]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

### Context
I am looking for a way to loop through **articles' sections, subsections, etc** the same way I used to do it with [mkdocs](https://www.mkdocs.org/). Pages on mkdocs come with a **graph-like** attribute named `page.toc` allowing to easily generate your article's **table of content** no matter it's depth with something like: 

`sidebar.html`
```html
<aside class="menu sticky">
  {% for toc_item in page.toc %}
    <p class="menu-label">
      {{ toc_item.title }}
    </p>

    {% if toc_item.children %}
      <ul class="menu-list">
        {% include 'partials/sidebar-item.html' %}
      </ul>
    {% endif %}
  {% endfor %}
</aside>
```
`sidebar-item.html`
```html
<li><a href="{{ toc_item.url }}">{{ toc_item.title }}</a>
  {% if toc_item.children %}
    <ul>
      {% for toc_item in toc_item.children %}
        {% include 'partials/sidebar-item.html' %}
      {% endfor %}
    </ul>
  {% endif %}
</li>
```
(you can see such a generated TOC on my blog, for instance [https://zarebski.io/wso2/](https://zarebski.io/wso2/))

### A .toc for article objects

From what I read on the [documentation](https://docs.getpelican.com/en/4.6.0/themes.html#page) on the `Article` [source code](https://github.com/getpelican/pelican/blob/master/pelican/contents.py#L514), there is no equivalent of  a graph structure representing the article's TOC. 

With a similar `.toc`, it would be quite easy to generate [anchors urls](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/What_is_a_URL#anchor) and get 

`my_article.md`
```md
## some_subsection
...
### some_subsubsection
...
```
* `my_article.html#some_subsection`
*  `my_article.html#some_subsubsection`

**Comment by avaris** [comment]
This would be better suited for a plugin. In fact there are a couple plugins that handle ToC generation: [extract_toc](https://github.com/getpelican/pelican-plugins/tree/master/extract_toc) and [pelican-toc](https://github.com/ingwinlu/pelican-toc/tree/master). If they don't fit the bill, I suspect they would make a good starting point.

**Comment by zar3bski** [comment]
I'll check those. Thx @avaris

**Comment by justinmayer** [comment]
@zar3bski: Were you able to find an appropriate ToC solution?

**Comment by zar3bski** [comment]
@justinmayer  been quite busy with work lately. https://github.com/ingwinlu/pelican-toc looked promising but didn't seem to be maintained anymore (not included in the new official pelican plugin repo) 

I'll check it out later

**Comment by rehanhaider** [comment]
This feature is already available by default with Pelican since it uses Python-Markdown. Python Markdown has an extension "TOC" that does exactly this. 

Add the below snippet to your `pelicanconf.py` to enable the setting. 
```md
MARKDOWN = {
    "extension_configs": {
        # Needed for code syntax highlighting
        "markdown.extensions.codehilite": {"css_class": "highlight"},
        "markdown.extensions.extra": {},
        "markdown.extensions.meta": {},
        # This is for enabling the TOC generation
        "markdown.extensions.toc": {"title": "Table of Contents"},
    },
    "output_format": "html5",
}
```

After that add `[TOC]` shotcode in your article at the top and it will generate the TOC. 

Here's a more [detailed walk-through](https://uberpython.com/articles/add-a-table-of-contents-using-markdown-in-pelican) and here is a [sample page with TOC](https://uberpython.com/articles/auto-deploy-pelican-websites-to-firebase-hosting)

**Comment by rehanhaider** [comment]
@justinmayer @zar3bski

This feature is already available by default with Python-Markdown via it's officially supported [TOC plugin](https://python-markdown.github.io/extensions/toc/). 

Since Pelican uses Python Markdown one just needs to add the below snippet to the `pelicanconf.py` to enable the setting. 

```md
MARKDOWN = {
    "extension_configs": {
        # Needed for code syntax highlighting
        "markdown.extensions.codehilite": {"css_class": "highlight"},
        "markdown.extensions.extra": {},
        "markdown.extensions.meta": {},
        # This is for enabling the TOC generation
        "markdown.extensions.toc": {"title": "Table of Contents"},
    },
    "output_format": "html5",
}
```

After that add `[TOC]` shotcode in your article at the top and it will generate the TOC. 

Here's a more [detailed walk-through](https://uberpython.com/articles/add-a-table-of-contents-using-markdown-in-pelican) and here is a [sample page with TOC](https://uberpython.com/articles/auto-deploy-pelican-websites-to-firebase-hosting)

PS: Both those links to my blog, but I couldn't find another sample that uses Pelican.

**Comment by rehanhaider** [comment]
@zar3bski Can the [Python-Markdown's Official TOC](https://python-markdown.github.io/extensions/toc/) extension not serve the purpose?

**Comment by rehanhaider** [comment]
From Markdown-Python's documentation

> Regardless of whether a marker is found in the document (or disabled), the Table of Contents is available as an attribute (toc) on the Markdown class. This allows one to insert the Table of Contents elsewhere in their page template. For example:
>```
>>>> md = markdown.Markdown(extensions=['toc'])
>>>> html = md.convert(text)
>>>> page = render_some_template(context={'body': html, 'toc': md.toc})
>```

I'm a bit new to Pelican, so it will take me some time to dig out where the "content" is being created, but I think this is something that can be enabled natively without more than 2-3 lines addition.

**Comment by zar3bski** [comment]
@rehanhaider Looks promissing since I am mostly using markdown instead of .rst.

**Comment by rehanhaider** [comment]
I found a solution, but am struggling to build it in without breaking things. 
From the documentation
>```md
>>>> md = markdown.Markdown(extensions=['toc'])
>>>> html = md.convert(text)
>>>> page = render_some_template(context={'body': html, 'toc': md.toc})
>```

But adding the _md.toc context is not getting enabled in the readers

**Comment by justinmayer** [comment]
For Markdown content, there is already built-in support for this via the Markdown TOC extension. I use Markdown and have successfully been using the following `pelicanconf.py` setting for quite some time:

```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
        'markdown.extensions.toc': {},   # <-- This is the relevant line
    },
    'output_format': 'html5',
}
```

(See [Pelican Settings](https://docs.getpelican.com/en/latest/settings.html) > `MARKDOWN`)

On my [Justin Mayer](https://justinmayer.com/) site, you can see this in action: one can link to specific section headings via anchor tags, such as: https://justinmayer.com/posts/homebrew-python-is-not-for-you/#best-tool-for-the-job

If that doesn't work well for you, or if you prefer reST content, I suggest exploring one of the aforementioned TOC plugins.

Hope this helps! 😁
