### ISSUE TITLE
Proper way to link to RSS feed?

### ISSUE THREAD

**Issue by daturkel** [getpelican/pelican#2879]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
I'm using Pelican to generate my RSS feed. 

When I want to link to the feed from elsewhere in the site, should I just use an explicit `[my RSS feed](/feeds/rss.xml)`? 

I tried using `[my RSS feed]({static}/feeds/rss.xml)` but got the error that the file does not exist in the `content` directory (which is true!).

Thanks!

**Comment by dflock** [comment]
I would use one of the config variables:

```python
FEED_ATOM = 'feeds/all.atom.xml'
CATEGORY_FEED_ATOM = 'feeds/{slug}.atom.xml'

FEED_RSS = 'feeds/all.rss.xml'
CATEGORY_FEED_RSS = 'feeds/{slug}.rss.xml'
```

So, something like:

```jinja
{% if FEED_ATOM %}
  <a href="{{ SITEURL }}/{{ FEED_ATOM }}">Atom Feed</a>
{% endif %}
```

**Comment by justinmayer** [comment]
> When I want to link to the feed from elsewhere in the site, should I just use an explicit `[my RSS feed](/feeds/rss.xml)`?

If linking from within article/page content in Markdown format, then I believe the above is indeed the right approach.

If from within a template, then the solution Duncan suggested would likely be the most appropriate.

Anything else we can help with here?

**Comment by daturkel** [comment]
This is perfect, thanks!
