### ISSUE TITLE
pelican.utils.get_date() should accept a datetime object

### ISSUE THREAD

**Issue by MinchinWeb** [getpelican/pelican#2881]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

get_date() [here](https://github.com/getpelican/pelican/blob/add3628a6474f2bd145fe2ea55c5e5255e9970ba/pelican/utils.py#L201) assumes that a string is provided, but it should also handle datetime (and date) objects transparently.

I came across this while working on a new Reader. I started with a datetime object, and it seemed kind of dumb to turn it into a string to have it turned back into a datetime. Plus, coveting from strings to datetimes often is slow.

**Comment by avaris** [comment]
You don't need to turn it back to a string, if you already have a `datettime` object override [`process_metadata`](https://github.com/getpelican/pelican/blob/1219bcd029a9386fdc2a398b79a72e60fb1fdb08/pelican/readers.py#L122-L125) in your reader and skip date processing.

**Comment by MinchinWeb** [comment]
I'll look into that. That seems like an easy fix...
