### ISSUE TITLE
Create index page under a subdirectory

### ISSUE THREAD

**Issue by lordfeck** [getpelican/pelican#2890]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Greetings,

I'm seeking to output my articles under the subdirectory `blog/`, which I have done by editing the ARTICLE_SAVE_AS and related variables. 

But, I'd also like Pelican to generate a file with the path -> `blog/index.html` which will list the categories and some of the latest posts in each. 

I have been creating my own theme, so I would know how to create the template page. However I can't find a way for Pelican to output a page under a subdirectory. I put index.html under a subdir `blog` in the theme source, but this wasn't picked up by Pelican.

Is this feature I'm describing possible? I'd appreciate any help. Thanks
Lord Feck

**Comment by avaris** [comment]
Yes, define `INDEX_SAVE_AS = 'blog/index.html` in your settings. Same can be done with other collection pages (`DIRECT_TEMPLATES`). See `INDEX_SAVE_AS` and similar under [URL settings in documentation](https://docs.getpelican.com/en/latest/settings.html#url-settings).

**Comment by lordfeck** [comment]
@avaris many thanks for your reply, that did the trick!

I also note for anyone reading that I had to add the default direct templates to the array, as presumably declaring it in pelicanconf overwrites the default list. So it looked as follows:

`DIRECT_TEMPLATES = ['index', 'authors', 'categories', 'tags', 'archives', 'blog']`

The template is coming along wonderfully now. Looking forward to getting my site off the ground!
