### ISSUE TITLE
Multi-site publishing

### ISSUE THREAD

**Issue by Kentoseth** [getpelican/pelican#2894]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I want to be able to publish my blog to a few different URLs. The reason for this is to keep a backup of my website on either github.io or gitlab.io

I found a similar issue discussing it, but it was regarding only ZeroNet, https://github.com/getpelican/pelican/issues/1928

I am not re-opening that issue because I think this feature could be generalized to be able to add any extra `SITEURL` values.

I checked the documentation and there is no mention of being able to publish the same content to different websites. `RELATIVE_URLS` should not be used for this, per the documentation: https://docs.getpelican.com/en/4.6.0/settings.html?highlight=relative_urls#url-settings

and I checked the plugins section as well and it doesn't exist.

I think 1 possible solution to this is to do the following:

1. Define multiple `SITEURL` in `publishconf.py`
2. Specify the output folder per site folder
3. The generation should generate a different version of the site with the correct site URLs for each output folder

Here is an example dir structure:

> ./home/kentoseth
> -- publishconf.py
> -- content/
> -- output/
> ./home/kentoseth.github.io

So using what I said above, the first SITEURL will generate the output in: `./home/kentoseth/output/` and the second SITEURL will generate the output in: `./home/kentoseth.github.io`

I think this feature is useful for lots of blogs who want (free) backup copies of their sites on github/gitlab or to even consider experimenting with site backups on ZeroNet or other P2P options.

**Comment by avaris** [comment]
One very simple solution is making multiple `publisconf` files with each different `SITEURL` and generating sites with each.

**Comment by justinmayer** [comment]
@Kentoseth: I agree with the suggestion by @avaris. Have you had a chance to try that? Then you could do something like:
```sh
cp publishconf.py kentoseth-github.py && mv publishconf.py kentoseth-gitlab.py
vim kentoseth-github.py # 👈 Add: SITEURL = https://kentoseth.github.io.py
vim kentoseth-gitlab.py # 👈 Add: SITEURL = https://kentoseth.gitlab.io.py
pelican -s kentoseth-github.py
pelican -s kentoseth-gitlab.py
```

The settings file names are totally arbitrary and up to you, in case that's not clear.

**Comment by Kentoseth** [comment]
Thanks for the suggestion @avaris 

I didn't consider that option(multiple publish-conf.py files) and it is much simpler than trying to rework the single file to do multiple deploys.

It does have a bit of manual work required, but for basic backups, doing it once or twice a year is not a lot.

Thanks.
