### ISSUE TITLE
nested, unordered list fails linter

### ISSUE THREAD

**Issue by leggewie** [getpelican/pelican#2895]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu Focal 20.04
- **Python version**: 3.8.3
- **Pelican version**: 4.6.0
- **Link to your source**: https://gitlab.com/leggewie/leggewie.gitlab.io
- **Link to failed pipeline**: https://gitlab.com/leggewie/leggewie.gitlab.io/-/jobs/1378106810

## Issue
A nested, unordered list in pelican throws off the [html-linter](https://pypi.org/project/html-linter/): "48:76: Error: General Formatting: Use a new line for every block, list, or table element, and indent every such child element: Move the opening "ul" to its own line."  

The offending pelican-generated HTML code is
```
$ grep -n remote.*ul public/pages/experience.html -A1
48:<li>highly proficient in Linux administration including headless and remote<ul>
49-<li>desktop, server and embedded</li>
```
The fact that pelican opens the second-level of the unordered list at the end of the preceding line is what triggers the linter. The error message is pretty clear.  The generating markup code is
```
$ grep remote$ content/pages/experience.md -A1
- highly proficient in Linux administration including headless and remote
    - desktop, server and embedded
```

**Comment by avaris** [comment]
This appears to be a [Python-Markdown](https://github.com/Python-Markdown/markdown) issue, rather than a `pelican` one. I'd suggest reporting there.

As a workaround, adding an empty line between levels helps it, but also wraps the previous one in `<p>` (which may or may not be desirable):

```python-console
>>> print(t1)                                                                     
- highly proficient in Linux administration including headless and remote         
     - desktop, server and embedded                                               
>>> print(m.convert(t1))                                                          
<ul>                                                                              
<li>highly proficient in Linux administration including headless and remote<ul>   
<li>desktop, server and embedded</li>                                             
</ul>                                                                             
</li>                                                                             
</ul>                                                                             
>>> print(t2)                                                                     
- highly proficient in Linux administration including headless and remote         
                                                                                  
     - desktop, server and embedded                                               
>>> print(m.convert(t2))                                                          
<ul>                                                                              
<li>                                                                              
<p>highly proficient in Linux administration including headless and remote</p>    
<ul>                                                                              
<li>desktop, server and embedded</li>                                             
</ul>                                                                             
</li>                                                                             
</ul>                                                                             
```

**Comment by leggewie** [comment]
Thank you for that information, @avaris 

I've opened a ticket upstream and will close this report here against pelican as invalid.
