### ISSUE TITLE
"Generating..." leaves artifacts in debug output

### ISSUE THREAD

**Issue by MinchinWeb** [getpelican/pelican#2896]
A spinner was added post 4.6 (which is snazzy!), but it leaves an artifact on the following debug lines.  Ideally these lines would be overwritten rather than appended.

![image](https://user-images.githubusercontent.com/1548809/123890693-e507d080-d914-11eb-9535-97ceadecffd4.png)

- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**:  Windows 10
- **Python version**:  3.9.6
- **Pelican version**:   master at e800b23b4d9ec45663dbac6c5cb4775b0cacdb57 (post 4.6)
- **Link to theme**:  
- **Links to plugins**:  
- **Link to your site**:  
- **Link to your source**:  not yet on GitHub
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**:

**Comment by MinchinWeb** [comment]
Waiting on #2897

**Comment by justinmayer** [comment]
Ostensibly addressed by #2897.
