### ISSUE TITLE
Chronological article listing

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican#2903]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I would like to *add* index pages (tags, categories, all) that show posts in chronological order, instead of the default latest-first sort. `ARTICLE_ORDER_BY` is almost perfect for this, but it replaces the entire index, forcing you to choose one and only one sort order. What I want to do is add functionality without replacing any.

On tumblr, you can can browse a blog's tag in either order: chronological order or latest-first. The URL schemes look like this:

Default: `https://{blog}.tumblr.com/tagged/{tag}/page/{i}`
Chrono: `https://{blog}.tumblr.com/tagged/{tag}/chrono/page/{i}`

I've been trying to hack together a way to reproduce this without forking pelican, and have had no luck. This can't be done with pure template language (since pagination happens in pelican) and I haven't figured out a way to make an additional generator that's correct to the pelican ArticlesGenerator without duplicating code.

Essentially, this would just be generating index pages (tags, categories, etc) twice, once with a different `order_by` setting. 

This could be an optional feature enabled with a setting. This shouldn't interfere with feed generation, which would respect `ARTICLE_ORDER_BY`.

**Comment by GiovanH** [comment]
It's definitely possible that this can be done with a pelican extension in a way that I'm not seeing. If that's the case and writing a generator for this is simple, this probably doesn't need to go in the main codebase.

**Comment by GiovanH** [comment]
Disregard, I've found a way to do this with standard extensions.

**Comment by virtadpt** [comment]
https://xkcd.com/979/

**Comment by GiovanH** [comment]
> https://xkcd.com/979/

Once I pack together a standard extension that does this I'll link it here! Heck, this is the sort of thing that it might sense to merge into pelican one day, once it exists.

**Comment by GiovanH** [comment]
Added an implementation at https://github.com/GiovanH/peliplugins/blob/master/chrono.py, see readme for details!

**Comment by virtadpt** [comment]
Nice!
