### ISSUE TITLE
Pages output as both pages and articles

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican#2906]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

I'm not sure if this is a bug, or maybe even a configuration issuse.

I have a fairly standard content layout, essentially this:
```
content
- category_name
  - article.md
- pages
  - page.md
```
Configuration looks like 
```python
# Directory behavior
PATH = 'content/'
PAGE_PATHS = ['pages/']
...

ARTICLE_SAVE_AS = 'blog/{date:%Y}/{date:%m}/{date:%d}/{slug}/index.html'
PAGE_SAVE_AS = '{slug}/index.html'
```

But whenever I generate my blog, my pages are output *twice*: both to `ARTICLE_SAVE_AS` and `PAGE_SAVE_AS`. The former is rendered with the article template, and the latter is rendered with the page template.

I feel like Pelican might be reading each page twice? I even tried explicitly adding `pages/` to `ARTICLE_EXCLUDES`, but had the same issue.

**Comment by justinmayer** [comment]
Does the problem go away if you comment out your `PATH` and `PAGE_PATHS` settings? I suspect it will.

Assuming that resolves the issue, try removing the slashes from those settings. I don't think those slashes should be there.

**Comment by GiovanH** [comment]
Yep, removing the slashes solved it.
