### ISSUE TITLE
Configure pagination on a per-category basis

### ISSUE THREAD

**Issue by logological** [getpelican/pelican#2907]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I'm building a site that uses different categories of articles for very different purposes.  For example, I've got a "news" category where I want Pelican to create a paginated index with 10 articles per page, but I've also got a "resources" category where I want _all_ the articles to appear on a single index page.  How can I get Pelican to do this?

Now, I could set `DEFAULT_PAGINATION = 10` and simply modify the `category.html` template so that it checks whether it's generating the "resources" index, and if so, prints out the entire index on one page and skips printing the pagination controls:

```
{% if category == "resources" %}
  {% for c, a in categories  %}
    {% if c == "resources" %}
       [ print out article a ]
    {% endif %}
  {% endfor %}
{% else %}
  {% for a in articles_page.object_list %}
    [ print out article a ]
  {% endfor %}
  {% include 'pagination.html' %}
{% endif %}
```

The problem with this approach is that Pelican will still generate `resources2.html`, `resources3.html`, etc., which I don't want.

I also tried creating a separate template named `resources.html` and adding it to `DIRECT_TEMPLATES` in `pelicanconf.py`, but this just results in the following error when I try to build my site:

```
CRITICAL: File /home/me/website/output/resources.html is to be overwritten
```

Probably what I need is the ability to turn pagination on and off on a per-category basis.  Is there some way of doing this?

**Comment by MinchinWeb** [comment]
There's a "Paginated Template" setting (if memory serves). Would removing your resources template from that list solve your issue?

**Comment by logological** [comment]
> There's a "Paginated Template" setting (if memory serves). Would removing your resources template from that list solve your issue?

The "resources" template isn't in that list to begin with, and adding it (with a safely high value, in order to suppress pagination) doesn't get around the `resources.html is to be overwritten` error.

**Comment by avaris** [comment]
There is no built-in way to achieve this. A plugin can do this but it's not going to be simple. Effectively you need your own [Writer](https://github.com/getpelican/pelican/blob/332be6e5c8005f699a708568939d31dd85e9cffb/pelican/writers.py#L18) with overridden [`write_file`](https://github.com/getpelican/pelican/blob/332be6e5c8005f699a708568939d31dd85e9cffb/pelican/writers.py#L169). While writing the categories, `write_file` will receive an additional keyword argument: `category=cat`. If you sent `paginated=False` to `write_file`, that should turn off pagination. So combining these, this might probably work once you turn it into a proper plugin:

```python
from pelican.writers import Writer


class MyWriter(Writer):
    def write_file(self, name, template, context, relative_urls=False,
                paginated=None, template_name=None, override_output=False,
                url=None, **kwargs):
        if ('category' in kwargs and
            kwargs['category'].name not in self.settings['PAGINATED_CATEGORIES']):
            super().write_file(name, template, context, relative_urls=relative_urls,
                               paginated=False, template_name=template_name,
                               override_output=override_output, url=url, **kwargs)
        else:
            super().write_file(name, template, context, relative_urls=relative_urls,
                               paginated=paginated, template_name=template_name,
                               override_output=override_output, url=url, **kwargs)
```

This assumes you have a list of categories you want to paginate in your config as `PAGINATED_CATEGORIES`.

**Comment by logological** [comment]
Thank you, @avaris; this seems to have done the trick!
