### ISSUE TITLE
Only certain themes are working

### ISSUE THREAD

**Issue by Karsteski** [getpelican/pelican#2909]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Hi, I can only get certain themes working. I've been trying to figure out why "elegant" and "Flex" don't work at all, meanwhile "waterspill-en" and "material" work perfectly fine. Is there something I'm missing to theme configuration? Note that Flex doesn't even need any extensions, so I'm confused as to why nothing happens when I select it, other than than the error message:

```
WARNING: Caught exception:
  | "'JINJA_EXTENSIONS' is undefined".
```

Which I can solve just by using an an empty dictionary with the same name, but it doesn't change anything.

Any help welcome. I'd really like to figure this out, it's starting to become quite frustrating... Every tutorial I has the same instructions, so I don't know what I'm missing exactly...

**Comment by justinmayer** [comment]
Hi Kareem. Have you tried searching for `JINJA_EXTENSIONS` in this repository and looking at the returned search results?

**Comment by justinmayer** [comment]
If we can be of further assistance, please comment here and I'd be happy to re-open this issue.
