### ISSUE TITLE
Error when building CRITICAL: 'pelican.contents.Article object' has no attribute 'include'

### ISSUE THREAD

**Issue by jitsejan** [getpelican/pelican#2910]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Mac 10.15.7
- **Python version**: 3.7.10
- **Pelican version**: 4.6.0
- **Link to theme**: 
- **Links to plugins**: 
- **Link to your site**: 
- **Link to your source**: https://github.com/jitsejan/jitsejan.com
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

Pelican was building fine last time I rebuild my website but now got this error all of a sudden. Looks like there is something wrong with the model and I might have defined something in my Markdown files that's not allowed but haven't been able to point out where the mistake is. 

I am using 3.7.10 locally as well as on the CloudFlare worker where my site gets generated.

**Comment by avaris** [comment]
Error is from the theme, [here](https://github.com/jitsejan/jitsejan.com/blob/master/themes/middle-theme/templates/article.html#L6) specifically. It expects a `include` metadata/attribute on articles. That's not default. So presumably it comes from a plugin or actual metadata. Or maybe it was never there and it seems to "work" in `Jinja2==2.11.3`. I think `Jinja2==3.x` made it more strict and raises errors for `foo in Undefined` now. So I'd suggest guarding against that:

```jinja
{% if article.include and 'angular' in article.include %}
```

**Comment by jitsejan** [comment]
Apologies for the (slight) delay. You are right and fixing the Jinja version the build is fine. Thanks!
