### ISSUE TITLE
Default theme leaves bad impression

### ISSUE THREAD

**Issue by paulfertser** [getpelican/pelican#2911]
- [ x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [ x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Pelican version**: 4.6.0
- **Link to theme**: notmyidea, integrated

## Issue

There're multiple shortcomings about the default theme, especially with narrow screens (such as many mobile devices have):
1. banner h1 (used for site title) has line-height:0 which results in ugly second line overlaying on top of the first if the text doesn't fit a single line. I got this effect by looking at "Open On-Chip Debug" with JS disabled so that default Chromium on Debian font was used;
2. banner nav (contains links to pages and categories) has hardcoded height, so if not all links fit the first line the others are shown white-on-white, the background doesn't expand;
3. many big blocks have ~800px width hardcoded, this results in necessity for horizontal scrolling on narrow displays;
4. when an Atom feed is enabled there's no way to suppress showing "Social links" block without editing the theme.
As a sidenote, I'm quite happy with my experience migrating a website from wordpress, everything (but the iframe links to youtube) converted nicely, Pelican documentation is extensive, pretty good overall impression. Other than the problems with the default theme which are hard to solve for somebody who has no clue about web development.
Please consider making default theme really modern, "mobile-friendly", flexible and compatible with wide range of fonts and other user stylesheet tweaks (such as "dark mode").

**Comment by justinmayer** [comment]
I agree, and this has been a long-outstanding goal. That said, someone would need to propose and implement a solution that meets that goal, and so far that hasn't happened. If you'd like to assist with that, which would be most welcome, let's discuss that further in the context of the already-existing issue #1280.

**Comment by BenSturmfels** [comment]
@paulfertser I've address items 1-3 in #2914. If you get a chance, please test it out and let me know if you spot any major issues.
