### ISSUE TITLE
IRC on Freenode is no longer usable

### ISSUE THREAD

**Issue by paulfertser** [getpelican/pelican#2912]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

Since drastic changes happened on Freenode it's no longer allowing unregistered users to connect at all (with IRC TLS protocol at least). Please consider moving the official channel to another network, e.g. OFTC or Libera.Chat.

**Comment by avaris** [comment]
See [this comment](https://github.com/getpelican/pelican/issues/1824#issuecomment-861492933).

**Comment by justinmayer** [comment]
Agreed. As @avaris said, let's try to keep these discussions in the already-existing corresponding issues.
