### ISSUE TITLE
Intra links don't work between drafta nd published pages

### ISSUE THREAD

**Issue by canyon289** [getpelican/pelican#2913]
Hi,
Tried using intra links between a draft post and the files dont link correctly. Issue is as described in these two tickets but perhaps the behavior regressed.
https://github.com/getpelican/pelican/pull/1708

Using `pelican==4.6.0`

This is probably not a huge priority. I really appreciate this SSG, its really great. Thanks for putting it together

## Feature Request
Intra linking is supported with draft tickets

**Comment by avaris** [comment]
I cannot replicate this with the following setup. Tried every combination: draft-to-article, article-to-draft, draft-to-draft. All links are correct and working.

```
content
 |- article.md
 |- draft.md
 |- draft2.md
pelicanconf.py
```
And, files
`article.md`
```markdown
Title: article
Date: 01-01-2021

[link to draft1]({filename}/draft.md)

[link to draft2]({filename}/draft2.md)
```

`draft.md`
```markdown
Title: draft
Status: draft

[link to article]({filename}/article.md)
```

`draft2.md`
```markdown
Title: draft2
Status: draft

[link to other draft]({filename}/draft.md)
```

`pelicanconf.py`
```python
PATH = 'content'
SITEURL = ''
TIMEZONE = 'UTC'
```

**Comment by canyon289** [comment]
Thanks for looking into it. I recently upgraded to 4.8.0 and now can replicate the issue either. Feel free to close ticket, or I can do so as well
