### ISSUE TITLE
truncate_html_words() breaks with Jinja2's autoescape and the end_text being Markup()

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#2917]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

When a template file contains something like the following:
```
{% set readmore -%}
     <span class="readmore">… <a href="{{ BASEURL }}/{{ article.url }}#continue" class="icon fa-forward">read </a></span>
{%- endset %}
{{ article.content|truncate_html_words(50, readmore)|safe }}
```
It works perfectly with the default Pelican settings and produces a properly truncated article with the addition of the custom end marker.  However, if one decides to enable Jinja2's `autoescape` functionality (which is coming to be a default setting pretty soon), by setting `JINJA_ENVIRONMENT` in `pelicanconf.py` to:
```
JINJA_ENVIRONMENT = {
    'autoescape': True,
}
```

The generated output of the template would suddenly contain the entire article's content in the escaped form while injected end marker will be in a valid HTML form.  If you try to rectify the situation by using filters, it will just invert parts -- in all times a part of the output of `truncate_html_words()` will be escaped.

This happens because when Jinja2 is configured for `autoescape` variable blocks (as in `{%set variable %}...{% endset %}` are automatically assigned to a safe class, which is `Markup()`.  This class ensures that if you add something unsafe to it (or add it to something unsafe), the result will be still safe from HTML point of view.

I think Pelican would benefit from using Jinja2's `autoescape` by default, since it makes the generated content less susceptible to XSS'es.

**Comment by avaris** [comment]
I am a bit puzzled by this. `truncate_html_words` is an internal function and not at all exposed to `Jinja` side of the things.

**Comment by galaxy4public** [comment]
Well, in my theme I needed a quick summary generated by keeping just few words.  I just checked my config, and you are correct -- the function itself is not available to Jinja2 by default.  I have the following in my config to make it visible:
```
from pelican.utils import truncate_html_words
JINJA_FILTERS.update({'truncate_html_words': truncate_html_words})
```
I guess, then it is not a bug :).  However, having such a filter helped me to do truncation at many places, I will find some other way to achieve it then.

**Comment by galaxy4public** [comment]
I am happy to close this issue and amend the corresponding PR to just include some missing tests for `truncate_html_words()` (there were no test for custom `end_text` at all.  However, that functionality is used for the built-in summary generation, where you can specify custom string to be used at the end of a summary.

**Comment by avaris** [comment]
You could write a simple `Jinja`-safe wrapper for it I suppose:

```python
def safe_truncate_html_words(text, num, end):
    # process inputs as needed
    return truncate_html_words(text, num, end)

JINJA_FILTERS = {'truncate_html_words': safe_truncate_html_words}
```

**Comment by galaxy4public** [comment]
@avaris, I always find your insights so thoughtful, thank you!  This is a really nice workaround to the issue.
