### ISSUE TITLE
What is the best way to use metadata generated from Plugins in direct templates?

### ISSUE THREAD

**Issue by patrickdung** [getpelican/pelican#2919]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
I generated metadata in the plugin. Now the articles and page could access it by article.new_metadata_name and page.new_metadata_name. But I could not find a way to apply it to direct templates like tags, archive, paginated page (/page/1, page/2, etc.)

Thanks.

**Comment by patrickdung** [comment]
Instead of using metatdata, I tried to global settings so that it could be used for all pages/templates.
Here is [my plugin](https://github.com/patrickdung/pelican_cdn_sri).
But I still want to know what is the best or preferred method, thanks.

**Comment by avaris** [comment]
Sorry, but I couldn't understand your question. If you have metadata that is specific to an article, what does it mean to "apply it" to pages like `DIRECT_TEMPLATES` which are for *collection* of articles? If what you were setting as metadata to articles/pages was in fact a single value that is meant to be accessed globally, then it's not really a metadata for the article and yes, putting it in settings would be the right way.

**Comment by patrickdung** [comment]
@avaris I need to apply to all articles including templates. The variable is for loading the CSS/JS framework.

Thanks for reply. Now, I think the best method is using the settings so that all articles / templates could use it.
