### ISSUE TITLE
Two-character tag at the end of tags in markdown articles prevents subsequent meta from being parsed correctly

### ISSUE THREAD

**Issue by oiseaumanifesto** [getpelican/pelican#2920]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

-   **OS version and name**: Ubuntu 20.10
-   **Python version**: 3.8.10
-   **Pelican version**: 4.6.0
-   **Link to theme**:  n/a
-   **Links to plugins**:  n/a
-   **Link to your site**:  n/a
-   **Link to your source**: n/a
-   **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**:  n/a

## Issue
Hello! I believe I've encountered a bug with two-letter tags in articles.

In my formatted posts I use a two-character tag `oc`.  When this tag (or any two-character tag) comes at the end of the `tag` list: all of the meta fields defined after the last valid tag are treated like article content and appear with `{{ article.content }}`.

This affects only markdown articles, and placing a comma after the two-character tag does not correct this. It's very easily worked around by placing the two-character tag at the beginning of `tags`. So I'm not sure if this is worth addressing, but since this issue is not present in RST articles I think it's a bug.

If I have a post `post.md`:
```
title: Test post
date: 06-03-2020 05:12
tags:  test, still test, oc
authors: Me
custommeta: I'm custom!

Here's some article content.
```

And I generate the site with `pelican`, what is loaded in `{{ article.content }}` is:
```
, oc authors: Me custommeta: I'm custom!

Here's some article content.
```
All previous meta is generated normally.

**Comment by avaris** [comment]
I cannot replicate this. I copy/pasted your example post and when I generate the site, everything is working fine. I cannot say what the issue is without seeing your setup. All I could suggest is, try disabling your plugins first to see if any of them are the issue, if not try with default theme as well.

**Comment by iranzo** [comment]
I faced similar issues when title had ":" like "`title: Welcome: This is our new beggining`", using quotes after `title:` allowed it to work fine.

Similarly, tags expressed as an array `tags: [tag1, tag2, tag3]` or tags as in yaml:

`tags:
  -  tag1
  - tag2
  - tag3`
Seem to cause issues

**Comment by justinmayer** [comment]
Thanks to @avaris and @iranzo for the input.

@oiseaumanifesto: Can you run `pelican-quickstart` to create a new project, see if you can replicate the problem within that new project, and then post another comment here with the results?

**Comment by iranzo** [comment]
Tags as per yaml:

~~~yaml
tags:
  - tag1
  - tag2
  - tag3
~~~

Still are missinterpreted and considered part of the 'text' , and makes the yaml preamble after it to be considered text as well.

tags as brackets:
~~~yaml
tags: [tag1, tag2, tag3]
~~~
Gets one tag named `[tag1`, `tag2` and `tag3]` (note the bracket is considered part of the tag)

**Comment by justinmayer** [comment]
@iranzo: Yeah, I saw your comment above with the same content. I'm not sure what that has to do with this specific issue, nor why we're suddenly talking about YAML?

**Comment by avaris** [comment]
YAML is not supported in python-markdown [meta extension](https://python-markdown.github.io/extensions/meta_data/). 

> ... Even though YAML deliminators are supported, meta-data is not parsed as YAML

**Comment by justinmayer** [comment]
@oiseaumanifesto: If you can replicate with a fresh project, as I mentioned previously, please comment here with the results so that we can re-open this issue.

@iranzo: As @avaris said, Python-Markdown does not support YAML in post metadata, so I'm not sure there is anything actionable regarding the observations you raised.
