### ISSUE TITLE
Markdown documents in `STATIC_PATHS` are being parsed as articles

### ISSUE THREAD

**Issue by Granitosaurus** [getpelican/pelican#2923]
The documentation indicates:
```
# static paths will be copied without parsing their contents
STATIC_PATHS = [
    'images',
    'extra/robots.txt',
    ]
```

However if you create `content/images/foo.md` Pelican still tries to interpret it as an article:
```
ERROR: Skipping /home/user/blog/content/images/foo.md: could not find information about 'title'
```
Which is very inconvenient if you want to add some non-article markdown files. For my particular case I use mdx_include markdown extension to embed some static intros/outros to blog posts as described in: https://docs.getpelican.com/en/latest/content.html?highlight=mdx_include#including-other-files 

Is there a way to prevent this?

**Comment by avaris** [comment]
It depends on your `ARTICLE_PATHS` and/or `PAGE_PATHS`. If you are using default `ARTICLE_PATHS` (which is `['']`, i.e. whole content folder), then everything inside is considered for article (except the ones in `PAGE_PATHS`, they are auto-excluded and vice versa). You can define `ARTICLE_EXCLUDES` to, well, exclude folders from there:

```python
ARTICLE_EXCLUDES = ['images']
```

**Comment by Granitosaurus** [comment]
@avaris That makes total sense - thanks for explaining it!
