### ISSUE TITLE
 svg in -- image:: output is an object instead of an img

### ISSUE THREAD

**Issue by Popolon** [getpelican/pelican#2937]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Arch Liunx updated
- **Python version**: 3.9.7
- **Pelican version**: 4.6.0
- **Link to theme**: no theme selected
- **Links to plugins**: no plugin
- **Link to your site**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

when using  -- image:: in rst for an animated (or not) SVG like this:
```
.. image:: /images/Pinguin_v2.svg
   :height: 250
   :width: 250
   :alt: penguin
   :align: right
```
the output in the formatted html is an object
```
<object class="align-right" data="/images/Pinguin_v2.svg" style="width: 250px; height: 250px;" type="image/svg+xml">penguin</object>
```
 instead of an image:
```
<img src="/images/Pinguin_v2.svg"  width="250px" height="250px" alt="penguin">
```
So the alignment at the right of the text doesn't work with default theme.

**Comment by Popolon** [comment]
Is there a mean to choose between the 2 modes, as object or as image ?

**Comment by avaris** [comment]
That seems to be the [default for HTML4 writer](https://docutils.sourceforge.io/test/functional/expected/standalone_rst_html4css1.html#svg-images) in `docutils`, and that is the one used in `pelican` right now. HTML5 support in `docutils` was not very good (see #2549). If that is improved over time, any contribution regarding upgrading the RST converter would be more than welcome :).

**Comment by Popolon** [comment]
Thanks for the answer. Strange to see again a SVN repository those days, here are more inforamtion about the HTML writer, it could be useful for other people interested by this subject:

The HTML writers part
https://docutils.sourceforge.io/docs/user/html.html
