### ISSUE TITLE
Identing by spaces instead of tab in the pelican-quickstart generated Makefile results in 'Makefile:48: *** missing separator.  Stop.' error message

### ISSUE THREAD

**Issue by szpeter80** [getpelican/pelican#2941]
- [x ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 21.10 on x86_64
- **Python version**: Python 3.9.7
- **Pelican version**: 4.7.1
- **Link to theme**: no themes installed
- **Links to plugins**: no plugins installed
- **Link to your site**: n/a
- **Link to your source**: n/a
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: https://gist.github.com/szpeter80/82fc243a5847cb485ca2168e7542f424

## Issue
Identing by spaces instead of tab in the pelican-quickstart generated Makefile results in 'Makefile:48: *** missing separator.  Stop.' error message.

Afaik it breaks all targets inside the Makefile. I think the issue is unintentionally introduced spaces instead of a tab in the Makefile's Jinja template:

https://github.com/getpelican/pelican/commit/31b282f3e267a4ce536fcdf598941cc9834c479b

**Comment by ingwinlu** [comment]
Hi @szpeter80

thanks for the detailed report and analysis and sorry for the late response.

Will take care of it.
