### ISSUE TITLE
Add parameter to turn off spinner "Generating..."

### ISSUE THREAD

**Issue by kotoko** [getpelican/pelican#2943]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [ ] I am willing to lend a hand to help implement this feature. 

## Feature Request

It looks like there is no way to turn off spinner from #2869 . I created simple plugin for pelican that spawns another proccess to do small processing of generated html files. I have inconvenience now because standard output from that proccess is mixed with many "Generating..." messages from pelican.

It would be nice if there could be option to disable spinner. Simple parameter like `--no-progress` or `--no-spinner` passed on pelican invocation would fine. I looked what `pelican --help` prints and did not see anything related to spinner.

**Comment by justinmayer** [comment]
Hi Jakub. Since we already have a `-q / --quiet` flag, would checking for that flag's presence to suppress the "Generating…" message be an adequate solution?

**Comment by kotoko** [comment]
IMHO correct way to this is to implement two modes:
a) when terminal support interactive messages (spinner),
b) when terminal is not interactive.

`--quiet` flag changes log's verbosity thus has slightly different meaning.

My proposal:
1. If there is flag `--nospinner` or `--force-spinner` hide/show spinner.
2. If there is no flag try to auto detect if terminal is interactive. If it's interactive show spinner. If it's not hide spinner.

Example how to implement auto detection:
```python
def is_interactive_auto_detection():
  return sys.stdout.isatty()
```

My 2¢.

**Comment by justinmayer** [comment]
I'm not super-excited about the idea of adding yet another command-line flag just to suppress the spinner. I'd rather try the second approach first, suppressing progress indicators if a non-interactive session is detected, and see how we fare with that before considering doing anything further.

**Comment by kotoko** [comment]
Good enough. Last time I tested `sys.stdout.isatty()` would return false when piping through `cat` which is OK solution for my problem.

**Comment by avaris** [comment]
Honestly, I was expecting `rich` to handle this and from my limited testing it seems to do just that. I don't see any `Generating...` artifact when I do `pelican content -s pelicanconf.py | cat`.

**Comment by kotoko** [comment]
Nice! I tested and indeed it already works - spinner is hidden when piping through `cat` (colors are missing too which is not a problem). You can close this issue.

I generally have opinion that such things (formatting output) should have explicit option to toggle but workaround is fine for me. Maybe add info about running `pelican [...] | cat` somewhere in documentation as a way of turning off spinner?

Thank you for quick responses! Have a nice day!

**Comment by justinmayer** [comment]
@kotoko said:
> I created simple plugin for pelican that spawns another process to do small processing of generated html files.

Perhaps you could elaborate as to how exactly that works so we could better understand why you're seeing those "Generating…" messages?

**Comment by justinmayer** [comment]
As an aside, I still think users who pass `--quiet` may also prefer not to see the `Generating...` prefix. Perhaps replacing `with console.status("Generating..."):` with the following might be beneficial?
```python
            gen = "" if args.verbosity == logging.CRITICAL else "Generating..."
            with console.status(gen):
```

**Comment by kotoko** [comment]
Plugin essentially just spawns another process and waits until it finishes. In my case I'm running gulp (nodejs etc.) Gulp prints one line when starting task and another one when finishing task.

Example output with messages:
```
⠹ Generating...Using gulpfile ~/xxx/gulpfile.js
[15:02:37] Starting 'default'...
[15:02:37] Starting 'code-highlight'...
⠸ Generating...[15:02:37] Finished 'code-highlight' after 85 ms
[15:02:37] Starting 'css-autoprefixer'...
⠼ Generating...[15:02:37] Finished 'css-autoprefixer' after 122 ms
[15:02:37] Starting 'css-compress'...
⠏ Generating...[15:02:38] Finished 'css-compress' after 435 ms
[15:02:38] Starting 'js-compress'...
⠹ Generating...[15:02:38] Finished 'js-compress' after 189 ms
[15:02:38] Starting 'js-clean'...
[15:02:38] Finished 'js-clean' after 6.97 ms
[15:02:38] Starting 'scss-clean'...
[15:02:38] Finished 'scss-clean' after 8.43 ms
[15:02:38] Starting 'scss-clean2'...
[15:02:38] Finished 'scss-clean2' after 6.94 ms
[15:02:38] Starting 'html-clean'...
[15:02:38] Finished 'html-clean' after 3.84 ms
[15:02:38] Starting 'linux-clean'...
[15:02:38] Finished 'linux-clean' after 7.88 ms
[15:02:38] Finished 'default' after 869 ms
Done: Processed 1 article, 0 drafts, 0 hidden articles, 0 pages, 1 hidden page and 0 draft pages in 1.95 seconds.
```

Source code for plugin:
```python
# -*- coding: utf-8 -*-

from pelican import signals
import logging
from pathlib import Path
from subprocess import check_call

logger = logging.getLogger(__name__)

"""
Run gulp tasks in output path.
"""


def gulp(pelican):
	"""
	Run gulp tasks
	:param pelican: The Pelican instance
	"""
	gulp_dir = Path(pelican.settings.get('GULP_DIR', './'))
	check_call(['npx', 'gulp', '--out', pelican.settings['OUTPUT_PATH']], cwd=gulp_dir)


def register():
	signals.finalized.connect(gulp)
```

**Comment by avaris** [comment]
You can easily integrate that to `pelican` logging:

```python
def gulp(pelican):
	"""
	Run gulp tasks
	:param pelican: The Pelican instance
	"""
	gulp_dir = Path(pelican.settings.get('GULP_DIR', './'))
	process = subprocess.Popen(
		['npx', 'gulp', '--out', pelican.settings['OUTPUT_PATH']],
		cwd=gulp_dir,
		stdout=subprocess.PIPE,
		stderr=subprocess.PIPE,
		universal_newlines=True  # get unicode output
	)

	while process.poll() is None:
		output = process.stdout.readline().rstrip()  # remove newline
		logger.info('GULP: %s', output)  # adjust logging level as you like
		# log stderr similarly if needed
```

PS: Hard tab indentation :confused:

**Comment by mulllhausen** [comment]
note: if you want to debug any of your plugins with pudb then the `generating...` message will mess up the output. piping through cat is a solution
