### ISSUE TITLE
Pelican not rendering markdown lists in output HTML files

### ISSUE THREAD

**Issue by rmhorne** [getpelican/pelican#2945]
- [X ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Windows 10
- **Python version**: 3.8.8
- **Pelican version**: 4.7.1
- **Link to theme**: None / Default
- **Links to plugins**: n/a
- **Link to your site**: n/a
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: [https://gist.github.com/rmhorne/3c5537912c4de77328ca2835f71470e7](https://gist.github.com/rmhorne/3c5537912c4de77328ca2835f71470e7)

## Issue

I can not get lists, both ordered and unordered, in markdown transformed into HTML lists with Pelican. As a test case I created a simple page with an unordered list which you can find here: [https://gist.github.com/rmhorne/3ac9ec590579b4cd483eff7772649f23](https://gist.github.com/rmhorne/3ac9ec590579b4cd483eff7772649f23). I also tested with ordered lists and got the same result. The same page and config was tested with the default theme, pelican-blue, and the directions here: [https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help](https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help), specifically 
``` cd ~/projects/your-site
git clone https://github.com/getpelican/pelican ~/projects/pelican
pelican content -s ~/projects/pelican/samples/pelican.conf.py -t ~/projects/pelican/pelican/themes/notmyidea
 ```
I tried making unordered lists with *, - , and + and Pelican did not convert them to html lists. You can see the html file here: [https://gist.github.com/rmhorne/9b020112ed7e867710b0b3790de75dc4](https://gist.github.com/rmhorne/9b020112ed7e867710b0b3790de75dc4)

**Comment by avaris** [comment]
Add an empty line between your paragraph and lists. Without that, your "list" is considered part of the paragraph.

```markdown
Title: list

Lists

- First item
- Second item
- Third item
    - Indented item
    - Indented item
- Fourth item
```

**Comment by rmhorne** [comment]
Yikes, I should have caught that. Thanks!
