### ISSUE TITLE
After import, pelican will not discern between a blog article and a visitor comment.

### ISSUE THREAD

**Issue by stolk** [getpelican/pelican#2954]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 20.04.3
- **Python version**: 3.8.10
- **Pelican version**: 4.7.1
- **Link to your site**: https://stolk.org/blog/

## Issue

I have used pelican-import to import the XML from a blogger export.

After importing and building the html, I get a pelican site that treats my blog posts and visitor comments as the same. Pelican makes no distinction.

Also, all categorization is lost, like the sections by date: Blog posts from September 2021, e.g. Now it is just an assorted list of articles and visitor comments.

As it is now, the imported site is a poor reflection of how my site was organized in blogger.

**Comment by MinchinWeb** [comment]
HI @stolk !

I orginally imported my site from Blogger, but it was some years ago now. A couple thoughts that might help:

- I remember having to go through and manually review all the imported entries one by one. It seems in particular that the images were still pointing to where they were stored on Blogger's server. There were also various issues that come up with the conversion to Markdown. This clean up took some time, but you only have to do it once.
- out of the box, Pelican doens't support comments, so you'll need to look to a plugin. I use the [Pelican Comment System}(https://github.com/Scheirle/pelican_comment_system), which has a script to import comments from Blogger (that I wrote originally for me). This is a completely static set up that does not require a database or server to work (instead, you get new comments when people email them to you). However, the plugin has not yet been updated to work with Pelican v4, although I am in the process (tonight!) of making that update.
- for categorization and orgaization, that will depend on the theme you're using. You can download an existing theme to change up your site, or modify an exisitng theme to personalize your site, or write a completely new theme. But categorizing by date is [definately possible](https://blog.minchin.ca/archives/) (example from my own site).

If this is something you're still working on, post where you're stuck and hopefully we can provide some insight to help you along your way!

**Comment by justinmayer** [comment]
@MinchinWeb: Many thanks for the detailed reply. Really appreciate you stepping up and helping out! ❤️
