### ISSUE TITLE
SEO-friendly backlinks

### ISSUE THREAD

**Issue by Avamander** [getpelican/pelican#2956]
- [X] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Pelican version**: 4.7.1

## Issue

This is a generic issue about the default Pelican theme, not specific to any generation.

Currently a bunch of the template pages contain backlinks to the "getpelican.com" domain, this does negatively impact its ranking as it's very numerous (looks spammy, bought) and you have no control over who links to you (could be a spammy domain).

## Proposal

Add `rel="nofollow"` (or `rel="ugc"`) to the backlinks in all templates. Suggest theme authors to do the same.

**Comment by Avamander** [comment]
I suspect it's still relevant.

**Comment by mart-e** [comment]
Hi,

You are talking about the "Proudly powered by pelican" in the bottom of the default theme, right?

> this does negatively impact its ranking as it's very numerous (looks spammy, bought) and you have no control over who links to you (could be a spammy domain).

What makes you think so? It's actually quite common to have this in default theme of CMS (e.g. the "powered by wordpress" everywhere and many don't have the  `rel=nofollow`) so I am not sure it's that bad.
