### ISSUE TITLE
Add `Status: ignored` to completely ignore an article

### ISSUE THREAD

**Issue by yifeikong** [getpelican/pelican#2961]
I have a notes folder, some of them are ready to be public and published, some post are personal notes or very early drafts. It seems that both `draft` and `hidden` status will transform them to be included in the generated website. I just want my drafts to be ignored by pelican until they are ready.

I know that I can change the suffixes to make pelican ignore them and change them back later by a script or something, but it just feels very clunky. Having an `ignored` status would be helpful for people mixing their notes and blogs in the same place like me.

If this feature is OK for pelican, I can help to implement it.

**Comment by virtadpt** [comment]
Set the status to something that isn't defined, like "ignore."  When Pelican runs, it'll say the undefined status is an error and ignore it.  It won't break the rest of the site generation process, though.

**Comment by avaris** [comment]
You can place the files you don't want to be processed in a folder and add that to `ARTICLE_EXCLUDES` (or `PAGE_EXCLUDES`, whichever is relevant).

**Comment by yifeikong** [comment]
> Set the status to something that isn't defined, like "ignore." When Pelican runs, it'll say the undefined status is an error and ignore it. It won't break the rest of the site generation process, though.

Thanks for the suggestion, but won't that result in a non-zero status code when running pelican?

> You can place the files you don't want to be processed in a folder and add that to `ARTICLE_EXCLUDES` (or `PAGE_EXCLUDES`, whichever is relevant).

Thanks for the suggestion. I'm aware of that, but like renaming the files with temporary suffixes, moving the files to a folder and restoring them back feels kind of clunky since my notes already have a structured layout on my hard drive.

**Comment by avaris** [comment]
> Thanks for the suggestion, but won't that result in a non-zero status code when running pelican?

No. Only downside is the clutter in your build log with a bunch of errors related to those files.

**Comment by virtadpt** [comment]
@yifeikong Nope.  The rest of the Pelican job will run just fine.  It's how I implemented timed posts in Pelican.

https://drwho.virtadpt.net/archive/2021-01-05/timed-posts-with-pelican/

**Comment by yifeikong** [comment]
@avaris @virtadpt Thanks for your replies, it looks like `Status: ignored` is already a hidden feature of pelican, maybe it could be mentioned somewhere in the docs. I was under the miss-assumption that all other status would be converted into the 3 supported statuses.
