### ISSUE TITLE
How to skip parse markdown italic symbol "_" (html <em>)?

### ISSUE THREAD

**Issue by shwartin** [getpelican/pelican#2962]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
Is there a way to disable the processing of different markdown elements?

For example I have html code inside a markdown file:
`<h3>Remove deprecated <code>torch.{is,set}_deterministic</code></h3>`

After processing it turns into this:
`<h3>Remove deprecated <code>torch.{is,set}<em>deterministic</code></h3>`

And it breaks the entire layout. How can I avoid this?

I tried enabling the markdown extension 'markdown.extensions.legacy_em' but that didn't help.

**Comment by avaris** [comment]
You need to [escape special characters](https://daringfireball.net/projects/markdown/syntax#backslash): `\_`

**Comment by shwartin** [comment]
Thank you it helped
