### ISSUE TITLE
Possible to style {attach}ed images?

### ISSUE THREAD

**Issue by bviefhues** [getpelican/pelican#2967]
Is it possible to CSS style the `<img>` tag produced from `{attach}`ing a file to an article or page? Any way to specify a CSS class? 

- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

**Comment by ysard** [comment]
Hi, to my knowledge, not with Pelican nor Jinja but with Python-Markdown yes.
Take a look at [python-markdown doc](https://python-markdown.github.io/extensions/attr_list/).

```
<img src="{attach}/extra/my_img.png">
{: .illustration-image }
```

**Comment by avaris** [comment]
This is more about the particular markup language you use, and not directly related to pelican. It is possible in [`rst`](https://docutils.sourceforge.io/docs/ref/rst/directives.html#image), but not with markdown (by default). At least without an extension or explicitly using HTML `<img>` directly.

**Comment by justinmayer** [comment]
@bviefhues: Hopefully these answers to your question were helpful. Please let us know if you need further assistance.
