### ISSUE TITLE
link background black in navbar if link is active

### ISSUE THREAD

**Issue by blitzgneisserin** [getpelican/pelican#2970]
Hi, I am using the newest stable release of Pelican on Debian 11 (Bullseye).

I noticed this odd behavior of the default theme "notmyidea":

If I create a custom navigation bar with the option MENUITEMS, the background of the link in the navbar that is active is not highlighted (red) but black. The link is only highlighted if the mouse is on it, if you click on the link, its background turns black again.
I think I know where the broken code is but I am too stupid to fix it. It is in the file tempaltes/base.html:

```
<nav><ul>
                <nav><ul>
                {% for title, link in MENUITEMS %}
                    <li><a href="{{ link }}">{{ title }}</a></li>
                {% endfor %}
                {% if DISPLAY_PAGES_ON_MENU -%}
                {% for pg in pages %}
                    <li{% if pg == page %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ pg.url }}">{{ pg.title }}</a></li>
                {% endfor %}
                {% endif %}
                {% if DISPLAY_CATEGORIES_ON_MENU -%}
                {% for cat, null in categories %}
                    <li{% if cat == category %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ cat.url }}">{{ cat }}</a></li>
                {% endfor %}
                {% endif %}
                </ul></nav>
                {% if DISPLAY_PAGES_ON_MENU -%}
                {% for pg in pages %}
                    <li{% if pg == page %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ pg.url }}">{{ pg.title }}</a></li>
                {% endfor %}
                {% endif %}
                {% if DISPLAY_CATEGORIES_ON_MENU -%}
                {% for cat, null in categories %}
                    <li{% if cat == category %} class="active"{% endif %}><a href="{{ SITEURL }}/{{ cat.url }}">{{ cat }}</a></li>
                {% endfor %}
                {% endif %}
                </ul></nav>
```

Unfortunately I don't know what must be changed here. Can someone help please?

**Comment by blitzgneisserin** [comment]
> Would you mind highlighting in - or extracting from - base.html the code that you think is at fault?

It's the part of the code that is cited above in base.html - at least I think so. I am not able to give you more info.

Obviuosly, this in the beginning

```
{% for title, link in MENUITEMS %}
                    <li><a href="{{ link }}">{{ title }}</a></li>
                {% endfor %}
```
is too short. There should be somewhere 

`class="active"`

in it, like in the code below. I guess "active" means that the menu item should be displayed red.

Btw, thanks for looking into this.

**Comment by avaris** [comment]
You would need a way to find out that the page that's being created is one of the items in that list, and that is not a trivial task.  `MENUITEMS` is a bit too generic, it's just a list of `title:link` pairs. You could have external links there in which case "highlighting" doesn't even make sense as you would go to a site with a completely different theme. If you have links to internal pages, those can be highlighted (I suppose) by matching [`output_file`](https://docs.getpelican.com/en/latest/themes.html#common-variables), for example, to link in some way. But ultimately it depends on what you have in `MENUITEMS`, how you specify links etc...

**Comment by leekimber** [comment]
This seems to be one of those problems that gets darker the more light we shine on it.

@blitzgneisserin: In the absence of a solution, I wonder if you could experiment with your 'class=active' idea yourself. 

Are you aware that you can load a theme from:
1. A git submodule (which I think is why you have it as a 'built-in' pelican theme)
2. Direct from your system's filesystem, or
3. As a pip module?

I ask because it is usually easiest to tweak and test a theme if you use method 2 to load the theme into pelican. Ie:

```
git clone https://github.com/leekimber/pelican-alchemy
# Tweak '<path/to/theme>/templates/base.html'
# Set the THEME variable in your Pelican config ie pelicanconf.py: 
THEME = '<PATH_TO_DOWNLOADED_REPO>/alchemy'
```
Then use pelican to rebuild the site.

If you use this method of loading a theme, it's also also easier to test if others have fixed/improved the theme with changes that have not made it into the default version of notmyidea. I haven't looked but perhaps at:

[https://github.com/getpelican/pelican-themes/tree/master/notmyidea-cms](https://github.com/getpelican/pelican-themes/tree/master/notmyidea-cms)
or
[https://codeberg.org/F_Thoma/NotMyIdea-Theme-Pelican](https://codeberg.org/F_Thoma/NotMyIdea-Theme-Pelican)

**Comment by blitzgneisserin** [comment]
> I wonder if you could experiment with your 'class=active' idea yourself.

I know how to change the theme of a project but I have no idea about coding. I know that a class=active is missing somewhere but not much else. I have been thinking about this but I think it's too difficult a task.

**Comment by justinmayer** [comment]
Hi Anna. I hope you were able to find a solution to this issue. If not, please let us know and we'll do our best to help you.

Many thanks to @leekimber and @avaris for the helpful replies. Much appreciated!
