### ISSUE TITLE
TEMPLATE_PAGES does not add to the file system wather.

### ISSUE THREAD

**Issue by a358003542** [getpelican/pelican#2971]
pelican version:  `pelican          4.7.1`

TEMPLATE_PAGES does not add to the file system wather.  so if i modified these template files, right now pelican does not do the rebuild thing.

**Comment by justinmayer** [comment]
I'm sorry, but I don't understand. Could you please elaborate in greater detail?

**Comment by a358003542** [comment]
like TEMPLATE_PAGES set to :

```
TEMPLATE_PAGES = {
'content/template_pages/test.html' , 'test.html'
}
```
and i aslo disable the html parse: 
```
READERS = {'html': None}
```

because i want all these html file as jinja2 template directly to output the html file, this has some directly simplicity sence.

and when i run the pelican autoreload mode use the `-r` parameters. and i saw when i changed these template file, the pelican does not autoreload it. and i found 


FileSystemWatcher class's update_watchers method right now does not add these file or folder.

i assume maybe the origin design purpose is to put these template file  under the theme folder , but maybe add some code line to add the  `TEMPLATE_PAGES` settings file to it would be more nicer.

**Comment by a358003542** [comment]
I have creat a pull for solve this. #2971. maybe this issue can closed.
