### ISSUE TITLE
Pelican main run function improvement advise

### ISSUE THREAD

**Issue by a358003542** [getpelican/pelican#2975]
Pelican很棒，但最近我也发现了pelican的一个问题，这个问题的解决可能需要pelican进行一次大重构。这个问题就是平时只修改一个markdown文件或者只修改一个css静态文件，将会触发pelican整个run函数，也就是用户当前所有文档的重新build输出动作，这太overworked了。虽然pelican提供了文件缓存策略，但从个人实践来看，这种缓存策略并不能有效地避免计算的过度开销，从源头就选择性地决定要build那些具体的文件才是真正从源头节省计算开销。从个人实践来看，大概四百篇文章的话，缓存策略仍然需要几十秒的build时间而定点的build某一篇markdown则可能只需要零点几秒。

Pelican is great, but right now i have found that pelican has some problem, and this problem solved maybe need pelican do a huge refactor. this problem is when modified one markdown file or simply a css static file, that's will trigger the pelican do the whole re-run work, which is current user all document will do the rebuild work, that is too overworked. althoght pelican has some file cache mechenism, but based on my practise, this filecache mechenism is not sufficient to avoid the overkilled computation works. from the origin source to decide which markdown file needed to be rebuild would be more efficient. base on my practise, about four hundred articles even thought of the file cache mechenism still need dozens of second, and precisely rebuild the target markdown file needed time that is just fractions of a second.

Here is a refactor advise ：

<a href="https://ibb.co/3vNpwtH"><img src="https://i.ibb.co/Jq7vNXP/pelican-improvement.png" alt="pelican-improvement" border="0" /></a>

**Comment by a358003542** [comment]
这样的话pelican将会更有选择性地决定我要处理那些文件，和使用那些generator。然后pelican需要精简自身原有功能，将自身功能集中在某几个文件夹里面的内容和 `ArticlesGenerator` 和 `PagesGenerator` 和 `StaticGenerator` 这几个。剩下的都应该交给插件去扩展完成。
比如说 `TemplatePagesGenerator` 没有articles和dates等环境变量，当用户编写新的插件，如果它的模板里面需要使用articles这个变量，则我们说这个插件是依赖于ArticlesGenerator的。建立插件依赖系统会更加规范pelican的插件开发生态。

目前pelican的使用来看一旦插件过多会很容易造成混乱，不同的输出方式输出风格都混合放在一个文件夹里面是很不好的，推荐风格将他们都分开，这不仅便于用户的内容管理，而且也便于基于不同的文件夹建立不同的Filewatcher。并且不同的文件夹还可以提供优先级参数，generator之间因为依赖也将建立一个优先级执行顺序。

-----
In this way pelican will work more selectively to decided which one i will to process, and use which generators. and i recommend pelican simplify his work, focus some target folder and the  `ArticlesGenerator`  ,  `PagesGenerator` and  `StaticGenerator` . the rest of work leave to some plugin do it.

like  `TemplatePagesGenerator` does not have articles and dates env variables，when user write some new plugin, if their template will use the articles variable, then we will say this pugin is rely on ArticlesGenerator. build a pugin rely on system will 
 make pelican pugin system more formally. 

right now pelican's usage, if use many plugin will be cause some chaos, and also different style different generator in one folder is really a very bad way. the recommend way is to split them into different folder. this will make user manage their content in a more convenient way, and different folder in the filewatcher will output different type, the different type decide the available generators, and different folder we will build a priority parameter, and the generators base on their rely on relationship also would have a priority order.

**Comment by justinmayer** [comment]
Normally, this is where someone might suggest `--write-selected`, but there are reports that it does not behave correctly. See: #2678

If someone would like to replace `--write-selected` with a better mechanism, as suggested at the end of the above issue thread, pull requests to that effect would be most welcome.

> Sorry I donot have time to do the refactor work

Well, that makes two of us. I do not have time to even _digest_ this proposal, much less implement it.

> Do not let the open-source project become to a menber-shared project, if so this project would be running to the dead road.

I have no idea what this means.

**Comment by a358003542** [comment]
mirekdlugosz comment is right, write selected is not enough, need to from the originally to select which type of file or which folder i want to be watch or processed. In some time i will try it. maybe --work-selected , empty string, plus symbol, minus symbol.

**Comment by justinmayer** [comment]
Hi @a358003542. Since we have already have an open issue to track this, I am going to close this issue in favor of the aforementioned open issue. We would welcome your PR contribution to improve this aspect of Pelican! 😊

**Comment by a358003542** [comment]
@justinmayer Looking forward your guys figure something out, as a pelian heavy user really hope Pelican can be more excellent. write some settings to set some folder or file to be processed choicely is a second way, I hope future Pelican can automatically choose which file or folder and which Generator need to run or worked on.
