### ISSUE TITLE
I have a template and page which uses the template but how do I get ARTICLES on the page..

### ISSUE THREAD

**Issue by bostonmacosx** [getpelican/pelican#2977]
I'm trying to get the list of articles to appear on a page i've created Page1.html using a template my_first.html which extends the base.html..... when I try to use the articles_page loop from the index.html on my my_first.html it gets an unknown articles_page... I'm wondering how I can have access to this object on my new template I'm designing. 

As a followup is it possible to only have certain articles show up in this list if the above is possible.

- [X ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

**Comment by justinmayer** [comment]
Hi @bostonmacosx. I'm not sure how to help you with this. [Looking at how the bundled default theme handles looping through items in `articles_page`](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/index.html#L5) should be sufficient to understand how to do something similar in your template.

**Comment by bostonmacosx** [comment]
@justinmayer It would be a huge plus not to limit "articles" to the article pages only. It would be nice to have access to all the objects on any page and any template so that you can build out a more robust site. I was hoping that pelican would be a fit for me however I think it might not be...

**Comment by justinmayer** [comment]
Pelican’s theme/template system is quite robust and should be capable of handling almost any situation that someone wants to implement. But there isn’t nearly enough information in this issue to act on, and even if there were, I personally am not in a position at the moment to dig into explaining potential solutions.

**Comment by bostonmacosx** [comment]
So what other information would you need. 

I have a page in the pages folder.....it uses a template in a theme called "first_template" which extends base. 

I was trying to use Articles_page in a for loop on the page to get the list of current articles...it was throwing the error that the page didn't have access to articles_page.

Maybe someone else will chime in.

**Comment by pauloxnet** [comment]
Hi @bostonmacosx it would help if you can share your repository or some code we can see to better understand your issue, and help you.

**Comment by pauloxnet** [comment]
> ... It would be a huge plus not to limit "articles" to the article pages only. It would be nice to have access to all the objects on any page and any template so that you can build out a more robust site ...

Actually I think you can access `articles` in all templates, in addition to other variables, as you can read in the documentation:
https://docs.getpelican.com/en/latest/themes.html#common-variables

**Comment by justinmayer** [comment]
Hi @bostonmacosx. We would be happy to help if we can, so please go through the [How to Get Help](https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help) section of the documentation and post the relevant the information here, at which point we can re-open the issue and get you all sorted out. ✨
