### ISSUE TITLE
cannot import `soft_unicode` from markupsafe

### ISSUE THREAD

**Issue by moorepants** [getpelican/pelican#2983]
- [ ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [ ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 20.04
- **Python version**: 3.7.12
- **Pelican version**: 4.7.2
- **Link to theme**: 
- **Links to plugins**: 
- **Link to your site**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

I likely upgraded packages in my environment and I now get an error:

```
moorepants@nandi:mechmotum.github.io(source)$ make devserver
"pelican" -lr "/home/moorepants/Websites/mechmotum.github.io/content" -o "/home/moorepants/Websites/mechmotum.github.io/output" -s "/home/moorepants/Websites/mechmotum.github.io/pelicanconf.py" 
Traceback (most recent call last):
  File "/home/moorepants/miniconda/bin/pelican", line 6, in <module>
    from pelican.__main__ import main
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/pelican/__init__.py", line 21, in <module>
    from pelican.generators import (ArticlesGenerator,  # noqa: I100
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/pelican/generators.py", line 11, in <module>
    from jinja2 import (BaseLoader, ChoiceLoader, Environment, FileSystemLoader,
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/home/moorepants/miniconda/lib/python3.7/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/moorepants/miniconda/lib/python3.7/site-packages/markupsafe/__init__.py)
make: *** [Makefile:73: devserver] Error 1
moorepants@nandi:mechmotum.github.io(source)$ conda list | grep markup
markupsafe                2.1.0            py37h540881e_0    conda-forge
moorepants@nandi:mechmotum.github.io(source)$ conda list | grep pelican
pelican                   4.7.2              pyhd8ed1ab_0    conda-forge
```

**Comment by moorepants** [comment]
There was a new release of markupsafe on Feb 18, 2022: https://pypi.org/project/MarkupSafe/#history

**Comment by moorepants** [comment]
Related issue: https://github.com/pallets/markupsafe/issues/282

**Comment by moorepants** [comment]
The response there is not that great:

> You are using an unsupported version of Jinja, please update to the latest version if possible. Additionally, please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by moorepants** [comment]
Downgrading to `markupsafe<2.10` fixes the issues (temporarily).

**Comment by moorepants** [comment]
I wonder if any deprecation warnings were emitted form markupsafe's prior version.

**Comment by moorepants** [comment]
Whatever they did is breaking a whole slew of downstream packages.

**Comment by justinmayer** [comment]
Hey Jason. I haven't run into this error personally, but I agree that their response is not great.

I'm going to close this for now, but if it's actually still unresolved and needs action on our part, by all means please let me know. Cheers!
