### ISSUE TITLE
Double-quote symbol got replaced with &rdquo; in middle of plugin generation stage

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2986]
- [ x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [ x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I noticed that `just_table` was not exactly fully working.  

Specifically the basic `[jtable]` keyword works just fine; it is the additional but various attributes that did not even work such as:

* `caption`
* `ai`
* `separator`
* `th`

like in `[jtable separator="|" ai=0 th=1 caption="A nice table of something"]`; only the basic `[jtable]` just works.

My question now is just before my plugin troubleshooting of Pelican generation stage (over various loaded plugins), the original file had the following:

```markdown
    [jtable separator=","]
```
and within and during this SAME generator stage, one of the earlier plugin performed the replacement of double-quote with `&rdquo;` of that file's content into this:
```markdown
    [jtable separator=&rdquo;,&rdquo]
```

So, my question from a Pelican plugin architect POV is this:

1. Are we supposed to make dual-REGEX (double-effort) for both the double-quote being as-is (`"`) as well as the webified variants ("`&rdquo;`") in case the ordering of plugin-loading gets different for each user?
2. Reorder the jtable plugin during Pelican plugin loading  to beat out before other plugin's double-quote replacement effort begin?
3. or fix the other plugin's "bastardizing" of double-quote during generator-stage and make the plugin do that substitution/replacement/translation later.

**Comment by egberts** [comment]
Looks like I have narrowed it down to Pelican overhead or `m.css` plugin for replacing the double-quote with a webify variant of `&rdquo;`.

**Comment by mosra** [comment]
I tried to find something about what `jump_table` is or what it does, but failed. Can you provide a link? I'm lost.

Yes, [`m.htmlsanity`](https://mcss.mosra.cz/plugins/htmlsanity/#typography) has an option for smart quotes -- did you try to disable it, if you have it enabled? But so does Docutils, and Pelican provided its own option via SmartyPants, so you might want to investigate these as well: https://mcss.mosra.cz/plugins/htmlsanity/#typography

Besides that, I'm not aware of the plugin doing anything rogue if `M_HTMLSANITY_SMART_QUOTES` is off. If you have it enabled and it changes stuff where you think it shouldn't, please give me more info about the other plugin, if it's processing reST or Markdown content, what exactly it generates and how can I try to reproduce this on my side.

**Comment by egberts** [comment]
SMARTYQUOTE are all disabled.

I obtained `just_table` from here https://github.com/getpelican/pelican-plugins.

Did I say "jump_table"?  ARGH!  My apology, it is `just_table` over at https://github.com/burakkose/just_table/tree/7100e984e30e2d3c00cb77037d6ce7e5da8119c3

MASSIVE RE-EDIT: And I've re-edited all the thread to reflect `just_table`. (*shaking my head*).  Thanks for the heads up.

**Comment by mosra** [comment]
> SMARTYQUOTE are all disabled.

Err, just to be clear -- does that mean that even if you set `M_HTMLSANITY_SMART_QUOTES`, `TYPOGRIFY`, *and* the `smart_quotes` Docutils option in `DOCUTILS_SETTINGS` to `False`, it still happens? Then I'm afraid I can't help, as this is then outside the control of my `m.htmlsanity` plugin.

If, however, it works when `M_HTMLSANITY_SMART_QUOTES` is `False` and you need it to work with it enabled, we can continue the discussion over at mosra/m.css#220.

**Comment by egberts** [comment]
i wasnt able to resolve this for my just_table plugin.  it’s stale.

**Comment by egberts** [comment]
Reworking for just_table  handling &rdquo

**Comment by egberts** [comment]
### WORKAROUND

For all those seemingly non-function `[jtable ...]` attribute options provided by the `just_table` plugin, these attributes  finally started working 100% completely and fully when  `smarty` extension got removed from the `MARKDOWN` settings.

Remove the line `smarty` from the `pelicanconf.py` (or `publishconf.py`) settings:

```Python
MARKDOWN = {
  'extension_configs': {
#    'markdown.extensions.smarty': {},
    'markdown.extensions.extra': {},
    'markdown.extensions.footnotes': {},
    'markdown.extensions.meta': {},
    'markdown.extensions.toc': {'baselevel': 1},
    'markdown.extensions.codehilite': {'css_class': 'codehilite'}
  },
  'output_format': 'html5'}
```

While it is an effective workaround, I think some redesign of `just_table` must be made to accommodate such 'bastardization' of `[jtable option=&rdquooptions]`, perhaps like  PRE-PREPROCESSING the `just_table` before the Markdown `smarty` extension starts munging the Jinja stuff.
