### ISSUE TITLE
HTML files in STATIC_PATHS are processed

### ISSUE THREAD

**Issue by Lx** [getpelican/pelican#2990]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: macOS 12.2.1
- **Python version**: 3.10.0
- **Pelican version**: 4.7.2
- **Link to theme**: N/A
- **Links to plugins**: N/A
- **Link to your site**: N/A
- **Link to your source**: N/A
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: inlined:

```py
TIMEZONE = "UTC"
PATH = "content"
STATIC_PATHS = ["static-html"]
```

## Issue
Pelican's documentation [says](https://docs.getpelican.com/en/latest/content.html#static-content), with **my emphasis**:

> ### Static content
> Static files are files other than articles and pages that are copied to the output folder **as-is, without processing**. You can control which static files are copied over with the `STATIC_PATHS` setting of the project’s `pelicanconf.py` file.

Therefore, given some HTML files in `content/static-html` (which is included in `STATIC_PATHS`), I would expect that Pelican does not attempt to process these files, instead copying them as-is to the output.

I have an empty file named `content/static-html/example.html` in place to test this, and I'm seeing this Pelican logging output:

```
ERROR    Skipping /Users/lx/PelicanBug/content/static-html/example.html: could not find          log.py:96
         information about 'title'                                                                        
```

suggesting that Pelican is indeed trying to process the file within `content/static-html`, despite it being listed in `STATIC_PATHS`.

I can work around this by disabling HTML processing:

```py
# Prevent HTML files from being processed as input
# (trying to use STATIC_PATHS for this didn't suffice)
READERS = {"html": None}
```

but this seems like a stop-gap solution, and it will prevent me from intentionally using other HTML files as input for processing.

**Comment by justinmayer** [comment]
Hey Alex. Did you read the FAQ? It seems to address this exact question: https://docs.getpelican.com/en/latest/faq.html#how-can-i-stop-pelican-from-trying-to-parse-my-static-files-as-content

**Comment by Lx** [comment]
D'oh, sorry.  I thought I had, but evidently I somehow totally missed this entry.  This does, of course, perfectly explain the phenomenon I'm seeing.

I wonder if I can redeem myself by offering a doc patch to copy this information closer to the docs for the `STATIC_PATHS` setting—would this be welcome?

**Comment by Lx** [comment]
I regret not getting to this sooner as I've lost some of the knowledge now, but I *think* what I've proposed here would still prevent Future Me™ from falling into the same trap.
