### ISSUE TITLE
CHECK_MODIFIED_METHOD alternatives to "mtime" are not documented

### ISSUE THREAD

**Issue by Lx** [getpelican/pelican#2991]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

The documentation for the `CHECK_MODIFIED_METHOD` setting specifies only `mtime` as an option.

Glancing through the source code, it seems that any name of a hashing function provided by the user's Python's `hashlib` module is accepted (so my options seem to be `sha1`, `sha224`, `sha256`, `sha384`, `sha512`, `blake2b`, `blake2s`, `md5`, `sha3_224`, `sha3_256`, `sha3_384`, `sha3_512`, `shake_128`, and `shake_256`).

I wouldn't expect Pelican's documentation to list all of these possibilities (especially since they might differ across systems), but perhaps just something like

> other options include the name of any hashing function provided by your Python version's `hashlib` module (such as `'sha1'` or `'md5'`), which will use that hashing algorithm to test for file changes

might do.

**Comment by justinmayer** [comment]
If you have tested that some sub-set of those functions actually work (I wouldn't expect you to test all of them), would you consider submitting a PR that clarifies the documentation appropriately?

**Comment by Lx** [comment]
> …would you consider submitting a PR that clarifies the documentation appropriately?

Absolutely—I’ll come back to this ticket soon.
