### ISSUE TITLE
Running Pelican as Github Action, one-step static hosting on yourname.github.io

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2993]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue
Scenario
=======
Often times, we like to just post a Markdown (`.md`) file by only commiting it into our Github repository and then keep walking just to check our phone for THAT new web page.

Options
-----------
I do believe this is now attainable by using the "Continuous Integration" (CI) called "[Actions](https://github.com/features/actions)" in Github.

So, I googled for it and got this '[HOWTO](https://cloudbytes.dev/snippets/automate-deployment-of-pelican-website-to-github-pages)'.

Trouble In Paradise
--------------------------
The problem is that this is a pretty vague step-by-step and it does not appear to be well-written (perhaps too specific for a distro).  I am about to try this but at the same time, I want to ask you this:

A Lil' Help?
---------------
Are there any other websites that details how to runs Pelican `make` in Github Actions?

**Comment by askpatrickw** [comment]
I always write the content, run pelican and commit both the markdown the site.. But yes you could what you suggest as well.

There is a GH Action in the Marketplace.
https://github.com/marketplace/actions/pelican-to-github-pages

And a blog post...
https://nielscautaerts.xyz/deploying-a-pelican-static-site-with-github-actions.html

**Comment by egberts** [comment]
Made My Day!

Thanks ever so MUCH!

**Comment by avaris** [comment]
We now have a reusable Actions workflow and relevant documentation for this, thanks to @seanh. See #3189.
