### ISSUE TITLE
i18n: Is it possible to customize individual SAVE_AS / URL of direct templates?

### ISSUE THREAD

**Issue by slybridges** [getpelican/pelican#2995]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I have direct templates that are localised in various languages and written in their respective folders using the i18n_subsites plugin. They are direct templates rather than content pages because they are html-heavy and would be complex to translate and maintain by our translators otherwise.

I would like to localize the filename of these direct templates depending if the language. What would be the best way to achieve this?

**Comment by jorgesumle** [comment]
If I understood you correctly, this thread can help you: https://github.com/getpelican/pelican/issues/2490. You can store those defined like this:

```
I18N_SUBSITES = {
    'eo': {
        'ARCHIVES_SAVE_AS': 'ekzemplo';
        'ARCHIVES_URL': 'ekzemplo/index.html';
    },
    'pt': {
        'ARCHIVES_SAVE_AS': 'exemplo';
        'ARCHIVES_URL': 'exemplo/index.html';
    }
}
```

**Comment by slybridges** [comment]
Hi @jorgesumle,

Thanks for the pointer. I did read #2490 before posting and, maybe I missed something, but I don't understand how it applies to direct templates.

Let me give an example, let's say I have the following in the config:

```python
DIRECT_TEMPLATES = ["pricing"]
```

I have a corresponding "pricing.html" template that includes some `{% trans %}[...]{% endtrans %}` tags for localization. As mentioned above, the reason I use a direct template instead of a standard page is because this template has a lot of html tags which would make it hard to translate by some non-techie translators.

Pelican will generate a "pricing.html" file in all subsites. What I would like to do is to customize this filename for languages other than English. For example to call this file `tarifs.html` for French so that I can use a localized URL. "tarifs.html" would still use the "pricing.html" template, only the saved filename would be different.

Is there any way to achieve this?

**Comment by jorgesumle** [comment]
> Is there any way to achieve this?

Yes. The following code works for your case:

```
DIRECT_TEMPLATES = ["pricing"]
I18N_SUBSITES = {
    'fr': {
        'PRICING_SAVE_AS': 'tarifs.html'
    }
```

**Comment by slybridges** [comment]
Thanks @jorgesumle, that's indeed exactly what I needed!

I didn't understand that the `_SAVE_AS` mechanism would apply to any template. I thought it would only apply to variables explicitly mentioned in the documentation.
