### ISSUE TITLE
Tables, Rows, and Columns, Oh My!

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#2997]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I have found a table-ization plugin for Pelican called jtable. 

https://github.com/burakkose/just_table

I am using it intensively in all my blogs, one example of multiple tables with many columns/rows is over at 

* https://egbert.net/blog/articles/bind9-directories.html
* [original markdown text file](https://raw.githubusercontent.com/egberts/egberts.github.io-src/master/content/articles/bind9-directories.md)

Templating for Markdown-only (not Rst) is easy as:

```
Nice table here:
[jtable]
Name, Description, Option
Sue, a web designer, yes
Tom, an IT guy, no
[/jtable]
```

It does work well.  Takes in Markdown CSS just fine. And handles any embedded HTML too!

Unfortunately, I cannot change the separator (it is stuck at comma symbol).  

Given that limitation, this is good enough for me. 

The plug-in is old.  Very old, has not been upgraded to use the `pelican.plugins` namespace ... yet.  My entire blog and I am in danger of being obsoleted out of Any future Pelican upgrades. 

Secondly, the new Pelican 4.x generator hook for plug-in doesn't seem to parse the various attributes anymore within the `[jtable opt=value]`.  This alone explains my inability to change separator char. 

Thirdly, the use of square brackets pair as a macro notation (within Markdown) seems to be treated very differently than Jinja2's double-curly-braces pair.  As if Pelican recognize Jinja2 as a first-class citizen exclusively and only; jtable, not so much.  

While jtable remains an awesome all-round Pelican plugin, it is in danger of obsolescence. 

That said, I am more than willing to step up and enhance the plug-in for modern Pelican use.  

Please bear with me for I am not well-versed on the nuances of plug-in (just the old Pelican ways before plug-in namespace), I am however am an expert Python developer but with some Pelican plug-in questions:

1. Does Pelican have an earlier plug-in callback (before generator, output) support in which to handle `[jtable]` notation, like Jinja2's double-curly-braces pair? I was thinking of something that would enable Pelican to call the plug-in firstly with each article/page before the generator stage. 

2. Can Pelican support for yet another -- > plug-in < -- preprocessing stage that covers the pages/articles but not on the template files?

3. Are there any internal design documentation WRT the preprocessing of being able to differentiate between Markdown and RST?  Preprocessing? Or is it just only about having to peruse other plugins for their programming tricks and tips?

Would this be THE great feature for Pelican to have and perhaps boast? Or is this feature request going to devolve into something where I could gladly receive a link to a better Pelican plug-in for this, grudgingly begin my next great search of a tablization Pelican plug-in, or the worst, try a different SSG?

I am a crossroad here.  I know I can be good at this.  Stuff like tables, columns, and rows could be the greatest draw of new users toward Pelican.

**Comment by avaris** [comment]
> Does Pelican have an earlier plug-in callback (before generator, output) support in which to handle [jtable] notation, like Jinja2's double-curly-braces pair? I was thinking of something that would enable Pelican to call the plug-in firstly with each article/page before the generator stage.

* Before output, yes. `just_table` is using it right now: `all_generators_finalized`. That's after everything is read but before anything is written as output.
* Before generator, depends. How before? `pelican` delegates reading and parsing of raw content to relevant libraries. `.md` will be processed with `python-markdown` and `.rst` will be processed with `docutils`, and so on. What `pelican` receives from them is the HTML-ized content. If you want to interject something there then it would need to be a plugin for the appropriate library (`python-markdown`, `docutils`, etc).

> Can Pelican support for yet another -- > plug-in < -- preprocessing stage that covers the pages/articles but not on the template files?

Which stage? We have a whole lot of signals covering more or less every stage of build process.

> Are there any internal design documentation WRT the preprocessing of being able to differentiate between Markdown and RST? Preprocessing? Or is it just only about having to peruse other plugins for their programming tricks and tips?

That also depends. `pelican` doesn't preprocess input files. By default, readers pass the raw input content to relevant libraries and get the HTML back. But it doesn't prevent writing a plugin that replaces default MD or RST readers and performs some preprocessing *before* passing it to `python-markdown` or `docutils` for example.

**Comment by egberts** [comment]
> But it doesn't prevent writing a plugin that replaces default MD or RST readers and performs some preprocessing before passing it to python-markdown or docutils for example.

so, a plug-in can remove the markdown hook, insert their own, and then call the markdown plug-in? 

Mmmmm.  Perhaps I should look at Markdown plug-in to see if they have hook API.

**Comment by justinmayer** [comment]
Hey @egberts. What were the results of your further research into this topic?

**Comment by egberts** [comment]
wrestled with the plugin and parsing the "HTML" tag for separator value.

Could not make it work.

**Comment by justinmayer** [comment]
I appreciate the attempt, as well as the update. Thanks!
