### ISSUE TITLE
Exporting plugin variable to Jinja template

### ISSUE THREAD

**Issue by ebanDev** [getpelican/pelican#2998]
Hello,
I wanna make a plugin that generate a list with the top 4 most read article from a JSON of my analytics tool. I currently have this code 
```py
from pelican import signals
import requests


def init(generator):
    data = requests.get(generator.settings.get('GOACCESS_JSON_URI')).json()
    top_read = []
    i = 0
    while i < 4:
        ii = 0
        while generator.articles[ii].slug != data['requests']['data'][i]['data']:
            ii += 1
        article = {
            'url': '/' + data['requests']['data'][i]['data'] + '.html',
            'title': generator.articles[ii].title,
            'author': generator.articles[ii].author,
            'locale_date': generator.articles[ii].locale_date,
            'readtime': generator.articles[ii].readtime['minutes']
        }
        top_read.append(article)
        i += 1
    generator.settings['TOP_READ'] = top_read


def register():
    signals.article_generator_finalized.connect(init)
```
It works, almost, fine 😅 The top_read variable contains what I want, but I can't find a way to "export" this variable to my Jinja template, I guess it's a signals issue. This `generator.settings['TOP_READ'] = top_read` just doesn't work, I can't access the variable from my jinja code (I tried just adding `{{ TOP_READ }}` to my template to see if it can display any content).

PS: I'm using the latest pelican version
PPS: Thank you for this amazing software 😄

**Comment by avaris** [comment]
`context` variable keeps the items that are passed to the templates. So, instead of 

```
generator.settings['TOP_READ'] = top_read
```

you need:

```
generator.context['TOP_READ'] = top_read
```

**Comment by ebanDev** [comment]
It works ! :D Thanks !
