### ISSUE TITLE
How to get category slug from Jinja template ?

### ISSUE THREAD

**Issue by ebanDev** [getpelican/pelican#2999]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
Hi, I'm making my own pelican theme and I'm facing an issue, on the index screen I wanna make a section with some articles of each category, and a button to see all the articles in this category. I've managed to do this `for` loop over each category, and display some articles of them *but* I'm facing an issue when I try to get the slug of a category. As my categories are in french, there are special chars that are removed when pelican generates the website. (ex: `Pensées du libre` become `pensees-du-libre`) How do I get this category slug ?
Thanks !

**Comment by avaris** [comment]
`category.slug` would give you that (see [doc](https://docs.getpelican.com/en/latest/themes.html#author-category-tag)).

**Comment by ebanDev** [comment]
Well, it doesn't seem to work :/
```html
  {% for category in categories %}
  <div class="card">
    <a href="/category/{{ category.slug }}" class="btn btn-primary">See more</a>
  </div>
  {% endfor %}
``` This category.slug thing just doesn't return anything :/

**Comment by ebanDev** [comment]
I made a temporary fix, but it's… crappy 😅 `{{ category[0]|lower|replace('é', 'e')|replace(' ', '-') }}`

**Comment by avaris** [comment]
`categories` contains list of `(category, articles)` tuples. So `{% for category in categories %}` is not exactly correct. Also, you probably want `category.url` instead. You can check [template](https://github.com/getpelican/pelican/blob/e8d6318e93fecacebca41b2013622b374bd2ad34/pelican/themes/notmyidea/templates/categories.html#L10-L12) in the default theme for an example.

**Comment by ebanDev** [comment]
It works ! Thanks !! :D
