### ISSUE TITLE
Please add this. It is more usefull than that error message.

### ISSUE THREAD

**Issue by rahelosm** [getpelican/pelican#3005]
https://github.com/getpelican/pelican/blob/e8d6318e93fecacebca41b2013622b374bd2ad34/pelican/__init__.py#L564

![image](https://user-images.githubusercontent.com/42242025/167298766-11a2e548-e50e-48d5-a257-07f17efafdb3.png)

**Comment by rahelosm** [comment]
Or what ever that realy tells where and why problem has happend.

**Comment by justinmayer** [comment]
I have no idea what this means. Please elaborate in much greater detail.

**Comment by avaris** [comment]
Try running with `--debug`.
