### ISSUE TITLE
fenced_code is not formatted properly newlines removed before markdown is called.

### ISSUE THREAD

**Issue by askpatrickw** [getpelican/pelican#3006]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Mac OS 12.3.1 (21E258)
- **Python version**: Python 3.9.7
- **Pelican version**: pelican            4.7.2
- **Link to theme**:  private
- **Links to plugins**: markdown, fenced_coee

```python
MARKDOWN = {
    'extension_configs': {
        'markdown.extensions.fenced_code': {},
        'markdown.extensions.codehilite': {'css_class': 'highlight'},
        'markdown.extensions.extra': {},
        'markdown.extensions.meta': {},
    },
    'output_format': 'html5',
}
```

> NOTE: I've tried with and without the fenced_code, without the css_class, and with the order of fenced_code first and last.... 

## Issue

[preformatted-text.md](https://github.com/getpelican/pelican/files/8647782/preformatted-text.md)

````markdown
# Testing preformatted text methods

  This should be preformatted using double space indents
  and it should be on three lines
  1, 2, 3

~~~
This uses triple ~ and it should also be
preformattand on three lines.
1, 2, 3
~~~

```
This uses triple ` and it should also be
preformattand on three lines.
1, 2, 3
```
````

This test file does not honor the line breaks.
The resulting preformatted blocks are all one line.

```html
  <div>
    <p>Testing preformatted text methods</p>
<p>This should be preformatted using double space indents
  and it should be on three lines
  1, 2, 3</p>
<div class="codehilite"><pre><span></span><code>This uses triple ~ and it should also be
preformattand on three lines.
1, 2, 3
</code></pre></div>

<div class="codehilite"><pre><span></span><code>This uses triple ` and it should also be
preformattand on three lines.
1, 2, 3
</code></pre></div>
```

This might be two issues, because when I try running just the article body through markdown, I get HTML  with `\n` in it.
`markdown.markdown(article_text, extensions=['fenced_code'])'

But I'm going to start here, as it appears as though some pre-processing is being done since I get different HTML from markdown than I do from Markdown with pelican.

**Comment by askpatrickw** [comment]
I should add, I see fence_code extension is loaded in debug whether I specify in the config or not.
So it is loading.

**Comment by avaris** [comment]
What do you mean "The resulting preformatted blocks are all one line."? The output you pasted shows them all in three lines?

**Comment by justinmayer** [comment]
Hey Patrick. If you need further assistance with this, please let us know.
