### ISSUE TITLE
Syntax error in parser.py 

### ISSUE THREAD

**Issue by digital-shokunin** [getpelican/pelican#3010]
- [X] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Mac OS X 12.4
- **Python version**: 3.9
- **Pelican version**: 4.7.2
- **Link to theme**: N/A
- **Links to plugins**: N/A
- **Link to your site**: N/A
- **Link to your source**: N/A
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: N/A

## Issue

 Whenever I run pelican I get the following error.

This happens regardless of argument provided.

CRITICAL SyntaxError: invalid syntax (parser.py, line 32)                                           __init__.py:566

**Comment by avaris** [comment]
`pelican` doesn't have a `parser.py`. This is likely from a plugin. Try removing plugins or running `pelican` with `--debug` to see which file/plugin is the issue.

**Comment by digital-shokunin** [comment]
![image](https://user-images.githubusercontent.com/913856/173419369-c623270c-5f1a-4fae-ae5a-8e7e1b845834.png)


I don't recall installing this plugin.

**Comment by digital-shokunin** [comment]
I'm currently in dependency hell, can't get linker plugin to import a module from itself.

**Comment by justinmayer** [comment]
Hey David. Were you eventually able to get everything sorted out?
