### ISSUE TITLE
Jinja template for XML files

### ISSUE THREAD

**Issue by matthewbellringer** [getpelican/pelican#3015]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
I'd like to generate an XML file as part of the build of the website - in this case a podcast-compatible RSS feed - and, having read the documentation, do not understand how to go about this.

I understand how to write a Jinja2 template which will generate the correct XML. What I don't understand is how to make Pelican use that template to generate the file I need. Can I do that as part of a theme, or do I need to write an entire plugin?

**Comment by lioman** [comment]
Perhaps you can just use [Template Pages](https://docs.getpelican.com/en/latest/settings.html#template-pages) to render the xml template as page in pelican.

**Comment by GiovanH** [comment]
Agree that a template page is the right tool for this.

**Comment by justinmayer** [comment]
Thanks for the helpful responses, @lioman and @GiovanH! 👍
