### ISSUE TITLE
Pass setting value from environment variable in command line

### ISSUE THREAD

**Issue by mateuszpawlik** [getpelican/pelican#3016]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

I had some troubles to correctly pass a setting variable value (single string) from an environment variable, in bash, using the `-e` Pelican option. In my case it was an api token which I don't want to store in the repository. Similar problem I had with GitLab CI/CD variable.

Since it took me a long time to get it right, I thought I'll share. This is the command
```
pelican content/ -e API_KEY=''\"$API_KEY\"'' -s pelicanconf.py -t themes/ccns/
```
The environment variable `$API_KEY` must be between `''\"` and `\"''`.

**Comment by justinmayer** [comment]
Many thanks for sharing this, Mateusz! I added this tip to the Pelican documentation. ✨

**Comment by mateuszpawlik** [comment]
Thanks :smiley:
