### ISSUE TITLE
Support for Google Analytics 4 

### ISSUE THREAD

**Issue by mparusinski** [getpelican/pelican#3018]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature.

## Feature Request

Pelican currently supports Google Analytics Universal Analytics, which is set to be decommissioned July 1st 2023 and users are demanded to move to version Google Analytics 4. I have not found in issues or the documentation how to use Google Analytics 4. I assume it is not currently supported.

The feature request is to support the new version of Google Analytics on Pelican. I believe the documentation for implementing support for Google Analytics 4 is here https://developers.google.com/analytics/devguides/collection/ga4.

**Comment by justinmayer** [comment]
Hi Michal. A lot has changed since GA support was originally added to Pelican, including the proliferation of many open-source and self-hosted alternatives that provide much better privacy. So I believe the appropriate course of action is to remove all code related to Google Analytics from Pelican. Theme authors can of course continue to support GA if they want, and Pelican users can make their own choices as well.

**Comment by lioman** [comment]
Wouldn't it be a good approach to have just a general analytics setting? Most of webanalytics software are including a piece of js code and or an image.
If pelican does not support a collection of different analytics system, but just a setting like `ANALYTICS` and this one is just added right before `</body>`  it would give freedom to the user and encourage theme creators to do the same.

**Comment by jorgesumle** [comment]
You can easily include a variable yourself. Anyways, it is not something most people will use. Many people don't care, and other people use server-side analytics because they consume less resources (eco-friendlier) and adblockers don't bypass them.

**Comment by lioman** [comment]
> Many people don't care, and other people use server-side analytics because they consume less resources (eco-friendlier) and adblockers don't bypass them.
That's what I do. Don't care. 
I just suggested dropping analytics completely or if we want to make it easy for beginners with default theme to give them one variable where they just can add any analytics code.
But the more I think about it, an even broader approach or nothing is better

**Comment by mycaule** [comment]
Hi, the new script to include is just this,

```html
<script async src="https://www.googletagmanager.com/gtag/js?id={GOOGLE_ANALYTICS}"></script>
  <script>
    window.dataLayer = window.dataLayer \|\| [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
 
    gtag('config', '{GOOGLE_ANALYTICS}');
 </script>
```

See https://support.google.com/analytics/answer/11583528 for reference

I can make a pull request for replacing this snippet of code, it is easy

https://github.com/getpelican/pelican/blob/1219bcd029a9386fdc2a398b79a72e60fb1fdb08/pelican/themes/notmyidea/templates/analytics.html#L1-L11

**Comment by szebenyib** [comment]
Yes, this would be nice. Also one just has to replace the snippet to keep supporting this feature.

**Comment by GiovanH** [comment]
Agree with removing google analytics support entirely but instead of just asking people to insert their own html in the code, replacing it with a generic optional JINJA variable to insert some arbitrary script at the bottom of the page. Obviously this is a theme change, rather than something to do with generation logic.

**Comment by justinmayer** [comment]
[As I indicated last year](https://github.com/getpelican/pelican/commit/e18c9d2c60195b25049ad5660e57253410096dc2), I believe that analytics in Pelican is a theme-related issue. Much as I removed the Piwik/Matomo-related code from the default theme in that latter commit, it seems to me that the most appropriate action is to replace the contents of the default theme's [`analytics.html`](https://github.com/getpelican/pelican/blob/master/pelican/themes/notmyidea/templates/analytics.html) template with:

```jinja2
{% if ANALYTICS %}
{{ ANALYTICS }}
{% endif %}
```

Then, Pelican users can use their site's configuration file to define that `ANALYTICS` setting to be whatever they want. For example:

```python
ANALYTICS = """
    <script src="/theme/js/primary-analytics.js"></script>
    <script src="/theme/js/secondary-analytics.js"></script>
    <script>
        [ … in-line Javascript code for tertiary analytics … ]
    </script>
"""
```

**Comment by justinmayer** [comment]
In summary, unless the destination is an open-source project that can be self-hosted (and maybe not even then), I don't think analytics code has a place in Pelican core.

In 639173da I removed everything I could find related to vendor-specific analytics, replacing it with the generalized `ANALYTICS` variable I proposed in my previous comment above.
