### ISSUE TITLE
Drop support foe EOL Python version 3.6

### ISSUE THREAD

**Issue by lioman** [getpelican/pelican#3021]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request
Python 3.6 has reached end of live and docs, package metadata still support 3.6.
I suggest increasing all references in documentation to 3.7+ and removing the classifier ` 'Programming Language :: Python :: 3.6',`. 
If we want to enforce it, by adding `python_requires='>3.6',`, but I'm not sure if this one is needed.

**Comment by avaris** [comment]
In theory yes, but unless there are no changes to the code that is not supported in 3.6, is there a point to drop the support?

**Comment by lioman** [comment]
Yes, I think there is. If we don't go the strict way and just remove the meta tag. It is still installable, and you can use it, but basically the meta tag  says. It is working and tested for 3.6 and developers need to make sure that it will work on 3.6 too.
By removing it, we can remove the burden to peek at 3.6 compatibility.
The same is true for dependencies (more and more libraries dropping support)

**Comment by avaris** [comment]
> It is working and tested for 3.6 and developers need to make sure that it will work on 3.6 too.

That's half of what I was saying. Yes, it is tested for 3.6 and working (now). That doesn't mean we need to keep it that way. Developers doesn't need to make 3.6 happy, we can drop 3.6 when a 3.7+ only feature is introduced. But I get what you are saying. I guess, it easier to communicate that by officially dropping 3.6.

**Comment by lioman** [comment]
Created a PR for that.
