### ISSUE TITLE
Please activate log for IRC

### ISSUE THREAD

**Issue by htgoebel** [getpelican/pelican#3022]
When asking question on IRC, one needs to stay online for many hours to see whether there is an answer. Please activate some IRC logging to allow asynchronous communication. Thanks.

Hint: https://irclogs.getnikola.com/ uses https://chriswarrick.com/kwbot/

**Comment by lioman** [comment]
Basically, IRC is dead without this feature. Perhaps we need something different, as discussed in #1824

**Comment by justinmayer** [comment]
For the foreseeable future, please use [Discussions](https://github.com/getpelican/pelican/discussions) for Pelican-related questions.
