### ISSUE TITLE
`_update_context` function converts dictionary to list of tuples

### ISSUE THREAD

**Issue by mateuszpawlik** [getpelican/pelican#3024]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Debian 11 bullseye
- **Python version**: 3.9.2
- **Pelican version**: 4.7.2
- **Link to theme**: https://gitlab.com/ccns/ccns.gitlab.io/-/tree/main/themes/ccns
- **Links to plugins**: https://gitlab.com/ccns/ccns.gitlab.io/-/tree/main/plugins
- **Link to your site**: https://gitlab.com/ccns/ccns.gitlab.io
- **Link to your source**: https://gitlab.com/ccns/ccns.gitlab.io
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: https://gitlab.com/ccns/ccns.gitlab.io/-/blob/main/pelicanconf.py

## Issue

The [`_update_context`](https://github.com/getpelican/pelican/blob/master/pelican/generators.py#L208) function seems to silently convert my dictionary variable to a list of tuples. I don't know if this is an intended behavior. It took me quite some time to figure it out.

Example:
```python
article_generator.publications = {'alice': [1,2,3]}
article_generator._update_context(('publications',))
```
The result is ` [('alice', [1, 2, 3])]`.

Adding the variable directly to generator's context solved the problem.

Example:
```python
if 'publications' not in article_generator.context:
    article_generator.context['publications'] = dict()
article_generator.context['publications']['alice'] = [1,2,3]
```
The result is `{'alice': [1, 2, 3]}`.

**Comment by avaris** [comment]
Yes, it is the intended behavior (in a way). It makes collections in the themes to behave as documented. Is that the right way? Debatable :).

**Comment by mateuszpawlik** [comment]
Thanks. If the behavior is how you expect it, it's fine with me. I pointed it out because for me it wasn't straightforward to understand.

**Comment by justinmayer** [comment]
Perhaps we should at least amend the function's doc-string to document this behavior?

**Comment by justinmayer** [comment]
I took the liberty of adding a note to the relevant function's docstring. Right or wrong, hopefully that will at least help clarify the current behavior.
