### ISSUE TITLE
CRITICAL KeyError: 'lang' - issue with the {lang} metadata in the URL/SAVE_AS of CATEGORY / TAG / ARCHIVE

### ISSUE THREAD

**Issue by fusiro79** [getpelican/pelican#3026]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Windows 10
- **Python version**: 3.10.6
- **Pelican version**: 4.8.0
- **Link to theme**: notmyidea

## Issue
I am setting up a pelicanconf.py for a multi-language site. The documentation says (https://docs.getpelican.com/en/latest/settings.html#url-settings):
      [...] you can use a variety of file metadata attributes within URL-related settings:
      slug
      date
      lang
      author
      category

So, I tried to make use of the "lang" metadata in the URLs. For the article and page URLs everything is ok. But if I try to use the "lang" in the "URLS" and "SAVE_AS" of CATEGORY, TAG, YEAR, MONTH the {lang} metadata generate and error.

For example, I have these settings:

ARTICLE_URL = '{lang}/{category}/{slug}.html'
ARTICLE_SAVE_AS = ARTICLE_URL
DRAFT_URL = '{lang}/{category}/_{slug}.html'
DRAFT_SAVE_AS = DRAFT_URL
PAGE_URL = '{lang}/{slug}.html'
PAGE_SAVE_AS = PAGE_URL
DRAFT_PAGE_URL = '{lang}/_{slug}.html'
DRAFT_PAGE_SAVE_AS = DRAFT_PAGE_URL
CATEGORY_URL = 'category/{slug}/'
CATEGORY_SAVE_AS = 'category/{slug}/index.html'
TAG_URL = 'tags/{slug}/'
TAG_SAVE_AS = 'tags/{slug}/index.html'
YEAR_ARCHIVE_SAVE_AS = 'archives/{date:%Y}_index.html'
MONTH_ARCHIVE_SAVE_AS = 'archives/{date:%Y}-{date:%b}_index.html'
AUTHOR_URL = AUTHOR_SAVE_AS = ''

The error I got with the "pelican -v" is:
CRITICAL KeyError: 'lang' 

Currently, as a workaround, I drop the idea to use the "lang" in the indexes for CATEGORY, TAG and the ARCHIVES... as per the following:

CATEGORY_URL = 'category/{slug}/'
CATEGORY_SAVE_AS = 'category/{slug}/index.html'
TAG_URL = 'tags/{slug}/'
TAG_SAVE_AS = 'tags/{slug}/index.html'
YEAR_ARCHIVE_SAVE_AS = 'archives/{date:%Y}_index.html'
MONTH_ARCHIVE_SAVE_AS = 'archives/{date:%Y}-{date:%b}_index.html'

Thank you in advance if you will find the time to help but also for your work!

Kind regards,
Roberto

**Comment by justinmayer** [comment]
Ciao Roberto. I'm so sorry for the long delay in responding to your question. Were you able to resolve this issue?

**Comment by justinmayer** [comment]
I did some testing but wasn't able to reproduce the reported problem. If you can provide more detail, including links to the actual site content source and the debug error output, we can continue to investigate. Until then, closing this issue for now.
