### ISSUE TITLE
404 not found with search widget queries?

### ISSUE THREAD

**Issue by sjjctl** [getpelican/pelican#3027]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 22.04
- **Python version**: 3.10.4
- **Pelican version**: 4.8.0
- **Link to theme**: elegant, community provided
- **Links to plugins**: n/a
- **Link to your site**: https://dev.nutra.tk/blog/
- **Link to your source**: https://github.com/nutratech/blog/blob/41a4337110a1d48a556afc3bea32b2b65114fc65/pelicanconf.py

## Issue

When typing a query into the search widget, I get a 404.

I can confirm the `search.html` file does NOT exist in `output/`

After running `make html serve` the console outputs this error on the search query.

```text
[21:12:12] WARNING  Unable to find `/search.html` or variations:       log.py:91
                    /search.html.html
                    /search.html/index.html
                    /search.html
```

**Comment by justinmayer** [comment]
Hi Shane. This seems to be related to the specific theme you are using and thus unrelated to Pelican itself. Perhaps the [Elegant](https://github.com/Pelican-Elegant/elegant) theme repository would be a better venue to field this question?

**Comment by gamesguru** [comment]
Okay, I posted an issue there too. Is there a stale issue policy here?

I was using an old version in the `pelican-themes` repo. But upgrading didn't fix it. And no one else reported the same issue. The closest was an empty search result. Be interesting to see what I'm missing here...

**Comment by justinmayer** [comment]
> Is there a stale issue policy here?

I don't understand the question nor what it has to do with this issue. Can you elaborate?

As I intimated above, there is a general policy around keeping issues related to plugins/themes in the respective plugin/theme repository, which I have take the liberty of clarifying via https://github.com/getpelican/pelican/commit/09d434d87b42c206533f33847b99e32dd7934297.

That all said, I sincerely hope someone in the Elegant theme community can assist with the issue you're experiencing. I'm sure it is quite vexing! 😅

**Comment by justinmayer** [comment]
It seems this is related to either the theme (most likely) or the plugin (less likely) and thus not related to Pelican core itself, I'm going to close this issue for now. If there is any evidence supporting the notion that something is awry in Pelican core, please feel free to comment here and we can consider re-opening the issue.
