### ISSUE TITLE
using `basename` in the `TRANSLATION_ID` collection

### ISSUE THREAD

**Issue by ungual** [getpelican/pelican#3033]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

**Being able to use `basename` in the `ARTICLE_TRANSLATION_ID` collection of metadata name.**

The reason why: to identify translated articles if they have the same relative path to a specific folder, without having to declare any metadata in the files themselves (like `lang` or `slug`). 

Say you have your article structured like this
``` 
├── fr/
│   └── event/
│       └── 2022/
│           ├── article_1.md
│           └── article_2.md
└── en/
    └── event/
        └── 2022/
            ├── article_1.md
            └── article_2.md
``` 
You could do
``` python
# first folder is lang metadata, others are category
PATH_METADATA = '^(?P<lang>.+?)\/(?P<category>.*)\/.*'
# articles are translation if they have the same relative path to their lang folder and same filename
ARTICLE_TRANSLATION_ID = ['category', 'basename']
``` 
This mean, that you don't have to declare a `lang` or a `slug` attribute anymore to do translations, and that translation are determined by the file location only.

**Comment by doriane-systems** [comment]
i was finally able to bypass it by creating a custom `transid` metadata extracted from `PATH_METADATA`
```python
# first folder is lang metadata, others are category, category + filename forms the translation id
PATH_METADATA = '^(?P<lang>.+?)\/(?P<transid>(?P<category>.*)\/.*)'
# articles are translation if they have the same relative path to their lang folder with same filename
ARTICLE_TRANSLATION_ID = ['transid']
```
sorry for the post, using the "native" `basename` is not necessary if you can extract it into a custom metadata with `PATH_METADATA`.

**Comment by justinmayer** [comment]
Hi @ungual. I am glad you were able to resolve this issue. 😊
