### ISSUE TITLE
Problem with cache

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#3034]
Issue on a single article if CACHE is activated

- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
If I activate the option CACHE_CONTENT all goes OK on all pages and articles except one that returns this error:
[15:31:31] WARNING  Could not save cache                                                                     log.py:91
                    /home/xxx/Sistema/pelican-web/mauriziopaglia/cache/ArticlesGenerator-Readers                      
                     ... Can't pickle <function gettext at 0x7f2c5ba32730>: it's not the same object as               
                    pelicanconf.gettext  
If I activate also LOAD_CONTENT_CACHE the error is:
[15:35:53] CRITICAL EOFError: Ran out of input 

I think the second error il caused by the first one and the first error is caused by something I put on that blog article!

**Comment by avaris** [comment]
Something with the `gettext` function in your config file. Can you show `pelicanconf.py`?

**Comment by mpaglia0** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*- #

from __future__ import unicode_literals
import os
import sys
sys.path.append(os.curdir)

AUTHOR = 'Maurizio'
SITENAME = 'MaurizioPaglia.it'
SITELOGO = '/assets/MPOnda.png'
SITESUBTITLE = 'Fotografie à la carte, con contorno'
# Leave SITEURL='' and set your domain in publishconf.py
SITEURL=''

# Path of source files
PATH = 'content'

DEFAULT_DATE = 'fs'
DEFAULT_DATE_FORMAT = '%d/%m/%Y'
TIMEZONE = 'UTC'
DEFAULT_LANG = 'it'
LOCALE = 'it_IT.UTF-8'

# By default, use agressive caching.
# The Makefile ensures we use `--ignore-cache` for production builds.
#CACHE_PATH = 'cache'
#CACHE_CONTENT = True
#LOAD_CONTENT_CACHE = True
#CHECK_MODIFIED_METHOD = 'md5'
WITH_FUTURE_DATES = False

# Adds some nice effects to text
TYPOGRIFY = True

# Max words to use for summary
SUMMARY_MAX_LENGTH = 55
SUMMARY_END_SUFFIX = ' …'

# Feed generation is usually not desired when developing
# Set these values only in publishconf.py
FEED_ALL_ATOM = None
FEED_ALL_RSS = None
CATEGORY_FEED_ATOM = None
CATEGORY_FEED_RSS = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'https://getpelican.com/'),
         ('Python.org', 'https://www.python.org/'),
         ('Jinja2', 'https://palletsprojects.com/p/jinja/'),
         ('You can modify those links in your config file', '#'),)

# Pagination
DEFAULT_PAGINATION = 5
DEFAULT_ORPHANS = 4
ARTICLE_ORDER_BY = 'reversed-date'
PAGINATION_PATTERNS = (
   (1, '{base_name}/', '{base_name}/index.html'),
   (2, '{base_name}/pagina/{number}/', '{base_name}/pagina/{number}/index.html'),
)

STATIC_PATHS = ['assets', 'blog', 'img', 'nemo', 'news', 'pages', 'progetti']
EXTRA_PATH_METADATA = {
    'assets/robots.txt': {'path': 'robots.txt'},
    'assets/favicon.ico': {'path': 'favicon.ico'},
    'assets/htaccess': {'path': '.htaccess'},
}

DIRECT_TEMPLATES = ['index', 'tags',  'archives', 'search', 'categories']

# Post and Pages path
ARTICLE_URL = '{date:%Y}/{date:%m}/{slug}'
ARTICLE_SAVE_AS = '{date:%Y}/{date:%m}/{slug}.html'

PAGE_URL = '{slug}'
PAGE_SAVE_AS = '{slug}.html'

YEAR_ARCHIVE_SAVE_AS = '{date:%Y}/index.html'
MONTH_ARCHIVE_SAVE_AS = '{date:%Y}/{date:%m}/index.html'

# Tags and Category path
CATEGORY_URL = '{slug}'
CATEGORY_SAVE_AS = '{slug}.html'
CATEGORIES_SAVE_AS = 'categorie/index.html'

DRAFT_URL = ''
DRAFT_SAVE_AS = ''

TAG_URL = '{slug}'
TAG_SAVE_AS = '{slug}.html'
TAGS_SAVE_AS = 'tags.html'

# Save the index.html template for blog only
# since the actual index.html will be different
#INDEX_SAVE_AS = 'genindex.html'

# Author
# This is the standard Pelican structure
AUTHOR_URL = ''
AUTHOR_SAVE_AS = ''
AUTHORS_SAVE_AS = ''
# And this is a static author page
# it works only if above settings are BLANKS ('')
SINGLE_AUTHOR_SAVE_AS = 'mi-presento.html'

# In this way all contents are created with status = draft
# unless a status = published is stated on each single content
DEFAULT_METADATA = {
   'status': 'draft',
   'author': 'Maurizio',
   'og_image': 'img/banner/og-image.jpg'
}

# Do not use Categories and Pages for the menu but...
DISPLAY_CATEGORIES_ON_MENU = False
DISPLAY_PAGES_ON_MENU = False

# ... list menu voices as you want
MENUITEMS = (
        ('News', '/news/'),
        ('Blog', '/blog/'),
        ('Progetti', '/progetti/'),
        ('Nemo', '/nemo/'),
        ('A.I.', '/ai.html'),
        ('Archivi', '/archives.html'),
        ('Contatti', '/contattami.html'),
    )

###############
###         ###
### Plugins ###
###         ###
###############

PLUGIN_PATHS = [
  'plugins'
]

PLUGINS = [
  'neighbors', # pip installed
  'static_comments_plus',
  'readtime', # pip installed
  'pelican.plugins.series', # pip installed
  'bootstrap-rst',
  'pelican_youtube', #pip installed
  'pelican_vimeo', #pip installed
  'webassets', #pip installed
  'sitemap', #pip installed
  'tipue_search'
]

# Sitemap
SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.6,
        'indexes': 0.5,
        'pages': 0.4
    },
    'changefreqs': {
        'articles': 'weekly',
        'indexes': 'weekly',
        'pages': 'monthly'
    }
}

# Static comments plus
STATIC_COMMENTS_PLUS = True
STATIC_COMMENTS_DIR = 'commenti'
STATIC_COMMENTS_SOURCE = 'RST'
SHOW_COMMENTS = True

# Readtime
READTIME_WPM = {
     'it': {
        'wpm': 190,
        'min_singular': 'minuto',
        'min_plural': 'minuti',
        'sec_singular': 'secondo',
        'sec_plural': 'secondi'
    }
}

THEME = 'themes/Z'

###############################
###                         ###
### Theme specific settings ###
###                         ###
###############################

# Import the date and extract the current year
# if you need a dynamic copyright year
from datetime import date
COPY_DATE = u'2018 - '
DCOPY_DATE = date.today().year

# If set to 'True' hide the copyright
# note and shows a CC statement
CC_LICENSE = False

# Set a custom footer
FOOTER_INCLUDE = 'Zfooter.html'
IGNORE_FILES = [FOOTER_INCLUDE]
THEME_TEMPLATES_OVERRIDE = [os.path.dirname(__file__)]

# Set a common header for all contents
# If you do not specify a different image or
# color on each page, this one will be used
HEADER_COLOR = '#242323'
HEADER_COVER = 'img/banner/main.jpg'
FORCE_TWITTER_IMAGE = True
TWITTER_IMAGE = 'img/banner/twitter-image.jpg'

# Show social icons in footer
SOCIAL = (('github', 'https://github.com/mpaglia0'),
          ('twitter', 'https://twitter.com/mpaglia0'),
          ('envelope','/contattami.html'))

# Color scheme for code blocks
COLOR_SCHEME_CSS = 'darkly.css'

# Customized CSS
CSS_OVERRIDE = 'assets/css/mp.css'

# Set it to 'True' if you need to use your own js
ENABLE_CUSTOM_THEME_JAVASCRIPT = False

# Jinja config - Pelican 4
JINJA_ENVIRONMENT = {
  'extensions' :[
    'jinja2.ext.loopcontrols',
    'jinja2.ext.i18n',
    'jinja2.ext.with_',
    'jinja2.ext.do'
  ]
}

# custom Jinja2 filter for localizing theme
def gettext(string, lang):
    if lang == 'en':
        return string
    elif lang == 'it':
      if string == 'Archives': return 'Archivi'
      elif string == 'Archives for dates': return 'Archivi per data'
      elif string == 'Posted by': return 'Pubblicato da'
      elif string == 'Updated on': return 'Aggiornato il'
      elif string == 'Articles by': return 'Articoli di'
      elif string == 'Articles in the': return 'Articoli in'
      elif string == 'Authors': return 'Autori'
      elif string == 'Categories': return 'Sezioni'
      elif string == 'Articles in': return 'Articoli in'
      elif string == 'category': return ''
      elif string == 'Year': return 'Anno'
      elif string == 'Day': return 'Giorno'
      elif string == 'There are': return 'Ci sono'
      elif string == 'comments': return 'commenti'
      elif string == 'Permalink to': return 'Leggi...'
      elif string == 'Older Posts': return 'Articoli meno recenti'
      elif string == 'Newest Posts': return 'Articoli più recenti'
      elif string == 'Page': return 'Pagina'
      elif string == 'Tags for': return 'Etichette in'
      elif string == 'Tags': return 'Etichette'
      elif string == 'Tag': return 'Etichetta'
      elif string == 'tags': return 'etichette'
      elif string == 'on': return 'il'
      elif string == 'All rights reserved': return 'Tutti i diritti riservati'
      elif string == 'search...': return 'cerca...'
      elif string == 'Search results': return 'Risultati della ricerca'
      elif string == 'Comments': return 'Commenti'
      elif string == 'Name': return 'Nome'
      elif string == 'Website': return 'Sito web'
      elif string == 'Comment': return 'Commento'
      elif string == 'This field is mandatory': return 'Campo richiesto'
      elif string == 'This field is optional': return 'Campo opzionale'
      elif string == 'Submit': return 'Invia'
      elif string == 'Click to return on top': return 'Torna all\'inizio'
      elif string == 'Read time, about': return 'Tempo di lettura, circa'
      elif string == 'minute(s)': return 'minuti'
      elif string == 'Would you like to be the first to leave a comment? I will be happy!': return 'Vuoi essere il primo a lasciare un commento? Ne sarei felice!'
      elif string == 'Mandatory': return 'Richiesto'
      elif string == 'Optional': return 'Opzionale'
      elif string == 'Your email': return 'La tua email'
      elif string == 'Please enter here your name': return 'Inserisci qui il tuo nome'
      elif string == 'Please enter here a valid email address': return 'Inserisci un indirizzo email valido'
      elif string == 'Please enter here your website address': return 'Inserisci qui l\'indirizzo del tuo sito web'
      elif string == 'Please enter here your comment': return 'Inserisci qui il tuo commento'
      elif string == 'You can leave a comment filling this form!': return 'Puoi lasciare un commento anche tu usando questo form!'
      elif string == 'This post is part': return 'Questo è il capitolo'
      elif string == 'of series': return 'della serie'
      elif string == 'Next part': return 'Prossimo capitolo'
      elif string == 'Previous part': return 'Capitolo precedente'
      elif string == 'Go to index': return 'Vai all\'indice'
      elif string == 'Blog powered by': return 'Questo sito web è stato creato con'
      elif string == 'which takes great advantage of': return 'un generatore SSG scritto in'
      elif string == 'Build Framework and Graphic theme': return 'Piattaforma di Sviluppo e Tema Grafico'
      elif string == 'Show/Hide Comments': return 'Mostra/Nascondi i commenti'
      elif string == 'This is lesson': return 'Questa è la lezione'
      elif string == 'of course': return 'del corso'
      elif string == 'Previous lesson': return 'Lezione precedente'
      elif string == 'Next lesson': return 'Lezione successiva'
      elif string == 'Go to start': return 'Vai all\'inizio'
      elif string == 'INDEX': return 'INDICE'
      elif string == 'Show index': return 'Mostra indice'
      else: return string

JINJA_FILTERS = {
     'gettext': gettext,
     'format': lambda x, *y, **z: x.format(*y, **z)
}

**Comment by mpaglia0** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*- #

from __future__ import unicode_literals
import os
import sys
sys.path.append(os.curdir)

AUTHOR = 'Maurizio'
SITENAME = 'MaurizioPaglia.it'
SITELOGO = '/assets/MPOnda.png'
SITESUBTITLE = 'Fotografie à la carte, con contorno'
# Leave SITEURL='' and set your domain in publishconf.py
SITEURL=''

# Path of source files
PATH = 'content'

DEFAULT_DATE = 'fs'
DEFAULT_DATE_FORMAT = '%d/%m/%Y'
TIMEZONE = 'UTC'
DEFAULT_LANG = 'it'
LOCALE = 'it_IT.UTF-8'

# By default, use agressive caching.
# The Makefile ensures we use `--ignore-cache` for production builds.
#CACHE_PATH = 'cache'
#CACHE_CONTENT = True
#LOAD_CONTENT_CACHE = True
#CHECK_MODIFIED_METHOD = 'md5'
WITH_FUTURE_DATES = False

# Adds some nice effects to text
TYPOGRIFY = True

# Max words to use for summary
SUMMARY_MAX_LENGTH = 55
SUMMARY_END_SUFFIX = ' …'

# Feed generation is usually not desired when developing
# Set these values only in publishconf.py
FEED_ALL_ATOM = None
FEED_ALL_RSS = None
CATEGORY_FEED_ATOM = None
CATEGORY_FEED_RSS = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

# Blogroll
LINKS = (('Pelican', 'https://getpelican.com/'),
         ('Python.org', 'https://www.python.org/'),
         ('Jinja2', 'https://palletsprojects.com/p/jinja/'),
         ('You can modify those links in your config file', '#'),)

# Pagination
DEFAULT_PAGINATION = 5
DEFAULT_ORPHANS = 4
ARTICLE_ORDER_BY = 'reversed-date'
PAGINATION_PATTERNS = (
   (1, '{base_name}/', '{base_name}/index.html'),
   (2, '{base_name}/pagina/{number}/', '{base_name}/pagina/{number}/index.html'),
)

STATIC_PATHS = ['assets', 'blog', 'img', 'nemo', 'news', 'pages', 'progetti']
EXTRA_PATH_METADATA = {
    'assets/robots.txt': {'path': 'robots.txt'},
    'assets/favicon.ico': {'path': 'favicon.ico'},
    'assets/htaccess': {'path': '.htaccess'},
}

DIRECT_TEMPLATES = ['index', 'tags',  'archives', 'search', 'categories']

# Post and Pages path
ARTICLE_URL = '{date:%Y}/{date:%m}/{slug}'
ARTICLE_SAVE_AS = '{date:%Y}/{date:%m}/{slug}.html'

PAGE_URL = '{slug}'
PAGE_SAVE_AS = '{slug}.html'

YEAR_ARCHIVE_SAVE_AS = '{date:%Y}/index.html'
MONTH_ARCHIVE_SAVE_AS = '{date:%Y}/{date:%m}/index.html'

# Tags and Category path
CATEGORY_URL = '{slug}'
CATEGORY_SAVE_AS = '{slug}.html'
CATEGORIES_SAVE_AS = 'categorie/index.html'

DRAFT_URL = ''
DRAFT_SAVE_AS = ''

TAG_URL = '{slug}'
TAG_SAVE_AS = '{slug}.html'
TAGS_SAVE_AS = 'tags.html'

# Save the index.html template for blog only
# since the actual index.html will be different
#INDEX_SAVE_AS = 'genindex.html'

# Author
# This is the standard Pelican structure
AUTHOR_URL = ''
AUTHOR_SAVE_AS = ''
AUTHORS_SAVE_AS = ''
# And this is a static author page
# it works only if above settings are BLANKS ('')
SINGLE_AUTHOR_SAVE_AS = 'mi-presento.html'

# In this way all contents are created with status = draft
# unless a status = published is stated on each single content
DEFAULT_METADATA = {
   'status': 'draft',
   'author': 'Maurizio',
   'og_image': 'img/banner/og-image.jpg'
}

# Do not use Categories and Pages for the menu but...
DISPLAY_CATEGORIES_ON_MENU = False
DISPLAY_PAGES_ON_MENU = False

# ... list menu voices as you want
MENUITEMS = (
        ('News', '/news/'),
        ('Blog', '/blog/'),
        ('Progetti', '/progetti/'),
        ('Nemo', '/nemo/'),
        ('A.I.', '/ai.html'),
        ('Archivi', '/archives.html'),
        ('Contatti', '/contattami.html'),
    )

###############
###         ###
### Plugins ###
###         ###
###############

PLUGIN_PATHS = [
  'plugins'
]

PLUGINS = [
  'neighbors', # pip installed
  'static_comments_plus',
  'readtime', # pip installed
  'pelican.plugins.series', # pip installed
  'bootstrap-rst',
  'pelican_youtube', #pip installed
  'pelican_vimeo', #pip installed
  'webassets', #pip installed
  'sitemap', #pip installed
  'tipue_search'
]

# Sitemap
SITEMAP = {
    'format': 'xml',
    'priorities': {
        'articles': 0.6,
        'indexes': 0.5,
        'pages': 0.4
    },
    'changefreqs': {
        'articles': 'weekly',
        'indexes': 'weekly',
        'pages': 'monthly'
    }
}

# Static comments plus
STATIC_COMMENTS_PLUS = True
STATIC_COMMENTS_DIR = 'commenti'
STATIC_COMMENTS_SOURCE = 'RST'
SHOW_COMMENTS = True

# Readtime
READTIME_WPM = {
     'it': {
        'wpm': 190,
        'min_singular': 'minuto',
        'min_plural': 'minuti',
        'sec_singular': 'secondo',
        'sec_plural': 'secondi'
    }
}

THEME = 'themes/Z'

###############################
###                         ###
### Theme specific settings ###
###                         ###
###############################

# Import the date and extract the current year
# if you need a dynamic copyright year
from datetime import date
COPY_DATE = u'2018 - '
DCOPY_DATE = date.today().year

# If set to 'True' hide the copyright
# note and shows a CC statement
CC_LICENSE = False

# Set a custom footer
FOOTER_INCLUDE = 'Zfooter.html'
IGNORE_FILES = [FOOTER_INCLUDE]
THEME_TEMPLATES_OVERRIDE = [os.path.dirname(__file__)]

# Set a common header for all contents
# If you do not specify a different image or
# color on each page, this one will be used
HEADER_COLOR = '#242323'
HEADER_COVER = 'img/banner/main.jpg'
FORCE_TWITTER_IMAGE = True
TWITTER_IMAGE = 'img/banner/twitter-image.jpg'

# Show social icons in footer
SOCIAL = (('github', 'https://github.com/mpaglia0'),
          ('twitter', 'https://twitter.com/mpaglia0'),
          ('envelope','/contattami.html'))

# Color scheme for code blocks
COLOR_SCHEME_CSS = 'darkly.css'

# Customized CSS
CSS_OVERRIDE = 'assets/css/mp.css'

# Set it to 'True' if you need to use your own js
ENABLE_CUSTOM_THEME_JAVASCRIPT = False

# Jinja config - Pelican 4
JINJA_ENVIRONMENT = {
  'extensions' :[
    'jinja2.ext.loopcontrols',
    'jinja2.ext.i18n',
    'jinja2.ext.with_',
    'jinja2.ext.do'
  ]
}

# custom Jinja2 filter for localizing theme
def gettext(string, lang):
    if lang == 'en':
        return string
    elif lang == 'it':
      if string == 'Archives': return 'Archivi'
      elif string == 'Archives for dates': return 'Archivi per data'
      elif string == 'Posted by': return 'Pubblicato da'
      elif string == 'Updated on': return 'Aggiornato il'
      elif string == 'Articles by': return 'Articoli di'
      elif string == 'Articles in the': return 'Articoli in'
      elif string == 'Authors': return 'Autori'
      elif string == 'Categories': return 'Sezioni'
      elif string == 'Articles in': return 'Articoli in'
      elif string == 'category': return ''
      elif string == 'Year': return 'Anno'
      elif string == 'Day': return 'Giorno'
      elif string == 'There are': return 'Ci sono'
      elif string == 'comments': return 'commenti'
      elif string == 'Permalink to': return 'Leggi...'
      elif string == 'Older Posts': return 'Articoli meno recenti'
      elif string == 'Newest Posts': return 'Articoli più recenti'
      elif string == 'Page': return 'Pagina'
      elif string == 'Tags for': return 'Etichette in'
      elif string == 'Tags': return 'Etichette'
      elif string == 'Tag': return 'Etichetta'
      elif string == 'tags': return 'etichette'
      elif string == 'on': return 'il'
      elif string == 'All rights reserved': return 'Tutti i diritti riservati'
      elif string == 'search...': return 'cerca...'
      elif string == 'Search results': return 'Risultati della ricerca'
      elif string == 'Comments': return 'Commenti'
      elif string == 'Name': return 'Nome'
      elif string == 'Website': return 'Sito web'
      elif string == 'Comment': return 'Commento'
      elif string == 'This field is mandatory': return 'Campo richiesto'
      elif string == 'This field is optional': return 'Campo opzionale'
      elif string == 'Submit': return 'Invia'
      elif string == 'Click to return on top': return 'Torna all\'inizio'
      elif string == 'Read time, about': return 'Tempo di lettura, circa'
      elif string == 'minute(s)': return 'minuti'
      elif string == 'Would you like to be the first to leave a comment? I will be happy!': return 'Vuoi essere il primo a lasciare un commento? Ne sarei felice!'
      elif string == 'Mandatory': return 'Richiesto'
      elif string == 'Optional': return 'Opzionale'
      elif string == 'Your email': return 'La tua email'
      elif string == 'Please enter here your name': return 'Inserisci qui il tuo nome'
      elif string == 'Please enter here a valid email address': return 'Inserisci un indirizzo email valido'
      elif string == 'Please enter here your website address': return 'Inserisci qui l\'indirizzo del tuo sito web'
      elif string == 'Please enter here your comment': return 'Inserisci qui il tuo commento'
      elif string == 'You can leave a comment filling this form!': return 'Puoi lasciare un commento anche tu usando questo form!'
      elif string == 'This post is part': return 'Questo è il capitolo'
      elif string == 'of series': return 'della serie'
      elif string == 'Next part': return 'Prossimo capitolo'
      elif string == 'Previous part': return 'Capitolo precedente'
      elif string == 'Go to index': return 'Vai all\'indice'
      elif string == 'Blog powered by': return 'Questo sito web è stato creato con'
      elif string == 'which takes great advantage of': return 'un generatore SSG scritto in'
      elif string == 'Build Framework and Graphic theme': return 'Piattaforma di Sviluppo e Tema Grafico'
      elif string == 'Show/Hide Comments': return 'Mostra/Nascondi i commenti'
      elif string == 'This is lesson': return 'Questa è la lezione'
      elif string == 'of course': return 'del corso'
      elif string == 'Previous lesson': return 'Lezione precedente'
      elif string == 'Next lesson': return 'Lezione successiva'
      elif string == 'Go to start': return 'Vai all\'inizio'
      elif string == 'INDEX': return 'INDICE'
      elif string == 'Show index': return 'Mostra indice'
      else: return string

JINJA_FILTERS = {
     'gettext': gettext,
     'format': lambda x, *y, **z: x.format(*y, **z)
}

**Comment by avaris** [comment]
I tried to replicate the issue but no luck. Does it help if you rebuild the cache with `--ignore-cache` option?

**Comment by mpaglia0** [comment]
Launched `pelican --ignore-cache` and I still see a warning message that says
WARNING  Could not save cache                                                                     log.py:91
                    /home/mau/Sistema/pelican-web/mauriziopaglia/cache/ArticlesGenerator-Readers                      
                     ... Can't pickle <function gettext at 0x7fc3479f1730>: it's not the same object as               
                    pelicanconf.gettext  

If I launch `pelican` it stops rather immediatly with critical message
CRITICAL EOFError: Ran out of input                                                         __init__.py:566

**Comment by mpaglia0** [comment]
Here below the output of `pelican --debug`
CRITICAL EOFError: Ran out of input                                                         __init__.py:566
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py:562 in main        │
│                                                                                                  │
│   559 │   │   │   watcher = FileSystemWatcher(args.settings, Readers, settings)                  │
│   560 │   │   │   watcher.check()                                                                │
│   561 │   │   │   with console.status("Generating..."):                                          │
│ ❱ 562 │   │   │   │   pelican.run()                                                              │
│   563 │   except KeyboardInterrupt:                                                              │
│   564 │   │   logger.warning('Keyboard interrupt received. Exiting.')                            │
│   565 │   except Exception as e:                                                                 │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py:102 in run         │
│                                                                                                  │
│    99 │   │   │   │   path=self.path,                                                            │
│   100 │   │   │   │   theme=self.theme,                                                          │
│   101 │   │   │   │   output_path=self.output_path,                                              │
│ ❱ 102 │   │   │   ) for cls in self._get_generator_classes()                                     │
│   103 │   │   ]                                                                                  │
│   104 │   │                                                                                      │
│   105 │   │   # Delete the output directory if (1) the appropriate setting is True               │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/__init__.py:102 in <listcomp>  │
│                                                                                                  │
│    99 │   │   │   │   path=self.path,                                                            │
│   100 │   │   │   │   theme=self.theme,                                                          │
│   101 │   │   │   │   output_path=self.output_path,                                              │
│ ❱ 102 │   │   │   ) for cls in self._get_generator_classes()                                     │
│   103 │   │   ]                                                                                  │
│   104 │   │                                                                                      │
│   105 │   │   # Delete the output directory if (1) the appropriate setting is True               │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/generators.py:302 in __init__  │
│                                                                                                  │
│   299 │   │   self.categories = defaultdict(list)                                                │
│   300 │   │   self.related_posts = []                                                            │
│   301 │   │   self.authors = defaultdict(list)                                                   │
│ ❱ 302 │   │   super().__init__(*args, **kwargs)                                                  │
│   303 │   │   signals.article_generator_init.send(self)                                          │
│   304 │                                                                                          │
│   305 │   def generate_feeds(self, writer):                                                      │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/generators.py:237 in __init__  │
│                                                                                                  │
│   234 │   │   cls_name = self.__class__.__name__                                                 │
│   235 │   │   Generator.__init__(self, *args,                                                    │
│   236 │   │   │   │   │   │      readers_cache_name=(cls_name + '-Readers'),                     │
│ ❱ 237 │   │   │   │   │   │      **kwargs)                                                       │
│   238 │   │                                                                                      │
│   239 │   │   cache_this_level = \                                                               │
│   240 │   │   │   self.settings['CONTENT_CACHING_LAYER'] == 'generator'                          │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/generators.py:43 in __init__   │
│                                                                                                  │
│    40 │   │   for arg, value in kwargs.items():                                                  │
│    41 │   │   │   setattr(self, arg, value)                                                      │
│    42 │   │                                                                                      │
│ ❱  43 │   │   self.readers = Readers(self.settings, readers_cache_name)                          │
│    44 │   │                                                                                      │
│    45 │   │   # templates cache                                                                  │
│    46 │   │   self._templates = {}                                                               │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/readers.py:534 in __init__     │
│                                                                                                  │
│   531 │   │   │   │   │   │   │   self.settings['CONTENT_CACHING_LAYER'] == 'reader')            │
│   532 │   │   caching_policy = cache_this_level and self.settings['CACHE_CONTENT']               │
│   533 │   │   load_policy = cache_this_level and self.settings['LOAD_CONTENT_CACHE']             │
│ ❱ 534 │   │   super().__init__(settings, cache_name, caching_policy, load_policy)                │
│   535 │                                                                                          │
│   536 │   @property                                                                              │
│   537 │   def extensions(self):                                                                  │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/cache.py:81 in __init__        │
│                                                                                                  │
│    78 │   │   and base path for filestamping operations                                          │
│    79 │   │   """                                                                                │
│    80 │   │                                                                                      │
│ ❱  81 │   │   super().__init__(settings, cache_name, caching_policy, load_policy)                │
│    82 │   │                                                                                      │
│    83 │   │   method = self.settings['CHECK_MODIFIED_METHOD']                                    │
│    84 │   │   if method == 'mtime':                                                              │
│                                                                                                  │
│ /home/mau/Sistema/pelican-web/lib/python3.6/site-packages/pelican/cache.py:33 in __init__        │
│                                                                                                  │
│    30 │   │   if load_policy:                                                                    │
│    31 │   │   │   try:                                                                           │
│    32 │   │   │   │   with self._cache_open(self._cache_path, 'rb') as fhandle:                  │
│ ❱  33 │   │   │   │   │   self._cache = pickle.load(fhandle)                                     │
│    34 │   │   │   except (OSError, UnicodeDecodeError) as err:                                   │
│    35 │   │   │   │   logger.debug('Cannot load cache %s (this is normal on first '              │
│    36 │   │   │   │   │   │   │    'run). Proceeding with empty cache.\n%s',                     │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
EOFError: Ran out of input

**Comment by avaris** [comment]
Good news: I was able to reproduce the issue. The problem is this one:

```python
JINJA_FILTERS = {
     'gettext': gettext,
     'format': lambda x, *y, **z: x.format(*y, **z)
}
```

It stores functions defined in `pelicanconf` in settings which are then stored in other objects such as `Author` etc. While saving the cache that contains any object retaining settings, `pickle` is complaining... because of reasons that are a bit too complicated.

Bad news: This is not easy to solve. It might require rethinking the caching mechanism, even.

**Comment by avaris** [comment]
OK, a bit more good news I suppose. Here is a workaround. First of all, `lambda` is a no-go. It needs to be a function. Extract these functions to another file, say `myfunctions.py` next to your `pelicanconf.py`:

```python
def gettext(string, lang):
     # ....


def format(x, *y, **z):
     return x.format(*y, **z)
```

and then in `pelicanconf` you can do:

```python
import myfunctions
JINJA_FILTERS = {
     'gettext': myfunctions.gettext,
     'format': myfunctions.format,
}
```

This makes `pickle` happy enough.

A word of warning though, with this workaround if you modify these functions I'd highly suggest clearing and rebuilding the cache.

**Comment by mpaglia0** [comment]
Dear Deniz,
first of all thank you indeed for your kind attention.
These are really good news.
As soon as possible I will do some test on my PC and will post here the
results.

Have a nice day!
Maurizio

Il giorno mer 19 ott 2022 alle ore 01:46 Deniz Turgut <
***@***.***> ha scritto:

**Comment by mpaglia0** [comment]
This solution works!
By the way with the `myfunctions.py` file it is all more elegant since I can keep all translated strings there and `pelicanconf.py` looks less cluttered.
