### ISSUE TITLE
HTML files are not found with {static}

### ISSUE THREAD

**Issue by whateverforever** [getpelican/pelican#3045]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: macOS 12.0.1
- **Python version**: 3.10.6
- **Pelican version**: 4.8.0

## Issue

Having the files structured such as this:

```
content/some_entry
├── some_image.jpg
├── my_page.md
├── static_page.html
└── other_image.png
```

I can't link to `static_page.html`, which used to be possible with older versions of pelican (last time I used it has been a few years, not sure which version I used at the time).

The linking is done like this: 

```
some link to [static_page]({static}static_page.html)
```

During page generation, I get the following warning:

```
[21:58:46] WARNING  Unable to find 'static_page.html', skipping url replacement.                                                                                                                                                              log.py:91
```

Linking to the other static files, like images and videos works fine. It's just html files that don't work.

Cheers

**Comment by emibarrod** [comment]
You shouldn't use `{static}` to link a page. Probably you just have to delete the `{static}` part:

```
some link to [static_page](static_page.html)
```

Another way is to follow the documentation on internal links: [linking to internal content](https://docs.getpelican.com/en/stable/content.html#linking-to-internal-content).
Your confusion is probably due to thinking that a static file is a static page. In Pelican static file is, for example, an image or a video, but not an HTML.

If that doesn't work, could you share your settings file?

**Comment by justinmayer** [comment]
@whateverforever: Is there anything else we can do to help you with this issue?

**Comment by whateverforever** [comment]
Hey, thanks for your replies. That seems to have worked to some degree. The file is being found and copied into the output folder. However, the link on the page that links to the HTML is not correct. It tries to find the file at `blog.domain/static_page.html`, when it actually was copied into a subfolder (mirroring the structure of my markdown files):

```
.
├── ...
├── my_subfolder
│   └── static_page.html
├── my-blog-post-slug.html
├── index.html
├── rss
├── sitemap.xml
└── ...
```

My pelicanconf.py is the following:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*- #
from __future__ import unicode_literals

AUTHOR = "..."
SITENAME = "..."
SITEURL = ""
SITEDESCRIPTION = "..."
LOGO = "./..."

# Theme_conf:
FIRST_NAME = "..."

PATH = "content"

TIMEZONE = "Europe/Paris"

DEFAULT_LANG = "de"

# Feed generation is usually not desired when developing
FEED_ALL_ATOM = None
CATEGORY_FEED_ATOM = None
TRANSLATION_FEED_ATOM = None
AUTHOR_FEED_ATOM = None
AUTHOR_FEED_RSS = None

DEFAULT_PAGINATION = 10

# Uncomment following line if you want document-relative URLs when developing
# RELATIVE_URLS = True

PLUGIN_PATHS = ["./plugins"]
PLUGINS = [
    "sitemap",
    "optimize_images",
    "latex_prerender",
    "clean_summary",
    "deadlinks",
]

DEADLINK_VALIDATION = True
DEADLINK_OPTS = {"archive": False}

SITEMAP = {
    "format": "xml",
    "priorities": {"articles": 0.99, "pages": 0.75, "indexes": 0.5},
    "changefreqs": {"articles": "weekly", "pages": "monthly", "indexes": "weekly"},
}

THEME = "./themes/brutalist"

SUMMARY_MAX_LENGTH = 50
```

publishconf

```
# This file is only used if you use `make publish` or
# explicitly specify it as your config file.

import os
import sys

sys.path.append(os.curdir)
from pelicanconf import *

# If your site is available via HTTPS, make sure SITEURL begins with https://
SITEURL = "..."
RELATIVE_URLS = False

FEED_ALL_ATOM = None  # "feeds/all.atom.xml"
CATEGORY_FEED_ATOM = None  # "feeds/{slug}.atom.xml"

FEED_RSS = "rss"
FEED_DOMAIN = SITEURL

DELETE_OUTPUT_DIRECTORY = True

# Following items are often useful when publishing

# DISQUS_SITENAME = ""
# GOOGLE_ANALYTICS = ""
```

**Comment by avaris** [comment]
Well, `{static}path/to/file` was correct and you should keep it like that to have proper links. One suggestion that comes to mind is disabling `html` reader so that `.html` files are not considered for regular content, in your config:

```python
READERS = {'html': None}
```

Otherwise I'd double check the paths are correct and you're following the [docs](https://docs.getpelican.com/en/stable/content.html#linking-to-internal-content) (i.e. `{static}path/to/file` vs `{static}/path/to/file`)

**Comment by emibarrod** [comment]
Try this:

```
some link to [static_page](subfolder_name/static_page.html
```

**Comment by whateverforever** [comment]
> Well, `{static}path/to/file` was correct and you should keep it like that to have proper links. One suggestion that comes to mind is disabling `html` reader so that `.html` files are not considered for regular content, in your config:
> 
> ```python
> READERS = {'html': None}
> ```
> 
> Otherwise I'd double check the paths are correct and you're following the [docs](https://docs.getpelican.com/en/stable/content.html#linking-to-internal-content) (i.e. `{static}path/to/file` vs `{static}/path/to/file`)

great, that seems to have done the trick, thank you!

> Try this:
> 
> ```
> some link to [static_page](subfolder_name/static_page.html
> ```

thank you for your reply. While that would have worked, I want to avoid including information in the markdown file that relates to the independent folder structure above. The file shouldn't need to know about that sort of stuff

**Comment by justinmayer** [comment]
Glad you seem to have found a solution to the problem you experienced. ✨
