### ISSUE TITLE
Python 3.8.8: ImportError: cannot import name 'OrderedDict' from 'typing_extensions'

### ISSUE THREAD

**Issue by bmcguirk** [getpelican/pelican#3047]
Tried running `pelican-quickstart` just after installing. Running Python 3.8.8 on Macbook Pro M1: 

> (base) ➜  pelikan-test `pelican-quickstart`
> Traceback (most recent call last):
>   File "/Users/[me]/opt/anaconda3/bin/pelican-quickstart", line 6, in <module>
>     from pelican.tools.pelican_quickstart import main
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/pelican/__init__.py", line 19, in <module>
>     from pelican.log import console
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/pelican/log.py", line 4, in <module>
>     from rich.console import Console
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/console.py", line 46, in <module>
>     from ._log_render import FormatTimeCallable, LogRender
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/_log_render.py", line 5, in <module>
>     from .text import Text, TextType
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/text.py", line 5, in <module>
>     from rich.emoji import EmojiVariant
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/emoji.py", line 4, in <module>
>     from .jupyter import JupyterMixin
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/jupyter.py", line 4, in <module>
>     from .segment import Segment
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/segment.py", line 19, in <module>
>     from .cells import (
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/cells.py", line 6, in <module>
>     from ._lru_cache import LRUCache
>   File "/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/rich/_lru_cache.py", line 8, in <module>
>     from typing_extensions import OrderedDict
> ImportError: cannot import name 'OrderedDict' from 'typing_extensions' (/Users/[me]/opt/anaconda3/lib/python3.8/site-packages/typing_extensions.py)

Running `pelican --debug` gives exactly the same error.

Installed via `conda install -c conda-forge pelican`.

**Comment by bmcguirk** [comment]
Ok, must be related to that version of Python and/or the M1 chip, because I ran `conda install anaconda=2022.05` and now `pelican-quickstart` works. You folks can close this issue, I think.

**Comment by justinmayer** [comment]
Thanks for the update, Brian. Glad to hear everything is running smoothly. ✨
