### ISSUE TITLE
Using article.content makes intra-site links not resolving

### ISSUE THREAD

**Issue by renyuneyun** [getpelican/pelican#3053]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Arch Linux
- **Python version**: 3.10.8
- **Pelican version**: 4.8.0
- **Link to theme**: https://github.com/renyuneyun/simplify-theme.git
- **Links to plugins**: https://github.com/getpelican/pelican-plugins.git , https://github.com/renyuneyun/pelican-interrefs.git
- **Link to your site**: https://blog.ryey.icu
- **Link to your source**: https://gitlab.com/renyuneyun/renyuneyun.gitlab.io

## Issue

This issue is related to plugin development. 

I'm developing the [interrefs](https://github.com/renyuneyun/pelican-interrefs.git) plugin listed above. To accomplish its functionality, I need to get the list of links contained in each article, and determine whether they are internal/intra-site links to other articles or not.
This list for all articles needs to be obtained first, and then used on each article. That means, I need to loop through all articles first, and then loop through each article for a specific task.

Therefore, I registered the `article_generator_finalized.connect` signal. Then, inside the first loop, I used BeautifulSoup to parse the content.

If I use `article._content`, the rendering works correctly. But I will get incorrect list, because the internal links (e.g. `{filename}article2.rst`) are not resolved.

But if I use `article.content`, the internal links get resolved. However, in the generated outputs (html), the images are not resolved any more -- they are `{static}/my-image.png`.

This seems to be a bug related to the resolution of the internal links. I would expect the content of `article.content` to be consistent with the output without me using them in the plugin.
Maybe this is related to the order of how the relevant bits are called?

**Comment by avaris** [comment]
It is not a bug, `article_generator_finalized` is too early to resolve static files (see [warning](https://docs.getpelican.com/en/latest/plugins.html#list-of-signals) here). Also note that `article.content` is cached. Once you access it, it will be "fixed".

`article.content` cannot be consistent because it depends on *where* it was accessed in the case of `RELATIVE_URLS = True`.

**Comment by renyuneyun** [comment]
Forget to update: thanks for the information. I have switched to using other signals and get it solved. Though, the method now is quite unintuitive.
