### ISSUE TITLE
How to creat numbered lists in content

### ISSUE THREAD

**Issue by yxwangnju** [getpelican/pelican#3059]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
How to creat numbered list in content? I tried using the following markdown code
```markdown
1. aaa
2. bbb
3. ccc
```

But it shows a bullet list.

**Comment by justinmayer** [comment]
Hi Audrey. I cannot replicate the behavior you describe, which indicates the likely cause is something in your theme, plugins, and/or settings. Please take a look at the [How to Get Help](https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help) section and follow the instructions there.

**Comment by jorgesumle** [comment]
Eso debería funcionar bien. A unas malas puedes usar HTML:

```
<ol>
<li>primero</li>
<li>segundo</li>
</ol>
```

**Comment by justinmayer** [comment]
As Jorge said, the provided Markdown should indeed yield a bullet list, and in the worst-case scenario, one can always fall back to HTML.

@yxwangnju: If we can be of further assistance, please let us know.
