### ISSUE TITLE
Troubleshooting _extremely_ slow site generation

### ISSUE THREAD

**Issue by offbyone** [getpelican/pelican#3071]
- [X] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: macOS Ventura 13.0.1 (22A400)
- **Python version**: 3.10.2
- **Pelican version**: 4.8.0
- **Link to theme**: https://github.com/offbyone/ideas/tree/main/themes/offby1
- **Links to plugins**: https://github.com/offbyone/ideas/blob/main/pelicanconf.py#L92-L101
- **Link to your site**: https://offby1.website/
- **Link to your source**: https://github.com/offbyone/ideas

## Issue

Hey, folks. Recently, I've found that my site generation is extremely slow. I'm talking over ten minutes to generate the content; previously it was seconds. It's not clear to me why, and I've been struggling to instrument the generation process because of how parallelized it is.  I can see, for example, when running in verbose mode, that each article is taking several seconds to generate, but I'm not able to quantify it.

```
Done: Processed 35 articles, 604 drafts, 0 hidden articles, 6 pages, 0 hidden pages and 1 draft page in 785.25
seconds
```

I'd love some help speeding this up, mostly because it makes the process of editing and adding new posts extremely painful, since each time I save content, I have to wait for the server to regenerate all of the content (so, 10+ minutes) before I can see the change.

I had recently made a plugin change (moving from a pure regexp twitter embedder to one that parsed the documents into a BeautifulSoup DOM and made smart embedding changes, but when I disable that plugin I still see the slow performance)

I can see from the [remote actions runs](https://github.com/offbyone/ideas/actions) that this issue is local to my laptop; there's no appreciable speed change in the publish flow, just in my working directory. I'd love to know how I can narrow this down and get my editing workflow performant again. Advice and bugfixes are welcome!

**Comment by offbyone** [comment]
I triangulated this to a plugin update: pelican-plugins/photos#70

My general question about "how to do this in general" still stands, so I'm leaving this open :)

**Comment by justinmayer** [comment]
Until some future day when someone submits a PR adding a performance profiling feature to Pelican, I think the kind of trial-and-error mentioned in this issue — in this case, disabling all plugins and re-enabling them one-by-one to find the problem plugin — is the best approach.
