### ISSUE TITLE
RTL support for languages written from Right to Left

### ISSUE THREAD

**Issue by damascene** [getpelican/pelican#3086]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Few languages are written from right to left like, Arabic, Persian Urdu and Hebrew. To display those languages correctly it requires direction support.

For more info https://rtlcss.com/learn/

It might simple to change by converting the css using `rtlcss`:
https://rtlcss.com/playground/ 

Other python static site generator that supports RTL:
https://squidfunk.github.io/mkdocs-material/setup/changing-the-language/#directionality

This might be more related to Theme but user should be able to set directionality in config file and standard theme should support it at least.

**Comment by justinmayer** [comment]
I don't have any experience with right-to-left languages, so I am not an ideal person to work on this issue. If someone would like to volunteer to work on a proposal to implement some kind of official support for right-to-left languages in Pelican, please submit that in the form of a pull request. Thank you!
