### ISSUE TITLE
Updating live site

### ISSUE THREAD

**Issue by ben-n93** [getpelican/pelican#3090]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

Apologies if this is made clear in the Docs but I've published my site using Github pages. However I realise I should have added something to the `pelicanconf.py` file but it seems to have disappeared.

Any advice would be appreciated, thanks.

**Comment by davidag** [comment]
It looks like you have deleted everything in your `main` branch: https://github.com/ben-n93/ben-n93.github.io/commits/main (assuming that is the repo you're talking about). You might want to [recover an old commit](https://medium.com/coder-nomad/how-to-reset-your-git-branch-to-a-previous-commit-both-local-and-remote-55e0351dca2b).

**Comment by ben-n93** [comment]
> It looks like you have deleted everything in your `main` branch: https://github.com/ben-n93/ben-n93.github.io/commits/main (assuming that is the repo you're talking about). You might want to [recover an old commit](https://medium.com/coder-nomad/how-to-reset-your-git-branch-to-a-previous-commit-both-local-and-remote-55e0351dca2b).

Bugger, how embarrassing. Thank you!

**Comment by justinmayer** [comment]
Thanks for helping out here, David! 🥇
