### ISSUE TITLE
A dead link on PyPI for the contributions and feedback

### ISSUE THREAD

**Issue by galaxy4public** [getpelican/pelican#3093]
I just stumbled upon [Pelican's page in PyPI](https://pypi.org/project/pelican/) and found that the l[ink for the contributions and feedback](https://pypi.org/project/pelican/CONTRIBUTING.rst) is dead.  Perhaps, it needs to be updated?

**Comment by justinmayer** [comment]
Nice catch. If you look at the [`README.rst` source](https://github.com/getpelican/pelican/blame/b777bedce30a624b689b5dc0b034ff8d18675747/README.rst#L33), you'll see that the link isn't exactly _dead_ but refers to a local file (`CONTRIBUTING.rst`) that sits alongside the `README.rst` file. I'm sure there is a better way to handle that link such that it works well in all cases, including on the PyPI project page, but I don't use reStructuredText enough to know how to handle that well.

Anyone know how to fix it appropriately?

**Comment by kurtmckee** [comment]
`README.rst` is injected into the package while `setup.py` is running.

The contents could be transformed using something like `README.replace("<CONTRIBUTING.rst>", "$ABSOLUTE_URL")` or similar. (Likely `$ABSOLUTE_URL` will be the rendered file on Read the Docs.)

**Comment by justinmayer** [comment]
Thanks for the suggestion, Kurt. Any chance you might be willing to submit a pull request for this fix? 😊
