### ISSUE TITLE
Process markdown images with relative url like they have {static}

### ISSUE THREAD

**Issue by doriane-systems** [getpelican/pelican#3099]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

### Context

I'm using a markdown editor (Zettlr) to manage the content of a Pelican website. The editor renders images directly inside its window which is nice. However the relative urls that work in the local context of the markdown editor are not the same than the one we need in order for the images to work on the website. (Similarly to this issue: <https://github.com/getpelican/pelican/issues/2842>)

This can of course easily be fixed by adding `{static}` in front on the url which will:
* move the image to the static directory
* change the image's url to one that work in the website context

But adding `{static}` break the image render in the markdown editor.

### Plugin

I thought about writing a plugin that would automatically add `{static}` in front of the images' urls.
But for that to work I need to make it happen before the images are processed in the pelican generation process and after the files have been read, and I can't manage to find which signal to use.

In every `article_` prefixed signal I either find myself with an empty `generator.articles` list thus not being able to insert `{static}` to their raw markdown string, either the articles have already been parsed and translated to html.

Is there a signal that would make sense to use for such a plugin?

### Other options

While I totally understand that it's important to not make this the default behavior, in my case I would like too.
Is there a possibility to have a pelican toggle option that would do it?

Would it make sense to make a markdown extension (instead of a pelican plugin), so the `{static}` keyword is added to image with relative urls, before pelican process them and after the files have been read ?

**Comment by avaris** [comment]
`pelican` does not handle "raw" markdown at any point. [`MarkdownReader`](https://github.com/getpelican/pelican/blob/b473280eac576705bc39b8151d27a1e05040d0e8/pelican/readers.py#L344) passes the markdown content to the appropriate library and converts it to HTML. So, `pelican` only receives HTML. So, your options are:

- pelican plugin that replaces `MarkdownReader` and does any preprocessing before turning it into HTML
- pelican plugin that deals with HTML instead and modifies the `src` of images to add `{static}` prefix
- deal with it in markdown processor completely with an extension

**Comment by GiovanH** [comment]
I have a pelican plugin that does exactly this for relative-style links: https://github.com/GiovanH/peliplugins/blob/master/auto_attach.py

I agree that this should/could be a setting in the main program, since it's such a common and desirable behavior.

**Comment by justinmayer** [comment]
@doriane-systems: For the time being, it seems the [Auto-Attach plugin](https://github.com/GiovanH/peliplugins#autoattach) by @GiovanH should address your immediate need.

If someone is interested in implementing something like that for Pelican core and is willing to document a _detailed_ proposal, please feel free to do so in the context of a new issue.
