### ISSUE TITLE
links point incorrectly

### ISSUE THREAD

**Issue by rgrover** [getpelican/pelican#3100]
- **OS version and name**: Debian (bullseye) release 11
- **Python version**: 3.10.9
- **Pelican version**: 4.8.0
- **Link to theme**: notmyidea

## Issue

Links introduced using simple Markdown point to a wrong destination.

I started with the quickstart state (refer to terminal interaction from https://gist.github.com/rgrover/036113c0d7d3bdbd6d8d984db6670dac)

I created an `about.md` under `content/pages`: https://gist.github.com/rgrover/563ec73cafac30a0969e154d9e10a047

Upon generating the output, I find that the link refers back to about.html.

**Comment by GiovanH** [comment]
You're setting the *title* of the link to the value within quotes, with no href set.
I believe what you mean to do is link to the BBC page, which would be `[BBC](https://www.bbc.com)` with no quotes.

Pelican behavior is non-discrepant.

**Comment by justinmayer** [comment]
I agree that the spurious quotation marks are the likely culprit. Either way, it is highly improbable that there is a related problem with Pelican itself — handling Markdown links properly is an area that is well-tested. 😸
