### ISSUE TITLE
Q: Get current page url?

### ISSUE THREAD

**Issue by gcb** [getpelican/pelican#3107]
- [X] I have searched the issues. And it is very similar to https://github.com/getpelican/pelican/issues/3039 but not exactly
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
How to get the current page url? Ideally the canonical one.

some [places](https://github.com/getpelican/pelican/issues/3039) have a very ugly snippet to get it from a dozen different places. Is there a cleaner way? something like `{{ SITEURL }}/{{ CURRENTPAGE }}`?

thanks!

**Comment by jorgesumle** [comment]
There is the `output_file` variable:

> The name of the file currently being generated. For instance, when Pelican is rendering the home page, output_file will be “index.html”

See [documentation on Common variables](https://docs.getpelican.com/en/latest/themes.html?highlight=paginator#common-variables).

**Comment by gcb** [comment]
Thanks. I didn't know it translated well to things that included paths (e.g. `category/abc.html`). but just tested it out and it does.

the only weird case is `/` is now linked to `/index.html` but I think i can live with that. would be nice to have a variable that behaved the same way as it does for other interlinked pages in the templating logic (i.e. it links to `/` instead `/index.html`, so `output_file` --or another var-- could also give me empty `` value)
