### ISSUE TITLE
Conflict between TEMPLATE_PAGES and STATIC_PATHS

### ISSUE THREAD

**Issue by badicsalex** [getpelican/pelican#3109]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Hi, it would be great if `STATIC_PATHS` didn't overwrite `TEMPLATE_PAGES` files (I mix template htmls with their respective images and such), just like it doesn't touch articles and pages.

I guess it would be enough to mark `TEMPLATE_PAGES` files as sources so that ` STATIC_EXCLUDE_SOURCES = True` does its job.

(PS.: It took a while to figure out, and #3097 would definitely have helped)

**Comment by badicsalex** [comment]
I guess something like this would help and not cause trouble:

```diff
diff --git a/pelican/generators.py b/pelican/generators.py
index e18531be..fad31907 100644
--- a/pelican/generators.py
+++ b/pelican/generators.py
@@ -268,6 +268,10 @@ class _FileLoader(BaseLoader):
 
 class TemplatePagesGenerator(Generator):
 
+    def generate_context(self):
+        for source in self.settings['TEMPLATE_PAGES'].keys():
+            self.add_source_path(source)
+
     def generate_output(self, writer):
         for source, dest in self.settings['TEMPLATE_PAGES'].items():
             self.env.loader.loaders.insert(0, _FileLoader(source, self.path))
```

**Comment by justinmayer** [comment]
Thanks for raising this issue, Alex. I think it is close enough to the issue to which you linked in the description that I would prefer to consolidate and close this issue in favor of the other. Feel free to subscribe to that issue so you can be notified when it is resolved.

Even better, perhaps you would like to help implement a fix? That would be super-helpful! 😊

**Comment by badicsalex** [comment]
Huh, I completely forgot about this. I've long since made some workaround plugin, and then extended that all kinds of features,  so it's not really that important anymore.

I guess this is more for future reference if other people run into the same issue.
