### ISSUE TITLE
Replace Flake8 & isort with Ruff

### ISSUE THREAD

**Issue by FriedrichFroebel** [getpelican/pelican#3123]
## `invoke lint` yields error with flake8 6.0.0

I just tried to run `invoke lint` on the code. This resulted in `flake8` not being installed first (not installed by `invoke install`, followed by:

> flake8: error: unrecognized arguments: --diff

This is related to flake8 6.0.0 dropping the `--diff` option, see https://flake8.pycqa.org/en/latest/release-notes/6.0.0.html#backwards-incompatible-changes. Using `pip install "flake8<6.0.0"` works, but the functionality should probably be fixed to not rely on old versions any more.

**Comment by justinmayer** [comment]
Hi @FriedrichFroebel. The proper version of Flake8 for use with this repository is listed in the [pyproject.toml file](https://github.com/getpelican/pelican/blob/86f62d0a92ad78df36aac9f5837d4f2715535421/pyproject.toml#L61).

As for this bit…

> This is related to flake8 6.0.0 dropping the `--diff` option

Speaking of dropping, I think it's time to drop Flake8. I'm tired of these shenanigans and the repeatedly rude manner in which Flake8 maintainers conduct themselves. (I'm going to refrain from posting relevant links here, as I have neither the time nor the interest in getting mired in pointless Internet wars.)

So, Friedrich, I'm sorry for hijacking your issue, but I have changed the intended resolution of this issue accordingly. I have already done an experiment in a plugin repo in which I replaced Flake8 (and isort) with Ruff, and it seems to working very well so far: https://github.com/pelican-plugins/touch/pull/2/commits/f93876da3b8c30af4aa6c869349e995c0b2d0fbd

I intend to make a similar transition here in this repository when I can find the time.

**Comment by FriedrichFroebel** [comment]
Thanks for the explanations. I had missed the versions inside the `pyproject.toml` file, as I assumed that the `tasks.py` file would install the required stuff (which proved to be wrong). The CONTRIBUTING guide was of no big help here either for now, recommending strange stuff like

> Add a `RELEASE.md` file in the root of the project

as well.

**Comment by justinmayer** [comment]
> This resulted in `flake8` not being installed first (not installed by `invoke install`)…

There is no `invoke install` task. If you tried that, Invoke should have rightfully responded with: `No idea what 'install' is!`

> I assumed that the `tasks.py` file would install the required stuff (which proved to be wrong).

For me, it does indeed install the required stuff, including all needed linter tools, as long as the proper invocation is used:

    invoke setup

> The CONTRIBUTING guide was of no big help here either for now.

All of the required steps should be meticulously described in the [Setting Up the Development Environment](https://docs.getpelican.com/en/latest/contribute.html#setting-up-the-development-environment) section of the documentation, including the above-mentioned `invoke setup` step.

**Comment by FriedrichFroebel** [comment]
Thanks for the hint. I actually assumed that https://github.com/getpelican/pelican/blob/master/CONTRIBUTING.rst would be the official contribution guide, as this is what GitHub automatically points to as well. Nevertheless, I managed to get it working somehow, but yes, good documentation is always appreciated.
