### ISSUE TITLE
About documentation translation

### ISSUE THREAD

**Issue by GeorgeHu6** [getpelican/pelican#3125]
Hi, Pelican has been a fantastic static blog generator which I have used for a long time. However, it seems that the documentation has just a English version. What should I do if I want to translate this into another language such as Chinese?

**Comment by jorgesumle** [comment]
See https://github.com/getpelican/pelican/pull/3084

I started translating it into Spanish, but I don't have much free time, so I didn't finish the translation. Maybe I can continue it soon!

**Comment by GeorgeHu6** [comment]
So I would like to know how to contribute the translation to the documentation of this project when I have finished it?

**Comment by justinmayer** [comment]
Hi @GeorgeHu6. Thank you for volunteering to assist with localization of Pelican's documentation to Chinese. You might want to take a look at #1138, which was an earlier attempt at beginning that process.

Regarding the mechanics of how to contribute the translation, the [Sphinx guide](https://docs.readthedocs.io/en/stable/guides/manage-translations-sphinx.html) that @jorgesumle mentioned would be a good place to start. If you have more specific questions, please let us know!

**Comment by GeorgeHu6** [comment]
Yeah, I start my translation project following the Sphinx guide. But I failed to run the command "sphinx-build -b html -D language=zh_CN . _build/html/zh_CN" under the docs directory because of the "theme error" and it said "no theme named 'furo' found (missing theme.conf?)".

**Comment by jorgesumle** [comment]
You need to install [Furo](https://github.com/pradyunsg/furo) (`pip install furo`) or change the theme to the default theme or any theme that you have installed (variable `html_theme` from `docs/conf.py` file).

**Comment by GeorgeHu6** [comment]
It works! It's so kind of you to offer the help, thank you so much!
