### ISSUE TITLE
Pelican Themes Website not active due to Heroku server

### ISSUE THREAD

**Issue by datatalking** [getpelican/pelican#3129]
@getpelican
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: MacOs BigSur 

- The bug is a hosting issue with heroku, likely due to them changing hosting plans what are some alternatives?
- Also posted here for visibility https://github.com/getpelican/pelican-themes/issues/731
<img width="666" alt="Screen Shot 2023-05-08 at 1 51 14 PM" src="https://user-images.githubusercontent.com/11813209/236932310-b9fa3fba-68a7-406e-b982-f086510674f0.png">

**Comment by justinmayer** [comment]
Hi Andrew. I appreciate the intent behind your comment and this new issue. However, having duplicate issues just adds to the maintenance burden for project maintainers, and moreover this is related to (1) Pelican themes and not Pelican itself (which is the scope of this repo) and also (2) that site is a 3rd-party site that up until now has had nothing to do with the official Pelican project.
