### ISSUE TITLE
Parse categories field when there is a comma separating several words

### ISSUE THREAD

**Issue by richardazia** [getpelican/pelican#3137]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Hello, 

I have been experimenting with Pelican and I came across a need. 

Example: I write a post that has the categories hiking, switzerland, and summer. At the moment GetPelican parses this as "Switzerland, Hiking, Summer", rather than as "hiking", "Switzerland", "summer". 

The problem occurs when you have dozens, or hundreds of posts with different combinations of categories, because each combination of categories appears in the navigation at the top of the page. With categories parsing we avoid this issue. 

Thanks, 

Richard

**Comment by avaris** [comment]
That's by design. `pelican`, by default, associates single category per content. `tags` is used to list multiple identifiers. So you need to either switch to `tags` or use a plugin like [`more-categories`](https://github.com/pelican-plugins/more-categories).

**Comment by richardazia** [comment]
Thanks for the recommendation. I will look into it.
