### ISSUE TITLE
Filter index page posts (not rss) to exclude categories (or category) through template

### ISSUE THREAD

**Issue by Jeffmackinnon** [getpelican/pelican#3146]
I would like to exclude my "social" type posts from the homepage, but keep them in the RSS feed. This would be controlled by a category defined in the configuration file.

In my case, I would like all posts except for 'microblog' to appear on the homepage. My original fix was to create a new paginated_posts template for index and then just exclude that category, however now that _most_ of my posts are that category the first page is empty.

```
<div class="posts">
    {% for article in articles_page.object_list %}
    {% if (article.category != MICROBLOG)%}
    <article>
```

Any tips whether through a plugin or template is appreciated.

**Comment by justinmayer** [comment]
Hey Jeff. Have you by chance checked the repositories in the [Pelican Plugins](https://github.com/pelican-plugins) organization and also any plugins in the [legacy monorepo](http://github.com/getpelican/pelican-plugins)? Because I have a sneaking suspicion that maybe you haven't. 😉 

As I write this, I'm realizing perhaps I need to add those plugin links to the _New Issue_ template for this repo.

**Comment by Jeffmackinnon** [comment]
I spent some time searching for something that would work a while back but nothing jumped out. There are a bunch of ways to add categories (more than one to a post), sub-categories, etc.

I just searched both repos [here ](https://github.com/search?q=org%3Apelican-plugins%20exclude%20category&type=code)and [here](https://github.com/search?q=repo%3Agetpelican%2Fpelican-plugins%20exclude%20category&type=code) with the "exclude category" search but nothing jumped out. 

When I was browsing [feed-filter](https://github.com/pelican-plugins/feed-filter) looked promising, but it is only for feeds, not .html "pages". However, if there isn't anything already baked, I'm think that this is the likely place that I will start building a plugin that adjusts the output for the index page.

**Comment by justinmayer** [comment]
My apologies, Jeff. I thought were talking about filtering from the Atom/RSS feed. Had I actually read what you wrote, I would have noticed that you were talking about filtering from your index page. A related topic was discussed here a few years ago in #1771.

In that case, your original approach should be the correct one. In fact, I just replicated that approach on my site, and it behaves precisely as expected. Adding `Category: foo` to the metadata of one of my posts causes it to be excluded from my index page when I add the following to my `index.html` template:

```jinja2
{% for article in articles_page.object_list %}
{% if (article.category != "foo")%}
[…]
{% endif %}
```

**Comment by avaris** [comment]
Unfortunately, you can't do that within templates. Pagination is decided and content is divided into pages before it's being sent to the jinja. So, if you selectively output content in templates, you would end up with pages less than (or even zero) the configured amount of content. Plugin is the only way right now.

**Comment by Jeffmackinnon** [comment]
Thanks for the heads up. I will probably put it aside for now and build a plug-in later. 

Too many other little projects on my plate right now. 

Cheers,
JM

**Comment by justinmayer** [comment]
Sounds good, Jeff. Feel free to post a comment here if and when you decide to pick this up again. Cheers! 😁

**Comment by jonathan-s** [comment]
Would be very nice indeed with plugin for this.
