### ISSUE TITLE
Strip html tags from the SITENAME and AUTHOR when used in the head

### ISSUE THREAD

**Issue by Gullumluvl** [getpelican/pelican#3147]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Hi, Pelican is great!

I wanted to give style to specific words in the `SITENAME` and `AUTHOR`, that are usually displayed at the top of the generated home page, which means adding html tags in those variables. However, this is inappropriate in the metadata and in the `<title>` fields of the html page (because it shows the raw text).

Specifically, my SITENAME is something like: `firstname <span class="smallcaps">lastname</span>`.

Is there a way to tolerate html markup in these variables, and tell Pelican or the jinja2 template to strip it away when needed?

Thanks!

**Comment by Gullumluvl** [comment]
OK I got it, I'm sorry I was not familiar with the templating system.

I realize it's dependent on the template files, exclusively. Mine was using the theme "Peli-Kiera".
The `simple` theme also does not handle it.

So we could write this in all templates:

```
{{ SITENAME|striptags }}
```

**Comment by justinmayer** [comment]
Putting HTML tags in the `SITENAME` and `AUTHOR` settings is a use case that was neither anticipated nor supported in Pelican, so I think it is up to theme maintainers to add `|striptags` in the appropriate places in theme templates if that is a use case they wish to support.
