### ISSUE TITLE
Make embedding custom HTML easier

### ISSUE THREAD

**Issue by ben-cottrell-nz** [getpelican/pelican#3152]
I would like to insert raw HTML with JavaScript, without resorting to loading the page inside an iframe for markdown.
I notice Jinja supports inserting raw HTML blocks, but don't know how to enable this in my pelicanconf.py.

**Comment by avaris** [comment]
I don't quite understand the issue. You can directly write HTML within markdown, or maybe you are looking for a plugin like [`markdown-include`](https://github.com/pelican-plugins/markdown-include).

**Comment by ben-cottrell-nz** [comment]
I just needed to enclose my HTML inside a div tag: https://www.bgcottrell.com/animated-rose-pattern-with-p5js.html

**Comment by justinmayer** [comment]
@ben-cottrell-nz: Does that mean that you were able to resolve your issue?

On a not-quite-related note, there will soon be a new plugin to inject custom code before or after specific HTML tags: https://github.com/pelican-plugins/injector
