### ISSUE TITLE
articles_page filter without breaking pagination

### ISSUE THREAD

**Issue by codeurimpulsif** [getpelican/pelican#3157]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

I want my index page to show all articles with pagination, except articles within a specific category.

I try some things like:
```jinja
{% block content %}
	{% for article in articles_page.object_list %}
		{% if article.category not in ['notes'] %}
		<div class="article">
			<h2><a href="/{{ article.url }}">{{ article.title }}</a></h2>
		</div>
		{% endif %}
	{% endfor %}
	{% if articles_page.has_other_pages() %}
		{% include 'pagination.html' %}
	{% endif %}
{% endblock content %}
```

Also with other `for` conditions instead of `if`, like:
```jinja
{% for article in articles_page.object_list | selectattr('category', '!=', 'notes') %}
```

But of course the loop count articles I want to hide, so with a `DEFAULT_PAGINATION` set to 4, if my 4 first articles are in the category I don't want to show in index, my first index page appear empty (and also other pages if 4 articles of this category are in it).

Is there anything I do wrong or any exemple of such thing I don't see during my searches?

**Comment by avaris** [comment]
See [comment](https://github.com/getpelican/pelican/issues/3146#issuecomment-1602772249).

**Comment by codeurimpulsif** [comment]
Oh ok, thanks @avaris !

I think I will try https://github.com/getpelican/pelican-plugins/tree/master/collate_content.

And if it don't work I will find another way or just keep it as it is.
