### ISSUE TITLE
Quickstart puts files/dirs in root, rather than projects/<proj name>

### ISSUE THREAD

**Issue by dgl-dev** [getpelican/pelican#3160]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

- I have a python venv at ~/PelicanBlog/ve
- I have created /projects/test1 in that
- I've run pelican-quickstart

I get :
<code>
(ve) lesatdgl@penguin:~/PelicanBlog/ve$ cd projects/test1
(ve) lesatdgl@penguin:~/PelicanBlog/ve/projects/test1$ pelican-quickstart
Welcome to pelican-quickstart v4.8.0.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

Using project associated with current virtual environment. Will save to:
/home/lesatdgl/PelicanBlog/ve
</code>
And it does, not putting  generated files/dirs in project/test1 as docs say

Did I not do something? If so, I didn't see it in the docs

**Comment by avaris** [comment]
It's mentioned in the [docs](https://docs.getpelican.com/en/latest/install.html#kickstart-your-site):

>  run inside an activated virtual environment, `pelican-quickstart` will look for an associated project path inside `$VIRTUAL_ENV/.project`. If that file exists and contains a valid directory path, the new Pelican project will be saved at that location. Otherwise, the default is the current working directory. To set the new project path on initial invocation, use: `pelican-quickstart --path /your/desired/directory`

**Comment by justinmayer** [comment]
@dgl-dev: As @avaris mentioned, Quickstart appears to be functioning as documented and designed. If you need further assistance, please let us know.

**Comment by dgl-dev** [comment]
Only that the Quickstart doc should be updated to show the requirement "Otherwise, the default is the current working directory. To set the new project path on initial invocation, use: `pelican-quickstart --path /your/desired/directory"`

Les Dunaway
770-490-7546 <http://voice.google.com/calls?a=nc,%2B17704907546>
