### ISSUE TITLE
`ParseOverrides` being invoked on account of `extra-settings` cannot be satisfied.

### ISSUE THREAD

**Issue by ployt0** [getpelican/pelican#3169]
- [x ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Ubuntu 22.04/Windows 10 Pro**: 
- **3.10**: 
- **4.8**: 
- **N/A**: 
- **N/A**: 
- **N/A**: 
- **N/A**: 
- **N/A**: 

## Issue

`extra-settings` cannot be satisfied under many environments.

I'm trying to run a CI pipeline manually and there's a line like this:

```
pelican _pelican/samples/content --settings _pelican/samples/pelican.conf.py --extra-settings SITENAME="basic preview" --relative-urls --theme-path $theme --output _output/$theme --ignore-cache --delete-output-directory
```

where `theme=basic` but I hardcoded to save quoting headaches.

It works from the pipeline, where `os` invokes the shell, but not from the command line.

To make testing easier I cloned `getpelican/pelican` and condensed the problem down to:

```
pelican samples/content --extra-settings SITENAME="basic preview" # unescaped
pelican samples/content --extra-settings SITENAME=\"basic preview\" # escaped
```

It *can* work, but not on Linux and certainly not using the example verbatim, on Windows:

![ValueError: Invalid JSON value](https://github.com/getpelican/pelican/assets/25666053/bb3507d4-a3d1-4c6e-b467-ee840f553e24)

It would be quicker to give the situations under which it does work, since they are few and far between.

The error is 

> ValueError: Invalid JSON value: basic preview. Values specified via -e / --extra-settings flags must be in JSON notation. Use -e KEY='"string"' to specify a string value; -e KEY=null to specify None; -e KEY=false (or true) to specify False (or True).

Instead I'll stick to the cases I quoted above, changing the path to samples where needed and referring to them as `unescaped` or `escaped`.

**pelican samples/content --extra-settings SITENAME="basic preview"**

- **fail** ubuntu 22 bash over ssh from PowerShell, escaped
- **fail** ubuntu 22 bash over ssh from PowerShell, unescaped
- **pass** Git Bash in Windows, escaped
- **fail** Git Bash in Windows, unescaped
- **fail** CMD in Windows, escaped
- **fail** CMD in Windows, unescaped
- **fail** PyCharm (likes PowerShell) in Windows, escaped
- **fail** PyCharm (likes PowerShell) in Windows, unescaped

Without a native Linux terminal this took me quite a few iterations to establish. It should be improved.

Here are the PyCharm screenshots for escaped and unescaped, just in case:

![winders-escaped](https://github.com/getpelican/pelican/assets/25666053/f844079a-31b3-497e-b6be-a2402ae5b582)

![winders-unescaped](https://github.com/getpelican/pelican/assets/25666053/043bd6b8-97fa-4a5b-8a28-87e2cda57695)

I'll just finish on the happy case, in case I ever need to repeat it (it isn't perfect here, but I might file another bug about the dependency trail under Windows):

![success](https://github.com/getpelican/pelican/assets/25666053/a11c9d33-bea1-4e69-baaf-42ff381c1cb4)

**Comment by ployt0** [comment]
To add:

- fail ubuntu 22 bash over ssh from Git Bash for Windows, escaped
- fail ubuntu 22 bash over ssh from Git Bash for Windows, unescaped

resulting in `ValueError: Invalid JSON value`

**Comment by ployt0** [comment]
To add:

- **fail** ubuntu 22 bash over ssh from Git Bash for Windows, escaped
- **fail** ubuntu 22 bash over ssh from Git Bash for Windows, unescaped

resulting in `ValueError: Invalid JSON value`

**Comment by ployt0** [comment]
Can I get approval to attempt a fix?

Does anyone else use Windows?

Does anyone else use `extra-settings`?

**Comment by justinmayer** [comment]
As is already specified in the [docs](https://docs.getpelican.com/en/latest/settings.html), all extra settings passed to the CLI must be in JSON format. For example, your invocation above should have been:

    pelican samples/content --extra-settings SITENAME='"basic preview"'

**Comment by ployt0** [comment]
Seems I must have already tried that:

![tried](https://github.com/getpelican/pelican/assets/25666053/aaa6481e-703f-4abc-adb7-1b37784316b6)

**Comment by justinmayer** [comment]
I don't have any way to reproduce this since I don't use Windows, but since the [Pelican test suite includes Windows in the CI environment](https://github.com/getpelican/pelican/blob/63b60da919937c04d55b7cddaad29fd171033dc6/.github/workflows/main.yml#L30-L31), you should be able to submit a pull request that tests this functionality. For example, you could first push a commit with a test that presumably passes on Linux/Mac environments but fails in the Windows environment, and then push a subsequent commit that fixes the failing test for Windows.

**Comment by avaris** [comment]
I believe there is a confusion here. It does work as expected, tricky part is that you actually have to pass `"some text"` as input, including the quotes. How that is achieved (quoted, escaped, etc) changes from shell to shell. 

e.g. these work fine for me on Win11 CMD:

```text
pelican content -e SITENAME="\"some text\""
pelican content -e SITENAME="""some text"""
```

but not these
```text
pelican content -e SITENAME=\"some text\"
pelican content -e SITENAME="some text"
```

`"\"some text\""` and `"""some text"""` pass quotes as escaped (`\"` or `""`) but with an encapsulating quote to make it a single argument.

PS: Simple way to check what could work:
```console
> python -c "import sys; print(sys.argv)" "unescaped quotes" \"escaped quotes\" "\"quoted escaped quotes\"" """triple quotes"""
['-c', 'unescaped quotes', '"escaped', 'quotes"', '"quoted escaped quotes"', '"triple quotes"']
```
as you can see only last two will give you expected result.

**Comment by ployt0** [comment]
> e.g. these work fine for me on Win11 CMD:
> 
> ```
> pelican content -e SITENAME="\"some text\""
> pelican content -e SITENAME="""some text"""
> ```

Confirmed.

Thank you. That's exactly what I was looking for.

This is good Windows knowledge. It would be helpful to include within the `argparse` calls.

CMD clearly has its uses and talented individuals like yourself still practicing it.

I only use PowerShell because it stores my command history. Nothing works with PowerShell...

I find PyCharm _isn't_ using PowerShell, but CMD! No idea how to change that, but I can use my IDE again:

![pycharm-debug-accepting-extra](https://github.com/getpelican/pelican/assets/25666053/481cf35f-324e-4166-bb59-519c1b6a8837)

It didn't like the triple quotes but I was surprised to see them in your answer, and confirm them to work in CMD.

What pycharm is actually using for the above screen cap is:

```shell
-e "SITENAME=\"basic preview\""
```

which also works in CMD.

I've got to stop taking Bash as the canon behaviour for shell usage; but what other shell would markdown code-hiliters pick for fenced-code labelled `shell`?

**Comment by avaris** [comment]
> Nothing works with PowerShell...

I don't really use windows in dev side at all, only for some testing. So I'm not that fluent in PowerShell but after some testing it's a bit weird. Finally, I was able to find one that worked :)

```console
> pelican content -e SITENAME='""some text""'
```

That's double-double quotes (escaped) inside single quotes for making single argument.
