### ISSUE TITLE
requirements are incomplete to run on Windows

### ISSUE THREAD

**Issue by ployt0** [getpelican/pelican#3170]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Windows 10**: 
- **3.10**: 
- **4.8**: 

## Issue

```python
pip install -r requirements/developer.pip
PYTHONPATH=. python pelican/__main__.py samples/content
```

I'd expect that to work but it doesn't. I still have to:

```
pip install rich python-dateutil blinker feedgenerator
```

Environments come and go, it would be easier if I didn't have to hunt dependencies to get set up.

**Comment by ployt0** [comment]
I forgot `unidecode`, and we need something for "time zone key UTC".

This sounds like a lot, maybe there's another way I missed?

**Comment by ployt0** [comment]
I forgot `unidecode`. We need something for "time zone key UTC", I'm using `tzdata`.

**Comment by justinmayer** [comment]
The list of dependencies in `requirements/` are meant to be *in addition to* the requirements that are currently defined in `setup.py`. In other words, the following is what you probably should have done:

    pip install -e . -r requirements/developer.pip
    pelican samples/content

**Comment by ployt0** [comment]
Thanks Justin. I thought they looked familiar.
