### ISSUE TITLE
Translate template without using subsites

### ISSUE THREAD

**Issue by damascene** [getpelican/pelican#3182]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue
Hi, I'm unable to find a clear way to just change some English text in default pelican theme using `gettext` method. I know I can just manually translate them but that didn't sound right to me. 

I was able to use i18n-subsites plugin and I was able to generate the po files and compile them and show the translated site under language subdir `example.com/es/` but I want to have the `es` language shown on them main domain not on subdir. 

When I set the default language to `es` translation doesn't show and theme is broken on `/es/` subdir.

My current config omitting most defaults generated by pelican:

```

DEFAULT_LANG = 'en'

JINJA_ENVIRONMENT = {
  'extensions': ['jinja2.ext.i18n', 'jinja2.ext.debug']
}


THEME = '/home/user/test_pelican_international/notmyidea'

PLUGINS = ['i18n_subsites']

I18N_SUBSITES = {
    'es': {
        'SITENAME': 'whatever',
        }
    }
```

**Comment by justinmayer** [comment]
As far as I know, there is no support for theme template localization built into Pelican core.

Regarding I18N Subsites, that is a plugin, and thus any discussion about it should take place in its home over at the [legacy Pelican Plugins repository](https://github.com/getpelican/pelican-plugins).

**Comment by damascene** [comment]
Pelican states that it supports `Publication of articles in multiple languages` which is good but it would be a weird experience to have support for other languages in the the article and not the template. 

I think it would benefit the user to have instruction for localizing the default website which I think it's achievable, however I wasn't able to do so.

Instructions at:
https://jinja.palletsprojects.com/en/3.1.x/extensions/

It might needs something like:
```
translations = get_gettext_translations()
env = Environment(extensions=["jinja2.ext.i18n"])
env.install_gettext_translations(translations)
```

but I've failed to adapt it to Pelcian

**Comment by justinmayer** [comment]
We could argue whether such a situation is "weird", but I don't have time to engage in that.

While modifying the theme templates directly would address the immediate need, I understand the desire is to localize the theme template strings in some other way. To that end, documentation/code change proposals and corresponding pull requests are welcome.
