### ISSUE TITLE
Wrong warning WITH_FUTURE_DATES

### ISSUE THREAD

**Issue by fornib** [getpelican/pelican#3184]
- [X] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue
When setting `WITH_FUTURE_DATES = True` (default) and `CONTENT_CACHING_LAYER = 'generator'`, I get the following warning:
`WITH_FUTURE_DATES conflicts with CONTENT_CACHING_LAYER set to 'generator', use 'reader' layer instead".`
But the documentation says that it should conflicts only when `WITH_FUTURE_DATES = False`.

I believe the fix is to change file `settings.py` line 585 into:
```python
not settings.get('WITH_FUTURE_DATES', True):
```

**Comment by avaris** [comment]
Sounds right. Would you like to make a PR for it?
