### ISSUE TITLE
add HTML to linguist-vendored

### ISSUE THREAD

**Issue by 1268** [getpelican/pelican#3188]
https://github.com/getpelican/pelican/blob/2eeff62fd70d6b150d85910bf7ebc1db3ca57651/.gitattributes#L4-L7

like this:

~~~
*.html linguist-vendored
~~~

since currently this looks like an HTML repo instead of a Python repo.

**Comment by justinmayer** [comment]
Thanks, Steven. The suggested solution seems like a blunt weapon, but it was also the only way I could find to adjust the statistics in any meaningful way. Perhaps there is a less-blunt way to address this problem, but until that time, it at least improves the situation in the interim.

For future reference: https://github.com/github-linguist/linguist/blob/master/docs/overrides.md
