### ISSUE TITLE
Spaces between rows in CODE area are huge

### ISSUE THREAD

**Issue by DragonSerW** [getpelican/pelican#3191]
Hello!
The problem is spaces between rows of code are huge, because of it attached to codebox `.nfo` looking stretched by vertical.
My blog with this issue is https://splash.org.ru/. Screen shot: https://i.ibb.co/xzNxKJ1/Screenshot-20230908-125445.png.
And my blog powered by DokuWiki has no such problem: https://dragonserw.ru/.

**Comment by avaris** [comment]
That's coming from your CSS, therefore theme. Look for `line-height` value for `pre` or `code` tags. Not directly related to `pelican`.

**Comment by justinmayer** [comment]
Hi @DragonSerW. As suggested by @avaris, please take a look at your theme's CSS and try adjusting it. If there is anything further to add to this issue, please comment here.

**Comment by DragonSerW** [comment]
All right, thank you both :-))
