### ISSUE TITLE
Perte du mot de passe lors d'une modification via la console d'administration

### ISSUE THREAD

**Issue by aidyouss** [getpelican/pelican#3193]
Bonjour,

Issue probablement liée à la TOS-592:
https://github.com/theopensourceitrust/tosiam/issues/592

Nous rencontrons un problème avec les mots de passe à partir de la console d’administration.

Lorsqu'on modifie une propriété existante d'un module TosiAM via la console, nous constatons que l'attribut "password" perd sa valeur quelque soit l'attribut modifié dans la configuration module, alors que cette propriété ne devrait pas être modifiée.

![image](https://github.com/getpelican/pelican/assets/39593329/75dca18d-fc73-4c38-8205-0cbaff79639e)

Pour information, nous sommes sur une version 2.17.1.

Merci d'avance

**Comment by justinmayer** [comment]
No idea what this is supposed to mean. Looks like spam? If not, feel free to comment again in English and explain how this relates to Pelican.

**Comment by aidyouss** [comment]
Sorry, i've made a mistake creating this issue here, please feel free to delete it.
