### ISSUE TITLE
URLs with uppercase components can cause issues.

### ISSUE THREAD

**Issue by Cartroo** [getpelican/pelican#3207]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

I've had a few cases where crawlers and tools seem to force the path of a URL to lowercase before checking them, and this doesn't play nicely with URLs which include the month name with a leading capital letter. The most recent example I found is [Sitechecker](https://sitechecker.pro/) — I had to check my `error.log` to realise it was lowercasing the URL before checking it.

Currently I've worked around this by updating my own site generation script[1] to add symlinks with the lowercase versions. However, I thought other people might be hit by this, and hence it might be a useful feature for Pelican to generate lowercase symlinks for any directories or files it creates which contain uppercase letters.

I'd be happy to look at implementing this, but since it's a bit of a niche feature I wanted to put this request in to gauge interest first. My current workaround works for me, and I'm not interested in maintaining my own fork of Pelican indefinitely, so there's little point me implementing it if there's no interest in merging upstream at some point.

[1] *I have a wrapper script which runs Pelican generating to a timestamp-specific directory, and makes sure the generation was successful before it updates a top-level symlink to point to the newly generated version. I know there are other tools for this, but I wrote it years ago and it's convenient to keep it around for little tweaks like this!*

**Comment by zemichael1234** [comment]
how can i fix this repo

**Comment by avaris** [comment]
> force the path of a URL to lowercase before checking them

It sounds a bit presumptuous for tools to do that... Setting this aside, I'd consider this a good candidate for a plugin rather than core functionality.

**Comment by justinmayer** [comment]
I agree with @avaris that such a feature would be best implemented in the form of a plugin. Note that such an endeavor should probably do more than just create symlinks, which presumably would result in the same content being available at two distinct URLs: the lower-case version and the upper-case version. That can have a negative impact on search engine indexing/ranking, which can theoretically be mitigated via [canonical link elements](https://en.wikipedia.org/wiki/Canonical_link_element).

Alternatively, one could instead re-direct URLs at the web server level (e.g., Caddy, Nginx, etc.).

**Comment by justinmayer** [comment]
As discussed here, attempts to address the situation described in this issue would be best implemented in the form of a Pelican plugin. 💫
