### ISSUE TITLE
Using METADATA in SAVE_URL

### ISSUE THREAD

**Issue by atallo** [getpelican/pelican#3208]
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

I have a blog with documents like

index.md
> blogid: any
> title: My title
> Post data

In my pelicanconf.py I have:

> ARTICLE_URL = 'art/{category}/{slug}'
> ARTICLE_SAVE_AS = 'art/{category}/{slug}.html'

I can use "blogid" Custom-metadata in ARTICLE_URL/ARTICLE_SAVE_AS ?

I try, but I see error.
> ARTICLE_URL = 'art/{blogid}/{category}/{slug}'
> ARTICLE_SAVE_AS = 'art/{blogid}/{category}/{slug}.html'

Thanks!

**Comment by avaris** [comment]
That should work. What's the error?

**Comment by atallo** [comment]
I found it

> DEFAULT_METADATA = {
>    'blogid': 'default-blog-id',
> }

Thank you. I knew it was stupid, but I couldn't get it to work.
