### ISSUE TITLE
Pelican : build system

### ISSUE THREAD

**Issue by drake-mer** [getpelican/pelican#324]
Hello, 

I run into pelican. I wanted to improve the build system. The way it is done now is to generate everything from the whole set of source files. I think this needs to be removed/upgraded. 

Why ? Because the build system is not modular at all. First problem is the need to parse again every source file (md or rst or whatever) when only one has been added or removed.

The problem I see is the 'tag' cloud. To build the 'tag' cloud and 'category' cloud we need to run across all the existing files. From then you are going to build every article in your blog engine, then the feed parsers, etc.

If I take the example of a standard Makefile to compile a C language project, every single file makes a .o file and then the '.o' (objects) are gathered into the executable. This is slightly different in pelican, since here the '.o' objects ('.html' files) are all interdependants because they rely on the list of tags and category (we call them _metadata_) to be build properly, which does not make the build process very modular.

I don't see exactly how to bring more modularity in the build process, but I think that drastic changes in the pelican code could allow to use either an internal build system or an external build system and would make the pelican app more suitable to speed optimization. 

One could think of a way to split the build process in several targets :
- pelican-template
- pelican-metadata
- pelican-article
- pelican-feeds

In some way, this would avoid code duplication and it would be cleaner for the end user. Then one could more easily use an efficient build system using eg make or an internal script. Not to mention also the advantages for the code quality and easiness of reading.

This could answer issue #310 and #224, and even other one I guess through improvement of the code quality. What do you think of it ? I am ready to take on my own some of the dev, but I would be glad to hear your opinion in the matter.

David

**Comment by xxks-kkk** [comment]
I notice this issue is 6 years old. I'm just curious if right now, we have implemented any smart build system so that I don't have to build every post every time. If so, can anyone point me any configuration I need to do? Right now, it takes about 1 minutes to build everything for me.

**Comment by justinmayer** [comment]
@xxks-kkk: Assuming you are only making changes to a single page/post, you can generate just that page/post. Instructions for doing so are in the documentation.

**Comment by xxks-kkk** [comment]
@justinmayer Thanks for the info. I tried the following command
```
pelican --write-selected /Users/zeyuan/Documents/projects/linuxjedi.co.uk/output/posts/2018/Apr/05/on-writereadspace-amplification/index.html
```
and itself still triggers the whole build process. Am I looking at the wrong command?

Thanks!

**Comment by justinmayer** [comment]
That should be the one. If you need further help, you might consider reaching out via the Pelican IRC channel, as noted in the [How to Get Help](http://docs.getpelican.com/en/stable/contribute.html#how-to-get-help) section of the documentation.
