### ISSUE TITLE
Pelican Webassets Cache Breaks Github Pages Deployment (File Permissions)

### ISSUE THREAD

**Issue by vbharadwaj-bk** [getpelican/pelican#3244]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**:  Ubuntu
- **Python version**: 3.10
- **Pelican version**: 3.9
- **Link to theme**: Base
- **Links to plugins**: [pelican-webassets](https://pypi.org/project/pelican-webassets/)

## Issue
Plugins such as Pelican-webassets create files in the output directory that do not have appropriate file permissions when deploying to Github pages (specifically in the folder `output/theme/.webassets-cache`). See this page for the required permissions for the "Upload Artifact" action <https://github.com/actions/upload-pages-artifact#file-permissions>). This causes the Github pages upload action to fail with the message "Check file permissions". The relevant action from the Pelican GH-pages workflow is below.
```
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{ inputs.output-path }}
```
It's easy to fix this by removing the offending files (which probably shouldn't be deployed as part of the website anyway), but a more general fix suggested by the "Upload Artifact" page is to add the action
```
      - name: Fix permissions
        run: |
          chmod -c -R +rX "output/" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
```
which changes the required file permissions (`output` should be replaced with the Pelican output directory). I can create a pull request that adds this action to the workflow script if there is enough interest. On the other hand, this issue was a useful signal that there were extraneous files to delete, and it may be worth just adding a note to the webassets repo README warning about this issue. Thoughts welcome.

**Comment by justinmayer** [comment]
@seanh: As the author of the PR (#3189) that added the GitHub Pages deployment workflow, do you have any thoughts about this issue?

**Comment by avaris** [comment]
Fix looks fine to me.

> it may be worth just adding a note to the webassets repo

I didn't test this but, it looks configurable via [`cache`](https://webassets.readthedocs.io/en/latest/environment.html#webassets.env.Environment.cache) option:

```python
WEBASSETS_CONFIG = [
    ("cache", False),  # disable, or
    ("cache", "/path/to/some/folder"),  # point to somewhere outside output folder
]

**Comment by vbharadwaj-bk** [comment]
Thanks for the find about the Webassets plugin @avaris ! I have opened a PR with the permission fix, since it doesn't seem like these cache files should block the upload in case WEBASSETS_CONFIG is not specified (but warnings are raised for each file that has a permission changed).

**Comment by seanh** [comment]
Late to the party, but I agree with the fix that has been merged :±1: There seems no reason why `github_pages.yml` shouldn't fix the permissions of files in the output directory if necessary to deploy them.

Glad to see that someone's already using the workflow, too
