### ISSUE TITLE
pages is treated as articles

### ISSUE THREAD

**Issue by dbzhang800** [getpelican/pelican#3247]
Hi All,

The version of my pelican is 4.8.0.

In my pelicanconf.py:
```
PATH = 'content'
PAGE_PATHS = ['pages']
PAGE_EXCLUDES = []

ARTICLE_PATHS = ['.',]
ARTICLE_EXCLUDES = []
```

I add a file called about.md to the directory pages:
contents\pages\about.md

Then, I get a page called about  and an article called about which live in a new created category called "pages" in show in my blog, how to Fix this?

**Comment by avaris** [comment]
```python
ARTICLE_PATHS = ['']
```

Empty string, no `.`.

Or you can remove them. Those are the same as default values.

PS: Still it's an interesting behavior with `'.'`. I'm on the fence about considering it as a bug :).

**Comment by dbzhang800** [comment]
Thanks , works now 

```
#ARTICLE_PATHS = ['.',]
#ARTICLE_EXCLUDES = []
```

**Comment by justinmayer** [comment]
I'm glad @avaris was able to help you. In the future, for questions such as these, please [create a Discussion](https://github.com/getpelican/pelican/discussions) instead of filing an issue. Also, please ensure you are using the latest version of Pelican, which is currently version 4.9.1. Thanks!
