### ISSUE TITLE
Enhance Social widget documentation

### ISSUE THREAD

**Issue by twopercent** [getpelican/pelican#3268]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

It is not clear in the documentation (https://docs.getpelican.com/en/latest/settings.html#SOCIAL) or the default pelican.conf.py file (samples/pelican.conf.py) that Social Widget names should be Font Awesome icon names. A note in either the documentation or sample file would be helpful.

I originally added some social widgets but nothing rendered on the generated site. After some searching I came across: https://github.com/Pelican-Elegant/elegant/issues/98 which led me to understand the names of widgets had to be specific.

Thank you.

**Comment by avaris** [comment]
> It is not clear ... that Social Widget names should be Font Awesome icon names.

Because they don't have to be. Default theme uses them as simple links with specified names as texts. Other themes are free to reuse the same name with different schema, but then it's up to the theme to document it.

**Comment by twopercent** [comment]
Ahh, thank you avaris.

It was likely working before I applied the Flex theme. I will follow up with that crew.
