### ISSUE TITLE
pelican --print-settings should show all possible settings, including those unset by default

### ISSUE THREAD

**Issue by khorton** [getpelican/pelican#3271]
- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [ ] I am willing to lend a hand to help implement this feature. 

## Feature Request
I am a new Pelican user since about a week ago, and just today discovered that pelican --print-settings does not show all possible settings if those settings are not setting (MENUITEMS, for example).

It would be helpful if the output from pelican --print-settings showed all possible settings, including those that are unset by default.  This will help new users learn all the possible ways that the behavior can be customized.  Alternatively, the output could include a statement like "The following output does not include all possible settings.  See the Settings documentation at https://docs.getpelican.com/en/latest/settings.html for all possible settings."

**Comment by CrazycatASG** [comment]
Apologies if I'm misunderstanding this, I'm also quite new to Pelican, but from my understanding, --print-setings is meant to print the settings currently configured, not all the settings you can set.

**Comment by avaris** [comment]
> --print-setings is meant to print the settings currently configured, not all the settings you can set.

That is correct. See help text: "Print **current configuration** settings and exit." (emphasis added). It is to help debug/validate if your config is pickup correctly. Not to list everything, that's the job of documentation.

**Comment by khorton** [comment]
OK, now I better understand the intended function of --print-settings.  I'll close this issue.

**Comment by egberts** [comment]
I maintain a complete list of all settings (circa 4.0) for Pelican's `pelicanconf.py` file here

https://egbert.net/blog/articles/pelican-configuration-settings.html
