### ISSUE TITLE
Pelican or Jinja problem?

### ISSUE THREAD

**Issue by mpaglia0** [getpelican/pelican#3273]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **Linux OS Tumbleweed 20240109**: 
- **Python 3.11.7**: 
- **Pelican 4.9.1**: 
- **https://github.com/mpaglia0/Z**: 
- **https://github.com/mpaglia0/Z/tree/main/plugins**: 
- **https://www.mauriziopaglia.it**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

Seems I have a problem when title of my articles contains more than one consecutive Capitals letter.

Examples:

Title of article: G.A.S.

Pelican template: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="{{ article.title }}" >`
HTML output: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="<span class="caps">G.A.S.</span>" >`

I could change template calling `article.metadata.title`...

Pelican template: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="{{ article.metadata.title }}" >`
HTML output: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="<span class="caps">G.A.S.</span>" >`

Title of article: NO alla violenza sulle donne

Pelican template: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="{{ article.title }}" >`
HTML output: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="<span class="caps">NO</span> alla violenza sulle&nbsp;donne" >`

I could change template calling `article.metadata.title`...

Pelican template: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="{{ article.metadata.title }}" >`
HTML output: `<input class="invisible readonly" type="text" id="arttitle" name="arttitle" value="<span class="caps">NO</span> alla violenza sulle&nbsp;donne" >`

Thanks,
Maurizio

**Comment by avaris** [comment]
That is coming from `typogrify`. Use [`striptags`](https://jinja.palletsprojects.com/en/2.11.x/templates/#striptags) Jinja filter ([example](https://github.com/getpelican/pelican/blob/af37f0656f18130f774ce0e22c0a3011d324d2c0/pelican/themes/simple/templates/index.html#L10)).

**Comment by mpaglia0** [comment]
Works perfectly!
Thank you indeed for all your support!

Have a nice day
Maurizio
