### ISSUE TITLE
Pelican Install Problem - Debian 11

### ISSUE THREAD

**Issue by dgl-dev** [getpelican/pelican#3274]
- [x ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x ] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue
Can't install - best to look at attached console

When I got to point of "there's something wrong" I stepped through to show the situation

1. apt list shows pelican is not installed
2. also tried to remove, since apt lies now and again
3. Created virtual env
4. tried pip install pelican and got the long error list - I'll put it here - it occurs over and over as I tried other approaches
(Blog) lesatdgl@penguin:~/PelicanProjects/Blog$ pip install pelican
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7eec4bacbd30>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pelican/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7eec4bab20a0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pelican/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7eec4bab2760>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pelican/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7eec4bab2df0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pelican/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7eec4bab2c70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/pelican/
ERROR: Could not find a version that satisfies the requirement pelican (from versions: none)
ERROR: No matching distribution found for pelican

# Same errors if i do pip install pelican outside a virtual env (in the attached log)

# Let me know if I can provide more info

[Pelican-Install-Issue.txt](https://github.com/getpelican/pelican/files/13924830/Pelican-Install-Issue.txt)

**Comment by avaris** [comment]
Well, this is not about `pelican` particularly. `Temporary failure in name resolution` suggests there is something wrong with your network configuration. `pip` cannot connect to PyPI. You would not be able to install any python package, not just `pelican`.

**Comment by dgl-dev** [comment]
OK, makes sense - could VPN be the problem?

Les Dunaway

**Comment by avaris** [comment]
Could be.

**Comment by dgl-dev** [comment]
Yes, pip/pip3 fails on other installs - with and without VPN
So, nuked browsing data and all is well
Thanks for the pointer
