### ISSUE TITLE
Adding keywords metadata to specific page

### ISSUE THREAD

**Issue by ianrussel** [getpelican/pelican#3275]
Let's say I want to have keywords meta tags in generated HTML for SEO purposes for welcome.rst

           <meta name="keywords" content="avantagepeople, mango"/>

How to achieve this? What I tried so far

         
```
  Welcome to Avantage people
##########################

:date: 20181216 08:30
:tags: welcome
:category: Intro
:slug: welcome
:authors: Craig
:summary: Welcome document
:keywords: avantagepeople, mango
:title: Welcome
:lang: en


Welcome to my blog.
This is a short page just to show how to put up a static page.
```

The welcome.rst file is located inside content/pages. Keywords don't show anywhere when Pelican generates the HTML by running ``` pelican content --ignore-cache```

**Comment by avaris** [comment]
Theme, therefore the relevant template, is supposed to generate that.

**Comment by ianrussel** [comment]
Hi @avaris, yeah I have a custom theme. But still confused about how to implement the keywords in it. The goal is to have meta keywords on specific pages only not for all pages.The custom theme is already working and used


pelicanconf.py

       # Define the path to the common_assets directory
        COMMON_ASSETS_PATH = os.path.join(os.pardir, 'common_assets')

        # Configure the theme
        THEME = os.path.join(COMMON_ASSETS_PATH, 'themes', 'boot5')

**Comment by ianrussel** [comment]
Inside theme called boot5

```
templates
     static/
     base.html
     index.html
     tag.html
     ...etc
```

**Comment by avaris** [comment]
I cannot say definitively without actually seeing your theme but in `page.html`, you need a line that inserts the keywords to `<head>`. Something like:

```jinja2
{% if page.keywords %}
    <meta name="keywords" content="{{ page.keywords }}" />
{% endif %}
```

e.g. for the default theme it would be in [this block](https://github.com/getpelican/pelican/blob/5d3e87b50be0c84d272e7fb2f9fb794af7887b50/pelican/themes/notmyidea/templates/page.html#L5-L10).

**Comment by ianrussel** [comment]
Yeah, thanks.That answer/solve my question. Have a nice day brother!.. @avaris 

Regards,

Ian
