### ISSUE TITLE
Is there a way to set `ext.i18n.trimmed` Jinja2 policy in Pelican?

### ISSUE THREAD

**Issue by slybridges** [getpelican/pelican#3283]
I would like to set the [ext-i18n-trimmed Policy](https://jinja.palletsprojects.com/en/3.1.x/api/#ext-i18n-trimmed) in Pelican config. 

I set `trimmed = true` in `babel.cfg` and messages in *.po files are trimmed. Now, I assume I also need to set it in my Jinja2 config in Pelican so that translated messages can be mapped when files are being generated.

I tried adding `"policies": { "ext.i18n.trimmed": True },` to `JINJA_ENVIRONMENT` but got met with `"Environment.__init__() got an unexpected keyword argument 'policies'".`

Is there a way to configure Jinja2 policies in Pelican config?

Using:
- `Babel==2.14.0`
- `Jinja2==3.1.3`
- `pelican==4.9.1`

- [X] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [X] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

**Comment by avaris** [comment]
No, not natively at least for now. It would need to be added as a config option similar to `JINJA_GLOBALS`, `JINJA_TESTS`, etc...

For now, you can do that with a simple plugin:

```python
from pelican import signals

def add_jinja_policy(generator):
    generator.env.policies['ext.i18n.trimmed'] = True

def register():
    signals.generator_init.connect(add_jinja_policy)
```

**Comment by slybridges** [comment]
Thanks for your answer, @avaris! I'm going to try this out. Closing the question for now.
