### ISSUE TITLE
How to handle line length limit error?

### ISSUE THREAD

**Issue by araichev** [getpelican/pelican#3284]
- [x ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [ x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Linux Mint 21
- **Python version**: 3.11
- **Pelican version**: 4.9.1
- **Link to theme**: 
- **Links to plugins**: 
- **Link to your site**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue
I have a RST file generated from a Jupyter notebook via `jupyter nbconvert notebooks/blah.ipynb --execute --no-input --to rst`.
The file contains a very long line of JavaScript, and when i add the file to my Pelican blog, i get the following error.
```
 Could not process                                  log.py:94
                    ./blah.rst                      
                    /home/me/blah.rst::                
                    (ERROR/3) Line 722 exceeds the line-length-limit.   
```
Is there any way to change or disable this line length limit, perhaps via the [DOCUTILS_SETTINGS variable](https://docs.getpelican.com/en/latest/settings.html#basic-settings)?
I tried adding the following line to my `pelicanconf.py` file to no avail.

```
DOCUTILS_SETTINGS = {
    "line_length_limit": 1_000_000_000
}
```

Is my error related to [this Github issue](https://github.com/spatialaudio/nbsphinx/pull/552)?

Thanks for your attention.

**Comment by avaris** [comment]
> Is there any way to change or disable this line length limit, perhaps via the [DOCUTILS_SETTINGS variable](https://docs.getpelican.com/en/latest/settings.html#basic-settings)?
I tried adding the following line to my pelicanconf.py file to no avail.

```
DOCUTILS_SETTINGS = {
    "line_length_limit": 1_000_000_000
}
```

This should be the way, and I can confirm it works:

```console
$ awk '{print length}' content/articles/article.rst
14
14
0
23
0
20000
$ pelican content -s pelicanconf.py
[22:02:16] ERROR    Could not process articles/article.rst                                                                                                                     generators.py:667
                    /home/avaris/ws/ptest/content/articles/article.rst:: (ERROR/3) Line 6 exceeds the line-length-limit.
Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.06 seconds.
$ cat pelicanconf_docutils.py
SITEURL = 'https://example.com'
TIMEZONE = 'Europe/Paris'

DOCUTILS_SETTINGS = {"line_length_limit": 10_000_000_000}
$ pelican content -s pelicanconf_docutils.py
Done: Processed 1 article, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.08 seconds.
```

**Comment by araichev** [comment]
Hmm, i keep getting the error, despite using the same 10 billion setting as you and my longest line being about 5 million characters long.
Same thing when i use `pelican content -s pelicanconf.py` instead of `make devserver`.
Any other tips?

Here's my 43 MB content file (which is too big to upload to Github), in case you're interested: https://mega.nz/file/dg1WCSoS#Ic1yfrW0CG-Ly8pnbnHHDNyZb7lSXy9TH4GjBQ8AW-c .

**Comment by avaris** [comment]
I can process your file just fine, just takes considerably longer. By the way, your longest line is about 13 million:

```console
$ awk '{print length}' content/articles/playground_accessibility.rst | sort -n | tail -5
5129180
5129180
6228997
10633710
12977231
$ pelican content -s pelicanconf.py
[20:10:36] ERROR    Could not process articles/playground_accessibility.rst                                                                                                    generators.py:667
                    /home/avaris/ws/ptest/content/articles/playground_accessibility.rst:: (ERROR/3) Line 150 exceeds the line-length-limit.
Done: Processed 0 articles, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 0.42 seconds.
$ pelican content -s pelicanconf_docutils.py
Done: Processed 1 article, 0 drafts, 0 hidden articles, 0 pages, 0 hidden pages and 0 draft pages in 4.85 seconds.
$ cat pelicanconf_docutils.py
SITEURL = 'https://example.com'
TIMEZONE = 'Europe/Paris'

DOCUTILS_SETTINGS = {"line_length_limit": 1_000_000_000}
```

I'd suggest looking at the `pelicanconf.py` a bit more in detail. Maybe plugins. If you can share your config here, I can also check what might cause this. Also, if you run pelican in debug mode, it should give you a longer traceback: `pelican content -s pelicanconf.py --debug`.

**Comment by araichev** [comment]
@avaris ah, the problem was caused by a plugin, namely, [Pelican Open Graph](https://github.com/whiskyechobravo/pelican-open_graph). 
When i disable that plugin, everything works fine.
Thanks for your help!
