### ISSUE TITLE
Option to disable the RichHandler log handler?

### ISSUE THREAD

**Issue by cpitclaudel** [getpelican/pelican#3292]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

The default logging format introduces aggressive line wraps.  For example:

```
[11:03:07] ERROR    Could not process                          generators.py:871
                    pages/xxxxx/xxxxxxxxxxx/xxxxxxxxxxx.rst                     
                    /home/cpitclaudel/git/xxxxxxx/xxx/xxx/page                  
                    s/xxxxx/xxxxxxxxxxx/xxxxxxxxxxx.rst:74:                     
                    (ERROR/2) …
```

Unfortunately, my editor is not smart enough to undo the line breaks, so it offers to open `s/xxxxx/xxxxxxxxxxx/xxxxxxxxxxx.rst:74` instead.

I would love an option to just print the error using a less-fancy log handler.  The default format is pretty OK:

```
Could not process pages/xxxxx/xxxxxxxxxxx/xxxxxxxxxxx.rst
/home/cpitclaudel/git/xxxxxxx/xxx/xxx/pages/pages/xxxxx/xxxxxxxxxxx/xxxxxxxxxxx.rst:74: (WARNING/2) …
```

**Comment by egberts** [comment]
What if we were to detect a Unix pipe condition and then omit the RichHandler?

Or a CLI option --no-color to disable RichHandler outright?
