### ISSUE TITLE
how to use rat-directive such as "toctree"

### ISSUE THREAD

**Issue by yanquer** [getpelican/pelican#3294]
when rst-doc has content as 

```
.. toctree::
    :maxdepth: 2

    xxx
```

and run  `` pelican content`` , get error message ``(ERROR/3) Unknown directive type "toctree".  `` 

how to support all-rst-directive-type ?

**Comment by avaris** [comment]
And where does the `toctree` directive come from? Docutils has no such [built-in directive](https://docutils.sourceforge.io/docs/ref/rst/directives.html). If you have a custom directive, you need to add/register it yourself (probably via a plugin).

**Comment by justinmayer** [comment]
I'm glad you were able to find a solution to your query. 😊
