### ISSUE TITLE
Pelican orgmode format

### ISSUE THREAD

**Issue by OrionRandD** [getpelican/pelican#3296]
Could you implement orgmode format for Pelican?
So that, we can edit articles using Emacs...
Thx a lot

**Comment by justinmayer** [comment]
Hi @OrionRandD. If you had searched existing issues, you would have come across #1670, in which we made it clear that any such functionality is welcome in plugin format but out-of-scope for inclusion in Pelican's core. You would then have likely followed the trail to the [`org_pandoc_reader` plugin](https://github.com/jo-tham/org_pandoc_reader), which albeit old at this point could possibly be used for the desired purpose.

**Comment by OrionRandD** [comment]
Thx for pointing me there.
