### ISSUE TITLE
Newest lxml breaks the building

### ISSUE THREAD

**Issue by mateuszpawlik** [getpelican/pelican#3297]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Debian 11
- **Python version**: 3.9.2
- **Pelican version**: 4.9.1
- **Link to theme**: https://gitlab.com/ccns/ccns.gitlab.io
- **Links to plugins**: https://gitlab.com/ccns/ccns.gitlab.io
- **Link to your site**: https://gitlab.com/ccns/ccns.gitlab.io
- **Link to your source**: https://gitlab.com/ccns/ccns.gitlab.io

## Issue

Our [CI/CD broke today](https://gitlab.com/ccns/ccns.gitlab.io/-/jobs/6535527326#L3044) with the following error:
```
$ pelican content/ -s pelicanconf.py -t themes/ccns/ -e SITEURL=''\"https://$ci_project_namespace.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public\"''
/builds/ccns/ccns.gitlab.io/baseconf.py:40: SyntaxWarning: invalid escape sequence '\.'
  PATH_METADATA = '(pages/)(?P<path_no_ext>.*)\..*'  # noqa
[08:32:09] CRITICAL ImportError: lxml.html.clean module is now a __init__.py:666
                    separate project lxml_html_clean.                           
                    Install lxml[html_clean] or lxml_html_clean                 
                    directly.
```
It seems that with the newest version of lxml, the clean module should be installed separately. Current Pelican version requires [lxml>=4.9.3](https://github.com/getpelican/pelican/blob/94bcd41f27d7f38a9dbd0847c6166e91a66d2090/pyproject.toml#L84).

Adding `lxml_html_clean` to our website's requirements solved the issue.

**Comment by avaris** [comment]
This doesn't come from `pelican`. There is no reference to `lxml.html.clean` in the codebase. 

> Current Pelican version requires [lxml>=4.9.3](https://github.com/getpelican/pelican/blob/94bcd41f27d7f38a9dbd0847c6166e91a66d2090/pyproject.toml#L84).

It doesn't. What you are linking is a dev dependency required for development, i.e. running tests. `lxml` is an [optional](https://docs.getpelican.com/en/latest/importer.html#dependencies) dependency for importer that needs to be installed manually if needed. It will not come automatically just by installing pelican. In your case, `lxml` is included from one of your other requirements: `metapub`. You can see it in your [CI log](https://gitlab.com/ccns/ccns.gitlab.io/-/jobs/6535527326#L2867): `Collecting lxml (from metapub->-r requirements.txt (line 4))`. I would say that's the culprit and I'd recommend reporting there. You can run the `pelican` command with `--debug` to see the full traceback and identify where the error comes from.

**Comment by mateuszpawlik** [comment]
Thanks @avaris for the help. I'm sorry, I overlooked that.

**Comment by mateuszpawlik** [comment]
Reported and being fixed: https://github.com/metapub/metapub/issues/49
