### ISSUE TITLE
Ability to show traceback of template errors

### ISSUE THREAD

**Issue by danrossi** [getpelican/pelican#3298]
This is a common problem people have and has caused me many hours trying to fix template problems in the past. On template errors, it doesn't show the actual trace of the line of the template with the error it only returns the top message string here

https://github.com/getpelican/pelican/blob/master/pelican/__init__.py#L590

I found adding this within the exception catch it shows the full stack to help figure out the issue.

```
traceback.print_exception(e)
```

**Comment by avaris** [comment]
Did you try it with master? This should be fixed with #3257

**Comment by danrossi** [comment]
I made a typo with the subject. It looks like I should be able to pipenv github and should fix the issue then. I've installed the released version. I'll close this thanks.
