### ISSUE TITLE
Article status to gracefully ignore the file

### ISSUE THREAD

**Issue by GiovanH** [getpelican/pelican#3304]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [x] I am willing to lend a hand to help implement this feature. 

## Feature Request

Currently, there are only three valid statuses: 'published', 'hidden', and 'draft'. If an article has a status that isn't in that list, it is ignored completely and an error is reported. Otherwise, it is processed in some way and a file of some variety is output.

I would like to add a status, titled something like "ignored", that mimics the behavior of an invalid status (not publishing the file at all) but does not throw an error at runtime. 

There are some files that I want to work on in my drafts, but are sensitive enough that I don't want the files published at all, even unlisted, so I currently use "invalid statuses" to prevent this, but it's a hacky solution. Looking at the documentation, it seems the only metadata configuration that results in the "skip" behavior I want is an invalid status.

**Comment by GeorgeHu6** [comment]
Actually, it will be a nice enhancement! I have exactly a need for such a status recently. :)
