### ISSUE TITLE
Unable to add Documentation-type bug

### ISSUE THREAD

**Issue by egberts** [getpelican/pelican#3341]
- [X ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

## Issue

Was attempting to add the following to [pelican/Wiki/Tip n Tricks](https://github.com/getpelican/pelican/wiki/Tips-n-Tricks) but Github froze (or perhaps I did not have privilege to update Wiki):

## Debugging Pelican

go to the directory where the `pelicanconf.py` or 
`publishconf.py` file is located, execute:
```bash
cd pelican
```

Edit pelicanconf.py (or trouble Python script file)
and insert a breakpoint for the Python debugger
```bash
vi pelicanconf.py
```
And add a line
```Python
breakpoint()
```
Save file and exit editor.

Set Pelican for debug mode, execute:
```bash
pelican -v -v -v -v -v -D -s pelicanconf.py 
```
A debugger prompt then appears:
```console
(Pdb)
```
For help with `Pdb`, enter in `help` as a command:
```console
(Pdb) help

Documented commands (type help <topic>):
========================================
EOF    c          d        h         list      q        rv       undisplay
a      cl         debug    help      ll        quit     s        unt      
alias  clear      disable  ignore    longlist  r        source   until    
args   commands   display  interact  n         restart  step     up       
b      condition  down     j         next      return   tbreak   w        
break  cont       enable   jump      p         retval   u        whatis   
bt     continue   exit     l         pp        run      unalias  where    

Miscellaneous help topics:
==========================
exec  pdb

(Pdb) 
```

**Comment by egberts** [comment]
It's two issues:

* Unable to add Documentation-type bug (just click green button, nothing).
* Unable to append to 'Tips n Tricks' Wiki sidebar page.

**Comment by justinmayer** [comment]
I'm sorry, Egbert, but I cannot reproduce either of the issues you mentioned. From the [new issue type selection page](https://github.com/getpelican/pelican/issues/new/choose), if I tap the "Get Started" button next to "Documentation", I see the usual form with fields to add a title and a description.

Similarly, I was able to edit the _Tips n Tricks_ wiki page without any problems, as you can see from the [edit history](https://github.com/getpelican/pelican/wiki/Tips-n-Tricks/_history).

Maybe it could have been a temporary GitHub-related problem, or perhaps a localized issue with your environment. May I suggest trying again with a different browser?

**Comment by egberts** [comment]
Must be transient.  Wiki is working.  Haven't tried Feature-specific Issue yet.
