### ISSUE TITLE
Pelican theme contains advertisements

### ISSUE THREAD

**Issue by scpedicini** [getpelican/pelican#3361]
I grabbed the entire pelican theme repo and noticed that one of the themes `Casper2Pelican` seems to have ads embedded inside of it - its probably worth removing from the repo.

![CleanShot 2024-07-07 at 12 02 35@2x](https://github.com/getpelican/pelican/assets/2040540/36804e16-d7fe-4ed7-afee-cd9bbe72b0ae)

**Comment by justinmayer** [comment]
Hi Shaun. Thank you for letting us know. Removed via: https://github.com/getpelican/pelican-themes/commit/cb986aa432759233dee963c1430ab502ac57dbec

In the future, the [Pelican Themes repository](https://github.com/getpelican/pelican-themes) would be the best place for any theme-related issues. Thanks again!
