### ISSUE TITLE
CJK filename output

### ISSUE THREAD

**Issue by GeorgeHu6** [getpelican/pelican#3383]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

How can I change the output html filename from pinyin to urlencode like "%xx%xx" when I use Chinese in Markdown filename?

Do I need to implement a customed "Writer"?

**Comment by SnDream** [comment]
As the content of your question is related to Chinese, please allow me to answer it directly in Chinese.

我也在学习使用Pelican，不得不说很多东西还是检查代码内容比较合适。
文件名的输出和 `slugify()` 有关系，里面可以查到一个参数 `SLUGIFY_USE_UNICODE` 。参数默认是 False 。在pelicanconf.py 中配置为 True 后可以达到你预期的效果。

另外，查阅文档的 Settings 章节，相关的还有 `SLUGIFY_SOURCE` 和 `SLUGIFY_PRESERVE_CASE` 参数。

**Comment by GeorgeHu6** [comment]
It works perfectly! Thanks a lot for your help. 😄
