### ISSUE TITLE
Cannot modify or over-ride footnote layout

### ISSUE THREAD

**Issue by Kentoseth** [getpelican/pelican#3390]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.

## Issue

This is not a theme-related question. My theme (Flex) does not have any rendering for footnotes, but somehow (using Markdown and the `[^1]` format), footnotes are displayed under my content.

The issue is that I am unable to over-ride the design/layout of the footnotes section. I simply want to put a title saying `###Footnotes` before the footnotes, but I don't know how to over-ride the settings. See below for the display:

![fn-bug](https://github.com/user-attachments/assets/aaa13b95-6794-4c88-81e1-6d365dbfb97c)

Here is what AI suggested I try in `article.html` (but didn't work):
```python
...
  <div>
    {{ article.content }}
  </div>

  {% if article.footnotes %}
  <div class="footnote">
    <h3>Footnotes</h3>
    <ol class="footnotes">
        {% for footnote in article.footnotes %}
        <li id="{{ footnote.id }}">{{ footnote.content }}
            <a class="footnote-back" href="#{{ footnote.backlink }}">↩</a>
        </li>
        {% endfor %}
    </ol>
  </div>
  {% endif %}
```

**Comment by justinmayer** [comment]
Hi @Kentoseth. Unfortunately, there is not enough information here to provide any assistance. I suggest following the instructions in the [How to Get Help](https://docs.getpelican.com/en/latest/contribute.html#how-to-get-help) section of the Pelican documentation. Alternatively, you can try the [Simple Footnotes](https://github.com/pelican-plugins/simple-footnotes) plugin and see if that provides a workable solution for you.

**Comment by justinmayer** [comment]
Feel free to provide the necessary additional information, at which point this can be re-opened. In the future, please use the [Discussions](https://github.com/getpelican/pelican/discussions) section for anything other than reproducible bug reports. Thanks!
