### ISSUE TITLE
Build test failures in GitHub CI workflow

### ISSUE THREAD

**Issue by justinmayer** [getpelican/pelican#3393]
It seems that GitHub CI suddenly started reporting that the `build` workflow job is failing:

➡️ https://github.com/getpelican/pelican/actions/runs/10884761305/job/30200770169

Only moments before, this job passed without problems. The only subsequent change was me pushing a `RELEASE.md` file in order to publish a new Pelican release.

@lioman: As the author of this CI job, could you take a look and shed some light on what might be happening here?

**Comment by lioman** [comment]
Will have a look

**Comment by lioman** [comment]
@justinmayer made a quick fix. Perhaps one could solve that differently by pulling the version from `pyproject.toml`. To unblock the build I thought the quicker version is the best approach now.

**Comment by lioman** [comment]
And I made that alternative approach here: #3396 

So both should fix those issues.
