### ISSUE TITLE
Schedules all running at multiple times tho most are not set for that.

### ISSUE THREAD

**Issue by BrianDLC** [getpelican/pelican#3400]
- [x] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: Ubuntu 24.04
- **Python version**: 3.12.3 
- **Pelican version**: 1.0.0-beta10
- **Link to your site**: panel.apoc.wtf
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**: 

## Issue

Schedules seem to run twice at two different times, today I was able to notice all schedules run at other times, I had set up an alarm to run every 3 hours, another to run at 0 0 * * * and another to run at */3, which would be every 3 hours, all 3 ran at the same time at 0 UTC. The 0 0 * * * schedule ran at 4PM and again at 8PM (it should run at 8PM), after it ran again at 8PM, it claims the next scheduled run time is at 4PM, meaning it'll most likely run at 4PM and 8PM again the next day. I did have this issue a month ago and had more information but decided to turn off all schedules due to wanting to progress on a game server.

The issue persists, If I run a schedule it will run at the time I designated and at another time around 4 hours before the scheduled time. I do not understand how to troubleshoot this and would love some assistance.

![image](https://github.com/user-attachments/assets/2f46451f-f167-4b18-8331-42a90087c90d)

**Comment by justinmayer** [comment]
I do not see anything here that relates to Pelican, which is a static site generator. I don't know which repository this issue was intended for, but this is almost certainly not the right place for it.
