### ISSUE TITLE
`webassets` dependency appears to be abandonware

### ISSUE THREAD

**Issue by phlax** [getpelican/pelican#3417]
PRs and issues are ignored in the webassets repo - upstream issue added here https://github.com/miracle2k/webassets/issues/554

questions below: N/A

- [ ] I have read the [Filing Issues](https://docs.getpelican.com/en/latest/contribute.html#filing-issues) and subsequent “How to Get Help” sections of the documentation.
- [ ] I can reproduce this problem with stock/default settings file, theme, and sample content (as described in above “How to Get Help” sections of the documentation).
- [ ] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.

- **OS version and name**: 
- **Python version**: 
- **Pelican version**: 
- **Link to theme**: 
- **Links to plugins**: 
- **Link to your site**: 
- **Link to your source**: 
- **Link to a [Gist](https://gist.github.com/) with the contents of your settings file**:

**Comment by jdpoccorie** [comment]
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by justinmayer** [comment]
Hi @phlax. A few things, in no particular order:

- I can emphasize with how frustrating it can be when projects appear to be abandoned.
- The `webassets` repository you referenced is not a Pelican “dependency”, but rather a 3rd-party plugin that is wholly unrelated to this Pelican core repository.
- This Pelican core repository previously contained some plugins, one of which (`assets`) was eventually moved to the [Pelican Plugins repository](https://github.com/getpelican/pelican-plugins) (now deprecated), and then subsequently moved to its own repository under the [Pelican Plugins organization](https://github.com/pelican-plugins) under the name [`webassets`](https://github.com/pelican-plugins/webassets).
- The aforementioned [`webassets`](https://github.com/pelican-plugins/webassets) plugin may or may not have any relation to the identically-named plugin repository you referenced.
- If there are features in the identically-named plugin repository you referenced that do not exist in the [`webassets`](https://github.com/pelican-plugins/webassets) plugin, my suggestion is to submit pull requests to the latter repository that implement those desired features, as the [`webassets`](https://github.com/pelican-plugins/webassets) plugin repository is actively maintained.
- If there is any further discussion warranted, let's do that in the relevant issue I just created for that purpose: https://github.com/miracle2k/webassets/issues/555

**Comment by phlax** [comment]
thanks for the follow up @justinmayer 

i wasnt aware that there was an ~official webassets other than the one i am using - not sure how/why i have that setup, but will check and update

mostly i was checking our deps are supported

thanks again

**Comment by justinmayer** [comment]
I wouldn’t go so far as to call that plugin “official”, but at least it is under an organization with multiple maintainers and is more actively monitored and maintained.

**Comment by phlax** [comment]
hmm - checking - and it seems that pelican-webassets is pulling in the linked webassets as a dep

https://github.com/pelican-plugins/webassets/blob/17faf0dcf94a165555109b58bd09fabb1decaa61/pyproject.toml#L40

which points back to the webassets repo mentioned - https://pypi.org/project/webassets/

am i misunderstanding something?

**Comment by justinmayer** [comment]
Please see related discussion at: https://github.com/miracle2k/webassets/pull/553

**Comment by justinmayer** [comment]
The unmaintained `webassets` library has been vendored into the identically-named Pelican plugin, which you can get from: https://github.com/pelican-plugins/webassets/releases
