### ISSUE TITLE
Support single column output for pelican object ls

### ISSUE THREAD

**Issue by stuartthebruce** [getpelican/pelican#3437]
- [x] I have searched the [issues](https://github.com/getpelican/pelican/issues?q=is%3Aissue) (including closed ones) and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://docs.getpelican.com/) and believe that my question is not covered.
- [ ] I am willing to lend a hand to help implement this feature. 

## Feature Request

It would be nice if `pelican object ls` had the ability to generate single column output to pipe into other programs like `sort` and `parallel`.

For bonus points this would follow the heuristics and options used bin Linux `/bin/ls`.

**Comment by stuartthebruce** [comment]
My bad--wrong Pelican project.

**Comment by justinmayer** [comment]
No worries. Happy holidays.
