### ISSUE TITLE
Add metadata for custom page ordering

### ISSUE THREAD

**Issue by onlyhavecans** [getpelican/pelican#420]
raignarok in IRC gave me this idea for this feature so I am documenting it.
- A `:page-order: #` metadata for pages
- Any `page-order` metadata that doesn't cast properly to a number throws a warning and discards the metadata
- Pages with the `page-order` metadata go first in the list, sorted in ascending numerically.
- If there is multiple pages with the same order # then they will be sorted by alpha slug
- Any pages missing an order # goes at the end of the list alpha-slug just like before to keep compatibility.

This will probably go nicely with #400 and #220 since pages and the location of articles will be way more flexible.

**Comment by arqeco** [comment]
It may sounds exaggerated, but this is a HUGE improvement to non-blog site projects in Pelican. This feature deserves a better explanation in the docs, maybe a full paragraph.Thank you very much!

**Comment by newptcai** [comment]
I gave this a try and it didn't work! Then I realized that is because the template which I am using also sort the pages!
