### ISSUE TITLE
Possible Error in MakeFile for ftp upload

### ISSUE THREAD

**Issue by patrickwelker** [getpelican/pelican#444]
I don't know if anyone else had this problem, but  in the quickstart setup I checked "No" when asked:

Do you want to upload your website using SSH ?

So the Makefile renders like this:

```
lftp ftp://$(FTP_USER)@$(FTP_HOST) -e "mirror -R $(OUTPUTDIR) $(FTP_TARGET_DIR) ; quit"
```

When triggering _make ftp_upload_ I get the follow error due to faulty SSL permissions:

```
mirror: Fatal error: Certificate verification: subjectAltName does not match ‘blogname.com’
```

I posted a question on [StackExchange](http://serverfault.com/questions/411970/how-to-avoid-lftp-certificate-verification-error) about how to avoid the SSL check (because I did it the wrong way), so here's the result which should work splendid:

```
lftp ftp://$(FTP_USER)@$(FTP_HOST) -e "set ftp:ssl-allow no; mirror -R $(OUTPUTDIR) $(FTP_TARGET_DIR) ; quit"
```

**Comment by SenaidaHdez** [comment]
I had a similar problem. The error message was:
> mirror: Fatal error: Certificate verification: certificate common name doesn't match requested host name

 I found a way around that seems to be safe. You can specifically set your website as an exception for the checking of the hostname in the rc file within the .lftp folder. Specifically, you can create the rc file and add the lines:

`set ssl:check-hostname/example.com no
set ssl:check-hostname true`

Then, you substitutle example.com for your website and paste the file into the .lftp folder.
That worked to me.


Hope it is useful.
