### ISSUE TITLE
status:draft for pages

### ISSUE THREAD

**Issue by andreasio** [getpelican/pelican#456]
This is very much related to the upcomming 3.0 feature `hidden`. But I think `hidden` and `drafts` mean two different things. This seams to be confirmed here: https://github.com/getpelican/pelican/issues/380

But I find it inlogical that I can not draft a page? So I propose to add `status:draft` for pages as well as for articles.

**Comment by justinmayer** [comment]
This issue was finally addressed by @oulenz. Thank you! 🙏🏻
