### ISSUE TITLE
404 page that inherits base.html

### ISSUE THREAD

**Issue by lucassmagal** [getpelican/pelican#492]
Hello,

I need create a custom 404 page that inherits base.html. How can I do it?

**Comment by shrayasr** [comment]
@justinmayer FWIW I think adding a 404 page in the default templates that ship with pelican would be great as it gives an idea of how these things can be achieved.

**Comment by justinmayer** [comment]
A 404 page usually doesn't have different layout than any other page (only the content is different), so I'm not sure that it would need its own template. If anything, it should probably be done as a page that is created during the quick-start process. But that still leaves open the question of how to configure this at the web server level, which makes me wonder whether we should be doing this at all.

**Comment by shrayasr** [comment]
> A 404 page usually doesn't have different layout than any other page (only the content is different), so I'm not sure that it would need its own template.

This is true. But that information is missing IMO

> it should probably be done as a page that is created during the quick-start process.

A question saying _"Create custom 404 page? [y/N]"_ might work?

> But that still leaves open the question of how to configure this at the web server level,

Configuring this at the web server level is beyond the scope of pelican as such. So we shouldn't bother about that part, no?

> which makes me wonder whether we should be doing this at all.

One more thing we can do instead of this is to add a quick Tip in the Tips area of the docs? That might help.

**Comment by justinmayer** [comment]
Agreed. Anyone want to submit a PR adding the relevant instructions to the Tips page?

**Comment by shrayasr** [comment]
@justinmayer took a crack at it. Do check it out and give feedback. 

Thanks

**Comment by justinmayer** [comment]
Added to docs via cff5f3e and 38c307e.
