### ISSUE TITLE
Blog caching

### ISSUE THREAD

**Issue by lucassmagal** [getpelican/pelican#507]
Hello guys,

I have, finally, deployed my blog. I'm still hacking the theme, but almost everything is fine, except one thing: browser page caching.

How are you dealing with it?

**Comment by eamonnfaherty-productmadness** [comment]
+1

I am having the same issue.

I am deploying to github pages using travisci and I have to hard reload the home page to see the most up to date version.

Is there any solution to this?

**Comment by justinmayer** [comment]
@eamonnfaherty-productmadness: This doesn't have anything to do with Pelican. Moreover, what you are describing sounds, to me, the way browser caching is designed to work. I don't understand what the perceived problem is.
