### ISSUE TITLE
:status: hidden for things other than pages.

### ISSUE THREAD

**Issue by wraithan** [getpelican/pelican#519]
#380 spoke about adding a hidden status, and #389 is the pull request that added it.

I would like this for things outside of the pages directory. For example I have `content/tech/` and `content/sc2/` and I'd like to have some pages-like content for my SC2 blog. 

I am left with either: 
- `content/pages/sc2/my_content.rst` with `:status: hidden`

This works but requires putting things that rely on each other in separate directories.
- `content/sc2/my_content.rst` and using `:status: draft`

This requires me to link to `/drafts/my_content.html` and is a misuse of the draft stuff.

I'd much prefer to keep all the content for a section of my blog/site together in a single directory. If this would be accepted, I'll gladly add a pull request to make it happen.

**Comment by ashwinvis** [comment]
Note: this issue has been fixed in https://github.com/getpelican/pelican/pull/2866 via https://github.com/getpelican/pelican/commit/add3628a6474f2bd145fe2ea55c5e5255e9970ba
