### ISSUE TITLE
Add option to keep a filesystem hierarchy for pages

### ISSUE THREAD

**Issue by pachi** [getpelican/pelican#686]
The usecase is the following: being able to migrate a website with an existing directory structure.
The directory hierarchy can't be changed for SEO and other reasons.

For instance, the site has a file /news/recent/programming/newsweek20100312.htm and it could be processed as a pelican page, but currently it isn't possible to tell that the folder structure in /content/pages/ is preserved so the /news/recent/programming hierarchy could be achieved.

As a hack, I could use the category metadata changing the PAGE_SAVE_AS and PAGE_URL settings, but this only gets one more nesting level.

Proposal: Add a PRESERVE_CONTENT_HIERARCHY (= True) directive so the directory structure in content/pages/ is replicated when building pages.

**Comment by abigailhart** [comment]
AVG customer service support call technical support number 1-855-408-6697.For Activate and install your AVG Antivirus online just by visiting  http://activateavg.com

**Comment by justinmayer** [comment]
Since the answer to this question should be more visible, I documented the aforementioned solution via b8f2326.

**Comment by cup** [comment]
https://github.com/getpelican/pelican/issues/2673

**Comment by kno10** [comment]
This breaks the automatic translation system, unfortunately.
