### ISSUE TITLE
Need for Output Filters

### ISSUE THREAD

**Issue by mankyd** [getpelican/pelican#722]
I would like to write a post-processing filter that takes in the entirety html that is about to be output, modifies it, and passes it on. The current plugin system is inadequate for this purpose because it does not allow plugins to be chained in a good way. That is, you can't easily take the output of one plugin and feed it into the input of another.

Theoretically, I suppose that this could be done if a new context object of some sort was created after rendering that had one property - the html - but that seems awfully heavy handed. Whereas, all that really needs to happen is a small modification to writer.py:

    output = template.render(localcontext)

Should become something like:

    output = template.render(localcontext)
    for output_filter in output_filters:
        output = output_filter(output)

I am curious what the developers' thoughts are on this. I have tried making my change through a Jinja extension and its an absolute nightmare of complexity. Jinja also does not allow post processing, and getting my code to insert what it needs into the live token stream is all but impossible - certainly impractical.

I'd be happy to contribute a pull request that implements this feature if people are interested.

**Comment by leotrs** [comment]
This should be closed. The current plugin system allows for plugin chaining and provides many different signals.
