### ISSUE TITLE
Pagination for archive.html Vs A separate blog.html

### ISSUE THREAD

**Issue by amanjeev** [getpelican/pelican#735]
Is it a good idea to introduce pagination for archives? Pelican's default behavior is to be a blog so the pagination is only available for index.html which is the home page. I was wondering if there should be or is planned feature where you can 

Change the blog page from index.html to say blog.html?

Or 

Have pagination for the archive.html?

Update: So I thought to start developing this myself yesterday and got the development environment running so far. I am trying to go through and understand the source. Where is it preferred to ask questions if I am stuck, here, freenode or somewhere else?

**Comment by justinmayer** [comment]
Addressed via the aforementioned pull request. Well done, @oulenz!
