### ISSUE TITLE
"CRITICAL: decode() argument 1 must be string, not None" on cygwin

### ISSUE THREAD

**Issue by falconair** [getpelican/pelican#760]
I am trying to setup a blog using python through cygwin on Windows 7, 64 bit in USA locale (looks like it has something to do with locale parsing).

The stack trace is:
$ pelican posts/ -s settings.py -D
DEBUG: Adding current directory to system path
DEBUG: template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', 'analytics.html', 'archives.html', 'article.html', 'article_infos.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'comments.html', 'disqus_script.html', 'github.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'piwik.html', 'tag.html', 'taglist.html', 'tags.html', 'translations.html', 'twitter.html']
DEBUG: template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', 'analytics.html', 'archives.html', 'article.html', 'article_infos.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'comments.html', 'disqus_script.html', 'github.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'piwik.html', 'tag.html', 'taglist.html', 'tags.html', 'translations.html', 'twitter.html']
DEBUG: template list: ['!simple/archives.html', '!simple/article.html', '!simple/author.html', '!simple/base.html', '!simple/categories.html', '!simple/category.html', '!simple/gosquared.html', '!simple/index.html', '!simple/page.html', '!simple/pagination.html', '!simple/tag.html', '!simple/tags.html', '!simple/translations.html', 'analytics.html', 'archives.html', 'article.html', 'article_infos.html', 'author.html', 'authors.html', 'base.html', 'categories.html', 'category.html', 'comments.html', 'disqus_script.html', 'github.html', 'gosquared.html', 'index.html', 'page.html', 'pagination.html', 'piwik.html', 'tag.html', 'taglist.html', 'tags.html', 'translations.html', 'twitter.html']
CRITICAL: decode() argument 1 must be string, not None
Traceback (most recent call last):
  File "C:\Python27\Scripts\pelican-script.py", line 9, in <module>
    load_entry_point('pelican==3.1.1', 'console_scripts', 'pelican')()
  File "C:\Python27\lib\site-packages\pelican__init__.py", line 320, in main
    pelican.run()
  File "C:\Python27\lib\site-packages\pelican__init__.py", line 153, in run
    p.generate_context()
  File "C:\Python27\lib\site-packages\pelican\generators.py", line 355, in generate_context
    filename=f, context=self.context)
  File "C:\Python27\lib\site-packages\pelican\contents.py", line 92, in **init**
    self.locale_date = encoded_date.decode(stdin.encoding)
TypeError: decode() argument 1 must be string, not None

My settings file is (note that I added DATE_FORMATS and LOCALE only after trying to resolve this error in other ways):
$ cat settings.py
PATH = 'posts'
AUTHOR = 'Shahbaz Chaudhary'
SITENAME = 'Dev Blog'
SITEURL = 'http://falconair.github.com'
TIMEZONE = 'EASTERN'
DATE_FORMATS = { 'en': '%a, %d %b %Y' }
LOCALE = ('usa', 'en_US')

The only markdown file I am parsing is:
$ cat posts/2013/02/25/java-apis-for-socket-programming/index.md
Title: My super title
Date: 2010-12-03 10:20
Tags: thats, awesome
Category: yeah
Slug: my-super-post
Author: Alexis Metaireau
Summary: Short version for index and feeds

This is the content of my super blog post.

$ pelican --version
3.1.1

EDIT:
Forgot to add this:
$ python --version
Python 2.6.8

$ uname -a
CYGWIN_NT-6.1-WOW64 MY-Laptop 1.7.17(0.262/5/3) 2012-10-19 14:39 i686 Cygwin

**Comment by vipzrx** [comment]
i issue this command 

$ pelican-quickstart.exe

it get stuck  and after i enter "Enter"  

Welcome to pelican-quickstart v3.6.3.

This script will help you create a new Pelican-based website.

Please answer the following questions so this script can generate the files
needed by Pelican.

> Where do you want to create your new web site? [.] Traceback (most recent call last):
  File "C:\soft_install\py2710\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\soft_install\py2710\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\soft_install\py2710\Scripts\pelican-quickstart.exe\__main__.py", line 9, in <module>
  File "C:\soft_install\py2710\lib\site-packages\pelican\tools\pelican_quickstart.py", line 217, in main
    ask('Where do you want to create your new web site?', answer=str_compat, default=args.path)))
  File "C:\soft_install\py2710\lib\site-packages\pelican\tools\pelican_quickstart.py", line 77, in wrapper
    return out.decode(sys.stdin.encoding)
TypeError: decode() argument 1 must be string, not None

kk@X201 ~
$ python2.7 -c 'import sys; print(sys.stdin.encoding)'
UTF-8

kk@X201 ~
$ pelican --version
3.6.3

**Comment by vipzrx** [comment]
kk@X201 ~
$ python --version
Python 2.7.10
