### ISSUE TITLE
Support the 'align-center' CSS class in main.css

### ISSUE THREAD

**Issue by skadge** [getpelican/pelican#776]
When adding an image with the property 'align:center' in rst, the generated HTML tag is `<img class="align-center" ...>`

`main.css` should implement this class, maybe like that:

``` css

.align-center {
   display: block;
   margin: auto;
```

**Comment by alkhimey** [comment]
@justinmayer I tested mwcz suggestion with a debugger and it works as expected in the theme I use for my blog (Flex). I am not sure what CSS file I should add this into. Flexe's CSS? notmytheme's CSS? 

I do not understand the structure here. How will it work with all the themes that are available for Pelican?

**Comment by justinmayer** [comment]
> I am not sure what CSS file I should add this into. Flexe's CSS? notmyidea's CSS?

Both. Each theme has its own CSS file.
