### ISSUE TITLE
Intra-site links for draft posts

### ISSUE THREAD

**Issue by Javex** [getpelican/pelican#865]
Probably a really low-priority issue: When you link to a file that is currently under `:status: draft`, the links will not work.

```
.. _some href: |filename|my-drafted-article.rst
```

This will create a link to the article as if it was not in the drafts folder. Not a very pressing issue but a little inconsistent.

**Comment by justinmayer** [comment]
Noting that this issue has ostensibly been addressed by df54953 (see #1708).
