### ISSUE TITLE
Description and index for categories

### ISSUE THREAD

**Issue by pagiraud** [getpelican/pelican#884]
I think it would be nice to have the possibility to give a description to the categories. This description could be printed at the top of the list of the blog entries of this category. This could also be used for generating a special page with a list of the categories and their descriptions.

Four ideas to implement this : 
1. If an index.md is given with a :category: name in its header, the content of the index is considered to be the description.
2. If a file is named after a category e.g. mycat.md AND contains :category: mycat in tis header, the content of this file is considered to be the description.
3. A special file called for instance categories.md could contain all the descriptions.
4. Create a :type: keyword for the header. It's multipurpose : if you have :type: category, then the content of the file is the category description. This way subcategories can also be handled. For instance, if you have a file called mysubcat.md with in the header
:type: category
:category: mycat
It would create a mysubcat category within the mycat category.
:type: could also be used for using different templates for posts within a same category (e. g. long posts, twiit-like posts, image post, etc.)

The last one is my favorite, though.

Thank you for this great tool !

**Comment by justinmayer** [comment]
@avaris: Any updates regarding your plugin that stores additional data for a category/author/tag in a specific folder just like an article?

**Comment by leotrs** [comment]
@avaris It's been a year, and I think I saw some other plugin that did something similar.

**Comment by justinmayer** [comment]
Ostensibly resolved by the [category_meta plugin](https://github.com/getpelican/pelican-plugins/tree/master/category_meta). Issue closed.
