### ISSUE TITLE
Multiple authors for single article

### ISSUE THREAD

**Issue by peterdesmet** [getpelican/pelican#956]
I would like to add multiple authors to a single article. Using Markdown, I tried comma-separate authors in my article metadata (like you can do with tags):

```
Tags: tag1, tag2
Authors: author1, author2
```

But this generated a link to `author1-author2`, instead of 2 links to the 2 author pages. Is there another way to do this and if no, are there any plans to support this feature?

**Comment by MartinThoma** [comment]
How should mutiple authors be written in the header? I am currently writing

    Title: Paper Discussion Group
    Category: Projekte
    Date: 2015-12-02 17:30
    Tags: Paper, Deep Learning, Autonomes Fahren
    Authors: Marvin Teichmann, Martin Thoma

    The article blablalbal adfasdf adsfasdf asd

However, when I look at the generated code, I see:

    [...]
     <meta name="author" content="Marvin Teichmann" />
    [...]

So only the first person appears there.  I've expected:

    [...]
     <meta name="author" content="Marvin Teichmann, Martin Thoma" />
    [...]

Is this a bug?

**Comment by ingwinlu** [comment]
In the theme you used, yes

**Comment by MartinThoma** [comment]
I guess the relevant part is

    {% if page.author %}
        <meta name="author" content="{{ page.author }}" />
    {% else %}
        <meta name="author" content="{{ AUTHOR }}" />
    {% endif %}

I've also found [the themes docs docs](http://docs.getpelican.com/en/3.6.3/themes.html#article) and I guess it should be

    {% if page.authors %}
        <meta name="author" content="{{ page.authors | join(',') }}" />
    {% elif page.author %}
        <meta name="author" content="{{ page.author }}" />
    {% else %}
        <meta name="author" content="{{ AUTHOR }}" />
    {% endif %}

At least on a first glance, it seems to work.

What is the reason to use `author` and `authors` at the same time? Wouldn't it be better to have only `authors` so that people who write templates will see their mistake?
